/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib
open Real Set MeasureTheory

noncomputable section

namespace ODEFlow

/-- A spacetime point in $\mathbb{R}^{1+n}$. -/
abbrev Spacetime (n : ℕ) := Fin (n + 1) → ℝ

/-- A real-valued scalar field on $\mathbb{R}^{1+n}$. -/
abbrev ScalarField (n : ℕ) := Spacetime n → ℝ

/-- A vector field on $\mathbb{R}^{1+n}$, i.e. a map from spacetime points to vectors. -/
abbrev VectorField (n : ℕ) := Spacetime n → Spacetime n

/-- A spacetime metric: at each point of $\mathbb{R}^{1+n}$, a function
$m_{\mu\nu}$ on pairs of indices. -/
abbrev Metric (n : ℕ) := Spacetime n → Fin (n + 1) → Fin (n + 1) → ℝ

/-- The spacetime gradient of a scalar field $\varphi$: the index-$\mu$ component
is the partial derivative $\partial_\mu \varphi$. -/
def spacetimeGradient {n : ℕ} (φ : ScalarField n) (x : Spacetime n) : Fin (n + 1) → ℝ :=
  fun μ => fderiv ℝ φ x (Pi.single μ 1)

/-- The Jacobian of a map $F : \mathbb{R}^{1+n} \to \mathbb{R}^{1+n}$ at $x$:
$(\partial F^\mu / \partial x^\nu)(x)$. -/
def jacobian {n : ℕ} (F : Spacetime n → Spacetime n) (x : Spacetime n) :
    Fin (n + 1) → Fin (n + 1) → ℝ :=
  fun μ ν => fderiv ℝ (fun y => F y μ) x (Pi.single ν 1)

/-- The Kronecker delta $\delta_{\mu\nu}$, equal to $1$ if $\mu = \nu$ and $0$ otherwise. -/
def kroneckerDelta (n : ℕ) (μ ν : Fin (n + 1)) : ℝ :=
  if μ = ν then 1 else 0

/-- The (spacetime) divergence of a vector field $Y$: $\nabla \cdot Y = \sum_\alpha \partial_\alpha Y^\alpha$. -/
def divergence {n : ℕ} (Y : VectorField n) (x : Spacetime n) : ℝ :=
  ∑ α : Fin (n + 1), jacobian Y x α α

/-- The Jacobian of a spacetime map packaged as a matrix. -/
def jacobianMatrix {n : ℕ} (G : Spacetime n → Spacetime n) (x : Spacetime n) :
    Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ :=
  Matrix.of (jacobian G x)

/-- A vector field $Y$ has all partial derivatives uniformly bounded by $C > 0$:
$|\partial_\mu Y^\nu(x)| \leq C$ for all $x, \mu, \nu$. -/
def HasBoundedDerivatives {n : ℕ} (Y : VectorField n) (C : ℝ) : Prop :=
  0 < C ∧ ∀ (x : Spacetime n) (μ ν : Fin (n + 1)),
    |fderiv ℝ (fun y => Y y ν) x (Pi.single μ 1)| ≤ C

/-- Data packaging the ODE flow generated by a vector field $Y$ on spacetime
$\mathbb{R}^{1+n}$ (Proposition 2.0.1): the flow map $F_\epsilon$ on
$[-\epsilon_0, \epsilon_0]$, its smoothness, the one-parameter group properties,
the Taylor expansion, and the corresponding expansion of the Jacobian. -/
structure FlowMapData (n : ℕ) where
  Y : VectorField n
  Y_smooth : ContDiff ℝ ⊤ Y
  C_bound : ℝ
  Y_bounded : HasBoundedDerivatives Y C_bound
  F : ℝ → Spacetime n → Spacetime n
  ε₀ : ℝ
  ε₀_pos : 0 < ε₀
  F_smooth : ∀ ε, |ε| ≤ ε₀ → ContDiff ℝ ⊤ (F ε)
  F_ode : ∀ (x : Spacetime n) (μ : Fin (n + 1)) (ε : ℝ), |ε| ≤ ε₀ →
    deriv (fun ε' => F ε' x μ) ε = Y (F ε x) μ
  F_initial : ∀ x : Spacetime n, F 0 x = x
  F_inverse : ∀ ε, |ε| ≤ ε₀ → ∀ x, F (-ε) (F ε x) = x
  F_group : ∀ ε₁ ε₂, |ε₁| + |ε₂| ≤ ε₀ → ∀ x, F ε₁ (F ε₂ x) = F (ε₁ + ε₂) x
  F_commutative : ∀ ε₁ ε₂, |ε₁| + |ε₂| ≤ ε₀ → ∀ x, F ε₂ (F ε₁ x) = F (ε₁ + ε₂) x
  R : ℝ → Spacetime n → Spacetime n
  R_smooth : ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n => R p.1 p.2)
  F_taylor : ∀ ε x μ, F ε x μ = x μ + ε * Y x μ + ε ^ 2 * R ε x μ
  jacobian_expansion : ∀ ε, |ε| ≤ ε₀ → ∀ x μ ν,
    jacobian (F ε) x μ ν =
      kroneckerDelta n μ ν + ε * jacobian Y x μ ν + ε ^ 2 * jacobian (R ε) x μ ν

/-- Transformation of a scalar field under a change of coordinates:
$\widetilde{\varphi}(\widetilde{x}) = \varphi(F^{-1}(\widetilde{x}))$
(cf. Definition 2.0.6). -/
def transformScalar {n : ℕ} (φ : ScalarField n)
    (Finv : Spacetime n → Spacetime n) : ScalarField n :=
  fun xt => φ (Finv xt)

/-- Transformation of the spacetime gradient of a scalar field under a change of
coordinates (Definition 2.0.6):
$\widetilde{\nabla}_\mu \widetilde{\varphi} = (M^{-1})_\mu{}^\alpha \nabla_\alpha \varphi$,
expressed using the Jacobian of $F^{-1}$. -/
def transformGradient {n : ℕ} (φ : ScalarField n)
    (Finv : Spacetime n → Spacetime n) (xt : Spacetime n) :
    Fin (n + 1) → ℝ :=
  fun μ => ∑ α : Fin (n + 1),
    jacobian Finv xt α μ * spacetimeGradient φ (Finv xt) α

/-- Transformation of a metric under a change of coordinates (Definition 2.0.6):
$\widetilde{m}_{\mu\nu} = (M^{-1})_\mu{}^\alpha (M^{-1})_\nu{}^\beta m_{\alpha\beta}$,
expressed using the Jacobian of $F^{-1}$. -/
def transformMetric {n : ℕ} (m : Metric n)
    (Finv : Spacetime n → Spacetime n) : Metric n :=
  fun xt μ ν => ∑ α : Fin (n + 1), ∑ β : Fin (n + 1),
    jacobian Finv xt α μ * jacobian Finv xt β ν * m (Finv xt) α β

/-- A Lagrangian as a function of $(\varphi, \nabla \varphi, m)$:
the scalar field value, its gradient, and the metric components. -/
def MetricLagrangian (n : ℕ) :=
  ℝ → (Fin (n + 1) → ℝ) → (Fin (n + 1) → Fin (n + 1) → ℝ) → ℝ

/-- A Lagrangian $\mathcal{L}(\varphi, \nabla \varphi, m)$ is coordinate invariant
(Definition 2.0.7) if for every smooth diffeomorphism $\Psi$ and every scalar field
$\varphi$ and metric $m$, the value $\mathcal{L}$ evaluated on the original fields at
$x$ equals $\mathcal{L}$ evaluated on the transformed fields at $\widetilde{x} = \Psi(x)$. -/
def IsCoordinateInvariant {n : ℕ} (L : MetricLagrangian n) : Prop :=
  ∀ (Fmap Finv : Spacetime n → Spacetime n),
    (∀ x, Finv (Fmap x) = x) →
    (∀ xt, Fmap (Finv xt) = xt) →
    ContDiff ℝ ⊤ Fmap →
    ContDiff ℝ ⊤ Finv →
    ∀ (φ : ScalarField n) (m : Metric n) (x : Spacetime n),
      let xt := Fmap x
      L (φ x) (spacetimeGradient φ x) (m x) =
      L (transformScalar φ Finv xt)
        (transformGradient φ Finv xt)
        (transformMetric m Finv xt)

end ODEFlow
