/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.IntroductionToPartialDifferentialEquations.code.CM18.LagrangianMechanics

open Real Set MeasureTheory

noncomputable section

namespace CM18

/-- A metric on $(1+n)$-dimensional spacetime: a function assigning to each spacetime point $x$ a
matrix of components $m_{\mu\nu}(x)$ for $\mu,\nu \in \{0,1,\dots,n\}$. -/
abbrev Metric (n : ℕ) := Spacetime n → Fin (n + 1) → Fin (n + 1) → ℝ

/-- An inverse metric on $(1+n)$-dimensional spacetime: a function assigning to each spacetime
point $x$ a matrix of components $(m^{-1})^{\mu\nu}(x)$ for $\mu,\nu \in \{0,1,\dots,n\}$. -/
abbrev InverseMetric (n : ℕ) := Spacetime n → Fin (n + 1) → Fin (n + 1) → ℝ

/-- A metric Lagrangian $\mathcal{L}(\phi, \nabla\phi, m)$: a function of a scalar value, a
gradient covector, and a metric matrix, returning a real number. This is the type of Lagrangian
considered in CM18 Section 2 (coordinate-invariant Lagrangians). -/
def MetricLagrangian (n : ℕ) :=
  (φ_val : ℝ) → (gradient : Fin (n + 1) → ℝ) → (metric : Fin (n + 1) → Fin (n + 1) → ℝ) → ℝ

/-- Evaluate a metric Lagrangian on a scalar field $\phi$ and metric $m$ at a spacetime point $x$,
producing $\mathcal{L}(\phi(x), \nabla\phi(x), m(x))$. -/
def MetricLagrangian.eval {n : ℕ} (L : MetricLagrangian n)
    (φ : ScalarField n) (m : Metric n) (x : Spacetime n) : ℝ :=
  L (φ x) (spacetimeGradient φ x) (m x)

/-- A one-parameter flow on spacetime generated by a smooth vector field $Y$.
The map $F_\epsilon : \text{Spacetime} \to \text{Spacetime}$ satisfies $F_0 = \mathrm{id}$,
$F_{-\epsilon} \circ F_\epsilon = \mathrm{id}$, and $\frac{d}{ds}F_s(x) = Y(F_s(x))$.
This corresponds to the diffeomorphism family of CM18 Proposition 2.0.1. -/
structure FlowMap (n : ℕ) where
  F : ℝ → Spacetime n → Spacetime n
  Y : Spacetime n → Spacetime n
  F_zero : ∀ x, F 0 x = x
  F_smooth_eps : ∀ x, ContDiff ℝ ⊤ (fun ε => F ε x)
  F_inv : ∀ ε x, F (-ε) (F ε x) = x
  F_flow : ∀ ε x, deriv (fun s => F s x) ε = Y (F ε x)
  F_smooth_joint : ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n => F p.1 p.2)
  Y_smooth : ContDiff ℝ ⊤ Y

/-- The $(\mu,\nu)$-component of the Jacobian matrix
$M^\mu_{\ \nu} = \partial \widetilde{x}^\mu / \partial x^\nu$
of the flow map $F_\epsilon$ evaluated at $x$. -/
def FlowMap.jacobian {n : ℕ} (Psi : FlowMap n) (eps : ℝ) (x : Spacetime n)
    (mu nu : Fin (n + 1)) : ℝ :=
  fderiv ℝ (fun y => Psi.F eps y mu) x (Pi.single nu 1)

/-- The $(\mu,\nu)$-component of the inverse-Jacobian matrix
$(M^{-1})^\mu_{\ \nu} = \partial x^\mu / \partial \widetilde{x}^\nu$,
defined as the Jacobian of $F_{-\epsilon}$ at $\widetilde{x}$. -/
def FlowMap.invJacobian {n : ℕ} (Psi : FlowMap n) (eps : ℝ) (xt : Spacetime n)
    (mu nu : Fin (n + 1)) : ℝ :=
  fderiv ℝ (fun z => Psi.F (-eps) z mu) xt (Pi.single nu 1)

/-- The transformed scalar field $\widetilde{\phi}(\widetilde{x}) := \phi(F_{-\epsilon}(\widetilde{x}))$
from CM18 Definition 2.0.6. -/
def transformedField {n : ℕ} (Psi : FlowMap n) (phi : ScalarField n)
    (eps : ℝ) (xt : Spacetime n) : ℝ :=
  phi (Psi.F (-eps) xt)

/-- The transformed gradient
$\widetilde{\nabla}_\mu \widetilde{\phi}(\widetilde{x})
  := (M^{-1})^\alpha_{\ \mu} \nabla_\alpha \phi(F_{-\epsilon}(\widetilde{x}))$
from CM18 Definition 2.0.6. -/
def transformedGradient {n : ℕ} (Psi : FlowMap n) (phi : ScalarField n)
    (eps : ℝ) (xt : Spacetime n) (mu : Fin (n + 1)) : ℝ :=
  ∑ alpha : Fin (n + 1),
    Psi.invJacobian eps xt alpha mu * spacetimeGradient phi (Psi.F (-eps) xt) alpha

/-- The transformed metric components
$\widetilde{m}_{\mu\nu}(\widetilde{x})
  := (M^{-1})^\alpha_{\ \mu} (M^{-1})^\beta_{\ \nu} m_{\alpha\beta}(F_{-\epsilon}(\widetilde{x}))$
from CM18 Definition 2.0.6. -/
def transformedMetric {n : ℕ} (Psi : FlowMap n) (m : Metric n)
    (eps : ℝ) (xt : Spacetime n) (mu nu : Fin (n + 1)) : ℝ :=
  ∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
    Psi.invJacobian eps xt alpha mu * Psi.invJacobian eps xt beta nu *
    m (Psi.F (-eps) xt) alpha beta

/-- The transformed inverse metric components
$(\widetilde{m}^{-1})^{\mu\nu}(\widetilde{x})
  := M^\mu_{\ \alpha} M^\nu_{\ \beta} (m^{-1})^{\alpha\beta}(F_{-\epsilon}(\widetilde{x}))$
from CM18 Definition 2.0.6. -/
def transformedInverseMetric {n : ℕ} (Psi : FlowMap n) (mInv : InverseMetric n)
    (eps : ℝ) (xt : Spacetime n) (mu nu : Fin (n + 1)) : ℝ :=
  let x := Psi.F (-eps) xt
  ∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
    Psi.jacobian eps x mu alpha * Psi.jacobian eps x nu beta * mInv x alpha beta

/-- A metric Lagrangian $\mathcal{L}$ is **coordinate invariant** (CM18 Definition 2.0.7) if for
every smooth flow $\Psi$ on spacetime,
$\mathcal{L}(\phi(x), \nabla\phi(x), m(x))
  = \mathcal{L}(\widetilde{\phi}(\widetilde{x}),
      \widetilde{\nabla}\widetilde{\phi}(\widetilde{x}),
      \widetilde{m}(\widetilde{x}))$
where the transformed fields are as in Definition 2.0.6 and $x = F_{-\epsilon}(\widetilde{x})$. -/
def IsCoordinateInvariant {n : ℕ} (L : MetricLagrangian n) : Prop :=
  ∀ (Psi : FlowMap n) (phi : ScalarField n) (m : Metric n) (eps : ℝ)
    (xt : Spacetime n),
    let x := Psi.F (-eps) xt

    L (phi x) (spacetimeGradient phi x) (m x) =


    L (transformedField Psi phi eps xt)
      (fun mu => transformedGradient Psi phi eps xt mu)
      (fun mu nu => transformedMetric Psi m eps xt mu nu)

/-- Chain rule along the inverse flow: for a smooth scalar function $f$,
$\left.\partial_\epsilon\right|_{\epsilon=0} f(F_{-\epsilon}(\widetilde{x}))
  = -Y^\alpha(\widetilde{x}) \, \nabla_\alpha f(\widetilde{x})$.
This is the scalar case of CM18 Proposition 2.0.2. -/
theorem chain_rule_scalar_along_inverse_flow {n : ℕ}
    (Psi : FlowMap n) (f : Spacetime n → ℝ)
    (hf : ContDiff ℝ ⊤ f) (xt : Spacetime n) :
    deriv (fun eps => f (Psi.F (-eps) xt)) 0 =
      -(∑ alpha : Fin (n + 1), Psi.Y xt alpha * spacetimeGradient f xt alpha) := by

  have hg : HasDerivAt (fun eps => Psi.F (-eps) xt) ((-1 : ℝ) • Psi.Y xt) 0 := by
    have hF : HasDerivAt (fun s => Psi.F s xt) (Psi.Y xt) 0 := by
      have hd : DifferentiableAt ℝ (fun s => Psi.F s xt) 0 :=
        ((Psi.F_smooth_eps xt).differentiable (WithTop.top_ne_zero)).differentiableAt
      rw [← show deriv (fun s => Psi.F s xt) 0 = Psi.Y xt from by
        rw [Psi.F_flow 0 xt, Psi.F_zero xt]]
      exact hd.hasDerivAt
    have hNeg : HasDerivAt Neg.neg (-1 : ℝ) (0 : ℝ) := hasDerivAt_neg 0
    have h0 : Neg.neg (0 : ℝ) = 0 := neg_zero
    rw [← h0] at hF
    exact hF.scomp 0 hNeg

  have hf_fderiv : HasFDerivAt f (fderiv ℝ f xt) xt :=
    (hf.differentiable (WithTop.top_ne_zero)).differentiableAt.hasFDerivAt

  have hg0 : Psi.F (-(0 : ℝ)) xt = xt := by simp [Psi.F_zero]
  have hf_at_g0 : HasFDerivAt f (fderiv ℝ f xt) (Psi.F (-(0 : ℝ)) xt) := by
    rw [hg0]; exact hf_fderiv
  have hchain : HasDerivAt (fun eps => f (Psi.F (-eps) xt))
      ((fderiv ℝ f xt) ((-1 : ℝ) • Psi.Y xt)) 0 :=
    hf_at_g0.comp_hasDerivAt 0 hg

  rw [hchain.deriv, ContinuousLinearMap.map_smul, smul_eq_mul, neg_one_mul]

  congr 1

  conv_lhs =>
    rw [show Psi.Y xt = ∑ alpha : Fin (n + 1),
        (Psi.Y xt alpha) • (Pi.single alpha (1 : ℝ) : Fin (n + 1) → ℝ) from by
      ext i; simp [Finset.sum_apply, Pi.single_apply, smul_eq_mul, mul_one]]
  rw [map_sum]
  congr 1; ext alpha
  rw [ContinuousLinearMap.map_smul, smul_eq_mul, spacetimeGradient]

/-- CM18 Proposition 2.0.2, scalar part: the $\epsilon$-derivative at $\epsilon=0$ of the
transformed field equals $-Y^\alpha \nabla_\alpha \phi$. -/
theorem flow_deriv_scalar {n : ℕ} (Psi : FlowMap n) (phi : ScalarField n)
    (hphi : ContDiff ℝ ⊤ phi) (xt : Spacetime n) :
    deriv (fun eps => transformedField Psi phi eps xt) 0 =
      -(∑ alpha : Fin (n + 1), Psi.Y xt alpha * spacetimeGradient phi xt alpha) := by
  exact chain_rule_scalar_along_inverse_flow Psi phi hphi xt

/-- At $\epsilon = 0$, the inverse Jacobian reduces to the Kronecker delta
$(M^{-1})^\alpha_{\ \mu}|_{\epsilon=0} = \delta^\alpha_{\ \mu}$. -/
lemma invJacobian_zero {n : ℕ} (Psi : FlowMap n) (xt : Spacetime n)
    (alpha mu : Fin (n + 1)) :
    Psi.invJacobian 0 xt alpha mu = if alpha = mu then 1 else 0 := by
  unfold FlowMap.invJacobian
  simp only [neg_zero]
  have h0 : (fun z => Psi.F 0 z alpha) = (fun z : Spacetime n => z alpha) := by
    ext z; simp [Psi.F_zero z]
  rw [h0, (hasFDerivAt_apply alpha xt).fderiv]
  simp [ContinuousLinearMap.proj_apply, Pi.single_apply]

/-- Schwarz-type swap: for a smooth $G : \mathbb{R} \times E \to F$, the time derivative of the
partial space differential equals the space differential of the partial time derivative,
$\partial_t \, d_x G(t, x_0)\,v = d_x (\partial_t G)(x_0)\,v$. -/
theorem deriv_fderiv_swap {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    (G : ℝ × E → F) (hG : ContDiff ℝ ⊤ G)
    (t₀ : ℝ) (x₀ : E) (v : E) :
    deriv (fun t => fderiv ℝ (fun x => G (t, x)) x₀ v) t₀ =
    fderiv ℝ (fun x => deriv (fun t => G (t, x)) t₀) x₀ v := by
  have h_smooth_fG : ContDiff ℝ ⊤ (fderiv ℝ G) := hG.fderiv_right le_top
  have hfG_at : HasFDerivAt (fderiv ℝ G) (fderiv ℝ (fderiv ℝ G) (t₀, x₀)) (t₀, x₀) :=
    (h_smooth_fG.differentiable WithTop.top_ne_zero).differentiableAt.hasFDerivAt
  have hSymm : IsSymmSndFDerivAt ℝ G (t₀, x₀) :=
    hG.contDiffAt.isSymmSndFDerivAt le_top
  suffices lhs_eq : deriv (fun t => fderiv ℝ (fun x => G (t, x)) x₀ v) t₀ =
      fderiv ℝ (fderiv ℝ G) (t₀, x₀) ((1 : ℝ), (0 : E)) ((0 : ℝ), v) by
    suffices rhs_eq : fderiv ℝ (fun x => deriv (fun t => G (t, x)) t₀) x₀ v =
        fderiv ℝ (fderiv ℝ G) (t₀, x₀) ((0 : ℝ), v) ((1 : ℝ), (0 : E)) by
      rw [lhs_eq, rhs_eq, hSymm.eq]
    have h_deriv_partial : (fun x => deriv (fun t => G (t, x)) t₀) =
        (fun x => fderiv ℝ G (t₀, x) ((1 : ℝ), (0 : E))) := by
      ext x
      have h1 : HasFDerivAt G (fderiv ℝ G (t₀, x)) (t₀, x) :=
        (hG.differentiable WithTop.top_ne_zero).differentiableAt.hasFDerivAt
      have h2 : HasDerivAt (fun t => (t, x)) ((1 : ℝ), (0 : E)) t₀ := by
        simpa using (hasDerivAt_id t₀).prodMk (hasDerivAt_const t₀ x)
      exact (h1.comp_hasDerivAt t₀ h2).deriv
    rw [h_deriv_partial]
    have hprod := hasFDerivAt_prodMk_right (𝕜 := ℝ) t₀ x₀
    have h_comp : HasFDerivAt (fun x => fderiv ℝ G (t₀, x))
        ((fderiv ℝ (fderiv ℝ G) (t₀, x₀)).comp (ContinuousLinearMap.inr ℝ ℝ E)) x₀ :=
      hfG_at.comp x₀ hprod
    have h_eval : HasFDerivAt (fun x => fderiv ℝ G (t₀, x) ((1 : ℝ), (0 : E)))
        (((ContinuousLinearMap.apply ℝ F ((1 : ℝ), (0 : E))).comp
         ((fderiv ℝ (fderiv ℝ G) (t₀, x₀)).comp (ContinuousLinearMap.inr ℝ ℝ E)))) x₀ :=
      (ContinuousLinearMap.apply ℝ F ((1 : ℝ), (0 : E))).hasFDerivAt.comp x₀ h_comp
    rw [h_eval.fderiv]
    simp [ContinuousLinearMap.comp_apply, ContinuousLinearMap.apply_apply,
      ContinuousLinearMap.inr_apply]
  have h_fderiv_partial : (fun t => fderiv ℝ (fun x => G (t, x)) x₀ v) =
      (fun t => fderiv ℝ G (t, x₀) ((0 : ℝ), v)) := by
    ext t
    have h1 : HasFDerivAt G (fderiv ℝ G (t, x₀)) (t, x₀) :=
      (hG.differentiable WithTop.top_ne_zero).differentiableAt.hasFDerivAt
    have h2 := hasFDerivAt_prodMk_right (𝕜 := ℝ) t x₀
    show (fderiv ℝ (fun x => G (t, x)) x₀) v = _
    change (fderiv ℝ ((fun p => G p) ∘ (fun x => (t, x))) x₀) v = _
    rw [(h1.comp x₀ h2).fderiv, ContinuousLinearMap.comp_apply, ContinuousLinearMap.inr_apply]
  rw [h_fderiv_partial]
  have hprod : HasDerivAt (fun t => (t, x₀)) ((1 : ℝ), (0 : E)) t₀ := by
    simpa using (hasDerivAt_id t₀).prodMk (hasDerivAt_const t₀ x₀)
  have h_clm_deriv := hfG_at.comp_hasDerivAt t₀ hprod
  have h_eval := h_clm_deriv.clm_apply (hasDerivAt_const t₀ ((0 : ℝ), v))
  simp only [ContinuousLinearMap.map_zero, add_zero] at h_eval
  exact h_eval.deriv

/-- The inverse Jacobian $(M^{-1})^\alpha_{\ \mu}$ depends differentiably on $\epsilon$ at
$\epsilon = 0$. -/
lemma invJacobian_differentiableAt_zero {n : ℕ} (Psi : FlowMap n)
    (xt : Spacetime n) (alpha mu : Fin (n + 1)) :
    DifferentiableAt ℝ (fun eps => Psi.invJacobian eps xt alpha mu) 0 := by


  have huncurry : ContDiff ℝ ⊤
      (Function.uncurry (fun eps (z : Spacetime n) => Psi.F (-eps) z alpha)) := by
    show ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n => Psi.F (-p.1) p.2 alpha)
    exact (contDiff_pi.mp (Psi.F_smooth_joint.comp
      (contDiff_fst.neg.prodMk contDiff_snd))) alpha

  have hfderiv_smooth : ContDiff ℝ ⊤
      (fun eps => fderiv ℝ (fun z => Psi.F (-eps) z alpha) xt) :=
    huncurry.fderiv contDiff_const le_top

  have heval : ContDiff ℝ ⊤
      (fun eps => fderiv ℝ (fun z => Psi.F (-eps) z alpha) xt (Pi.single mu 1)) := by
    have := (ContinuousLinearMap.apply ℝ ℝ (Pi.single mu 1)).contDiff.comp hfderiv_smooth
    convert this using 1

  show DifferentiableAt ℝ (fun eps =>
    fderiv ℝ (fun z => Psi.F (-eps) z alpha) xt (Pi.single mu 1)) 0
  exact (heval.differentiable WithTop.top_ne_zero).differentiableAt

/-- The derivative of the inverse Jacobian at $\epsilon = 0$:
$\left.\partial_\epsilon\right|_{\epsilon=0} (M^{-1})^\alpha_{\ \mu}
  = -\nabla_\mu Y^\alpha$.
This expands the expansion $(M^{-1})^\mu_{\ \nu} = \delta^\mu_\nu - \epsilon \nabla_\nu Y^\mu + O(\epsilon^2)$
from CM18 Proposition 2.0.1. -/
theorem hasDerivAt_invJacobian_at_zero {n : ℕ} (Psi : FlowMap n)
    (xt : Spacetime n) (alpha mu : Fin (n + 1)) :
    HasDerivAt (fun eps => Psi.invJacobian eps xt alpha mu)
      (-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) 0 := by

  have hDiff := invJacobian_differentiableAt_zero Psi xt alpha mu
  rw [show (-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) =
    deriv (fun eps => Psi.invJacobian eps xt alpha mu) 0 from ?_]
  · exact hDiff.hasDerivAt
  ·

    set G : ℝ × Spacetime n → ℝ := fun p => Psi.F (-p.1) p.2 alpha with hG_def

    have hG_smooth : ContDiff ℝ ⊤ G := by
      show ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n => Psi.F (-p.1) p.2 alpha)
      exact (contDiff_pi.mp (Psi.F_smooth_joint.comp
        (contDiff_fst.neg.prodMk contDiff_snd))) alpha

    have h_inv_eq : ∀ eps, Psi.invJacobian eps xt alpha mu =
        fderiv ℝ (fun z => G (eps, z)) xt (Pi.single mu 1) := by
      intro eps; rfl
    simp_rw [h_inv_eq]

    rw [deriv_fderiv_swap G hG_smooth 0 xt (Pi.single mu 1)]


    have h_deriv_G : ∀ z, deriv (fun eps => G (eps, z)) 0 = -Psi.Y z alpha := by
      intro z


      have hF_diff : DifferentiableAt ℝ (fun s => Psi.F s z) 0 :=
        ((Psi.F_smooth_eps z).differentiable WithTop.top_ne_zero).differentiableAt
      have hNeg : HasDerivAt Neg.neg (-1 : ℝ) (0 : ℝ) := hasDerivAt_neg 0
      have hF_at : HasDerivAt (fun s => Psi.F s z) (Psi.Y (Psi.F 0 z)) 0 := by
        rw [← Psi.F_flow 0 z]; exact hF_diff.hasDerivAt
      rw [Psi.F_zero] at hF_at

      show deriv (fun eps => Psi.F (-eps) z alpha) 0 = -Psi.Y z alpha
      have hcomp : HasDerivAt (fun eps => Psi.F (-eps) z) ((-1 : ℝ) • Psi.Y z) 0 := by
        have h0 : Neg.neg (0 : ℝ) = 0 := neg_zero
        rw [← h0] at hF_at
        exact hF_at.scomp 0 hNeg
      have hcomp_alpha : HasDerivAt (fun eps => Psi.F (-eps) z alpha)
          (((-1 : ℝ) • Psi.Y z) alpha) 0 :=
        hasDerivAt_pi.mp hcomp alpha
      rw [hcomp_alpha.deriv]
      simp [Pi.smul_apply, smul_eq_mul]

    have hfn_eq : (fun z => deriv (fun eps => G (eps, z)) 0) = (fun z => -Psi.Y z alpha) :=
      funext h_deriv_G
    rw [hfn_eq]

    have hY_diff : DifferentiableAt ℝ (fun z => Psi.Y z alpha) xt :=
      ((contDiff_pi.mp Psi.Y_smooth alpha).differentiable WithTop.top_ne_zero).differentiableAt
    have : (fun z => -Psi.Y z alpha) = -(fun z => Psi.Y z alpha) := rfl
    rw [this, fderiv_neg]
    simp [ContinuousLinearMap.neg_apply]

/-- `HasDerivAt` version of `chain_rule_scalar_along_inverse_flow`: for a smooth scalar $g$,
the function $\epsilon \mapsto g(F_{-\epsilon}(\widetilde{x}))$ has derivative
$-Y^\alpha \nabla_\alpha g$ at $\epsilon = 0$. -/
lemma hasDerivAt_scalar_along_inverse_flow {n : ℕ}
    (Psi : FlowMap n) (g : Spacetime n → ℝ)
    (hg : ContDiff ℝ ⊤ g) (xt : Spacetime n) :
    HasDerivAt (fun eps => g (Psi.F (-eps) xt))
      (-(∑ alpha : Fin (n + 1), Psi.Y xt alpha * spacetimeGradient g xt alpha)) 0 := by
  have hg_deriv : HasDerivAt (fun eps => Psi.F (-eps) xt) ((-1 : ℝ) • Psi.Y xt) 0 := by
    have hF : HasDerivAt (fun s => Psi.F s xt) (Psi.Y xt) 0 := by
      have hd : DifferentiableAt ℝ (fun s => Psi.F s xt) 0 :=
        ((Psi.F_smooth_eps xt).differentiable (WithTop.top_ne_zero)).differentiableAt
      rw [← show deriv (fun s => Psi.F s xt) 0 = Psi.Y xt from by
        rw [Psi.F_flow 0 xt, Psi.F_zero xt]]
      exact hd.hasDerivAt
    have hNeg : HasDerivAt Neg.neg (-1 : ℝ) (0 : ℝ) := hasDerivAt_neg 0
    have h0 : Neg.neg (0 : ℝ) = 0 := neg_zero
    rw [← h0] at hF
    exact hF.scomp 0 hNeg
  have hg_fderiv : HasFDerivAt g (fderiv ℝ g xt) xt :=
    (hg.differentiable (WithTop.top_ne_zero)).differentiableAt.hasFDerivAt
  have hg0 : Psi.F (-(0 : ℝ)) xt = xt := by simp [Psi.F_zero]
  have hg_at : HasFDerivAt g (fderiv ℝ g xt) (Psi.F (-(0 : ℝ)) xt) := by
    rw [hg0]; exact hg_fderiv
  have hchain : HasDerivAt (fun eps => g (Psi.F (-eps) xt))
      ((fderiv ℝ g xt) ((-1 : ℝ) • Psi.Y xt)) 0 :=
    hg_at.comp_hasDerivAt 0 hg_deriv

  rw [show (fderiv ℝ g xt) ((-1 : ℝ) • Psi.Y xt) =
    -(∑ alpha : Fin (n + 1), Psi.Y xt alpha * spacetimeGradient g xt alpha) from by
    rw [ContinuousLinearMap.map_smul, smul_eq_mul, neg_one_mul]
    congr 1
    conv_lhs =>
      rw [show Psi.Y xt = ∑ alpha : Fin (n + 1),
          (Psi.Y xt alpha) • (Pi.single alpha (1 : ℝ) : Fin (n + 1) → ℝ) from by
        ext i; simp [Finset.sum_apply, Pi.single_apply, smul_eq_mul, mul_one]]
    rw [map_sum]
    congr 1; ext alpha
    rw [ContinuousLinearMap.map_smul, smul_eq_mul, spacetimeGradient]] at hchain
  exact hchain

/-- Leibniz-rule expansion of $\nabla_\mu (Y^\alpha \nabla_\alpha \phi)$ as a sum, used in proving
the gradient transformation rule (CM18 Proposition 2.0.2). -/
theorem fderiv_sum_Y_spacetimeGradient {n : ℕ} (Psi : FlowMap n) (phi : ScalarField n)
    (hphi : ContDiff ℝ ⊤ phi) (xt : Spacetime n) (mu : Fin (n + 1)) :
    (fderiv ℝ (fun y => ∑ alpha : Fin (n + 1),
      Psi.Y y alpha * spacetimeGradient phi y alpha) xt) (Pi.single mu 1) =
    ∑ alpha : Fin (n + 1),
      ((fderiv ℝ (fun y => Psi.Y y alpha) xt) (Pi.single mu 1) * spacetimeGradient phi xt alpha +
       Psi.Y xt alpha * spacetimeGradient (fun y => spacetimeGradient phi y alpha) xt mu) := by

  simp only [spacetimeGradient]

  have hY_comp : ∀ alpha : Fin (n + 1), DifferentiableAt ℝ (fun y => Psi.Y y alpha) xt :=
    fun alpha => ((contDiff_pi.mp Psi.Y_smooth alpha).differentiable
      WithTop.top_ne_zero).differentiableAt
  have hphi_grad : ∀ alpha : Fin (n + 1),
      DifferentiableAt ℝ (fun y => fderiv ℝ phi y (Pi.single alpha 1)) xt := by
    intro alpha
    exact ((ContinuousLinearMap.apply ℝ ℝ (Pi.single alpha 1)).differentiableAt).comp xt
      ((hphi.fderiv_right le_top).differentiable WithTop.top_ne_zero).differentiableAt
  have hprod : ∀ alpha : Fin (n + 1),
      DifferentiableAt ℝ (fun y => Psi.Y y alpha * fderiv ℝ phi y (Pi.single alpha 1)) xt :=
    fun alpha => (hY_comp alpha).mul (hphi_grad alpha)

  have heq : (fun y => ∑ alpha : Fin (n + 1),
      Psi.Y y alpha * fderiv ℝ phi y (Pi.single alpha 1)) =
    ∑ alpha : Fin (n + 1),
      (fun y => Psi.Y y alpha * fderiv ℝ phi y (Pi.single alpha 1)) := by
    ext y; simp [Finset.sum_apply]
  rw [heq, fderiv_sum (fun i _ => hprod i)]
  simp_rw [ContinuousLinearMap.sum_apply]
  congr 1; ext alpha

  have hprod_eq : (fun y => Psi.Y y alpha * fderiv ℝ phi y (Pi.single alpha 1)) =
    (fun y => Psi.Y y alpha) * (fun y => fderiv ℝ phi y (Pi.single alpha 1)) := rfl
  rw [hprod_eq, fderiv_mul (hY_comp alpha) (hphi_grad alpha)]
  simp [ContinuousLinearMap.add_apply, ContinuousLinearMap.smul_apply, smul_eq_mul]
  ring

/-- CM18 Proposition 2.0.2, gradient part: for a smooth scalar field $\phi$,
$\left.\partial_\epsilon\right|_{\epsilon=0} \widetilde{\nabla}_\mu \widetilde{\phi}
  = -\nabla_\mu(Y^\alpha \nabla_\alpha \phi)$. -/
theorem chain_rule_gradient_along_inverse_flow {n : ℕ}
    (Psi : FlowMap n) (phi : ScalarField n)
    (hphi : ContDiff ℝ ⊤ phi) (xt : Spacetime n) (mu : Fin (n + 1)) :
    deriv (fun eps => transformedGradient Psi phi eps xt mu) 0 =
      -fderiv ℝ (fun y => ∑ alpha : Fin (n + 1),
        Psi.Y y alpha * spacetimeGradient phi y alpha) xt (Pi.single mu 1) := by

  show deriv (fun eps => ∑ alpha : Fin (n + 1),
    Psi.invJacobian eps xt alpha mu * spacetimeGradient phi (Psi.F (-eps) xt) alpha) 0 = _


  have hA : ∀ alpha : Fin (n + 1),
    HasDerivAt (fun eps => Psi.invJacobian eps xt alpha mu)
      (-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) 0 :=
    fun alpha => hasDerivAt_invJacobian_at_zero Psi xt alpha mu

  have hB : ∀ alpha : Fin (n + 1),
    HasDerivAt (fun eps => spacetimeGradient phi (Psi.F (-eps) xt) alpha)
      (-(∑ beta : Fin (n + 1),
        Psi.Y xt beta * spacetimeGradient (fun y => spacetimeGradient phi y alpha) xt beta)) 0 := by
    intro alpha

    have hg : ContDiff ℝ ⊤ (fun y => spacetimeGradient phi y alpha) := by
      unfold spacetimeGradient
      exact (ContinuousLinearMap.apply ℝ ℝ (Pi.single alpha 1)).contDiff.comp
        (hphi.fderiv_right (m := ⊤) le_top)
    exact hasDerivAt_scalar_along_inverse_flow Psi (fun y => spacetimeGradient phi y alpha) hg xt

  have hAB : ∀ alpha : Fin (n + 1),
    HasDerivAt (fun eps => Psi.invJacobian eps xt alpha mu *
      spacetimeGradient phi (Psi.F (-eps) xt) alpha)
      ((-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) *
        spacetimeGradient phi (Psi.F (-(0:ℝ)) xt) alpha +
       Psi.invJacobian 0 xt alpha mu *
        (-(∑ beta : Fin (n + 1),
          Psi.Y xt beta * spacetimeGradient (fun y => spacetimeGradient phi y alpha) xt beta)))  0 :=
    fun alpha => (hA alpha).mul (hB alpha)

  have hSum : HasDerivAt (fun eps => ∑ alpha : Fin (n + 1),
      Psi.invJacobian eps xt alpha mu * spacetimeGradient phi (Psi.F (-eps) xt) alpha)
    (∑ alpha : Fin (n + 1),
      ((-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) *
        spacetimeGradient phi (Psi.F (-(0:ℝ)) xt) alpha +
       Psi.invJacobian 0 xt alpha mu *
        (-(∑ beta : Fin (n + 1),
          Psi.Y xt beta * spacetimeGradient (fun y => spacetimeGradient phi y alpha) xt beta)))) 0 := by
    have h := HasDerivAt.sum (u := Finset.univ) (fun alpha _ => hAB alpha)
    convert h using 1; ext eps; simp

  rw [hSum.deriv]

  simp only [neg_zero, Psi.F_zero]

  simp_rw [invJacobian_zero Psi xt _ mu]


  simp only [ite_mul, one_mul, zero_mul]

  rw [show (∑ x : Fin (n + 1),
      (-(fderiv ℝ (fun y => Psi.Y y x) xt) (Pi.single mu 1) * spacetimeGradient phi xt x +
        if x = mu then -∑ beta, Psi.Y xt beta *
          spacetimeGradient (fun y => spacetimeGradient phi y x) xt beta else 0)) =
    ∑ x : Fin (n + 1),
      -(fderiv ℝ (fun y => Psi.Y y x) xt) (Pi.single mu 1) * spacetimeGradient phi xt x +
    (-∑ beta, Psi.Y xt beta *
          spacetimeGradient (fun y => spacetimeGradient phi y mu) xt beta) from by
    rw [Finset.sum_add_distrib]
    congr 1
    rw [Finset.sum_ite_eq' Finset.univ mu]
    simp]

  have hSchwarz : ∀ (beta : Fin (n + 1)),
      spacetimeGradient (fun y => spacetimeGradient phi y mu) xt beta =
      spacetimeGradient (fun y => spacetimeGradient phi y beta) xt mu := by
    intro beta
    simp only [spacetimeGradient]
    have hsymm : IsSymmSndFDerivAt ℝ phi xt := by
      apply ContDiffAt.isSymmSndFDerivAt hphi.contDiffAt
      simp [minSmoothness_of_isRCLikeNormedField]
    have hdiff : DifferentiableAt ℝ (fderiv ℝ phi) xt :=
      (hphi.contDiffAt.fderiv_right le_top).differentiableAt (by exact WithTop.top_ne_zero)

    have heval : ∀ (v : Fin (n + 1) → ℝ) (w : Fin (n + 1) → ℝ),
        (fderiv ℝ (fun y => (fderiv ℝ phi y) v) xt) w =
        ((fderiv ℝ (fderiv ℝ phi) xt) w) v := by
      intro v w
      have h := fderiv_clm_apply (H := ℝ) (c := fderiv ℝ phi) (u := fun _ => v)

        hdiff (differentiableAt_const v)
      have : fderiv ℝ (fun y => (fderiv ℝ phi y) v) xt =
          (fderiv ℝ phi xt).comp (fderiv ℝ (fun _ => v) xt) + (fderiv ℝ (fderiv ℝ phi) xt).flip v := h
      rw [this]
      simp [ContinuousLinearMap.flip_apply]

    rw [heval (Pi.single mu 1) (Pi.single beta 1),
        heval (Pi.single beta 1) (Pi.single mu 1)]
    exact hsymm (Pi.single beta 1) (Pi.single mu 1)
  simp_rw [hSchwarz]

  rw [fderiv_sum_Y_spacetimeGradient Psi phi hphi xt mu]


  simp only [Finset.sum_neg_distrib, neg_mul, Finset.sum_add_distrib, neg_add_rev]
  ring

/-- Restatement of `chain_rule_gradient_along_inverse_flow` (CM18 Proposition 2.0.2, gradient
case): the $\epsilon$-derivative of the transformed gradient at $\epsilon = 0$ equals
$-\nabla_\mu(Y^\alpha \nabla_\alpha \phi)$. -/
theorem flow_deriv_gradient {n : ℕ} (Psi : FlowMap n) (phi : ScalarField n)
    (hphi : ContDiff ℝ ⊤ phi) (xt : Spacetime n) (mu : Fin (n + 1)) :
    deriv (fun eps => transformedGradient Psi phi eps xt mu) 0 =
      -fderiv ℝ (fun y => ∑ alpha : Fin (n + 1),
        Psi.Y y alpha * spacetimeGradient phi y alpha) xt (Pi.single mu 1) := by
  exact chain_rule_gradient_along_inverse_flow Psi phi hphi xt mu

/-- For a smooth metric component $m_{\alpha\beta}$, the derivative of
$\epsilon \mapsto m_{\alpha\beta}(F_{-\epsilon}(\widetilde{x}))$ at $\epsilon = 0$ is
$-Y^\gamma \nabla_\gamma m_{\alpha\beta}$. -/
lemma hasDerivAt_metric_component_along_inverse_flow {n : ℕ}
    (Psi : FlowMap n) (m : Metric n) (xt : Spacetime n)
    (alpha beta : Fin (n + 1))
    (hm : ContDiff ℝ ⊤ (fun y => m y alpha beta)) :
    HasDerivAt (fun eps => m (Psi.F (-eps) xt) alpha beta)
      (-(∑ gamma : Fin (n + 1),
        Psi.Y xt gamma * fderiv ℝ (fun y => m y alpha beta) xt (Pi.single gamma 1))) 0 :=
  hasDerivAt_scalar_along_inverse_flow Psi (fun y => m y alpha beta) hm xt

/-- CM18 Proposition 2.0.2, metric part:
$\left.\partial_\epsilon\right|_{\epsilon=0} \widetilde{m}_{\mu\nu}
  = -(m_{\alpha\nu} \nabla_\mu Y^\alpha + m_{\mu\alpha} \nabla_\nu Y^\alpha
       + Y^\alpha \nabla_\alpha m_{\mu\nu})$. -/
theorem chain_rule_metric_along_inverse_flow {n : ℕ}
    (Psi : FlowMap n) (m : Metric n) (xt : Spacetime n)
    (mu nu : Fin (n + 1))
    (hm : ∀ alpha beta, ContDiff ℝ ⊤ (fun y => m y alpha beta)) :
    deriv (fun eps => transformedMetric Psi m eps xt mu nu) 0 =
      -(∑ alpha : Fin (n + 1),
        m xt alpha nu * fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)
      + ∑ alpha : Fin (n + 1),
        m xt mu alpha * fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single nu 1)
      + ∑ alpha : Fin (n + 1),
        Psi.Y xt alpha * fderiv ℝ (fun y => m y mu nu) xt (Pi.single alpha 1)) := by

  show deriv (fun eps => ∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
    Psi.invJacobian eps xt alpha mu * Psi.invJacobian eps xt beta nu *
    m (Psi.F (-eps) xt) alpha beta) 0 = _

  have hA : ∀ alpha : Fin (n + 1),
      HasDerivAt (fun eps => Psi.invJacobian eps xt alpha mu)
        (-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) 0 :=
    fun alpha => hasDerivAt_invJacobian_at_zero Psi xt alpha mu
  have hB : ∀ beta : Fin (n + 1),
      HasDerivAt (fun eps => Psi.invJacobian eps xt beta nu)
        (-fderiv ℝ (fun y => Psi.Y y beta) xt (Pi.single nu 1)) 0 :=
    fun beta => hasDerivAt_invJacobian_at_zero Psi xt beta nu
  have hC : ∀ alpha beta : Fin (n + 1),
      HasDerivAt (fun eps => m (Psi.F (-eps) xt) alpha beta)
        (-(∑ gamma : Fin (n + 1),
          Psi.Y xt gamma * fderiv ℝ (fun y => m y alpha beta) xt (Pi.single gamma 1))) 0 :=
    fun alpha beta => hasDerivAt_metric_component_along_inverse_flow Psi m xt alpha beta (hm alpha beta)

  have hAB : ∀ alpha beta : Fin (n + 1),
      HasDerivAt (fun eps => Psi.invJacobian eps xt alpha mu * Psi.invJacobian eps xt beta nu)
        ((-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) *
          Psi.invJacobian 0 xt beta nu +
         Psi.invJacobian 0 xt alpha mu *
          (-fderiv ℝ (fun y => Psi.Y y beta) xt (Pi.single nu 1))) 0 :=
    fun alpha beta => (hA alpha).mul (hB beta)

  have hABC : ∀ alpha beta : Fin (n + 1),
      HasDerivAt (fun eps => Psi.invJacobian eps xt alpha mu * Psi.invJacobian eps xt beta nu *
        m (Psi.F (-eps) xt) alpha beta)
        (((-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) *
            Psi.invJacobian 0 xt beta nu +
          Psi.invJacobian 0 xt alpha mu *
            (-fderiv ℝ (fun y => Psi.Y y beta) xt (Pi.single nu 1))) *
          m (Psi.F (-(0:ℝ)) xt) alpha beta +
        (Psi.invJacobian 0 xt alpha mu * Psi.invJacobian 0 xt beta nu) *
          (-(∑ gamma : Fin (n + 1),
            Psi.Y xt gamma * fderiv ℝ (fun y => m y alpha beta) xt (Pi.single gamma 1)))) 0 :=
    fun alpha beta => (hAB alpha beta).mul (hC alpha beta)

  have hInnerSum : ∀ alpha : Fin (n + 1),
      HasDerivAt (fun eps => ∑ beta : Fin (n + 1),
        Psi.invJacobian eps xt alpha mu * Psi.invJacobian eps xt beta nu *
        m (Psi.F (-eps) xt) alpha beta)
      (∑ beta : Fin (n + 1),
        (((-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) *
            Psi.invJacobian 0 xt beta nu +
          Psi.invJacobian 0 xt alpha mu *
            (-fderiv ℝ (fun y => Psi.Y y beta) xt (Pi.single nu 1))) *
          m (Psi.F (-(0:ℝ)) xt) alpha beta +
        (Psi.invJacobian 0 xt alpha mu * Psi.invJacobian 0 xt beta nu) *
          (-(∑ gamma : Fin (n + 1),
            Psi.Y xt gamma * fderiv ℝ (fun y => m y alpha beta) xt (Pi.single gamma 1))))) 0 := by
    intro alpha
    have h := HasDerivAt.sum (u := Finset.univ) (fun beta _ => hABC alpha beta)
    convert h using 1; ext eps; simp
  have hOuterSum : HasDerivAt (fun eps => ∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
      Psi.invJacobian eps xt alpha mu * Psi.invJacobian eps xt beta nu *
      m (Psi.F (-eps) xt) alpha beta)
    (∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
      (((-fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)) *
          Psi.invJacobian 0 xt beta nu +
        Psi.invJacobian 0 xt alpha mu *
          (-fderiv ℝ (fun y => Psi.Y y beta) xt (Pi.single nu 1))) *
        m (Psi.F (-(0:ℝ)) xt) alpha beta +
      (Psi.invJacobian 0 xt alpha mu * Psi.invJacobian 0 xt beta nu) *
        (-(∑ gamma : Fin (n + 1),
          Psi.Y xt gamma * fderiv ℝ (fun y => m y alpha beta) xt (Pi.single gamma 1))))) 0 := by
    have h := HasDerivAt.sum (u := Finset.univ) (fun alpha _ => hInnerSum alpha)
    convert h using 1; ext eps; simp

  rw [hOuterSum.deriv]

  simp only [neg_zero, Psi.F_zero]
  simp_rw [invJacobian_zero Psi xt _ mu, invJacobian_zero Psi xt _ nu]

  simp only [ite_mul, one_mul, zero_mul, mul_ite, mul_one, mul_zero]


  simp only [add_mul, Finset.sum_add_distrib]

  simp only [ite_mul, zero_mul]

  simp only [Finset.sum_ite_eq' Finset.univ nu, Finset.sum_ite_eq' Finset.univ mu,
    Finset.mem_univ, ↓reduceIte]

  have hcollapse : (∑ x : Fin (n + 1), ∑ x_1 : Fin (n + 1),
      if x = mu then -(fderiv ℝ (fun y => Psi.Y y x_1) xt) (Pi.single nu 1) * m xt x x_1 else 0) =
    ∑ x_1 : Fin (n + 1), -(fderiv ℝ (fun y => Psi.Y y x_1) xt) (Pi.single nu 1) * m xt mu x_1 := by
    rw [Finset.sum_comm]
    congr 1; ext x_1
    rw [Finset.sum_ite_eq' Finset.univ mu]
    simp
  rw [hcollapse]

  simp only [Finset.sum_neg_distrib, neg_mul]
  simp only [neg_add]
  have hmul1 : ∀ x : Fin (n + 1),
      (fderiv ℝ (fun y => Psi.Y y x) xt) (Pi.single mu 1) * m xt x nu =
      m xt x nu * (fderiv ℝ (fun y => Psi.Y y x) xt) (Pi.single mu 1) :=
    fun x => mul_comm _ _
  have hmul2 : ∀ x : Fin (n + 1),
      (fderiv ℝ (fun y => Psi.Y y x) xt) (Pi.single nu 1) * m xt mu x =
      m xt mu x * (fderiv ℝ (fun y => Psi.Y y x) xt) (Pi.single nu 1) :=
    fun x => mul_comm _ _
  simp_rw [hmul1, hmul2]

/-- Restatement of `chain_rule_metric_along_inverse_flow` (CM18 Proposition 2.0.2, metric case):
the $\epsilon$-derivative of the transformed metric at $\epsilon=0$ equals
$-(m_{\alpha\nu} \nabla_\mu Y^\alpha + m_{\mu\alpha} \nabla_\nu Y^\alpha
     + Y^\alpha \nabla_\alpha m_{\mu\nu})$. -/
theorem flow_deriv_metric {n : ℕ} (Psi : FlowMap n) (m : Metric n)
    (xt : Spacetime n) (mu nu : Fin (n + 1))
    (hm : ∀ alpha beta, ContDiff ℝ ⊤ (fun y => m y alpha beta)) :
    deriv (fun eps => transformedMetric Psi m eps xt mu nu) 0 =
      -(∑ alpha : Fin (n + 1),
        m xt alpha nu * fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single mu 1)
      + ∑ alpha : Fin (n + 1),
        m xt mu alpha * fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single nu 1)
      + ∑ alpha : Fin (n + 1),
        Psi.Y xt alpha * fderiv ℝ (fun y => m y mu nu) xt (Pi.single alpha 1)) := by
  exact chain_rule_metric_along_inverse_flow Psi m xt mu nu hm

/-- At $\epsilon = 0$, the Jacobian reduces to the Kronecker delta
$M^\mu_{\ \alpha}|_{\epsilon=0} = \delta^\mu_{\ \alpha}$. -/
lemma jacobian_zero {n : ℕ} (Psi : FlowMap n) (xt : Spacetime n)
    (mu alpha : Fin (n + 1)) :
    Psi.jacobian 0 xt mu alpha = if mu = alpha then 1 else 0 := by
  unfold FlowMap.jacobian
  have h0 : (fun y => Psi.F 0 y mu) = (fun y : Spacetime n => y mu) := by
    ext y; simp [Psi.F_zero y]
  rw [h0, (hasFDerivAt_apply mu xt).fderiv]
  simp [ContinuousLinearMap.proj_apply, Pi.single_apply]

/-- Derivative of the Jacobian along the inverse flow at the moving point:
$\left.\partial_\epsilon\right|_{\epsilon=0} M^\mu_{\ \alpha}(F_{-\epsilon}(\widetilde{x}))
  = \nabla_\alpha Y^\mu(\widetilde{x})$.
This is the key identity for differentiating the transformed inverse metric. -/
lemma hasDerivAt_jacobian_at_moving_point_zero {n : ℕ} (Psi : FlowMap n)
    (xt : Spacetime n) (mu alpha : Fin (n + 1)) :
    HasDerivAt (fun eps => Psi.jacobian eps (Psi.F (-eps) xt) mu alpha)
      (fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)) 0 := by


  set H : ℝ × Spacetime n → ℝ :=
    fun p => fderiv ℝ (fun y => Psi.F p.1 y mu) p.2 (Pi.single alpha 1) with hH_def


  have hFmu_smooth : ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n => Psi.F p.1 p.2 mu) :=
    (contDiff_pi.mp Psi.F_smooth_joint) mu

  have hFmu_uncurry : ContDiff ℝ ⊤
      (Function.uncurry (fun (s : ℝ) (z : Spacetime n) => Psi.F s z mu)) := by
    show ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n => Psi.F p.1 p.2 mu)
    exact hFmu_smooth


  have hH_smooth : ContDiff ℝ ⊤ H := by


    have h1 : ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n =>
        fderiv ℝ (fun z => Psi.F p.1 z mu) p.2) := by


      have huf : ContDiff ℝ ⊤ (Function.uncurry
          (fun (p : ℝ × Spacetime n) (y : Spacetime n) => Psi.F p.1 y mu)) := by
        show ContDiff ℝ ⊤ (fun q : (ℝ × Spacetime n) × Spacetime n => Psi.F q.1.1 q.2 mu)
        exact (contDiff_pi.mp (Psi.F_smooth_joint.comp
          ((contDiff_fst.comp contDiff_fst).prodMk contDiff_snd))) mu
      have hg : ContDiff ℝ ⊤ (fun p : ℝ × Spacetime n => p.2) := contDiff_snd
      exact huf.fderiv hg le_top

    exact (ContinuousLinearMap.apply ℝ ℝ (Pi.single alpha 1)).contDiff.comp h1

  have hH_fderiv : HasFDerivAt H (fderiv ℝ H (0, xt)) (0, xt) :=
    (hH_smooth.differentiable WithTop.top_ne_zero).differentiableAt.hasFDerivAt

  have hPath : HasDerivAt (fun eps => (eps, Psi.F (-eps) xt))
      ((1 : ℝ), (-1 : ℝ) • Psi.Y xt) 0 := by
    have hF : HasDerivAt (fun eps => Psi.F (-eps) xt) ((-1 : ℝ) • Psi.Y xt) 0 := by
      have hd : DifferentiableAt ℝ (fun s => Psi.F s xt) 0 :=
        ((Psi.F_smooth_eps xt).differentiable WithTop.top_ne_zero).differentiableAt
      have hF_at : HasDerivAt (fun s => Psi.F s xt) (Psi.Y xt) 0 := by
        rw [← show deriv (fun s => Psi.F s xt) 0 = Psi.Y xt from by
          rw [Psi.F_flow 0 xt, Psi.F_zero xt]]
        exact hd.hasDerivAt
      have hNeg : HasDerivAt Neg.neg (-1 : ℝ) (0 : ℝ) := hasDerivAt_neg 0
      have h0 : Neg.neg (0 : ℝ) = 0 := neg_zero
      rw [← h0] at hF_at
      exact hF_at.scomp 0 hNeg
    exact (hasDerivAt_id (0 : ℝ)).prodMk hF

  have hg0 : (fun eps : ℝ => (eps, Psi.F (-eps) xt)) 0 = (0, xt) := by
    simp [Psi.F_zero]
  have hH_at : HasFDerivAt H (fderiv ℝ H (0, xt)) ((fun eps : ℝ => (eps, Psi.F (-eps) xt)) 0) := by
    rw [hg0]; exact hH_fderiv
  have hchain : HasDerivAt (fun eps => H (eps, Psi.F (-eps) xt))
      ((fderiv ℝ H (0, xt)) ((1 : ℝ), (-1 : ℝ) • Psi.Y xt)) 0 := by
    have := hH_at.comp_hasDerivAt 0 hPath
    simp only [Function.comp_def] at this
    exact this


  have hLinear : (fderiv ℝ H (0, xt)) ((1 : ℝ), (-1 : ℝ) • Psi.Y xt) =
      (fderiv ℝ H (0, xt)) ((1, 0) : ℝ × Spacetime n) +
      (fderiv ℝ H (0, xt)) ((0, (-1 : ℝ) • Psi.Y xt) : ℝ × Spacetime n) := by
    rw [show ((1 : ℝ), (-1 : ℝ) • Psi.Y xt) =
      ((1, 0) : ℝ × Spacetime n) + ((0, (-1 : ℝ) • Psi.Y xt) : ℝ × Spacetime n) from by
        simp]
    exact map_add (fderiv ℝ H (0, xt)) _ _

  have hH0_const : ∀ z : Spacetime n,
      H (0, z) = if mu = alpha then 1 else 0 := by
    intro z
    show fderiv ℝ (fun y => Psi.F 0 y mu) z (Pi.single alpha 1) = _
    have h0 : (fun y => Psi.F 0 y mu) = (fun y : Spacetime n => y mu) := by
      ext y; simp [Psi.F_zero y]
    rw [h0, (hasFDerivAt_apply mu z).fderiv]
    simp [ContinuousLinearMap.proj_apply, Pi.single_apply]
  have hH0_fn : (fun z => H (0, z)) = fun _ => if mu = alpha then 1 else 0 :=
    funext hH0_const
  have hz_part : (fderiv ℝ H (0, xt)) ((0, (-1 : ℝ) • Psi.Y xt) : ℝ × Spacetime n) = 0 := by


    have hfz : HasFDerivAt (fun z => H (0, z))
        (0 : Spacetime n →L[ℝ] ℝ) xt := by
      rw [hH0_fn]
      exact hasFDerivAt_const _ _

    have h_prod_right := hasFDerivAt_prodMk_right (𝕜 := ℝ) (0 : ℝ) xt

    have h_comp : HasFDerivAt (fun z => H (0, z))
        ((fderiv ℝ H (0, xt)).comp (ContinuousLinearMap.inr ℝ ℝ (Spacetime n))) xt :=
      hH_fderiv.comp xt h_prod_right
    have hfz_eq : fderiv ℝ (fun z => H (0, z)) xt =
        (fderiv ℝ H (0, xt)).comp (ContinuousLinearMap.inr ℝ ℝ (Spacetime n)) :=
      h_comp.fderiv

    have hfz_zero : fderiv ℝ (fun z => H (0, z)) xt = 0 := hfz.fderiv

    have : (fderiv ℝ H (0, xt)).comp (ContinuousLinearMap.inr ℝ ℝ (Spacetime n)) = 0 := by
      rw [← hfz_eq, hfz_zero]

    have : ∀ v, (fderiv ℝ H (0, xt)) ((0 : ℝ), v) = 0 := by
      intro v
      have h := ContinuousLinearMap.ext_iff.mp this v
      simp [ContinuousLinearMap.comp_apply, ContinuousLinearMap.inr_apply,
        ContinuousLinearMap.zero_apply] at h
      exact h
    exact this _

  have hs_part : (fderiv ℝ H (0, xt)) ((1, 0) : ℝ × Spacetime n) =
      fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1) := by

    have h_prod_left := (hasDerivAt_id (0 : ℝ)).prodMk (hasDerivAt_const (0 : ℝ) xt)
    have h_prod_left' : HasDerivAt (fun s => (s, xt)) ((1 : ℝ), (0 : Spacetime n)) 0 := by
      simpa using h_prod_left
    have h_comp_s : HasDerivAt (fun s => H (s, xt))
        ((fderiv ℝ H (0, xt)) ((1 : ℝ), (0 : Spacetime n))) 0 := by
      have h00 : (fun s : ℝ => (s, xt)) 0 = (0, xt) := by simp
      have hH_at' : HasFDerivAt H (fderiv ℝ H (0, xt)) ((fun s : ℝ => (s, xt)) 0) := by
        rw [h00]; exact hH_fderiv
      exact hH_at'.comp_hasDerivAt 0 h_prod_left'

    have hs_deriv : deriv (fun s => H (s, xt)) 0 =
        (fderiv ℝ H (0, xt)) ((1 : ℝ), (0 : Spacetime n)) := h_comp_s.deriv
    rw [← hs_deriv]


    show deriv (fun s => fderiv ℝ (fun y => Psi.F s y mu) xt (Pi.single alpha 1)) 0 =
        fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)

    set G : ℝ × Spacetime n → ℝ := fun p => Psi.F p.1 p.2 mu with hG_def
    have hG_smooth : ContDiff ℝ ⊤ G := hFmu_smooth
    have hG_eq : ∀ s, (fun y => Psi.F s y mu) = (fun y => G (s, y)) := by
      intro s; rfl
    simp_rw [hG_eq]
    rw [deriv_fderiv_swap G hG_smooth 0 xt (Pi.single alpha 1)]


    have h_deriv_G : ∀ z, deriv (fun s => G (s, z)) 0 = Psi.Y z mu := by
      intro z
      show deriv (fun s => Psi.F s z mu) 0 = Psi.Y z mu
      have hF_diff : DifferentiableAt ℝ (fun s => Psi.F s z) 0 :=
        ((Psi.F_smooth_eps z).differentiable WithTop.top_ne_zero).differentiableAt
      have hF_at : HasDerivAt (fun s => Psi.F s z) (Psi.Y (Psi.F 0 z)) 0 := by
        rw [← Psi.F_flow 0 z]; exact hF_diff.hasDerivAt
      rw [Psi.F_zero] at hF_at
      exact (hasDerivAt_pi.mp hF_at mu).deriv
    have hfn_eq : (fun z => deriv (fun s => G (s, z)) 0) = (fun z => Psi.Y z mu) :=
      funext h_deriv_G
    rw [hfn_eq]

  rw [show (fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)) =
    (fderiv ℝ H (0, xt)) ((1 : ℝ), (-1 : ℝ) • Psi.Y xt) from by
      rw [hLinear, hz_part, add_zero, hs_part]]
  exact hchain

/-- CM18 Proposition 2.0.2, inverse metric part:
$\left.\partial_\epsilon\right|_{\epsilon=0} (\widetilde{m}^{-1})^{\mu\nu}
  = (m^{-1})^{\alpha\nu} \nabla_\alpha Y^\mu + (m^{-1})^{\mu\alpha} \nabla_\alpha Y^\nu
    - Y^\alpha \nabla_\alpha (m^{-1})^{\mu\nu}$. -/
theorem chain_rule_inverse_metric_along_flow {n : ℕ}
    (Psi : FlowMap n) (mInv : InverseMetric n) (xt : Spacetime n)
    (mu nu : Fin (n + 1))
    (hmInv : ∀ alpha beta, ContDiff ℝ ⊤ (fun y => mInv y alpha beta)) :
    deriv (fun eps => transformedInverseMetric Psi mInv eps xt mu nu) 0 =
      ∑ alpha : Fin (n + 1),
        mInv xt alpha nu * fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)
      + ∑ alpha : Fin (n + 1),
        mInv xt mu alpha * fderiv ℝ (fun y => Psi.Y y nu) xt (Pi.single alpha 1)
      - ∑ alpha : Fin (n + 1),
        Psi.Y xt alpha * fderiv ℝ (fun y => mInv y mu nu) xt (Pi.single alpha 1) := by

  show deriv (fun eps => ∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
    Psi.jacobian eps (Psi.F (-eps) xt) mu alpha *
    Psi.jacobian eps (Psi.F (-eps) xt) nu beta *
    mInv (Psi.F (-eps) xt) alpha beta) 0 = _

  have hA : ∀ alpha : Fin (n + 1),
      HasDerivAt (fun eps => Psi.jacobian eps (Psi.F (-eps) xt) mu alpha)
        (fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)) 0 :=
    fun alpha => hasDerivAt_jacobian_at_moving_point_zero Psi xt mu alpha
  have hB : ∀ beta : Fin (n + 1),
      HasDerivAt (fun eps => Psi.jacobian eps (Psi.F (-eps) xt) nu beta)
        (fderiv ℝ (fun y => Psi.Y y nu) xt (Pi.single beta 1)) 0 :=
    fun beta => hasDerivAt_jacobian_at_moving_point_zero Psi xt nu beta
  have hC : ∀ alpha beta : Fin (n + 1),
      HasDerivAt (fun eps => mInv (Psi.F (-eps) xt) alpha beta)
        (-(∑ gamma : Fin (n + 1),
          Psi.Y xt gamma * fderiv ℝ (fun y => mInv y alpha beta) xt (Pi.single gamma 1))) 0 := by
    intro alpha beta
    have := hasDerivAt_scalar_along_inverse_flow Psi (fun y => mInv y alpha beta) (hmInv alpha beta) xt
    simp only [spacetimeGradient] at this
    exact this

  have hAB : ∀ alpha beta : Fin (n + 1),
      HasDerivAt (fun eps => Psi.jacobian eps (Psi.F (-eps) xt) mu alpha *
        Psi.jacobian eps (Psi.F (-eps) xt) nu beta)
        ((fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)) *
          Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) nu beta +
         Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) mu alpha *
          (fderiv ℝ (fun y => Psi.Y y nu) xt (Pi.single beta 1))) 0 :=
    fun alpha beta => (hA alpha).mul (hB beta)

  have hABC : ∀ alpha beta : Fin (n + 1),
      HasDerivAt (fun eps => Psi.jacobian eps (Psi.F (-eps) xt) mu alpha *
        Psi.jacobian eps (Psi.F (-eps) xt) nu beta *
        mInv (Psi.F (-eps) xt) alpha beta)
        (((fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)) *
            Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) nu beta +
          Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) mu alpha *
            (fderiv ℝ (fun y => Psi.Y y nu) xt (Pi.single beta 1))) *
          mInv (Psi.F (-(0:ℝ)) xt) alpha beta +
        (Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) mu alpha *
          Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) nu beta) *
          (-(∑ gamma : Fin (n + 1),
            Psi.Y xt gamma * fderiv ℝ (fun y => mInv y alpha beta) xt (Pi.single gamma 1)))) 0 :=
    fun alpha beta => (hAB alpha beta).mul (hC alpha beta)

  have hInnerSum : ∀ alpha : Fin (n + 1),
      HasDerivAt (fun eps => ∑ beta : Fin (n + 1),
        Psi.jacobian eps (Psi.F (-eps) xt) mu alpha *
        Psi.jacobian eps (Psi.F (-eps) xt) nu beta *
        mInv (Psi.F (-eps) xt) alpha beta)
      (∑ beta : Fin (n + 1),
        (((fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)) *
            Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) nu beta +
          Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) mu alpha *
            (fderiv ℝ (fun y => Psi.Y y nu) xt (Pi.single beta 1))) *
          mInv (Psi.F (-(0:ℝ)) xt) alpha beta +
        (Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) mu alpha *
          Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) nu beta) *
          (-(∑ gamma : Fin (n + 1),
            Psi.Y xt gamma * fderiv ℝ (fun y => mInv y alpha beta) xt (Pi.single gamma 1))))) 0 := by
    intro alpha
    have h := HasDerivAt.sum (u := Finset.univ) (fun beta _ => hABC alpha beta)
    convert h using 1; ext eps; simp
  have hOuterSum : HasDerivAt (fun eps => ∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
      Psi.jacobian eps (Psi.F (-eps) xt) mu alpha *
      Psi.jacobian eps (Psi.F (-eps) xt) nu beta *
      mInv (Psi.F (-eps) xt) alpha beta)
    (∑ alpha : Fin (n + 1), ∑ beta : Fin (n + 1),
      (((fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)) *
          Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) nu beta +
        Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) mu alpha *
          (fderiv ℝ (fun y => Psi.Y y nu) xt (Pi.single beta 1))) *
        mInv (Psi.F (-(0:ℝ)) xt) alpha beta +
      (Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) mu alpha *
        Psi.jacobian 0 (Psi.F (-(0:ℝ)) xt) nu beta) *
        (-(∑ gamma : Fin (n + 1),
          Psi.Y xt gamma * fderiv ℝ (fun y => mInv y alpha beta) xt (Pi.single gamma 1))))) 0 := by
    have h := HasDerivAt.sum (u := Finset.univ) (fun alpha _ => hInnerSum alpha)
    convert h using 1; ext eps; simp

  rw [hOuterSum.deriv]

  simp only [neg_zero, Psi.F_zero]
  simp_rw [jacobian_zero Psi xt mu _, jacobian_zero Psi xt nu _]

  simp only [ite_mul, one_mul, zero_mul, mul_ite, mul_one, mul_zero]

  simp only [add_mul, Finset.sum_add_distrib]
  simp only [ite_mul, zero_mul]


  conv_lhs => rw [show (∑ x : Fin (n + 1), ∑ x_1 : Fin (n + 1),
      if nu = x_1 then (fderiv ℝ (fun y => Psi.Y y mu) xt) (Pi.single x 1) * mInv xt x x_1 else 0) =
    ∑ x : Fin (n + 1), (fderiv ℝ (fun y => Psi.Y y mu) xt) (Pi.single x 1) * mInv xt x nu from by
      congr 1; ext x; simp [Finset.sum_ite_eq, Finset.mem_univ]]

  conv_lhs => rw [show (∑ x : Fin (n + 1), ∑ x_1 : Fin (n + 1),
      if mu = x then (fderiv ℝ (fun y => Psi.Y y nu) xt) (Pi.single x_1 1) * mInv xt x x_1 else 0) =
    ∑ x_1 : Fin (n + 1), (fderiv ℝ (fun y => Psi.Y y nu) xt) (Pi.single x_1 1) * mInv xt mu x_1 from by
      rw [Finset.sum_comm]; congr 1; ext x_1; simp [Finset.sum_ite_eq, Finset.mem_univ]]

  conv_lhs => rw [show (∑ x : Fin (n + 1), ∑ x_1 : Fin (n + 1),
      if nu = x_1 then
        if mu = x then -(∑ gamma : Fin (n + 1),
          Psi.Y xt gamma * (fderiv ℝ (fun y => mInv y x x_1) xt) (Pi.single gamma 1)) else 0
      else 0) =
    -(∑ gamma : Fin (n + 1),
      Psi.Y xt gamma * (fderiv ℝ (fun y => mInv y mu nu) xt) (Pi.single gamma 1)) from by
      simp [Finset.sum_ite_eq, Finset.mem_univ]]

  congr 1
  · congr 1
    · congr 1; ext x; ring
    · congr 1; ext x; ring

/-- Restatement of `chain_rule_inverse_metric_along_flow` (CM18 Proposition 2.0.2, inverse metric
case): the $\epsilon$-derivative of the transformed inverse metric at $\epsilon = 0$. -/
theorem flow_deriv_inverse_metric {n : ℕ} (Psi : FlowMap n) (mInv : InverseMetric n)
    (xt : Spacetime n) (mu nu : Fin (n + 1))
    (hmInv : ∀ alpha beta, ContDiff ℝ ⊤ (fun y => mInv y alpha beta)) :
    deriv (fun eps => transformedInverseMetric Psi mInv eps xt mu nu) 0 =
      ∑ alpha : Fin (n + 1),
        mInv xt alpha nu * fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single alpha 1)
      + ∑ alpha : Fin (n + 1),
        mInv xt mu alpha * fderiv ℝ (fun y => Psi.Y y nu) xt (Pi.single alpha 1)
      - ∑ alpha : Fin (n + 1),
        Psi.Y xt alpha * fderiv ℝ (fun y => mInv y mu nu) xt (Pi.single alpha 1) := by
  exact chain_rule_inverse_metric_along_flow Psi mInv xt mu nu hmInv

/-- For any non-identity permutation $\sigma$ and any index $i$, there exists some $j \ne i$ that
$\sigma$ does not fix. Used in the proof of the Jacobi determinant identity. -/
lemma exists_ne_fixed_in_erase {n : ℕ} (σ : Equiv.Perm (Fin n)) (hσ : σ ≠ 1)
    (i : Fin n) : ∃ j ∈ Finset.univ.erase i, σ j ≠ j := by
  have h0 : σ.support.card ≠ 0 := by
    rwa [ne_eq, Finset.card_eq_zero, Equiv.Perm.support_eq_empty_iff]
  have hge2 : 1 < σ.support.card := by
    have := Equiv.Perm.card_support_ne_one σ; omega
  obtain ⟨a, ha, b, hb, hab⟩ := Finset.one_lt_card.mp hge2
  by_cases hai : a = i
  · subst hai
    exact ⟨b, Finset.mem_erase.mpr ⟨hab.symm, Finset.mem_univ b⟩, Equiv.Perm.mem_support.mp hb⟩
  · exact ⟨a, Finset.mem_erase.mpr ⟨hai, Finset.mem_univ a⟩, Equiv.Perm.mem_support.mp ha⟩

/-- Jacobi-style trace identity: the permutation-sum form of the determinant derivative at the
identity matrix collapses to the trace $\sum_k f'_{kk}$. -/
lemma det_deriv_trace_identity {n : ℕ} (f' : Fin (n+1) → Fin (n+1) → ℝ) :
    ∑ σ : Equiv.Perm (Fin (n+1)), (↑↑(Equiv.Perm.sign σ) : ℝ) *
      (∑ k : Fin (n+1), (∏ j ∈ Finset.univ.erase k,
        (if σ j = j then (1:ℝ) else 0)) • f' (σ k) k) =
    ∑ k : Fin (n+1), f' k k := by
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ (1 : Equiv.Perm (Fin (n+1))))]
  have h_rest : ∑ σ ∈ Finset.univ.erase 1, (↑↑(Equiv.Perm.sign σ) : ℝ) *
      (∑ k, (∏ j ∈ Finset.univ.erase k, (if σ j = j then (1:ℝ) else 0)) • f' (σ k) k) = 0 := by
    apply Finset.sum_eq_zero
    intro σ hσ
    have hσ_ne : σ ≠ 1 := (Finset.mem_erase.mp hσ).1
    have h : ∀ k, (∏ j ∈ Finset.univ.erase k, (if σ j = j then (1:ℝ) else 0)) • f' (σ k) k = 0 := by
      intro k
      obtain ⟨j, hj_mem, hj_ne⟩ := exists_ne_fixed_in_erase σ hσ_ne k
      rw [Finset.prod_eq_zero hj_mem (by simp [hj_ne]), zero_smul]
    simp_rw [h]; simp
  rw [h_rest, add_zero]
  simp [Equiv.Perm.one_apply]

/-- Jacobi's formula applied to the inverse-Jacobian flow at $\epsilon = 0$:
$\left.\partial_\epsilon\right|_{\epsilon=0} \det M^{-1} = -\nabla_\alpha Y^\alpha$,
matching the expansion $\det M^{-1} = 1 - \epsilon \nabla_\alpha Y^\alpha + O(\epsilon^2)$
in CM18 Proposition 2.0.1. -/
theorem jacobi_formula_flow {n : ℕ} (Psi : FlowMap n) (xt : Spacetime n) :
    deriv (fun eps =>
      Matrix.det (Matrix.of (fun mu nu => Psi.invJacobian eps xt mu nu))) 0 =
      -(∑ alpha : Fin (n + 1),
        fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single alpha 1)) := by

  have hdet : ∀ eps, Matrix.det (Matrix.of (fun mu nu => Psi.invJacobian eps xt mu nu)) =
      ∑ σ : Equiv.Perm (Fin (n+1)), ↑↑(Equiv.Perm.sign σ) *
        ∏ i : Fin (n+1), Psi.invJacobian eps xt (σ i) i := by
    intro eps; rw [Matrix.det_apply']; rfl
  simp_rw [hdet]

  set g := fun (mu nu : Fin (n+1)) (eps : ℝ) => Psi.invJacobian eps xt mu nu with hg_def
  set g' := fun (mu nu : Fin (n+1)) => -fderiv ℝ (fun y => Psi.Y y mu) xt (Pi.single nu 1)
    with hg'_def
  have hg_deriv : ∀ mu nu, HasDerivAt (g mu nu) (g' mu nu) 0 :=
    fun mu nu => hasDerivAt_invJacobian_at_zero Psi xt mu nu

  have hprod : ∀ σ : Equiv.Perm (Fin (n+1)),
      HasDerivAt (fun eps => ∏ i : Fin (n+1), g (σ i) i eps)
        (∑ k : Fin (n+1), (∏ j ∈ Finset.univ.erase k, g (σ j) j 0) • g' (σ k) k) 0 := by
    intro σ
    exact HasDerivAt.fun_finset_prod (fun i _ => hg_deriv (σ i) i)

  have hsign_prod : ∀ σ : Equiv.Perm (Fin (n+1)),
      HasDerivAt (fun eps => (↑↑(Equiv.Perm.sign σ) : ℝ) * ∏ i, g (σ i) i eps)
        ((↑↑(Equiv.Perm.sign σ) : ℝ) *
          (∑ k, (∏ j ∈ Finset.univ.erase k, g (σ j) j 0) • g' (σ k) k)) 0 := by
    intro σ; exact (hprod σ).const_mul _

  have hfull : HasDerivAt
      (fun eps => ∑ σ : Equiv.Perm (Fin (n+1)),
        (↑↑(Equiv.Perm.sign σ) : ℝ) * ∏ i, g (σ i) i eps)
      (∑ σ : Equiv.Perm (Fin (n+1)), (↑↑(Equiv.Perm.sign σ) : ℝ) *
        (∑ k, (∏ j ∈ Finset.univ.erase k, g (σ j) j 0) • g' (σ k) k)) 0 := by
    exact HasDerivAt.fun_sum (fun σ _ => hsign_prod σ)

  rw [hfull.deriv]

  have hg_zero : ∀ mu nu, g mu nu 0 = if mu = nu then 1 else 0 := by
    intro mu nu; exact invJacobian_zero Psi xt mu nu
  simp_rw [hg_zero]

  rw [det_deriv_trace_identity]

  simp only [hg'_def, Finset.sum_neg_distrib]

/-- Restatement of `jacobi_formula_flow`: the $\epsilon$-derivative of $\det M^{-1}$ at $\epsilon=0$
equals $-\nabla_\alpha Y^\alpha$ (CM18 Proposition 2.0.1, determinant case). -/
theorem flow_deriv_det_invJacobian {n : ℕ} (Psi : FlowMap n) (xt : Spacetime n) :
    deriv (fun eps =>
      Matrix.det (Matrix.of (fun mu nu => Psi.invJacobian eps xt mu nu))) 0 =
      -(∑ alpha : Fin (n + 1),
        fderiv ℝ (fun y => Psi.Y y alpha) xt (Pi.single alpha 1)) := by
  exact jacobi_formula_flow Psi xt

/-- The partial derivative $\partial \mathcal{L} / \partial m_{\mu\nu}$ of a metric Lagrangian
with respect to the $(\mu,\nu)$-entry of the metric, evaluated at $(\phi(x), \nabla\phi(x), m(x))$. -/
def dL_dm {n : ℕ} (L : MetricLagrangian n) (phi : ScalarField n)
    (m : Metric n) (x : Spacetime n)
    (mu nu : Fin (n + 1)) : ℝ :=
  fderiv ℝ (fun mval => L (phi x) (spacetimeGradient phi x) mval)
    (m x)
    (fun mu' nu' => if mu' = mu ∧ nu' = nu then 1 else 0)


set_option maxHeartbeats 800000 in
/-- Decomposition of the Fréchet derivative on a product: for $h : E \times F \to G$ differentiable
at $(a,b)$,
$dh_{(a,b)}(da, db) = dh^{(\cdot, b)}_a(da) + dh^{(a, \cdot)}_b(db)$,
i.e. the total differential splits into the two partial differentials. -/
lemma fderiv_prod_decomp_chain {E F G : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [NormedAddCommGroup F] [NormedSpace ℝ F] [NormedAddCommGroup G] [NormedSpace ℝ G]
    (h : E × F → G) (a : E) (b : F) (da : E) (db : F)
    (hh : DifferentiableAt ℝ h (a, b)) :
    (fderiv ℝ h (a, b)) (da, db) =
      (fderiv ℝ (fun a' => h (a', b)) a) da + (fderiv ℝ (fun b' => h (a, b')) b) db := by
  have h1 : fderiv ℝ (fun a' => h (a', b)) a =
      (fderiv ℝ h (a, b)).comp (ContinuousLinearMap.inl ℝ E F) := by
    have heq : (fun a' => h (a', b)) = h ∘ (fun a' => (a', b)) := by ext; simp
    rw [heq, fderiv_comp a hh (differentiableAt_id.prodMk (differentiableAt_const b))]
    ext v; simp [ContinuousLinearMap.comp_apply]
    have hfd : HasFDerivAt (fun a' => (a', b)) (ContinuousLinearMap.inl ℝ E F) a :=
      (hasFDerivAt_id a).prodMk (hasFDerivAt_const b a)
    congr 1; rw [hfd.fderiv]; simp
  have h2 : fderiv ℝ (fun b' => h (a, b')) b =
      (fderiv ℝ h (a, b)).comp (ContinuousLinearMap.inr ℝ E F) := by
    have heq : (fun b' => h (a, b')) = h ∘ (fun b' => (a, b')) := by ext; simp
    rw [heq, fderiv_comp b hh ((differentiableAt_const a).prodMk differentiableAt_id)]
    ext v; simp [ContinuousLinearMap.comp_apply]
    have hfd : HasFDerivAt (Prod.mk a) (ContinuousLinearMap.inr ℝ E F) b :=
      (hasFDerivAt_const a b).prodMk (hasFDerivAt_id b)
    congr 1; rw [hfd.fderiv]; simp
  rw [h1, h2, ContinuousLinearMap.comp_apply, ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.inl_apply, ContinuousLinearMap.inr_apply]
  have key : (da, db) = ((da, (0 : F)) : E × F) + ((0 : E), db) := by ext <;> simp
  rw [key, map_add]

/-- A continuous linear functional on $\mathbb{R}^{n+1}$ decomposes in the standard basis as
$D(v) = \sum_\mu D(e_\mu)\, v_\mu$, where $e_\mu$ is the $\mu$-th unit vector. -/
lemma clm_pi_decomp_chain {n : ℕ}
    (D : (Fin (n + 1) → ℝ) →L[ℝ] ℝ) (v : Fin (n + 1) → ℝ) :
    D v = ∑ μ, D (Pi.single μ 1) * v μ := by
  conv_lhs =>
    rw [show v = ∑ i : Fin (n + 1), v i •
      (Pi.single (M := fun _ : Fin (n + 1) => ℝ) i 1) from by
      ext j; simp [Finset.sum_apply, Pi.single_apply]]
  simp [map_sum, map_smul, mul_comm]

set_option maxHeartbeats 800000 in
/-- Matrix version of `clm_pi_decomp_chain`: a continuous linear functional on the matrix space
$\mathbb{R}^{(n+1) \times (n+1)}$ decomposes as
$D(v) = \sum_{\mu,\nu} D(E_{\mu\nu})\, v_{\mu\nu}$, where $E_{\mu\nu}$ is the matrix with a single
$1$ in position $(\mu,\nu)$. -/
lemma clm_dbl_pi_decomp_chain {n : ℕ}
    (D : (Fin (n + 1) → Fin (n + 1) → ℝ) →L[ℝ] ℝ)
    (v : Fin (n + 1) → Fin (n + 1) → ℝ) :
    D v = ∑ μ, ∑ ν, D (fun μ' ν' => if μ' = μ ∧ ν' = ν then 1 else 0) * v μ ν := by
  conv_lhs =>
    rw [show v = ∑ μ : Fin (n + 1),
        (fun μ' => if μ' = μ then v μ else (0 : Fin (n + 1) → ℝ)) from by
      ext μ' ν'
      have : ∀ c, (if μ' = c then v c else (0 : Fin (n + 1) → ℝ)) ν' =
          if μ' = c then v c ν' else 0 := fun c => by split_ifs <;> simp
      simp_rw [Finset.sum_apply, this, Finset.sum_ite_eq, Finset.mem_univ, ite_true],
      map_sum]
  congr 1; ext μ
  rw [show (fun μ' => if μ' = μ then v μ else (0 : Fin (n+1) → ℝ)) =
      ∑ ν : Fin (n + 1), v μ ν •
        (fun μ' ν' => if μ' = μ ∧ ν' = ν then (1 : ℝ) else 0) from by
    ext μ' ν'
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
    split_ifs with h
    · subst h; simp [mul_ite, mul_one, mul_zero, Finset.sum_ite_eq, Finset.mem_univ]
    · simp [h, mul_zero, Finset.sum_const_zero],
    map_sum]
  congr 1; ext ν; rw [map_smul, smul_eq_mul, mul_comm]

/-- For a vector-valued function $f : \mathbb{R} \to \mathbb{R}^{n+1}$, taking the $i$-th component
of $f'(x)$ equals the derivative of the scalar component function $\epsilon \mapsto f(\epsilon)_i$. -/
lemma deriv_pi_comp_chain {n : ℕ} (f : ℝ → Fin (n + 1) → ℝ) (x : ℝ)
    (i : Fin (n + 1)) (hf : DifferentiableAt ℝ f x) :
    (deriv f x) i = deriv (fun ε => f ε i) x := by
  rw [deriv_pi (fun j => differentiableAt_pi.mp hf j)]

/-- Matrix version of `deriv_pi_comp_chain`: for $f : \mathbb{R} \to \mathbb{R}^{(n+1)\times(n+1)}$,
the $(i,j)$ entry of $f'(x)$ equals the derivative of the scalar component
$\epsilon \mapsto f(\epsilon)_{ij}$. -/
lemma deriv_double_pi_comp_chain {n : ℕ}
    (f : ℝ → Fin (n + 1) → Fin (n + 1) → ℝ)
    (x : ℝ) (i j : Fin (n + 1)) (hf : DifferentiableAt ℝ f x) :
    deriv f x i j = deriv (fun ε => f ε i j) x := by
  rw [deriv_pi (fun μ => differentiableAt_pi.mp hf μ)]
  show deriv (fun ε => f ε i) x j = deriv (fun ε => f ε i j) x
  rw [deriv_pi (fun ν => differentiableAt_pi.mp (differentiableAt_pi.mp hf i) ν)]

set_option maxHeartbeats 1600000 in
/-- Three-argument chain rule for a Lagrangian $L(v, p, m)$ composed with three smooth families
$f_1(\epsilon), f_2(\epsilon), f_3(\epsilon)$: the $\epsilon$-derivative at $0$ decomposes as
$\partial_v L \cdot f_1' + \sum_\mu \partial_{p_\mu} L \cdot (f_2)_\mu'
  + \sum_{\mu,\nu} \partial_{m_{\mu\nu}} L \cdot (f_3)_{\mu\nu}'$. -/
theorem chain_rule_three_arg {n : ℕ}
    (L : ℝ → (Fin (n + 1) → ℝ) → (Fin (n + 1) → Fin (n + 1) → ℝ) → ℝ)
    (f₁ : ℝ → ℝ) (f₂ : ℝ → Fin (n + 1) → ℝ)
    (f₃ : ℝ → Fin (n + 1) → Fin (n + 1) → ℝ)
    (hL : ContDiff ℝ 2 (fun p : ℝ × (Fin (n + 1) → ℝ) ×
      (Fin (n + 1) → Fin (n + 1) → ℝ) => L p.1 p.2.1 p.2.2))
    (hf₁ : DifferentiableAt ℝ f₁ 0)
    (hf₂ : DifferentiableAt ℝ f₂ 0)
    (hf₃ : DifferentiableAt ℝ f₃ 0) :
    deriv (fun ε => L (f₁ ε) (f₂ ε) (f₃ ε)) 0 =
      deriv (fun v => L v (f₂ 0) (f₃ 0)) (f₁ 0) * deriv f₁ 0
      + ∑ μ : Fin (n + 1),
          fderiv ℝ (fun p => L (f₁ 0) p (f₃ 0)) (f₂ 0) (Pi.single μ 1) *
          deriv (fun ε => f₂ ε μ) 0
      + ∑ μ : Fin (n + 1), ∑ ν : Fin (n + 1),
          fderiv ℝ (fun m => L (f₁ 0) (f₂ 0) m) (f₃ 0)
            (fun μ' ν' => if μ' = μ ∧ ν' = ν then 1 else 0) *
          deriv (fun ε => f₃ ε μ ν) 0 := by
  let L' := fun p : ℝ × (Fin (n + 1) → ℝ) × (Fin (n + 1) → Fin (n + 1) → ℝ) =>
    L p.1 p.2.1 p.2.2
  have hL'_diff : DifferentiableAt ℝ L' (f₁ 0, f₂ 0, f₃ 0) :=
    (hL.differentiable (by norm_cast : (2 : WithTop ℕ∞) ≠ 0)).differentiableAt
  have chain := hL'_diff.hasFDerivAt.comp_hasDerivAt 0
    (hf₁.hasDerivAt.prodMk (hf₂.hasDerivAt.prodMk hf₃.hasDerivAt))
  rw [show deriv (fun ε => L (f₁ ε) (f₂ ε) (f₃ ε)) 0 =
      (fderiv ℝ L' (f₁ 0, f₂ 0, f₃ 0)) (deriv f₁ 0, deriv f₂ 0, deriv f₃ 0) from by
    convert chain.deriv using 1]
  rw [fderiv_prod_decomp_chain L' (f₁ 0) (f₂ 0, f₃ 0) (deriv f₁ 0)
    (deriv f₂ 0, deriv f₃ 0) hL'_diff]
  have hL'_bc : DifferentiableAt ℝ (fun bc => L' (f₁ 0, bc)) (f₂ 0, f₃ 0) := by
    show DifferentiableAt ℝ (L' ∘ (fun bc => (f₁ 0, bc))) (f₂ 0, f₃ 0)
    exact hL'_diff.comp _ ((differentiableAt_const _).prodMk differentiableAt_id)
  rw [fderiv_prod_decomp_chain (fun bc => L' (f₁ 0, bc)) (f₂ 0) (f₃ 0)
    (deriv f₂ 0) (deriv f₃ 0) hL'_bc, add_assoc]
  congr 1
  · exact fderiv_eq_deriv_mul
  congr 1
  · rw [clm_pi_decomp_chain _ (deriv f₂ 0)]
    congr 1; ext μ; congr 1
    exact deriv_pi_comp_chain f₂ 0 μ hf₂
  · rw [clm_dbl_pi_decomp_chain _ (deriv f₃ 0)]
    congr 1; ext μ; congr 1; ext ν; congr 1
    exact deriv_double_pi_comp_chain f₃ 0 μ ν hf₃

/-- At $\epsilon = 0$, the transformed scalar field reduces to the original:
$\widetilde{\phi}|_{\epsilon=0}(x) = \phi(x)$. -/
theorem transformedField_at_zero {n : ℕ} (Psi : FlowMap n)
    (phi : ScalarField n) (x : Spacetime n) :
    transformedField Psi phi 0 x = phi x := by
  unfold transformedField
  simp [Psi.F_zero]

/-- At $\epsilon = 0$, the transformed gradient reduces to the original gradient
$\nabla\phi(x)$. -/
theorem transformedGradient_at_zero {n : ℕ} (Psi : FlowMap n)
    (phi : ScalarField n) (x : Spacetime n) :
    (fun mu => transformedGradient Psi phi 0 x mu) = spacetimeGradient phi x := by
  ext mu
  unfold transformedGradient


  simp only [neg_zero]

  have hJ : ∀ alpha, Psi.invJacobian 0 x alpha mu =
      if alpha = mu then 1 else 0 := by
    intro alpha
    unfold FlowMap.invJacobian
    simp only [neg_zero]
    have : (fun z => Psi.F 0 z alpha) = (fun z => z alpha) := by
      ext z; rw [Psi.F_zero]
    rw [this]
    have key : HasFDerivAt (fun z : Fin (n+1) → ℝ => z alpha)
      (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin (n+1) => ℝ) alpha) x :=
      (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin (n+1) => ℝ) alpha).hasFDerivAt
    rw [key.fderiv, ContinuousLinearMap.proj_apply, Pi.single_apply]
  simp_rw [hJ, Psi.F_zero]

  simp [Finset.sum_ite_eq', Finset.mem_univ]

/-- At $\epsilon = 0$, the transformed metric reduces to the original $m(x)$. -/
theorem transformedMetric_at_zero {n : ℕ} (Psi : FlowMap n)
    (m : Metric n) (x : Spacetime n) :
    (fun mu nu => transformedMetric Psi m 0 x mu nu) = m x := by
  ext mu nu
  unfold transformedMetric
  simp only [neg_zero]

  have hJ : ∀ alpha idx, Psi.invJacobian 0 x alpha idx =
      if alpha = idx then 1 else 0 := by
    intro alpha idx
    unfold FlowMap.invJacobian
    simp only [neg_zero]
    have : (fun z => Psi.F 0 z alpha) = (fun z => z alpha) := by
      ext z; rw [Psi.F_zero]
    rw [this]
    have key : HasFDerivAt (fun z : Fin (n+1) → ℝ => z alpha)
      (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin (n+1) => ℝ) alpha) x :=
      (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin (n+1) => ℝ) alpha).hasFDerivAt
    rw [key.fderiv, ContinuousLinearMap.proj_apply, Pi.single_apply]
  simp_rw [hJ, Psi.F_zero]

  have h1 : ∀ alpha, ∑ beta : Fin (n+1),
      (if alpha = mu then (1 : ℝ) else 0) * (if beta = nu then (1 : ℝ) else 0) * m x alpha beta =
      if alpha = mu then m x alpha nu else 0 := by
    intro alpha
    by_cases ha : alpha = mu
    · subst ha; simp [Finset.sum_ite_eq', Finset.mem_univ]
    · simp [ha]
  simp_rw [h1]
  simp [Finset.sum_ite_eq', Finset.mem_univ]

/-- For smooth $\phi$, the transformed field $\epsilon \mapsto \widetilde{\phi}(x)$ is
differentiable at $\epsilon = 0$. -/
theorem transformedField_differentiable {n : ℕ} (Psi : FlowMap n)
    (phi : ScalarField n) (x : Spacetime n)
    (hphi : ContDiff ℝ ⊤ phi) :
    DifferentiableAt ℝ (fun eps => transformedField Psi phi eps x) 0 := by
  unfold transformedField
  apply DifferentiableAt.comp (𝕜 := ℝ)
  · exact (hphi.differentiable (WithTop.top_ne_zero)).differentiableAt
  · show DifferentiableAt ℝ (fun eps => Psi.F (-eps) x) 0
    have h1 : DifferentiableAt ℝ (fun eps => Psi.F eps x) 0 :=
      ((Psi.F_smooth_eps x).differentiable (WithTop.top_ne_zero)).differentiableAt
    have h2 : DifferentiableAt ℝ (Neg.neg : ℝ → ℝ) (0 : ℝ) :=
      differentiable_neg.differentiableAt
    have h3 := DifferentiableAt.comp (0 : ℝ) (by convert h1 using 1; simp) h2
    convert h3 using 1

/-- For smooth $\phi$, the transformed gradient $\epsilon \mapsto \widetilde{\nabla}\widetilde{\phi}(x)$
is differentiable at $\epsilon = 0$. -/
theorem transformedGradient_differentiable {n : ℕ} (Psi : FlowMap n)
    (phi : ScalarField n) (x : Spacetime n)
    (hphi : ContDiff ℝ ⊤ phi) :
    DifferentiableAt ℝ (fun eps mu => transformedGradient Psi phi eps x mu) 0 := by
  rw [differentiableAt_pi]
  intro mu


  show DifferentiableAt ℝ (fun eps => ∑ alpha : Fin (n + 1),
    Psi.invJacobian eps x alpha mu * spacetimeGradient phi (Psi.F (-eps) x) alpha) 0
  apply DifferentiableAt.fun_sum

  intro alpha _

  apply DifferentiableAt.mul
  ·
    exact invJacobian_differentiableAt_zero Psi x alpha mu

  ·
    have hg : ContDiff ℝ ⊤ (fun y => spacetimeGradient phi y alpha) := by
      unfold spacetimeGradient
      exact (ContinuousLinearMap.apply ℝ ℝ (Pi.single alpha 1)).contDiff.comp
        (hphi.fderiv_right (m := ⊤) le_top)
    exact (hasDerivAt_scalar_along_inverse_flow Psi
      (fun y => spacetimeGradient phi y alpha) hg x).differentiableAt

/-- For a smooth metric, the transformed metric $\epsilon \mapsto \widetilde{m}(x)$ is
differentiable at $\epsilon = 0$. -/
theorem transformedMetric_differentiable {n : ℕ} (Psi : FlowMap n)
    (m : Metric n) (x : Spacetime n)
    (hm : ∀ alpha beta, ContDiff ℝ ⊤ (fun y => m y alpha beta)) :
    DifferentiableAt ℝ (fun eps mu nu => transformedMetric Psi m eps x mu nu) 0 := by
  rw [differentiableAt_pi]; intro mu; rw [differentiableAt_pi]; intro nu
  unfold transformedMetric
  apply DifferentiableAt.fun_sum; intro alpha _
  apply DifferentiableAt.fun_sum; intro beta _
  apply DifferentiableAt.mul
  · apply DifferentiableAt.mul
    · exact invJacobian_differentiableAt_zero Psi x alpha mu
    · exact invJacobian_differentiableAt_zero Psi x beta nu

  · exact (hasDerivAt_scalar_along_inverse_flow Psi (fun y => m y alpha beta)
      (hm alpha beta) x).differentiableAt

/-- Algebraic combination of the scalar, gradient, and metric variation formulas. Given the three
flow-derivative identities (CM18 Proposition 2.0.2) as hypotheses, the $\epsilon$-derivative of
$\mathcal{L}(\widetilde{\phi}, \widetilde{\nabla}\widetilde{\phi}, \widetilde{m})$ at $\epsilon=0$
expands by the three-argument chain rule into the explicit sum appearing in CM18 Corollary 2.0.3. -/
theorem flow_algebra_simplification {n : ℕ}
    (L : MetricLagrangian n) (Psi : FlowMap n) (phi : ScalarField n)
    (m : Metric n) (x : Spacetime n)

    (hL_smooth : ContDiff ℝ 2 (fun p : ℝ × (Fin (n + 1) → ℝ) ×
      (Fin (n + 1) → Fin (n + 1) → ℝ) => L p.1 p.2.1 p.2.2))

    (h_scalar : deriv (fun eps => transformedField Psi phi eps x) 0 =
      -(∑ alpha : Fin (n + 1), Psi.Y x alpha * spacetimeGradient phi x alpha))
    (h_grad : ∀ mu : Fin (n + 1),
      deriv (fun eps => transformedGradient Psi phi eps x mu) 0 =
        -fderiv ℝ (fun y => ∑ alpha : Fin (n + 1),
          Psi.Y y alpha * spacetimeGradient phi y alpha) x (Pi.single mu 1))
    (h_metric : ∀ mu nu : Fin (n + 1),
      deriv (fun eps => transformedMetric Psi m eps x mu nu) 0 =
        -(∑ alpha : Fin (n + 1),
          m x alpha nu * fderiv ℝ (fun y => Psi.Y y alpha) x (Pi.single mu 1)
        + ∑ alpha : Fin (n + 1),
          m x mu alpha * fderiv ℝ (fun y => Psi.Y y alpha) x (Pi.single nu 1)
        + ∑ alpha : Fin (n + 1),
          Psi.Y x alpha * fderiv ℝ (fun y => m y mu nu) x (Pi.single alpha 1)))

    (hphi : ContDiff ℝ ⊤ phi)
    (hm : ∀ alpha beta, ContDiff ℝ ⊤ (fun y => m y alpha beta)) :

    deriv (fun eps =>
      L (transformedField Psi phi eps x)
        (fun mu => transformedGradient Psi phi eps x mu)
        (fun mu nu => transformedMetric Psi m eps x mu nu)) 0 =
      -(deriv (fun v => L v (spacetimeGradient phi x) (m x)) (phi x)) *
        (∑ alpha : Fin (n + 1), Psi.Y x alpha * spacetimeGradient phi x alpha)
      - ∑ mu : Fin (n + 1),
        (fderiv ℝ (fun p => L (phi x) p (m x)) (spacetimeGradient phi x)
          (Pi.single mu 1)) *
        fderiv ℝ (fun y => ∑ alpha : Fin (n + 1),
          Psi.Y y alpha * spacetimeGradient phi y alpha) x (Pi.single mu 1)
      - ∑ mu : Fin (n + 1), ∑ nu : Fin (n + 1), dL_dm L phi m x mu nu *
        (∑ alpha : Fin (n + 1),
          m x alpha nu * fderiv ℝ (fun y => Psi.Y y alpha) x (Pi.single mu 1)
        + ∑ alpha : Fin (n + 1),
          m x mu alpha * fderiv ℝ (fun y => Psi.Y y alpha) x (Pi.single nu 1)
        + ∑ alpha : Fin (n + 1),
          Psi.Y x alpha * fderiv ℝ (fun y => m y mu nu) x (Pi.single alpha 1)) := by

  have hcr := chain_rule_three_arg L
    (fun eps => transformedField Psi phi eps x)
    (fun eps mu => transformedGradient Psi phi eps x mu)
    (fun eps mu nu => transformedMetric Psi m eps x mu nu)
    hL_smooth
    (transformedField_differentiable Psi phi x hphi)
    (transformedGradient_differentiable Psi phi x hphi)
    (transformedMetric_differentiable Psi m x hm)

  simp only [] at hcr
  rw [transformedField_at_zero] at hcr
  rw [show (fun mu => transformedGradient Psi phi 0 x mu) = spacetimeGradient phi x
    from transformedGradient_at_zero Psi phi x] at hcr
  rw [show (fun mu nu => transformedMetric Psi m 0 x mu nu) = m x
    from transformedMetric_at_zero Psi m x] at hcr

  simp only [h_scalar, h_grad, h_metric] at hcr

  rw [hcr]

  unfold dL_dm
  simp only [mul_neg, neg_mul, Finset.sum_neg_distrib]
  ring

/-- CM18 Corollary 2.0.3: the derivative of the Lagrangian along the flow at $\epsilon = 0$,
$\left.\partial_\epsilon\right|_{\epsilon=0} \mathcal{L}(\widetilde{\phi}, \widetilde{\nabla}\widetilde{\phi}, \widetilde{m})
  = -\frac{\partial \mathcal{L}}{\partial \phi} Y^\alpha \nabla_\alpha \phi
    - \frac{\partial \mathcal{L}}{\partial (\nabla_\mu \phi)} \nabla_\mu (Y^\alpha \nabla_\alpha \phi)
    - \frac{\partial \mathcal{L}}{\partial m_{\mu\nu}} (m_{\alpha\nu} \nabla_\mu Y^\alpha
      + m_{\mu\alpha} \nabla_\nu Y^\alpha + Y^\alpha \nabla_\alpha m_{\mu\nu})$. -/
theorem corollary_deriv_L_flow {n : ℕ}
    (L : MetricLagrangian n) (Psi : FlowMap n) (phi : ScalarField n)
    (m : Metric n) (x : Spacetime n)
    (hL_smooth : ContDiff ℝ 2 (fun p : ℝ × (Fin (n + 1) → ℝ) ×
      (Fin (n + 1) → Fin (n + 1) → ℝ) => L p.1 p.2.1 p.2.2))
    (hphi : ContDiff ℝ ⊤ phi)
    (hm : ∀ alpha beta, ContDiff ℝ ⊤ (fun y => m y alpha beta)) :
    deriv (fun eps =>
      L (transformedField Psi phi eps x)
        (fun mu => transformedGradient Psi phi eps x mu)
        (fun mu nu => transformedMetric Psi m eps x mu nu)) 0 =

      -(deriv (fun v => L v (spacetimeGradient phi x) (m x)) (phi x)) *
        (∑ alpha : Fin (n + 1), Psi.Y x alpha * spacetimeGradient phi x alpha)

      - ∑ mu : Fin (n + 1),
        (fderiv ℝ (fun p => L (phi x) p (m x)) (spacetimeGradient phi x)
          (Pi.single mu 1)) *
        fderiv ℝ (fun y => ∑ alpha : Fin (n + 1),
          Psi.Y y alpha * spacetimeGradient phi y alpha) x (Pi.single mu 1)

      - ∑ mu : Fin (n + 1), ∑ nu : Fin (n + 1), dL_dm L phi m x mu nu *
        (∑ alpha : Fin (n + 1),
          m x alpha nu * fderiv ℝ (fun y => Psi.Y y alpha) x (Pi.single mu 1)
        + ∑ alpha : Fin (n + 1),
          m x mu alpha * fderiv ℝ (fun y => Psi.Y y alpha) x (Pi.single nu 1)
        + ∑ alpha : Fin (n + 1),
          Psi.Y x alpha * fderiv ℝ (fun y => m y mu nu) x (Pi.single alpha 1)) := by

  exact flow_algebra_simplification L Psi phi m x hL_smooth
    (flow_deriv_scalar Psi phi hphi x)
    (fun mu => flow_deriv_gradient Psi phi hphi x mu)
    (fun mu nu => flow_deriv_metric Psi m x mu nu hm)
    hphi hm

/-- The energy-momentum tensor associated to a metric Lagrangian:
$T^{\mu\nu}(x) := 2 \frac{\partial \mathcal{L}}{\partial m_{\mu\nu}}
  + (m^{-1})^{\mu\nu} \mathcal{L}(\phi, \nabla\phi, m)$.
This is the canonical "Hilbert" energy-momentum tensor obtained by varying the action with respect
to the metric. -/
def energyMomentumTensor {n : ℕ} (L : MetricLagrangian n) (phi : ScalarField n)
    (m : Metric n) (mInv : InverseMetric n) (x : Spacetime n)
    (mu nu : Fin (n + 1)) : ℝ :=
  2 * dL_dm L phi m x mu nu + mInv x mu nu * L.eval phi m x

/-- Divergence of a tensor field $T$ at a point $x$ in the $\nu$ slot:
$(\nabla \cdot T)^\nu(x) := \sum_\mu \nabla_\mu T^{\mu\nu}(x)$. -/
def tensorDivergence {n : ℕ}
    (T : Spacetime n → Fin (n + 1) → Fin (n + 1) → ℝ)
    (x : Spacetime n) (nu : Fin (n + 1)) : ℝ :=
  ∑ mu : Fin (n + 1),
    fderiv ℝ (fun y => T y mu nu) x (Pi.single mu 1)

/-- A scalar field $\phi$ satisfies the Euler-Lagrange equation for the Lagrangian $\mathcal{L}$
with metric $m$ if the Euler-Lagrange operator vanishes at every spacetime point. -/
def SatisfiesEulerLagrange {n : ℕ} (L : MetricLagrangian n)
    (phi : ScalarField n) (m : Metric n) : Prop :=
  ∀ x : Spacetime n,
    eulerLagrangeOperator (fun v p y => L v p (m y)) phi x = 0

/-- Matrix transpose viewed as an $\mathbb{R}$-linear map $\mathbb{R}^{k \times k} \to \mathbb{R}^{k \times k}$. -/
def matTransposeLM (k : ℕ) : (Fin k → Fin k → ℝ) →ₗ[ℝ] (Fin k → Fin k → ℝ) where
  toFun M := fun i j => M j i
  map_add' x y := by ext i j; simp
  map_smul' c x := by ext i j; simp

/-- Matrix transpose as a continuous $\mathbb{R}$-linear map on $\mathbb{R}^{k \times k}$. -/
def matTransposeCLM (k : ℕ) : (Fin k → Fin k → ℝ) →L[ℝ] (Fin k → Fin k → ℝ) :=
  LinearMap.toContinuousLinearMap (matTransposeLM k)

/-- A symmetric matrix is fixed by transposition: if $M_0$ is symmetric then $M_0^\top = M_0$. -/
lemma matTranspose_symm_eq {k : ℕ} (M₀ : Fin k → Fin k → ℝ)
    (hM₀_symm : ∀ mu nu, M₀ mu nu = M₀ nu mu) :
    matTransposeCLM k M₀ = M₀ := by
  ext i j
  simp [matTransposeCLM, matTransposeLM, LinearMap.toContinuousLinearMap]
  exact hM₀_symm j i

/-- If $f : \mathbb{R}^{(n+1)\times(n+1)} \to \mathbb{R}$ is invariant under transpose and $M_0$ is
a symmetric matrix, then the partial derivatives of $f$ at $M_0$ with respect to the $(\mu,\nu)$
and $(\nu,\mu)$ entries coincide. -/
theorem fderiv_symmetric_at_symm_point {n : ℕ}
    (f : (Fin (n + 1) → Fin (n + 1) → ℝ) → ℝ)
    (M₀ : Fin (n + 1) → Fin (n + 1) → ℝ)
    (hf_symm : ∀ M, f M = f (fun i j => M j i))
    (hM₀_symm : ∀ mu nu, M₀ mu nu = M₀ nu mu)
    (mu nu : Fin (n + 1)) :
    fderiv ℝ f M₀ (fun mu' nu' => if mu' = mu ∧ nu' = nu then 1 else 0) =
    fderiv ℝ f M₀ (fun mu' nu' => if mu' = nu ∧ nu' = mu then 1 else 0) := by

  have hfT : f ∘ (matTransposeCLM (n + 1)) = f := by
    ext M
    simp [Function.comp, matTransposeCLM, matTransposeLM, LinearMap.toContinuousLinearMap]
    exact (hf_symm M).symm

  have hTM₀ : matTransposeCLM (n + 1) M₀ = M₀ := matTranspose_symm_eq M₀ hM₀_symm

  suffices key : ∀ h, fderiv ℝ f M₀ h = fderiv ℝ f M₀ (matTransposeCLM (n + 1) h) by
    rw [key]
    congr 1
    ext i j
    simp [matTransposeCLM, matTransposeLM, LinearMap.toContinuousLinearMap]
    congr 1; exact propext and_comm
  intro h
  by_cases hf_diff : DifferentiableAt ℝ f M₀
  ·
    have hdf_at_TM₀ : DifferentiableAt ℝ f (matTransposeCLM (n + 1) M₀) := by rwa [hTM₀]
    have chain := fderiv_comp M₀ hdf_at_TM₀ (matTransposeCLM (n + 1)).differentiableAt
    rw [hfT] at chain
    rw [ContinuousLinearMap.fderiv, hTM₀] at chain

    conv_lhs => rw [chain]
    simp [ContinuousLinearMap.comp_apply]
  ·
    rw [fderiv_zero_of_not_differentiableAt hf_diff]
    simp

/-- If the Lagrangian $\mathcal{L}$ is invariant under transposing the metric argument and the
metric $m$ is symmetric, then $\partial \mathcal{L} / \partial m_{\mu\nu}$ is symmetric in
$(\mu,\nu)$. -/
theorem dL_dm_symmetric {n : ℕ} (L : MetricLagrangian n) (phi : ScalarField n)
    (m : Metric n) (x : Spacetime n)
    (hm_symm : ∀ y mu nu, m y mu nu = m y nu mu)
    (hL_symm : ∀ v p M, L v p M = L v p (fun i j => M j i))
    (mu nu : Fin (n + 1)) :
    dL_dm L phi m x mu nu = dL_dm L phi m x nu mu := by
  unfold dL_dm
  exact fderiv_symmetric_at_symm_point
    (fun mval => L (phi x) (spacetimeGradient phi x) mval)
    (m x) (fun M => hL_symm (phi x) (spacetimeGradient phi x) M)
    (hm_symm x) mu nu

/-- The energy-momentum tensor is symmetric in $(\mu,\nu)$ whenever the metric, inverse metric, and
Lagrangian (in its metric argument) are all symmetric: $T^{\mu\nu} = T^{\nu\mu}$. -/
theorem energyMomentumTensor_symmetric {n : ℕ}
    (L : MetricLagrangian n) (phi : ScalarField n)
    (m : Metric n) (mInv : InverseMetric n) (x : Spacetime n)
    (hm_symm : ∀ y mu nu, m y mu nu = m y nu mu)
    (hL_symm : ∀ v p M, L v p M = L v p (fun i j => M j i))
    (hmInv_symm : ∀ y mu nu, mInv y mu nu = mInv y nu mu)
    (mu nu : Fin (n + 1)) :
    energyMomentumTensor L phi m mInv x mu nu =
    energyMomentumTensor L phi m mInv x nu mu := by
  unfold energyMomentumTensor
  rw [dL_dm_symmetric L phi m x hm_symm hL_symm mu nu, hmInv_symm x mu nu]

/-- The integration-by-parts computation underlying Noether's theorem in CM18: for a coordinate
invariant Lagrangian, a solution $\phi$ of the Euler-Lagrange equation, and a compactly supported
vector field $Y$, the contracted integral
$\int_K (\nabla \cdot T)_\nu \, m_{\alpha\nu} \, Y^\alpha\, d^{1+n}x = 0$
vanishes. -/
theorem noether_ibp_computation {n : ℕ}
    (L : MetricLagrangian n) (phi : ScalarField n)
    (m : Metric n) (mInv : InverseMetric n)
    (hL_inv : IsCoordinateInvariant L)
    (hL_smooth : ContDiff ℝ 2 (fun p : ℝ × (Fin (n + 1) → ℝ) ×
      (Fin (n + 1) → Fin (n + 1) → ℝ) => L p.1 p.2.1 p.2.2))
    (hphi_smooth : ContDiff ℝ 2 phi)
    (hphi_EL : SatisfiesEulerLagrange L phi m)
    (hmInv : ∀ x, Matrix.of (mInv x) * Matrix.of (m x) =
      (1 : Matrix (Fin (n+1)) (Fin (n+1)) ℝ))
    (hm_symm : ∀ y mu nu, m y mu nu = m y nu mu)
    (K : Set (Spacetime n)) (hK : IsCompact K)
    (Y : Spacetime n → Spacetime n) (hY : ContDiff ℝ ⊤ Y)
    (hY_supp : Function.support Y ⊆ K)
    (nu : Fin (n + 1)) :
    ∫ x in K, (∑ alpha : Fin (n + 1),
      tensorDivergence (energyMomentumTensor L phi m mInv) x nu *
      m x alpha nu * Y x alpha) = 0 := by sorry

/-- Restatement of `noether_ibp_computation` as the Noether integral identity: for any compactly
supported smooth vector field $Y$,
$\int_K (\nabla \cdot T)_\nu \, m_{\alpha\nu} \, Y^\alpha\, d^{1+n}x = 0$. -/
theorem noether_integral_identity {n : ℕ}
    (L : MetricLagrangian n) (phi : ScalarField n)
    (m : Metric n) (mInv : InverseMetric n)
    (hL_inv : IsCoordinateInvariant L)
    (hL_smooth : ContDiff ℝ 2 (fun p : ℝ × (Fin (n + 1) → ℝ) ×
      (Fin (n + 1) → Fin (n + 1) → ℝ) => L p.1 p.2.1 p.2.2))
    (hphi_smooth : ContDiff ℝ 2 phi)
    (hphi_EL : SatisfiesEulerLagrange L phi m)
    (hmInv : ∀ x, Matrix.of (mInv x) * Matrix.of (m x) =
      (1 : Matrix (Fin (n+1)) (Fin (n+1)) ℝ))
    (hm_symm : ∀ y mu nu, m y mu nu = m y nu mu)
    (K : Set (Spacetime n)) (hK : IsCompact K)
    (Y : Spacetime n → Spacetime n) (hY : ContDiff ℝ ⊤ Y)
    (hY_supp : Function.support Y ⊆ K)
    (nu : Fin (n + 1)) :
    ∫ x in K, (∑ alpha : Fin (n + 1),
      tensorDivergence (energyMomentumTensor L phi m mInv) x nu *
      m x alpha nu * Y x alpha) = 0 := by
  exact noether_ibp_computation L phi m mInv hL_inv hL_smooth hphi_smooth
    hphi_EL hmInv hm_symm K hK Y hY hY_supp nu

/-- A contracted du Bois-Reymond / fundamental lemma of the calculus of variations: if for every
compactly supported smooth test vector field $Y$ one has
$\int_K \sum_\alpha f(x) m_{\alpha\nu}(x) Y^\alpha(x)\, d^{1+n}x = 0$,
then $f$ vanishes identically. Uses invertibility of $m$ via $m^{-1}$. -/
theorem duBoisReymond_contracted {n : ℕ}
    (f : Spacetime n → ℝ)
    (m : Metric n) (mInv : InverseMetric n)
    (hmInv : ∀ x, Matrix.of (mInv x) * Matrix.of (m x) =
      (1 : Matrix (Fin (n+1)) (Fin (n+1)) ℝ))
    (nu : Fin (n + 1))
    (hf : ∀ (K : Set (Spacetime n)), IsCompact K →
      ∀ (Y : Spacetime n → Spacetime n), ContDiff ℝ ⊤ Y →
        Function.support Y ⊆ K →
          ∫ x in K, (∑ alpha : Fin (n + 1),
            f x * m x alpha nu * Y x alpha) = 0) :
    ∀ x : Spacetime n, f x = 0 := by sorry

/-- **Noether's theorem (CM18 main result):** for a coordinate-invariant Lagrangian $\mathcal{L}$
and a scalar field $\phi$ satisfying the Euler-Lagrange equation, the energy-momentum tensor is
divergence-free,
$\nabla_\mu T^{\mu\nu}(x) = 0$ for all $x$ and $\nu$. -/
theorem noether_energy_momentum_divergence_free {n : ℕ}
    (L : MetricLagrangian n) (phi : ScalarField n)
    (m : Metric n) (mInv : InverseMetric n)
    (hL_inv : IsCoordinateInvariant L)
    (hL_smooth : ContDiff ℝ 2 (fun p : ℝ × (Fin (n + 1) → ℝ) ×
      (Fin (n + 1) → Fin (n + 1) → ℝ) => L p.1 p.2.1 p.2.2))
    (hphi_smooth : ContDiff ℝ 2 phi)
    (hphi_EL : SatisfiesEulerLagrange L phi m)
    (hmInv : ∀ x, Matrix.of (mInv x) * Matrix.of (m x) =
      (1 : Matrix (Fin (n+1)) (Fin (n+1)) ℝ))
    (hm_symm : ∀ y mu nu, m y mu nu = m y nu mu)
    (x : Spacetime n) (nu : Fin (n + 1)) :
    tensorDivergence (energyMomentumTensor L phi m mInv) x nu = 0 := by
  have key := duBoisReymond_contracted
    (fun x₀ => tensorDivergence (energyMomentumTensor L phi m mInv) x₀ nu)
    m mInv hmInv nu
    (fun K hK Y hY hY_supp =>
      noether_integral_identity L phi m mInv hL_inv hL_smooth hphi_smooth
        hphi_EL hmInv hm_symm K hK Y hY hY_supp nu)
  exact key x

end CM18
