/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.Valuation.ValuationSubring
import Mathlib.Order.KrullDimension
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic

/-- (Definition 18.1) A Noetherian local ring $R$ is regular if its maximal ideal can be generated by $\dim R$ elements (equivalently, $\dim_{R/\mathfrak{m}} \mathfrak{m}/\mathfrak{m}^2 = \dim R$). -/
abbrev IsRegularLocalRing181 (R : Type*) [CommRing R] [IsLocalRing R] [IsNoetherianRing R] : Prop :=
  IsRegularLocalRing R

open Order ValuationSubring

variable {K : Type*} [Field K]


/-- For a valuation subring $R$ of a field $K$, the ring-theoretic Krull dimension of $R$ equals the order-theoretic coheight of $R$ in the lattice of valuation subrings of $K$. -/
lemma ValuationSubring.ringKrullDim_eq_coheight (R : ValuationSubring K) :
    ringKrullDim R = coheight (α := ValuationSubring K) R := by
  unfold ringKrullDim
  rw [← krullDim_orderDual, krullDim_eq_of_orderIso R.primeSpectrumOrderEquiv]
  exact (coheight_eq_krullDim_Ici R).symm

/-- If $R_1 \subsetneq R_2$ is a strict inclusion of valuation subrings of $K$, then $\dim R_1 \geq \dim R_2 + 1$ (a strictly larger valuation ring has strictly smaller Krull dimension). -/
theorem ValuationSubring.ringKrullDim_add_one_le_of_lt {R₁ R₂ : ValuationSubring K}
    (h : R₁ < R₂) : ringKrullDim R₂ + 1 ≤ ringKrullDim R₁ := by
  rw [R₁.ringKrullDim_eq_coheight, R₂.ringKrullDim_eq_coheight]
  exact_mod_cast coheight_add_one_le h

/-- (Nakayama's Lemma, 18.3) For a finitely generated module $M$ over a local ring $(R, \mathfrak{m})$, if $\mathfrak{m} M = M$, then $M = 0$. -/
theorem nakayama_lemma_18_3 {R : Type*} {M : Type*} [CommRing R] [IsLocalRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (h : (IsLocalRing.maximalIdeal R) • (⊤ : Submodule R M) = ⊤) :
    Subsingleton M := by
  have htop : (⊤ : Submodule R M) = ⊥ := by
    apply Submodule.eq_bot_of_le_smul_of_le_jacobson_bot (IsLocalRing.maximalIdeal R)
    · exact Module.Finite.fg_top
    · rw [h]
    · rw [IsLocalRing.jacobson_eq_maximalIdeal]
      exact bot_ne_top
  rw [subsingleton_iff_forall_eq 0]
  intro x
  have hx : x ∈ (⊤ : Submodule R M) := Submodule.mem_top
  rw [htop] at hx
  exact (Submodule.mem_bot R).mp hx
