/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.Buildings.code.Reflection.HyperplaneChambers
import Atlas.Buildings.code.Reflection.WallSeparationCorollary

set_option maxHeartbeats 4000000

open scoped InnerProductSpace
open Set

set_option maxHeartbeats 8000000

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- The monoid homomorphism sending an affine isometry equivalence to its linear part. -/
def linearPartHom : (E ≃ᵃⁱ[ℝ] E) →* (E ≃ₗᵢ[ℝ] E) where
  toFun := AffineIsometryEquiv.linearIsometryEquiv
  map_one' := by ext; rfl
  map_mul' := fun _ _ => by ext; rfl

/-- An affine reflection group on $E$ consists of a subgroup of affine isometries together
with a locally finite hyperplane arrangement that is stable under the group, with each
hyperplane realized as the fixed set of a non-trivial reflection in the group; the group
is generated by these reflections, and parallel reflecting hyperplanes give the same
linear part. -/
structure AffineReflectionGroup (E : Type*) [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] where
  group : Subgroup (E ≃ᵃⁱ[ℝ] E)
  arrangement : HyperplaneArrangement E
  locallyFinite : arrangement.IsLocallyFinite
  stable : ∀ g ∈ group, ∀ η ∈ arrangement.hyperplanes,
    ∃ η' ∈ arrangement.hyperplanes, ∀ x : E, g x ∈ η'.carrier ↔ x ∈ η.carrier
  has_reflection : ∀ η ∈ arrangement.hyperplanes,
    ∃ s ∈ group, (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 ∧ s ≠ 1
  generated_by_reflections :
    group = Subgroup.closure
      {s | s ∈ group ∧ ∃ η ∈ arrangement.hyperplanes,
        (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1}
  parallel_reflections_same_linear_part :
    ∀ s₁ ∈ group, ∀ s₂ ∈ group,
      ∀ η₁ ∈ arrangement.hyperplanes, ∀ η₂ ∈ arrangement.hyperplanes,
      (∀ y ∈ η₁.carrier, s₁ y = y) → s₁ * s₁ = 1 →
      (∀ y ∈ η₂.carrier, s₂ y = y) → s₂ * s₂ = 1 →
      (∃ t : ℝ, η₂.normal = t • η₁.normal) →
      linearPartHom s₁ = linearPartHom s₂

namespace AffineReflectionGroup

variable (W : AffineReflectionGroup E)

/-- An alcove is a chamber of the underlying hyperplane arrangement. -/
def Alcove := W.arrangement.Chamber

/-- A point $x$ is *good* if it lies in the complement of every reflecting hyperplane. -/
def GoodPoint (x : E) : Prop :=
  x ∈ W.arrangement.complement

/-- A point $x$ is *special* if for every hyperplane $η$ of the arrangement there is a
parallel hyperplane $η'$ in the arrangement passing through $x$. -/
def SpecialPoint (x : E) : Prop :=
  ∀ η ∈ W.arrangement.hyperplanes,
    ∃ η' ∈ W.arrangement.hyperplanes,
      (∃ t : ℝ, η'.normal = t • η.normal) ∧ x ∈ η'.carrier

/-- The linear part subgroup is the image of $W$ under the linear-part homomorphism. -/
def LinearPartGroup : Subgroup (E ≃ₗᵢ[ℝ] E) :=
  W.group.map linearPartHom

/-- The translation subgroup of $W$: those elements with trivial linear part. -/
def TranslationSubgroup : Subgroup (E ≃ᵃⁱ[ℝ] E) :=
  W.group ⊓ linearPartHom.ker

/-- The group $W$ is *essential* if its linear part has no nonzero fixed vector. -/
def IsEssential : Prop :=
  ∀ v : E, (∀ wbar ∈ W.LinearPartGroup, wbar v = v) → v = 0

/-- The group $W$ is *indecomposable* if its set of reflections cannot be partitioned into
two pairwise-commuting nonempty subsets. -/
def IsIndecomposable : Prop :=
  let reflections := {s | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
    (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 ∧ s ≠ 1}
  ∀ (S1 S2 : Set (E ≃ᵃⁱ[ℝ] E)),
    S1 ⊆ reflections → S2 ⊆ reflections →
    (∀ s1 ∈ S1, ∀ s2 ∈ S2, s1 * s2 = s2 * s1) →
    S1 ∪ S2 = reflections →
    S1 = ∅ ∨ S2 = ∅

/-- Intersection of $n+1$ open half-spaces $\{x : ⟨n_i, x⟩ > c_i\}$. -/
def openHalfSpaceIntersection (n : ℕ) (normals : Fin (n + 1) → E)
    (offsets : Fin (n + 1) → ℝ) : Set E :=
  ⋂ i, {x : E | ⟪normals i, x⟫_ℝ > offsets i}

/-- Any chamber of a locally finite hyperplane arrangement is an intersection of finitely
many open half-spaces. -/
theorem chamber_eq_halfspace_inter_of_locally_finite
    (arr : HyperplaneArrangement E) (hlf : arr.IsLocallyFinite)
    (C : arr.Chamber) :
    ∃ (m : ℕ) (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ),
      C.set = ⋂ i, {x : E | ⟪normals i, x⟫_ℝ > offsets i} := by sorry

/-- Every alcove is a finite intersection of open half-spaces. -/
theorem alcove_eq_open_halfspace_inter (W : AffineReflectionGroup E)
    (A : W.Alcove) :
    ∃ (m : ℕ) (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ),
      A.set = openHalfSpaceIntersection m normals offsets :=
  chamber_eq_halfspace_inter_of_locally_finite W.arrangement W.locallyFinite A

/-- The set of hyperplanes of the arrangement that separate two chambers $C$ and $D$. -/
def separatingHyperplanes (W : AffineReflectionGroup E)
    (C D : W.arrangement.Chamber) : Set (AffineHyperplane E) :=
  { η ∈ W.arrangement.hyperplanes |
    ∃ c, c ∈ C.set ∧ ∃ d, d ∈ D.set ∧ η.Separates c d }

end AffineReflectionGroup
end

/-- If $s$ is the reflection in a wall $η$ of chamber $C$, and $η$ separates $C$ from $D$,
then $s$ sends $C$ into some chamber $D'$ that is strictly closer to $D$ in the sense of
having fewer separating hyperplanes. -/
theorem AffineReflectionGroup.reflection_of_wall_chamber
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (W : AffineReflectionGroup E) (C D : W.arrangement.Chamber)
    (s : E ≃ᵃⁱ[ℝ] E) (hs_mem : s ∈ W.group)
    (η : AffineHyperplane E) (hη : η ∈ W.arrangement.hyperplanes)
    (hwall : η.IsWall C.set)
    (hfix : ∀ y ∈ η.carrier, s y = y) (hinv : s * s = 1) (hne_id : s ≠ 1)
    (hsep : HyperplaneArrangement.SeparatesChambers η hη C D) :
    ∃ D' : W.arrangement.Chamber,
      (∀ x ∈ C.set, s x ∈ D'.set) ∧
      (W.separatingHyperplanes D' D).ncard < (W.separatingHyperplanes C D).ncard := by sorry

/-- Wall-separation reduction step: given two distinct chambers $C ≠ D$, there exists a
wall-reflection of $C$ that sends $C$ to some chamber $D'$ with strictly fewer separating
hyperplanes from $D$. -/
theorem AffineReflectionGroup.wall_separation_step
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (W : AffineReflectionGroup E) (C D : W.arrangement.Chamber)
    (hne : C.set ≠ D.set) :
    ∃ (s : E ≃ᵃⁱ[ℝ] E)
      (_ : s ∈ W.group)
      (η : AffineHyperplane E) (_ : η ∈ W.arrangement.hyperplanes)
      (_ : η.IsWall C.set)
      (_ : ∀ y ∈ η.carrier, s y = y) (_ : s * s = 1)
      (D' : W.arrangement.Chamber),
      (∀ x ∈ C.set, s x ∈ D'.set) ∧
      (W.separatingHyperplanes D' D).ncard < (W.separatingHyperplanes C D).ncard := by

  obtain ⟨η, hη_mem, hwall, hsep_cd⟩ :=
    HyperplaneArrangement.wall_of_C_separates_distinct_chambers C D hne W.locallyFinite

  obtain ⟨s, hs_mem, hfix, hinv, hne_id⟩ := W.has_reflection η hη_mem

  obtain ⟨D', hmaps, hlt⟩ :=
    AffineReflectionGroup.reflection_of_wall_chamber W C D s hs_mem η hη_mem
      hwall hfix hinv hne_id hsep_cd
  exact ⟨s, hs_mem, η, hη_mem, hwall, hfix, hinv, D', hmaps, hlt⟩

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

namespace AffineReflectionGroup

/-- The interior of an affine hyperplane is empty. -/
theorem hyperplane_carrier_interior_empty (η : AffineHyperplane E) :
    interior η.carrier = ∅ := by
  by_contra h_ne
  obtain ⟨x, hx⟩ := (Set.nonempty_iff_ne_empty.mpr h_ne)
  rw [mem_interior] at hx
  obtain ⟨U, hU_sub, hU_open, hx_mem⟩ := hx
  have hn_norm_pos : 0 < ‖η.normal‖ := norm_pos_iff.mpr η.normal_ne_zero
  rw [Metric.isOpen_iff] at hU_open
  obtain ⟨ε, hε_pos, hball⟩ := hU_open x hx_mem
  set t := ε / (2 * ‖η.normal‖)
  have ht_pos : 0 < t := div_pos hε_pos (mul_pos two_pos hn_norm_pos)
  have h_in_ball : x + t • η.normal ∈ Metric.ball x ε := by
    rw [Metric.mem_ball, dist_eq_norm]
    simp only [add_sub_cancel_left, norm_smul, Real.norm_eq_abs, abs_of_pos ht_pos]
    calc t * ‖η.normal‖ = ε / (2 * ‖η.normal‖) * ‖η.normal‖ := rfl
      _ = ε / 2 := by field_simp
      _ < ε := by linarith
  have h_on_hyp : ⟪η.normal, x + t • η.normal⟫_ℝ = η.offset := by
    have := hU_sub (hball h_in_ball)
    simp only [AffineHyperplane.carrier, Set.mem_setOf_eq] at this
    exact this
  have h_base : ⟪η.normal, x⟫_ℝ = η.offset := by
    have := hU_sub (hball (Metric.mem_ball_self hε_pos))
    simp only [AffineHyperplane.carrier, Set.mem_setOf_eq] at this
    exact this
  rw [inner_add_right, inner_smul_right, real_inner_self_eq_norm_sq, h_base] at h_on_hyp
  linarith [mul_pos ht_pos (pow_pos hn_norm_pos 2)]

/-- Every affine hyperplane is a closed subset of $E$. -/
theorem hyperplane_carrier_isClosed (η : AffineHyperplane E) :
    IsClosed η.carrier := by
  simp only [AffineHyperplane.carrier]
  exact isClosed_eq (Continuous.inner continuous_const continuous_id) continuous_const

/-- A finite union of closed sets with empty interior has empty interior (Baire-type fact). -/
theorem finite_iUnion_empty_interior {X : Type*} [TopologicalSpace X]
    (S : Finset (Set X)) (hclosed : ∀ s ∈ S, IsClosed s) (hint : ∀ s ∈ S, interior s = ∅) :
    interior (⋃ s ∈ S, s) = ∅ := by
  induction S using Finset.cons_induction with
  | empty => simp
  | cons new rest h_not_in ih =>
    have hc_rest : ∀ s ∈ rest, IsClosed s :=
      fun s hs => hclosed s (Finset.mem_cons.mpr (Or.inr hs))
    have hi_rest : ∀ s ∈ rest, interior s = ∅ :=
      fun s hs => hint s (Finset.mem_cons.mpr (Or.inr hs))
    have ih_result := ih hc_rest hi_rest
    have hc_new : IsClosed new := hclosed new (Finset.mem_cons_self _ _)
    have hi_new : interior new = ∅ := hint new (Finset.mem_cons_self _ _)
    have h_eq : (⋃ s ∈ (Finset.cons new rest h_not_in), s) = new ∪ ⋃ s ∈ rest, s := by
      ext x; simp only [Finset.mem_cons, Set.mem_iUnion, Set.mem_union, exists_prop]
      exact ⟨fun ⟨s, hs, hx⟩ => hs.elim (fun h => h ▸ Or.inl hx) (fun h => Or.inr ⟨s, h, hx⟩),
             fun h => h.elim (fun hx => ⟨new, Or.inl rfl, hx⟩)
               (fun ⟨s, hs, hx⟩ => ⟨s, Or.inr hs, hx⟩)⟩
    rw [h_eq]
    by_contra h_ne
    have h_nonempty : (interior (new ∪ ⋃ s ∈ rest, s)).Nonempty := by
      rwa [Set.nonempty_iff_ne_empty]
    obtain ⟨x, hx⟩ := h_nonempty
    rw [mem_interior] at hx
    obtain ⟨U, hU_sub, hU_open, hx_mem⟩ := hx
    have hU_diff_open : IsOpen (U \ new) := hU_open.sdiff hc_new
    by_cases h_diff_ne : (U \ new).Nonempty
    · have hU_diff_sub : U \ new ⊆ ⋃ s ∈ rest, s := by
        intro y hy; exact (hU_sub hy.1).resolve_left hy.2
      have hsub : U \ new ⊆ interior (⋃ s ∈ rest, s) :=
        interior_maximal hU_diff_sub hU_diff_open
      rw [ih_result] at hsub
      exact h_diff_ne.ne_empty (Set.subset_eq_empty hsub rfl)
    · rw [Set.not_nonempty_iff_eq_empty, Set.diff_eq_empty] at h_diff_ne
      have hsub : U ⊆ interior new := interior_maximal h_diff_ne hU_open
      rw [hi_new] at hsub
      exact Set.Nonempty.ne_empty ⟨x, hx_mem⟩ (Set.subset_eq_empty hsub rfl)

/-- There exists a generic point on $η$ that lies on no other hyperplane of the arrangement. -/
lemma exists_generic_point_on_hyperplane
    (W : AffineReflectionGroup E) (η : AffineHyperplane E)
    (hη : η ∈ W.arrangement.hyperplanes) :
    ∃ z₀ : E, z₀ ∈ η.carrier ∧
      ∀ η' ∈ W.arrangement.hyperplanes, η'.carrier ≠ η.carrier → z₀ ∉ η'.carrier := by
  classical
  set p := η.basePoint
  set n := η.normal
  set c_η := η.offset
  have hp : p ∈ η.carrier := η.basePoint_mem_carrier
  have hn_ne : n ≠ 0 := η.normal_ne_zero
  have hnn_pos : (0 : ℝ) < ⟪n, n⟫_ℝ := by
    rw [real_inner_self_eq_norm_sq]; exact sq_pos_of_pos (norm_pos_iff.mpr hn_ne)
  have hnn_ne : ⟪n, n⟫_ℝ ≠ 0 := ne_of_gt hnn_pos

  obtain ⟨ε, hε_pos, hfin⟩ := W.locallyFinite p

  have hε3_pos : (0 : ℝ) < ε / 3 := by linarith
  set nearby := hfin.toFinset

  set other_nearby := nearby.filter (fun η' => η'.carrier ≠ η.carrier)

  let proj_bad_set (η' : AffineHyperplane E) : Set E :=
    {y : E | ⟪η'.normal, y + ((c_η - ⟪n, y⟫_ℝ) / ⟪n, n⟫_ℝ) • n⟫_ℝ = η'.offset}

  set carrier_sets := other_nearby.image (fun η' => η'.carrier)
  set proj_bad_sets := other_nearby.image (fun η' => proj_bad_set η')
  set avoid_sets := carrier_sets ∪ proj_bad_sets

  have h_avoid_closed : ∀ s ∈ avoid_sets, IsClosed s := by
    intro s hs
    simp only [avoid_sets, carrier_sets, proj_bad_sets, Finset.mem_union, Finset.mem_image] at hs
    rcases hs with ⟨η', _, rfl⟩ | ⟨η', _, rfl⟩
    · exact hyperplane_carrier_isClosed η'
    · show IsClosed (proj_bad_set η')
      simp only [proj_bad_set]
      apply isClosed_eq
      · apply Continuous.inner continuous_const
        apply Continuous.add continuous_id
        apply Continuous.smul
        · apply Continuous.div
          · exact continuous_const.sub (Continuous.inner continuous_const continuous_id)
          · exact continuous_const
          · intro _; exact hnn_ne
        · exact continuous_const
      · exact continuous_const

  have h_avoid_int : ∀ s ∈ avoid_sets, interior s = ∅ := by
    intro s hs
    simp only [avoid_sets, carrier_sets, proj_bad_sets, Finset.mem_union, Finset.mem_image] at hs
    rcases hs with ⟨η', hη'_mem, rfl⟩ | ⟨η', hη'_mem, rfl⟩
    · exact hyperplane_carrier_interior_empty η'
    ·
      simp only [other_nearby, Finset.mem_filter] at hη'_mem
      obtain ⟨_, hη'_ne⟩ := hη'_mem
      by_contra h_ne_empty
      set m := η'.normal - (⟪η'.normal, n⟫_ℝ / ⟪n, n⟫_ℝ) • n
      set d := c_η * (⟪η'.normal, n⟫_ℝ / ⟪n, n⟫_ℝ)
      have h_eq : proj_bad_set η' = {y : E | ⟪m, y⟫_ℝ = η'.offset - d} := by
        ext y
        simp only [proj_bad_set, Set.mem_setOf_eq, m, d]
        rw [inner_add_right, inner_smul_right]
        constructor
        · intro h
          have : ⟪η'.normal, y⟫_ℝ + (c_η - ⟪n, y⟫_ℝ) / ⟪n, n⟫_ℝ * ⟪η'.normal, n⟫_ℝ = η'.offset := h
          rw [inner_sub_left, inner_smul_left, conj_trivial] at *
          field_simp at this ⊢
          linarith
        · intro h
          rw [inner_sub_left, inner_smul_left, conj_trivial] at h
          field_simp at h ⊢
          linarith
      rw [h_eq] at h_ne_empty
      by_cases hm : m = 0
      · rw [hm] at h_ne_empty
        simp only [inner_zero_left] at h_ne_empty
        by_cases hd : (0 : ℝ) = η'.offset - d
        · exfalso; apply hη'_ne
          set t := ⟪η'.normal, n⟫_ℝ / ⟪n, n⟫_ℝ
          have hm_eq : η'.normal = t • n := sub_eq_zero.mp hm

          have hd_eq : η'.offset = c_η * t := by
            simp only [d] at hd; linarith
          ext x
          simp only [AffineHyperplane.carrier, Set.mem_setOf_eq]
          rw [hm_eq, inner_smul_left, conj_trivial, hd_eq]
          constructor
          · intro h
            have ht_ne : t ≠ 0 := by
              intro ht; rw [ht, zero_smul] at hm_eq; exact η'.normal_ne_zero hm_eq
            rw [mul_comm c_η t] at h
            exact mul_left_cancel₀ ht_ne h
          · intro h; rw [h, mul_comm]

        · exfalso
          have : {y : E | (0 : ℝ) = η'.offset - d} = ∅ := by
            ext y; simp [hd]
          rw [this, interior_empty] at h_ne_empty
          exact h_ne_empty rfl
      · have h_hyp := hyperplane_carrier_interior_empty
          (AffineHyperplane.mk m (η'.offset - d) hm)
        simp only [AffineHyperplane.carrier] at h_hyp
        exact h_ne_empty h_hyp


  have h_union_int := finite_iUnion_empty_interior avoid_sets h_avoid_closed h_avoid_int

  have h_ball_open : IsOpen (Metric.ball p (ε / 3)) := Metric.isOpen_ball
  have h_ball_ne : (Metric.ball p (ε / 3)).Nonempty := ⟨p, Metric.mem_ball_self hε3_pos⟩
  have h_ball_diff : (Metric.ball p (ε / 3) \ ⋃ s ∈ avoid_sets, s).Nonempty := by
    rw [Set.nonempty_iff_ne_empty]
    intro h_empty
    have hsub : Metric.ball p (ε / 3) ⊆ ⋃ s ∈ avoid_sets, s := Set.diff_eq_empty.mp h_empty
    have hint : Metric.ball p (ε / 3) ⊆ interior (⋃ s ∈ avoid_sets, s) :=
      interior_maximal hsub h_ball_open
    rw [h_union_int] at hint
    exact h_ball_ne.ne_empty (Set.subset_eq_empty hint rfl)
  obtain ⟨y, hy_ball, hy_not_on⟩ := h_ball_diff

  set t₀ := (c_η - ⟪n, y⟫_ℝ) / ⟪n, n⟫_ℝ
  set z₀ := y + t₀ • n

  have hz₀_on : z₀ ∈ η.carrier := by
    simp only [z₀, AffineHyperplane.carrier, Set.mem_setOf_eq,
      inner_add_right, inner_smul_right, t₀]
    rw [div_mul_cancel₀ _ hnn_ne]
    linarith

  have hz₀_ball : z₀ ∈ Metric.ball p ε := by

    have hp_inner : ⟪n, p⟫_ℝ = c_η := by
      have := hp
      simp only [AffineHyperplane.carrier, Set.mem_setOf_eq] at this
      exact this
    have ht₀_eq : t₀ = ⟪n, p - y⟫_ℝ / ⟪n, n⟫_ℝ := by
      simp only [t₀, inner_sub_right, hp_inner]

    have ht_bound : ‖t₀ • n‖ ≤ ‖p - y‖ := by
      rw [ht₀_eq, norm_smul, Real.norm_eq_abs, abs_div, abs_of_pos hnn_pos,
        div_mul_eq_mul_div]
      rw [div_le_iff₀ hnn_pos]
      calc |⟪n, p - y⟫_ℝ| * ‖n‖
          ≤ ‖n‖ * ‖p - y‖ * ‖n‖ := by
            gcongr; exact abs_real_inner_le_norm n (p - y)
        _ = ‖p - y‖ * (‖n‖ * ‖n‖) := by ring
        _ = ‖p - y‖ * ⟪n, n⟫_ℝ := by rw [real_inner_self_eq_norm_sq, sq]

    rw [Metric.mem_ball, dist_eq_norm]
    have h1 : z₀ - p = (y - p) + t₀ • n := by simp only [z₀]; abel
    rw [h1]
    have hy_dist : ‖y - p‖ < ε / 3 := by
      rw [Metric.mem_ball, dist_eq_norm] at hy_ball; exact hy_ball
    calc ‖(y - p) + t₀ • n‖
        ≤ ‖y - p‖ + ‖t₀ • n‖ := norm_add_le _ _
      _ ≤ ‖y - p‖ + ‖p - y‖ := by gcongr
      _ = ‖y - p‖ + ‖y - p‖ := by rw [norm_sub_rev]
      _ = 2 * ‖y - p‖ := by ring
      _ < 2 * (ε / 3) := by linarith
      _ < ε := by linarith

  have hz₀_avoids : ∀ η' ∈ W.arrangement.hyperplanes,
      η'.carrier ≠ η.carrier → z₀ ∉ η'.carrier := by
    intro η' hη'_mem hη'_ne hz₀_on'

    have hy_in_proj : y ∈ proj_bad_set η' := by
      have hz₀_on'' := hz₀_on'
      simp only [proj_bad_set, AffineHyperplane.carrier, Set.mem_setOf_eq] at hz₀_on'' ⊢
      simp only [z₀, t₀] at hz₀_on''
      exact hz₀_on''


    have h_meets : (Metric.ball p ε ∩ η'.carrier).Nonempty := ⟨z₀, hz₀_ball, hz₀_on'⟩

    have h_η'_nearby : η' ∈ nearby := by
      simp only [nearby, Set.Finite.mem_toFinset]
      exact ⟨hη'_mem, h_meets⟩

    have h_η'_other : η' ∈ other_nearby := by
      simp only [other_nearby, Finset.mem_filter]
      exact ⟨h_η'_nearby, hη'_ne⟩

    have h_in_avoid : proj_bad_set η' ∈ avoid_sets := by
      simp only [avoid_sets, Finset.mem_union]
      right
      simp only [proj_bad_sets, Finset.mem_image]
      exact ⟨η', h_η'_other, rfl⟩

    have hy_avoids : y ∉ ⋃ s ∈ avoid_sets, s := hy_not_on
    exact hy_avoids (Set.mem_biUnion h_in_avoid hy_in_proj)
  exact ⟨z₀, hz₀_on, hz₀_avoids⟩

/-- A small half-ball $B(z_0, δ) ∩ η^+$ around a generic point of $η$ lies in a single chamber. -/
lemma half_ball_in_one_chamber
    (arr : HyperplaneArrangement E)
    (η : AffineHyperplane E) (hη : η ∈ arr.hyperplanes)
    (z₀ : E) (hz₀ : z₀ ∈ η.carrier)
    (hz₀_generic : ∀ η' ∈ arr.hyperplanes, η'.carrier ≠ η.carrier → z₀ ∉ η'.carrier)
    (δ : ℝ) (hδ : 0 < δ)
    (hδ_small : ∀ η' ∈ arr.hyperplanes, η'.carrier ≠ η.carrier →
      Metric.ball z₀ δ ∩ η'.carrier = ∅) :
    ∃ C : arr.Chamber,
      Metric.ball z₀ δ ∩ η.positiveHalfSpace ⊆ C.set := by
  classical
  set S := Metric.ball z₀ δ ∩ η.positiveHalfSpace with S_def
  set n := η.normal
  have hn : n ≠ 0 := η.normal_ne_zero
  have hnn_pos : (0 : ℝ) < ⟪n, n⟫_ℝ := by
    rw [real_inner_self_eq_norm_sq]; exact sq_pos_of_pos (norm_pos_iff.mpr hn)
  have hn_pos : (0 : ℝ) < ‖n‖ := norm_pos_iff.mpr hn

  set t := δ / (2 * ‖n‖) with t_def
  have ht_pos : 0 < t := div_pos hδ (mul_pos two_pos hn_pos)
  set y₀ := z₀ + t • n with y₀_def
  have hy₀_ball : y₀ ∈ Metric.ball z₀ δ := by
    rw [Metric.mem_ball, dist_eq_norm, y₀_def, add_sub_cancel_left,
      norm_smul, Real.norm_eq_abs, abs_of_pos ht_pos, t_def]
    have h1 : δ / (2 * ‖n‖) * ‖n‖ = δ * (‖n‖ / (2 * ‖n‖)) := by ring
    rw [h1]
    have h2 : ‖n‖ / (2 * ‖n‖) < 1 := by
      rw [div_lt_one (mul_pos two_pos hn_pos)]; linarith
    have h3 : 0 < ‖n‖ / (2 * ‖n‖) := div_pos hn_pos (mul_pos two_pos hn_pos)
    nlinarith
  have hy₀_pos : y₀ ∈ η.positiveHalfSpace := by
    simp only [AffineHyperplane.positiveHalfSpace, mem_setOf_eq, y₀_def,
      inner_add_right, inner_smul_right]
    have hz₀_inner : ⟪n, z₀⟫_ℝ = η.offset := hz₀
    rw [hz₀_inner]
    linarith [mul_pos ht_pos hnn_pos]
  have hS_ne : S.Nonempty := ⟨y₀, hy₀_ball, hy₀_pos⟩

  have hS_convex : Convex ℝ S := by
    exact (convex_ball z₀ δ).inter
      (convex_halfSpace_gt
        ⟨fun _ _ => inner_add_right _ _ _, fun _ _ => inner_smul_right _ _ _⟩ η.offset)
  have hS_conn : IsConnected S := hS_convex.isConnected hS_ne

  have hS_compl : S ⊆ arr.complement := by
    intro x ⟨hx_ball, hx_pos⟩
    simp only [HyperplaneArrangement.complement, HyperplaneArrangement.unionSet,
      mem_diff, mem_univ, true_and, mem_iUnion]
    intro ⟨η', hη'_mem, hx_on⟩
    by_cases hcarrier : η'.carrier = η.carrier
    ·

      have hx_on_η : x ∈ η.carrier := hcarrier ▸ hx_on
      simp only [AffineHyperplane.carrier, mem_setOf_eq] at hx_on_η
      simp only [AffineHyperplane.positiveHalfSpace, mem_setOf_eq] at hx_pos
      linarith
    ·
      have h_empty := hδ_small η' hη'_mem hcarrier
      have : x ∈ Metric.ball z₀ δ ∩ η'.carrier := ⟨hx_ball, hx_on⟩
      rw [h_empty] at this
      exact this.elim

  have hy₀_mem_S : y₀ ∈ S := ⟨hy₀_ball, hy₀_pos⟩
  have hy₀_compl : y₀ ∈ arr.complement := hS_compl hy₀_mem_S
  refine ⟨{
    set := connectedComponentIn arr.complement y₀
    subset_complement := connectedComponentIn_subset arr.complement y₀
    isConnected := isConnected_connectedComponentIn_iff.mpr hy₀_compl
    is_maximal := fun T hT_sub hT_conn hC_sub => by
      have hy₀_in_T : y₀ ∈ T := hC_sub (mem_connectedComponentIn hy₀_compl)
      exact hT_conn.isPreconnected.subset_connectedComponentIn hy₀_in_T hT_sub
  }, ?_⟩

  exact hS_conn.isPreconnected.subset_connectedComponentIn
    hy₀_mem_S hS_compl

/-- Every hyperplane $η$ of the arrangement is a wall of at least one chamber. -/
theorem hyperplane_is_wall_of_some_chamber
    (W : AffineReflectionGroup E) (η : AffineHyperplane E)
    (hη : η ∈ W.arrangement.hyperplanes) :
    ∃ D : W.arrangement.Chamber, η.IsWall D.set := by
  classical
  set arr := W.arrangement
  set n := η.normal
  have hn : n ≠ 0 := η.normal_ne_zero
  have hnn_pos : (0 : ℝ) < ⟪n, n⟫_ℝ := by
    rw [real_inner_self_eq_norm_sq]; exact sq_pos_of_pos (norm_pos_iff.mpr hn)
  have hn_pos : (0 : ℝ) < ‖n‖ := norm_pos_iff.mpr hn

  obtain ⟨z₀, hz₀_on, hz₀_generic⟩ := exists_generic_point_on_hyperplane W η hη

  obtain ⟨ε, hε_pos, hε_fin⟩ := W.locallyFinite z₀

  set nearby_other : Set (AffineHyperplane E) :=
    {η' ∈ arr.hyperplanes | (Metric.ball z₀ ε ∩ η'.carrier).Nonempty ∧
      η'.carrier ≠ η.carrier} with nearby_other_def
  have h_nearby_fin : nearby_other.Finite :=
    hε_fin.subset (fun η' ⟨hm, hne, _⟩ => ⟨hm, hne⟩)


  have h_infDist_pos : ∀ η' ∈ nearby_other,
      0 < Metric.infDist z₀ η'.carrier := by
    intro η' ⟨hη'_mem, _, hη'_ne⟩
    have : z₀ ∉ η'.carrier := hz₀_generic η' hη'_mem hη'_ne
    exact ((hyperplane_carrier_isClosed η').notMem_iff_infDist_pos
      ⟨η'.basePoint, η'.basePoint_mem_carrier⟩).mp this


  set nearby_finset := h_nearby_fin.toFinset
  have h_mem_iff : ∀ η', η' ∈ nearby_finset ↔ η' ∈ nearby_other :=
    fun η' => h_nearby_fin.mem_toFinset

  have h_exists_δ : ∃ δ > 0, δ ≤ ε ∧
      ∀ η' ∈ nearby_other, δ ≤ Metric.infDist z₀ η'.carrier := by
    by_cases h_ne : nearby_finset.Nonempty
    ·
      set m := nearby_finset.inf' h_ne (fun η' => Metric.infDist z₀ η'.carrier) with m_def
      have hm_pos : 0 < m := by
        rw [Finset.lt_inf'_iff]
        intro η' hη'
        exact h_infDist_pos η' ((h_mem_iff η').mp hη')
      set δ := min ε m / 2
      refine ⟨δ, by positivity, ?_, ?_⟩
      · calc δ = min ε m / 2 := rfl
          _ ≤ ε / 2 := by apply div_le_div_of_nonneg_right (min_le_left _ _) (by positivity)
          _ ≤ ε := by linarith
      · intro η' hη'
        have hη'_fs : η' ∈ nearby_finset := (h_mem_iff η').mpr hη'
        calc δ = min ε m / 2 := rfl
          _ ≤ m / 2 := by apply div_le_div_of_nonneg_right (min_le_right _ _) (by positivity)
          _ ≤ m := by linarith
          _ ≤ Metric.infDist z₀ η'.carrier := Finset.inf'_le _ hη'_fs
    ·
      refine ⟨ε / 2, by linarith, by linarith, ?_⟩
      intro η' hη'
      exfalso
      rw [Finset.not_nonempty_iff_eq_empty] at h_ne
      have : η' ∈ nearby_finset := (h_mem_iff η').mpr hη'
      rw [h_ne] at this
      exact absurd this (Finset.notMem_empty η')
  obtain ⟨δ, hδ_pos, hδ_le_ε, hδ_le_infDist⟩ := h_exists_δ

  have hδ_small : ∀ η' ∈ arr.hyperplanes, η'.carrier ≠ η.carrier →
      Metric.ball z₀ δ ∩ η'.carrier = ∅ := by
    intro η' hη'_mem hη'_ne
    by_cases h_meets : (Metric.ball z₀ ε ∩ η'.carrier).Nonempty
    ·
      have hη'_nearby : η' ∈ nearby_other := ⟨hη'_mem, h_meets, hη'_ne⟩
      have hδ_le := hδ_le_infDist η' hη'_nearby
      rw [Set.eq_empty_iff_forall_notMem]
      intro x ⟨hx_ball, hx_carrier⟩
      have hx_dist : dist z₀ x < δ := Metric.mem_ball'.mp hx_ball
      have hx_infDist : Metric.infDist z₀ η'.carrier ≤ dist z₀ x :=
        Metric.infDist_le_dist_of_mem hx_carrier
      linarith
    ·
      rw [Set.not_nonempty_iff_eq_empty] at h_meets
      rw [Set.eq_empty_iff_forall_notMem]
      intro x ⟨hx_ball, hx_carrier⟩
      have hx_in_big : x ∈ Metric.ball z₀ ε :=
        Metric.ball_subset_ball hδ_le_ε hx_ball
      have : x ∈ Metric.ball z₀ ε ∩ η'.carrier := ⟨hx_in_big, hx_carrier⟩
      rw [h_meets] at this
      exact this.elim

  obtain ⟨C, hC⟩ := half_ball_in_one_chamber arr η hη z₀ hz₀_on hz₀_generic δ hδ_pos hδ_small

  refine ⟨C, Metric.ball z₀ δ, Metric.isOpen_ball, ⟨z₀, ?_, hz₀_on⟩, ?_⟩
  ·
    exact Metric.mem_ball_self hδ_pos
  ·
    intro x ⟨hx_ball, hx_carrier⟩


    rw [Metric.mem_closure_iff]
    intro ε' hε'

    set r := dist x z₀ with r_def
    have hx_in_ball : r < δ := by
      rw [r_def]; exact Metric.mem_ball.mp hx_ball
    set gap := δ - r with gap_def
    have hgap_pos : 0 < gap := by linarith
    set t := min (ε' / (2 * ‖n‖)) (gap / (2 * ‖n‖)) with t_def
    have ht_pos : 0 < t := lt_min
      (div_pos hε' (mul_pos two_pos hn_pos))
      (div_pos hgap_pos (mul_pos two_pos hn_pos))
    set y := x + t • n with y_def

    have hy_ball : y ∈ Metric.ball z₀ δ := by
      rw [Metric.mem_ball]
      calc dist y z₀ ≤ dist y x + dist x z₀ := dist_triangle y x z₀
        _ = ‖t • n‖ + r := by
            rw [dist_eq_norm, y_def, add_sub_cancel_left, r_def]
        _ = t * ‖n‖ + r := by
            rw [norm_smul, Real.norm_eq_abs, abs_of_pos ht_pos]
        _ < gap / (2 * ‖n‖) * ‖n‖ + r + gap / 2 := by
            have : t ≤ gap / (2 * ‖n‖) := min_le_right _ _
            nlinarith
        _ ≤ gap / 2 + r + gap / 2 := by
            have : gap / (2 * ‖n‖) * ‖n‖ = gap / 2 := by
              have := ne_of_gt hn_pos
              field_simp
            linarith
        _ = r + gap := by ring
        _ = δ := by rw [gap_def]; ring

    have hy_pos : y ∈ η.positiveHalfSpace := by
      simp only [AffineHyperplane.positiveHalfSpace, mem_setOf_eq, y_def,
        inner_add_right, inner_smul_right]
      have hx_inner : ⟪n, x⟫_ℝ = η.offset := hx_carrier
      rw [hx_inner]
      linarith [mul_pos ht_pos hnn_pos]

    have hy_C : y ∈ C.set := hC ⟨hy_ball, hy_pos⟩

    have hy_dist : dist y x < ε' := by
      rw [dist_eq_norm, y_def, add_sub_cancel_left, norm_smul,
        Real.norm_eq_abs, abs_of_pos ht_pos]
      calc t * ‖n‖ ≤ (ε' / (2 * ‖n‖)) * ‖n‖ := by
            nlinarith [min_le_left (ε' / (2 * ‖n‖)) (gap / (2 * ‖n‖))]
        _ = ε' / 2 := by have := ne_of_gt hn_pos; field_simp
        _ < ε' := by linarith
    exact ⟨y, hy_C, by rwa [dist_comm]⟩

/-- Conjugating a wall reflection of $D$ by an element $w$ taking $C → D$ lies in the
subgroup generated by wall reflections of $C$. -/
theorem conjugate_wall_reflection
    (W : AffineReflectionGroup E) (C D : W.arrangement.Chamber)
    (w : E ≃ᵃⁱ[ℝ] E) (hw : w ∈ W.group)
    (hw_maps : ∀ x ∈ C.set, w x ∈ D.set)
    (s : E ≃ᵃⁱ[ℝ] E) (hs : s ∈ W.group)
    (η : AffineHyperplane E) (hη : η ∈ W.arrangement.hyperplanes)
    (hη_wall : η.IsWall D.set)
    (hs_fix : ∀ y ∈ η.carrier, s y = y) (hs_inv : s * s = 1) :
    w⁻¹ * s * w ∈ Subgroup.closure
      { t | t ∈ W.group ∧ ∃ ζ ∈ W.arrangement.hyperplanes,
        ζ.IsWall C.set ∧ (∀ y ∈ ζ.carrier, t y = y) ∧ t * t = 1 } := by

  have hw_inv : w⁻¹ ∈ W.group := W.group.inv_mem hw
  obtain ⟨ζ, hζ_mem, hζ_char⟩ := W.stable w⁻¹ hw_inv η hη


  have hζ_equiv : ∀ y, y ∈ ζ.carrier ↔ w y ∈ η.carrier := by
    intro y
    have h := hζ_char (w y)
    rwa [show (w⁻¹ : E ≃ᵃⁱ[ℝ] E) (w y) = y from w.symm_apply_apply y] at h


  have hC_sub : C.set ⊆ (w : E → E) ⁻¹' D.set := fun x hx => hw_maps x hx

  have hpreimage_compl : (w : E → E) ⁻¹' D.set ⊆ W.arrangement.complement := by
    intro x hx

    have hwx_compl := D.subset_complement hx


    rw [HyperplaneArrangement.complement] at hwx_compl ⊢
    simp only [Set.mem_diff, Set.mem_univ, true_and] at hwx_compl ⊢
    intro hx_union
    apply hwx_compl
    rw [HyperplaneArrangement.unionSet] at hx_union ⊢
    simp only [Set.mem_iUnion] at hx_union ⊢
    obtain ⟨ξ, hξ_mem, hx_carrier⟩ := hx_union
    obtain ⟨ξ', hξ'_mem, hξ'_char⟩ := W.stable w hw ξ hξ_mem
    exact ⟨ξ', hξ'_mem, (hξ'_char x).mpr hx_carrier⟩

  have hpreimage_conn : IsConnected ((w : E → E) ⁻¹' D.set) := by
    rw [show (w : E → E) ⁻¹' D.set = w.symm '' D.set from by
      ext x; constructor
      · intro hx; exact ⟨w x, hx, w.symm_apply_apply x⟩
      · intro ⟨d, hd, hxd⟩; rw [← hxd]; show w (w.symm d) ∈ D.set; rwa [w.apply_symm_apply]]
    exact D.isConnected.image (w.symm : E → E) w.symm.continuous.continuousOn

  have hpreimage_sub_C : (w : E → E) ⁻¹' D.set ⊆ C.set :=
    C.is_maximal _ hpreimage_compl hpreimage_conn hC_sub

  have hpreimage_eq : (w : E → E) ⁻¹' D.set = C.set :=
    Set.Subset.antisymm hpreimage_sub_C hC_sub

  apply Subgroup.subset_closure
  refine ⟨?_, ζ, hζ_mem, ?_, ?_, ?_⟩

  · exact W.group.mul_mem (W.group.mul_mem hw_inv hs) hw

  · obtain ⟨U, hU_open, hU_nonempty, hU_sub⟩ := hη_wall
    refine ⟨(w : E → E) ⁻¹' U, hU_open.preimage w.continuous, ?_, ?_⟩
    · obtain ⟨z, hz_U, hz_carrier⟩ := hU_nonempty
      refine ⟨w.symm z, ?_, ?_⟩
      · show w (w.symm z) ∈ U; rw [w.apply_symm_apply]; exact hz_U
      · exact (hζ_equiv _).mpr (by rw [w.apply_symm_apply]; exact hz_carrier)
    · intro y ⟨hy_preimage, hy_carrier⟩
      have hwy_in : w y ∈ U ∩ η.carrier := ⟨hy_preimage, (hζ_equiv y).mp hy_carrier⟩
      have hwy_closure : w y ∈ closure D.set := hU_sub hwy_in

      rw [← hpreimage_eq]


      have hclosure_comm : (w : E → E) ⁻¹' closure D.set = closure ((w : E → E) ⁻¹' D.set) :=
        IsOpenMap.preimage_closure_eq_closure_preimage
          w.toHomeomorph.isOpenMap w.continuous D.set
      rw [← hclosure_comm]

      exact hwy_closure


  · intro y hy
    have hwy : w y ∈ η.carrier := (hζ_equiv y).mp hy
    show (w⁻¹ * s * w) y = y
    change (w⁻¹ : E ≃ᵃⁱ[ℝ] E) (s (w y)) = y
    rw [hs_fix (w y) hwy]
    exact w.symm_apply_apply y

  · ext x
    show (w⁻¹ * s * w * (w⁻¹ * s * w)) x = (1 : E ≃ᵃⁱ[ℝ] E) x
    simp only [AffineIsometryEquiv.coe_mul, Function.comp_apply, AffineIsometryEquiv.coe_one, id]
    show (w⁻¹ : E ≃ᵃⁱ[ℝ] E) (s (w ((w⁻¹ : E ≃ᵃⁱ[ℝ] E) (s (w x))))) = x
    simp only [show (w⁻¹ : E ≃ᵃⁱ[ℝ] E) = w.symm from rfl,
               w.apply_symm_apply, w.symm_apply_apply]

    have h_ss : s (s (w x)) = w x := by
      have h1 : (s * s : E ≃ᵃⁱ[ℝ] E) (w x) = (1 : E ≃ᵃⁱ[ℝ] E) (w x) := by rw [hs_inv]
      simp only [AffineIsometryEquiv.coe_mul, Function.comp_apply,
                  AffineIsometryEquiv.coe_one, id] at h1
      exact h1
    rw [h_ss]
    exact w.symm_apply_apply x

/-- The wall-reflection closure is stable under conjugation by a wall reflection $s$ of
$C$ when $s$ maps $C$ to $D'$. -/
theorem conjugate_in_wall_closure
    (W : AffineReflectionGroup E) (C : W.arrangement.Chamber)
    (s : E ≃ᵃⁱ[ℝ] E)
    (hs_group : s ∈ W.group)
    (hs_wall : ∃ η ∈ W.arrangement.hyperplanes,
      η.IsWall C.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1)
    (D' : W.arrangement.Chamber)
    (hs_maps : ∀ x ∈ C.set, s x ∈ D'.set)
    (w' : E ≃ᵃⁱ[ℝ] E)
    (hw' : w' ∈ Subgroup.closure
      { t | t ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
        η.IsWall D'.set ∧ (∀ y ∈ η.carrier, t y = y) ∧ t * t = 1 }) :
    s * w' * s ∈ Subgroup.closure
      { t | t ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
        η.IsWall C.set ∧ (∀ y ∈ η.carrier, t y = y) ∧ t * t = 1 } := by

  obtain ⟨η_s, hη_s_mem, hη_s_wall, hs_fix, hs_inv⟩ := hs_wall
  have sinv : s⁻¹ = s := inv_eq_of_mul_eq_one_right hs_inv

  set WC := Subgroup.closure
    { t : E ≃ᵃⁱ[ℝ] E | t ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
      η.IsWall C.set ∧ (∀ y ∈ η.carrier, t y = y) ∧ t * t = 1 }

  induction hw' using Subgroup.closure_induction with
  | mem t ht =>

    obtain ⟨ht_group, ζ, hζ_mem, hζ_wall, ht_fix, ht_inv⟩ := ht

    have h := conjugate_wall_reflection W C D' s hs_group hs_maps
      t ht_group ζ hζ_mem hζ_wall ht_fix ht_inv


    rwa [sinv] at h
  | one =>

    rw [mul_one, hs_inv]
    exact WC.one_mem
  | mul x y _ _ hx hy =>

    have key : s * (x * y) * s = (s * x * s) * (s * y * s) := by
      simp only [mul_assoc]
      congr 2
      conv_rhs => rw [← mul_assoc, ← mul_assoc, hs_inv, one_mul]
    rw [key]
    exact WC.mul_mem hx hy
  | inv x _ hx =>

    have key : s * x⁻¹ * s = (s * x * s)⁻¹ := by
      rw [mul_inv_rev, mul_inv_rev, sinv, mul_assoc]
    rw [key]
    exact WC.inv_mem hx

/-- Composition step: combining a wall reflection $s : C → D'$ with an element
$w' : D' → D$ in the wall closure of $D'$ produces an element in the wall closure of $C$
mapping $C → D$. -/
lemma wall_closure_compose_step
    (W : AffineReflectionGroup E) (C D D' : W.arrangement.Chamber)
    (s : E ≃ᵃⁱ[ℝ] E) (hs_group : s ∈ W.group)
    (hs_wall : ∃ η ∈ W.arrangement.hyperplanes,
      η.IsWall C.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1)
    (hs_maps : ∀ x ∈ C.set, s x ∈ D'.set)
    (w' : E ≃ᵃⁱ[ℝ] E)
    (hw'_mem : w' ∈ Subgroup.closure
      { t | t ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
        η.IsWall D'.set ∧ (∀ y ∈ η.carrier, t y = y) ∧ t * t = 1 })
    (hw'_maps : ∀ x ∈ D'.set, w' x ∈ D.set) :
    ∃ w ∈ Subgroup.closure
      { t | t ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
        η.IsWall C.set ∧ (∀ y ∈ η.carrier, t y = y) ∧ t * t = 1 },
      ∀ x ∈ C.set, w x ∈ D.set := by


  set WC := Subgroup.closure
    { t : E ≃ᵃⁱ[ℝ] E | t ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
      η.IsWall C.set ∧ (∀ y ∈ η.carrier, t y = y) ∧ t * t = 1 }

  have hs_in_WC : s ∈ WC := by
    apply Subgroup.subset_closure
    exact ⟨hs_group, hs_wall⟩

  have h_conj : s * w' * s ∈ WC :=
    conjugate_in_wall_closure W C s hs_group hs_wall D' hs_maps w' hw'_mem

  have h_prod : s * (s * w' * s) ∈ WC := WC.mul_mem hs_in_WC h_conj

  have hs_inv : s * s = 1 := by
    obtain ⟨_, _, _, _, h⟩ := hs_wall; exact h
  have h_eq : s * (s * w' * s) = w' * s := by
    have : s * (s * w' * s) = (s * s) * w' * s := by group
    rw [this, hs_inv, one_mul]
  rw [h_eq] at h_prod
  refine ⟨w' * s, h_prod, ?_⟩
  intro x hx
  simp only [AffineIsometryEquiv.coe_mul, Function.comp]
  exact hw'_maps (s x) (hs_maps x hx)

/-- Induction on the number of separating hyperplanes: for any two chambers $A,B$ there
is an element of the wall-reflection closure of $A$ sending $A$ to $B$. -/
lemma wall_closure_transitive_aux
    (W : AffineReflectionGroup E) (n : ℕ) :
    ∀ (A B : W.arrangement.Chamber),
      (W.separatingHyperplanes A B).ncard = n →
      ∃ w ∈ Subgroup.closure
        { s | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
          η.IsWall A.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 },
        ∀ x ∈ A.set, w x ∈ B.set := by
  induction n using Nat.strongRecOn with
  | _ n ih =>
  intro A B hAB
  by_cases heq : A.set = B.set
  ·
    exact ⟨1, Subgroup.one_mem _, fun x hx => by
      simp only [AffineIsometryEquiv.coe_one, id]; rwa [← heq]⟩
  ·
    obtain ⟨s, hs_group, η, hη_mem, hη_wall, hs_fix, hs_inv, D',
            hs_maps, h_fewer⟩ :=
      wall_separation_step W A B heq

    have h_lt : (W.separatingHyperplanes D' B).ncard < n := by omega
    obtain ⟨w', hw'_mem, hw'_maps⟩ := ih _ h_lt D' B rfl

    exact wall_closure_compose_step W A B D' s hs_group
      ⟨η, hη_mem, hη_wall, hs_fix, hs_inv⟩ hs_maps w' hw'_mem hw'_maps

/-- The wall-reflection closure of a chamber $C$ acts transitively on chambers. -/
theorem wall_closure_transitive_on_chambers
    (W : AffineReflectionGroup E) (C D : W.arrangement.Chamber) :
    ∃ w ∈ Subgroup.closure
      { s | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
        η.IsWall C.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 },
      ∀ x ∈ C.set, w x ∈ D.set :=
  wall_closure_transitive_aux W _ C D rfl

/-- Every reflection in $W$ belongs to the subgroup generated by the wall reflections of
a fixed chamber $C$. -/
theorem all_reflections_in_wall_closure
    (W : AffineReflectionGroup E) (C : W.arrangement.Chamber) :
    {s | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
      (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1} ⊆
    ↑(Subgroup.closure
      { s | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
        η.IsWall C.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 }) := by
  intro s ⟨hs_mem, η, hη_hyp, hs_fix, hs_inv⟩

  obtain ⟨D, hD_wall⟩ := hyperplane_is_wall_of_some_chamber W η hη_hyp

  obtain ⟨w, hw_mem, hw_maps⟩ := wall_closure_transitive_on_chambers W C D

  have hw_in_group : w ∈ W.group := by
    apply (Subgroup.closure_le W.group).mpr _ hw_mem
    intro t ht; exact ht.1
  have hconj := conjugate_wall_reflection W C D w
    hw_in_group hw_maps s hs_mem η hη_hyp hD_wall hs_fix hs_inv

  set WC := Subgroup.closure
    { t : E ≃ᵃⁱ[ℝ] E | t ∈ W.group ∧ ∃ ζ ∈ W.arrangement.hyperplanes,
      ζ.IsWall C.set ∧ (∀ y ∈ ζ.carrier, t y = y) ∧ t * t = 1 }
  have hw_inv_mem : w⁻¹ ∈ WC := WC.inv_mem hw_mem
  have : s = w * (w⁻¹ * s * w) * w⁻¹ := by group
  rw [this]
  exact WC.mul_mem (WC.mul_mem hw_mem hconj) hw_inv_mem

/-- For any chamber $C$, the wall reflections of $C$ generate the whole group $W$. -/
theorem wall_reflections_generate_group (W : AffineReflectionGroup E)
    (C : W.arrangement.Chamber) :
    W.group = Subgroup.closure
      { s | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
        η.IsWall C.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 } := by
  set S_wall := { s : E ≃ᵃⁱ[ℝ] E | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
    η.IsWall C.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 }
  set S_all := { s : E ≃ᵃⁱ[ℝ] E | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
    (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 }

  have hgen : W.group = Subgroup.closure S_all := W.generated_by_reflections

  have hwall_sub : S_wall ⊆ ↑W.group := fun s ⟨hs, _⟩ => hs

  have hkey : S_all ⊆ ↑(Subgroup.closure S_wall) :=
    all_reflections_in_wall_closure W C

  apply le_antisymm
  ·
    rw [hgen]
    exact (Subgroup.closure_le _).mpr hkey
  ·
    exact (Subgroup.closure_le _).mpr hwall_sub

/-- The linear part of an isometry fixing an affine hyperplane fixes every vector
orthogonal to the hyperplane normal. -/
theorem linear_part_fixes_hyperplane_direction
    (s : E ≃ᵃⁱ[ℝ] E) (η : AffineHyperplane E)
    (hs_fix : ∀ y ∈ η.carrier, s y = y)
    (hsp : s η.basePoint = η.basePoint) :
    ∀ v : E, ⟪η.normal, v⟫_ℝ = 0 → s.linearIsometryEquiv v = v := by
  intro v hv
  set p := η.basePoint
  have h_pv_mem : p + v ∈ η.carrier := by
    simp only [AffineHyperplane.carrier, Set.mem_setOf_eq, inner_add_right, hv, add_zero]
    exact η.basePoint_mem_carrier
  have h_spv : s (p + v) = p + v := hs_fix (p + v) h_pv_mem
  have h_lin := (AffineIsometryEquiv.map_vsub s (p + v) p).symm
  rw [vsub_eq_sub, vsub_eq_sub, add_sub_cancel_left, hsp, h_spv, add_sub_cancel_left] at h_lin
  exact h_lin.symm

/-- If $A$ is described as the intersection of open half-spaces with given normals, then
the normal of any wall of $A$ is parallel to one of these defining normals. -/
theorem wall_normal_parallel_to_halfspace_normal (W : AffineReflectionGroup E)
    (A : W.Alcove)
    {m : ℕ} (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ)
    (hdesc : A.set = openHalfSpaceIntersection m normals offsets)
    (η : AffineHyperplane E)
    (hη_hyp : η ∈ W.arrangement.hyperplanes)
    (hη_wall : η.IsWall A.set) :
    ∃ i : Fin (m + 1), ∃ c : ℝ, η.normal = c • normals i := by sorry

/-- A vector orthogonal to all defining normals of an alcove $A$ is fixed by every element
of the linear part group $W̄$. -/
theorem wall_normals_ortho_fixed (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) (A : W.Alcove)
    {m : ℕ} (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ)
    (hdesc : A.set = openHalfSpaceIntersection m normals offsets)
    (v : E) (hv : ∀ i, ⟪v, normals i⟫_ℝ = 0) :
    ∀ wbar ∈ W.LinearPartGroup, wbar v = v := by

  set S_wall := { s : E ≃ᵃⁱ[ℝ] E | s ∈ W.group ∧ ∃ η ∈ W.arrangement.hyperplanes,
    η.IsWall A.set ∧ (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 }

  have hgen : W.group = Subgroup.closure S_wall :=
    wall_reflections_generate_group W A


  have hLPG : W.LinearPartGroup = Subgroup.closure (linearPartHom '' S_wall) := by
    unfold LinearPartGroup
    rw [hgen]
    exact MonoidHom.map_closure linearPartHom S_wall


  suffices h_sub : linearPartHom '' S_wall ⊆ ↑({
    carrier := {f : E ≃ₗᵢ[ℝ] E | f v = v}
    one_mem' := by simp [Set.mem_setOf_eq, LinearIsometryEquiv.coe_one]
    mul_mem' := by
      intro a b ha hb
      simp only [Set.mem_setOf_eq] at ha hb ⊢
      simp only [LinearIsometryEquiv.coe_mul, Function.comp_apply, hb, ha]
    inv_mem' := by
      intro a ha
      simp only [Set.mem_setOf_eq] at ha ⊢
      rw [LinearIsometryEquiv.inv_def]
      have : a.symm (a v) = a.symm v := congr_arg a.symm ha
      rw [LinearIsometryEquiv.symm_apply_apply] at this
      exact this.symm

  } : Subgroup (E ≃ₗᵢ[ℝ] E)) by
    intro wbar hwbar
    rw [hLPG] at hwbar
    exact (Subgroup.closure_le _).mpr h_sub hwbar

  rintro f ⟨s, hs_mem, rfl⟩

  obtain ⟨_, η, hη_hyp, hη_wall, hs_fix, _⟩ := hs_mem

  obtain ⟨i, c, hc⟩ := wall_normal_parallel_to_halfspace_normal W A normals offsets hdesc
    η hη_hyp hη_wall


  have h_ortho : ⟪η.normal, v⟫_ℝ = 0 := by
    rw [hc, real_inner_smul_left, real_inner_comm, hv i, mul_zero]

  have hsp : s η.basePoint = η.basePoint :=
    hs_fix η.basePoint η.basePoint_mem_carrier

  show (linearPartHom s) v = v
  simp only [linearPartHom, MonoidHom.coe_mk, OneHom.coe_mk]
  exact linear_part_fixes_hyperplane_direction s η hs_fix hsp v h_ortho

/-- For an essential, indecomposable affine reflection group, the wall normals of any
alcove span $E$. -/
theorem wall_normals_span_top (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) (A : W.Alcove)
    {m : ℕ} (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ)
    (hdesc : A.set = openHalfSpaceIntersection m normals offsets) :
    Submodule.span ℝ (Set.range normals) = ⊤ := by

  set S := Submodule.span ℝ (Set.range normals)
  have hfin : FiniteDimensional ℝ S :=
    FiniteDimensional.span_of_finite ℝ (Set.finite_range normals)
  have hproj : S.HasOrthogonalProjection := inferInstance

  rw [← Submodule.orthogonal_eq_bot_iff (K := S)]
  rw [Submodule.eq_bot_iff]
  intro v hv

  have hv_ortho : ∀ i, ⟪v, normals i⟫_ℝ = 0 := by
    intro i
    rw [Submodule.mem_orthogonal'] at hv
    exact hv (normals i) (Submodule.subset_span ⟨i, rfl⟩)

  have hv_fixed : ∀ wbar ∈ W.LinearPartGroup, wbar v = v :=
    wall_normals_ortho_fixed W hess hind A normals offsets hdesc v hv_ortho

  exact hess v hv_fixed

/-- The linear-combination map sending coefficients $(c_i)$ to $\sum_i c_i n_i$. -/
noncomputable def normalLinearCombinationMap {m : ℕ} (normals : Fin (m + 1) → E) :
    (Fin (m + 1) → ℝ) →ₗ[ℝ] E :=
  Fintype.linearCombination ℝ normals

/-- For an essential, indecomposable group, the kernel of the linear-combination map of
the alcove normals is one-dimensional. -/
theorem indecomposable_normal_ker_one (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) (A : W.Alcove)
    {m : ℕ} (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ)
    (hdesc : A.set = openHalfSpaceIntersection m normals offsets)
    (hspan : Submodule.span ℝ (Set.range normals) = ⊤) :
    Module.finrank ℝ (LinearMap.ker (normalLinearCombinationMap normals)) = 1 := by sorry

/-- If an alcove is bounded by $m+1$ half-spaces in an essential, indecomposable group,
then $\dim E = m$. -/
theorem alcove_normals_finrank (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) (A : W.Alcove)
    {m : ℕ} (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ)
    (hdesc : A.set = openHalfSpaceIntersection m normals offsets) :
    Module.finrank ℝ E = m := by
  have hspan := wall_normals_span_top W hess hind A normals offsets hdesc
  have hker := indecomposable_normal_ker_one W hess hind A normals offsets hdesc hspan

  have hsurj : Function.Surjective (normalLinearCombinationMap normals) :=
    (span_range_eq_top_iff_surjective_fintypeLinearCombination ℝ normals).mp hspan

  haveI : FiniteDimensional ℝ E := Module.Finite.of_surjective _ hsurj

  have hrange : LinearMap.range (normalLinearCombinationMap normals) = ⊤ :=
    LinearMap.range_eq_top.mpr hsurj

  have hrn := LinearMap.finrank_range_add_finrank_ker (normalLinearCombinationMap normals)
  rw [hrange, finrank_top, Module.finrank_fin_fun] at hrn
  linarith

/-- Any $m$ of the $m+1$ alcove normals are linearly independent (general position). -/
theorem alcove_normals_general_position (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) (A : W.Alcove)
    {m : ℕ} (normals : Fin (m + 1) → E) (offsets : Fin (m + 1) → ℝ)
    (hdesc : A.set = openHalfSpaceIntersection m normals offsets) :
    ∀ i : Fin (m + 1), LinearIndependent ℝ (normals ∘ i.succAbove) := by sorry

/-- Full half-space description of an alcove: every alcove is bounded by $n+1$
hyperplanes whose normals span $E$ and are in general position, with $n = \dim E$. -/
theorem alcove_halfspace_description (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) :
    ∀ A : W.Alcove, ∃ (n : ℕ) (normals : Fin (n + 1) → E)
      (offsets : Fin (n + 1) → ℝ),
      Module.finrank ℝ E = n ∧
      Submodule.span ℝ (Set.range normals) = ⊤ ∧
      (∀ i : Fin (n + 1), LinearIndependent ℝ (normals ∘ i.succAbove)) ∧
      A.set = openHalfSpaceIntersection n normals offsets := by
  intro A
  obtain ⟨m, normals, offsets, hdesc⟩ := alcove_eq_open_halfspace_inter W A
  exact ⟨m, normals, offsets,
    alcove_normals_finrank W hess hind A normals offsets hdesc,
    wall_normals_span_top W hess hind A normals offsets hdesc,
    alcove_normals_general_position W hess hind A normals offsets hdesc, hdesc⟩

/-- A nonempty intersection of $n+1$ open half-spaces in $n$-dimensional general position
is the interior of an affine $n$-simplex. -/
theorem spanning_halfspace_intersection_is_simplex
    {n : ℕ} {normals : Fin (n + 1) → E} {offsets : Fin (n + 1) → ℝ}
    (hdim : Module.finrank ℝ E = n)
    (hspan : Submodule.span ℝ (Set.range normals) = ⊤)
    (hgp : ∀ i : Fin (n + 1), LinearIndependent ℝ (normals ∘ i.succAbove))
    (hne : (openHalfSpaceIntersection n normals offsets).Nonempty) :
    ∃ vertices : Fin (n + 1) → E,
      openHalfSpaceIntersection n normals offsets =
        interior (convexHull ℝ (Set.range vertices)) ∧
      AffineIndependent ℝ vertices := by sorry

/-- Every alcove of an essential, indecomposable affine reflection group is the interior
of a simplex spanned by $n+1$ affinely independent vertices, where $n = \dim E$. -/
theorem alcove_is_simplex (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) :
    ∀ A : W.Alcove, ∃ (n : ℕ) (vertices : Fin (n + 1) → E),
      A.set = interior (convexHull ℝ (Set.range vertices)) ∧
      AffineIndependent ℝ vertices := by
  intro A

  obtain ⟨n, normals, offsets, hdim, hspan, hgp, hA_eq⟩ :=
    alcove_halfspace_description W hess hind A

  have hA_ne : A.set.Nonempty := A.isConnected.nonempty
  have hhs_ne : (openHalfSpaceIntersection n normals offsets).Nonempty :=
    hA_eq ▸ hA_ne

  obtain ⟨vertices, hvert_eq, hindep⟩ :=
    spanning_halfspace_intersection_is_simplex hdim hspan hgp hhs_ne
  exact ⟨n, vertices, hA_eq.trans hvert_eq, hindep⟩

/-- The set of walls of a single chamber is finite. -/
theorem walls_finite (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable)
    (C : W.arrangement.Chamber) :
    Set.Finite { η ∈ W.arrangement.hyperplanes | η.IsWall C.set } := by

  obtain ⟨n, vertices, hC_eq, _⟩ := alcove_is_simplex W hess hind
    ⟨C.set, C.subset_complement, C.isConnected, C.is_maximal⟩

  set K := convexHull ℝ (Set.range vertices) with K_def
  have hK_compact : IsCompact K := (Set.finite_range vertices).isCompact_convexHull ℝ
  have hK_closed : IsClosed K := hK_compact.isClosed

  have hC_sub_K : C.set ⊆ K := hC_eq ▸ interior_subset
  have hclosure_sub_K : closure C.set ⊆ K :=
    hK_closed.closure_subset_iff.mpr hC_sub_K


  have hlf := W.locallyFinite
  choose ε hε_pos hε_fin using hlf

  have h_nhds : ∀ x : E, Metric.ball x (ε x) ∈ nhds x :=
    fun x => Metric.ball_mem_nhds x (hε_pos x)

  obtain ⟨centers, hcenters_sub, hcenters_cover⟩ :=
    hK_compact.elim_nhds_subcover (fun x => Metric.ball x (ε x)) (fun x _ => h_nhds x)


  have hfin_meeting_K :
      Set.Finite {η ∈ W.arrangement.hyperplanes | (K ∩ η.carrier).Nonempty} := by
    have : {η ∈ W.arrangement.hyperplanes | (K ∩ η.carrier).Nonempty} ⊆
        ⋃ c ∈ centers, {η ∈ W.arrangement.hyperplanes |
          (Metric.ball c (ε c) ∩ η.carrier).Nonempty} := by
      intro η ⟨hη_mem, z, hz_K, hz_carrier⟩

      have hz_covered := hcenters_cover hz_K
      simp only [Set.mem_iUnion] at hz_covered
      obtain ⟨c, hc_mem, hz_ball⟩ := hz_covered
      exact Set.mem_biUnion hc_mem ⟨hη_mem, z, hz_ball, hz_carrier⟩
    exact Set.Finite.subset
      (Set.Finite.biUnion centers.finite_toSet (fun c _ => hε_fin c)) this

  apply Set.Finite.subset hfin_meeting_K
  intro η ⟨hη_hyp, hη_wall⟩
  refine ⟨hη_hyp, ?_⟩

  obtain ⟨U, _, hU_ne, hU_sub⟩ := hη_wall
  obtain ⟨z, hz_U, hz_carrier⟩ := hU_ne
  exact ⟨z, hclosure_sub_K (hU_sub ⟨hz_U, hz_carrier⟩), hz_carrier⟩

/-- A linear isometry fixing the orthogonal complement of $n$ acts on $n$ by $±1$. -/
theorem involutive_isometry_normal_eigenvalue
    (f : E ≃ₗᵢ[ℝ] E) (n : E) (hn : n ≠ 0)
    (h_fix_hyp : ∀ v : E, ⟪n, v⟫_ℝ = 0 → f v = v) :
    f n = -n ∨ f n = n := by

  have h_span : f n ∈ (ℝ ∙ n) := by
    rw [← Submodule.orthogonal_orthogonal (ℝ ∙ n)]
    rw [Submodule.mem_orthogonal]
    intro w hw
    have hw_orth : ⟪n, w⟫_ℝ = 0 := by
      rwa [Submodule.mem_orthogonal_singleton_iff_inner_right] at hw
    have h_fw : f w = w := h_fix_hyp w hw_orth
    calc ⟪(w : E), (f n : E)⟫_ℝ
        = ⟪f w, f n⟫_ℝ := by rw [h_fw]
      _ = ⟪w, n⟫_ℝ := f.inner_map_map w n
      _ = 0 := by rw [real_inner_comm]; exact hw_orth

  rw [Submodule.mem_span_singleton] at h_span
  obtain ⟨c, hc⟩ := h_span
  have h_nn : (0 : ℝ) < ‖n‖ := norm_pos_iff.mpr hn
  have h_norm : ‖f n‖ = ‖n‖ := f.norm_map n
  rw [← hc, norm_smul, Real.norm_eq_abs] at h_norm
  have h_abs : |c| = 1 := by nlinarith

  have h_cases : c = 1 ∨ c = -1 := by
    cases abs_cases c with
    | inl h => left; linarith [h.1]
    | inr h => right; linarith [h.1]
  rcases h_cases with rfl | rfl
  · right; rw [← hc]; simp
  · left; rw [← hc]; simp

/-- A non-trivial involutive reflection fixing $η$ has fixed-point set exactly $η$. -/
theorem reflection_fixes_iff (s : E ≃ᵃⁱ[ℝ] E) (η : AffineHyperplane E)
    (hs_inv : s * s = 1) (hs_fix : ∀ y ∈ η.carrier, s y = y) (hs_ne : s ≠ 1) :
    ∀ x : E, x ∈ η.carrier ↔ s x = x := by
  set n := η.normal with hn
  set p := η.basePoint with hp_def
  have hp_mem : p ∈ η.carrier := η.basePoint_mem_carrier
  have hsp : s p = p := hs_fix p hp_mem

  have h_fix_hyp : ∀ v : E, ⟪n, v⟫_ℝ = 0 → s.linearIsometryEquiv v = v :=
    linear_part_fixes_hyperplane_direction s η hs_fix hsp

  have h_aff : ∀ x, s x = p + s.linearIsometryEquiv (x - p) := by
    intro x
    have h := (AffineIsometryEquiv.map_vsub s x p).symm
    rw [vsub_eq_sub, vsub_eq_sub, hsp] at h
    rw [← h, add_comm, sub_add_cancel]

  have h_eigen := involutive_isometry_normal_eigenvalue s.linearIsometryEquiv n
    η.normal_ne_zero h_fix_hyp
  intro x
  constructor
  ·
    exact hs_fix x
  ·
    intro hsx

    have h_fix : s.linearIsometryEquiv (x - p) = x - p := by
      have h1 := h_aff x; rw [hsx] at h1
      have h2 : p + s.linearIsometryEquiv (x - p) - p = x - p := by rw [← h1]
      simp only [add_sub_cancel_left] at h2; exact h2


    have h_inner_eq : ⟪s.linearIsometryEquiv n, x - p⟫_ℝ = ⟪n, x - p⟫_ℝ := by
      have h1 := LinearIsometryEquiv.inner_map_map s.linearIsometryEquiv n (x - p)
      rw [h_fix] at h1; exact h1
    have h_inner_zero : ⟪n, x - p⟫_ℝ = 0 := by
      rcases h_eigen with h_neg | h_pos
      ·
        rw [h_neg, inner_neg_left] at h_inner_eq; linarith
      ·

        exfalso
        have h_nn_pos : (0 : ℝ) < ⟪n, n⟫_ℝ := by
          rw [real_inner_self_eq_norm_sq]
          exact sq_pos_of_pos (norm_pos_iff.mpr η.normal_ne_zero)
        have h_lin_id : ∀ v : E, s.linearIsometryEquiv v = v := by
          intro v
          set c := ⟪n, v⟫_ℝ / ⟪n, n⟫_ℝ
          set w := v - c • n
          have hw_orth : ⟪n, w⟫_ℝ = 0 := by
            rw [show w = v - c • n from rfl, inner_sub_right, inner_smul_right,
                show c = ⟪n, v⟫_ℝ / ⟪n, n⟫_ℝ from rfl, div_mul_cancel₀]
            · ring
            · linarith
          have h_decomp : v = c • n + w := by show v = c • n + (v - c • n); abel
          rw [h_decomp, map_add, map_smul, h_pos, h_fix_hyp w hw_orth]
        apply hs_ne
        ext x
        simp only [AffineIsometryEquiv.coe_one, id_eq]
        have h_map := (AffineIsometryEquiv.map_vsub s x p).symm
        rw [vsub_eq_sub, vsub_eq_sub, hsp] at h_map
        rw [h_lin_id (x - p)] at h_map
        have := congr_arg (· + p) h_map
        simp [sub_add_cancel] at this
        exact this

    simp only [AffineHyperplane.carrier, Set.mem_setOf_eq]
    have hp_inner : ⟪n, p⟫_ℝ = η.offset := by
      have := hp_mem; simp only [AffineHyperplane.carrier, Set.mem_setOf_eq] at this; exact this
    have h_split : ⟪n, x⟫_ℝ = ⟪n, p⟫_ℝ + ⟪n, x - p⟫_ℝ := by
      rw [← inner_add_right, show p + (x - p) = x from by abel]
    rw [h_split, h_inner_zero, add_zero, hp_inner]

/-- Any locally finite hyperplane arrangement admits at least one chamber. -/
theorem chamber_exists (arr : HyperplaneArrangement E) (hlf : arr.IsLocallyFinite) :
    Nonempty arr.Chamber := by

  obtain ⟨ε, hε_pos, hfin⟩ := hlf 0

  set nearby := hfin.toFinset with nearby_def

  have h_ball_open : IsOpen (Metric.ball (0 : E) ε) := Metric.isOpen_ball
  have h_ball_ne : (Metric.ball (0 : E) ε).Nonempty := ⟨0, Metric.mem_ball_self hε_pos⟩

  set carrier_set := nearby.image (fun η => η.carrier) with carrier_set_def
  have h_carrier_closed : ∀ s ∈ carrier_set, IsClosed s := by
    intro s hs
    simp only [carrier_set_def, Finset.mem_image] at hs
    obtain ⟨η, _, rfl⟩ := hs
    exact hyperplane_carrier_isClosed η
  have h_carrier_int : ∀ s ∈ carrier_set, interior s = ∅ := by
    intro s hs
    simp only [carrier_set_def, Finset.mem_image] at hs
    obtain ⟨η, _, rfl⟩ := hs
    exact hyperplane_carrier_interior_empty η
  have h_union_int := finite_iUnion_empty_interior carrier_set h_carrier_closed h_carrier_int

  have h_ball_diff : (Metric.ball (0 : E) ε \ ⋃ s ∈ carrier_set, s).Nonempty := by
    rw [Set.nonempty_iff_ne_empty]
    intro h_empty
    have : Metric.ball (0 : E) ε ⊆ ⋃ s ∈ carrier_set, s := Set.diff_eq_empty.mp h_empty
    have : Metric.ball (0 : E) ε ⊆ interior (⋃ s ∈ carrier_set, s) :=
      interior_maximal this h_ball_open
    rw [h_union_int] at this
    exact h_ball_ne.ne_empty (Set.subset_eq_empty this rfl)
  obtain ⟨y, hy_ball, hy_not_on⟩ := h_ball_diff

  have hy_complement : y ∈ arr.complement := by
    simp only [HyperplaneArrangement.complement, HyperplaneArrangement.unionSet,
      Set.mem_diff, Set.mem_univ, true_and, Set.mem_iUnion]
    intro ⟨η, hη_mem, hy_on⟩

    have h_meets : (Metric.ball (0 : E) ε ∩ η.carrier).Nonempty := ⟨y, hy_ball, hy_on⟩

    have h_η_nearby : η ∈ nearby := by
      rw [nearby_def, Set.Finite.mem_toFinset]
      exact ⟨hη_mem, h_meets⟩

    have h_in_carriers : η.carrier ∈ carrier_set := by
      rw [carrier_set_def]
      exact Finset.mem_image_of_mem _ h_η_nearby

    exact hy_not_on (Set.mem_biUnion h_in_carriers hy_on)

  exact ⟨{
    set := connectedComponentIn arr.complement y
    subset_complement := connectedComponentIn_subset arr.complement y
    isConnected := isConnected_connectedComponentIn_iff.mpr hy_complement
    is_maximal := fun S hS_sub hS_conn hC_sub => by

      have hy_in_S : y ∈ S := hC_sub (mem_connectedComponentIn hy_complement)
      exact hS_conn.isPreconnected.subset_connectedComponentIn hy_in_S hS_sub
  }⟩

/-- The reflection across an affine hyperplane is unique: any two non-trivial involutions
fixing the same hyperplane coincide. -/
theorem reflection_unique (s₁ s₂ : E ≃ᵃⁱ[ℝ] E) (η : AffineHyperplane E)
    (h₁_inv : s₁ * s₁ = 1) (h₁_fix : ∀ y ∈ η.carrier, s₁ y = y)
    (h₂_inv : s₂ * s₂ = 1) (h₂_fix : ∀ y ∈ η.carrier, s₂ y = y)
    (h₁_ne : s₁ ≠ 1) (h₂_ne : s₂ ≠ 1) :
    s₁ = s₂ := by
  set n := η.normal
  set p := η.basePoint
  have hp_mem : p ∈ η.carrier := η.basePoint_mem_carrier
  have hs₁p : s₁ p = p := h₁_fix p hp_mem
  have hs₂p : s₂ p = p := h₂_fix p hp_mem

  have h₁_fix_dir : ∀ v : E, ⟪n, v⟫_ℝ = 0 → s₁.linearIsometryEquiv v = v :=
    linear_part_fixes_hyperplane_direction s₁ η h₁_fix hs₁p
  have h₂_fix_dir : ∀ v : E, ⟪n, v⟫_ℝ = 0 → s₂.linearIsometryEquiv v = v :=
    linear_part_fixes_hyperplane_direction s₂ η h₂_fix hs₂p

  have h₁_eigen := involutive_isometry_normal_eigenvalue s₁.linearIsometryEquiv n
    η.normal_ne_zero h₁_fix_dir
  have h₂_eigen := involutive_isometry_normal_eigenvalue s₂.linearIsometryEquiv n
    η.normal_ne_zero h₂_fix_dir

  have h_nn_pos : (0 : ℝ) < ⟪n, n⟫_ℝ := by
    rw [real_inner_self_eq_norm_sq]
    exact sq_pos_of_pos (norm_pos_iff.mpr η.normal_ne_zero)

  have elim_pos : ∀ (s : E ≃ᵃⁱ[ℝ] E),
      (∀ y ∈ η.carrier, s y = y) → s p = p →
      (∀ v : E, ⟪n, v⟫_ℝ = 0 → s.linearIsometryEquiv v = v) →
      s.linearIsometryEquiv n = n → s = 1 := by
    intro s hs_fix hsp h_fix_hyp h_pos
    have h_lin_id : ∀ v : E, s.linearIsometryEquiv v = v := by
      intro v
      set c := ⟪n, v⟫_ℝ / ⟪n, n⟫_ℝ
      set w := v - c • n
      have hw_orth : ⟪n, w⟫_ℝ = 0 := by
        rw [show w = v - c • n from rfl, inner_sub_right, inner_smul_right,
            show c = ⟪n, v⟫_ℝ / ⟪n, n⟫_ℝ from rfl, div_mul_cancel₀]
        · ring
        · linarith
      have h_decomp : v = c • n + w := by show v = c • n + (v - c • n); abel
      rw [h_decomp, map_add, map_smul, h_pos, h_fix_hyp w hw_orth]
    ext x
    simp only [AffineIsometryEquiv.coe_one, id_eq]
    have h_map := (AffineIsometryEquiv.map_vsub s x p).symm
    rw [vsub_eq_sub, vsub_eq_sub, hsp] at h_map
    rw [h_lin_id (x - p)] at h_map
    have := congr_arg (· + p) h_map
    simp [sub_add_cancel] at this
    exact this
  have h₁_neg : s₁.linearIsometryEquiv n = -n := by
    rcases h₁_eigen with h | h
    · exact h
    · exact absurd (elim_pos s₁ h₁_fix hs₁p h₁_fix_dir h) h₁_ne
  have h₂_neg : s₂.linearIsometryEquiv n = -n := by
    rcases h₂_eigen with h | h
    · exact h
    · exact absurd (elim_pos s₂ h₂_fix hs₂p h₂_fix_dir h) h₂_ne

  have h_lin_eq : ∀ v : E, s₁.linearIsometryEquiv v = s₂.linearIsometryEquiv v := by
    intro v
    set c := ⟪n, v⟫_ℝ / ⟪n, n⟫_ℝ
    set w := v - c • n
    have hw_orth : ⟪n, w⟫_ℝ = 0 := by
      rw [show w = v - c • n from rfl, inner_sub_right, inner_smul_right,
          show c = ⟪n, v⟫_ℝ / ⟪n, n⟫_ℝ from rfl, div_mul_cancel₀]
      · ring
      · linarith
    have h_decomp : v = c • n + w := by show v = c • n + (v - c • n); abel
    rw [h_decomp, map_add, map_smul, h₁_neg, h₁_fix_dir w hw_orth,
        map_add, map_smul, h₂_neg, h₂_fix_dir w hw_orth]

  ext x
  have h₁_aff : s₁ x = p + s₁.linearIsometryEquiv (x - p) := by
    have h := (AffineIsometryEquiv.map_vsub s₁ x p).symm
    rw [vsub_eq_sub, vsub_eq_sub, hs₁p] at h
    rw [← h, add_comm, sub_add_cancel]
  have h₂_aff : s₂ x = p + s₂.linearIsometryEquiv (x - p) := by
    have h := (AffineIsometryEquiv.map_vsub s₂ x p).symm
    rw [vsub_eq_sub, vsub_eq_sub, hs₂p] at h
    rw [← h, add_comm, sub_add_cancel]
  rw [h₁_aff, h₂_aff, h_lin_eq]

/-- Main result: an essential, indecomposable affine reflection group has a finite set $S$
of wall reflections of any chosen alcove that satisfies the defining property of a Coxeter
system — each element is an involution in $W$, the set generates $W$, and each element is
the unique reflection across some hyperplane of the arrangement. -/
theorem is_coxeter_system (W : AffineReflectionGroup E)
    (hess : W.IsEssential) (hind : W.IsIndecomposable) :
    ∃ (S : Finset (E ≃ᵃⁱ[ℝ] E)),
      (∀ s ∈ S, s ∈ W.group ∧ s * s = 1) ∧
      Subgroup.closure (S : Set (E ≃ᵃⁱ[ℝ] E)) = W.group ∧
      (∀ s ∈ S, ∃ η ∈ W.arrangement.hyperplanes,
        ∀ x : E, x ∈ η.carrier ↔ s x = x) := by

  obtain ⟨C⟩ := chamber_exists W.arrangement W.locallyFinite

  set wallSet := { η ∈ W.arrangement.hyperplanes | η.IsWall C.set } with wallSet_def
  have hfin_walls : wallSet.Finite := walls_finite W hess hind C


  have wall_has_refl : ∀ η ∈ wallSet,
      ∃ s ∈ W.group, (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 ∧ s ≠ 1 :=
    fun η hη => W.has_reflection η hη.1


  set reflSet : Set (E ≃ᵃⁱ[ℝ] E) :=
    { s | s ∈ W.group ∧ ∃ η ∈ wallSet, (∀ y ∈ η.carrier, s y = y) ∧ s * s = 1 ∧ s ≠ 1 }

  have choose_refl : ∀ η : wallSet, ∃ s : E ≃ᵃⁱ[ℝ] E,
      s ∈ W.group ∧ (∀ y ∈ (η : AffineHyperplane E).carrier, s y = y) ∧ s * s = 1 ∧ s ≠ 1 := by
    intro ⟨η, hη⟩
    exact W.has_reflection η hη.1
  choose refl_of_wall h_refl_of_wall using choose_refl

  set S_set : Set (E ≃ᵃⁱ[ℝ] E) :=
    { s | ∃ (η : wallSet), refl_of_wall η = s } with S_set_def
  have hfin_S : S_set.Finite := by
    have : S_set = Set.range refl_of_wall := by
      ext s; simp [S_set_def]
    rw [this]
    haveI : Finite wallSet := hfin_walls.to_subtype
    exact Set.finite_range refl_of_wall

  refine ⟨hfin_S.toFinset, ?_, ?_, ?_⟩
  ·
    intro s hs
    rw [Set.Finite.mem_toFinset] at hs
    obtain ⟨⟨η, hη⟩, rfl⟩ := hs
    exact ⟨(h_refl_of_wall ⟨η, hη⟩).1, (h_refl_of_wall ⟨η, hη⟩).2.2.1⟩
  ·
    rw [hfin_S.coe_toFinset]


    rw [wall_reflections_generate_group W C]


    apply le_antisymm
    ·
      apply Subgroup.closure_mono
      intro s hs
      obtain ⟨⟨η, hη⟩, rfl⟩ := hs
      refine ⟨(h_refl_of_wall ⟨η, hη⟩).1, η, hη.1, hη.2,
              (h_refl_of_wall ⟨η, hη⟩).2.1, (h_refl_of_wall ⟨η, hη⟩).2.2.1⟩
    ·
      rw [Subgroup.closure_le]
      intro s ⟨hs_mem, η, hη_hyp, hη_wall, hs_fix, hs_inv⟩


      have hη_wall_mem : η ∈ wallSet := ⟨hη_hyp, hη_wall⟩
      by_cases hs_ne : s = 1
      ·
        subst hs_ne
        exact (Subgroup.closure S_set).one_mem
      · have : s = refl_of_wall ⟨η, hη_wall_mem⟩ :=
          reflection_unique s (refl_of_wall ⟨η, hη_wall_mem⟩) η
            hs_inv hs_fix
            (h_refl_of_wall ⟨η, hη_wall_mem⟩).2.2.1
            (h_refl_of_wall ⟨η, hη_wall_mem⟩).2.1
            hs_ne
            (h_refl_of_wall ⟨η, hη_wall_mem⟩).2.2.2
        rw [this]
        exact Subgroup.subset_closure ⟨⟨η, hη_wall_mem⟩, rfl⟩
  ·
    intro s hs
    rw [Set.Finite.mem_toFinset] at hs
    obtain ⟨⟨η, hη⟩, rfl⟩ := hs
    exact ⟨η, hη.1, reflection_fixes_iff _ η
      (h_refl_of_wall ⟨η, hη⟩).2.2.1 (h_refl_of_wall ⟨η, hη⟩).2.1
      (h_refl_of_wall ⟨η, hη⟩).2.2.2⟩

end AffineReflectionGroup

/-- The integer-linear span $\mathbb Z Φ$ of a set of roots $Φ$ is the root lattice. -/
def RootLattice (Φ : Set E) : Submodule ℤ E :=
  Submodule.span ℤ Φ

/-- Data underlying an affine Weyl group: a reduced root system $Φ$ in $E$, the linear
Weyl subgroup, and a coroot lattice stable under the Weyl group. -/
structure AffineWeylGroupData (E : Type*) [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] where
  roots : Set E
  roots_ne_zero : ∀ α ∈ roots, α ≠ 0
  roots_reduced : ∀ α ∈ roots, ∀ t : ℝ, t • α ∈ roots → t = 1 ∨ t = -1
  weylGroup : Subgroup (E ≃ₗᵢ[ℝ] E)
  corootLattice : AddSubgroup E
  weylGroup_stable_corootLattice :
    ∀ w ∈ weylGroup, ∀ v ∈ corootLattice, w v ∈ corootLattice

namespace AffineWeylGroupData

variable (d : AffineWeylGroupData E)

/-- The affine hyperplane arrangement $\{H_{α,k} : α ∈ Φ,\ k ∈ ℤ\}$ associated to the
root system data. -/
def affineArrangement : HyperplaneArrangement E where
  hyperplanes := { η | ∃ α ∈ d.roots, ∃ k : ℤ, η.normal = α ∧ η.offset = ↑k }

end AffineWeylGroupData

namespace AffineReflectionGroup

variable (W : AffineReflectionGroup E)

/-- A point is good iff it lies on no hyperplane of the arrangement. -/
theorem goodPoint_iff_not_on_hyperplanes (x : E) :
    W.GoodPoint x ↔ ∀ η ∈ W.arrangement.hyperplanes, x ∉ η.carrier := by
  simp only [GoodPoint, HyperplaneArrangement.complement,
    HyperplaneArrangement.unionSet, Set.mem_diff, Set.mem_univ, true_and,
    Set.mem_iUnion]
  constructor
  · intro h η hη hx
    exact h ⟨η, hη, hx⟩
  · intro h ⟨η, hη, hx⟩
    exact h η hη hx

/-- The translation subgroup is contained in $W$. -/
theorem translationSubgroup_le_group :
    W.TranslationSubgroup ≤ W.group :=
  inf_le_left

/-- The pointwise stabilizer of $p ∈ E$ inside $W$. -/
def PointStabilizer (p : E) : Subgroup (E ≃ᵃⁱ[ℝ] E) where
  carrier := {g | g ∈ W.group ∧ g p = p}
  mul_mem' := by
    intro a b ⟨haW, hap⟩ ⟨hbW, hbp⟩
    refine ⟨W.group.mul_mem haW hbW, ?_⟩
    show (a * b) p = p
    simp only [AffineIsometryEquiv.coe_mul, Function.comp_apply, hbp, hap]
  one_mem' := ⟨W.group.one_mem, rfl⟩
  inv_mem' := by
    intro a ⟨haW, hap⟩
    refine ⟨W.group.inv_mem haW, ?_⟩
    have h := a.symm_apply_apply p
    rw [hap] at h
    exact h

end AffineReflectionGroup

/-- An affine Weyl group on $E$: a packaging of root-system data with a compatible affine
reflection group whose arrangement is the affine arrangement $\{H_{α,k}\}$ and whose
linear part equals the linear Weyl group. -/
structure AffineWeylGroup (E : Type*) [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] where
  data : AffineWeylGroupData E
  reflGroup : AffineReflectionGroup E
  arrangement_eq : reflGroup.arrangement = data.affineArrangement
  linearPart_eq : reflGroup.LinearPartGroup = data.weylGroup

namespace AffineWeylGroup

variable (Wa : AffineWeylGroup E)

/-- An essential, indecomposable affine Weyl group is an (affine) Coxeter system,
generated by the finitely many wall reflections of an alcove. -/
theorem IsAffineCoxeter
    (hess : Wa.reflGroup.IsEssential) (hind : Wa.reflGroup.IsIndecomposable) :
    ∃ (S : Finset (E ≃ᵃⁱ[ℝ] E)),
      (∀ s ∈ S, s ∈ Wa.reflGroup.group ∧ s * s = 1) ∧
      Subgroup.closure (S : Set (E ≃ᵃⁱ[ℝ] E)) = Wa.reflGroup.group ∧
      (∀ s ∈ S, ∃ η ∈ Wa.reflGroup.arrangement.hyperplanes,
        ∀ x : E, x ∈ η.carrier ↔ s x = x) :=
  AffineReflectionGroup.is_coxeter_system Wa.reflGroup hess hind

end AffineWeylGroup

section SpecialPointInnerProducts

/-- For any special point $z$ and any root $α$, the pairing $⟨α, z⟩$ is an integer. -/
theorem inner_root_specialPoint_int
    (Wa : AffineWeylGroup E)
    (z : E)
    (hz : Wa.reflGroup.SpecialPoint z)
    (α : E) (hα : α ∈ Wa.data.roots) :
    ∃ k : ℤ, ⟪α, z⟫_ℝ = ↑k := by

  have hα_ne : α ≠ 0 := Wa.data.roots_ne_zero α hα
  set η₀ : AffineHyperplane E := ⟨α, 0, hα_ne⟩
  have h_η₀_aff : η₀ ∈ Wa.data.affineArrangement.hyperplanes :=
    ⟨α, hα, 0, rfl, by norm_cast⟩

  have h_η₀_refl : η₀ ∈ Wa.reflGroup.arrangement.hyperplanes := by
    rw [Wa.arrangement_eq]; exact h_η₀_aff

  obtain ⟨η', h_η'_mem, ⟨t, ht_normal⟩, hz_carrier⟩ := hz η₀ h_η₀_refl

  rw [Wa.arrangement_eq] at h_η'_mem
  obtain ⟨α', hα'_root, k', h_normal_eq, h_offset_eq⟩ := h_η'_mem

  simp only [AffineHyperplane.carrier, Set.mem_setOf_eq] at hz_carrier


  have h_alpha'_eq : α' = t • α := by rw [← h_normal_eq, ← ht_normal]
  have h_tα_root : t • α ∈ Wa.data.roots := h_alpha'_eq ▸ hα'_root
  have h_t_cases := Wa.data.roots_reduced α hα t h_tα_root

  rw [h_normal_eq, h_offset_eq] at hz_carrier

  rw [h_alpha'_eq, inner_smul_left] at hz_carrier

  rcases h_t_cases with rfl | rfl
  ·
    simp at hz_carrier
    exact ⟨k', hz_carrier⟩
  ·
    simp at hz_carrier

    exact ⟨-k', by push_cast; linarith⟩

end SpecialPointInnerProducts
