/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.Buildings.code.Reflection.HyperplaneChambers
import Mathlib.Data.Set.Card
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.Nat.Lattice

open scoped InnerProductSpace
open Set

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [CompleteSpace E] [FiniteDimensional ℝ E]

namespace HyperplaneArrangement

/-- The set of all affine reflections through hyperplanes of `arr`, viewed as affine isometries
$E \simeq^{ai}_\mathbb{R} E$. Each element is the orthogonal reflection $s_h$ across some
$h \in arr.hyperplanes$. -/
def reflections (arr : HyperplaneArrangement E) : Set (E ≃ᵃⁱ[ℝ] E) :=
  { g | ∃ h ∈ arr.hyperplanes, g = h.reflectionMap }

/-- The *reflection group* of a hyperplane arrangement: the subgroup of affine isometries
$E \simeq^{ai} E$ generated by all reflections through hyperplanes of `arr`. -/
def ReflectionGroup (arr : HyperplaneArrangement E) : Subgroup (E ≃ᵃⁱ[ℝ] E) :=
  Subgroup.closure arr.reflections

/-- The set of *walls* of a chamber $C$: those hyperplanes of `arr` whose carrier contains a
relatively open piece of the closure of $C$ (i.e. $η$ satisfies `η.IsWall C.set`). -/
def walls (arr : HyperplaneArrangement E) (C : arr.Chamber) :
    Set (AffineHyperplane E) :=
  { η ∈ arr.hyperplanes | η.IsWall C.set }

/-- The set of reflections through the walls of a chamber $C$. These are the Coxeter generators
$s_i$ for the Coxeter system attached to the arrangement. -/
def wallReflections (arr : HyperplaneArrangement E) (C : arr.Chamber) :
    Set (E ≃ᵃⁱ[ℝ] E) :=
  { g | ∃ η ∈ arr.walls C, g = η.reflectionMap }

/-- The subgroup of $E \simeq^{ai} E$ generated by the wall reflections of $C$. A central
theorem (`wallReflections_generate_theorem`) shows this equals the full `ReflectionGroup`. -/
def WallReflectionGroup (arr : HyperplaneArrangement E) (C : arr.Chamber) :
    Subgroup (E ≃ᵃⁱ[ℝ] E) :=
  Subgroup.closure (arr.wallReflections C)

/-- The *Coxeter order* $m_{ij}$ of a pair of reflections: the order of the product $s_i s_j$
inside the group of affine isometries. This is the entry of the Coxeter matrix. -/
def coxeterOrder (sᵢ sⱼ : E ≃ᵃⁱ[ℝ] E) : ℕ :=
  orderOf (sᵢ * sⱼ)

/-- The *Coxeter relation* $(s_i s_j)^{m_{ij}} = 1$ holds for the pair $(s_i, s_j)$. -/
def CoxeterRelation (sᵢ sⱼ : E ≃ᵃⁱ[ℝ] E) : Prop :=
  (sᵢ * sⱼ) ^ coxeterOrder sᵢ sⱼ = 1

/-- The set of hyperplanes of `arr` that strictly separate two points $x, y$ (i.e. $x$ and $y$
lie in opposite open half-spaces of $η$). -/
def separatingHyperplanes (arr : HyperplaneArrangement E) (x y : E) :
    Set (AffineHyperplane E) :=
  { η ∈ arr.hyperplanes | η.Separates x y }

/-- The *gallery distance* between two points $x$ and $y$ is the number of hyperplanes in
`arr` separating them. In a Coxeter arrangement this coincides with the word length of the
unique group element sending the chamber of $x$ to that of $y$. -/
def galleryDistance (arr : HyperplaneArrangement E) (x y : E) : ℕ :=
  (arr.separatingHyperplanes x y).ncard

/-- The *gallery distance* between two chambers $C$ and $D$: the minimum, over $x \in C$ and
$y \in D$, of `galleryDistance x y`. Equivalently the minimum number of walls one must cross
in a chamber-to-chamber path. -/
def chamberGalleryDistance (arr : HyperplaneArrangement E)
    (C D : arr.Chamber) : ℕ :=
  sInf { n : ℕ | ∃ x ∈ C.set, ∃ y ∈ D.set, arr.galleryDistance x y = n }

/-- The image of a set $S \subseteq E$ under an affine isometry $w$. A convenience wrapper for
`w '' S` used throughout the development to talk about the action of reflection-group elements
on chambers. -/
def imageByIsometry (w : E ≃ᵃⁱ[ℝ] E) (S : Set E) : Set E := w '' S

/-- The arrangement *acts on its chambers*: every element of the reflection group sends each
chamber to another chamber. -/
def ActsOnChambers (arr : HyperplaneArrangement E) : Prop :=
  ∀ w ∈ arr.ReflectionGroup,
    ∀ C : arr.Chamber, ∃ D : arr.Chamber, D.set = imageByIsometry w C.set

/-- The action of the reflection group on chambers is *simply transitive*: for any pair of
chambers $C, D$ there is a unique $w$ with $w(C) = D$. This is the key Coxeter property
ensuring chambers are in bijection with group elements. -/
def SimplyTransitive (arr : HyperplaneArrangement E) : Prop :=
  ∀ C D : arr.Chamber,
    ∃! w : arr.ReflectionGroup, imageByIsometry w.val C.set = D.set

/-- A chamber $C$ is a *fundamental domain* for the action of the reflection group on $E$: its
translates by group elements cover $E$ (via closures) and distinct translates of the open
chamber are disjoint. -/
def FundamentalDomain (arr : HyperplaneArrangement E) (C : arr.Chamber) : Prop :=
  (∀ x : E, ∃ w ∈ arr.ReflectionGroup, x ∈ imageByIsometry w (closure C.set)) ∧
  (∀ w₁ w₂ : arr.ReflectionGroup, w₁ ≠ w₂ →
    imageByIsometry w₁.val C.set ∩ imageByIsometry w₂.val C.set = ∅)

/-- A `word` (a list of wall reflections of $C$) *expresses* the element $w$ if all entries
are wall reflections and the list product equals $w$. -/
def IsWordFor (arr : HyperplaneArrangement E) (C : arr.Chamber)
    (word : List (E ≃ᵃⁱ[ℝ] E)) (w : E ≃ᵃⁱ[ℝ] E) : Prop :=
  (∀ s ∈ word, s ∈ arr.wallReflections C) ∧ word.prod = w

/-- The *word length* $\ell(w)$ of an element $w$ relative to the chamber $C$: the minimum
length of a list of wall reflections of $C$ whose product is $w$. By convention $\ell(w) = 0$
when no such list exists (using $\inf \emptyset = 0$ on $\mathbb{N}$). -/
def wordLength (arr : HyperplaneArrangement E) (C : arr.Chamber)
    (w : E ≃ᵃⁱ[ℝ] E) : ℕ :=
  sInf { n : ℕ | ∃ word : List (E ≃ᵃⁱ[ℝ] E),
    arr.IsWordFor C word w ∧ word.length = n }

/-- *Length equals gallery distance*: for every element $w$ of the reflection group and every
$x \in C$, $\ell(w)$ equals the number of hyperplanes separating $x$ from $w(x)$. This is the
hallmark equivalence between algebraic length and geometric distance in a Coxeter system. -/
def LengthEqualsGalleryDistance (arr : HyperplaneArrangement E)
    (C : arr.Chamber) : Prop :=
  ∀ w ∈ arr.ReflectionGroup,
    ∀ x ∈ C.set, arr.wordLength C w = arr.galleryDistance x (w x)

/-- The *Deletion condition* (one of the equivalent axioms of a Coxeter system): if a word in
wall reflections is non-reduced ($\ell(\prod\text{word}) < |\text{word}|$), then we can delete
two of its letters without changing the product. -/
def DeletionCondition (arr : HyperplaneArrangement E) (C : arr.Chamber) : Prop :=
  ∀ (word : List (E ≃ᵃⁱ[ℝ] E)),
    (∀ s ∈ word, s ∈ arr.wallReflections C) →
    arr.wordLength C word.prod < word.length →
    ∃ i j : Fin word.length, i.val < j.val ∧
      ((word.eraseIdx j.val).eraseIdx i.val).prod = word.prod

/-- The *isotropy subgroup* of a point $x \in E$ inside the reflection group: those $w$ in
$ReflectionGroup$ that fix $x$. -/
def isotropyGroup (arr : HyperplaneArrangement E) (x : E) :
    Subgroup (E ≃ᵃⁱ[ℝ] E) where
  carrier := { w ∈ (arr.ReflectionGroup : Set (E ≃ᵃⁱ[ℝ] E)) | w x = x }
  mul_mem' := by
    intro a b ha hb
    simp only [SetLike.mem_coe] at *
    exact ⟨mul_mem ha.1 hb.1, show (a * b) x = x by simp [hb.2, ha.2]⟩
  one_mem' := by
    simp only [SetLike.mem_coe]
    exact ⟨one_mem _, show (1 : E ≃ᵃⁱ[ℝ] E) x = x from rfl⟩
  inv_mem' := by
    intro a ha
    simp only [SetLike.mem_coe] at *
    refine ⟨inv_mem ha.1, ?_⟩
    calc (a⁻¹ : E ≃ᵃⁱ[ℝ] E) x = a⁻¹ (a x) := by rw [ha.2]
      _ = x := by simp [AffineIsometryEquiv.symm_apply_apply]

/-- The set of hyperplanes of `arr` containing the point $x$. -/
def hyperplanesThrough (arr : HyperplaneArrangement E) (x : E) :
    Set (AffineHyperplane E) :=
  { η ∈ arr.hyperplanes | x ∈ η.carrier }

/-- The set of reflections through hyperplanes containing the point $x$ (i.e. those that fix
$x$). Used to describe the isotropy group of $x$. -/
def reflectionsThrough (arr : HyperplaneArrangement E) (x : E) :
    Set (E ≃ᵃⁱ[ℝ] E) :=
  { g | ∃ η ∈ arr.hyperplanesThrough x, g = η.reflectionMap }

/-- *Stabilizers are generated by reflections*: for every point $x$ in the closure of the
fundamental chamber, the isotropy subgroup of $x$ equals the subgroup generated by reflections
through hyperplanes containing $x$. This is the parabolic-subgroup structure of a Coxeter
group. -/
def IsotropyGeneratedByReflections (arr : HyperplaneArrangement E)
    (C : arr.Chamber) : Prop :=
  ∀ x ∈ closure C.set,
    arr.isotropyGroup x = Subgroup.closure (arr.reflectionsThrough x)

/-- A *Coxeter arrangement* is a hyperplane arrangement equipped with the package of axioms
needed to identify the reflection group as a Coxeter group. The axioms include: reflections
permute chambers, are involutions, act transitively (and via wall-reflections) on chambers, are
faithful, the closure of one chamber tiles space, distinct translates of the open chamber are
disjoint, an Exchange property holds, wall reflections in adjacent chambers are conjugate,
length is bounded by gallery distance both above and below, walls of a reduced word fix the
right points, a reflection through a wall of $C$ is a wall of any chamber it produces, wall
reflections fix points of their carriers, and the dihedral subgroups are locally finite (Cartan
integrality). -/
class CoxeterArrangement (arr : HyperplaneArrangement E) where
  reflection_maps_chambers :
    ∀ η ∈ arr.hyperplanes, ∀ C : arr.Chamber,
      ∃ D : arr.Chamber, D.set = imageByIsometry η.reflectionMap C.set
  reflection_involutive :
    ∀ η ∈ arr.hyperplanes, η.reflectionMap * η.reflectionMap = 1
  transitive_on_chambers :
    ∀ C D : arr.Chamber, ∃ w : arr.ReflectionGroup,
      imageByIsometry w.val C.set = D.set
  transitive_via_wall_reflections :
    ∀ C D : arr.Chamber, ∃ w ∈ arr.WallReflectionGroup C,
      imageByIsometry w C.set = D.set
  faithful_on_chambers :
    ∀ (C : arr.Chamber) (w : arr.ReflectionGroup),
      imageByIsometry w.val C.set = C.set → w = ⟨1, one_mem _⟩
  closure_covers :
    ∀ (C : arr.Chamber) (x : E),
      ∃ w ∈ arr.ReflectionGroup, x ∈ imageByIsometry w (closure C.set)
  open_chambers_disjoint :
    ∀ (C : arr.Chamber) (w₁ w₂ : arr.ReflectionGroup), w₁ ≠ w₂ →
      imageByIsometry w₁.val C.set ∩ imageByIsometry w₂.val C.set = ∅
  exchange_property :
    ∀ (C : arr.Chamber) (s : E ≃ᵃⁱ[ℝ] E), s ∈ arr.wallReflections C →
    ∀ (word : List (E ≃ᵃⁱ[ℝ] E)),
      (∀ t ∈ word, t ∈ arr.wallReflections C) →
      arr.IsWordFor C word word.prod →
      arr.wordLength C (s * word.prod) ≤ arr.wordLength C word.prod →
      ∃ i : Fin word.length,
        (s * word.prod) = (word.eraseIdx i.val).prod
  wall_reflection_conjugate :
    ∀ (C : arr.Chamber) (w : E ≃ᵃⁱ[ℝ] E), w ∈ arr.WallReflectionGroup C →
      ∀ (D : arr.Chamber), imageByIsometry w C.set = D.set →
        ∀ t ∈ arr.wallReflections D,
          ∃ s ∈ arr.wallReflections C, t = w * s * w⁻¹
  gallery_upper_bound :
    ∀ (C : arr.Chamber) (word : List (E ≃ᵃⁱ[ℝ] E)),
      (∀ s ∈ word, s ∈ arr.wallReflections C) →
      ∀ x ∈ C.set,
        arr.galleryDistance x (word.prod x) ≤ word.length
  gallery_lower_bound :
    ∀ (C : arr.Chamber) (w : E ≃ᵃⁱ[ℝ] E), w ∈ arr.ReflectionGroup →
      ∀ x ∈ C.set,
        arr.wordLength C w ≤ arr.galleryDistance x (w x)
  closure_wall_membership :
    ∀ (C : arr.Chamber) (s₁ : E ≃ᵃⁱ[ℝ] E) (rest : List (E ≃ᵃⁱ[ℝ] E)),
      s₁ ∈ arr.wallReflections C →
      (∀ t ∈ rest, t ∈ arr.wallReflections C) →
      arr.wordLength C ((s₁ :: rest).prod) = (s₁ :: rest).length →
      ∀ x ∈ closure C.set, (s₁ :: rest).prod x = x →
      ∃ η ∈ arr.walls C, s₁ = η.reflectionMap ∧ x ∈ η.carrier
  reflection_creates_wall :
    ∀ (η : AffineHyperplane E), η ∈ arr.hyperplanes →
      ∀ (C D : arr.Chamber), D.set = imageByIsometry η.reflectionMap C.set →
        η.IsWall D.set
  wall_reflection_fixes_wall_point :
    ∀ (η : AffineHyperplane E), η ∈ arr.hyperplanes →
      ∀ x ∈ η.carrier, η.reflectionMap x = x
  locally_finite :
    ∀ (C : arr.Chamber) (η ζ : AffineHyperplane E),
      η ∈ arr.hyperplanes → ζ ∈ arr.hyperplanes →
      η.IsWall C.set → ζ.IsWall C.set →
      ∃ n : ℤ, (2 : ℝ) * ⟪(‖η.normal‖⁻¹) • η.normal, (‖ζ.normal‖⁻¹) • ζ.normal⟫_ℝ = ↑n

variable {arr : HyperplaneArrangement E} [CoxeterArrangement arr]

/-- An affine isometry $w$ *preserves chambers* if both $w$ and its inverse send every chamber
to a chamber. This is satisfied by every element of the reflection group. -/
def PreservesChambers (arr : HyperplaneArrangement E) (w : E ≃ᵃⁱ[ℝ] E) : Prop :=
  (∀ D : arr.Chamber, ∃ D' : arr.Chamber, D'.set = imageByIsometry w D.set) ∧
  (∀ D : arr.Chamber, ∃ D' : arr.Chamber, D'.set = imageByIsometry w⁻¹ D.set)

/-- *The reflection group acts simply transitively on chambers* in a Coxeter arrangement.
Existence comes from `CoxeterArrangement.transitive_on_chambers`; uniqueness uses the
`faithful_on_chambers` axiom to show that $w'^{-1} w$ fixes $C$ setwise, hence equals $1$. -/
theorem simplyTransitive_theorem : arr.SimplyTransitive := by
  intro C D
  obtain ⟨w, hw⟩ := CoxeterArrangement.transitive_on_chambers (arr := arr) C D
  refine ⟨w, hw, ?_⟩
  intro w' hw'
  have h_fix : w'⁻¹ * w = ⟨1, one_mem _⟩ := by
    apply CoxeterArrangement.faithful_on_chambers C
    show imageByIsometry (↑(w'⁻¹ * w)) C.set = C.set
    ext x; simp only [imageByIsometry, Set.mem_image]
    constructor
    · rintro ⟨y, hy, rfl⟩
      have hwy : (↑w : E ≃ᵃⁱ[ℝ] E) y ∈ D.set := by rw [← hw]; exact ⟨y, hy, rfl⟩
      have : (↑w' : E ≃ᵃⁱ[ℝ] E).symm ((↑w : E ≃ᵃⁱ[ℝ] E) y) ∈ C.set := by
        rw [← hw'] at hwy; obtain ⟨z, hz, hze⟩ := hwy
        rw [show (↑w' : E ≃ᵃⁱ[ℝ] E).symm ((↑w : E ≃ᵃⁱ[ℝ] E) y) =
          (↑w' : E ≃ᵃⁱ[ℝ] E).symm ((↑w' : E ≃ᵃⁱ[ℝ] E) z) from by rw [hze]]
        simp [AffineIsometryEquiv.symm_apply_apply]; exact hz
      convert this using 1
    · intro hx
      refine ⟨(↑w : E ≃ᵃⁱ[ℝ] E).symm ((↑w' : E ≃ᵃⁱ[ℝ] E) x), ?_, ?_⟩
      · have hw'x : (↑w' : E ≃ᵃⁱ[ℝ] E) x ∈ D.set := by rw [← hw']; exact ⟨x, hx, rfl⟩
        rw [← hw] at hw'x; obtain ⟨z, hz, hze⟩ := hw'x
        rw [show (↑w : E ≃ᵃⁱ[ℝ] E).symm ((↑w' : E ≃ᵃⁱ[ℝ] E) x) =
          (↑w : E ≃ᵃⁱ[ℝ] E).symm ((↑w : E ≃ᵃⁱ[ℝ] E) z) from by rw [hze]]
        simp [AffineIsometryEquiv.symm_apply_apply]; exact hz
      · show (↑(w'⁻¹ * w) : E ≃ᵃⁱ[ℝ] E) ((↑w : E ≃ᵃⁱ[ℝ] E).symm ((↑w' : E ≃ᵃⁱ[ℝ] E) x)) = x
        simp [Subgroup.coe_mul]
  have : w = w' := by
    have h1 := congr_arg Subtype.val h_fix
    simp [Subgroup.coe_mul] at h1
    ext1
    calc (w : E ≃ᵃⁱ[ℝ] E) = (↑w' * (↑w')⁻¹) * ↑w := by simp
      _ = ↑w' * ((↑w')⁻¹ * ↑w) := by rw [mul_assoc]
      _ = ↑w' * 1 := by rw [h1]
      _ = ↑w' := by rw [mul_one]
  exact this.symm

/-- *Every chamber is a fundamental domain* of the reflection group in a Coxeter arrangement.
Covering follows from `closure_covers`, disjointness from `open_chambers_disjoint`. -/
theorem fundamentalDomain_theorem (C : arr.Chamber) :
    arr.FundamentalDomain C := by
  constructor
  · intro x; exact CoxeterArrangement.closure_covers C x
  · intro w₁ w₂ hw; exact CoxeterArrangement.open_chambers_disjoint C w₁ w₂ hw

/-- *Wall reflections are involutions*: $s^2 = 1$ for every $s$ in `wallReflections C`. This
follows immediately from `CoxeterArrangement.reflection_involutive` once we extract the
underlying hyperplane $η$. -/
theorem wallReflection_involutive (C : arr.Chamber)
    (s : E ≃ᵃⁱ[ℝ] E) (hs : s ∈ arr.wallReflections C) :
    s * s = 1 := by
  obtain ⟨η, hη_wall, hs_eq⟩ := hs
  subst hs_eq
  exact CoxeterArrangement.reflection_involutive η hη_wall.1

/-- *The deletion condition holds*: in a Coxeter arrangement, every non-reduced expression in
the wall generators admits a deletion of two letters yielding the same product. Proof by
induction on the word, applying the Exchange property to find an index $i$ such that
$s \cdot \text{rest}.\text{prod} = (\text{rest}.\text{eraseIdx}\,i).\text{prod}$. -/
theorem deletionCondition_theorem (C : arr.Chamber) :
    arr.DeletionCondition C := by
  intro word hword hlen
  induction word using List.rec with
  | nil => simp at hlen
  | cons s rest ih =>
    by_cases hrest : arr.wordLength C rest.prod < rest.length
    · have hrest_word : ∀ t ∈ rest, t ∈ arr.wallReflections C :=
        fun t ht => hword t (List.mem_cons_of_mem s ht)
      obtain ⟨i, j, hij, hprod⟩ := ih hrest_word hrest
      refine ⟨⟨i.val + 1, by simp⟩, ⟨j.val + 1, by simp⟩, by simp; omega, ?_⟩
      simp only [List.eraseIdx_cons_succ, List.prod_cons]
      rw [hprod]
    · push Not at hrest
      have hs : s ∈ arr.wallReflections C := hword s (List.mem_cons.mpr (Or.inl rfl))
      have hrest_word : ∀ t ∈ rest, t ∈ arr.wallReflections C :=
        fun t ht => hword t (List.mem_cons_of_mem s ht)
      have hle : arr.wordLength C rest.prod ≤ rest.length := by
        apply Nat.sInf_le; exact ⟨rest, ⟨hrest_word, rfl⟩, rfl⟩
      have hrest_eq : arr.wordLength C rest.prod = rest.length := le_antisymm hle hrest
      have hle2 : arr.wordLength C (s * rest.prod) ≤ arr.wordLength C rest.prod := by
        rw [hrest_eq]
        simp only [List.prod_cons] at hlen
        simp only [List.length_cons] at hlen
        omega
      have hIsWord : arr.IsWordFor C rest rest.prod := ⟨hrest_word, rfl⟩
      obtain ⟨i, hi⟩ := CoxeterArrangement.exchange_property C s hs rest hrest_word hIsWord hle2
      refine ⟨⟨0, by simp⟩, ⟨i.val + 1, by simp⟩, by simp, ?_⟩
      simp only [List.eraseIdx_cons_succ, List.eraseIdx_cons_zero, List.prod_cons]
      exact hi.symm

/-- *Wall reflections of any chamber generate the full reflection group*: $\langle s_i : s_i
\text{ wall of } C\rangle = \text{ReflectionGroup}$. The inclusion $\subseteq$ is immediate;
for $\supseteq$ one uses transitivity-via-wall-reflections and the conjugation axiom
`wall_reflection_conjugate` to express each reflection through any hyperplane as a conjugate
of some wall reflection by an element of $WallReflectionGroup\,C$. -/
theorem wallReflections_generate_theorem (C : arr.Chamber) :
    arr.WallReflectionGroup C = arr.ReflectionGroup := by
  apply le_antisymm
  ·
    apply (Subgroup.closure_le _).mpr
    intro g hg
    obtain ⟨η, hη_wall, hg_eq⟩ := hg
    apply Subgroup.subset_closure
    exact ⟨η, hη_wall.1, hg_eq⟩
  ·
    apply (Subgroup.closure_le _).mpr
    intro g hg
    obtain ⟨η, hη, hg_eq⟩ := hg
    subst hg_eq

    obtain ⟨D, hD⟩ := CoxeterArrangement.reflection_maps_chambers η hη C

    obtain ⟨w, hw_mem, hw_eq⟩ := CoxeterArrangement.transitive_via_wall_reflections C D
    have hD_eq : imageByIsometry w C.set = D.set := hw_eq

    obtain ⟨s, hs, hconj⟩ := CoxeterArrangement.wall_reflection_conjugate C w hw_mem D hD_eq
      η.reflectionMap
      ⟨η, ⟨hη, CoxeterArrangement.reflection_creates_wall η hη C D hD⟩, rfl⟩

    rw [hconj]
    have hs_mem : s ∈ arr.WallReflectionGroup C := Subgroup.subset_closure hs
    exact (arr.WallReflectionGroup C).mul_mem
      ((arr.WallReflectionGroup C).mul_mem hw_mem hs_mem)
      (inv_mem hw_mem)

/-- *Reversing a list of involutions inverts its product*: if every element $s$ of a list `wa`
satisfies $s^2 = 1$ (so $s = s^{-1}$), then $(\text{wa.reverse}).\text{prod} = (\text{wa.prod})
^{-1}$. This is the generic group-theoretic fact behind constructing inverse words from
generators known to be involutive (such as Coxeter generators). -/
lemma reverse_prod_of_involutions {G : Type*} [Group G] (wa : List G)
    (hinv : ∀ s ∈ wa, s * s = 1) :
    wa.reverse.prod = wa.prod⁻¹ := by
  rw [List.prod_reverse_noncomm]
  congr 1
  have hmap : List.map (fun x => x⁻¹) wa = wa := by
    induction wa with
    | nil => simp
    | cons a' rest ih_rest =>
      simp only [List.map_cons]
      congr 1
      · have ha := hinv a' (List.mem_cons.mpr (Or.inl rfl))
        exact mul_left_cancel (a := a') (by rw [ha, mul_inv_cancel])
      · exact ih_rest (fun s hs => hinv s (List.mem_cons.mpr (Or.inr hs)))
  rw [hmap]

/-- *Every element of $WallReflectionGroup C$ is a product of wall reflections of $C$*: by
`Subgroup.closure_induction` over generators, identity, multiplication, and inverses. Inverses
are handled by reversing the word (using `reverse_prod_of_involutions`), since each generator
is an involution. -/
theorem word_exists_for_closure_element (C : arr.Chamber) (w : E ≃ᵃⁱ[ℝ] E)
    (hw : w ∈ arr.WallReflectionGroup C) :
    ∃ word : List (E ≃ᵃⁱ[ℝ] E),
      (∀ s ∈ word, s ∈ arr.wallReflections C) ∧ word.prod = w := by
  have hinv : ∀ s ∈ arr.wallReflections C, s * s = 1 :=
    fun s hs => wallReflection_involutive C s hs
  refine Subgroup.closure_induction
    (p := fun g _ => ∃ word : List (E ≃ᵃⁱ[ℝ] E),
      (∀ s ∈ word, s ∈ arr.wallReflections C) ∧ word.prod = g) ?_ ?_ ?_ ?_ hw
  · intro x hx'; exact ⟨[x], fun s hs => by simp at hs; rwa [hs], by simp⟩
  · exact ⟨[], fun s hs => by simp at hs, by simp⟩
  · intro a b _ _ ⟨wa, hwa_mem, hwa_prod⟩ ⟨wb, hwb_mem, hwb_prod⟩
    exact ⟨wa ++ wb, fun s hs => by
      rw [List.mem_append] at hs
      exact hs.elim (hwa_mem s) (hwb_mem s),
      by rw [List.prod_append, hwa_prod, hwb_prod]⟩
  · intro a _ ⟨wa, hwa_mem, hwa_prod⟩
    refine ⟨wa.reverse, fun s hs => hwa_mem s (List.mem_reverse.mp hs), ?_⟩
    rw [← hwa_prod]
    exact reverse_prod_of_involutions wa (fun s hs => hinv s (hwa_mem s hs))

/-- *Word length equals gallery distance*: for every $w$ in the reflection group and every
$x \in C$, $\ell(w) = d_{\text{gallery}}(x, w(x))$. The lower bound comes from
`gallery_lower_bound`; the upper bound from `gallery_upper_bound` applied to a minimal-length
expression of $w$ in wall reflections of $C$. -/
theorem lengthEqualsGalleryDistance_theorem (C : arr.Chamber) :
    arr.LengthEqualsGalleryDistance C := by
  intro w hw x hx
  apply le_antisymm
  ·
    exact CoxeterArrangement.gallery_lower_bound C w hw x hx
  ·
    apply le_csInf
    ·
      have hw_mem : w ∈ arr.WallReflectionGroup C := by
        rw [wallReflections_generate_theorem C]; exact hw
      obtain ⟨word, hword_mem, hword_prod⟩ := word_exists_for_closure_element C w hw_mem
      exact ⟨word.length, word, ⟨hword_mem, hword_prod⟩, rfl⟩
    · intro n ⟨word, ⟨hword_mem, hword_prod⟩, hword_len⟩
      rw [← hword_len, ← hword_prod]
      exact CoxeterArrangement.gallery_upper_bound C word hword_mem x hx

/-- *Isotropy groups are generated by reflections through containing walls* (the parabolic
subgroup theorem): for each $x$ in the closure of a fundamental chamber, the stabilizer of $x$
in the reflection group equals the subgroup generated by reflections through hyperplanes
containing $x$. The forward direction is by strong induction on word length, peeling off a
fixing initial wall reflection via `closure_wall_membership`. The reverse direction is
immediate from `wall_reflection_fixes_wall_point`. -/
theorem isotropyGeneratedByReflections_theorem (C : arr.Chamber) :
    arr.IsotropyGeneratedByReflections C := by
  intro x hx
  apply le_antisymm
  ·


    intro w hw_iso

    have hw_mem : w ∈ arr.ReflectionGroup := hw_iso.1
    have hw_fix : w x = x := hw_iso.2

    have hw_wall : w ∈ arr.WallReflectionGroup C := by
      rw [wallReflections_generate_theorem C]; exact hw_mem

    suffices key : ∀ (n : ℕ) (g : E ≃ᵃⁱ[ℝ] E),
        g ∈ arr.WallReflectionGroup C →
        g x = x →
        arr.wordLength C g = n →
        g ∈ Subgroup.closure (arr.reflectionsThrough x) by
      exact key (arr.wordLength C w) w hw_wall hw_fix rfl
    intro n
    induction n using Nat.strongRecOn with
    | _ n ih =>
    intro g hg_wall hg_fix hg_len
    by_cases hn : n = 0
    ·
      subst hn
      have hne : { n : ℕ | ∃ word : List (E ≃ᵃⁱ[ℝ] E),
          arr.IsWordFor C word g ∧ word.length = n }.Nonempty := by
        obtain ⟨word, hword_mem, hword_prod⟩ := word_exists_for_closure_element C g hg_wall
        exact ⟨word.length, word, ⟨hword_mem, hword_prod⟩, rfl⟩
      have h0 : arr.wordLength C g ∈ { n : ℕ | ∃ word : List (E ≃ᵃⁱ[ℝ] E),
          arr.IsWordFor C word g ∧ word.length = n } := Nat.sInf_mem hne
      rw [hg_len] at h0
      obtain ⟨word, ⟨_, hword_prod⟩, hword_len⟩ := h0
      have hnil : word = [] := List.eq_nil_of_length_eq_zero hword_len
      subst hnil
      simp at hword_prod
      rw [← hword_prod]
      exact one_mem _
    ·

      have hne : { k : ℕ | ∃ word : List (E ≃ᵃⁱ[ℝ] E),
          arr.IsWordFor C word g ∧ word.length = k }.Nonempty := by
        obtain ⟨word, hword_mem, hword_prod⟩ := word_exists_for_closure_element C g hg_wall
        exact ⟨word.length, word, ⟨hword_mem, hword_prod⟩, rfl⟩
      have h_in : arr.wordLength C g ∈ { k : ℕ | ∃ word : List (E ≃ᵃⁱ[ℝ] E),
          arr.IsWordFor C word g ∧ word.length = k } := Nat.sInf_mem hne
      rw [hg_len] at h_in
      obtain ⟨word, ⟨hword_wall, hword_prod⟩, hword_len⟩ := h_in

      obtain ⟨s₁, rest, rfl⟩ : ∃ s₁ rest, word = s₁ :: rest := by
        cases word with
        | nil => simp at hword_len; omega
        | cons h t => exact ⟨h, t, rfl⟩
      simp only [List.length_cons] at hword_len
      have hs₁ : s₁ ∈ arr.wallReflections C :=
        hword_wall s₁ (List.mem_cons.mpr (Or.inl rfl))
      have hrest_wall : ∀ t ∈ rest, t ∈ arr.wallReflections C :=
        fun t ht => hword_wall t (List.mem_cons.mpr (Or.inr ht))

      have hreduced : arr.wordLength C ((s₁ :: rest).prod) = (s₁ :: rest).length := by
        rw [hword_prod, hg_len]; simp [hword_len]


      have hg_eq : (s₁ :: rest).prod = g := hword_prod
      obtain ⟨η₁, hη₁_wall, hs₁_eq, hx_in⟩ :=
        CoxeterArrangement.closure_wall_membership C s₁ rest hs₁ hrest_wall
          hreduced x hx (by rw [hg_eq, hg_fix])

      have hs₁_fix : s₁ x = x := by
        rw [hs₁_eq]
        exact CoxeterArrangement.wall_reflection_fixes_wall_point η₁ hη₁_wall.1 x hx_in

      have hs₁_refl_through : s₁ ∈ arr.reflectionsThrough x :=
        ⟨η₁, ⟨hη₁_wall.1, hx_in⟩, hs₁_eq⟩

      have hs₁_in_closure : s₁ ∈ Subgroup.closure (arr.reflectionsThrough x) :=
        Subgroup.subset_closure hs₁_refl_through

      have hs₁g_eq : s₁ * g = rest.prod := by
        rw [← hg_eq]
        simp only [List.prod_cons]
        rw [← mul_assoc]
        have : s₁ * s₁ = 1 := wallReflection_involutive C s₁ hs₁
        rw [this, one_mul]

      have hs₁g_fix : (s₁ * g) x = x := by
        show s₁ (g x) = x
        rw [hg_fix, hs₁_fix]

      have hs₁g_wall : s₁ * g ∈ arr.WallReflectionGroup C :=
        (arr.WallReflectionGroup C).mul_mem (Subgroup.subset_closure hs₁) hg_wall

      have hs₁g_len : arr.wordLength C (s₁ * g) ≤ rest.length := by
        rw [hs₁g_eq]
        apply Nat.sInf_le
        exact ⟨rest, ⟨hrest_wall, rfl⟩, rfl⟩
      have hrest_len : rest.length = n - 1 := by omega
      have hs₁g_lt : arr.wordLength C (s₁ * g) < n := by omega

      have hs₁g_in : s₁ * g ∈ Subgroup.closure (arr.reflectionsThrough x) :=
        ih (arr.wordLength C (s₁ * g)) hs₁g_lt (s₁ * g) hs₁g_wall hs₁g_fix rfl


      have hg_decomp : g = s₁ * (s₁ * g) := by
        rw [← mul_assoc]
        have : s₁ * s₁ = 1 := wallReflection_involutive C s₁ hs₁
        rw [this, one_mul]
      rw [hg_decomp]
      exact (Subgroup.closure (arr.reflectionsThrough x)).mul_mem hs₁_in_closure hs₁g_in
  ·

    apply (Subgroup.closure_le _).mpr
    intro g hg
    obtain ⟨η, ⟨hη_hyp, hη_mem⟩, hg_eq⟩ := hg
    simp only [SetLike.mem_coe]
    constructor
    · rw [hg_eq]
      exact Subgroup.subset_closure ⟨η, hη_hyp, rfl⟩
    · rw [hg_eq]
      exact CoxeterArrangement.wall_reflection_fixes_wall_point η hη_hyp x hη_mem

/-- A hyperplane arrangement $(arr, C)$ *forms a Coxeter system* (relative to a fundamental
chamber $C$) if all five canonical properties hold: simple transitivity, fundamental-domain
property, length = gallery distance, deletion condition, and isotropy generated by
reflections. The theorems above show every `CoxeterArrangement` satisfies this conjunction. -/
def IsCoxeterSystem (arr : HyperplaneArrangement E)
    (C : arr.Chamber) : Prop :=
  arr.SimplyTransitive ∧
  arr.FundamentalDomain C ∧
  arr.LengthEqualsGalleryDistance C ∧
  arr.DeletionCondition C ∧
  arr.IsotropyGeneratedByReflections C

end HyperplaneArrangement
