/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.Henselian
import Mathlib.NumberTheory.Padics.PadicIntegers
import Mathlib.LinearAlgebra.FreeModule.Basic
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.Algebra.Polynomial.Taylor
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.Topology.MetricSpace.Ultra.Basic
import Mathlib.Analysis.Normed.Field.Basic

open Polynomial Matrix


section PadicNumbers

variable (p : ℕ) [hp : Fact (Nat.Prime p)]

example : IsDiscreteValuationRing ℤ_[p] := PadicInt.instIsDiscreteValuationRing

example : IsLocalRing ℤ_[p] := inferInstance

example : IsDomain ℤ_[p] := inferInstance

end PadicNumbers


/-- *Discrete valuation context*: a bundle of data describing a discrete valuation field. It
consists of a field $k$, an integral domain $\mathfrak{o}$ (the ring of integers), an
injective ring embedding $\mathfrak{o} \hookrightarrow k$, a chosen uniformizer
$\pi \in \mathfrak{o}$ generating the maximal ideal, and a positive integer $n$ specifying the
rank of the ambient module $k^n$ used for lattices and the building of $GL_n$. -/
structure DVRContext where
  k : Type*
  𝔬 : Type*
  [inst_field : Field k]
  [inst_comm_ring : CommRing 𝔬]
  [inst_domain : IsDomain 𝔬]
  embed : 𝔬 →+* k
  embed_injective : Function.Injective embed
  uniformizer : 𝔬
  n : ℕ
  n_pos : 0 < n

namespace DVRContext

variable (C : DVRContext)

attribute [instance] DVRContext.inst_field DVRContext.inst_comm_ring DVRContext.inst_domain

/-- *The maximal ideal of $\mathfrak{o}$*: the principal ideal $(\pi) \subseteq \mathfrak{o}$
generated by the chosen uniformizer $\pi$. In a DVR this is the unique maximal ideal. -/
def maxIdeal : Ideal C.𝔬 := Ideal.span {C.uniformizer}

/-- *$\mathfrak{o}$-scalar action on $k^n$*: pointwise multiplication by the image
$\iota(r) \in k$ of $r \in \mathfrak{o}$. Used to express the $\mathfrak{o}$-module structure
of $k^n$ via the embedding $\iota = $`embed`. -/
def oscal (r : C.𝔬) (v : Fin C.n → C.k) : Fin C.n → C.k :=
  fun i => C.embed r * v i

/-- *Predicate "$x \in \mathfrak{o}$"*: an element $x \in k$ lies in the valuation ring iff it
is the image of some $r \in \mathfrak{o}$ under the embedding $\iota$. -/
def isInO (x : C.k) : Prop := ∃ r : C.𝔬, C.embed r = x

/-- *Predicate "$x \in \mathfrak{m}$"*: an element $x \in k$ lies in the maximal ideal iff it
is the image of some $r \in (\pi) \subseteq \mathfrak{o}$. -/
def isInMaxIdeal (x : C.k) : Prop :=
  ∃ r : C.𝔬, r ∈ C.maxIdeal ∧ C.embed r = x

/-- *Predicate "$x \in \mathfrak{o}^\times$"*: an element $x \in k$ is a unit of the valuation
ring iff it is the image of a unit $r \in \mathfrak{o}^\times$. -/
def isUnitInO (x : C.k) : Prop :=
  ∃ r : C.𝔬, IsUnit r ∧ C.embed r = x

/-- *Units lie in $\mathfrak{o}$*: every unit in $\mathfrak{o}$ is in particular an element of
$\mathfrak{o}$. -/
lemma isUnitInO_isInO {x : C.k} (h : C.isUnitInO x) : C.isInO x :=
  let ⟨r, _, hr⟩ := h; ⟨r, hr⟩

/-- *The maximal ideal lies in $\mathfrak{o}$*: every element of the maximal ideal is in
particular an element of $\mathfrak{o}$. -/
lemma isInMaxIdeal_isInO {x : C.k} (h : C.isInMaxIdeal x) : C.isInO x :=
  let ⟨r, _, hr⟩ := h; ⟨r, hr⟩


/-- *Newton iteration sequence*: starting from $x_0$, iteratively define
$x_{n+1} = x_n - f(x_n) / f'(x_n)$ using `Ring.inverse` for the division. This is the
underlying sequence used in Hensel's lemma to produce a root of $f$. -/
noncomputable def newtonSeq (f : C.𝔬[X]) (x₀ : C.𝔬) : ℕ → C.𝔬 :=
  fun n => Nat.recOn n x₀ fun _ b =>
    b - f.eval b * Ring.inverse ((Polynomial.derivative f).eval b)

/-- *Hensel's lemma*: in an adically complete local ring $\mathfrak{o}$, if $a_0 \in
\mathfrak{o}$ satisfies $f(a_0) \in \mathfrak{m}$ and $f'(a_0) \notin \mathfrak{m}$, then
there exists a root $a \in \mathfrak{o}$ of $f$ with $a \equiv a_0 \pmod{\mathfrak{m}}$.
Moreover the Newton iterates $c_n$ satisfy $f(c_n) \in \mathfrak{m}^{n+1}$ and $f'(c_n)$ is a
unit for all $n$. -/
theorem HenselsLemma
    [IsLocalRing C.𝔬]
    [IsAdicComplete (IsLocalRing.maximalIdeal C.𝔬) C.𝔬] :
    ∀ (f : C.𝔬[X]) (a₀ : C.𝔬),
      f.eval a₀ ∈ IsLocalRing.maximalIdeal C.𝔬 →
      (Polynomial.derivative f).eval a₀ ∉ IsLocalRing.maximalIdeal C.𝔬 →
      ∃ a : C.𝔬,
        f.eval a = 0 ∧
        a - a₀ ∈ IsLocalRing.maximalIdeal C.𝔬 ∧

        (∀ n, f.eval (C.newtonSeq f a₀ n) ∈
          (IsLocalRing.maximalIdeal C.𝔬) ^ (n + 1)) ∧

        (∀ n, IsUnit ((Polynomial.derivative f).eval (C.newtonSeq f a₀ n))) := by
  intro f a₀ h1 h2
  have h_unit_R : IsUnit ((Polynomial.derivative f).eval a₀) := by
    rwa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, not_not] at h2
  have h_unit : IsUnit (Ideal.Quotient.mk (IsLocalRing.maximalIdeal C.𝔬)
      ((Polynomial.derivative f).eval a₀)) := h_unit_R.map _
  classical
  set I := IsLocalRing.maximalIdeal C.𝔬

  set c := C.newtonSeq f a₀
  have hc : ∀ n, c (n + 1) = c n - f.eval (c n) *
      Ring.inverse ((Polynomial.derivative f).eval (c n)) := by
    intro n; simp only [c, newtonSeq]

  have hc_mod : ∀ n, c n ≡ a₀ [SMOD I] := by
    intro n; induction n with
    | zero => rfl
    | succ n ih =>
      rw [hc, sub_eq_add_neg, ← add_zero a₀]
      refine ih.add ?_
      rw [SModEq.zero, Ideal.neg_mem_iff]
      refine I.mul_mem_right _ ?_
      rw [← SModEq.zero] at h1 ⊢
      exact (ih.eval f).trans h1

  have hf'c : ∀ n, IsUnit ((derivative f).eval (c n)) := by
    intro n
    haveI := isLocalHom_of_le_jacobson_bot I (IsAdicComplete.le_jacobson_bot I)
    apply IsUnit.of_map (Ideal.Quotient.mk I)
    convert h_unit using 1
    exact SModEq.def.mp ((hc_mod n).eval _)


  have hfcI : ∀ n, f.eval (c n) ∈ I ^ (n + 1) := by
    intro n; induction n with
    | zero => simpa only [Nat.rec_zero, zero_add, pow_one] using h1
    | succ n ih =>
      rw [← taylor_eval_sub (c n), hc, sub_eq_add_neg, sub_eq_add_neg, add_neg_cancel_comm]
      rw [eval_eq_sum, sum_over_range' _ _ _ (lt_add_of_pos_right _ zero_lt_two),
        ← Finset.sum_range_add_sum_Ico _ (Nat.le_add_left _ _)]
      swap; · intro i; rw [zero_mul]
      refine Ideal.add_mem _ ?_ ?_

      · rw [← one_add_one_eq_two, Finset.sum_range_succ, Finset.range_one, Finset.sum_singleton,
          taylor_coeff_zero, taylor_coeff_one, pow_zero, pow_one, mul_one, mul_neg,
          mul_left_comm, Ring.mul_inverse_cancel _ (hf'c n), mul_one, add_neg_cancel]
        exact Ideal.zero_mem _


      · refine Submodule.sum_mem _ ?_
        simp only [Finset.mem_Ico]
        rintro i ⟨h2i, _⟩
        have aux : n + 2 ≤ i * (n + 1) := by trans 2 * (n + 1) <;> nlinarith only [h2i]
        refine Ideal.mul_mem_left _ _ (Ideal.pow_le_pow_right aux ?_)
        rw [pow_mul']
        exact Ideal.pow_mem_pow ((Ideal.neg_mem_iff _).2 <| Ideal.mul_mem_right _ _ ih) _

  have cauchy : ∀ m n, m ≤ n → c m ≡ c n [SMOD (I ^ m • ⊤ : Ideal C.𝔬)] := by
    intro m n hmn
    rw [← Ideal.one_eq_top, Ideal.smul_eq_mul, mul_one]
    obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hmn
    clear hmn; induction k with
    | zero => simp [SModEq.refl]
    | succ k ih =>
      rw [← Nat.add_assoc, hc, ← add_zero (c m), sub_eq_add_neg]
      refine ih.add ?_
      symm; rw [SModEq.zero, Ideal.neg_mem_iff]
      refine Ideal.mul_mem_right _ _ (Ideal.pow_le_pow_right ?_ (hfcI _))
      rw [Nat.add_assoc]; exact le_self_add

  obtain ⟨a, ha⟩ := IsPrecomplete.prec' c (cauchy _ _)
  refine ⟨a, ?_, ?_, hfcI, hf'c⟩

  · show f.IsRoot a
    suffices ∀ n, f.eval a ≡ 0 [SMOD (I ^ n • ⊤ : Ideal C.𝔬)] by
      exact IsHausdorff.haus' _ this
    intro n; specialize ha n
    rw [← Ideal.one_eq_top, Ideal.smul_eq_mul, mul_one] at ha ⊢
    refine (ha.symm.eval f).trans ?_
    rw [SModEq.zero]
    exact Ideal.pow_le_pow_right le_self_add (hfcI _)

  · show a - a₀ ∈ I
    specialize ha (0 + 1)
    rw [hc, pow_one, ← Ideal.one_eq_top, Ideal.smul_eq_mul, mul_one, sub_eq_add_neg] at ha
    rw [← SModEq.sub_mem, ← add_zero a₀]
    refine ha.symm.trans (SModEq.rfl.add ?_)
    rw [SModEq.zero, Ideal.neg_mem_iff]
    exact Ideal.mul_mem_right _ _ h1


/-- *An $\mathfrak{o}$-lattice in $V = k^n$*: a subset $\Lambda \subseteq k^n$ that is an
$\mathfrak{o}$-submodule (contains zero, is closed under addition and under the action of
$\mathfrak{o}$), spans $V$ as a $k$-vector space, and is closed under $\mathfrak{o}$-linear
combinations of $n$ vectors with $\mathfrak{o}$-coefficients (used as a substitute for finite
generation over $\mathfrak{o}$). -/
structure OLattice where
  carrier : Set (Fin C.n → C.k)
  zero_mem : (0 : Fin C.n → C.k) ∈ carrier
  add_mem : ∀ {x y}, x ∈ carrier → y ∈ carrier → x + y ∈ carrier
  smul_mem : ∀ (r : C.𝔬) {x}, x ∈ carrier → C.oscal r x ∈ carrier
  spans_V : ∀ v : Fin C.n → C.k,
    ∃ (m : ℕ) (cs : Fin m → C.k) (vs : Fin m → Fin C.n → C.k),
      (∀ j, vs j ∈ carrier) ∧ v = ∑ j, cs j • vs j
  closed_under_o_combination :
    ∀ (coeffs : Fin C.n → C.k) (vectors : Fin C.n → (Fin C.n → C.k)),
      (∀ i, C.isInO (coeffs i)) →
      (∀ i, vectors i ∈ carrier) →
      (∑ i, coeffs i • vectors i) ∈ carrier

/-- *Scaling a lattice by a scalar*: $\alpha \cdot \Lambda := \{\alpha \cdot w : w \in
\Lambda\}$, used to define the homothety relation between lattices. -/
def OLattice.scale (Λ : OLattice C) (α : C.k) : Set (Fin C.n → C.k) :=
  {v | ∃ w ∈ Λ.carrier, v = fun i => α * w i}

/-- *Homothety relation on lattices*: two lattices $\Lambda_1, \Lambda_2$ are *homothetic* iff
$\Lambda_1 = \alpha \cdot \Lambda_2$ for some nonzero scalar $\alpha \in k^\times$. The
quotient by this relation yields the vertices of the Bruhat--Tits building. -/
def OLattice.IsHomothetic (Λ₁ Λ₂ : OLattice C) : Prop :=
  ∃ α : C.k, α ≠ 0 ∧ Λ₁.carrier = Λ₂.scale C α

/-- *Vertex set of the Bruhat--Tits building*: the quotient of the set of $\mathfrak{o}$-lattices
in $V = k^n$ by the homothety equivalence relation. -/
def HomothetyClass := Quot (OLattice.IsHomothetic C)

/-- *Primitive lattice with a bilinear form*: an $\mathfrak{o}$-lattice $\Lambda$ equipped with
a bilinear form `form` $: V \times V \to k$ such that the form is integral on $\Lambda$
(takes values in $\mathfrak{o}$) and is nondegenerate modulo $\pi$: any element $v \in
\Lambda$ that is not divisible by the uniformizer pairs to a unit against some element of
$\Lambda$. -/
structure PrimitiveLattice extends OLattice C where
  form : (Fin C.n → C.k) → (Fin C.n → C.k) → C.k
  form_linear_left : ∀ (r : C.k) (v w : Fin C.n → C.k),
    form (r • v) w = r * form v w
  form_linear_right : ∀ (r : C.k) (v w : Fin C.n → C.k),
    form v (r • w) = r * form v w
  form_integral : ∀ {v w}, v ∈ carrier → w ∈ carrier → C.isInO (form v w)
  form_nondeg : ∀ {v}, v ∈ carrier →
    (¬ ∃ w ∈ carrier, v = C.oscal C.uniformizer w) →
    ∃ w ∈ carrier, C.isUnitInO (form v w)


/-- *Abbreviation for $GL_n(k)$*: the general linear group of invertible $n \times n$ matrices
over the field $k$. -/
abbrev GL_n_k := GL (Fin C.n) C.k

/-- *Upper unipotent subgroup of $GL_n(k)$*: matrices with $1$'s on the diagonal and zeros
strictly below the diagonal. -/
def UpperUnipotent : Set C.GL_n_k :=
  { g | (∀ i, g.val i i = 1) ∧ (∀ i j, j < i → g.val i j = 0) }

/-- *Lower unipotent subgroup of $GL_n(k)$*: matrices with $1$'s on the diagonal and zeros
strictly above the diagonal. -/
def LowerUnipotent : Set C.GL_n_k :=
  { g | (∀ i, g.val i i = 1) ∧ (∀ i j, i < j → g.val i j = 0) }

/-- *Diagonal subgroup of $GL_n(k)$*: invertible matrices whose off-diagonal entries vanish. -/
def DiagonalMatrices : Set C.GL_n_k :=
  { g | ∀ i j, i ≠ j → g.val i j = 0 }

/-- *Iwahori subgroup of $GL_n(k)$*: invertible matrices whose diagonal entries are units in
$\mathfrak{o}$, whose strictly-upper-triangular entries lie in $\mathfrak{o}$, and whose
strictly-lower-triangular entries lie in the maximal ideal $\mathfrak{m}$. -/
def IwahoriSubgroupGLn : Set C.GL_n_k :=
  { g |

    (∀ i : Fin C.n, C.isUnitInO (g.val i i)) ∧

    (∀ i j : Fin C.n, i < j → C.isInO (g.val i j)) ∧

    (∀ i j : Fin C.n, j < i → C.isInMaxIdeal (g.val i j)) }

/-- *Maximal compact subgroup $GL_n(\mathfrak{o})$*: invertible matrices over $\mathfrak{o}$
whose inverse also has entries in $\mathfrak{o}$. Equivalently, $GL_n(\mathfrak{o})$ is the
group of $\mathfrak{o}$-linear automorphisms of the standard lattice. -/
def GL_n_o : Set C.GL_n_k :=
  { g |
    (∀ i j : Fin C.n, C.isInO (g.val i j)) ∧
    (∀ i j : Fin C.n, C.isInO (g⁻¹.val i j)) }


/-- *DVR closure axioms*: a packaging of the algebraic closure properties of $\mathfrak{o}
\subseteq k$ that are used throughout the development: $0, 1 \in \mathfrak{o}$, closure of
$\mathfrak{o}$ under negation, addition, and multiplication, integers are in $\mathfrak{o}$,
the inverse of a unit in $\mathfrak{o}$ is in $\mathfrak{o}$, and the determinant of any
matrix satisfying the Iwahori conditions is a unit in $\mathfrak{o}$. -/
class DVRClosure (C : DVRContext) where
  isInO_zero : C.isInO 0
  isInO_one : C.isInO 1
  isInO_neg : ∀ {x}, C.isInO x → C.isInO (-x)
  isInO_add : ∀ {x y}, C.isInO x → C.isInO y → C.isInO (x + y)
  isInO_mul : ∀ {x y}, C.isInO x → C.isInO y → C.isInO (x * y)
  isInO_intCast : ∀ (n : ℤ), C.isInO (n : C.k)
  isUnitInO_inv : ∀ {x}, C.isUnitInO x → C.isInO x⁻¹
  iwahori_det_unit : ∀ (g : Matrix (Fin C.n) (Fin C.n) C.k),
    (∀ i, C.isUnitInO (g i i)) →
    (∀ i j, i < j → C.isInO (g i j)) →
    (∀ i j, j < i → C.isInMaxIdeal (g i j)) →
    C.isUnitInO g.det

variable [DVRClosure C]

/-- *Sums of $\mathfrak{o}$-elements lie in $\mathfrak{o}$*: a finite sum of elements all in
$\mathfrak{o}$ remains in $\mathfrak{o}$. -/
lemma isInO_sum {ι : Type*} {s : Finset ι} {f : ι → C.k}
    (hf : ∀ i ∈ s, C.isInO (f i)) : C.isInO (∑ i ∈ s, f i) := by
  induction s using Finset.cons_induction with
  | empty => simp; exact DVRClosure.isInO_zero
  | cons a s has ih =>
    rw [Finset.sum_cons]
    exact DVRClosure.isInO_add (hf a (Finset.mem_cons_self a s))
      (ih (fun i hi => hf i (Finset.mem_cons_of_mem hi)))

/-- *Products of $\mathfrak{o}$-elements lie in $\mathfrak{o}$*: a finite product of elements
all in $\mathfrak{o}$ remains in $\mathfrak{o}$. -/
lemma isInO_prod {ι : Type*} {s : Finset ι} {f : ι → C.k}
    (hf : ∀ i ∈ s, C.isInO (f i)) : C.isInO (∏ i ∈ s, f i) := by
  induction s using Finset.cons_induction with
  | empty => simp; exact DVRClosure.isInO_one
  | cons a s has ih =>
    rw [Finset.prod_cons]
    exact DVRClosure.isInO_mul (hf a (Finset.mem_cons_self a s))
      (ih (fun i hi => hf i (Finset.mem_cons_of_mem hi)))

/-- *Determinant of an $\mathfrak{o}$-matrix lies in $\mathfrak{o}$*: if all entries of an
$m \times m$ matrix $A$ over $k$ lie in $\mathfrak{o}$, then so does $\det A$. -/
lemma det_isInO {m : ℕ} (A : Matrix (Fin m) (Fin m) C.k)
    (hA : ∀ i j, C.isInO (A i j)) : C.isInO A.det := by
  rw [Matrix.det_apply]
  apply isInO_sum; intro σ _
  simp only [Units.smul_def, zsmul_eq_mul]
  exact DVRClosure.isInO_mul (DVRClosure.isInO_intCast _)
    (isInO_prod C (fun i _ => hA (σ i) i))

/-- *Adjugate of an $\mathfrak{o}$-matrix has $\mathfrak{o}$-entries*: if all entries of $A$
lie in $\mathfrak{o}$, then every entry of the adjugate matrix $\mathrm{adj}(A)$ also lies in
$\mathfrak{o}$. -/
lemma adjugate_isInO {m : ℕ} (A : Matrix (Fin m) (Fin m) C.k)
    (hA : ∀ i j, C.isInO (A i j)) : ∀ i j, C.isInO (A.adjugate i j) := by
  intro i j
  rw [Matrix.adjugate_apply]
  apply det_isInO; intro a b
  simp only [Matrix.updateRow_apply]
  split
  · simp only [Pi.single_apply]; split
    · exact DVRClosure.isInO_one
    · exact DVRClosure.isInO_zero
  · exact hA a b

/-- *Inverse of an integral matrix with unit determinant has $\mathfrak{o}$-entries*: if $A$
has entries in $\mathfrak{o}$ and $\det A$ is a unit in $\mathfrak{o}$, then $A^{-1}$ also has
entries in $\mathfrak{o}$. This is the analogue for integral matrices of the unimodularity
condition for $GL_n(\mathfrak{o})$. -/
lemma nonsing_inv_isInO {m : ℕ} (A : Matrix (Fin m) (Fin m) C.k)
    (hA : ∀ i j, C.isInO (A i j))
    (hdet : C.isUnitInO A.det) :
    ∀ i j, C.isInO (A⁻¹ i j) := by
  intro i j

  rw [Matrix.inv_def, Matrix.smul_apply, smul_eq_mul, Ring.inverse_eq_inv]
  exact DVRClosure.isInO_mul (DVRClosure.isUnitInO_inv hdet) (adjugate_isInO C A hA i j)

section Topology185

omit [DVRClosure C]


/-- *DVR topology axioms*: bundle together an ultrametric normed-field structure on $k$ and
the assertions that the valuation predicates `isInO`, `isInMaxIdeal`, `isUnitInO` correspond
to the standard normed conditions $\|x\| \le 1$, $\|x\| < 1$, $\|x\| = 1$ respectively. This
turns the algebraic DVR data into a topological one. -/
class DVRTopology where
  instNormedField : NormedField C.k
  instUltrametric : @IsUltrametricDist C.k instNormedField.toPseudoMetricSpace.toDist
  isInO_iff_norm_le_one : ∀ x : C.k,
    C.isInO x ↔ @norm C.k instNormedField.toNorm x ≤ 1
  isInMaxIdeal_iff_norm_lt_one : ∀ x : C.k,
    C.isInMaxIdeal x ↔ @norm C.k instNormedField.toNorm x < 1
  isUnitInO_iff_norm_eq_one : ∀ x : C.k,
    C.isUnitInO x ↔ @norm C.k instNormedField.toNorm x = 1

variable [ht : DVRTopology C]

open Metric Set in
/-- *The valuation ring $\mathfrak{o}$ is clopen in $k$*: under the ultrametric topology of
$k$, the set $\{x \in k : \|x\| \le 1\} = \mathfrak{o}$ is both open and closed. This is a key
feature distinguishing the ultrametric setting from the archimedean one. -/
theorem isClopen_valuationRing :
    @IsClopen C.k ht.instNormedField.toUniformSpace.toTopologicalSpace
      {x : C.k | C.isInO x} := by
  letI : NormedField C.k := ht.instNormedField
  letI : IsUltrametricDist C.k := ht.instUltrametric
  have heq : {x : C.k | C.isInO x} = closedBall (0 : C.k) 1 := by
    ext x; simp only [mem_setOf_eq, mem_closedBall, dist_zero_right]
    exact ht.isInO_iff_norm_le_one x
  rw [heq]
  exact IsUltrametricDist.isClopen_closedBall 0 one_ne_zero

open Metric Set in
/-- *The maximal ideal $\mathfrak{m}$ is clopen in $k$*: under the ultrametric topology of
$k$, the set $\{x \in k : \|x\| < 1\} = \mathfrak{m}$ is both open and closed. -/
theorem isClopen_maximalIdeal :
    @IsClopen C.k ht.instNormedField.toUniformSpace.toTopologicalSpace
      {x : C.k | C.isInMaxIdeal x} := by
  letI : NormedField C.k := ht.instNormedField
  letI : IsUltrametricDist C.k := ht.instUltrametric
  have heq : {x : C.k | C.isInMaxIdeal x} = ball (0 : C.k) 1 := by
    ext x; simp only [mem_setOf_eq, mem_ball, dist_zero_right]
    exact ht.isInMaxIdeal_iff_norm_lt_one x
  rw [heq]
  exact IsUltrametricDist.isClopen_ball 0 1

open Metric Set in
/-- *The unit sphere $\mathfrak{o}^\times$ is clopen in $k$*: the set $\{x \in k : \|x\| = 1\}
= \mathfrak{o}^\times$ is both open and closed, expressed as the difference of two clopen
balls. -/
theorem isClopen_units :
    @IsClopen C.k ht.instNormedField.toUniformSpace.toTopologicalSpace
      {x : C.k | C.isUnitInO x} := by
  letI : NormedField C.k := ht.instNormedField
  letI : IsUltrametricDist C.k := ht.instUltrametric
  have heq : {x : C.k | C.isUnitInO x} =
      closedBall (0 : C.k) 1 \ ball (0 : C.k) 1 := by
    ext x
    simp only [mem_setOf_eq, mem_diff, mem_closedBall, mem_ball, dist_zero_right]
    constructor
    · intro h; rw [ht.isUnitInO_iff_norm_eq_one x] at h
      exact ⟨le_of_eq h, not_lt.mpr (ge_of_eq h)⟩
    · intro ⟨h1, h2⟩; rw [ht.isUnitInO_iff_norm_eq_one x]
      exact le_antisymm h1 (not_lt.mp h2)
  rw [heq]
  exact IsClopen.diff (IsUltrametricDist.isClopen_closedBall 0 one_ne_zero)
    (IsUltrametricDist.isClopen_ball 0 1)

/-- *All three valuation-defined subsets are clopen*: $\mathfrak{o}$, $\mathfrak{o}^\times$,
and $\mathfrak{m}$ are all simultaneously open and closed in the ultrametric topology of $k$.
A convenient packaging of the three preceding theorems. -/
theorem isClopen_valuationRing_units_maxIdeal :
    @IsClopen C.k ht.instNormedField.toUniformSpace.toTopologicalSpace
      {x : C.k | C.isInO x} ∧
    @IsClopen C.k ht.instNormedField.toUniformSpace.toTopologicalSpace
      {x : C.k | C.isUnitInO x} ∧
    @IsClopen C.k ht.instNormedField.toUniformSpace.toTopologicalSpace
      {x : C.k | C.isInMaxIdeal x} :=
  ⟨isClopen_valuationRing C, isClopen_units C, isClopen_maximalIdeal C⟩

end Topology185

end DVRContext
