/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.Buildings.code.BNPair.NormalizerParabolicProof
import Atlas.Buildings.code.BNPair.SubgroupOverBProof
import Atlas.Buildings.code.BNPair.BruhatPropertiesInstance
import Mathlib.Tactic.Group

set_option linter.unusedSectionVars false
set_option maxHeartbeats 800000

variable {G : Type*} [Group G] {B_idx : Type*} {M : CoxeterMatrix B_idx}

namespace PropositionParabolics

open BNPair NormalizerParabolic SubgroupOverB

/-- $B \leq \langle BwB \rangle$: write each $b \in B$ as $n^{-1}(nb)$ with $n, nb \in BwB$. -/
lemma B_le_closure_bruhatCell (bp : BNPair G M) (w : M.Group) :
    bp.B ≤ Subgroup.closure (bp.bruhatCell w) := by
  intro b hb
  obtain ⟨n, hn⟩ := bp.π_surj w
  have hn_mem : (n : G) ∈ bp.bruhatCell w :=
    ⟨⟨1, bp.B.one_mem⟩, n, ⟨1, bp.B.one_mem⟩, hn, by simp⟩
  have hnb_mem : (n : G) * b ∈ bp.bruhatCell w :=
    ⟨⟨1, bp.B.one_mem⟩, n, ⟨b, hb⟩, hn, by simp⟩
  have hn_cl := Subgroup.subset_closure hn_mem
  have hnb_cl := Subgroup.subset_closure hnb_mem

  have : b = (n : G)⁻¹ * ((n : G) * b) := by group
  rw [this]
  exact (Subgroup.closure (bp.bruhatCell w)).mul_mem
    ((Subgroup.closure (bp.bruhatCell w)).inv_mem hn_cl) hnb_cl

/-- If $BwB \subseteq Q$ and $B \leq Q$, then $w$ belongs to the parabolic Weyl subgroup
$W_{S_Q}$, where $S_Q = \{s \in S : BsB \subseteq Q\}$. -/
theorem bruhatCell_generators_in_subgroup
    (bp : BNPair G M) (ax : BNPairAxioms bp)
    (Q : Subgroup G) (w : M.Group)
    (hBwB : bp.bruhatCell w ⊆ (Q : Set G))
    (hBQ : bp.B ≤ Q) :
    w ∈ bp.parabolicSubgroupW { s : B_idx | bp.bruhatCell (M.toCoxeterSystem.simple s) ⊆ (Q : Set G) } :=
  w_mem_parabolicW_of_cell_sub bp ax Q hBQ _ rfl w hBwB

/-- Applied to $Q = \langle BwB \rangle$: the element $w$ lies in the parabolic Weyl
subgroup generated by those simple reflections whose Bruhat cell already lies in
$\langle BwB \rangle$. -/
theorem generators_in_closure_bruhatCell
    (bp : BNPair G M) (ax : BNPairAxioms bp)
    (w : M.Group) :
    w ∈ bp.parabolicSubgroupW
      { s : B_idx | bp.bruhatCell (M.toCoxeterSystem.simple s) ⊆
        (Subgroup.closure (bp.bruhatCell w) : Set G) } := by
  apply bruhatCell_generators_in_subgroup bp ax
  · exact Subgroup.subset_closure
  · exact B_le_closure_bruhatCell bp w

/-- The conjugate Borel $n^{-1} B n = \{n^{-1} b n : b \in B\}$. -/
def conjB (bp : BNPair G M) (n : bp.N) : Set G :=
  { g : G | ∃ b ∈ bp.B, g = (n : G)⁻¹ * b * (n : G) }

/-- $BwB \subseteq \langle B \cup n^{-1}Bn \rangle$ for any $N$-lift $n$ of $w$. Uses the
key conjugation lemma `N_lift_mem_subgroup_of_conj` applied to $n^{-1}$. -/
theorem bruhatCell_sub_closure_B_conjB
    (bp : BNPair G M) (ax : BNPairAxioms bp)
    (w : M.Group) (n : bp.N) (hn : bp.π n = w) :
    bp.bruhatCell w ⊆
      (Subgroup.closure ((bp.B : Set G) ∪ conjB bp n) : Set G) := by
  set Q := Subgroup.closure ((bp.B : Set G) ∪ conjB bp n)

  have hBQ : bp.B ≤ Q := by
    intro b hb
    exact Subgroup.subset_closure (Set.mem_union_left _ hb)

  have hconjQ : ∀ b ∈ bp.B, (n : G)⁻¹ * b * (n : G) ∈ (Q : Set G) := by
    intro b hb
    apply Subgroup.subset_closure
    right
    exact ⟨b, hb, rfl⟩

  have hn_inv_conj : ∀ b ∈ bp.B, (n⁻¹ : bp.N) * b * ((n⁻¹ : bp.N) : G)⁻¹ ∈ (Q : Set G) := by
    intro b hb
    simp only [Subgroup.coe_inv, inv_inv]
    exact hconjQ b hb

  have hπ_inv : bp.π (n⁻¹) = w⁻¹ := by
    rw [map_inv, hn]

  have hn_inv_Q : ((n⁻¹ : bp.N) : G) ∈ (Q : Set G) :=
    N_lift_mem_subgroup_of_conj bp ax Q hBQ w⁻¹ n⁻¹ hπ_inv hn_inv_conj

  have hn_Q : (n : G) ∈ (Q : Set G) := by
    have : (n : G) = ((n⁻¹ : bp.N) : G)⁻¹ := by simp
    rw [this]
    exact Q.inv_mem hn_inv_Q

  intro g hg
  obtain ⟨⟨b₁, hb₁⟩, n', ⟨b₂, hb₂⟩, hπ', hg_eq⟩ := hg

  have hπ_diff : bp.π (n' * n⁻¹) = 1 := by
    rw [map_mul, map_inv, hπ', hn, mul_inv_cancel]
  have hdiff_T : ((n' * n⁻¹ : bp.N) : G) ∈ bp.T := (bp.π_ker _).mp hπ_diff
  have hdiff_B : ((n' * n⁻¹ : bp.N) : G) ∈ bp.B := by
    rw [bp.T_eq] at hdiff_T; exact (Subgroup.mem_inf.mp hdiff_T).1

  have hn'_Q : (n' : G) ∈ (Q : Set G) := by
    have : (n' : G) = ((n' * n⁻¹ : bp.N) : G) * (n : G) := by
      simp [Subgroup.coe_mul]
    rw [this]
    exact Q.mul_mem (hBQ hdiff_B) hn_Q

  rw [hg_eq]
  exact Q.mul_mem (Q.mul_mem (hBQ hb₁) hn'_Q) (hBQ hb₂)

/-- $\langle B \cup n^{-1}Bn \rangle \leq \langle BwB \rangle$: both generating sets sit
inside $\langle BwB \rangle$ since $n \in BwB$ and $B \leq \langle BwB \rangle$. -/
theorem closure_B_conjB_sub_closure_bruhatCell
    (bp : BNPair G M) (w : M.Group) (n : bp.N) (hn : bp.π n = w) :
    Subgroup.closure ((bp.B : Set G) ∪ conjB bp n) ≤
      Subgroup.closure (bp.bruhatCell w) := by
  rw [Subgroup.closure_le]
  intro g hg
  rcases hg with hg_B | hg_conj
  ·
    exact B_le_closure_bruhatCell bp w hg_B
  ·
    obtain ⟨b, hb, hg_eq⟩ := hg_conj
    rw [hg_eq]

    have hn_mem : (n : G) ∈ bp.bruhatCell w :=
      ⟨⟨1, bp.B.one_mem⟩, n, ⟨1, bp.B.one_mem⟩, hn, by simp⟩
    have hn_cl := Subgroup.subset_closure hn_mem
    have hn_inv_cl := (Subgroup.closure (bp.bruhatCell w)).inv_mem hn_cl
    have hb_cl := B_le_closure_bruhatCell bp w hb
    exact (Subgroup.closure (bp.bruhatCell w)).mul_mem
      ((Subgroup.closure (bp.bruhatCell w)).mul_mem hn_inv_cl hb_cl) hn_cl

/-- $\langle BwB \rangle = \langle B \cup n^{-1}Bn \rangle$ for any $N$-lift $n$ of $w$.
Combines the two inclusions above. -/
theorem closure_bruhatCell_eq_closure_B_conjB
    (bp : BNPair G M) (ax : BNPairAxioms bp)
    (w : M.Group) (n : bp.N) (hn : bp.π n = w) :
    Subgroup.closure (bp.bruhatCell w) =
      Subgroup.closure ((bp.B : Set G) ∪ conjB bp n) := by
  apply le_antisymm
  ·
    rw [Subgroup.closure_le]
    exact bruhatCell_sub_closure_B_conjB bp ax w n hn
  ·
    exact closure_B_conjB_sub_closure_bruhatCell bp w n hn

/-- An $N$-lift of a simple reflection $s$ already lies in $\langle BwB \rangle$ whenever
the simple cell $BsB$ does. -/
theorem N_lift_in_closure_bruhatCell
    (bp : BNPair G M) (w : M.Group)
    (s : B_idx) (hs : bp.bruhatCell (M.toCoxeterSystem.simple s) ⊆
      (Subgroup.closure (bp.bruhatCell w) : Set G))
    (n : bp.N) (hn : bp.π n = M.toCoxeterSystem.simple s) :
    (n : G) ∈ (Subgroup.closure (bp.bruhatCell w) : Set G) := by
  apply hs
  exact ⟨⟨1, bp.B.one_mem⟩, n, ⟨1, bp.B.one_mem⟩, hn, by simp⟩

/-- **Combined "Proposition" on the parabolic subgroup generated by a Bruhat cell.**
For any $w \in W$ and any $N$-lift $n$ of $w$, the following both hold:
(i) $w$ lies in the parabolic Weyl subgroup generated by $\{s : BsB \subseteq \langle BwB \rangle\}$;
(ii) $\langle BwB \rangle = \langle B \cup n^{-1}Bn \rangle$.
This is the conjunction of `generators_in_closure_bruhatCell` and
`closure_bruhatCell_eq_closure_B_conjB`. -/
theorem proposition_parabolic_subgroup_of_cell
    (bp : BNPair G M) (ax : BNPairAxioms bp)
    (w : M.Group) (n : bp.N) (hn : bp.π n = w) :
    (w ∈ bp.parabolicSubgroupW
      { s : B_idx | bp.bruhatCell (M.toCoxeterSystem.simple s) ⊆
        (Subgroup.closure (bp.bruhatCell w) : Set G) })
    ∧
    (Subgroup.closure (bp.bruhatCell w) =
      Subgroup.closure ((bp.B : Set G) ∪ conjB bp n)) :=
  ⟨generators_in_closure_bruhatCell bp ax w,
   closure_bruhatCell_eq_closure_B_conjB bp ax w n hn⟩

end PropositionParabolics
