/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.Buildings.code.BNPair.Basic
import Atlas.Buildings.code.BNPair.ParabolicDefs
import Mathlib.Tactic.Group
import Mathlib.GroupTheory.Coxeter.Length

set_option linter.unusedSectionVars false

section CoxeterHelpers

variable {B_idx : Type*} {W : Type*} [Group W] {M : CoxeterMatrix B_idx}

/-- The cyclic subgroup generated by a simple reflection $s$ has exactly two elements:
$\langle s \rangle = \{1, s\}$, since $s^2 = 1$. -/
lemma closure_simple_eq_pair (cs : CoxeterSystem M W) (s : B_idx) :
    (Subgroup.closure ({cs.simple s} : Set W) : Set W) = {1, cs.simple s} := by
  ext w
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff, SetLike.mem_coe]
  constructor
  · intro hw
    induction hw using Subgroup.closure_induction with
    | mem x hx => simp at hx; right; exact hx
    | one => left; rfl
    | mul x y _ _ ihx ihy =>
      rcases ihx with rfl | rfl <;> rcases ihy with rfl | rfl
      · left; simp
      · right; simp
      · right; simp
      · left; have := cs.simple_sq s; rw [sq] at this; exact this
    | inv x _ ihx =>
      rcases ihx with rfl | rfl
      · left; simp
      · right
        have hsq : cs.simple s * cs.simple s = 1 := by have := cs.simple_sq s; rwa [sq] at this
        calc (cs.simple s)⁻¹ = 1 * (cs.simple s)⁻¹ := by simp
          _ = (cs.simple s * cs.simple s) * (cs.simple s)⁻¹ := by rw [hsq]
          _ = cs.simple s := by group
  · rintro (rfl | rfl)
    · exact Subgroup.one_mem _
    · exact Subgroup.subset_closure (Set.mem_singleton _)

/-- Every simple reflection $s$ is a right descent of the longest element $w_0$:
$\ell(w_0 s) < \ell(w_0)$. Otherwise $w_0 s$ would be longer than $w_0$, contradicting
maximality. -/
theorem longest_isRightDescent (cs : CoxeterSystem M W)
    (w₀ : W)
    (hw₀_longest : ∀ w : W, cs.length w ≤ cs.length w₀)
    (s : B_idx) :
    cs.IsRightDescent w₀ s := by
  unfold CoxeterSystem.IsRightDescent
  rcases cs.length_mul_simple w₀ s with h | h
  · exfalso; have := hw₀_longest (w₀ * cs.simple s); omega
  · omega

/-- Right-multiplying the longest element $w_0$ by any simple reflection $s$ decreases
length by exactly one: $\ell(w_0 s) = \ell(w_0) - 1$. -/
theorem longest_length_mul_simple (cs : CoxeterSystem M W)
    (w₀ : W)
    (hw₀_longest : ∀ w : W, cs.length w ≤ cs.length w₀)
    (s : B_idx) :
    cs.length (w₀ * cs.simple s) = cs.length w₀ - 1 := by
  rcases cs.length_mul_simple w₀ s with h | h
  · exfalso; have := hw₀_longest (w₀ * cs.simple s); omega
  · omega

/-- Every simple reflection $s$ is a left descent of $w_0$: $\ell(sw_0) < \ell(w_0)$. -/
theorem longest_isLeftDescent (cs : CoxeterSystem M W)
    (w₀ : W)
    (hw₀_longest : ∀ w : W, cs.length w ≤ cs.length w₀)
    (s : B_idx) :
    cs.IsLeftDescent w₀ s := by
  unfold CoxeterSystem.IsLeftDescent
  rcases cs.length_simple_mul w₀ s with h | h
  · exfalso; have := hw₀_longest (cs.simple s * w₀); omega
  · omega

/-- Left-multiplying $w_0$ by any simple reflection $s$ decreases length by one:
$\ell(s w_0) = \ell(w_0) - 1$. -/
theorem longest_length_simple_mul (cs : CoxeterSystem M W)
    (w₀ : W)
    (hw₀_longest : ∀ w : W, cs.length w ≤ cs.length w₀)
    (s : B_idx) :
    cs.length (cs.simple s * w₀) = cs.length w₀ - 1 := by
  rcases cs.length_simple_mul w₀ s with h | h
  · exfalso; have := hw₀_longest (cs.simple s * w₀); omega
  · omega

/-- **The longest element is an involution:** $w_0^2 = 1$. Since $\ell(w_0^{-1}) = \ell(w_0)$,
$w_0^{-1}$ is also a maximal-length element, and uniqueness forces $w_0^{-1} = w_0$. -/
theorem longest_sq_eq_one (cs : CoxeterSystem M W)
    (w₀ : W)
    (hw₀_longest : ∀ w : W, cs.length w ≤ cs.length w₀)
    (hw₀_unique : ∀ w : W, (∀ v : W, cs.length v ≤ cs.length w) → w = w₀) :
    w₀ ^ 2 = 1 := by
  have hinv : cs.length w₀⁻¹ = cs.length w₀ := cs.length_inv w₀
  have hinv_longest : ∀ w : W, cs.length w ≤ cs.length w₀⁻¹ := by
    intro w; rw [hinv]; exact hw₀_longest w
  have heq : w₀⁻¹ = w₀ := hw₀_unique w₀⁻¹ hinv_longest
  rw [sq]
  calc w₀ * w₀ = w₀⁻¹ * w₀ := by rw [heq]
    _ = 1 := inv_mul_cancel w₀

/-- **Type-preserving involution induced by $w_0$.** If $w_0$ conjugates each cyclic
parabolic $\langle s \rangle$ to another cyclic parabolic $\langle s' \rangle$, then in fact
$w_0 \cdot s \cdot w_0^{-1} = s'$ on the nose (not just on the closures). Eliminates the
"$=1$" case using $\ell(s) = 1$. -/
theorem conj_simple_from_parabolic (cs : CoxeterSystem M W)
    (w₀ : W)
    (h_parabolic : ∀ s : B_idx, ∃ s' : B_idx,
      Subgroup.closure ({w₀ * cs.simple s * w₀⁻¹} : Set W) =
        Subgroup.closure ({cs.simple s'} : Set W)) :
    ∀ s : B_idx, ∃ s' : B_idx,
      w₀ * cs.simple s * w₀⁻¹ = cs.simple s' := by
  intro s
  obtain ⟨s', hs'⟩ := h_parabolic s
  use s'
  have h_conj_in_closure : w₀ * cs.simple s * w₀⁻¹ ∈
      Subgroup.closure ({cs.simple s'} : Set W) := by
    rw [← hs']
    exact Subgroup.subset_closure (Set.mem_singleton _)
  have h_mem : (w₀ * cs.simple s * w₀⁻¹ : W) ∈ ({1, cs.simple s'} : Set W) := by
    rwa [← closure_simple_eq_pair, SetLike.mem_coe]
  rcases h_mem with h | h
  ·
    exfalso
    have : cs.simple s = 1 := by
      calc cs.simple s = w₀⁻¹ * (w₀ * cs.simple s * w₀⁻¹) * w₀ := by group
        _ = w₀⁻¹ * 1 * w₀ := by rw [h]
        _ = 1 := by group
    have : cs.length (cs.simple s) = 0 := by rw [this, cs.length_one]
    rw [cs.length_simple] at this
    exact absurd this (by omega)
  · exact h

end CoxeterHelpers

/-- A **spherical BN-pair**: a BN-pair whose Weyl group $W$ is finite. Axiomatized by
existence of a longest element $w_0$ (unique, of maximal length), the fact that $w_0$
conjugates each simple reflection to another simple reflection (an involution on $S$),
and structural identities relating the torus, Borel and Levi components needed for the
opposite-parabolic / Levi-decomposition theory of finite Coxeter / Tits systems. -/
structure SphericalBNPair (G : Type*) [Group G] {B_idx : Type*}
    (M : CoxeterMatrix B_idx) extends BNPair G M where
  weylFinite : Set.Finite (Set.univ : Set M.Group)
  w₀ : M.Group
  w₀_longest : ∀ w : M.Group,
    M.toCoxeterSystem.length w ≤ M.toCoxeterSystem.length w₀
  w₀_unique : ∀ w : M.Group,
    (∀ v : M.Group, M.toCoxeterSystem.length v ≤ M.toCoxeterSystem.length w) →
    w = w₀
  w₀_conj_parabolic : ∀ s : B_idx, ∃ s' : B_idx,
    Subgroup.closure ({w₀ * M.toCoxeterSystem.simple s * w₀⁻¹} : Set M.Group) =
      Subgroup.closure ({M.toCoxeterSystem.simple s'} : Set M.Group)
  torus_eq_levi_borel : ∀ n : toBNPair.N, toBNPair.π n = w₀ →
    (toBNPair.T : Set G) =
      (toBNPair.B : Set G) ∩ ((fun s => (n : G) * s * (n : G)⁻¹) '' (toBNPair.B : Set G))
  levi_normalization : ∀ (T : Set B_idx) (n : toBNPair.N), toBNPair.π n = w₀ →
    ∀ g : G, g ∈ toBNPair.standardParabolic T →
      (fun s => g * s * g⁻¹) ''
        (toBNPair.standardParabolic T ∩
          ((fun s => (n : G) * s * (n : G)⁻¹) '' toBNPair.standardParabolic T)) ⊆
        toBNPair.standardParabolic T
  levi_weyl_group : ∀ (T : Set B_idx) (n : toBNPair.N), toBNPair.π n = w₀ →
    ∀ w : M.Group,
      w ∈ (toBNPair.parabolicSubgroupW T : Set M.Group) ↔
      toBNPair.bruhatCell w ⊆
        (toBNPair.standardParabolic T ∩
          ((fun s => (n : G) * s * (n : G)⁻¹) '' toBNPair.standardParabolic T))

namespace SphericalBNPair

variable {G : Type*} [Group G] {B_idx : Type*} {M : CoxeterMatrix B_idx}

/-- The **longest element** $w_0$ of a spherical Weyl group, exposed as a definition. -/
def longestElement (sbp : SphericalBNPair G M) : M.Group := sbp.w₀

variable (sbp : SphericalBNPair G M)

/-- $w_0$ is an involution: $w_0^2 = 1$. -/
theorem w₀_sq : sbp.w₀ ^ 2 = 1 :=
  longest_sq_eq_one M.toCoxeterSystem sbp.w₀ sbp.w₀_longest sbp.w₀_unique

/-- $w_0$ permutes the simple reflections by conjugation: for each $s$ there is $s'$ with
$w_0 s w_0^{-1} = s'$. -/
theorem w₀_conj_simple : ∀ s : B_idx, ∃ s' : B_idx,
    sbp.w₀ * M.toCoxeterSystem.simple s * sbp.w₀⁻¹ = M.toCoxeterSystem.simple s' :=
  conj_simple_from_parabolic M.toCoxeterSystem sbp.w₀ sbp.w₀_conj_parabolic

/-- Restatement of `w₀_sq` in product form: $w_0 \cdot w_0 = 1$. -/
theorem w₀_mul_self : sbp.w₀ * sbp.w₀ = 1 := by
  have h := sbp.w₀_sq; rwa [sq] at h

/-- $w_0^{-1} = w_0$, equivalent to $w_0^2 = 1$. -/
theorem w₀_inv_eq : sbp.w₀⁻¹ = sbp.w₀ :=
  mul_right_cancel (a := sbp.w₀⁻¹) (b := sbp.w₀) (c := sbp.w₀)
    (by rw [inv_mul_cancel, ← sq, sbp.w₀_sq])

/-- Conjugation of a subset $S \subseteq G$ by a single element $g$: $gSg^{-1}$. -/
def conjugateSetBy (_ : SphericalBNPair G M) (g : G) (S : Set G) : Set G :=
  (fun s => g * s * g⁻¹) '' S

/-- Conjugation of $S \subseteq G$ by a chosen $N$-lift of a Weyl element $w$. -/
noncomputable def conjugateByWeylElt (sbp : SphericalBNPair G M)
    (w : M.Group) (S : Set G) : Set G :=
  sbp.conjugateSetBy (sbp.toBNPair.π_surj w).choose.val S

/-- The **opposite Borel** $B^- = n_{w_0} B n_{w_0}^{-1}$, obtained by conjugating $B$
through a chosen $N$-lift of $w_0$. -/
noncomputable def oppositeBorel (sbp : SphericalBNPair G M) : Set G :=
  sbp.conjugateByWeylElt sbp.w₀ (sbp.toBNPair.B : Set G)

/-- The **opposite parabolic** $P_T^- = n_{w_0} P_T n_{w_0}^{-1}$, for $T \subseteq S$. -/
noncomputable def oppositeParabolic (sbp : SphericalBNPair G M)
    (T : Set B_idx) : Set G :=
  sbp.conjugateByWeylElt sbp.w₀ (sbp.toBNPair.standardParabolic T)

/-- The **Levi component** $L = B \cap B^-$ of the BN-pair, the intersection of $B$ with
its opposite. -/
noncomputable def leviComponent (sbp : SphericalBNPair G M) : Set G :=
  (sbp.toBNPair.B : Set G) ∩ sbp.oppositeBorel

/-- The **Levi component of a parabolic** $L_T = P_T \cap P_T^-$, generalizing
`leviComponent` (which is the case $T = \emptyset$). -/
noncomputable def leviComponentGeneral (sbp : SphericalBNPair G M)
    (T : Set B_idx) : Set G :=
  sbp.toBNPair.standardParabolic T ∩ sbp.oppositeParabolic T

/-- Specification of the noncomputably chosen $N$-lift of $w_0$: its image under $\pi$ is $w_0$. -/
theorem chosen_lift_w₀_spec :
    sbp.toBNPair.π (sbp.toBNPair.π_surj sbp.w₀).choose = sbp.w₀ :=
  (sbp.toBNPair.π_surj sbp.w₀).choose_spec

/-- Alias for `w₀_conj_simple` emphasizing that $w_0$ induces an automorphism (a permutation)
of the index set $S$ of simple reflections. -/
theorem longestElementAutoS :
    ∀ s : B_idx,
      ∃ s' : B_idx,
        sbp.w₀ * M.toCoxeterSystem.simple s * sbp.w₀⁻¹ =
          M.toCoxeterSystem.simple s' :=
  sbp.w₀_conj_simple

/-- **The $w_0$-induced permutation of $S$ is an involution.** Conjugation by $w_0$ maps
each simple reflection to another simple reflection, and this map is its own inverse:
if $w_0 s w_0^{-1} = s'$ then $w_0 s' w_0^{-1} = s$. Direct consequence of $w_0^2 = 1$. -/
theorem longestElementAutoSInvolution :
    (∀ s : B_idx,
      ∃ s' : B_idx,
        sbp.w₀ * M.toCoxeterSystem.simple s * sbp.w₀⁻¹ =
          M.toCoxeterSystem.simple s') ∧
    ∀ (s s' : B_idx),
      sbp.w₀ * M.toCoxeterSystem.simple s * sbp.w₀⁻¹ =
        M.toCoxeterSystem.simple s' →
      sbp.w₀ * M.toCoxeterSystem.simple s' * sbp.w₀⁻¹ =
        M.toCoxeterSystem.simple s := by
  refine ⟨sbp.longestElementAutoS, fun s s' h => ?_⟩
  have hw : sbp.w₀⁻¹ = sbp.w₀ := sbp.w₀_inv_eq
  rw [hw] at h ⊢
  have hsq : sbp.w₀ * sbp.w₀ = 1 := sbp.w₀_mul_self
  calc sbp.w₀ * M.toCoxeterSystem.simple s' * sbp.w₀
      = sbp.w₀ * (sbp.w₀ * M.toCoxeterSystem.simple s * sbp.w₀) * sbp.w₀ := by
        rw [h]
    _ = (sbp.w₀ * sbp.w₀) * M.toCoxeterSystem.simple s * (sbp.w₀ * sbp.w₀) := by
        group
    _ = 1 * M.toCoxeterSystem.simple s * 1 := by rw [hsq]
    _ = M.toCoxeterSystem.simple s := by group

/-- Unfolding equation for `leviComponent`: $L = B \cap n_{w_0} B n_{w_0}^{-1}$, made
explicit at the level of `choose` for the noncomputable $N$-lift. -/
theorem leviComponent_eq :
    sbp.leviComponent =
      (sbp.toBNPair.B : Set G) ∩
        ((fun s => ((sbp.toBNPair.π_surj sbp.w₀).choose : G) * s *
          ((sbp.toBNPair.π_surj sbp.w₀).choose : G)⁻¹) '' (sbp.toBNPair.B : Set G)) := by
  rfl

/-- Unfolding equation for `leviComponentGeneral`: $L_T = P_T \cap n_{w_0} P_T n_{w_0}^{-1}$. -/
theorem leviComponentGeneral_eq (T : Set B_idx) :
    sbp.leviComponentGeneral T =
      sbp.toBNPair.standardParabolic T ∩
        ((fun s => ((sbp.toBNPair.π_surj sbp.w₀).choose : G) * s *
          ((sbp.toBNPair.π_surj sbp.w₀).choose : G)⁻¹) ''
          sbp.toBNPair.standardParabolic T) := by
  rfl

end SphericalBNPair
