/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.Nullstellensatz
import Mathlib.Topology.Irreducible
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.FieldTheory.Galois.Infinite
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.FieldTheory.Perfect
import Mathlib.FieldTheory.PurelyInseparable.PerfectClosure
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.RingTheory.MvPolynomial.Homogeneous

open MvPolynomial Set

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]
variable {σ : Type*}

/-- Galois-equivalence formulation matching Definition 4.40: an algebraic
extension `L/k` is Galois iff it is both normal and separable. -/
theorem isGalois_iff_normal_and_separable
    {k L : Type*} [Field k] [Field L] [Algebra k L] :
    IsGalois k L ↔ Normal k L ∧ Algebra.IsSeparable k L :=
  isGalois_iff.trans And.comm

/-- The `n`-dimensional affine space over `K` indexed by `σ`, defined as the
full set of `σ`-tuples of elements of `K`. This is the underlying set of
`𝔸_k^n` from Definition 4.41. -/
def affineSpace (σ : Type*) (K : Type*) [Field K] : Set (σ → K) := Set.univ

/-- Unfolding lemma: affine space is by definition the whole `σ → K`. -/
@[simp]
theorem affineSpace_eq_univ : affineSpace σ K = Set.univ := rfl

/-- The set of `L`-rational points of affine space: tuples whose every
coordinate lies in the intermediate field `L`. This corresponds to
`𝔸^n(L)` from Definition 4.41. -/
def affineRationalPoints (σ : Type*) (L : IntermediateField k K) : Set (σ → K) :=
  {x : σ → K | ∀ i : σ, x i ∈ L}

/-- A tuple is `L`-rational iff each of its coordinates lies in `L`. -/
@[simp]
theorem mem_affineRationalPoints_iff (L : IntermediateField k K) (x : σ → K) :
    x ∈ affineRationalPoints σ L ↔ ∀ i : σ, x i ∈ L :=
  Iff.rfl

/-- Galois-fixed points in affine space: tuples fixed by every element of the
Galois group fixing `L`. By the Galois correspondence (cf. Definition 4.41),
these coincide with `L`-rational points when `K/k` is Galois. -/
def affineGaloisFixedPoints (σ : Type*) (L : IntermediateField k K) : Set (σ → K) :=
  MulAction.fixedPoints L.fixingSubgroup (σ → K)

/-- Characterization of Galois-fixed points: a tuple `x` is fixed iff every
`L`-fixing automorphism `φ` of `K` acts trivially on `x`. -/
@[simp]
theorem mem_affineGaloisFixedPoints_iff (L : IntermediateField k K) (x : σ → K) :
    x ∈ affineGaloisFixedPoints σ L ↔
      ∀ φ : K ≃ₐ[k] K, φ ∈ L.fixingSubgroup → φ • x = x := by
  unfold affineGaloisFixedPoints
  rw [MulAction.mem_fixedPoints]
  constructor
  · intro h φ hφ; simpa using h ⟨φ, hφ⟩
  · intro h ⟨φ, hφ⟩; simpa using h φ hφ

/-- Every `L`-rational point is fixed by the subgroup of automorphisms of
`K/k` fixing `L`. -/
theorem affineRationalPoints_subset_galoisFixedPoints
    (L : IntermediateField k K) :
    affineRationalPoints σ L ⊆ affineGaloisFixedPoints σ L := by
  intro x hx
  rw [mem_affineGaloisFixedPoints_iff]
  intro φ hφ
  ext i
  simp only [Pi.smul_apply, AlgEquiv.smul_def]
  rw [IntermediateField.mem_fixingSubgroup_iff] at hφ
  exact hφ (x i) (hx i)

/-- Converse of `affineRationalPoints_subset_galoisFixedPoints`: when `K/k`
is Galois, a tuple fixed by all `L`-fixing automorphisms must be `L`-rational. -/
theorem galoisFixedPoints_subset_affineRationalPoints
    [IsGalois k K]
    (L : IntermediateField k K) :
    affineGaloisFixedPoints σ L ⊆ affineRationalPoints σ L := by
  intro x hx
  rw [mem_affineGaloisFixedPoints_iff] at hx
  intro i
  rw [← InfiniteGalois.fixedField_fixingSubgroup L]
  rw [IntermediateField.mem_fixedField_iff]
  intro φ hφ
  have hi := congr_fun (hx φ hφ) i
  simp only [Pi.smul_apply] at hi
  exact hi

/-- The zero locus `Z_S` of a set `S` of polynomials, defined as the zero locus
of the ideal generated by `S`. This matches Definition 4.42. -/
def zeroLocusOfSet (K : Type*) [Field K]
    (S : Set (MvPolynomial σ K)) : Set (σ → K) :=
  MvPolynomial.zeroLocus K (Ideal.span S)

/-- Membership in `Z_S` is equivalent to all polynomials in `S` vanishing at
the point. -/
@[simp]
theorem mem_zeroLocusOfSet_iff (S : Set (MvPolynomial σ K)) (x : σ → K) :
    x ∈ zeroLocusOfSet K S ↔ ∀ p ∈ S, aeval x p = 0 := by
  unfold zeroLocusOfSet
  rw [MvPolynomial.zeroLocus_span]
  rfl

/-- Set-builder form of `zeroLocusOfSet`. -/
theorem zeroLocusOfSet_eq (S : Set (MvPolynomial σ K)) :
    zeroLocusOfSet K S = {x : σ → K | ∀ p ∈ S, aeval x p = 0} := by
  ext x; simp

/-- The set of `L`-rational points on the algebraic set cut out by `S`:
points lying in the zero locus and having all coordinates in `L`. This is
`Z_S(L)` from Definition 4.42. -/
def lRationalPoints (K : Type*) [Field K] [Algebra k K]
    (S : Set (MvPolynomial σ K)) (L : IntermediateField k K) : Set (σ → K) :=
  zeroLocusOfSet K S ∩ affineRationalPoints σ L

/-- Membership in `lRationalPoints`: vanishing of all polynomials in `S` plus
all coordinates in `L`. -/
@[simp]
theorem mem_lRationalPoints_iff
    (S : Set (MvPolynomial σ K)) (L : IntermediateField k K) (x : σ → K) :
    x ∈ lRationalPoints K S L ↔
      (∀ f ∈ S, aeval x f = 0) ∧ (∀ i : σ, x i ∈ L) := by
  simp [lRationalPoints]

/-- An (affine) algebraic set is a set of the form `Z(I)` for some ideal
`I ⊆ K[x₁, …, xₙ]`. Corresponds to the notion from Definition 4.42. -/
def IsAffineAlgebraicSet (K : Type*) [Field K] (V : Set (σ → K)) : Prop :=
  ∃ I : Ideal (MvPolynomial σ K), V = MvPolynomial.zeroLocus K I

/-- The zero locus of any ideal is an algebraic set, by definition. -/
theorem isAffineAlgebraicSet_zeroLocus (I : Ideal (MvPolynomial σ K)) :
    IsAffineAlgebraicSet K (MvPolynomial.zeroLocus K I) :=
  ⟨I, rfl⟩

/-- The empty set is an algebraic set, realized as the zero locus of the
unit ideal. -/
theorem isAffineAlgebraicSet_empty : IsAffineAlgebraicSet K (∅ : Set (σ → K)) :=
  ⟨⊤, by simp [zeroLocus_top]⟩

/-- An algebraic set is irreducible if it is nonempty and cannot be written
as the union of two strictly smaller algebraic sets. This is Definition 4.54. -/
def IsIrreducibleAffineAlgebraicSet (K : Type*) [Field K]
    (V : Set (σ → K)) : Prop :=
  IsAffineAlgebraicSet K V ∧
  V.Nonempty ∧
  ∀ V₁ V₂ : Set (σ → K),
    IsAffineAlgebraicSet K V₁ →
    IsAffineAlgebraicSet K V₂ →
    V = V₁ ∪ V₂ → V = V₁ ∨ V = V₂

/-- An affine variety is an irreducible affine algebraic set. -/
def IsAffineVariety (K : Type*) [Field K] (V : Set (σ → K)) : Prop :=
  IsIrreducibleAffineAlgebraicSet K V

/-- The vanishing ideal `I(V)` of a set of points: all polynomials that
vanish identically on `V`. This is Definition 4.46. -/
def vanishingIdealOfSet (K : Type*) [Field K]
    (V : Set (σ → K)) : Ideal (MvPolynomial σ K) :=
  MvPolynomial.vanishingIdeal K V

/-- A polynomial lies in `I(V)` iff it vanishes at every point of `V`. -/
@[simp]
theorem mem_vanishingIdealOfSet_iff (V : Set (σ → K)) (f : MvPolynomial σ K) :
    f ∈ vanishingIdealOfSet K V ↔ ∀ x ∈ V, aeval x f = 0 :=
  MvPolynomial.mem_vanishingIdeal_iff

/-- Set-builder form of `vanishingIdealOfSet`. -/
theorem vanishingIdealOfSet_eq (V : Set (σ → K)) :
    (vanishingIdealOfSet K V : Set (MvPolynomial σ K)) =
      {f | ∀ x ∈ V, aeval x f = 0} := by
  ext f; simp

/-- The coordinate ring of an algebraic set `V`: the quotient of the
polynomial ring by the vanishing ideal `I(V)`. -/
abbrev coordinateRing (K : Type*) [Field K]
    (σ : Type*) (V : Set (σ → K)) :=
  MvPolynomial σ K ⧸ vanishingIdealOfSet K V

/-- Unfolding the definition of `coordinateRing` in terms of `vanishingIdeal`. -/
theorem coordinateRing_eq (V : Set (σ → K)) :
    coordinateRing K σ V = (MvPolynomial σ K ⧸ MvPolynomial.vanishingIdeal K V) := rfl

/-- The canonical quotient map `K[x₁, …, xₙ] → K[V]` from the polynomial ring
to the coordinate ring of `V`. -/
def coordinateRing.mk (V : Set (σ → K)) :
    MvPolynomial σ K →+* coordinateRing K σ V :=
  Ideal.Quotient.mk _

/-- A representation of a homogeneous rational function on the projective curve
defined by `f`: a numerator and denominator, both homogeneous of the same
degree, with the denominator not in the ideal `(f)`. -/
structure HomogeneousRationalFunction (k : Type*) [CommRing k]
    (f : MvPolynomial (Fin 3) k) where
  num : MvPolynomial (Fin 3) k
  den : MvPolynomial (Fin 3) k
  deg : ℕ
  num_homogeneous : num.IsHomogeneous deg
  den_homogeneous : den.IsHomogeneous deg
  den_not_in_ideal : den ∉ Ideal.span ({f} : Set (MvPolynomial (Fin 3) k))

/-- The equivalence relation on `HomogeneousRationalFunction`s used to define
the function field of a projective curve: `p₁ ∼ p₂` iff
`p₁.num * p₂.den - p₂.num * p₁.den ∈ (f)`. -/
def HomogeneousRationalFunction.Equiv (k : Type*) [CommRing k]
    (f : MvPolynomial (Fin 3) k) :
    HomogeneousRationalFunction k f → HomogeneousRationalFunction k f → Prop :=
  fun p₁ p₂ => p₁.num * p₂.den - p₂.num * p₁.den ∈
    Ideal.span ({f} : Set (MvPolynomial (Fin 3) k))

/-- The setoid on `HomogeneousRationalFunction`s built from `Equiv`. Reflexivity,
symmetry, and transitivity use that `(f)` is a prime ideal (since `f` is
irreducible), so denominators behave well. -/
def projectiveFunctionFieldSetoid {k : Type*} [Field k]
    (f : MvPolynomial (Fin 3) k) [Fact (Irreducible f)] :
    Setoid (HomogeneousRationalFunction k f) where
  r := HomogeneousRationalFunction.Equiv k f
  iseqv := {
    refl := fun p => by
      simp [HomogeneousRationalFunction.Equiv, sub_self]
    symm := fun {p₁ p₂} h => by
      simp only [HomogeneousRationalFunction.Equiv] at *
      rwa [show p₂.num * p₁.den - p₁.num * p₂.den =
        -(p₁.num * p₂.den - p₂.num * p₁.den) from by ring,
        Ideal.neg_mem_iff]
    trans := fun {p₁ p₂ p₃} h12 h23 => by
      simp only [HomogeneousRationalFunction.Equiv] at *
      have h12' := Ideal.mul_mem_right p₃.den _ h12
      have h23' := Ideal.mul_mem_right p₁.den _ h23
      have hsum := Ideal.add_mem _ h12' h23'
      have hrw : (p₁.num * p₂.den - p₂.num * p₁.den) * p₃.den +
          (p₂.num * p₃.den - p₃.num * p₂.den) * p₁.den =
          p₂.den * (p₁.num * p₃.den - p₃.num * p₁.den) := by ring
      rw [hrw] at hsum
      have hprime : (Ideal.span ({f} : Set (MvPolynomial (Fin 3) k))).IsPrime := by
        rw [Ideal.span_singleton_prime]
        · exact (Fact.out : Irreducible f).prime
        · exact (Fact.out : Irreducible f).ne_zero
      exact (hprime.mem_or_mem hsum).resolve_left p₂.den_not_in_ideal
  }

/-- The function field of the projective curve cut out by an irreducible
`f ∈ k[x, y, z]`: the quotient of homogeneous rational functions by the
equivalence relation `projectiveFunctionFieldSetoid f`. -/
def functionField (k : Type*) [Field k]
    (f : MvPolynomial (Fin 3) k) [Fact (Irreducible f)] :=
  Quotient (projectiveFunctionFieldSetoid f)

/-- The canonical map sending a homogeneous rational function to its class in
the function field. -/
def functionField.mk {k : Type*} [Field k]
    {f : MvPolynomial (Fin 3) k} [Fact (Irreducible f)]
    (p : HomogeneousRationalFunction k f) : functionField k f :=
  Quotient.mk (projectiveFunctionFieldSetoid f) p

/-- The ideal `(f)` generated by an irreducible polynomial `f ∈ k[x, y, z]`
is prime. -/
instance homogeneousIdeal_isPrime {k : Type*} [Field k]
    (f : MvPolynomial (Fin 3) k) [Fact (Irreducible f)] :
    (Ideal.span ({f} : Set (MvPolynomial (Fin 3) k))).IsPrime :=
  (Ideal.span_singleton_prime (Fact.out : Irreducible f).ne_zero).mpr
    (Fact.out : Irreducible f).prime

/-- An alternative model of the function field of `Z(f)` as the fraction
field of the quotient ring `k[x, y, z] / (f)`. -/
abbrev functionFieldFrac (k : Type*) [Field k]
    (f : MvPolynomial (Fin 3) k) [Fact (Irreducible f)] :=
  FractionRing (MvPolynomial (Fin 3) k ⧸ Ideal.span ({f} : Set (MvPolynomial (Fin 3) k)))


/-- The affine function field of an affine algebraic set `V`: the fraction
field of its coordinate ring `K[V]`. -/
abbrev affineFunctionField (K : Type*) [Field K]
    (σ : Type*) (V : Set (σ → K)) :=
  FractionRing (coordinateRing K σ V)

/-- When `I(V)` is prime, the coordinate ring `K[V]` is an integral domain. -/
instance coordinateRing.isDomain_of_prime (V : Set (σ → K))
    [(vanishingIdealOfSet K V).IsPrime] :
    IsDomain (coordinateRing K σ V) :=
  Ideal.Quotient.isDomain _

/-- When `I(V)` is prime, the affine function field of `V` is genuinely a
field (it is the fraction field of an integral domain). -/
instance affineFunctionField.field_of_prime (V : Set (σ → K))
    [(vanishingIdealOfSet K V).IsPrime] :
    Field (affineFunctionField K σ V) :=
  FractionRing.field _

/-- The canonical embedding of the coordinate ring `K[V]` into its fraction
field, the affine function field of `V`. -/
def affineFunctionField.ofCoordinateRing (V : Set (σ → K)) :
    coordinateRing K σ V →+* affineFunctionField K σ V :=
  algebraMap _ _

/-- The dimension of an affine variety `V` over `k`: the transcendence degree
over `k` of its affine function field. This realizes Definition 4.35
specialized to affine varieties. -/
noncomputable def varietyDimension (k : Type*) [Field k] (K : Type*) [Field K] [Algebra k K]
    (σ : Type*) (V : Set (σ → K)) [(vanishingIdealOfSet K V).IsPrime] : Cardinal :=
  Algebra.trdeg k (affineFunctionField K σ V)

/-- A ring is noetherian iff every ideal is finitely generated.
Matches Definition 4.44. -/
theorem isNoetherianRing_iff_every_ideal_fg (R : Type*) [CommRing R] :
    IsNoetherianRing R ↔ ∀ I : Ideal R, I.FG :=
  isNoetherianRing_iff_ideal_fg R

/-- Hilbert's basis theorem (Theorem 4.45): if `R` is noetherian, so is `R[x]`. -/
theorem hilbert_basis_theorem
    (R : Type*) [CommRing R] [IsNoetherianRing R] : IsNoetherianRing (Polynomial R) :=
  Polynomial.isNoetherianRing

/-- Explicit set-theoretic description of the radical `√I` of an ideal `I`:
those `f` such that some positive power `f^n` lies in `I`. Matches
Definition 4.47. -/
theorem radical_eq_setOf {R : Type*} [CommSemiring R] (I : Ideal R) :
    (I.radical : Set R) = {f | ∃ n : ℕ, 0 < n ∧ f ^ n ∈ I} := by
  ext f
  simp only [SetLike.mem_coe, Ideal.mem_radical_iff, Set.mem_setOf_eq]
  constructor
  · rintro ⟨n, hn⟩
    exact ⟨n + 1, Nat.succ_pos n, by rw [pow_succ]; exact I.mul_mem_right f hn⟩
  · rintro ⟨n, -, hn⟩
    exact ⟨n, hn⟩

/-- Lemma 4.48: `√I` is an ideal — exhibited here by giving the witness
ideal `I.radical`. -/
theorem radical_is_ideal {R : Type*} [CommSemiring R] (I : Ideal R) :
    ∃ J : Ideal R, (J : Set R) = {f | ∃ n : ℕ, f ^ n ∈ I} :=
  ⟨I.radical, by ext; simp [Ideal.mem_radical_iff]⟩

/-- The vanishing ideal `I(V)` of any set `V ⊆ 𝔸^n` is radical. -/
theorem vanishingIdealOfSet_isRadical (V : Set (σ → K)) :
    (vanishingIdealOfSet K V).IsRadical := by
  rw [← Ideal.radical_eq_iff]
  ext f
  simp only [Ideal.mem_radical_iff]
  constructor
  · rintro ⟨n, hn⟩
    intro x hx
    have : aeval x (f ^ n) = 0 := hn x hx
    rw [map_pow] at this
    exact (pow_eq_zero_iff'.mp this).1
  · intro h
    exact ⟨1, by simpa using h⟩

/-- The union of two algebraic sets is algebraic, realized via the
intersection of their defining ideals. -/
theorem isAffineAlgebraicSet_union {V₁ V₂ : Set (σ → K)}
    (h₁ : IsAffineAlgebraicSet K V₁) (h₂ : IsAffineAlgebraicSet K V₂) :
    IsAffineAlgebraicSet K (V₁ ∪ V₂) := by
  obtain ⟨I, rfl⟩ := h₁
  obtain ⟨J, rfl⟩ := h₂
  exact ⟨I ⊓ J, by
    ext x
    simp only [Set.mem_union, MvPolynomial.mem_zeroLocus_iff, Ideal.mem_inf]
    constructor
    · rintro (h | h) p ⟨hp1, hp2⟩
      · exact h p hp1
      · exact h p hp2
    · intro h
      by_contra hc
      push Not at hc
      obtain ⟨⟨p, hp, hpx⟩, ⟨q, hq, hqx⟩⟩ := hc
      have hpq : p * q ∈ I ⊓ J :=
        Ideal.mem_inf.mpr ⟨I.mul_mem_right q hp, J.mul_mem_left p hq⟩
      have := h (p * q) hpq
      rw [map_mul] at this
      exact (mul_eq_zero.mp this).elim hpx hqx⟩

/-- An arbitrary intersection of algebraic sets is algebraic, realized via
the supremum of the corresponding ideals. -/
theorem isAffineAlgebraicSet_sInter (A : Set (Set (σ → K)))
    (hA : ∀ V ∈ A, IsAffineAlgebraicSet K V) :
    IsAffineAlgebraicSet K (⋂₀ A) := by
  choose I hI using hA
  exact ⟨⨆ V : A, I V.1 V.2, by
    ext x
    simp only [Set.mem_sInter, MvPolynomial.mem_zeroLocus_iff]
    constructor
    · intro h p hp
      have : ∀ (V : A), I V.1 V.2 ≤ RingHom.ker (aeval (R := K) x) := by
        intro ⟨V, hV⟩ q hq
        simp only [RingHom.mem_ker]
        have := h V hV
        rw [hI V hV] at this
        exact this q hq
      have hsup := iSup_le this
      simpa [RingHom.mem_ker] using hsup hp
    · intro h V hV
      rw [hI V hV]
      intro p hp'
      exact h p (Ideal.mem_iSup_of_mem ⟨V, hV⟩ hp')⟩

/-- The Zariski topology on `σ → K`: closed sets are exactly the affine
algebraic sets, with closure under empty, arbitrary intersection, and
finite unions. -/
@[reducible]
def zariskiTopology (K : Type*) [Field K] (σ : Type*) : TopologicalSpace (σ → K) :=
  TopologicalSpace.ofClosed
    {V : Set (σ → K) | IsAffineAlgebraicSet K V}
    isAffineAlgebraicSet_empty
    (fun _ hA => isAffineAlgebraicSet_sInter _ hA)
    (fun _ h₁ _ h₂ => isAffineAlgebraicSet_union h₁ h₂)

/-- Hilbert's Nullstellensatz (Theorem 4.49): over an algebraically closed
field `K`, for every ideal `I ⊆ K[x₁, …, xₙ]` we have
`I(Z(I)) = √I`. -/
theorem hilberts_nullstellensatz
    {K : Type*} [Field K] [IsAlgClosed K]
    {σ : Type*} [Finite σ]
    (I : Ideal (MvPolynomial σ K)) :
    vanishingIdealOfSet K (MvPolynomial.zeroLocus K I) = I.radical := by sorry

/-- For radical ideals `I`, the Nullstellensatz simplifies to
`I(Z(I)) = I`. -/
theorem vanishingIdealOfSet_zeroLocus_of_radical
    {K : Type*} [Field K] [IsAlgClosed K]
    {σ : Type*} [Finite σ]
    (I : Ideal (MvPolynomial σ K))
    (hI : I.IsRadical) :
    vanishingIdealOfSet K (MvPolynomial.zeroLocus K I) = I := by
  rw [hilberts_nullstellensatz]
  exact hI.radical

/-- For algebraic sets `V`, the Nullstellensatz says `Z(I(V)) = V`. -/
theorem zeroLocus_vanishingIdealOfSet_of_algebraicSet
    {K : Type*} [Field K] [IsAlgClosed K]
    {σ : Type*} [Finite σ]
    (V : Set (σ → K))
    (hV : IsAffineAlgebraicSet K V) :
    MvPolynomial.zeroLocus K (vanishingIdealOfSet K V) = V := by
  obtain ⟨I, rfl⟩ := hV
  apply le_antisymm
  · rw [hilberts_nullstellensatz]
    exact MvPolynomial.zeroLocus_anti_mono Ideal.le_radical
  · exact MvPolynomial.zeroLocus_vanishingIdeal_le _

/-- Injectivity half of the algebraic-set / radical-ideal correspondence
(Corollary 4.52): two algebraic sets with the same vanishing ideal are equal. -/
theorem ideal_variety_injective_sets
    {K : Type*} [Field K] [IsAlgClosed K]
    {σ : Type*} [Finite σ]
    {V W : Set (σ → K)}
    (hV : IsAffineAlgebraicSet K V)
    (hW : IsAffineAlgebraicSet K W)
    (h : vanishingIdealOfSet K V = vanishingIdealOfSet K W) :
    V = W := by
  rw [← zeroLocus_vanishingIdealOfSet_of_algebraicSet V hV,
      ← zeroLocus_vanishingIdealOfSet_of_algebraicSet W hW, h]

/-- Iff-form of the weak Nullstellensatz: the zero locus of `I` is empty iff
`I` is the unit ideal. -/
theorem weak_nullstellensatz_iff
    {K : Type*} [Field K] [IsAlgClosed K]
    {σ : Type*} [Finite σ]
    (I : Ideal (MvPolynomial σ K)) :
    MvPolynomial.zeroLocus K I = ∅ ↔ I = ⊤ := by
  constructor
  · intro hV
    have hNSS := hilberts_nullstellensatz I
    rw [hV, show vanishingIdealOfSet K (∅ : Set (σ → K)) = ⊤ from
      MvPolynomial.vanishingIdeal_empty] at hNSS
    exact Ideal.radical_eq_top.mp hNSS.symm
  · intro hI
    rw [hI]
    simp [MvPolynomial.zeroLocus_top]

/-- Theorem 4.50 (weak Nullstellensatz): a proper ideal of
`K[x₁, …, xₙ]` over an algebraically closed `K` has nonempty zero locus. -/
theorem weak_nullstellensatz
    {K : Type*} [Field K] [IsAlgClosed K]
    {σ : Type*} [Finite σ]
    (I : Ideal (MvPolynomial σ K)) (hI : I ≠ ⊤) :
    (MvPolynomial.zeroLocus K I).Nonempty := by
  rw [Set.nonempty_iff_ne_empty]
  intro hV
  exact hI ((weak_nullstellensatz_iff I).mp hV)

/-- The vanishing ideal of a union of two sets equals the intersection of
their vanishing ideals. -/
theorem vanishingIdealOfSet_union (V₁ V₂ : Set (σ → K)) :
    vanishingIdealOfSet K (V₁ ∪ V₂) =
      vanishingIdealOfSet K V₁ ⊓ vanishingIdealOfSet K V₂ := by
  ext f
  simp only [mem_vanishingIdealOfSet_iff, Ideal.mem_inf, Set.mem_union]
  exact ⟨fun h => ⟨fun x hx => h x (.inl hx), fun x hx => h x (.inr hx)⟩,
         fun ⟨h1, h2⟩ x hx => hx.elim (h1 x) (h2 x)⟩

/-- The intersection of an algebraic set `V` with the zero locus of a single
polynomial `f` is again an algebraic set, realized by the ideal `I + (f)`. -/
theorem isAffineAlgebraicSet_inter_zeroLocus_singleton
    (V : Set (σ → K)) (f : MvPolynomial σ K)
    (hV : IsAffineAlgebraicSet K V) :
    IsAffineAlgebraicSet K (V ∩ {x | aeval x f = 0}) := by
  obtain ⟨I, rfl⟩ := hV
  exact ⟨I ⊔ Ideal.span {f}, by
    ext x
    simp only [Set.mem_inter_iff, MvPolynomial.mem_zeroLocus_iff, Set.mem_setOf_eq]
    constructor
    · rintro ⟨hxI, hxf⟩ p hp
      have : I ⊔ Ideal.span {f} ≤ RingHom.ker (aeval x) :=
        sup_le (fun q hq => RingHom.mem_ker.mpr (hxI q hq))
          (fun q hq => RingHom.mem_ker.mpr (by
            obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton.mp hq
            rw [map_mul, hxf, zero_mul]))
      exact RingHom.mem_ker.mp (this hp)
    · intro hx
      exact ⟨fun p hp => hx p (Ideal.mem_sup_left hp),
             hx f (Ideal.mem_sup_right (Ideal.mem_span_singleton_self f))⟩⟩

/-- Idempotence of the `Z ∘ I` operation on zero loci: `Z(I(Z(J))) = Z(J)`.
This follows from the Nullstellensatz applied to the radical of `J`. -/
theorem zeroLocus_vanishingIdealOfSet_zeroLocus [IsAlgClosed K] [Finite σ]
    (J : Ideal (MvPolynomial σ K)) :
    MvPolynomial.zeroLocus K (vanishingIdealOfSet K (MvPolynomial.zeroLocus K J)) =
      MvPolynomial.zeroLocus K J := by
  unfold vanishingIdealOfSet
  rw [MvPolynomial.vanishingIdeal_zeroLocus_eq_radical]
  apply le_antisymm (MvPolynomial.zeroLocus_anti_mono Ideal.le_radical)
  intro x hx p hp
  obtain ⟨n, hn⟩ := Ideal.mem_radical_iff.mp hp
  have := hx (p ^ n) hn
  rw [map_pow] at this
  exact (pow_eq_zero_iff'.mp this).1

/-- One direction of Theorem 4.55: if `V` is an irreducible algebraic set,
then its vanishing ideal `I(V)` is prime. -/
theorem IsIrreducibleAffineAlgebraicSet.vanishingIdeal_isPrime
    {V : Set (σ → K)}
    (hIrr : IsIrreducibleAffineAlgebraicSet K V) :
    (vanishingIdealOfSet K V).IsPrime := by
  obtain ⟨hAlg, hNe, hIrr⟩ := hIrr
  constructor
  · intro h
    obtain ⟨x, hx⟩ := hNe
    have := (mem_vanishingIdealOfSet_iff V 1).mp (h ▸ Submodule.mem_top) x hx
    simp at this
  · intro f g hfg
    let V₁ := V ∩ {x | aeval x f = 0}
    let V₂ := V ∩ {x | aeval x g = 0}
    have hVunion : V = V₁ ∪ V₂ := by
      ext x
      simp only [V₁, V₂, Set.mem_union, Set.mem_inter_iff, Set.mem_setOf_eq]
      constructor
      · intro hx
        have := (mem_vanishingIdealOfSet_iff V (f * g)).mp hfg x hx
        rw [map_mul] at this
        rcases mul_eq_zero.mp this with h | h
        · exact .inl ⟨hx, h⟩
        · exact .inr ⟨hx, h⟩
      · rintro (⟨hx, -⟩ | ⟨hx, -⟩) <;> exact hx
    rcases hIrr V₁ V₂
      (isAffineAlgebraicSet_inter_zeroLocus_singleton V f hAlg)
      (isAffineAlgebraicSet_inter_zeroLocus_singleton V g hAlg)
      hVunion with h | h
    · left
      rw [mem_vanishingIdealOfSet_iff]
      intro x hx
      exact (h ▸ hx : x ∈ V₁).2
    · right
      rw [mem_vanishingIdealOfSet_iff]
      intro x hx
      exact (h ▸ hx : x ∈ V₂).2

/-- Other direction of Theorem 4.55: an algebraic set whose vanishing ideal
is prime is irreducible. -/
theorem prime_vanishingIdeal_implies_irreducible
    [IsAlgClosed K] [Finite σ]
    {V : Set (σ → K)}
    (hAlg : IsAffineAlgebraicSet K V)
    (hPrime : (vanishingIdealOfSet K V).IsPrime) :
    IsIrreducibleAffineAlgebraicSet K V := by
  obtain ⟨I, rfl⟩ := hAlg
  refine ⟨⟨I, rfl⟩, ?_, ?_⟩
  · by_contra h
    rw [Set.not_nonempty_iff_eq_empty] at h
    simp only [h, vanishingIdealOfSet, MvPolynomial.vanishingIdeal_empty] at hPrime
    exact hPrime.ne_top rfl
  · intro V₁ V₂ ⟨J₁, hV₁⟩ ⟨J₂, hV₂⟩ hunion
    have hIV := hunion ▸ vanishingIdealOfSet_union V₁ V₂
    have hprod : vanishingIdealOfSet K V₁ * vanishingIdealOfSet K V₂ ≤
        vanishingIdealOfSet K (MvPolynomial.zeroLocus K I) := hIV ▸ Ideal.mul_le_inf
    rcases hPrime.mul_le.mp hprod with h₁ | h₂
    · left
      rw [hV₁]
      have heq := le_antisymm h₁
        (MvPolynomial.vanishingIdeal_anti_mono (hunion ▸ Set.subset_union_left))
      have : MvPolynomial.zeroLocus K (vanishingIdealOfSet K V₁) =
          MvPolynomial.zeroLocus K (vanishingIdealOfSet K (MvPolynomial.zeroLocus K I)) := by
        rw [heq]
      rw [hV₁, zeroLocus_vanishingIdealOfSet_zeroLocus,
          zeroLocus_vanishingIdealOfSet_zeroLocus] at this
      exact this.symm
    · right
      rw [hV₂]
      have heq := le_antisymm h₂
        (MvPolynomial.vanishingIdeal_anti_mono (hunion ▸ Set.subset_union_right))
      have : MvPolynomial.zeroLocus K (vanishingIdealOfSet K V₂) =
          MvPolynomial.zeroLocus K (vanishingIdealOfSet K (MvPolynomial.zeroLocus K I)) := by
        rw [heq]
      rw [hV₂, zeroLocus_vanishingIdealOfSet_zeroLocus,
          zeroLocus_vanishingIdealOfSet_zeroLocus] at this
      exact this.symm

/-- Theorem 4.55 (combined form): for an algebraic set `V`, irreducibility is
equivalent to primality of its vanishing ideal. -/
theorem algebraicSet_irreducible_iff_prime
    [IsAlgClosed K] [Finite σ]
    {V : Set (σ → K)} (hAlg : IsAffineAlgebraicSet K V) :
    IsIrreducibleAffineAlgebraicSet K V ↔ (vanishingIdealOfSet K V).IsPrime :=
  ⟨IsIrreducibleAffineAlgebraicSet.vanishingIdeal_isPrime,
   prime_vanishingIdeal_implies_irreducible hAlg⟩

/-- Predicate saying that an algebraic set consists of a single point. -/
def IsPoint (K : Type*) [Field K] (V : Set (σ → K)) : Prop :=
  ∃ P : σ → K, V = {P}

/-- Every singleton `{P} ⊆ 𝔸^n` over an algebraically closed field is an
algebraic set, realized as the zero locus of its vanishing ideal (generated
by `x_i - P_i`). -/
theorem isAffineAlgebraicSet_singleton [IsAlgClosed K] [Finite σ] (P : σ → K) :
    IsAffineAlgebraicSet K ({P} : Set (σ → K)) :=
  ⟨vanishingIdealOfSet K {P}, by
    show {P} = zeroLocus K (vanishingIdeal K {P})
    apply le_antisymm
    · exact zeroLocus_vanishingIdeal_le ({P} : Set (σ → K))
    · intro x hx
      rw [mem_zeroLocus_iff] at hx
      rw [mem_singleton_iff]
      funext i
      have hmem : (X i - C (P i) : MvPolynomial σ K) ∈
          vanishingIdeal K ({P} : Set (σ → K)) := by
        rw [mem_vanishingIdeal_iff]
        intro y hy; rw [mem_singleton_iff] at hy; subst hy; simp
      have heval := hx _ hmem
      simp at heval
      exact sub_eq_zero.mp heval⟩

/-- The vanishing ideal of a single point `P` is maximal: it is the maximal
ideal `m_P = (x_1 - P_1, …, x_n - P_n)` from Corollary 4.51. -/
theorem vanishingIdealOfSet_singleton_isMaximal (P : σ → K) :
    (vanishingIdealOfSet K ({P} : Set (σ → K))).IsMaximal :=
  MvPolynomial.instIsMaximalVanishingIdealSingletonForallSet

/-- Corollary 4.51: over an algebraically closed field with finitely many
variables, every maximal ideal of `K[x₁, …, xₙ]` is of the form `m_P` for a
unique point `P`. -/
theorem maximal_iff_vanishingIdealOfSet_singleton [IsAlgClosed K] [Finite σ]
    (I : Ideal (MvPolynomial σ K)) :
    I.IsMaximal ↔ ∃ P : σ → K, I = vanishingIdealOfSet K ({P} : Set (σ → K)) :=
  MvPolynomial.isMaximal_iff_eq_vanishingIdeal_singleton

end

open Cardinal

universe u v w w'

/-- Theorem 4.34: any two transcendence bases of a field extension `L/k`
have the same cardinality. -/
theorem transcendence_bases_same_cardinality
    {k : Type u} {L : Type v} [Field k] [Field L] [Algebra k L]
    {ι : Type w} {ι' : Type w} {x : ι → L} {y : ι' → L}
    (hx : IsTranscendenceBasis k x) (hy : IsTranscendenceBasis k y) :
    #ι = #ι' :=
  hx.cardinalMk_eq hy

/-- For a field `k` of exponential characteristic `p`, being a perfect field
(Definition 4.38) is equivalent to being a perfect ring with respect to `p`. -/
theorem perfectField_iff_perfectRing (k : Type*) [Field k]
    (p : ℕ) [ExpChar k p] :
    PerfectField k ↔ PerfectRing k p := by
  constructor
  · intro; exact PerfectField.toPerfectRing p
  · intro; exact PerfectRing.toPerfectField k p
