/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Data.Complex.Basic
import Mathlib.Data.Nat.Prime.Defs
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Tactic.Linarith
import Atlas.EllipticCurves.code.Isogenies

noncomputable section

open Complex

/-- The additive subgroup of $\mathbb{C}$ generated by two complex numbers $a$ and $b$,
i.e. the (typically rank-2) lattice $\mathbb{Z}a + \mathbb{Z}b$. -/
def spanLattice (a b : ℂ) : AddSubgroup ℂ :=
  AddSubgroup.closure {a, b}

/-- A sublattice $L' \leq L$ is called *cyclic* (Definition 20.1) if the quotient
$L/L'$ is a cyclic abelian group. Cyclic sublattices correspond to cyclic isogenies of
the associated complex tori. -/
def IsCyclicSublattice (L' L : AddSubgroup ℂ) : Prop :=
  L' ≤ L ∧ IsAddCyclic (L ⧸ L'.addSubgroupOf L)

/-- An isogeny $\varphi : E_1 \to E_2$ between elliptic curves over a field $F$ is
*cyclic* iff its kernel is a cyclic abelian group. -/
def IsCyclicIsogeny {F : Type*} [Field F] [DecidableEq F]
    {E₁ E₂ : WeierstrassCurve.Affine F}
    (φ : Isogeny E₁ E₂) : Prop :=
  IsAddCyclic (AddMonoidHom.ker φ.toAddMonoidHom)

/-- Lemma 20.2 (cyclic isogeny ↔ cyclic sublattice): an isogeny of complex elliptic
curves is cyclic iff the corresponding sublattice inclusion has cyclic quotient. -/
theorem isCyclicIsogeny_iff_isCyclicSublattice
    {E₁ E₂ : WeierstrassCurve.Affine ℂ}
    (φ : Isogeny E₁ E₂)
    (L₁ L₂ : AddSubgroup ℂ)
    (hL : L₁ ≤ L₂) :
    IsCyclicIsogeny φ ↔ IsCyclicSublattice L₁ L₂ := by sorry

/-- Hermite normal form for sublattices: every finite-index sublattice $L'$ of
$\mathbb{Z} + \mathbb{Z}\tau$ admits a basis of the form $\{d, a\tau + k\}$ with $a, d > 0$
and $a \cdot d = [L : L']$. -/
theorem sublattice_hermite_form (τ : ℂ) (hτ : 0 < τ.im)
    (L' : AddSubgroup ℂ) (hL' : L' ≤ spanLattice 1 τ) (hfin : L'.index ≠ 0) :
    ∃ (d a : ℕ) (k : ℤ), 0 < d ∧ 0 < a ∧
      L' = spanLattice (↑d) (↑a * τ + ↑k) ∧ a * d = L'.index := by sorry

/-- The lattice $\mathbb{Z} + \mathbb{Z}(N\tau)$ is contained in $\mathbb{Z} + \mathbb{Z}\tau$: stretching
the second generator by $N$ produces a sublattice. -/
theorem spanLattice_one_Ntau_sub (τ : ℂ) (hτ : 0 < τ.im) (N : ℕ) (hN : 0 < N) :
    spanLattice 1 (↑N * τ) ≤ spanLattice 1 τ := by
  have h1 : (1 : ℂ) ∈ spanLattice 1 τ :=
    AddSubgroup.subset_closure (Set.mem_insert _ _)
  have hτ : τ ∈ spanLattice 1 τ :=
    AddSubgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  simp only [spanLattice]
  apply (AddSubgroup.closure_le (spanLattice 1 τ)).2
  intro x hx
  rcases Set.mem_insert_iff.mp hx with rfl | hx
  · exact h1
  · rw [Set.mem_singleton_iff.mp hx, show (↑N : ℂ) * τ = (N : ℤ) • τ from by simp [zsmul_eq_mul]]
    exact (spanLattice 1 τ).zsmul_mem hτ N

/-- The sublattice $\mathbb{Z} + \mathbb{Z}(N\tau)$ has index exactly $N$ in $\mathbb{Z} + \mathbb{Z}\tau$. -/
theorem spanLattice_one_Ntau_index (τ : ℂ) (hτ : 0 < τ.im) (N : ℕ) (hN : 0 < N) :
    (spanLattice 1 (↑N * τ)).index = N := by sorry

/-- For each $k \in \{0, \ldots, N-1\}$, the lattice $\mathbb{Z}N + \mathbb{Z}(\tau + k)$ is a
sublattice of $\mathbb{Z} + \mathbb{Z}\tau$: scaling the first generator by $N$ and shifting the
second produces a sublattice. -/
theorem spanLattice_N_taupk_sub (τ : ℂ) (hτ : 0 < τ.im) (N : ℕ) (hN : 0 < N)
    (k : Fin N) : spanLattice (↑N) (τ + ↑(k : ℕ)) ≤ spanLattice 1 τ := by
  simp only [spanLattice]
  apply (AddSubgroup.closure_le (AddSubgroup.closure {1, τ})).2
  intro x hx
  rcases Set.mem_insert_iff.mp hx with rfl | hx
  · rw [show (↑N : ℂ) = (N : ℤ) • (1 : ℂ) from by simp [zsmul_eq_mul]]
    exact AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (Set.mem_insert _ _)) N
  · rw [Set.mem_singleton_iff.mp hx, show (↑(k : ℕ) : ℂ) = ((k : ℕ) : ℤ) • (1 : ℂ) from by
      simp [zsmul_eq_mul]]
    exact AddSubgroup.add_mem _
      (AddSubgroup.subset_closure (Set.mem_insert_of_mem _ rfl))
      (AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (Set.mem_insert _ _)) (k : ℕ))

/-- The sublattice $\mathbb{Z}N + \mathbb{Z}(\tau + k)$ has index exactly $N$ in $\mathbb{Z} + \mathbb{Z}\tau$. -/
theorem spanLattice_N_taupk_index (τ : ℂ) (hτ : 0 < τ.im) (N : ℕ) (hN : 0 < N)
    (k : Fin N) : (spanLattice (↑N) (τ + ↑(k : ℕ))).index = N := by sorry

/-- Any sublattice of prime index $p$ has cyclic quotient: every abelian group of
prime order is cyclic. -/
theorem index_prime_isAddCyclic (τ : ℂ) (hτ : 0 < τ.im) (N : ℕ) (hN : Nat.Prime N)
    (L' : AddSubgroup ℂ) (hL' : L' ≤ spanLattice 1 τ) (hidx : L'.index = N) :
    IsAddCyclic (↥(spanLattice 1 τ) ⧸ L'.addSubgroupOf (spanLattice 1 τ)) := by sorry

/-- Modding the integer shift $k$ by $d$ does not change the lattice $\mathbb{Z}d + \mathbb{Z}(b+k)$,
since subtracting a multiple of $d$ from the second generator stays in the lattice. -/
theorem spanLattice_shift_k (τ : ℂ) (hτ : 0 < τ.im) (d : ℕ) (hd : 0 < d)
    (b : ℂ) (k : ℤ) :
    spanLattice (↑d) (b + ↑k) = spanLattice (↑d) (b + ↑(k % ↑d)) := by sorry

/-- An integer shift of the second generator does not change the lattice $\mathbb{Z} + \mathbb{Z}(N\tau)$,
since the shift is itself an integer combination of the first generator. -/
theorem spanLattice_one_tau_shift (τ : ℂ) (hτ : 0 < τ.im) (N : ℕ) (hN : 0 < N)
    (k : ℤ) : spanLattice 1 (↑N * τ + ↑k) = spanLattice 1 (↑N * τ) := by sorry

/-- If $a \cdot d = p$ for a prime $p$ with $a, d > 0$, then $(a,d) = (1,p)$ or
$(a,d) = (p,1)$. -/
lemma prime_mul_eq {a d N : ℕ} (hN : Nat.Prime N) (ha : 0 < a) (hd : 0 < d)
    (h : a * d = N) : (a = 1 ∧ d = N) ∨ (a = N ∧ d = 1) := by
  rcases hN.eq_one_or_self_of_dvd a ⟨d, h.symm⟩ with ha1 | haN
  · subst ha1
    simp at h
    exact Or.inl ⟨rfl, h⟩
  · right
    refine ⟨haN, ?_⟩
    nlinarith [hN.one_lt]

/-- Classification of cyclic sublattices of prime index $p$ in $\mathbb{Z} + \mathbb{Z}\tau$:
they are exactly the $p+1$ lattices $\mathbb{Z} + \mathbb{Z}(p\tau)$ and
$\mathbb{Z}p + \mathbb{Z}(\tau + k)$ for $k = 0, 1, \ldots, p-1$. This parametrizes the
$p+1$ cyclic $p$-isogenies out of the complex torus $\mathbb{C}/(\mathbb{Z}+\mathbb{Z}\tau)$. -/
theorem cyclicSublattices_prime_index
    (τ : ℂ) (hτ : 0 < τ.im) (N : ℕ) (hN : Nat.Prime N)
    (L' : AddSubgroup ℂ) :
    (IsCyclicSublattice L' (spanLattice 1 τ) ∧ L'.index = N) ↔
    (L' = spanLattice 1 (↑N * τ) ∨
     ∃ k : Fin N, L' = spanLattice (↑N) (τ + ↑(k : ℕ))) := by
  constructor
  ·
    rintro ⟨⟨hle, _⟩, hidx⟩
    have hidx_ne : L'.index ≠ 0 := by rw [hidx]; exact hN.pos.ne'
    obtain ⟨d, a, k, hd, ha, hform, hprod⟩ := sublattice_hermite_form τ hτ L' hle hidx_ne
    rw [hidx] at hprod
    rcases prime_mul_eq hN ha hd hprod with ⟨ha1, hdN⟩ | ⟨haN, hd1⟩
    ·
      right
      rw [hform, ha1, hdN, Nat.cast_one, one_mul,
          spanLattice_shift_k τ hτ N hN.pos τ k]
      have hk_nn : 0 ≤ k % ↑N := Int.emod_nonneg k (by omega)
      have hk_lt : k % ↑N < ↑N := Int.emod_lt_of_pos k (by omega)
      refine ⟨⟨(k % ↑N).toNat, by exact Int.toNat_lt hk_nn |>.mpr hk_lt⟩, ?_⟩
      congr 1
      congr 1
      exact_mod_cast (Int.toNat_of_nonneg hk_nn).symm
    ·
      left
      rw [hform, haN, hd1, Nat.cast_one]
      exact spanLattice_one_tau_shift τ hτ N hN.pos k
  ·
    rintro (rfl | ⟨k, rfl⟩)
    · exact ⟨⟨spanLattice_one_Ntau_sub τ hτ N hN.pos,
              index_prime_isAddCyclic τ hτ N hN _ (spanLattice_one_Ntau_sub τ hτ N hN.pos)
                (spanLattice_one_Ntau_index τ hτ N hN.pos)⟩,
             spanLattice_one_Ntau_index τ hτ N hN.pos⟩
    · exact ⟨⟨spanLattice_N_taupk_sub τ hτ N hN.pos k,
              index_prime_isAddCyclic τ hτ N hN _ (spanLattice_N_taupk_sub τ hτ N hN.pos k)
                (spanLattice_N_taupk_index τ hτ N hN.pos k)⟩,
             spanLattice_N_taupk_index τ hτ N hN.pos k⟩

end
