/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Algebra.Algebra.Basic
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.FreeModule.StrongRankCondition
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.Algebra.Quaternion
import Mathlib.Algebra.QuaternionBasis
import Atlas.EllipticCurves.code.EndAlgebra
import Atlas.EllipticCurves.code.EndomorphismAlgebra
import Mathlib.RingTheory.Flat.Localization
import Mathlib.RingTheory.SimpleRing.Basic

open Module
open scoped Quaternion TensorProduct

/-- A `ℚ`-algebra `A` equipped with an anti-involution `invol` together with a positive-definite
reduced norm `normMap : A → ℚ` satisfying `a * invol a = normMap a`. This abstracts the structure
of the Rosati involution on the endomorphism algebra of an abelian variety. -/
class PositiveDefiniteInvolutionAlgebra (A : Type*) [Ring A] [Algebra ℚ A] where
  invol : A → A
  invol_invol : ∀ a : A, invol (invol a) = a
  invol_add : ∀ a b : A, invol (a + b) = invol a + invol b
  invol_mul : ∀ a b : A, invol (a * b) = invol b * invol a
  invol_one : invol 1 = 1
  invol_rat : ∀ q : ℚ, invol ((algebraMap ℚ A) q) = (algebraMap ℚ A) q
  normMap : A → ℚ
  normMap_spec : ∀ a : A, a * invol a = (algebraMap ℚ A) (normMap a)
  normMap_pos : ∀ a : A, a ≠ 0 → 0 < normMap a

namespace PositiveDefiniteInvolutionAlgebra

variable {A : Type*} [Ring A] [Algebra ℚ A] [PositiveDefiniteInvolutionAlgebra A]

/-- The reduced trace `tr(a) = N(a + 1) - N(a) - 1`, induced by the reduced norm. -/
noncomputable def traceMap (a : A) : ℚ :=
  normMap (a + 1) - normMap a - 1

end PositiveDefiniteInvolutionAlgebra

/-- Albert's classification of finite-dimensional positive-definite involution `ℚ`-algebras `A`:
either `A = ℚ` (dimension `1`), or `A` is an imaginary quadratic field (dimension `2` with a
non-rational element squaring to a negative rational), or `A` is a definite quaternion algebra
(dimension `4` with anticommuting generators squaring to negative rationals). -/
inductive EndAlgClassification (A : Type*) [Ring A] [Algebra ℚ A] : Prop where
  | rational (h : finrank ℚ A = 1) : EndAlgClassification A
  | imaginaryQuadratic (hdim : finrank ℚ A = 2)
      (hα : ∃ α : A, (∀ q : ℚ, α ≠ (algebraMap ℚ A) q) ∧
            ∃ d : ℚ, d < 0 ∧ α * α = (algebraMap ℚ A) d) :
      EndAlgClassification A
  | quaternionAlgebra (hdim : finrank ℚ A = 4)
      (hαβ : ∃ α β : A,
            (∃ a : ℚ, a < 0 ∧ α * α = (algebraMap ℚ A) a) ∧
            (∃ b : ℚ, b < 0 ∧ β * β = (algebraMap ℚ A) b) ∧
            α * β = -(β * α)) :
      EndAlgClassification A

/-- In a positive-definite involution algebra, any element `β` that commutes with a non-rational
element `α` lies in the `ℚ`-subalgebra generated by `α`: there exist `r, s ∈ ℚ` with `β = r + s α`.
This is the crucial step that forces a `4`-dimensional algebra to be a quaternion algebra. -/
theorem commuting_elements_in_subfield
  {A : Type*} [Ring A] [Algebra ℚ A] [PositiveDefiniteInvolutionAlgebra A]
  (α β : A)
  (hcomm : α * β = β * α)
  (hα_not_rat : ∀ q : ℚ, α ≠ (algebraMap ℚ A) q) :
  ∃ r s : ℚ, β = (algebraMap ℚ A) r + (algebraMap ℚ A) s * α := by
  open PositiveDefiniteInvolutionAlgebra in
  have inv0 : invol (0 : A) = 0 := by
    have := invol_rat (0 : ℚ) (A := A); simp only [map_zero] at this; exact this
  have inv_neg : ∀ a : A, invol (-a) = -invol a := fun a =>
    eq_neg_of_add_eq_zero_right (by rw [← invol_add, add_neg_cancel, inv0])
  have inv_sub : ∀ a b : A, invol (a - b) = invol a - invol b := fun a b => by
    simp only [sub_eq_add_neg, invol_add, inv_neg]
  have inv_add_self : ∀ a : A, a + invol a = (algebraMap ℚ A) (traceMap a) := by
    intro a; have h1 := normMap_spec (a + 1); rw [invol_add, invol_one] at h1
    have : (a + 1) * (invol a + 1) = a * invol a + a + invol a + 1 := by
      simp only [mul_add, add_mul, mul_one, one_mul]; abel
    rw [this, normMap_spec] at h1
    show a + invol a = (algebraMap ℚ A) (normMap (a + 1) - normMap a - 1)
    rw [map_sub, map_sub, map_one]
    calc a + invol a
      = (algebraMap ℚ A) (normMap a) + (a + invol a) + 1 - (algebraMap ℚ A) (normMap a) - 1 := by abel
      _ = (algebraMap ℚ A) (normMap (a + 1)) - (algebraMap ℚ A) (normMap a) - 1 := by
          congr 1; congr 1; convert h1 using 1; abel
  have nzd : ∀ a b : A, a * b = 0 → b ≠ 0 → a = 0 := by
    intro a b hab hb; have hN : (normMap b : ℚ) ≠ 0 := ne_of_gt (normMap_pos b hb)
    have h : normMap b • a = 0 := by
      have : a * (algebraMap ℚ A) (normMap b) = 0 := by
        rw [← normMap_spec, ← mul_assoc, hab, zero_mul]
      rwa [Algebra.algebraMap_eq_smul_one, mul_smul_comm, mul_one] at this
    have : ((normMap b)⁻¹ * normMap b) • a = 0 := by rw [mul_smul, h, smul_zero]
    simpa [inv_mul_cancel₀ hN] using this
  have char0 : ∀ a : A, a + a = 0 → a = 0 := by
    intro a h; have h2 : (2 : ℚ) • a = 0 := by rw [two_smul]; exact h
    have h3 : ((2 : ℚ)⁻¹ * 2) • a = 0 := by rw [mul_smul, h2, smul_zero]
    simpa using h3
  have trace_norm : ∀ (a : A) (q : ℚ),
      (a - (algebraMap ℚ A) q) + invol (a - (algebraMap ℚ A) q) =
      (algebraMap ℚ A) (traceMap a - 2 * q) := by
    intro a q; rw [inv_sub, invol_rat]
    calc (a - (algebraMap ℚ A) q) + (invol a - (algebraMap ℚ A) q)
      = (a + invol a) - (algebraMap ℚ A) q - (algebraMap ℚ A) q := by abel
      _ = (algebraMap ℚ A) (traceMap a) - (algebraMap ℚ A) q - (algebraMap ℚ A) q := by rw [inv_add_self]
      _ = (algebraMap ℚ A) (traceMap a) - ((algebraMap ℚ A) q + (algebraMap ℚ A) q) := by abel
      _ = (algebraMap ℚ A) (traceMap a) - (algebraMap ℚ A) (2 * q) := by rw [← map_add]; ring_nf
      _ = (algebraMap ℚ A) (traceMap a - 2 * q) := by rw [map_sub]
  have inv_neg_of_half_trace : ∀ (a : A),
      invol (a - (algebraMap ℚ A) (traceMap a / 2)) = -(a - (algebraMap ℚ A) (traceMap a / 2)) := by
    intro a; apply eq_neg_of_add_eq_zero_right
    have h := trace_norm a (traceMap a / 2)
    have hzero : traceMap a - 2 * (traceMap a / 2) = 0 := by ring
    rw [hzero, map_zero] at h; exact h

  set rα := traceMap α / 2; set α₀ := α - (algebraMap ℚ A) rα
  have hα₀_nrat : ∀ q : ℚ, α₀ ≠ (algebraMap ℚ A) q := by
    intro q habs; exact hα_not_rat (q + rα) (by
      calc α = α₀ + (algebraMap ℚ A) rα := by simp [α₀]
        _ = (algebraMap ℚ A) q + (algebraMap ℚ A) rα := by rw [habs]
        _ = _ := by rw [← map_add])
  have hα₀_ne : α₀ ≠ 0 := fun h => hα₀_nrat 0 (by rw [h, map_zero])
  have hinv_α₀ : invol α₀ = -α₀ := inv_neg_of_half_trace α

  set sβ := traceMap β / 2; set β₁ := β - (algebraMap ℚ A) sβ
  have hinv_β₁ : invol β₁ = -β₁ := inv_neg_of_half_trace β
  have hcomm₀₁ : α₀ * β₁ = β₁ * α₀ := by
    show (α - (algebraMap ℚ A) rα) * (β - (algebraMap ℚ A) sβ) =
         (β - (algebraMap ℚ A) sβ) * (α - (algebraMap ℚ A) rα)
    simp only [mul_sub, sub_mul]
    rw [← Algebra.commutes sβ α, ← Algebra.commutes rα β, Algebra.commutes rα ((algebraMap ℚ A) sβ), hcomm]; abel

  have hNα₀_ne : normMap α₀ ≠ 0 := ne_of_gt (normMap_pos α₀ hα₀_ne)
  set tc := -(traceMap (α₀ * β₁)) / (2 * normMap α₀)
  set β₀ := β₁ - (algebraMap ℚ A) tc * α₀
  have hcomm₀ : α₀ * β₀ = β₀ * α₀ := by
    show α₀ * (β₁ - (algebraMap ℚ A) tc * α₀) = (β₁ - (algebraMap ℚ A) tc * α₀) * α₀
    simp only [mul_sub, sub_mul, mul_assoc, Algebra.commutes]; rw [hcomm₀₁]
  have hinv_β₀ : invol β₀ = -β₀ := by
    show invol (β₁ - (algebraMap ℚ A) tc * α₀) = -(β₁ - (algebraMap ℚ A) tc * α₀)
    rw [inv_sub, invol_mul, hinv_α₀, invol_rat, hinv_β₁, Algebra.commutes tc α₀]
    simp only [neg_mul, neg_sub]; abel
  have hα₀_sq : α₀ * α₀ = -(algebraMap ℚ A) (normMap α₀) := by
    have h := normMap_spec α₀; rw [hinv_α₀, mul_neg] at h
    calc α₀ * α₀ = -(-(α₀ * α₀)) := by abel
      _ = -(algebraMap ℚ A) (normMap α₀) := by rw [h]
  have htr_01 := inv_add_self (α₀ * β₁)
  rw [show invol (α₀ * β₁) = β₁ * α₀ from by rw [invol_mul, hinv_α₀, hinv_β₁, neg_mul_neg],
      ← hcomm₀₁] at htr_01


  have key_sum : β₀ * α₀ + β₀ * α₀ = 0 := by
    have expand : β₀ * α₀ = α₀ * β₁ + (algebraMap ℚ A) tc * (algebraMap ℚ A) (normMap α₀) := by
      show (β₁ - (algebraMap ℚ A) tc * α₀) * α₀ =
           α₀ * β₁ + (algebraMap ℚ A) tc * (algebraMap ℚ A) (normMap α₀)
      rw [sub_mul, mul_assoc, hα₀_sq, ← hcomm₀₁]; simp only [mul_neg, sub_neg_eq_add]
    rw [expand]
    have step : (α₀ * β₁ + (algebraMap ℚ A) tc * (algebraMap ℚ A) (normMap α₀)) +
                (α₀ * β₁ + (algebraMap ℚ A) tc * (algebraMap ℚ A) (normMap α₀))
              = (α₀ * β₁ + α₀ * β₁) +
                ((algebraMap ℚ A) tc * (algebraMap ℚ A) (normMap α₀) +
                 (algebraMap ℚ A) tc * (algebraMap ℚ A) (normMap α₀)) := by abel
    rw [step, htr_01, ← map_mul, ← map_add,
      show tc * normMap α₀ + tc * normMap α₀ = 2 * tc * normMap α₀ from by ring,
      show 2 * tc * normMap α₀ = -(traceMap (α₀ * β₁)) from by
        simp only [tc]; field_simp]
    simp [map_neg, add_neg_cancel]

  have hβα_zero : β₀ * α₀ = 0 := char0 _ key_sum
  have hαβ_zero : α₀ * β₀ = 0 := by rw [hcomm₀, hβα_zero]
  have hβ₀_zero : β₀ = 0 := by
    by_contra hβ₀_ne; exact hα₀_ne (nzd α₀ β₀ hαβ_zero hβ₀_ne)
  exact ⟨sβ - tc * rα, tc, by
    have hβ₁_eq : β₁ = (algebraMap ℚ A) tc * α₀ := sub_eq_zero.mp hβ₀_zero
    calc β = β₁ + (algebraMap ℚ A) sβ := by simp [β₁]
      _ = (algebraMap ℚ A) tc * α₀ + (algebraMap ℚ A) sβ := by rw [hβ₁_eq]
      _ = (algebraMap ℚ A) tc * (α - (algebraMap ℚ A) rα) + (algebraMap ℚ A) sβ := rfl
      _ = (algebraMap ℚ A) tc * α - (algebraMap ℚ A) tc * (algebraMap ℚ A) rα +
            (algebraMap ℚ A) sβ := by rw [mul_sub]
      _ = (algebraMap ℚ A) (sβ - tc * rα) + (algebraMap ℚ A) tc * α := by
          rw [← map_mul, map_sub]; abel⟩

section QuaternionHelpers
variable {A : Type*} [Ring A] [Algebra ℚ A] [PositiveDefiniteInvolutionAlgebra A]
open PositiveDefiniteInvolutionAlgebra

set_option maxHeartbeats 800000 in
/-- Given a pure imaginary element `α` (anti-fixed by the involution) and a candidate `β₁` not in
the subfield `ℚ[α]`, produce a pure imaginary element `β` anticommuting with `α`, by Gram-Schmidt
style adjustment. This is a key step in constructing a quaternion basis. -/
lemma pdi_make_anticommuting (α β₁ : A)
    (hinv_α : invol α = -α) (hinv_β₁ : invol β₁ = -β₁)
    (hα_sq : α * α = -(algebraMap ℚ A) (normMap α))
    (hNα_pos : 0 < normMap α)
    (hias : ∀ a : A, a + invol a = (algebraMap ℚ A) (traceMap a))
    (hβ₁ni : ∀ r s : ℚ, β₁ ≠ (algebraMap ℚ A) r + (algebraMap ℚ A) s * α) :
    ∃ β : A, invol β = -β ∧ α * β = -(β * α) ∧
      (∀ r s : ℚ, β ≠ (algebraMap ℚ A) r + (algebraMap ℚ A) s * α) ∧ β ≠ 0 := by
  set tc := -(traceMap (α * β₁) / (2 * normMap α))
  set β := β₁ - (algebraMap ℚ A) tc * α
  have hβ₁_rec : β₁ = β + (algebraMap ℚ A) tc * α := by simp [β]
  refine ⟨β, ?_, ?_, ?_, ?_⟩
  ·
    have hinv_sub : ∀ a b : A, invol (a - b) = invol a - invol b := by
      intro a b; simp only [sub_eq_add_neg]
      have inv0 : invol (0 : A) = 0 := by
        have := invol_rat (0 : ℚ) (A := A); simp only [map_zero] at this; exact this
      have inv_neg : ∀ x : A, invol (-x) = -invol x := fun x =>
        eq_neg_of_add_eq_zero_right (by rw [← invol_add, add_neg_cancel, inv0])
      rw [invol_add, inv_neg]
    have hinv_tc_α : invol ((algebraMap ℚ A) tc * α) = -((algebraMap ℚ A) tc * α) := by
      rw [invol_mul, hinv_α, invol_rat, neg_mul, Algebra.commutes]
    rw [show β = β₁ - (algebraMap ℚ A) tc * α from rfl, hinv_sub, hinv_β₁, hinv_tc_α]
    simp only [neg_neg, sub_eq_add_neg]; abel
  ·
    apply eq_neg_of_add_eq_zero_left
    show α * (β₁ - (algebraMap ℚ A) tc * α) + (β₁ - (algebraMap ℚ A) tc * α) * α = 0
    rw [mul_sub, sub_mul,
      show α * ((algebraMap ℚ A) tc * α) = (algebraMap ℚ A) tc * (α * α) from
        by rw [← mul_assoc, ← Algebra.commutes, mul_assoc],
      mul_assoc, hα_sq,
      show (algebraMap ℚ A) tc * -((algebraMap ℚ A) (normMap α)) =
        -((algebraMap ℚ A) (tc * normMap α)) from by rw [mul_neg, ← map_mul]]
    have hsum : α * β₁ + β₁ * α = (algebraMap ℚ A) (traceMap (α * β₁)) := by
      conv_lhs => rw [show β₁ * α = invol (α * β₁) from by
        rw [invol_mul, hinv_β₁, hinv_α, neg_mul_neg]]
      exact hias _
    rw [show α * β₁ - -((algebraMap ℚ A) (tc * normMap α)) +
      (β₁ * α - -((algebraMap ℚ A) (tc * normMap α))) =
      (α * β₁ + β₁ * α) + ((algebraMap ℚ A) (tc * normMap α) +
        (algebraMap ℚ A) (tc * normMap α)) from by abel,
      hsum, ← map_add, ← map_add]
    convert map_zero (algebraMap ℚ A) using 2
    show traceMap (α * β₁) + (-(traceMap (α * β₁) / (2 * normMap α)) * normMap α +
      -(traceMap (α * β₁) / (2 * normMap α)) * normMap α) = 0
    have : normMap α ≠ 0 := ne_of_gt hNα_pos; field_simp; ring
  · intro r s h; exact hβ₁ni r (s + tc) (by rw [hβ₁_rec, h, map_add, add_mul]; abel)
  · intro h; exact hβ₁ni 0 tc (by rw [hβ₁_rec, h, zero_add, map_zero, zero_add])

end QuaternionHelpers

set_option maxHeartbeats 6400000 in
set_option linter.unusedSimpArgs false in
/-- In a positive-definite involution algebra `A`, the four elements `{1, α, β, αβ}` are
`ℚ`-linearly independent whenever `α` is non-rational, anticommutes with `β`, `β ∉ ℚ[α]`, and the
norms behave as in a quaternion algebra. -/
theorem quaternion_linIndep_four
    {A : Type*} [Ring A] [Algebra ℚ A]
    [PositiveDefiniteInvolutionAlgebra A]
    (α β : A)
    (hα_ne : α ≠ 0)
    (hα_not_rat : ∀ q : ℚ, α ≠ (algebraMap ℚ A) q)
    (hα_sq_val : α * α = (algebraMap ℚ A) (-(PositiveDefiniteInvolutionAlgebra.normMap α)))
    (hanticomm : α * β = -(β * α))
    (hβni : ∀ r s : ℚ, β ≠ (algebraMap ℚ A) r + (algebraMap ℚ A) s * α)
    (hNα_pos : 0 < PositiveDefiniteInvolutionAlgebra.normMap α) :
    LinearIndependent ℚ ![1, α, β, α * β] := by
  set Nα := PositiveDefiniteInvolutionAlgebra.normMap α
  rw [Fintype.linearIndependent_iff]
  intro g hg
  replace hg : g 0 • (1 : A) + g 1 • α + g 2 • β + g 3 • (α * β) = 0 := by
    simp only [Fin.sum_univ_four] at hg
    dsimp [Matrix.vecCons, Matrix.vecHead, Matrix.vecTail] at hg
    exact hg

  have hgα : g 0 • α + (g 1 * (-Nα)) • (1 : A) + g 2 • (α * β) +
      (g 3 * (-Nα)) • β = 0 := by
    have hmul := congr_arg (α * ·) hg
    simp only [mul_zero, mul_add, mul_smul_comm] at hmul
    rw [mul_one, hα_sq_val, ← mul_assoc, hα_sq_val] at hmul
    simp only [Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul,
      smul_smul] at hmul
    exact hmul


  have hg23 : g 2 = 0 ∧ g 3 = 0 := by
    suffices hcoeff_zero : (g 2) ^ 2 + Nα * (g 3) ^ 2 = 0 by
      have h2_sq : (g 2) ^ 2 = 0 := by nlinarith [sq_nonneg (g 2), sq_nonneg (g 3)]
      have h3_sq : (g 3) ^ 2 = 0 := by
        have : Nα * (g 3) ^ 2 = 0 := by nlinarith [sq_nonneg (g 2)]
        exact (mul_eq_zero.mp this).resolve_left (ne_of_gt hNα_pos)
      exact ⟨by rwa [sq, mul_self_eq_zero] at h2_sq,
             by rwa [sq, mul_self_eq_zero] at h3_sq⟩
    by_contra hcoeff_ne


    have h1 : g 2 • (g 0 • (1 : A) + g 1 • α + g 2 • β + g 3 • (α * β)) = 0 := by
      rw [hg, smul_zero]
    have h2 : g 3 • (g 0 • α + (g 1 * (-Nα)) • (1 : A) + g 2 • (α * β) +
        (g 3 * (-Nα)) • β) = 0 := by
      rw [hgα, smul_zero]
    simp only [smul_add, smul_smul] at h1 h2


    have elim : ((g 2) ^ 2 + Nα * (g 3) ^ 2) • β =
        -((g 2 * g 0 - g 3 * (g 1 * (-Nα))) • (1 : A) +
          (g 2 * g 1 - g 3 * g 0) • α) := by
      linear_combination (norm := module) h1 - h2

    have hβ_val : β = ((g 2) ^ 2 + Nα * (g 3) ^ 2)⁻¹ •
        (-((g 2 * g 0 - g 3 * (g 1 * (-Nα))) • (1 : A) +
        (g 2 * g 1 - g 3 * g 0) • α)) := by
      rw [← elim, inv_smul_smul₀ hcoeff_ne]

    simp only [neg_add_rev, smul_add, smul_smul, ← neg_smul] at hβ_val

    rw [← Algebra.algebraMap_eq_smul_one, Algebra.smul_def, add_comm] at hβ_val

    exact absurd hβ_val (hβni _ _)

  obtain ⟨hg2, hg3⟩ := hg23

  rw [hg2, hg3, zero_smul, zero_smul, add_zero, add_zero] at hg
  have hg01 : g 0 = 0 ∧ g 1 = 0 := by
    rcases eq_or_ne (g 1) 0 with hg1_eq | hg1_ne
    · rw [hg1_eq, zero_smul, add_zero] at hg
      refine ⟨?_, hg1_eq⟩
      by_contra hg0_ne
      have : (1 : A) = (g 0)⁻¹ • (g 0 • (1 : A)) := by rw [inv_smul_smul₀ hg0_ne]
      rw [hg, smul_zero] at this
      exact hα_ne (by rw [show α = α * 1 from (mul_one α).symm, this, mul_zero])
    · exfalso
      have hsum : (g 1) • α = -(g 0 • (1 : A)) := by
        have := hg
        rw [show g 0 • (1 : A) + g 1 • α = g 1 • α + g 0 • (1 : A) from by abel] at this
        exact eq_neg_of_add_eq_zero_left this
      rw [← neg_smul] at hsum
      have h1 : α = (g 1)⁻¹ • ((-g 0) • (1 : A)) := by
        rw [← hsum, inv_smul_smul₀ hg1_ne]
      rw [smul_smul, ← Algebra.algebraMap_eq_smul_one] at h1
      exact hα_not_rat _ h1
  obtain ⟨hg0, hg1⟩ := hg01
  intro i; fin_cases i <;> assumption

set_option maxHeartbeats 6400000 in
set_option linter.unusedSimpArgs false in
/-- If `A` is a positive-definite involution algebra containing anticommuting pure imaginary
elements `α, β` with the right norm properties, then `A` has `ℚ`-dimension exactly `4`, with basis
`{1, α, β, αβ}`. -/
theorem endAlg_quaternion_finrank_four
    (A : Type*) [Ring A] [Algebra ℚ A]
    [PositiveDefiniteInvolutionAlgebra A] [Nontrivial A]
    (α β : A)
    (hα_ne : α ≠ 0) (hβ_ne : β ≠ 0)
    (hinv_α : PositiveDefiniteInvolutionAlgebra.invol α = -α)
    (hinv_β : PositiveDefiniteInvolutionAlgebra.invol β = -β)
    (hα_not_rat : ∀ q : ℚ, α ≠ (algebraMap ℚ A) q)
    (hα_sq_val : α * α = (algebraMap ℚ A) (-(PositiveDefiniteInvolutionAlgebra.normMap α)))
    (hβ_sq_val : β * β = (algebraMap ℚ A) (-(PositiveDefiniteInvolutionAlgebra.normMap β)))
    (hanticomm : α * β = -(β * α))
    (hβni : ∀ r s : ℚ, β ≠ (algebraMap ℚ A) r + (algebraMap ℚ A) s * α)
    (hαβ_not_rat : ∀ q : ℚ, α * β ≠ (algebraMap ℚ A) q)
    (inv_add_self : ∀ a : A,
      a + PositiveDefiniteInvolutionAlgebra.invol a =
        (algebraMap ℚ A) (PositiveDefiniteInvolutionAlgebra.traceMap a))
    (inv_neg_of_ht : ∀ a : A,
      PositiveDefiniteInvolutionAlgebra.invol
        (a - (algebraMap ℚ A) (PositiveDefiniteInvolutionAlgebra.traceMap a / 2)) =
          -(a - (algebraMap ℚ A) (PositiveDefiniteInvolutionAlgebra.traceMap a / 2))) :
    Module.finrank ℚ A = 4 := by
  open PositiveDefiniteInvolutionAlgebra in
  have hNα_pos : 0 < normMap α := normMap_pos α hα_ne
  have hNβ_pos : 0 < normMap β := normMap_pos β hβ_ne
  have hNβ_ne : (normMap β : ℚ) ≠ 0 := ne_of_gt hNβ_pos


  have hli : LinearIndependent ℚ ![1, α, β, α * β] :=
    quaternion_linIndep_four α β hα_ne hα_not_rat hα_sq_val hanticomm hβni hNα_pos

  have hsp : Submodule.span ℚ (Set.range ![1, α, β, α * β]) = ⊤ := by
    rw [Submodule.eq_top_iff']
    intro γ


    set tγ := traceMap γ / 2 with tγ_def
    set γ₀ := γ - (algebraMap ℚ A) tγ with γ₀_def
    have hinv_γ₀ : invol γ₀ = -γ₀ := inv_neg_of_ht γ

    set tαγ := traceMap (α * γ₀) / (2 * normMap α) with tαγ_def
    set γ₁ := γ₀ + (algebraMap ℚ A) tαγ * α with γ₁_def

    have hinv_γ₁ : invol γ₁ = -γ₁ := by
      show invol (γ₀ + (algebraMap ℚ A) tαγ * α) = -(γ₀ + (algebraMap ℚ A) tαγ * α)
      rw [invol_add, invol_mul, hinv_α, invol_rat, hinv_γ₀]

      rw [neg_mul, (Algebra.commutes tαγ α).symm, neg_add_rev]; abel


    have hinv_αγ₁ : invol (α * γ₁) = γ₁ * α := by
      rw [invol_mul, hinv_α, hinv_γ₁, neg_mul_neg]

    have hT_αγ₁ : α * γ₁ + γ₁ * α = 0 := by
      have hias := inv_add_self (α * γ₁)
      rw [hinv_αγ₁] at hias


      suffices hT : traceMap (α * γ₁) = 0 by
        rw [hT, map_zero] at hias
        exact hias


      have hαγ₁_expand : α * γ₁ = α * γ₀ + (algebraMap ℚ A) (tαγ * -(normMap α)) := by
        show α * (γ₀ + (algebraMap ℚ A) tαγ * α) = α * γ₀ + (algebraMap ℚ A) (tαγ * -(normMap α))
        rw [mul_add, ← mul_assoc,
            show α * ((algebraMap ℚ A) tαγ) = (algebraMap ℚ A) tαγ * α from
              (Algebra.commutes tαγ α).symm,
            mul_assoc, hα_sq_val, ← map_mul]


      have trace_shift : ∀ (x : A) (q : ℚ), traceMap (x + (algebraMap ℚ A) q) = traceMap x + 2 * q := by
        intro x q
        have h1 := inv_add_self (x + (algebraMap ℚ A) q)
        rw [invol_add, invol_rat] at h1
        have h2 := inv_add_self x

        have h3 : (algebraMap ℚ A) (traceMap x + (q + q)) =
            (algebraMap ℚ A) (traceMap (x + (algebraMap ℚ A) q)) := by
          rw [map_add, map_add, ← h2, ← h1]; abel
        have h4 := RingHom.injective (algebraMap ℚ A) h3
        linarith [show q + q = 2 * q from by ring]
      rw [hαγ₁_expand, trace_shift]
      simp only [tαγ_def]
      have hNα_ne : normMap α ≠ 0 := ne_of_gt hNα_pos
      field_simp; ring

    have hanticomm_γ₁ : α * γ₁ = -(γ₁ * α) := eq_neg_of_add_eq_zero_left hT_αγ₁

    have hcomm_βγ₁ : α * (β * γ₁) = (β * γ₁) * α := by
      calc α * (β * γ₁) = (α * β) * γ₁ := by rw [mul_assoc]
        _ = (-(β * α)) * γ₁ := by rw [hanticomm]
        _ = -(β * (α * γ₁)) := by rw [neg_mul, mul_assoc]
        _ = -(β * (-(γ₁ * α))) := by rw [hanticomm_γ₁]
        _ = β * (γ₁ * α) := by rw [mul_neg, neg_neg]
        _ = (β * γ₁) * α := by rw [mul_assoc]

    obtain ⟨r, s, hβγ₁⟩ := commuting_elements_in_subfield α (β * γ₁) hcomm_βγ₁ hα_not_rat


    have hsolve_γ₁ : (-(normMap β)) • γ₁ = r • β + s • (-(α * β)) := by

      have lhs_eq : β * (β * γ₁) = (-(normMap β)) • γ₁ := by
        rw [← mul_assoc, hβ_sq_val, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]

      have rhs_eq : β * ((algebraMap ℚ A) r + (algebraMap ℚ A) s * α) =
          r • β + s • (-(α * β)) := by
        have hβα : β * α = -(α * β) := (neg_eq_of_add_eq_zero_right
          (show α * β + β * α = 0 by rw [hanticomm, neg_add_cancel])).symm
        calc β * ((algebraMap ℚ A) r + (algebraMap ℚ A) s * α)
          = β * (algebraMap ℚ A) r + β * ((algebraMap ℚ A) s * α) := by rw [mul_add]
          _ = (algebraMap ℚ A) r * β + (algebraMap ℚ A) s * (β * α) := by
              rw [(Algebra.commutes r β).symm,
                  show β * ((algebraMap ℚ A) s * α) = (algebraMap ℚ A) s * (β * α) from by
                    rw [← mul_assoc, (Algebra.commutes s β).symm, mul_assoc]]
          _ = (algebraMap ℚ A) r * β + (algebraMap ℚ A) s * (-(α * β)) := by rw [hβα]
          _ = r • β + s • (-(α * β)) := by
              simp only [Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
      rw [← lhs_eq, hβγ₁, rhs_eq]

    have hNβ_neg_ne : (-(normMap β) : ℚ) ≠ 0 := by linarith
    have hγ₁_in_span : γ₁ ∈ Submodule.span ℚ (Set.range ![1, α, β, α * β]) := by
      have hγ₁_eq : γ₁ = (-(normMap β))⁻¹ • (r • β + s • (-(α * β))) := by
        rw [← hsolve_γ₁, inv_smul_smul₀ hNβ_neg_ne]
      rw [hγ₁_eq, smul_add, smul_smul, smul_smul, smul_neg]
      apply Submodule.add_mem
      · exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨2, by simp [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.head_fin_const]⟩)
      · exact Submodule.neg_mem _ (Submodule.smul_mem _ _ (Submodule.subset_span ⟨3, by simp [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.head_fin_const]⟩))


    have hγ_eq : γ = γ₁ + (algebraMap ℚ A) (-(tαγ)) * α + (algebraMap ℚ A) tγ := by
      simp only [γ₁_def, γ₀_def, map_neg, neg_mul]
      abel
    rw [hγ_eq]
    apply Submodule.add_mem
    apply Submodule.add_mem
    · exact hγ₁_in_span
    · rw [show (algebraMap ℚ A) (-(tαγ)) * α = (-(tαγ)) • α from by
          rw [Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨1, by simp [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.head_fin_const]⟩)
    · rw [Algebra.algebraMap_eq_smul_one]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨0, by simp [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.head_fin_const]⟩)

  rw [finrank_eq_card_basis (Basis.mk hli hsp.ge), Fintype.card_fin]

set_option maxHeartbeats 800000 in
/-- The quaternion case of Albert's classification: given a pure imaginary element `α` and an
element not in `ℚ[α]`, build a quaternion basis and conclude that `A` is a definite quaternion
algebra. -/
lemma endAlg_quaternion_case
    (A : Type*) [Ring A] [Algebra ℚ A]
    [PositiveDefiniteInvolutionAlgebra A] [Nontrivial A]
    (α : A)
    (hinv_α : PositiveDefiniteInvolutionAlgebra.invol α = -α)
    (hα_ne : α ≠ 0)
    (hα_not_rat : ∀ q : ℚ, α ≠ (algebraMap ℚ A) q)
    (hNα_pos : 0 < PositiveDefiniteInvolutionAlgebra.normMap α)
    (hα_sq_val : α * α = (algebraMap ℚ A) (-(PositiveDefiniteInvolutionAlgebra.normMap α)))
    (inv_add_self : ∀ a : A,
      a + PositiveDefiniteInvolutionAlgebra.invol a =
        (algebraMap ℚ A) (PositiveDefiniteInvolutionAlgebra.traceMap a))
    (inv_neg_of_ht : ∀ a : A,
      PositiveDefiniteInvolutionAlgebra.invol
        (a - (algebraMap ℚ A) (PositiveDefiniteInvolutionAlgebra.traceMap a / 2)) =
          -(a - (algebraMap ℚ A) (PositiveDefiniteInvolutionAlgebra.traceMap a / 2)))
    (hall_in_α : ¬∀ a : A, ∃ r s : ℚ, a = (algebraMap ℚ A) r + (algebraMap ℚ A) s * α) :
    EndAlgClassification A := by
  classical
  open PositiveDefiniteInvolutionAlgebra in
  push_neg at hall_in_α; obtain ⟨β_raw, hβ_raw⟩ := hall_in_α

  have hα_sq : α * α = -(algebraMap ℚ A) (normMap α) := by rw [map_neg] at hα_sq_val; exact hα_sq_val

  set sβ := traceMap β_raw / 2 with hsβ_def
  have hinv_β₁ : invol (β_raw - (algebraMap ℚ A) sβ) =
      -(β_raw - (algebraMap ℚ A) sβ) := inv_neg_of_ht β_raw
  have hβ₁ni : ∀ r s : ℚ,
      β_raw - (algebraMap ℚ A) sβ ≠ (algebraMap ℚ A) r + (algebraMap ℚ A) s * α := by
    intro r s habs
    apply hβ_raw (r + sβ) s
    have : β_raw = (algebraMap ℚ A) r + (algebraMap ℚ A) s * α + (algebraMap ℚ A) sβ :=
      sub_eq_iff_eq_add.mp habs
    calc β_raw = (algebraMap ℚ A) r + (algebraMap ℚ A) s * α + (algebraMap ℚ A) sβ := this
      _ = (algebraMap ℚ A) r + (algebraMap ℚ A) sβ + (algebraMap ℚ A) s * α := by abel
      _ = (algebraMap ℚ A) (r + sβ) + (algebraMap ℚ A) s * α := by rw [← map_add]
  obtain ⟨β, hinv_β, hanticomm, hβni, hβ_ne⟩ :=
    pdi_make_anticommuting α (β_raw - (algebraMap ℚ A) sβ)
      hinv_α hinv_β₁ hα_sq hNα_pos inv_add_self hβ₁ni
  clear hinv_β₁ hβ₁ni β_raw hβ_raw sβ hsβ_def
  have hNβ_pos : 0 < normMap β := normMap_pos β hβ_ne
  have hβ_sq_val : β * β = (algebraMap ℚ A) (-(normMap β)) := by
    have h := normMap_spec β; rw [hinv_β, mul_neg] at h
    rw [map_neg]; exact neg_eq_iff_eq_neg.mp h
  have hNα_neg : -(normMap α) < 0 := by linarith
  have hNβ_neg : -(normMap β) < 0 := by linarith

  have hαβ_not_rat : ∀ q : ℚ, α * β ≠ (algebraMap ℚ A) q := by
    intro q habs
    have h1 : α * (α * β) = α * (algebraMap ℚ A) q := congr_arg (α * ·) habs
    rw [← mul_assoc, hα_sq_val, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul,
      show α * (algebraMap ℚ A) q = (algebraMap ℚ A) q * α from (Algebra.commutes q α).symm,
      Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul] at h1
    by_cases hq : q = 0
    · rw [hq, zero_smul] at h1
      exact hβ_ne ((smul_eq_zero.mp h1).resolve_left (by linarith))
    · have hNα_ne : (-normMap α : ℚ) ≠ 0 := by linarith
      have h2 : β = (-normMap α)⁻¹ • (q • α) := by
        rw [← h1, inv_smul_smul₀ hNα_ne]
      rw [smul_smul] at h2
      exact hβni 0 ((-normMap α)⁻¹ * q) (by
        rw [h2, map_zero, zero_add, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul])
  have hdim : finrank ℚ A = 4 :=
    endAlg_quaternion_finrank_four A α β hα_ne hβ_ne hinv_α hinv_β hα_not_rat
      hα_sq_val hβ_sq_val hanticomm hβni hαβ_not_rat inv_add_self inv_neg_of_ht
  exact .quaternionAlgebra hdim
    ⟨α, β, ⟨-(normMap α), hNα_neg, hα_sq_val⟩, ⟨-(normMap β), hNβ_neg, hβ_sq_val⟩, hanticomm⟩

/-- Albert's classification of endomorphism algebras: every nontrivial finite-dimensional
positive-definite involution `ℚ`-algebra is either `ℚ` itself, an imaginary quadratic field, or a
definite quaternion algebra. -/
theorem endomorphism_algebra_classification
  (A : Type*) [Ring A] [Algebra ℚ A]
  [PositiveDefiniteInvolutionAlgebra A] [Nontrivial A] :
  EndAlgClassification A := by
  classical
  open PositiveDefiniteInvolutionAlgebra in

  have inv0 : invol (0 : A) = 0 := by
    have := invol_rat (0 : ℚ) (A := A); simp only [map_zero] at this; exact this
  have inv_neg : ∀ a : A, invol (-a) = -invol a := fun a =>
    eq_neg_of_add_eq_zero_right (by rw [← invol_add, add_neg_cancel, inv0])
  have inv_sub : ∀ a b : A, invol (a - b) = invol a - invol b := fun a b => by
    simp only [sub_eq_add_neg, invol_add, inv_neg]
  have inv_add_self : ∀ a : A, a + invol a = (algebraMap ℚ A) (traceMap a) := by
    intro a; have h1 := normMap_spec (a + 1); rw [invol_add, invol_one] at h1
    have : (a + 1) * (invol a + 1) = a * invol a + a + invol a + 1 := by
      simp only [mul_add, add_mul, mul_one, one_mul]; abel
    rw [this, normMap_spec] at h1
    show a + invol a = (algebraMap ℚ A) (normMap (a + 1) - normMap a - 1)
    rw [map_sub, map_sub, map_one]
    calc a + invol a
      = (algebraMap ℚ A) (normMap a) + (a + invol a) + 1 - (algebraMap ℚ A) (normMap a) - 1 := by abel
      _ = (algebraMap ℚ A) (normMap (a + 1)) - (algebraMap ℚ A) (normMap a) - 1 := by
          congr 1; congr 1; convert h1 using 1; abel
  have trace_norm : ∀ (a : A) (q : ℚ),
      (a - (algebraMap ℚ A) q) + invol (a - (algebraMap ℚ A) q) =
      (algebraMap ℚ A) (traceMap a - 2 * q) := by
    intro a q; rw [inv_sub, invol_rat]
    calc (a - (algebraMap ℚ A) q) + (invol a - (algebraMap ℚ A) q)
      = (a + invol a) - (algebraMap ℚ A) q - (algebraMap ℚ A) q := by abel
      _ = (algebraMap ℚ A) (traceMap a) - (algebraMap ℚ A) q - (algebraMap ℚ A) q := by rw [inv_add_self]
      _ = (algebraMap ℚ A) (traceMap a) - ((algebraMap ℚ A) q + (algebraMap ℚ A) q) := by abel
      _ = (algebraMap ℚ A) (traceMap a) - (algebraMap ℚ A) (2 * q) := by rw [← map_add]; ring_nf
      _ = (algebraMap ℚ A) (traceMap a - 2 * q) := by rw [map_sub]
  have inv_neg_of_half_trace : ∀ (a : A),
      invol (a - (algebraMap ℚ A) (traceMap a / 2)) = -(a - (algebraMap ℚ A) (traceMap a / 2)) := by
    intro a; apply eq_neg_of_add_eq_zero_right
    have h := trace_norm a (traceMap a / 2)
    have hzero : traceMap a - 2 * (traceMap a / 2) = 0 := by ring
    rw [hzero, map_zero] at h; exact h


  by_cases hall_rat : ∀ a : A, ∃ q : ℚ, a = (algebraMap ℚ A) q
  ·


    by_cases h1 : (1 : A) = 0
    ·
      exfalso
      have : Subsingleton A := subsingleton_of_forall_eq (0 : A) (fun x => by
        obtain ⟨q, hq⟩ := hall_rat x
        rw [hq, Algebra.algebraMap_eq_smul_one, h1, smul_zero])
      exact not_subsingleton A this
    · exact .rational ((finrank_eq_one_iff_of_nonzero' (1 : A) h1).mpr
        (fun w => by
          obtain ⟨q, hq⟩ := hall_rat w
          exact ⟨q, by simp only [Algebra.smul_def, mul_one]; exact hq.symm⟩))
  ·
    push_neg at hall_rat
    obtain ⟨α₀_raw, hα₀_not_rat⟩ := hall_rat


    set α := α₀_raw - (algebraMap ℚ A) (traceMap α₀_raw / 2) with α_def
    have hα_not_rat : ∀ q : ℚ, α ≠ (algebraMap ℚ A) q := by
      intro q habs
      exact (hα₀_not_rat (q + traceMap α₀_raw / 2)) (by
        calc α₀_raw = α + (algebraMap ℚ A) (traceMap α₀_raw / 2) := by simp [α_def]
          _ = (algebraMap ℚ A) q + (algebraMap ℚ A) (traceMap α₀_raw / 2) := by rw [habs]
          _ = _ := by rw [← map_add])
    have hα_ne : α ≠ 0 := fun h => hα_not_rat 0 (by rw [h, map_zero])
    have hone_ne : (1 : A) ≠ 0 := by
      intro h1; exact hα_ne (by rw [← mul_one α, h1, mul_zero])
    have hinv_α : invol α = -α := inv_neg_of_half_trace α₀_raw

    have hα_sq : α * α = -(algebraMap ℚ A) (normMap α) := by
      have h := normMap_spec α; rw [hinv_α, mul_neg] at h
      calc α * α = -(-(α * α)) := (neg_neg _).symm
        _ = -(algebraMap ℚ A) (normMap α) := by rw [h]
    have hNα_pos : 0 < normMap α := normMap_pos α hα_ne
    have hα_sq_val : α * α = (algebraMap ℚ A) (-(normMap α)) := by rw [map_neg]; exact hα_sq

    by_cases hall_in_α : ∀ a : A, ∃ r s : ℚ, a = (algebraMap ℚ A) r + (algebraMap ℚ A) s * α
    ·

      have hli : LinearIndependent ℚ ![((1 : A)), α] := by
        rw [linearIndependent_fin2]
        refine ⟨hα_ne, fun c hc => ?_⟩
        simp only [Matrix.cons_val_zero] at hc
        by_cases hc0 : c = 0
        · simp only [hc0, zero_smul] at hc; exact absurd hc.symm hone_ne
        · have hα_eq : α = (algebraMap ℚ A) c⁻¹ := by
            have h1 : c⁻¹ • (c • α) = c⁻¹ • (1 : A) := congr_arg (c⁻¹ • ·) hc
            rwa [inv_smul_smul₀ hc0, ← Algebra.algebraMap_eq_smul_one] at h1
          exact absurd hα_eq (hα_not_rat c⁻¹)


      have hsp : Submodule.span ℚ (Set.range ![((1 : A)), α]) = ⊤ := by
        rw [Submodule.eq_top_iff']
        intro a; obtain ⟨r, s, ha⟩ := hall_in_α a; rw [ha]
        apply Submodule.add_mem
        · rw [Algebra.algebraMap_eq_smul_one]
          exact Submodule.smul_mem _ r (Submodule.subset_span ⟨0, by simp⟩)
        · rw [show (algebraMap ℚ A) s * α = s • α from by
            rw [Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]]
          exact Submodule.smul_mem _ s (Submodule.subset_span ⟨1, by simp⟩)
      have hdim : finrank ℚ A = 2 := by
        rw [finrank_eq_card_basis (Basis.mk hli hsp.ge), Fintype.card_fin]
      have hd_neg : -(normMap α) < 0 := by linarith
      exact .imaginaryQuadratic hdim ⟨α, hα_not_rat, -(normMap α), hd_neg, hα_sq_val⟩
    ·
      exact endAlg_quaternion_case A α hinv_α hα_ne hα_not_rat hNα_pos
        hα_sq_val inv_add_self inv_neg_of_half_trace hall_in_α

universe u

namespace WeierstrassCurve.Affine

variable {F : Type u} [Field F] [DecidableEq F]
variable (E : WeierstrassCurve.Affine F)

/-- The endomorphism algebra `End⁰(E) := End(E) ⊗_ℤ ℚ` of an elliptic curve `E` carries a
positive-definite involution algebra structure: the Rosati involution together with the reduced
degree-norm. -/
noncomputable instance EndomorphismAlgebra.instPDInvAlgebra :
  @PositiveDefiniteInvolutionAlgebra (EndomorphismAlgebra E)
    (EndomorphismAlgebra.instRing E) (EndomorphismAlgebra.instAlgebra E) := by sorry

/-- The Rosati involution on the endomorphism algebra of `E`, packaged as a function. -/
noncomputable def EndomorphismAlgebra.rosatiInvol
    (x : @EndomorphismAlgebra F _ _ E) : @EndomorphismAlgebra F _ _ E :=
  letI := EndomorphismAlgebra.instRing E
  letI := EndomorphismAlgebra.instAlgebra E
  @PositiveDefiniteInvolutionAlgebra.invol _ _ _
    (EndomorphismAlgebra.instPDInvAlgebra E) x

/-- The reduced norm `End⁰(E) → ℚ` (the rational extension of the degree map on `End(E)`). -/
noncomputable def EndomorphismAlgebra.reducedNorm
    (x : @EndomorphismAlgebra F _ _ E) : ℚ :=
  letI := EndomorphismAlgebra.instRing E
  letI := EndomorphismAlgebra.instAlgebra E
  @PositiveDefiniteInvolutionAlgebra.normMap _ _ _
    (EndomorphismAlgebra.instPDInvAlgebra E) x

/-- The reduced trace `End⁰(E) → ℚ`, defined as `N(x + 1) - N(x) - 1`. -/
noncomputable def EndomorphismAlgebra.reducedTrace
    (x : @EndomorphismAlgebra F _ _ E) : ℚ :=
  letI := EndomorphismAlgebra.instRing E
  EndomorphismAlgebra.reducedNorm E
    (@HAdd.hAdd _ _ _ (@instHAdd _ (EndomorphismAlgebra.instRing E).toAdd) x
      (@OfNat.ofNat _ 1 (@One.toOfNat1 _ (EndomorphismAlgebra.instRing E).toOne)))
    - EndomorphismAlgebra.reducedNorm E x - 1

/-- The Rosati involution is additive. -/
theorem EndomorphismAlgebra.rosatiInvol_add (a b : EndomorphismAlgebra E) :
    letI := EndomorphismAlgebra.instRing E
    EndomorphismAlgebra.rosatiInvol E (@HAdd.hAdd _ _ _ (@instHAdd _ (EndomorphismAlgebra.instRing E).toAdd) a b) =
    @HAdd.hAdd _ _ _ (@instHAdd _ (EndomorphismAlgebra.instRing E).toAdd)
      (EndomorphismAlgebra.rosatiInvol E a) (EndomorphismAlgebra.rosatiInvol E b) := by
  letI := EndomorphismAlgebra.instRing E
  letI := EndomorphismAlgebra.instAlgebra E
  exact (EndomorphismAlgebra.instPDInvAlgebra E).invol_add a b

/-- The Rosati involution fixes the identity. -/
theorem EndomorphismAlgebra.rosatiInvol_one :
    letI := EndomorphismAlgebra.instRing E
    EndomorphismAlgebra.rosatiInvol E (1 : EndomorphismAlgebra E) = 1 := by
  letI := EndomorphismAlgebra.instRing E
  letI := EndomorphismAlgebra.instAlgebra E
  exact (EndomorphismAlgebra.instPDInvAlgebra E).invol_one

/-- The defining identity of the reduced norm: `a * a^† = N(a) · 1` in the endomorphism algebra. -/
theorem EndomorphismAlgebra.reducedNorm_spec (a : EndomorphismAlgebra E) :
    letI := EndomorphismAlgebra.instRing E
    letI := EndomorphismAlgebra.instAlgebra E
    @HMul.hMul _ _ _ (@instHMul _ (EndomorphismAlgebra.instRing E).toMul) a (EndomorphismAlgebra.rosatiInvol E a) =
    (algebraMap ℚ (EndomorphismAlgebra E)) (EndomorphismAlgebra.reducedNorm E a) := by
  letI := EndomorphismAlgebra.instRing E
  letI := EndomorphismAlgebra.instAlgebra E
  exact (EndomorphismAlgebra.instPDInvAlgebra E).normMap_spec a

/-- The integer algebra map into the endomorphism ring is injective: the canonical map
`ℤ → End(E)` has no kernel. -/
theorem EndomorphismAlgebra.algebraMap_int_injective :
    Function.Injective (algebraMap ℤ (EndRing E)) := by sorry

/-- The endomorphism algebra `End⁰(E)` is nontrivial: tensoring `End(E)` (a nontrivial ring with
injective integer algebra map) with `ℚ` over `ℤ` remains nontrivial since `ℚ` is `ℤ`-flat. -/
noncomputable instance EndomorphismAlgebra.instNontrivial :
    @Nontrivial (EndomorphismAlgebra E) := by
  letI : Ring (EndomorphismAlgebra E) := EndomorphismAlgebra.instRing E
  change Nontrivial ((EndRing E) ⊗[ℤ] ℚ)
  haveI : Module.Flat ℤ ℚ := IsLocalization.flat ℚ (nonZeroDivisors ℤ)
  exact Algebra.TensorProduct.nontrivial_of_algebraMap_injective_of_flat_right
    ℤ (EndRing E) ℚ (EndomorphismAlgebra.algebraMap_int_injective E)

/-- The endomorphism algebra `End⁰(E)` is a finite-dimensional `ℚ`-vector space. -/
theorem EndomorphismAlgebra.instFiniteDimensional :
  @FiniteDimensional ℚ (EndomorphismAlgebra E)
    _ (EndomorphismAlgebra.instRing E).toAddCommGroup
    (@Algebra.toModule ℚ (EndomorphismAlgebra E) _ _ (EndomorphismAlgebra.instAlgebra E)) := by sorry

/-- Specialization of Albert's classification to the endomorphism algebra of an elliptic curve:
`End⁰(E)` is `ℚ`, an imaginary quadratic field, or a definite quaternion algebra. -/
theorem endomorphism_algebra_classification_EC :
    @EndAlgClassification (EndomorphismAlgebra E)
      (EndomorphismAlgebra.instRing E) (EndomorphismAlgebra.instAlgebra E) := by
  haveI := EndomorphismAlgebra.instPDInvAlgebra E
  haveI := EndomorphismAlgebra.instNontrivial E
  exact endomorphism_algebra_classification (EndomorphismAlgebra E)

namespace EndomorphismRing

/-- The endomorphism ring of an elliptic curve is torsion-free as a `ℤ`-module. -/
theorem isTorsionFree :
    Module.IsTorsionFree ℤ (EndRing E) := by sorry

/-- The endomorphism ring of an elliptic curve is finitely generated as a `ℤ`-module. -/
theorem isFinite :
    Module.Finite ℤ (EndRing E) := by sorry

/-- A finitely generated torsion-free `ℤ`-module is free; in particular, `End(E)` is `ℤ`-free. -/
instance instFree : Module.Free ℤ (EndRing E) := by
  haveI := isTorsionFree E
  haveI := isFinite E
  obtain ⟨n, s, hs⟩ := Module.Finite.exists_fin (R := ℤ) (M := EndRing E)
  exact Module.free_of_finite_type_torsion_free hs

/-- The `ℤ`-rank of `End(E)` is `1`, `2`, or `4`, matching the three Albert cases. -/
theorem finrank_mem :
    Module.finrank ℤ (EndRing E) ∈ ({1, 2, 4} : Set ℕ) := by sorry

/-- Combined freeness and rank statement for `End(E)`: it is a free `ℤ`-module of rank `1`, `2`,
or `4`. -/
theorem free_rank :
    Module.Free ℤ (EndRing E) ∧
      Module.finrank ℤ (EndRing E) ∈ ({1, 2, 4} : Set ℕ) :=
  ⟨instFree E, finrank_mem E⟩

end EndomorphismRing

end WeierstrassCurve.Affine
