/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.GeometryOfManifolds.code.SymplecticManifolds

set_option autoImplicit false

open DifferentialFormSpace


/-- For any vector field $X$ and 2-form $\alpha$, the double contraction vanishes:
$\iota_X \iota_X \alpha = 0$. -/
theorem ι_squared_zero_on_2forms
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (X : VF) (α : Ω 2) :
    inst.ι X (inst.ι X α) = (0 : Ω 0) :=
  inst.ι_squared X α

/-- Skew-symmetry of iterated contractions on a 2-form:
$\iota_Y \iota_X \alpha = -\iota_X \iota_Y \alpha$. -/
theorem ι_ι_skew_2form
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (X Y : VF) (α : Ω 2) :
    inst.ι Y (inst.ι X α) = -(inst.ι X (inst.ι Y α)) :=
  inst.ι_ι_anticomm Y X α


/-- A **Hamiltonian vector field** for $H$ on a symplectic manifold $(M, \omega)$: a vector field
$X$ satisfying the defining equation $\iota_X \omega = dH$. -/
structure HamiltonianVectorField
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (H : Ω 0) where
  X : VF
  defining_eq : inst.ι X S.ω = inst.d H

/-- Symplectic manifolds in which every smooth function $H : M \to \mathbb{R}$ admits a Hamiltonian
vector field $X_H$. -/
class HasHamiltonianVF
    (Ω : ℕ → Type*) (VF : Type*)
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF) where
  hamiltonianVF : (H : Ω 0) → HamiltonianVectorField S H


/-- A Hamiltonian vector field preserves the symplectic form: $\mathcal{L}_{X_H} \omega = 0$. By
Cartan's magic formula $\mathcal{L}_{X_H}\omega = \iota_{X_H} d\omega + d(\iota_{X_H}\omega)
= 0 + d(dH) = 0$. -/
theorem lie_deriv_hamiltonian_eq_zero
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (H : Ω 0) (hv : HamiltonianVectorField S H) :
    inst.L hv.X S.ω = (0 : Ω 2) := by

  rw [cartan_formula hv.X S.ω]

  rw [hv.defining_eq, inst.d_squared]

  rw [S.closed, ι_zero_val]

  rw [add_zero]

/-- The flow (isotopy) $\rho_t$ generated by a Hamiltonian vector field $X_H$, encoded as a
one-parameter family of pullback morphisms together with the defining ODE
$\tfrac{d}{dt}(\rho_t^*\alpha) = \rho_t^*(\mathcal{L}_{X_H}\alpha)$, the initial condition
$\rho_0 = \mathrm{id}$, the constancy principle for forms with zero derivative, and inverse
relations $\rho_{-t} \circ \rho_t = \mathrm{id}$. -/
structure HamiltonianFlow
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (H : Ω 0)
    (hv : HamiltonianVectorField S H) where
  ρ_t : ℝ → DFSMorphism Ω VF Ω VF
  ρ_zero : ∀ {p : ℕ} (α : Ω p), (ρ_t 0).pullback α = α
  pullback_deriv : ∀ (t : ℝ) {p : ℕ}, Ω p → Ω p
  flow_ode : ∀ (t : ℝ) {p : ℕ} (α : Ω p),
    pullback_deriv t α = (ρ_t t).pullback (inst.L hv.X α)
  deriv_zero_const : ∀ {p : ℕ} (α : Ω p),
    (∀ t, pullback_deriv t α = 0) → ∀ t, (ρ_t t).pullback α = α
  flow_inv : ∀ (t : ℝ) {p : ℕ} (α : Ω p),
    (ρ_t (-t)).pullback ((ρ_t t).pullback α) = α
  flow_inv' : ∀ (t : ℝ) {p : ℕ} (α : Ω p),
    (ρ_t t).pullback ((ρ_t (-t)).pullback α) = α

/-- General invariance principle: if $\mathcal{L}_{X_H}\alpha = 0$ then the Hamiltonian flow leaves
$\alpha$ invariant: $\rho_t^* \alpha = \alpha$ for all $t$. -/
theorem HamiltonianFlow.preserves_lie_zero
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    {H : Ω 0} {hv : HamiltonianVectorField S H}
    (flow : HamiltonianFlow S H hv)
    (t : ℝ) {p : ℕ} (α : Ω p)
    (hL : inst.L hv.X α = 0) :
    (flow.ρ_t t).pullback α = α := by
  apply flow.deriv_zero_const α _ t
  intro s
  rw [flow.flow_ode s α, hL]

  have := (flow.ρ_t s).pullback_smul (0 : ℝ) (0 : Ω p)
  simp only [zero_smul] at this
  exact this

/-- **Proposition 3** (method form): the Hamiltonian flow preserves the symplectic form,
$\rho_t^* \omega = \omega$ for all $t$. -/
theorem HamiltonianFlow.preserves_symplectic_form
    {Ω : ℕ → Type*} {VF : Type*}
    [DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    {H : Ω 0} {hv : HamiltonianVectorField S H}
    (flow : HamiltonianFlow S H hv)
    (t : ℝ) :
    (flow.ρ_t t).pullback S.ω = S.ω :=
  flow.preserves_lie_zero t S.ω (lie_deriv_hamiltonian_eq_zero S H hv)

/-- **Proposition 3** (standalone form): for $H : M \to \mathbb{R}$ smooth with Hamiltonian vector
field $X_H$, every time-$t$ map of the generated isotopy $\rho_t$ is a symplectomorphism:
$\rho_t^* \omega = \omega$. -/
theorem hamiltonian_flow_preserves_symplectic_form
    {Ω : ℕ → Type*} {VF : Type*}
    [DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (H : Ω 0) (hv : HamiltonianVectorField S H)
    (flow : HamiltonianFlow S H hv)
    (t : ℝ) :
    (flow.ρ_t t).pullback S.ω = S.ω :=
  flow.preserves_symplectic_form t

/-- Promote a time-$t$ map of a Hamiltonian flow to a symplectomorphism of $(M, \omega)$, using
$\rho_{-t}$ as the inverse. -/
def HamiltonianFlow.toSymplectomorphism
    {Ω : ℕ → Type*} {VF : Type*}
    [DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    {H : Ω 0} {hv : HamiltonianVectorField S H}
    (flow : HamiltonianFlow S H hv)
    (t : ℝ) :
    Symplectomorphism S S where
  toMorphism := flow.ρ_t t
  invMorphism := flow.ρ_t (-t)
  left_inv := flow.flow_inv t
  right_inv := flow.flow_inv' t
  pullback_symplectic := flow.preserves_symplectic_form t


/-- **Definition 1** (symplectic part): a vector field $X$ is **symplectic** if
$\mathcal{L}_X \omega = 0$, equivalently $\iota_X \omega$ is closed. -/
def IsSymplecticVectorField
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (X : VF) : Prop :=
  inst.L X S.ω = 0

/-- **Definition 1** (Hamiltonian part): a vector field $X$ is **Hamiltonian** if
$\iota_X \omega$ is exact, i.e. there exists $H \in C^\infty(M)$ with $\iota_X \omega = dH$. -/
def IsHamiltonianVectorField
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (X : VF) : Prop :=
  ∃ (H : Ω 0), inst.ι X S.ω = inst.d H

/-- Equivalent characterisation of symplectic vector fields: $X$ is symplectic iff
$\iota_X \omega$ is a closed 1-form. This follows from Cartan's formula together with
$d\omega = 0$. -/
theorem isSymplecticVF_iff_ιXω_closed
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (X : VF) :
    IsSymplecticVectorField S X ↔ IsClosed' VF (inst.ι X S.ω) := by
  unfold IsSymplecticVectorField IsClosed'
  constructor
  ·
    intro h

    have hcartan := cartan_formula X S.ω
    rw [S.closed, ι_zero_val, add_zero] at hcartan

    rw [← hcartan]; exact h
  ·
    intro h
    rw [cartan_formula X S.ω, S.closed, ι_zero_val, add_zero]
    exact h

/-- The underlying vector field of any `HamiltonianVectorField` structure satisfies the
predicate `IsHamiltonianVectorField`. -/
theorem hamiltonianVF_isHamiltonianVF
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (H : Ω 0) (hv : HamiltonianVectorField S H) :
    IsHamiltonianVectorField S hv.X :=
  ⟨H, hv.defining_eq⟩


/-- The **Poisson bracket** $\{F, G\} := \omega(X_F, X_G) = \iota_{X_G}\iota_{X_F}\omega$ of two
smooth functions $F, G$ with chosen Hamiltonian vector fields. -/
def poissonBracket
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    {F G : Ω 0}
    (hvF : HamiltonianVectorField S F)
    (hvG : HamiltonianVectorField S G) :
    Ω 0 :=
  inst.ι hvG.X (inst.ι hvF.X S.ω)

/-- The Poisson bracket equals minus the Lie derivative of one Hamiltonian along the other:
$\{F, G\} = -\mathcal{L}_{X_F} G$. -/
theorem poissonBracket_eq_neg_lie_deriv
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    {F G : Ω 0}
    (hvF : HamiltonianVectorField S F)
    (hvG : HamiltonianVectorField S G) :
    poissonBracket S hvF hvG = -(inst.L hvF.X G) := by
  show inst.ι hvG.X (inst.ι hvF.X S.ω) = -(inst.L hvF.X G)
  rw [ι_ι_skew_2form hvF.X hvG.X S.ω, hvG.defining_eq]
  rw [inst.L_zero_eq_ι_d hvF.X G]


/-- Interface providing a **Lie bracket** $[X, Y]$ of vector fields characterised by the
identity $\iota_{[X, Y]} \alpha = \mathcal{L}_X (\iota_Y \alpha) - \iota_Y (\mathcal{L}_X \alpha)$
for every form $\alpha$ of positive degree. -/
class HasLieBracket (Ω : ℕ → Type*) (VF : Type*) [inst : DifferentialFormSpace Ω VF] where
  bracket : VF → VF → VF
  bracket_ι_eq : ∀ (X Y : VF) {p : ℕ} (α : Ω (p + 1)),
    inst.ι (bracket X Y) α = inst.L X (inst.ι Y α) - inst.ι Y (inst.L X α)

/-- Restatement of the defining identity for the Lie bracket:
$\iota_{[X, Y]} \alpha = \mathcal{L}_X (\iota_Y \alpha) - \iota_Y (\mathcal{L}_X \alpha)$. -/
theorem lie_bracket_ι_eq
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    [hbr : HasLieBracket Ω VF]
    (X Y : VF) {p : ℕ} (α : Ω (p + 1)) :
    inst.ι (hbr.bracket X Y) α = inst.L X (inst.ι Y α) - inst.ι Y (inst.L X α) :=
  hbr.bracket_ι_eq X Y α

/-- Compatibility of the Lie bracket with Lie derivatives on forms:
$\mathcal{L}_{[X, Y]} \alpha = \mathcal{L}_X (\mathcal{L}_Y \alpha) - \mathcal{L}_Y (\mathcal{L}_X \alpha)$
for every form $\alpha$ of arbitrary degree. -/
theorem L_bracket_eq
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    [hbr : HasLieBracket Ω VF]
    (X Y : VF) {p : ℕ} (α : Ω p) :
    inst.L (hbr.bracket X Y) α = inst.L X (inst.L Y α) - inst.L Y (inst.L X α) := by
  induction p with
  | zero =>


    rw [inst.L_zero_eq_ι_d (hbr.bracket X Y) α]
    rw [lie_bracket_ι_eq X Y (inst.d α)]
    rw [← inst.L_zero_eq_ι_d Y α]
    rw [inst.L_comm_d X α]
    rw [← inst.L_zero_eq_ι_d Y (inst.L X α)]
  | succ n ih =>


    have L_neg : ∀ (Z : VF) {q : ℕ} (β : Ω q), inst.L Z (-β) = -(inst.L Z β) := by
      intro Z q β
      have h := inst.L_smul Z (-1 : ℝ) β
      simp at h; exact h
    have L_sub : ∀ (Z : VF) {q : ℕ} (a b : Ω q),
        inst.L Z (a - b) = inst.L Z a - inst.L Z b := by
      intro Z q a b
      rw [sub_eq_add_neg, inst.L_add, L_neg, ← sub_eq_add_neg]

    have fMul_sub_left : ∀ {q : ℕ} (a b : Ω 0) (c : Ω q),
        inst.fMul (a - b) c = inst.fMul a c - inst.fMul b c := by
      intro q a b c
      rw [sub_eq_add_neg, inst.fMul_add_left, sub_eq_add_neg]
      congr 1
      have h := inst.fMul_smul (-1 : ℝ) b c
      simp at h; exact h
    have d_sub : ∀ {q : ℕ} (a b : Ω q),
        inst.d (a - b) = inst.d a - inst.d b := by
      intro q a b
      rw [sub_eq_add_neg, inst.d_add, sub_eq_add_neg]
      congr 1
      have h := inst.d_smul (-1 : ℝ) b
      simp at h; exact h
    have fMul_sub_right : ∀ {q : ℕ} (g : Ω 0) (a b : Ω q),
        inst.fMul g (a - b) = inst.fMul g a - inst.fMul g b := by
      intro q g a b
      rw [sub_eq_add_neg, inst.fMul_add_right, sub_eq_add_neg]
      congr 1


      have h1 : inst.fMul g (b + (-b)) = inst.fMul g b + inst.fMul g (-b) :=
        inst.fMul_add_right g b (-b)
      rw [add_neg_cancel, DifferentialFormSpace.fMul_zero] at h1
      exact eq_neg_of_add_eq_zero_right h1.symm


    have key : inst.L (hbr.bracket X Y) α - inst.L X (inst.L Y α) +
        inst.L Y (inst.L X α) = 0 := by
      apply inst.ext_fdα
        (fun β => inst.L (hbr.bracket X Y) β - inst.L X (inst.L Y β) +
          inst.L Y (inst.L X β))
      ·
        intro a b
        simp only [inst.L_add]
        abel
      ·
        intro r a
        simp only [inst.L_smul]
        simp [smul_sub, smul_add]

      ·
        intro f γ

        have ih_f : inst.L (hbr.bracket X Y) f =
            inst.L X (inst.L Y f) - inst.L Y (inst.L X f) := by
          rw [inst.L_zero_eq_ι_d (hbr.bracket X Y) f]
          rw [lie_bracket_ι_eq X Y (inst.d f)]
          rw [← inst.L_zero_eq_ι_d Y f]
          rw [inst.L_comm_d X f]
          rw [← inst.L_zero_eq_ι_d Y (inst.L X f)]

        have ih_γ : inst.L (hbr.bracket X Y) γ =
            inst.L X (inst.L Y γ) - inst.L Y (inst.L X γ) := ih γ

        have e1 : inst.L (hbr.bracket X Y) (inst.fMul f (inst.d γ)) =
            inst.fMul (inst.L (hbr.bracket X Y) f) (inst.d γ) +
            inst.fMul f (inst.d (inst.L (hbr.bracket X Y) γ)) := by
          rw [inst.L_fMul, inst.L_comm_d]
        have e2 : inst.L X (inst.L Y (inst.fMul f (inst.d γ))) =
            inst.L X (inst.fMul (inst.L Y f) (inst.d γ) +
              inst.fMul f (inst.d (inst.L Y γ))) := by
          rw [inst.L_fMul Y, inst.L_comm_d Y]
        have e3 : inst.L Y (inst.L X (inst.fMul f (inst.d γ))) =
            inst.L Y (inst.fMul (inst.L X f) (inst.d γ) +
              inst.fMul f (inst.d (inst.L X γ))) := by
          rw [inst.L_fMul X, inst.L_comm_d X]
        rw [e1, e2, e3]

        rw [inst.L_add X (inst.fMul (inst.L Y f) (inst.d γ))
          (inst.fMul f (inst.d (inst.L Y γ)))]
        rw [inst.L_add Y (inst.fMul (inst.L X f) (inst.d γ))
          (inst.fMul f (inst.d (inst.L X γ)))]

        rw [inst.L_fMul X (inst.L Y f) (inst.d γ)]
        rw [inst.L_fMul X f (inst.d (inst.L Y γ))]
        rw [inst.L_fMul Y (inst.L X f) (inst.d γ)]
        rw [inst.L_fMul Y f (inst.d (inst.L X γ))]

        rw [inst.L_comm_d X γ, inst.L_comm_d Y γ]
        rw [inst.L_comm_d X (inst.L Y γ), inst.L_comm_d Y (inst.L X γ)]

        rw [ih_f, ih_γ]

        rw [fMul_sub_left, d_sub, fMul_sub_right]

        abel


    have goal : inst.L (hbr.bracket X Y) α =
        inst.L (hbr.bracket X Y) α - inst.L X (inst.L Y α) +
        inst.L Y (inst.L X α) +
        (inst.L X (inst.L Y α) - inst.L Y (inst.L X α)) := by abel
    rw [key, zero_add] at goal
    exact goal

/-- Non-degeneracy of contraction for 1-forms: if $\iota_X \alpha = 0$ for every vector field $X$,
then $\alpha = 0$. -/
theorem ι_one_form_nondegenerate
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (α : Ω 1) (h : ∀ (X : VF), inst.ι X α = (0 : Ω 0)) :
    α = 0 :=
  inst.ι_one_form_nondegenerate α h

/-- For Hamiltonian vector fields $X_F$ and $X_G$, the bracket $[X_F, X_G]$ is itself Hamiltonian
with Hamiltonian $\mathcal{L}_{X_F} G = \{F, G\}$ (up to sign): explicitly,
$\iota_{[X_F, X_G]} \omega = d(\mathcal{L}_{X_F} G)$. -/
theorem lie_bracket_hamiltonian_eq
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    [hbr : HasLieBracket Ω VF]
    (S : SymplecticManifold Ω VF)
    {F G : Ω 0}
    (hvF : HamiltonianVectorField S F)
    (hvG : HamiltonianVectorField S G) :
    inst.ι (hbr.bracket hvF.X hvG.X) S.ω =
      inst.d (inst.L hvF.X G) := by

  rw [lie_bracket_ι_eq hvF.X hvG.X S.ω]

  rw [hvG.defining_eq]

  rw [lie_deriv_hamiltonian_eq_zero S F hvF]

  rw [inst.L_comm_d hvF.X G]

  rw [ι_zero_val, sub_zero]


/-- A **symplectic isotopy** of $(M, \omega)$: a one-parameter family $\varphi_t$ of pullback
morphisms starting at the identity, generated by a time-dependent symplectic vector field $X_t$
(i.e. $\mathcal{L}_{X_t} \omega = 0$), and preserving $\omega$ at each time. -/
structure SymplecticIsotopy
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF) where
  φ_t : ℝ → DFSMorphism Ω VF Ω VF
  X_t : ℝ → VF
  symplectic : ∀ t, IsSymplecticVectorField S (X_t t)
  φ_zero : ∀ {p : ℕ} (α : Ω p), (φ_t 0).pullback α = α
  preserves_ω : ∀ t, (φ_t t).pullback S.ω = S.ω


/-- The flow generated by a **time-dependent Hamiltonian** $H_t : M \to \mathbb{R}$ with chosen
Hamiltonian vector fields $X_{H_t}$: the analogue of `HamiltonianFlow` with $H$ and $X_H$ allowed
to vary smoothly in $t$. -/
structure TimeDependentHamiltonianFlow
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF) where
  H_t : ℝ → Ω 0
  hv_t : (t : ℝ) → HamiltonianVectorField S (H_t t)
  φ_t : ℝ → DFSMorphism Ω VF Ω VF
  φ_zero : ∀ {p : ℕ} (α : Ω p), (φ_t 0).pullback α = α
  pullback_deriv : ∀ (t : ℝ) {p : ℕ}, Ω p → Ω p
  flow_ode : ∀ (t : ℝ) {p : ℕ} (α : Ω p),
    pullback_deriv t α = (φ_t t).pullback (inst.L (hv_t t).X α)
  deriv_zero_const : ∀ {p : ℕ} (α : Ω p),
    (∀ t, pullback_deriv t α = 0) → ∀ t, (φ_t t).pullback α = α

/-- General invariance principle for time-dependent Hamiltonian flows: if
$\mathcal{L}_{X_{H_s}}\alpha = 0$ for all $s$, then $\varphi_t^*\alpha = \alpha$ for all $t$. -/
theorem TimeDependentHamiltonianFlow.preserves_lie_zero
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    (flow : TimeDependentHamiltonianFlow S)
    (t : ℝ) {p : ℕ} (α : Ω p)
    (hL : ∀ s, inst.L (flow.hv_t s).X α = 0) :
    (flow.φ_t t).pullback α = α := by
  apply flow.deriv_zero_const α _ t
  intro s
  rw [flow.flow_ode s α, hL s]
  have := (flow.φ_t s).pullback_smul (0 : ℝ) (0 : Ω p)
  simp only [zero_smul] at this
  exact this

/-- Time-dependent version of Proposition 3: a flow generated by a time-dependent Hamiltonian
preserves the symplectic form, $\varphi_t^* \omega = \omega$. -/
theorem TimeDependentHamiltonianFlow.preserves_symplectic_form
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    (flow : TimeDependentHamiltonianFlow S)
    (t : ℝ) :
    (flow.φ_t t).pullback S.ω = S.ω :=
  flow.preserves_lie_zero t S.ω
    (fun s => lie_deriv_hamiltonian_eq_zero S (flow.H_t s) (flow.hv_t s))

/-- A time-dependent Hamiltonian flow is automatically a symplectic isotopy, with generating
vector field $X_t := X_{H_t}$. -/
def SymplecticIsotopy.ofHamiltonian
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    (flow : TimeDependentHamiltonianFlow S) :
    SymplecticIsotopy S where
  φ_t := flow.φ_t
  X_t := fun t => (flow.hv_t t).X
  symplectic := fun t => lie_deriv_hamiltonian_eq_zero S (flow.H_t t) (flow.hv_t t)
  φ_zero := flow.φ_zero
  preserves_ω := flow.preserves_symplectic_form


/-- **Flux data** of a symplectic isotopy $\varphi_t$: a closed 1-form $\sigma$ representing the
class $[\iota_{X_t}\omega] \in H^1(M; \mathbb{R})$ uniformly in $t$, i.e. each
$\sigma - \iota_{X_t}\omega$ is exact. The flux of $\varphi$ is the cohomology class
$[\sigma]$. -/
structure FluxData
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    (S : SymplecticManifold Ω VF)
    (iso : SymplecticIsotopy S) where
  representative : Ω 1
  is_closed : inst.d representative = 0
  cohomologous_to_ιXω : ∀ t, IsExact' VF (representative - inst.ι (iso.X_t t) S.ω)


/-- A symplectic isotopy $\varphi_t$ is **Hamiltonian** if its generating vector field $X_t$ is a
Hamiltonian vector field for every $t$. -/
def SymplecticIsotopy.IsHamiltonian
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    (iso : SymplecticIsotopy S) : Prop :=
  ∀ t, IsHamiltonianVectorField S (iso.X_t t)

/-- The symplectic isotopy associated to a time-dependent Hamiltonian flow is Hamiltonian. -/
theorem SymplecticIsotopy.ofHamiltonian_isHamiltonian
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {S : SymplecticManifold Ω VF}
    (flow : TimeDependentHamiltonianFlow S) :
    (SymplecticIsotopy.ofHamiltonian flow).IsHamiltonian := by
  intro t
  exact hamiltonianVF_isHamiltonianVF S (flow.H_t t) (flow.hv_t t)


/-- The sum of two exact forms is exact: $d a + d b = d(a + b)$. -/
lemma exact_add
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {p : ℕ} (α β : Ω (p + 1))
    (hα : IsExact' VF α) (hβ : IsExact' VF β) :
    IsExact' VF (α + β) := by
  obtain ⟨a, ha⟩ := hα
  obtain ⟨b, hb⟩ := hβ
  exact ⟨a + b, by rw [ha, hb, inst.d_add]⟩

/-- The negation of an exact form is exact: if $\alpha = da$ then $-\alpha = d(-a)$. -/
lemma exact_neg
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {p : ℕ} (α : Ω (p + 1))
    (hα : IsExact' VF α) :
    IsExact' VF (-α) := by
  obtain ⟨a, ha⟩ := hα
  exact ⟨-a, by rw [ha, d_neg]⟩

/-- The difference of two exact forms is exact. -/
lemma exact_sub
    {Ω : ℕ → Type*} {VF : Type*}
    [inst : DifferentialFormSpace Ω VF]
    {p : ℕ} (α β : Ω (p + 1))
    (hα : IsExact' VF α) (hβ : IsExact' VF β) :
    IsExact' VF (α - β) := by
  rw [sub_eq_add_neg]
  exact exact_add α (-β) hα (exact_neg β hβ)
