/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Computability.ContextFreeGrammar
import Mathlib.Computability.Language
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Pigeonhole
import Mathlib.Data.Set.Finite.Lattice

namespace ContextFree

/-- A Context Free Grammar (CFG) over the terminal alphabet `T`.

In Sipser's notation, a CFG is a 4-tuple `G = (V, Σ, R, S)` where `V` is a finite
set of variables (nonterminals), `Σ = T` is the set of terminal symbols, `R` is a
finite set of production rules of the form `V → (V ∪ Σ)*`, and `S ∈ V` is the
start variable. -/
abbrev CFG (T : Type*) := ContextFreeGrammar T

/-- A production rule of a CFG: an element of the form `A → α` where `A ∈ V` is a
nonterminal and `α ∈ (V ∪ Σ)*` is a sentential form. -/
abbrev Rule (T N : Type*) := ContextFreeRule T N

variable {T : Type*}

/-- A grammar symbol: either a terminal `t ∈ T` or a nonterminal `A ∈ N`. -/
abbrev Sym (T N : Type*) := Symbol T N

/-- A sentential form is a finite string over the combined alphabet of terminals
and nonterminals, i.e. an element of `(V ∪ Σ)*`. -/
abbrev SententialForm (T : Type*) (N : Type*) := List (Symbol T N)

/-- One-step derivation `u ⇒ v`: `v` is obtained from `u` by applying a single
production rule of `g` at one position. -/
abbrev Produces (g : CFG T) := g.Produces

/-- Multi-step derivation `u ⇒* v`: the reflexive transitive closure of
`Produces g`, i.e. `v` is obtained from `u` by zero or more rule applications. -/
abbrev Derives (g : CFG T) := g.Derives

/-- `g.Generates w` means the start symbol `S` derives the sentential form `w`,
i.e. `S ⇒* w` (where `w` is a list of symbols, not yet restricted to terminals). -/
abbrev Generates (g : CFG T) := g.Generates

/-- The language generated by the grammar `g`:
`L(G) = { w ∈ Σ* | S ⇒* w }`. -/
abbrev language (g : CFG T) := g.language

/-- A language `L ⊆ T*` is a *context free language* (CFL) if there exists a CFG
`G` with `L = L(G)`. -/
abbrev IsContextFree (L : Language T) := Language.IsContextFree L

end ContextFree

namespace ChomskyNormalForm

variable {T : Type*}

/-- A rule `r : A → α` is in *Chomsky Normal Form* if its right-hand side has one
of the following forms:
* `A → BC` where `B, C` are nonterminals distinct from the start variable, or
* `A → a` where `a` is a single terminal symbol, or
* `S → ε` where `S` is the start variable (the only allowed ε-production). -/
def IsCNFRule {N : Type*} (r : ContextFreeRule T N) (startVar : N) : Prop :=
  (∃ B C : N, B ≠ startVar ∧ C ≠ startVar ∧
    r.output = [Symbol.nonterminal B, Symbol.nonterminal C]) ∨
  (∃ a : T, r.output = [Symbol.terminal a]) ∨
  (r.input = startVar ∧ r.output = [])

/-- A grammar `g` is in Chomsky Normal Form iff every one of its rules is. -/
def IsCNF (g : ContextFreeGrammar T) : Prop :=
  ∀ r ∈ g.rules, IsCNFRule r g.initial

/-- **Lemma 1 (Sipser, Lecture 7):** Every context free grammar can be converted
into an equivalent grammar in Chomsky Normal Form (i.e. one generating the same
language). -/
theorem cfg_to_cnf (g : ContextFreeGrammar T) :
    ∃ g' : ContextFreeGrammar T, IsCNF g' ∧ g'.language = g.language := by sorry

/-- Refinement of `cfg_to_cnf` producing an equivalent CNF grammar whose
nonterminal type is additionally a `Fintype` with decidable equality. This finite
witness is needed for the pumping-length argument, which counts nonterminals. -/
theorem cfg_to_cnf_fintype (g : ContextFreeGrammar T) :
    ∃ (g' : ContextFreeGrammar T) (_ : Fintype g'.NT) (_ : DecidableEq g'.NT),
      IsCNF g' ∧ g'.language = g.language := by
  classical

  obtain ⟨g₁, hcnf₁, hlang₁⟩ := cfg_to_cnf g

  let activeSet : Set g₁.NT :=
    {g₁.initial} ∪
    ⋃ r ∈ (g₁.rules : Set (ContextFreeRule T g₁.NT)),
      ({r.input} : Set g₁.NT) ∪ {n : g₁.NT | Symbol.nonterminal n ∈ r.output}
  have hfin_active : activeSet.Finite := by
    apply Set.Finite.union (Set.finite_singleton _)
    apply Set.Finite.biUnion g₁.rules.finite_toSet
    intro r _
    apply Set.Finite.union (Set.finite_singleton _)
    apply Set.Finite.subset (Set.finite_range (fun i : Fin r.output.length =>
      match r.output.get i with
      | Symbol.nonterminal n => n
      | Symbol.terminal _ => g₁.initial))
    intro n hn
    simp only [Set.mem_setOf_eq] at hn
    rw [Set.mem_range]
    obtain ⟨i, hi⟩ := List.mem_iff_get.mp hn
    exact ⟨i, by rw [show r.output.get i = Symbol.nonterminal n from hi]⟩

  have hinitial_mem : g₁.initial ∈ activeSet :=
    Set.mem_union_left _ (Set.mem_singleton _)
  have hrule_input_mem : ∀ r ∈ g₁.rules, r.input ∈ activeSet := fun r hr =>
    Set.mem_union_right _ (Set.mem_biUnion hr (Set.mem_union_left _ (Set.mem_singleton _)))
  have hrule_output_mem : ∀ r ∈ g₁.rules, ∀ n : g₁.NT,
      Symbol.nonterminal n ∈ r.output → n ∈ activeSet := fun r hr n hn =>
    Set.mem_union_right _ (Set.mem_biUnion hr (Set.mem_union_right _ hn))

  haveI : Fintype activeSet := hfin_active.fintype

  let mapSym : Symbol T g₁.NT → Symbol T activeSet := fun s =>
    match s with
    | Symbol.terminal t => Symbol.terminal t
    | Symbol.nonterminal n =>
      if h : n ∈ activeSet then Symbol.nonterminal ⟨n, h⟩
      else Symbol.nonterminal ⟨g₁.initial, hinitial_mem⟩
  let unmapSym : Symbol T activeSet → Symbol T g₁.NT := fun s =>
    match s with
    | Symbol.terminal t => Symbol.terminal t
    | Symbol.nonterminal ⟨n, _⟩ => Symbol.nonterminal n

  have hmap_unmap : ∀ s : Symbol T activeSet, mapSym (unmapSym s) = s := by
    intro s; cases s with
    | terminal t => simp [mapSym, unmapSym]
    | nonterminal n =>
      simp only [unmapSym, mapSym]
      rw [dif_pos n.property]
  have hunmap_map_active : ∀ (s : Symbol T g₁.NT),
      (∀ n, s = Symbol.nonterminal n → n ∈ activeSet) →
      unmapSym (mapSym s) = s := by
    intro s hs; cases s with
    | terminal t => simp [mapSym, unmapSym]
    | nonterminal n =>
      simp only [mapSym, unmapSym]
      rw [dif_pos (hs n rfl)]

  let mapRule (r : ContextFreeRule T g₁.NT) (hr : r ∈ g₁.rules) :
      ContextFreeRule T activeSet :=
    { input := ⟨r.input, hrule_input_mem r hr⟩
      output := r.output.map mapSym }

  let g₂ : ContextFreeGrammar T :=
    { NT := activeSet
      initial := ⟨g₁.initial, hinitial_mem⟩
      rules := g₁.rules.attach.image fun ⟨r, hr⟩ => mapRule r hr }

  have hfintype : Fintype g₂.NT := inferInstance
  have hdec : DecidableEq g₂.NT := Subtype.instDecidableEq

  have hcnf₂ : IsCNF g₂ := by
    intro r' hr'
    simp only [g₂, Finset.mem_image, Finset.mem_attach, true_and, Subtype.exists] at hr'
    obtain ⟨r, hr, rfl⟩ := hr'
    have hcnf_r := hcnf₁ r hr

    show IsCNFRule (mapRule r hr) ⟨g₁.initial, hinitial_mem⟩
    unfold IsCNFRule at hcnf_r ⊢
    rcases hcnf_r with ⟨B, C, hB, hC, hout⟩ | ⟨a, hout⟩ | ⟨hinp, hout⟩
    ·
      left
      have hBmem : B ∈ activeSet := hrule_output_mem r hr B (by rw [hout]; simp)
      have hCmem : C ∈ activeSet := hrule_output_mem r hr C (by rw [hout]; simp)
      refine ⟨⟨B, hBmem⟩, ⟨C, hCmem⟩, ?_, ?_, ?_⟩
      · intro heq; apply hB; exact congr_arg Subtype.val heq
      · intro heq; apply hC; exact congr_arg Subtype.val heq
      · simp only [mapRule, hout, List.map, mapSym, dif_pos hBmem, dif_pos hCmem]
    ·
      right; left
      exact ⟨a, by simp only [mapRule, hout, List.map, mapSym]⟩
    ·
      right; right
      exact ⟨Subtype.ext hinp, by simp only [mapRule, hout, List.map]⟩

  have hlang₂ : g₂.language = g₁.language := by
    ext w
    simp only [ContextFreeGrammar.mem_language_iff]
    constructor
    ·
      intro hderiv

      suffices h : ∀ (u v : List (Symbol T g₂.NT)),
          g₂.Derives u v →
          g₁.Derives (u.map unmapSym) (v.map unmapSym) by
        have := h _ _ hderiv
        simp only [g₂, List.map, unmapSym] at this
        convert this using 1 <;> simp [List.map_map, Function.comp]
      intro u v hd
      induction hd with
      | refl => exact Relation.ReflTransGen.refl
      | tail _ hlast ih =>
        apply ih.trans
        obtain ⟨r', hr'mem, hrw⟩ := hlast
        simp only [g₂, Finset.mem_image, Finset.mem_attach, true_and, Subtype.exists] at hr'mem
        obtain ⟨r, hr, rfl⟩ := hr'mem
        obtain ⟨p, q, hu, hv⟩ := ContextFreeRule.Rewrites.exists_parts hrw
        rw [hu, hv]
        simp only [List.map_append, List.map]
        apply Relation.ReflTransGen.single
        refine ⟨r, hr, ?_⟩
        simp only [mapRule, unmapSym] at *


        have hmap_output : (r.output.map mapSym).map unmapSym = r.output := by
          rw [List.map_map]
          conv_rhs => rw [← List.map_id r.output]
          exact List.map_congr_left (fun s hs =>
            hunmap_map_active s (fun n heq => by
              subst heq; exact hrule_output_mem r hr n hs))
        rw [hmap_output]
        exact ContextFreeRule.rewrites_of_exists_parts r _ _
    ·
      intro hderiv

      have active_preserved : ∀ (u v : List (Symbol T g₁.NT)),
          g₁.Produces u v →
          (∀ s ∈ u, ∀ n, s = Symbol.nonterminal n → n ∈ activeSet) →
          (∀ s ∈ v, ∀ n, s = Symbol.nonterminal n → n ∈ activeSet) := by
        intro u v ⟨r, hrmem, hrw⟩ hu_act s hs n heq
        subst heq
        obtain ⟨p, q, hu_eq, hv_eq⟩ := ContextFreeRule.Rewrites.exists_parts hrw
        rw [hv_eq] at hs
        have hmem := List.mem_append.mp hs
        rcases hmem with hmem | hmem
        · have hmem2 := List.mem_append.mp hmem
          rcases hmem2 with hmem2 | hmem2
          · exact hu_act _ (by rw [hu_eq]; exact List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl hmem2)))) n rfl
          · exact hrule_output_mem r hrmem n hmem2
        · exact hu_act _ (by rw [hu_eq]; exact List.mem_append.mpr (Or.inr hmem)) n rfl

      have lift_step : ∀ (u v : List (Symbol T g₁.NT)),
          g₁.Produces u v →
          (∀ s ∈ u, ∀ n, s = Symbol.nonterminal n → n ∈ activeSet) →
          g₂.Produces (u.map mapSym) (v.map mapSym) := by
        intro u v ⟨r, hrmem, hrw⟩ _
        obtain ⟨p, q, hu_eq, hv_eq⟩ := ContextFreeRule.Rewrites.exists_parts hrw
        rw [hu_eq, hv_eq]
        simp only [List.map_append, List.map]
        have hinp_active := hrule_input_mem r hrmem
        have hmapinp : mapSym (Symbol.nonterminal r.input) =
            Symbol.nonterminal ⟨r.input, hinp_active⟩ := by
          simp [mapSym, dif_pos hinp_active]
        rw [hmapinp]
        refine ⟨mapRule r hrmem, ?_, ContextFreeRule.rewrites_of_exists_parts _ _ _⟩
        simp only [g₂, Finset.mem_image, Finset.mem_attach, true_and, Subtype.exists]
        exact ⟨r, hrmem, rfl⟩

      suffices h : ∀ (u v : List (Symbol T g₁.NT)),
          g₁.Derives u v →
          (∀ s ∈ u, ∀ n, s = Symbol.nonterminal n → n ∈ activeSet) →
          g₂.Derives (u.map mapSym) (v.map mapSym) by
        have := h _ _ hderiv (by
          intro s hs n heq; subst heq
          simp [List.mem_singleton] at hs; subst hs
          exact hinitial_mem)
        simp only [List.map, mapSym, dif_pos hinitial_mem] at this
        convert this using 1
        simp [List.map_map, Function.comp, mapSym]
      intro u v hd
      induction hd with
      | refl => intro _; exact Relation.ReflTransGen.refl
      | tail hab hbc ih =>
        intro hu_active

        have hg₂_derives := ih hu_active

        have derives_active_gen : ∀ (a b : List (Symbol T g₁.NT)),
            g₁.Derives a b →
            (∀ s ∈ a, ∀ n, s = Symbol.nonterminal n → n ∈ activeSet) →
            (∀ s ∈ b, ∀ n, s = Symbol.nonterminal n → n ∈ activeSet) := by
          intro a b hd'
          induction hd' with
          | refl => exact id
          | tail _ hlast' ih' => exact fun h => active_preserved _ _ hlast' (ih' h)
        have hb_active := derives_active_gen _ _ hab hu_active

        have hg₂_step := lift_step _ _ hbc hb_active
        exact hg₂_derives.trans (Relation.ReflTransGen.single hg₂_step)

  exact ⟨g₂, hfintype, hdec, hcnf₂, hlang₂.trans hlang₁⟩

/-- `DerivesIn g u w n` means `u ⇒* w` in exactly `n` derivation steps in `g`.
This is a counted refinement of `g.Derives` used to formalise step-counting
arguments such as Lemma 2 below. -/
inductive DerivesIn (g : ContextFreeGrammar T) :
    List (Symbol T g.NT) → List (Symbol T g.NT) → ℕ → Prop where
  | refl (u : List (Symbol T g.NT)) : DerivesIn g u u 0
  | step {u v w : List (Symbol T g.NT)} {n : ℕ} :
      g.Produces u v → DerivesIn g v w n → DerivesIn g u w (n + 1)

/-- Counts the number of nonterminal symbols occurring in a sentential form. -/
def ntCount {N : Type*} : List (Symbol T N) → ℕ
  | [] => 0
  | Symbol.nonterminal _ :: rest => 1 + ntCount rest
  | Symbol.terminal _ :: rest => ntCount rest

/-- Counts the number of terminal symbols occurring in a sentential form. -/
def tCount {N : Type*} : List (Symbol T N) → ℕ
  | [] => 0
  | Symbol.terminal _ :: rest => 1 + tCount rest
  | Symbol.nonterminal _ :: rest => tCount rest

/-- The nonterminal count is additive over list concatenation. -/
theorem ntCount_append {N : Type*} (l₁ l₂ : List (Symbol T N)) :
    ntCount (l₁ ++ l₂) = ntCount l₁ + ntCount l₂ := by
  induction l₁ with
  | nil => simp [ntCount]
  | cons s rest ih =>
    cases s with
    | terminal a => simp [ntCount, ih]
    | nonterminal A => simp [ntCount, ih]; omega

/-- The terminal count is additive over list concatenation. -/
theorem tCount_append {N : Type*} (l₁ l₂ : List (Symbol T N)) :
    tCount (l₁ ++ l₂) = tCount l₁ + tCount l₂ := by
  induction l₁ with
  | nil => simp [tCount]
  | cons s rest ih =>
    cases s with
    | terminal a => simp [tCount, ih]; omega
    | nonterminal A => simp [tCount, ih]

/-- A string consisting only of terminals (as in `w.map Symbol.terminal`) contains
no nonterminal symbols. -/
theorem ntCount_map_terminal {N : Type*} (w : List T) :
    ntCount (N := N) (w.map Symbol.terminal) = 0 := by
  induction w with
  | nil => simp [ntCount]
  | cons a rest ih => simp [ntCount, ih]

/-- A string of terminals contributes exactly `w.length` terminals to the
`tCount` measure. -/
theorem tCount_map_terminal {N : Type*} (w : List T) :
    tCount (N := N) (w.map Symbol.terminal) = w.length := by
  induction w with
  | nil => simp [tCount]
  | cons a rest ih => simp [tCount, ih]; omega

/-- In a CNF grammar, the start variable `S` never appears on the right-hand side
of any rule. This is forced by the definition of `IsCNFRule`, which requires the
two nonterminals in `A → BC` to differ from the start variable. -/
theorem cnf_start_not_in_output (g : ContextFreeGrammar T) (hcnf : IsCNF g)
    (r : ContextFreeRule T g.NT) (hr : r ∈ g.rules) :
    Symbol.nonterminal g.initial ∉ r.output := by
  have hcnf_r := hcnf r hr
  rcases hcnf_r with ⟨B, C, hB, hC, hout⟩ | ⟨a, hout⟩ | ⟨_, hout⟩
  · rw [hout]
    intro hmem
    simp only [List.mem_cons, List.mem_nil_iff, or_false, Symbol.nonterminal.injEq] at hmem
    rcases hmem with h | h
    · exact hB (Eq.symm h)
    · exact hC (Eq.symm h)
  · rw [hout]; simp
  · rw [hout]; simp

/-- "Absence of the start variable" is preserved by one-step derivations in a CNF
grammar: if `S ∉ sf` and `sf ⇒ v`, then `S ∉ v`. -/
theorem cnf_start_not_in_produces (g : ContextFreeGrammar T) (hcnf : IsCNF g)
    {sf v : List (Symbol T g.NT)}
    (hp : g.Produces sf v)
    (hsf : Symbol.nonterminal g.initial ∉ sf) :
    Symbol.nonterminal g.initial ∉ v := by
  obtain ⟨r, hr_mem, hrw⟩ := hp
  rw [ContextFreeRule.rewrites_iff] at hrw
  obtain ⟨p, q, hpq_in, hpq_out⟩ := hrw
  rw [hpq_out]
  intro hmem
  simp only [List.mem_append] at hmem
  rcases hmem with (h | h) | h
  · exact hsf (by rw [hpq_in]; simp [List.mem_append]; left; exact h)
  · exact cnf_start_not_in_output g hcnf r hr_mem h
  · exact hsf (by rw [hpq_in]; simp [List.mem_append]; right; right; exact h)

/-- *Potential function* for a single derivation step in a CNF grammar.
Defining `Φ(sf) := 2·tCount(sf) + ntCount(sf)`, one CNF production step (other
than the start ε-rule, which is forbidden once `S ∉ sf`) increases `Φ` by exactly
one. This is the key invariant behind Lemma 2 (`cnf_derivation_length`). -/
theorem cnf_produces_cost_step (g : ContextFreeGrammar T) (hcnf : IsCNF g)
    {sf v : List (Symbol T g.NT)}
    (hp : g.Produces sf v)
    (hsf : Symbol.nonterminal g.initial ∉ sf) :
    2 * tCount v + ntCount v = 2 * tCount sf + ntCount sf + 1 := by
  obtain ⟨r, hr_mem, hrw⟩ := hp
  rw [ContextFreeRule.rewrites_iff] at hrw
  obtain ⟨p, q, hpq_in, hpq_out⟩ := hrw
  have hcnf_r := hcnf r hr_mem
  rw [hpq_in, hpq_out]
  simp only [ntCount_append, tCount_append]


  rcases hcnf_r with ⟨B, C, _, _, hout⟩ | ⟨a, hout⟩ | ⟨hinp, hout⟩
  ·
    rw [hout]; simp [ntCount, tCount]; omega
  ·
    rw [hout]; simp [ntCount, tCount]; omega
  ·
    exfalso
    have : Symbol.nonterminal r.input ∈ sf := by
      rw [hpq_in]; simp [List.mem_append]
    rw [hinp] at this
    exact hsf this

/-- Iterating the per-step potential identity: after `n` CNF derivation steps
starting from a sentential form not containing `S`, the potential `Φ` has
increased by exactly `n`. -/
theorem cnf_derivesIn_cost (g : ContextFreeGrammar T) (hcnf : IsCNF g)
    {sf w : List (Symbol T g.NT)} {n : ℕ}
    (hd : DerivesIn g sf w n)
    (hsf : Symbol.nonterminal g.initial ∉ sf) :
    2 * tCount w + ntCount w = 2 * tCount sf + ntCount sf + n := by
  induction hd with
  | refl _ => omega
  | step hp hd' ih =>
    have hsf' := cnf_start_not_in_produces g hcnf hp hsf
    have hih := ih hsf'
    have hcost := cnf_produces_cost_step g hcnf hp hsf
    omega

/-- **Lemma 2 (Sipser, Lecture 7):** If `H` is in Chomsky Normal Form and
`w ∈ L(H)` is nonempty, then every derivation of `w` from the start symbol has
exactly `2|w| − 1` steps. Proved by combining the potential identity
`cnf_derivesIn_cost` with the fact that the first step must produce either
`BC` (cost `+2`) or a single terminal (cost `+2` toward `2|w|`). -/
theorem cnf_derivation_length
    (g : ContextFreeGrammar T) (hcnf : IsCNF g)
    (w : List T) (hw : w ≠ []) (hw_mem : w ∈ g.language)
    (n : ℕ) (hderiv : DerivesIn g [Symbol.nonterminal g.initial] (w.map Symbol.terminal) n) :
    n = 2 * w.length - 1 := by

  have hne_sf : [Symbol.nonterminal g.initial] ≠ w.map Symbol.terminal := by
    intro heq
    have : Symbol.nonterminal g.initial ∈ w.map Symbol.terminal := by
      rw [← heq]; simp
    simp only [List.mem_map] at this
    obtain ⟨_, _, habs⟩ := this
    cases habs

  obtain ⟨v, n', hp, hd, rfl⟩ : ∃ v n', g.Produces [Symbol.nonterminal g.initial] v ∧
      DerivesIn g v (w.map Symbol.terminal) n' ∧ n = n' + 1 := by
    generalize hs : [Symbol.nonterminal g.initial] = s at hderiv
    cases hderiv with
    | refl => exact absurd (Eq.symm hs) (Ne.symm hne_sf)
    | step hp hd => exact ⟨_, _, hs ▸ hp, hd, rfl⟩

  obtain ⟨r, hr_mem, hrw⟩ := hp
  rw [ContextFreeRule.rewrites_iff] at hrw
  obtain ⟨p, q, hpq_in, hpq_out⟩ := hrw

  have hp_nil : p = [] := by
    by_contra h
    have hlen := congr_arg List.length hpq_in
    simp [List.length_append] at hlen
    cases p with
    | nil => exact h rfl
    | cons _ _ => simp [List.length_append] at hlen; omega
  have hq_nil : q = [] := by
    rw [hp_nil] at hpq_in; simp at hpq_in; exact hpq_in.2
  have hv_eq : v = r.output := by
    rw [hp_nil, hq_nil] at hpq_out; simpa using hpq_out

  have hsv : Symbol.nonterminal g.initial ∉ v := by
    rw [hv_eq]; exact cnf_start_not_in_output g hcnf r hr_mem

  have hcost := cnf_derivesIn_cost g hcnf hd hsv

  have hcnf_r := hcnf r hr_mem
  rcases hcnf_r with ⟨B, C, _, _, hout⟩ | ⟨a, hout⟩ | ⟨_, hout⟩
  ·
    rw [hv_eq, hout] at hcost
    simp [ntCount, tCount, ntCount_map_terminal, tCount_map_terminal] at hcost
    omega
  ·
    rw [hv_eq, hout] at hcost
    simp [ntCount, tCount, ntCount_map_terminal, tCount_map_terminal] at hcost
    omega
  ·
    exfalso
    rw [hv_eq, hout] at hd

    suffices h : (w.map (Symbol.terminal (N := g.NT))) = ([] : List (Symbol T g.NT)) by
      simp at h; exact hw h
    generalize ht : (w.map (Symbol.terminal (N := g.NT))) = t at hd
    generalize hw' : ([] : List (Symbol T g.NT)) = s' at hd
    induction hd with
    | refl => rfl
    | step hp' _ _ =>
      obtain ⟨r', _, hrw'⟩ := hp'
      rw [ContextFreeRule.rewrites_iff] at hrw'
      obtain ⟨p', _, hpq', _⟩ := hrw'
      rw [← hw'] at hpq'; simp [List.append_assoc] at hpq'

end ChomskyNormalForm

universe u v w

/-- A **Pushdown Automaton** (PDA), Sipser, Lecture 4.

Formally, a PDA is a 6-tuple `(Q, Σ, Γ, δ, q₀, F)` where `Σ = α` is the input
alphabet, `Γ = γ` is the stack alphabet, `Q = σ` is the set of states,
`q₀ ∈ Q` is the start state, `F ⊆ Q` is the set of accept states, and
`δ : Q × Σ_ε × Γ_ε → 𝒫(Q × Γ_ε)` is the transition relation (where `_ε` means an
optional symbol, encoded here by `Option`). A move `(q', push) ∈ step q a pop`
means: in state `q`, optionally reading input `a` and optionally popping `pop`
from the stack, go to `q'` and optionally push `push`. -/
structure PDA (α : Type u) (σ : Type v) (γ : Type w) where
  step : σ → Option α → Option γ → Set (σ × Option γ)
  start : σ
  accept : Set σ

namespace PDA

variable {α : Type u} {σ : Type v} {γ : Type w}
variable (M : PDA α σ γ)

/-- An *instantaneous configuration* of a PDA: a triple `(q, input, stack)`
recording the current state, the remaining input to be read, and the current
stack contents (top at the head of the list). -/
abbrev Config := σ × List α × List γ

/-- One step of the PDA: read (optionally) an input symbol `a`, pop (optionally)
`pop` from the top of the stack, transition to `q'`, and push (optionally) `push`
on top of the stack. -/
inductive Step : Config (α := α) (σ := σ) (γ := γ) →
    Config (α := α) (σ := σ) (γ := γ) → Prop where
  | mk (q q' : σ) (a : Option α) (pop : Option γ) (push : Option γ)
      (input : List α) (stack : List γ) :
    (q', push) ∈ M.step q a pop →
    Step
      (q, a.toList ++ input, pop.toList ++ stack)
      (q', input, push.toList ++ stack)

/-- The reflexive transitive closure of `Step`: `c ⊢* c'` means `c` can reach
`c'` in zero or more PDA moves. -/
def Reaches : Config (α := α) (σ := σ) (γ := γ) →
    Config (α := α) (σ := σ) (γ := γ) → Prop :=
  Relation.ReflTransGen M.Step

/-- `M` accepts the input string `w` if, starting from `(q₀, w, ε)`, some
sequence of moves consumes all of `w` and ends in an accept state (the final
stack contents are arbitrary). -/
def Accepts (w : List α) : Prop :=
  ∃ q ∈ M.accept, ∃ stack : List γ, M.Reaches (M.start, w, []) (q, [], stack)

/-- The language recognised by the PDA: `L(M) = { w ∈ Σ* | M accepts w }`. -/
def language : Language α :=
  { w | M.Accepts w }

end PDA

/-- `listPow l n` is the list `l` repeated `n` times (i.e. `l^n` in the free
monoid of lists). Used to express the pumped strings `v^i` and `y^i` in the CFL
pumping lemma. -/
def listPow (l : List α) : Nat → List α
  | 0 => []
  | n + 1 => l ++ listPow l n

/-- `l^(n+1) = l ++ l^n`. -/
@[simp]
theorem listPow_succ (l : List α) (n : Nat) :
    listPow l (n + 1) = l ++ listPow l n := rfl

/-- The list power commutes with prepending vs. appending: `l ++ l^n = l^n ++ l`. -/
theorem listPow_comm (l : List α) :
    ∀ n, l ++ listPow l n = listPow l n ++ l := by
  intro n
  induction n with
  | zero => simp [listPow]
  | succ n ih =>
    show l ++ (l ++ listPow l n) = (l ++ listPow l n) ++ l
    rw [List.append_assoc, ih]

/-- Right-recursive form: `l^(n+1) = l^n ++ l`. -/
theorem listPow_succ_right (l : List α) (n : Nat) :
    listPow l (n + 1) = listPow l n ++ l :=
  listPow_comm l n

namespace CFLPumping

variable {T : Type*}

section PumpIteration

variable {g : ContextFreeGrammar T}

/-- *Pumping one level.* Given a self-loop derivation
`A ⇒* uAv` together with any derivation `A ⇒* target`, we can derive
`A ⇒* u·target·v` by first taking the loop and then substituting `target` for the
internal `A`. -/
theorem derives_pump_once {A : g.NT}
    {u v target : List (Symbol T g.NT)}
    (hloop : g.Derives [Symbol.nonterminal A]
      (u ++ [Symbol.nonterminal A] ++ v))
    (htarget : g.Derives [Symbol.nonterminal A] target) :
    g.Derives [Symbol.nonterminal A] (u ++ target ++ v) :=
  hloop.trans ((htarget.append_left u).append_right v)

/-- *Iterated pumping.* Iterating `derives_pump_once` `i` times yields
`A ⇒* u^i · target · v^i`. This is the source of the `v^i x y^i` structure in the
CFL pumping lemma. -/
theorem derives_pump_iter {A : g.NT}
    {u v target : List (Symbol T g.NT)}
    (hloop : g.Derives [Symbol.nonterminal A]
      (u ++ [Symbol.nonterminal A] ++ v))
    (htarget : g.Derives [Symbol.nonterminal A] target)
    (i : ℕ) :
    g.Derives [Symbol.nonterminal A]
      (listPow u i ++ target ++ listPow v i) := by
  induction i with
  | zero => simpa [listPow] using htarget
  | succ n ih =>
    have h := derives_pump_once hloop ih
    rw [listPow_succ, listPow_succ_right v n]
    simp only [List.append_assoc] at h ⊢
    exact h

end PumpIteration

section DecompositionHelpers

variable {g : ContextFreeGrammar T}

/-- *Splitting a one-step derivation across a concatenation.* If `u ++ v ⇒ w`,
then the single rule application happened entirely inside `u` or entirely inside
`v`; correspondingly `w` decomposes as `u' ++ v` (with `u ⇒ u'`) or as
`u ++ v'` (with `v ⇒ v'`). -/
theorem produces_append_split {u v w : List (Symbol T g.NT)}
    (h : g.Produces (u ++ v) w) :
    (∃ u', w = u' ++ v ∧ g.Produces u u') ∨
    (∃ v', w = u ++ v' ∧ g.Produces v v') := by
  obtain ⟨r, hr_mem, hrw⟩ := h
  rw [ContextFreeRule.rewrites_iff] at hrw
  obtain ⟨p, q, hpq_in, hpq_out⟩ := hrw
  have hpq_in' : u ++ v = p ++ ([Symbol.nonterminal r.input] ++ q) := by
    simp only [List.append_assoc] at hpq_in ⊢; exact hpq_in
  rw [List.append_eq_append_iff] at hpq_in'
  cases hpq_in' with
  | inl h =>
    obtain ⟨as, hp, hv⟩ := h
    right
    refine ⟨as ++ r.output ++ q, ?_, ?_⟩
    · rw [hpq_out, hp]; simp [List.append_assoc]
    · refine ⟨r, hr_mem, ?_⟩
      rw [ContextFreeRule.rewrites_iff]
      exact ⟨as, q, by rwa [List.append_assoc], rfl⟩
  | inr h =>
    obtain ⟨bs, hu, hbsv⟩ := h
    cases bs with
    | nil =>
      simp at hbsv
      right
      refine ⟨r.output ++ q, ?_, ?_⟩
      · rw [hpq_out, hu]; simp [List.append_assoc]
      · refine ⟨r, hr_mem, ?_⟩
        rw [ContextFreeRule.rewrites_iff]
        refine ⟨[], q, ?_, rfl⟩
        simp; exact hbsv.symm
    | cons b bs' =>
      simp at hbsv
      obtain ⟨hb, hbs'v⟩ := hbsv
      left
      refine ⟨p ++ r.output ++ bs', ?_, ?_⟩
      · rw [hpq_out, hbs'v]; simp [List.append_assoc]
      · refine ⟨r, hr_mem, ?_⟩
        rw [ContextFreeRule.rewrites_iff]
        refine ⟨p, bs', ?_, rfl⟩
        rw [hu, ← hb]; simp [List.append_assoc]

/-- *Splitting a multi-step derivation across a concatenation.* If
`u ++ v ⇒* w`, then `w = w₁ ++ w₂` with `u ⇒* w₁` and `v ⇒* w₂`. -/
theorem derives_append_split {u v w : List (Symbol T g.NT)}
    (h : g.Derives (u ++ v) w) :
    ∃ w1 w2, w = w1 ++ w2 ∧ g.Derives u w1 ∧ g.Derives v w2 := by
  induction h with
  | refl => exact ⟨u, v, rfl, .refl u, .refl v⟩
  | tail _ hlast ih =>
    obtain ⟨w1, w2, heq, hd1, hd2⟩ := ih
    subst heq
    cases produces_append_split hlast with
    | inl h =>
      obtain ⟨w1', hw, hp⟩ := h
      exact ⟨w1', w2, hw, hd1.trans_produces hp, hd2⟩
    | inr h =>
      obtain ⟨w2', hw, hp⟩ := h
      exact ⟨w1, w2', hw, hd1, hd2.trans_produces hp⟩

/-- A string consisting only of terminals cannot derive anything in one step:
a CFG rule requires a nonterminal on its left-hand side, so no rewrite position
exists inside `w.map Symbol.terminal`. -/
theorem all_terminals_not_produces
    {w : List T} {v : List (Symbol T g.NT)}
    (h : g.Produces (w.map Symbol.terminal) v) : False := by
  obtain ⟨r, _, hrw⟩ := h
  exact absurd hrw.nonterminal_input_mem (by simp [List.mem_map])

/-- Any decomposition of `w.map Symbol.terminal` as `w₁ ++ w₂` lifts to a
decomposition of `w` itself into `a ++ b` (with `w₁ = a.map Symbol.terminal` and
`w₂ = b.map Symbol.terminal`). -/
theorem map_terminal_split {N : Type*}
    (w : List T) (w1 w2 : List (Symbol T N))
    (h : w.map Symbol.terminal = w1 ++ w2) :
    ∃ a b : List T, w1 = a.map Symbol.terminal ∧
      w2 = b.map Symbol.terminal ∧ w = a ++ b := by
  induction w generalizing w1 w2 with
  | nil =>
    simp at h
    obtain ⟨h1, h2⟩ := h; subst h1; subst h2
    exact ⟨[], [], rfl, rfl, rfl⟩
  | cons t w ih =>
    cases w1 with
    | nil => simp at h; exact ⟨[], t :: w, rfl, by simp [h], rfl⟩
    | cons s w1' =>
      simp at h
      obtain ⟨hs, hrest⟩ := h
      obtain ⟨a', b', ha', hb', hw'⟩ := ih w1' w2 hrest
      exact ⟨t :: a', b', by simp [← hs, ha'], hb', by simp [hw']⟩

end DecompositionHelpers

section ParseTreeInfrastructure

variable {g : ContextFreeGrammar T}

/-- A *parse tree* of a CNF grammar `g`, rooted at the nonterminal `A`.

In CNF, each internal node is generated by a rule `A → BC` and has exactly two
children rooted at `B` and `C`; each leaf is generated by a rule `A → a` for some
terminal `a`. The CNF ε-rule `S → ε` is excluded here, since we only build parse
trees for nonempty strings. -/
inductive CNFParseTree (g : ContextFreeGrammar T) : g.NT → Type _ where
  | leaf (A : g.NT) (a : T) (hr : ⟨A, [Symbol.terminal a]⟩ ∈ g.rules) :
      CNFParseTree g A
  | node (A B C : g.NT)
      (hr : ⟨A, [Symbol.nonterminal B, Symbol.nonterminal C]⟩ ∈ g.rules)
      (left : CNFParseTree g B) (right : CNFParseTree g C) :
      CNFParseTree g A

namespace CNFParseTree

/-- The *yield* of a parse tree: the list of terminals at its leaves, read
left-to-right. -/
def yield : CNFParseTree g A → List T
  | .leaf _ a _ => [a]
  | .node _ _ _ _ l r => l.yield ++ r.yield

/-- The *height* of a parse tree: leaves have height `0`, and an internal node
has height `1 + max(height(left), height(right))`. -/
def height : CNFParseTree g A → ℕ
  | .leaf _ _ _ => 0
  | .node _ _ _ _ l r => max l.height r.height + 1

/-- *Yield-height bound.* In a binary parse tree, the number of leaves is at most
`2^h` where `h` is the height. This is the pigeonhole bound that gives the
pumping length `2^(k+1)` in the CFL pumping lemma. -/
theorem yield_length_le_pow_height (t : CNFParseTree g A) :
    t.yield.length ≤ 2 ^ t.height := by
  induction t with
  | leaf _ a _ => simp [yield, height]
  | node _ _ _ _ l r ihl ihr =>
    simp only [yield, height, List.length_append]
    have hle1 : l.yield.length + r.yield.length
        ≤ 2 ^ (max l.height r.height) + 2 ^ (max l.height r.height) := by
      calc l.yield.length + r.yield.length
          ≤ 2 ^ l.height + 2 ^ r.height := Nat.add_le_add ihl ihr
        _ ≤ 2 ^ (max l.height r.height) + 2 ^ (max l.height r.height) := by
            apply Nat.add_le_add
            · apply Nat.pow_le_pow_right (by omega : 1 ≤ 2) (le_max_left _ _)
            · apply Nat.pow_le_pow_right (by omega : 1 ≤ 2) (le_max_right _ _)
    calc l.yield.length + r.yield.length
        ≤ 2 ^ (max l.height r.height) + 2 ^ (max l.height r.height) := hle1
      _ = 2 * 2 ^ (max l.height r.height) := by omega
      _ = 2 ^ (max l.height r.height + 1) := by rw [Nat.pow_succ, Nat.mul_comm]

/-- *Soundness of parse trees.* Every parse tree rooted at `A` witnesses a
derivation `A ⇒* yield(t)` in the grammar. -/
theorem tree_derives (t : CNFParseTree g A) :
    g.Derives [Symbol.nonterminal A] (t.yield.map Symbol.terminal) := by
  induction t with
  | leaf A a hr =>
    apply Relation.ReflTransGen.single
    exact ⟨⟨A, [Symbol.terminal a]⟩, hr, ContextFreeRule.Rewrites.input_output⟩
  | node A B C hr l r ihl ihr =>
    simp only [yield, List.map_append]
    exact (Relation.ReflTransGen.single
      ⟨⟨A, _⟩, hr, ContextFreeRule.Rewrites.input_output⟩).trans
      ((ihl.append_right _).trans (ihr.append_left _))

/-- A parse tree (which has no ε-leaves by construction) always yields a nonempty
string of terminals. -/
theorem yield_nonempty (t : CNFParseTree g A) : t.yield ≠ [] := by
  cases t with
  | leaf => simp [yield]
  | node _ _ _ _ l _ =>
    simp only [yield]
    exact List.append_ne_nil_of_left_ne_nil l.yield_nonempty _

/-- The nonterminal label appearing at depth `d` along the *tallest path* of `t`
(breaking ties by descending into the left subtree). The pumping argument inspects
this sequence of labels to find a repeat by pigeonhole. -/
def ntAtDepth : {A : g.NT} → (t : CNFParseTree g A) → (d : ℕ) → (hd : d ≤ t.height) → g.NT
  | A, _, 0, _ => A
  | _, .node _ _ _ _ l r, d + 1, hd =>
    if h : l.height ≥ r.height then
      ntAtDepth l d (by simp [height] at hd; omega)
    else
      ntAtDepth r d (by simp [height] at hd; omega)

/-- *Decomposition with nonempty context.* For any positive depth `d` along the
tallest path of `t`, the tree splits as

  `yield(t) = lc ++ yield(sub) ++ rc`

where `sub` is the subtree rooted at the nonterminal `R = ntAtDepth t d`, the
derivation `A ⇒* lc · R · rc` holds, the subtree has height `height(t) − d`, and
the surrounding context `lc ++ rc` is nonempty (because we went down at least one
internal node and so picked off a sibling subtree, which yields a nonempty
string). This is what produces the `vy ≠ ε` clause of the CFL pumping lemma. -/
theorem exists_decomp_nonempty_ctx (t : CNFParseTree g A) (d : ℕ)
    (hd : d ≤ t.height) (hd_pos : 0 < d) :
    ∃ (R : g.NT) (sub : CNFParseTree g R) (lc rc : List T),
      R = t.ntAtDepth d hd ∧ sub.height = t.height - d ∧
      t.yield = lc ++ sub.yield ++ rc ∧
      g.Derives [Symbol.nonterminal A]
        (lc.map Symbol.terminal ++ [Symbol.nonterminal R] ++ rc.map Symbol.terminal) ∧
      (lc ++ rc).length > 0 := by
  induction d generalizing A with
  | zero => omega
  | succ d ih =>
    cases t with
    | leaf _ _ hr => simp [height] at hd
    | node A B C hr l r =>
      simp only [height] at hd
      by_cases h : l.height ≥ r.height
      · have hd' : d ≤ l.height := by omega
        rcases Nat.eq_zero_or_pos d with rfl | hd_pos'
        · exact ⟨B, l, [], r.yield,
            by simp only [ntAtDepth, h, ↓reduceDIte],
            by simp [height]; omega,
            by simp [yield],
            by simp only [List.map_nil, List.nil_append]
               exact (Relation.ReflTransGen.single
                 ⟨⟨A, _⟩, hr, ContextFreeRule.Rewrites.input_output⟩).trans
                 (r.tree_derives.append_left [Symbol.nonterminal B]),
            List.length_pos_of_ne_nil r.yield_nonempty⟩
        · obtain ⟨R, sub, lc', rc', hR, hsub, hyield, hderives, hctx⟩ := ih l hd' hd_pos'
          exact ⟨R, sub, lc', rc' ++ r.yield,
            by simp only [ntAtDepth, h, ↓reduceDIte, hR],
            by simp only [height]; omega,
            by simp only [yield, hyield, List.append_assoc],
            by have step2 := hderives.append_right [Symbol.nonterminal C]
               have step3 := r.tree_derives.append_left
                 (lc'.map Symbol.terminal ++ [Symbol.nonterminal R] ++ rc'.map Symbol.terminal)
               simp only [List.map_append, List.append_assoc] at step2 step3 ⊢
               exact (Relation.ReflTransGen.single
                   ⟨⟨A, _⟩, hr, ContextFreeRule.Rewrites.input_output⟩).trans (step2.trans step3),
            by simp only [List.length_append] at hctx ⊢; omega⟩
      · simp only [not_le] at h
        have hd' : d ≤ r.height := by omega
        rcases Nat.eq_zero_or_pos d with rfl | hd_pos'
        · exact ⟨C, r, l.yield, [],
            by simp only [ntAtDepth, not_le.mpr h, ↓reduceDIte],
            by simp [height]; omega,
            by simp [yield],
            by simp only [List.map_nil, List.append_nil]
               exact (Relation.ReflTransGen.single
                 ⟨⟨A, _⟩, hr, ContextFreeRule.Rewrites.input_output⟩).trans
                 (l.tree_derives.append_right [Symbol.nonterminal C]),
            by simp only [List.length_append, List.length_nil, Nat.add_zero]
               exact List.length_pos_of_ne_nil l.yield_nonempty⟩
        · obtain ⟨R, sub, lc', rc', hR, hsub, hyield, hderives, hctx⟩ := ih r hd' hd_pos'
          exact ⟨R, sub, l.yield ++ lc', rc',
            by simp only [ntAtDepth, not_le.mpr h, ↓reduceDIte, hR],
            by simp only [height]; omega,
            by simp only [yield, hyield, List.append_assoc],
            by have step2 := l.tree_derives.append_right [Symbol.nonterminal C]
               have step3 := hderives.append_left (l.yield.map Symbol.terminal)
               simp only [List.map_append, List.append_assoc] at step2 step3 ⊢
               exact (Relation.ReflTransGen.single
                   ⟨⟨A, _⟩, hr, ContextFreeRule.Rewrites.input_output⟩).trans (step2.trans step3),
            by simp only [List.length_append] at hctx ⊢; omega⟩

/-- Computation rule for `ntAtDepth` at a node: at depth `n > 0`, descend into
the taller child and ask for depth `n − 1`. -/
theorem ntAtDepth_node_eq {A B C : g.NT}
    (hr : ⟨A, [Symbol.nonterminal B, Symbol.nonterminal C]⟩ ∈ g.rules)
    (l : CNFParseTree g B) (r : CNFParseTree g C)
    (n : ℕ) (hn : 0 < n) (hd : n ≤ (node A B C hr l r).height) :
    (node A B C hr l r).ntAtDepth n hd =
      if h : l.height ≥ r.height then l.ntAtDepth (n - 1) (by simp [height] at hd; omega)
      else r.ntAtDepth (n - 1) (by simp [height] at hd; omega) := by
  cases n with
  | zero => omega
  | succ n => simp only [ntAtDepth, Nat.succ_sub_one]

/-- *Decomposition that is coherent with deeper sampling.* Like
`exists_decomp_nonempty_ctx`, but also guarantees that the nonterminal at depth
`d₂` of the extracted subtree `sub` coincides with the nonterminal at depth
`d₁ + d₂` of the original tree `t`. This coherence lets one apply two layers of
`exists_decomp_…` in `tree_pump` and ensure that the inner pumped nonterminal
matches the outer one (so the loop `A ⇒* uAv` is well-formed). -/
theorem exists_decomp_with_coherence (t : CNFParseTree g A) (d1 d2 : ℕ)
    (hd1 : d1 ≤ t.height) (hd12 : d1 + d2 ≤ t.height) :
    ∃ (R : g.NT) (sub : CNFParseTree g R) (lc rc : List T),
      R = t.ntAtDepth d1 hd1 ∧
      sub.height = t.height - d1 ∧
      t.yield = lc ++ sub.yield ++ rc ∧
      g.Derives [Symbol.nonterminal A]
        (lc.map Symbol.terminal ++ [Symbol.nonterminal R] ++ rc.map Symbol.terminal) ∧
      (∀ hd2 : d2 ≤ sub.height, sub.ntAtDepth d2 hd2 = t.ntAtDepth (d1 + d2) hd12) := by
  induction d1 generalizing A with
  | zero =>
    cases t with
    | leaf A a hr =>
      exact ⟨A, .leaf A a hr, [], [], rfl, rfl, by simp [yield], .refl _,
        fun _ => by congr 1; omega⟩
    | node A B C hr l r =>
      exact ⟨A, .node A B C hr l r, [], [], rfl, rfl, by simp [yield], .refl _,
        fun _ => by congr 1; omega⟩
  | succ d1 ih =>
    cases t with
    | leaf _ _ _ => simp [height] at hd1
    | node A B C hr l r =>
      simp only [height] at hd1 hd12
      by_cases h : l.height ≥ r.height
      · have hd1' : d1 ≤ l.height := by omega
        have hd12' : d1 + d2 ≤ l.height := by omega
        obtain ⟨R, sub, lc', rc', hR, hsub, hyield, hderives, hcoh⟩ := ih l hd1' hd12'
        refine ⟨R, sub, lc', rc' ++ r.yield, ?_, ?_, ?_, ?_, ?_⟩
        · rw [hR]; simp only [ntAtDepth, h, ↓reduceDIte]
        · rw [hsub]; simp [height]; omega
        · simp only [yield, hyield, List.append_assoc]
        · have step2 := hderives.append_right [Symbol.nonterminal C]
          have step3 := r.tree_derives.append_left
            (lc'.map Symbol.terminal ++ [Symbol.nonterminal R] ++ rc'.map Symbol.terminal)
          simp only [List.map_append, List.append_assoc] at step2 step3 ⊢
          exact (Relation.ReflTransGen.single
              ⟨⟨A, _⟩, hr, ContextFreeRule.Rewrites.input_output⟩).trans (step2.trans step3)
        · intro hd2
          rw [hcoh (by rw [hsub]; omega)]
          rw [ntAtDepth_node_eq hr l r _ (by omega) hd12, dif_pos h]
          congr 1; omega
      · have hnotge : ¬(l.height ≥ r.height) := h
        have hd1' : d1 ≤ r.height := by simp only [not_le] at h; omega
        have hd12' : d1 + d2 ≤ r.height := by simp only [not_le] at h; omega
        obtain ⟨R, sub, lc', rc', hR, hsub, hyield, hderives, hcoh⟩ := ih r hd1' hd12'
        refine ⟨R, sub, l.yield ++ lc', rc', ?_, ?_, ?_, ?_, ?_⟩
        · rw [hR]; simp only [ntAtDepth, hnotge, ↓reduceDIte]
        · rw [hsub]; simp [height]; simp only [not_le] at h; omega
        · simp only [yield, hyield, List.append_assoc]
        · have step2 := l.tree_derives.append_right [Symbol.nonterminal C]
          have step3 := hderives.append_left (l.yield.map Symbol.terminal)
          simp only [List.map_append, List.append_assoc] at step2 step3 ⊢
          exact (Relation.ReflTransGen.single
              ⟨⟨A, _⟩, hr, ContextFreeRule.Rewrites.input_output⟩).trans (step2.trans step3)
        · intro hd2
          rw [hcoh (by rw [hsub]; omega)]
          rw [ntAtDepth_node_eq hr l r _ (by omega) hd12, dif_neg hnotge]
          congr 1; omega

end CNFParseTree

/-- Inversion principle: a one-step derivation `[A] ⇒ v` from a singleton
sentential form must use a rule whose left-hand side is `A`, and `v` is that
rule's right-hand side. -/
theorem produces_from_singleton_nonterminal'
    {g : ContextFreeGrammar T} {A : g.NT} {v : List (Symbol T g.NT)}
    (h : g.Produces [Symbol.nonterminal A] v) :
    ∃ r ∈ g.rules, r.input = A ∧ v = r.output := by
  obtain ⟨r, hr_mem, hrw⟩ := h
  obtain ⟨p, q, hpq_in, hpq_out⟩ := hrw.exists_parts
  have hlen : p.length + 1 + q.length = 1 := by
    have := congr_arg List.length hpq_in
    simp [List.length_append] at this; omega
  have hp : p = [] := by
    rcases p with _ | ⟨_, _⟩ <;> simp_all <;> omega
  have hq : q = [] := by
    subst hp; simp at hlen
    rcases q with _ | ⟨_, _⟩ <;> simp_all <;> omega
  subst hp; subst hq
  simp at hpq_in hpq_out
  exact ⟨r, hr_mem, hpq_in.symm, hpq_out⟩

/-- A derivation `[A] ⇒* w` to a nonempty terminal string must contain at least
one step, and so factors as a first one-step `[A] ⇒ v` followed by `v ⇒* w`. -/
theorem derives_from_nt_nontrivial
    {g : ContextFreeGrammar T} {A : g.NT} {w : List T} (hne : w ≠ [])
    (hd : g.Derives [Symbol.nonterminal A] (w.map Symbol.terminal)) :
    ∃ v, g.Produces [Symbol.nonterminal A] v ∧ g.Derives v (w.map Symbol.terminal) := by
  rcases hd.eq_or_head with h | ⟨v, hprod, hrest⟩
  · exfalso
    cases w with
    | nil => exact hne rfl
    | cons t ts => simp at h
  · exact ⟨v, hprod, hrest⟩

/-- The empty sentential form derives only itself: `[] ⇒* w` implies `w = []`,
since there is no nonterminal in `[]` to rewrite. -/
theorem derives_nil_of_nil
    {g : ContextFreeGrammar T} {w : List (Symbol T g.NT)}
    (hd : g.Derives [] w) : w = [] := by
  rcases hd.eq_or_head with h | ⟨v, hprod, _⟩
  · exact h.symm
  · exfalso
    obtain ⟨r, _, hrw⟩ := hprod
    have := hrw.nonterminal_input_mem
    simp at this

/-- In a CNF grammar, only the start variable can erase a string: if `B ≠ S` and
`B ⇒* w`, then `w` is nonempty. (The only ε-rule allowed in CNF has `S` on its
left-hand side, and the start variable never appears on a right-hand side.) -/
theorem cnf_nonempty_of_derives_ne_initial
    {g : ContextFreeGrammar T} (hcnf : ChomskyNormalForm.IsCNF g)
    {B : g.NT} (hB : B ≠ g.initial)
    (w : List (Symbol T g.NT)) (hd : g.Derives [Symbol.nonterminal B] w) :
    w ≠ [] := by
  intro hw
  subst hw


  rcases hd.eq_or_tail with h | ⟨u, hderiv_u, hprod_u⟩
  · simp at h
  · obtain ⟨r, hr_mem, hrw⟩ := hprod_u
    obtain ⟨p, q, hpq_in, hpq_out⟩ := hrw.exists_parts
    have hp : p = [] := by
      cases p with
      | nil => rfl
      | cons _ _ => simp [List.append_assoc] at hpq_out
    have hq : q = [] := by
      subst hp
      simp [List.append_assoc] at hpq_out
      cases q with
      | nil => rfl
      | cons _ _ =>
        cases r.output <;> simp at hpq_out
    have hro : r.output = [] := by
      subst hp
      subst hq
      simpa using hpq_out

    have hcnf_r := hcnf r hr_mem
    rcases hcnf_r with ⟨_, _, _, _, ho⟩ | ⟨_, ho⟩ | ⟨hinp, _⟩
    · simp [ho] at hro
    · simp [ho] at hro
    ·
      subst hp
      subst hq
      simp at hpq_in
      rw [hinp] at hpq_in

      have : ∀ sf, g.Derives [Symbol.nonterminal B] sf →
          Symbol.nonterminal g.initial ∉ sf := by
        intro sf hder
        induction hder with
        | refl => simp; exact fun h => hB h.symm
        | tail _ hlast ih_inner =>
          intro hmem
          obtain ⟨r', hr'_mem, hrw'⟩ := hlast
          obtain ⟨p', q', hp'_in, hp'_out⟩ := hrw'.exists_parts
          rw [hp'_out] at hmem
          simp [List.mem_append] at hmem
          rcases hmem with hmem_p | hmem_out | hmem_q
          · exact ih_inner (by rw [hp'_in]; exact List.mem_append_left _ (List.mem_append_left _ hmem_p))
          ·
            have hcnf_r' := hcnf r' hr'_mem
            rcases hcnf_r' with ⟨B'', C'', hB''ne, hC''ne, ho'⟩ | ⟨a', ho'⟩ | ⟨_, ho'⟩
            · rw [ho'] at hmem_out; simp at hmem_out
              rcases hmem_out with h' | h'
              · exact hB''ne h'.symm
              · exact hC''ne h'.symm
            · rw [ho'] at hmem_out; simp at hmem_out
            · rw [ho'] at hmem_out; simp at hmem_out
          · exact ih_inner (by rw [hp'_in]; exact List.mem_append_right _ hmem_q)
      have h_not_mem := this _ hderiv_u
      rw [hpq_in] at h_not_mem
      exact h_not_mem (List.mem_singleton.mpr rfl)

/-- *Existence of a parse tree, by strong induction on the length of the yield.*
If `g` is in CNF and `[A] ⇒* w` with `w` nonempty and `|w| ≤ n`, then there is a
`CNFParseTree g A` whose yield is `w`. The proof inverts the first derivation
step against the three CNF rule forms and recurses on the two halves produced by
an `A → BC` rule. -/
theorem cnf_tree_of_derives_aux
    (g : ContextFreeGrammar T) (hcnf : ChomskyNormalForm.IsCNF g) :
    ∀ (n : ℕ) (A : g.NT) (w : List T),
      w.length ≤ n → w ≠ [] →
      g.Derives [Symbol.nonterminal A] (w.map Symbol.terminal) →
      ∃ (t : CNFParseTree g A), t.yield = w := by
  intro n
  induction n with
  | zero =>
    intro A w hw hne _
    exfalso; exact hne (List.eq_nil_of_length_eq_zero (Nat.le_zero.mp hw))
  | succ n ih =>
  intro A w hw hne hd

  obtain ⟨v, hprod, hrest⟩ := derives_from_nt_nontrivial hne hd

  obtain ⟨r, hr_mem, hr_input, hv_eq⟩ := produces_from_singleton_nonterminal' hprod

  subst hv_eq

  have hcnf_r := hcnf r hr_mem
  rcases hcnf_r with ⟨B, C, hBne, hCne, hr_out⟩ | ⟨a, hr_out⟩ | ⟨hinp, hr_out⟩
  ·
    rw [hr_out] at hrest

    have hsplit := derives_append_split
      (u := [Symbol.nonterminal B]) (v := [Symbol.nonterminal C]) hrest
    obtain ⟨w1, w2, heq, hd1, hd2⟩ := hsplit

    obtain ⟨s1, s2, hw1, hw2, hweq⟩ := map_terminal_split w w1 w2 heq

    rw [hw1] at hd1; rw [hw2] at hd2

    have hs1_ne : s1 ≠ [] := by
      intro hs1; subst hs1; simp at hd1
      exact cnf_nonempty_of_derives_ne_initial hcnf hBne _ hd1 rfl
    have hs2_ne : s2 ≠ [] := by
      intro hs2; subst hs2; simp at hd2
      exact cnf_nonempty_of_derives_ne_initial hcnf hCne _ hd2 rfl

    have hs1_len : s1.length ≤ n := by
      have : s2.length > 0 := List.length_pos_of_ne_nil hs2_ne
      rw [hweq] at hw; simp [List.length_append] at hw; omega
    have hs2_len : s2.length ≤ n := by
      have : s1.length > 0 := List.length_pos_of_ne_nil hs1_ne
      rw [hweq] at hw; simp [List.length_append] at hw; omega
    obtain ⟨t1, ht1⟩ := ih B s1 hs1_len hs1_ne hd1
    obtain ⟨t2, ht2⟩ := ih C s2 hs2_len hs2_ne hd2

    have hr_mem' : (⟨A, [Symbol.nonterminal B, Symbol.nonterminal C]⟩ : ContextFreeRule T g.NT) ∈ g.rules := by
      have heq_r : r = ⟨A, [Symbol.nonterminal B, Symbol.nonterminal C]⟩ := by
        cases r; simp_all
      rw [← heq_r]; exact hr_mem
    exact ⟨.node A B C hr_mem' t1 t2, by simp [CNFParseTree.yield, ht1, ht2, hweq]⟩
  ·
    rw [hr_out] at hrest


    rcases hrest.eq_or_head with h | ⟨v', hprod', _⟩
    ·
      have hw_eq : w = [a] := by
        have hlen : w.length = 1 := by
          have := congr_arg List.length h
          simp at this; exact this.symm
        match w, hlen with
        | [x], _ =>
          simp at h; exact congrArg ([·]) h.symm
      subst hw_eq
      have hr_mem' : (⟨A, [Symbol.terminal a]⟩ : ContextFreeRule T g.NT) ∈ g.rules := by
        have : r = ⟨A, [Symbol.terminal a]⟩ := by
          have h1 : r.input = A := hr_input
          have h2 : r.output = [Symbol.terminal a] := hr_out
          exact ContextFreeRule.ext h1 h2
        rw [← this]; exact hr_mem
      exact ⟨.leaf A a hr_mem', by simp [CNFParseTree.yield]⟩
    ·
      exfalso
      exact all_terminals_not_produces (w := [a]) hprod'
  ·
    rw [hr_out] at hrest

    exfalso
    have h := derives_nil_of_nil hrest
    exact hne (by cases w <;> simp_all)

/-- *Completeness of CNF parse trees:* every nonempty string in `L(g)` (for a CNF
grammar `g`) is the yield of some parse tree rooted at the start variable. -/
theorem cnf_tree_of_mem_language
    (g : ContextFreeGrammar T) (hcnf : ChomskyNormalForm.IsCNF g)
    (s : List T) (hs : s ∈ g.language) (hne : s ≠ []) :
    ∃ (t : CNFParseTree g g.initial), t.yield = s := by
  rw [ContextFreeGrammar.mem_language_iff] at hs
  exact cnf_tree_of_derives_aux g hcnf s.length g.initial s (Nat.le_refl _) hne hs

/-- `List.map` distributes over `listPow`: `map f (l^n) = (map f l)^n`. -/
theorem listPow_map (f : α → β) (l : List α) :
    ∀ n, (listPow l n).map f = listPow (l.map f) n := by
  intro n; induction n with
  | zero => simp [listPow]
  | succ n ih => simp [listPow, List.map_append, ih]

/-- *Tree-level pumping lemma.* If a parse tree `t` (rooted at `A`) has height
exceeding the number of nonterminals `k = |V|`, then by pigeonhole some
nonterminal `R` repeats along the tallest path. The two occurrences of `R`
decompose `yield(t) = u v x y z` with:

* `A ⇒* u v^i x y^i z` for every `i ≥ 0` (using `derives_pump_iter`),
* `vy ≠ ε` (from `exists_decomp_nonempty_ctx`), and
* `|vxy| ≤ 2^(k+1)` (from the yield/height bound applied to the inner subtree). -/
theorem tree_pump
    (g : ContextFreeGrammar T) [Fintype g.NT] [DecidableEq g.NT]
    {A : g.NT} (t : CNFParseTree g A)
    (hh : t.height > Fintype.card g.NT) :
    ∃ u v x y z : List T,
      t.yield = u ++ v ++ x ++ y ++ z ∧
      (∀ i : ℕ, g.Derives [Symbol.nonterminal A]
        ((u ++ listPow v i ++ x ++ listPow y i ++ z).map Symbol.terminal)) ∧
      (v ++ y).length > 0 ∧
      (v ++ x ++ y).length ≤ 2 ^ (Fintype.card g.NT + 1) := by
  set k := Fintype.card g.NT
  have hbase : t.height - k ≥ 1 := by omega

  let f : Fin (k + 1) → g.NT := fun i => t.ntAtDepth (t.height - k + i.val) (by omega)
  obtain ⟨i, j, hij, hfij⟩ :=
    Fintype.exists_ne_map_eq_of_card_lt f (by rw [Fintype.card_fin]; omega)

  obtain ⟨d1f, d2f, hd12, hfd⟩ : ∃ d1 d2 : Fin (k + 1), d1 < d2 ∧ f d1 = f d2 := by
    rcases lt_or_gt_of_ne hij with h | h
    · exact ⟨i, j, h, hfij⟩
    · exact ⟨j, i, h, hfij.symm⟩
  set d1 := t.height - k + d1f.val
  set d2 := t.height - k + d2f.val
  have hd1_pos : 0 < d1 := by omega
  have hd1_le : d1 ≤ t.height := by omega
  have hd1_lt_d2 : d1 < d2 := by omega
  have hd_diff_pos : 0 < d2 - d1 := by omega
  have hnt_eq : t.ntAtDepth d1 hd1_le = t.ntAtDepth d2 (by omega) := by
    show f d1f = f d2f; exact hfd

  have hd12_le : d1 + (d2 - d1) ≤ t.height := by omega
  obtain ⟨R, sub, u_part, z_part, hR, hsub_h, hyield_outer, hderives_outer, hcoh⟩ :=
    t.exists_decomp_with_coherence d1 (d2 - d1) hd1_le hd12_le

  have hsub_nt : sub.ntAtDepth (d2 - d1) (by rw [hsub_h]; omega) = R := by
    rw [hcoh (by rw [hsub_h]; omega)]


    calc t.ntAtDepth (d1 + (d2 - d1)) hd12_le
        = t.ntAtDepth d2 (by omega) := by congr 1; omega
      _ = t.ntAtDepth d1 hd1_le := hnt_eq.symm
      _ = R := hR.symm

  obtain ⟨R', sub_inner, v_part, y_part, hR', hsub_inner_h, hyield_inner, hderives_inner, hctx⟩ :=
    sub.exists_decomp_nonempty_ctx (d2 - d1) (by rw [hsub_h]; omega) hd_diff_pos

  have hR'_eq_R : R' = R := by rw [hR', hsub_nt]
  subst hR'_eq_R
  refine ⟨u_part, v_part, sub_inner.yield, y_part, z_part, ?_, ?_, ?_, ?_⟩
  ·
    simp only [hyield_outer, hyield_inner, List.append_assoc]
  ·
    intro i
    have hpump := derives_pump_iter hderives_inner sub_inner.tree_derives i
    have hfull := hderives_outer.trans
      ((hpump.append_left (u_part.map Symbol.terminal)).append_right (z_part.map Symbol.terminal))
    simp only [List.map_append, List.append_assoc, listPow_map] at hfull ⊢
    exact hfull
  ·
    exact hctx
  ·
    have hsub_height_le : sub.height ≤ k + 1 := by rw [hsub_h]; omega
    have hyield_len := sub.yield_length_le_pow_height
    rw [hyield_inner] at hyield_len
    simp only [List.length_append] at hyield_len ⊢
    calc v_part.length + sub_inner.yield.length + y_part.length
        ≤ 2 ^ sub.height := hyield_len
      _ ≤ 2 ^ (k + 1) := Nat.pow_le_pow_right (by omega) hsub_height_le

/-- *Pumping lemma for CNF grammars.* If `g` is a CNF grammar with `k = |V|`
nonterminals and `s ∈ L(g)` has length `|s| ≥ 2^(k+1)`, then `s = u v x y z`
with `u v^i x y^i z ∈ L(g)` for all `i ≥ 0`, `vy ≠ ε`, and `|vxy| ≤ 2^(k+1)`.
The argument: the height bound `|s| ≤ 2^h` forces `h > k`, so `tree_pump`
applies to a parse tree for `s`. -/
theorem cnf_pumping_core [Fintype g.NT] [DecidableEq g.NT]
    (hcnf : ChomskyNormalForm.IsCNF g)
    (s : List T) (hs : s ∈ g.language)
    (hlen : s.length ≥ 2 ^ (Fintype.card g.NT + 1)) :
    ∃ u v x y z : List T,
      s = u ++ v ++ x ++ y ++ z ∧
      (∀ i : ℕ, (u ++ listPow v i ++ x ++ listPow y i ++ z) ∈ g.language) ∧
      (v ++ y).length > 0 ∧
      (v ++ x ++ y).length ≤ 2 ^ (Fintype.card g.NT + 1) := by

  have hne : s ≠ [] := by
    intro h; subst h; simp at hlen

  obtain ⟨t, ht⟩ := cnf_tree_of_mem_language g hcnf s hs hne

  have hheight : t.height > Fintype.card g.NT := by
    by_contra h
    push_neg at h
    have h1 := t.yield_length_le_pow_height
    rw [ht] at h1
    have h2 : 2 ^ t.height ≤ 2 ^ Fintype.card g.NT :=
      Nat.pow_le_pow_right (by omega) h
    have : 2 ^ Fintype.card g.NT < 2 ^ (Fintype.card g.NT + 1) :=
      Nat.pow_lt_pow_right (by omega) (by omega)
    omega

  obtain ⟨u, v, x, y, z, hyield, hpump, hvy, hvxy⟩ := tree_pump g t hheight
  exact ⟨u, v, x, y, z, ht ▸ hyield, fun i => by
    rw [ContextFreeGrammar.mem_language_iff]; exact hpump i, hvy, hvxy⟩

end ParseTreeInfrastructure

/-- **Pumping Lemma for Context Free Languages** (Sipser, Lecture 5).

For every CFL `A` there exists a *pumping length* `p ∈ ℕ` such that every string
`s ∈ A` with `|s| ≥ p` admits a decomposition `s = uvxyz` satisfying:

1. `u v^i x y^i z ∈ A` for all `i ≥ 0`,
2. `vy ≠ ε`, and
3. `|vxy| ≤ p`.

Proof: pick a CFG for `A`, convert it to a CNF grammar `g` with a finite
nonterminal type via `ChomskyNormalForm.cfg_to_cnf_fintype`, and apply
`cnf_pumping_core` with `p = 2^(|V|+1)`. -/
theorem pumping_lemma_cfl {A : Language T} (hA : Language.IsContextFree A) :
    ∃ p : ℕ, ∀ s ∈ A, s.length ≥ p →
      ∃ u v x y z : List T,
        s = u ++ v ++ x ++ y ++ z ∧
        (∀ i : ℕ, u ++ listPow v i ++ x ++ listPow y i ++ z ∈ A) ∧
        (v ++ y).length > 0 ∧
        (v ++ x ++ y).length ≤ p := by
  obtain ⟨g₀, hg₀⟩ := hA
  obtain ⟨g, hfin, hdec, hcnf, hlang⟩ := ChomskyNormalForm.cfg_to_cnf_fintype g₀
  haveI := hfin; haveI := hdec
  use 2 ^ (Fintype.card g.NT + 1)
  intro s hs hlen
  rw [← hlang.trans hg₀] at hs ⊢
  exact cnf_pumping_core hcnf s hs hlen

end CFLPumping
