/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.RingTheory.ClassGroup

set_option maxHeartbeats 1600000


section CartierDivisorGroupAlgebraic

open scoped nonZeroDivisors
open FractionalIdeal

variable (A : Type*) [CommRing A] [IsDomain A] [IsDedekindDomain A]
variable (K : Type*) [Field K] [Algebra A K] [IsFractionRing A K]

/-- The Cartier divisor group of a Dedekind domain `A` with fraction field `K`, defined
algebraically as the units in the monoid of fractional ideals (cf. Def 30, Lec 14). -/
def CartierDivisorGroup : Type _ := (FractionalIdeal A⁰ K)ˣ

namespace CartierDivisorGroup

/-- The Cartier divisor group is a commutative group, inherited from the units of fractional
ideals. -/
noncomputable instance instCommGroup : CommGroup (CartierDivisorGroup A K) :=
  inferInstanceAs (CommGroup (FractionalIdeal A⁰ K)ˣ)

/-- The Cartier divisor group is inhabited by the trivial divisor `1`. -/
noncomputable instance instInhabited : Inhabited (CartierDivisorGroup A K) := ⟨1⟩

/-- The tautological multiplicative equivalence between `CartierDivisorGroup A K` and the units
of fractional ideals. -/
noncomputable def equiv : CartierDivisorGroup A K ≃* (FractionalIdeal A⁰ K)ˣ :=
  MulEquiv.refl _

/-- Forget the Cartier divisor wrapping to obtain the underlying unit fractional ideal. -/
noncomputable def toUnits (D : CartierDivisorGroup A K) :
    (FractionalIdeal A⁰ K)ˣ := D

/-- View a Cartier divisor as the underlying fractional ideal (forgetting invertibility). -/
noncomputable def toFractionalIdeal (D : CartierDivisorGroup A K) :
    FractionalIdeal A⁰ K :=
  (D.toUnits : FractionalIdeal A⁰ K)

/-- The principal divisor map `Kˣ → CartierDivisorGroup A K` sending a unit `x` to the
divisor of the principal fractional ideal `(x)`. -/
noncomputable def principalDivisor : Kˣ →* CartierDivisorGroup A K :=
  toPrincipalIdeal A K

/-- The Picard group of a Dedekind domain is the quotient of the Cartier divisor group by the
subgroup of principal divisors; this realises it as the ideal class group. -/
noncomputable def picardEquiv :
    ClassGroup A ≃*
      (CartierDivisorGroup A K) ⧸ (principalDivisor A K).range := by
  unfold CartierDivisorGroup principalDivisor
  exact ClassGroup.equiv K

omit [IsDomain A] in
/-- A Cartier divisor is principal iff its underlying fractional ideal is generated by a single
element of `K`. -/
theorem isPrincipal_iff (D : CartierDivisorGroup A K) :
    D ∈ (principalDivisor A K).range ↔
      ∃ x : K, FractionalIdeal.spanSingleton A⁰ x =
        D.toFractionalIdeal A K := by
  unfold principalDivisor toFractionalIdeal toUnits
  exact mem_principal_ideals_iff

omit [IsDomain A] in
/-- Two Cartier divisors are linearly equivalent (i.e. equal in the Picard group) iff they differ
by a principal divisor. -/
theorem linearlyEquivalent_iff (D₁ D₂ : CartierDivisorGroup A K) :
    (QuotientGroup.mk' (principalDivisor A K).range D₁ =
      QuotientGroup.mk' (principalDivisor A K).range D₂) ↔
    ∃ x : Kˣ, D₁ * principalDivisor A K x = D₂ := by
  rw [QuotientGroup.mk'_eq_mk']
  simp only [MonoidHom.mem_range]
  constructor
  · rintro ⟨z, ⟨x, rfl⟩, h⟩
    exact ⟨x, h⟩
  · rintro ⟨x, h⟩
    exact ⟨principalDivisor A K x, ⟨x, rfl⟩, h⟩

/-- Promote a nonzero ordinary ideal of `A` to a Cartier divisor by viewing it as a fractional
ideal of `K`. -/
noncomputable def fromIdeal : (Ideal A)⁰ →* CartierDivisorGroup A K :=
  FractionalIdeal.mk0 K

end CartierDivisorGroup

end CartierDivisorGroupAlgebraic
