/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.GradedAlgebra.Basic
import Mathlib.RingTheory.ReesAlgebra
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.AlgebraicGeometry.Scheme

set_option maxHeartbeats 400000

noncomputable section

open Polynomial AlgebraicGeometry

variable {R : Type*} [CommRing R]

namespace Definition38

/-- The ideal of the Rees algebra of `𝔪` generated by the image of `𝔪 ⊆ R`. -/
noncomputable def reesIdealFromBase (𝔪 : Ideal R) : Ideal (reesAlgebra 𝔪) :=
  Ideal.map (algebraMap R (reesAlgebra 𝔪)) 𝔪

/-- Associated graded ring `gr_𝔪(R) = ⊕_n 𝔪^n / 𝔪^{n+1}`, realized as the Rees algebra modulo
the ideal generated by `𝔪` (Def 38, Lec 19). -/
def assocGradedRing (𝔪 : Ideal R) : Type _ :=
  (reesAlgebra 𝔪) ⧸ reesIdealFromBase 𝔪

/-- The associated graded ring is a commutative ring. -/
noncomputable instance assocGradedRing.instCommRing (𝔪 : Ideal R) :
    CommRing (assocGradedRing 𝔪) :=
  Ideal.Quotient.commRing (reesIdealFromBase 𝔪)

/-- Canonical ring map `R → gr_𝔪(R)` factoring through the Rees algebra and quotient. -/
noncomputable def ringHomToAssocGraded (𝔪 : Ideal R) : R →+* assocGradedRing 𝔪 :=
  (Ideal.Quotient.mk (reesIdealFromBase 𝔪)).comp (algebraMap R (reesAlgebra 𝔪))

/-- The maximal ideal `𝔪` lies in the kernel of `R → gr_𝔪(R)`, i.e. the associated graded
ring lives over the closed point. -/
theorem tangentCone_over_closedPoint (𝔪 : Ideal R) :
    𝔪 ≤ RingHom.ker (ringHomToAssocGraded 𝔪) := by
  intro r hr
  rw [RingHom.mem_ker]
  show (Ideal.Quotient.mk (reesIdealFromBase 𝔪)) ((algebraMap R (reesAlgebra 𝔪)) r) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.mem_map_of_mem _ hr

/-- The tangent cone (Def 38, Lec 19): `T_x X = Spec(gr_𝔪(O_{X,x}))` for the maximal ideal `𝔪`. -/
noncomputable def tangentCone (𝔪 : Ideal R) : Scheme :=
  Spec (.of (assocGradedRing 𝔪))

/-- The canonical morphism `tangentCone 𝔪 → Spec R` induced by `R → gr_𝔪(R)`. -/
noncomputable def tangentConeMap (𝔪 : Ideal R) :
    tangentCone 𝔪 ⟶ Spec (.of R) :=
  Spec.map (CommRingCat.ofHom (ringHomToAssocGraded 𝔪))

end Definition38

end
