/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.ReesAlgebra
import Mathlib.Algebra.GroupWithZero.NonZeroDivisors

set_option maxHeartbeats 400000

open Polynomial

namespace GradedRingQuotient

universe u

variable {A : Type u} [CommRing A]

/-- Ideal of the Rees algebra generated by the image of `I ⊆ A`. -/
noncomputable def reesIdealFromBase (I : Ideal A) : Ideal (reesAlgebra I) :=
  Ideal.map (algebraMap A (reesAlgebra I)) I

/-- Associated graded ring `gr_I(A) = ⊕_p I^p / I^{p+1}` realized via the Rees algebra. -/
def assocGradedRing (I : Ideal A) : Type _ :=
  (reesAlgebra I) ⧸ reesIdealFromBase I

/-- The associated graded ring is a commutative ring. -/
noncomputable instance assocGradedRing.commRing (I : Ideal A) :
    CommRing (assocGradedRing I) :=
  Ideal.Quotient.commRing (reesIdealFromBase I)

/-- If `a ∈ I^p`, then the monomial `a · t^p` belongs to the Rees algebra of `I`. -/
lemma monomial_mem_reesAlgebra (I : Ideal A) (p : ℕ) (a : A) (ha : a ∈ I ^ p) :
    Polynomial.monomial p a ∈ reesAlgebra I :=
  reesAlgebra.monomial_mem.mpr ha

/-- Image in `gr_I(A)` of an element `a ∈ I^p`, viewed as a degree-`p` homogeneous element. -/
noncomputable def imageInAssocGraded (I : Ideal A) (p : ℕ) (a : A) (ha : a ∈ I ^ p) :
    assocGradedRing I :=
  Ideal.Quotient.mk (reesIdealFromBase I)
    ⟨Polynomial.monomial p a, monomial_mem_reesAlgebra I p a ha⟩

/-- Image of the ideal `𝔪` under the quotient map `A → A / (a)`. -/
noncomputable def quotientIdeal (𝔪 : Ideal A) (a : A) : Ideal (A ⧸ Ideal.span {a}) :=
  Ideal.map (Ideal.Quotient.mk (Ideal.span {a})) 𝔪

/-- Lemma 32: if `a ∈ 𝔪^p` and its image in `gr_𝔪(A)` is a nonzero divisor, then
`gr_{𝔪/(a)}(A/(a)) ≃ gr_𝔪(A) / (image of a)`. -/
theorem lemma_32_graded_ring_quotient
    (𝔪 : Ideal A) [𝔪.IsMaximal]
    (a : A) (p : ℕ) (ha : a ∈ 𝔪 ^ p)
    (hreg : imageInAssocGraded 𝔪 p a ha ∈ nonZeroDivisors (assocGradedRing 𝔪)) :
    Nonempty (assocGradedRing (quotientIdeal 𝔪 a) ≃+*
      assocGradedRing 𝔪 ⧸ Ideal.span {imageInAssocGraded 𝔪 p a ha}) := by
  sorry

end GradedRingQuotient
