/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.Algebra.Category.ModuleCat.Basic
import Mathlib.GroupTheory.QuotientGroup.Defs
import Mathlib.Algebra.Module.Prod
import Mathlib.Algebra.Exact

set_option maxHeartbeats 400000

noncomputable section

open CategoryTheory

namespace DegreeAdditivity

universe u

/-- The set of relations in `K^0` arising from short exact sequences `0 → A → B → C → 0`: each
yields the relation `[B] - [A] - [C] = 0`. -/
def K0SESRelSet (R : Type u) [Ring R] : Set (FreeAbelianGroup (ModuleCat.{u} R)) :=
  { x | ∃ (A B C : ModuleCat.{u} R) (f : A →ₗ[R] B) (g : B →ₗ[R] C),
    Function.Injective f ∧ Function.Surjective g ∧ Function.Exact f g ∧
    x = FreeAbelianGroup.of B - FreeAbelianGroup.of A - FreeAbelianGroup.of C }

/-- Subgroup generated by all SES-relations; quotienting by it yields the Grothendieck group. -/
def K0SESRelSubgroup (R : Type u) [Ring R] : AddSubgroup (FreeAbelianGroup (ModuleCat.{u} R)) :=
  AddSubgroup.closure (K0SESRelSet R)

/-- Grothendieck group `K^0(A) = K^0(R-Mod)` (Def 42, Lec 22): free abelian on iso classes of
modules modulo `[B] = [A] + [C]` for every SES `0 → A → B → C → 0`. -/
abbrev GrothendieckGroupK0 (R : Type u) [Ring R] : Type _ :=
  FreeAbelianGroup (ModuleCat.{u} R) ⧸ K0SESRelSubgroup R

/-- The class `[M]` of a module `M` in `K^0(R)`. -/
def GrothendieckGroupK0.classOf (R : Type u) [Ring R] (M : ModuleCat.{u} R) :
    GrothendieckGroupK0 R :=
  QuotientAddGroup.mk (FreeAbelianGroup.of M)

/-- Defining relation in `K^0`: for any SES `0 → A → B → C → 0`, `[B] = [A] + [C]`. -/
theorem GrothendieckGroupK0.ses_relation (R : Type u) [Ring R]
    {A B C : ModuleCat.{u} R} (f : A →ₗ[R] B) (g : B →ₗ[R] C)
    (hf : Function.Injective f) (hg : Function.Surjective g)
    (hex : Function.Exact f g) :
    GrothendieckGroupK0.classOf R B =
      GrothendieckGroupK0.classOf R A + GrothendieckGroupK0.classOf R C := by
  unfold GrothendieckGroupK0.classOf
  rw [← QuotientAddGroup.mk_add]
  apply QuotientAddGroup.eq.mpr
  have hmem : FreeAbelianGroup.of B - FreeAbelianGroup.of A -
      FreeAbelianGroup.of C ∈ K0SESRelSubgroup R :=
    AddSubgroup.subset_closure ⟨A, B, C, f, g, hf, hg, hex, rfl⟩
  have : -FreeAbelianGroup.of B + (FreeAbelianGroup.of A + FreeAbelianGroup.of C) =
      -(FreeAbelianGroup.of B - FreeAbelianGroup.of A - FreeAbelianGroup.of C) := by
    simp [sub_eq_add_neg]; abel
  rw [this]
  exact (K0SESRelSubgroup R).neg_mem hmem

/-- The class of the zero module vanishes in `K^0`. -/
theorem GrothendieckGroupK0.classOf_zero (R : Type u) [Ring R] :
    GrothendieckGroupK0.classOf R (ModuleCat.of R PUnit.{u+1}) = 0 := by
  set a := GrothendieckGroupK0.classOf R (ModuleCat.of R PUnit.{u+1})
  have hses : a = a + a :=
    GrothendieckGroupK0.ses_relation R
      (0 : PUnit.{u+1} →ₗ[R] PUnit.{u+1}) (0 : PUnit.{u+1} →ₗ[R] PUnit.{u+1})
      (fun ⟨⟩ ⟨⟩ _ => rfl) (fun ⟨⟩ => ⟨PUnit.unit, rfl⟩) (by intro x; simp)
  rwa [eq_comm, add_eq_left] at hses

/-- Additivity on direct sums: `[M × N] = [M] + [N]` in `K^0`. -/
theorem GrothendieckGroupK0.classOf_prod (R : Type u) [Ring R]
    (M N : ModuleCat.{u} R) :
    GrothendieckGroupK0.classOf R (ModuleCat.of R (M × N)) =
      GrothendieckGroupK0.classOf R M + GrothendieckGroupK0.classOf R N :=
  GrothendieckGroupK0.ses_relation R
    (LinearMap.inl R M N) (LinearMap.snd R M N)
    LinearMap.inl_injective LinearMap.snd_surjective Function.Exact.inl_snd

/-- Isomorphic modules have the same class in `K^0`. -/
theorem GrothendieckGroupK0.classOf_iso (R : Type u) [Ring R]
    (M N : ModuleCat.{u} R) (e : M ≃ₗ[R] N) :
    GrothendieckGroupK0.classOf R M = GrothendieckGroupK0.classOf R N := by
  have h := GrothendieckGroupK0.ses_relation R (C := ModuleCat.of R PUnit.{u+1})
    (e : M →ₗ[R] N) (0 : N →ₗ[R] PUnit.{u+1})
    e.injective (fun ⟨⟩ => ⟨0, rfl⟩) (by intro x; simp)
  rw [GrothendieckGroupK0.classOf_zero R, add_zero] at h
  exact h.symm

/-- A function `φ` to an abelian group is SES-additive when `φ(B) = φ(A) + φ(C)` holds
for every short exact sequence. This is the universal property tested by `K^0`. -/
def IsSESAdditive (R : Type u) [Ring R] {G : Type*} [AddCommGroup G]
    (φ : ModuleCat.{u} R → G) : Prop :=
  ∀ (A B C : ModuleCat.{u} R) (f : A →ₗ[R] B) (g : B →ₗ[R] C),
    Function.Injective f → Function.Surjective g → Function.Exact f g →
    φ B = φ A + φ C

/-- If `φ` is SES-additive, then the lifted homomorphism vanishes on every SES-relation. -/
lemma K0SESRelSubgroup_le_ker (R : Type u) [Ring R] {G : Type*} [AddCommGroup G]
    (φ : ModuleCat.{u} R → G) (hφ : IsSESAdditive R φ) :
    K0SESRelSubgroup R ≤ (FreeAbelianGroup.lift φ).ker := by
  rw [K0SESRelSubgroup, AddSubgroup.closure_le]
  rintro _ ⟨A, B, C, f, g, hf, hg, hex, rfl⟩
  show (FreeAbelianGroup.lift φ) (FreeAbelianGroup.of B - FreeAbelianGroup.of A -
    FreeAbelianGroup.of C) = 0
  rw [map_sub, map_sub, FreeAbelianGroup.lift_apply_of,
    FreeAbelianGroup.lift_apply_of, FreeAbelianGroup.lift_apply_of,
    hφ A B C f g hf hg hex]
  abel

/-- Universal property: lift an SES-additive `φ : Mod → G` to a homomorphism `K^0(R) → G`. -/
def GrothendieckGroupK0.lift (R : Type u) [Ring R] {G : Type*} [AddCommGroup G]
    (φ : ModuleCat.{u} R → G) (hφ : IsSESAdditive R φ) :
    GrothendieckGroupK0 R →+ G :=
  QuotientAddGroup.lift (K0SESRelSubgroup R) (FreeAbelianGroup.lift φ)
    (K0SESRelSubgroup_le_ker R φ hφ)

/-- Computation: the universal lift sends `[M]` to `φ M`. -/
theorem GrothendieckGroupK0.lift_classOf (R : Type u) [Ring R] {G : Type*} [AddCommGroup G]
    (φ : ModuleCat.{u} R → G) (hφ : IsSESAdditive R φ) (M : ModuleCat.{u} R) :
    GrothendieckGroupK0.lift R φ hφ (GrothendieckGroupK0.classOf R M) = φ M := by
  unfold GrothendieckGroupK0.lift GrothendieckGroupK0.classOf
  rw [QuotientAddGroup.lift_mk', FreeAbelianGroup.lift_apply_of]

/-- Uniqueness in the universal property: two homomorphisms agreeing on all classes `[M]` are equal. -/
theorem GrothendieckGroupK0.lift_unique (R : Type u) [Ring R] {G : Type*} [AddCommGroup G]
    (ψ₁ ψ₂ : GrothendieckGroupK0 R →+ G)
    (h : ∀ M : ModuleCat.{u} R, ψ₁ (GrothendieckGroupK0.classOf R M) =
      ψ₂ (GrothendieckGroupK0.classOf R M)) :
    ψ₁ = ψ₂ := by

  have hsuff : ψ₁.comp (QuotientAddGroup.mk' (K0SESRelSubgroup R)) =
      ψ₂.comp (QuotientAddGroup.mk' (K0SESRelSubgroup R)) := by

    rw [← FreeAbelianGroup.lift.apply_symm_apply (ψ₁.comp (QuotientAddGroup.mk' _)),
        ← FreeAbelianGroup.lift.apply_symm_apply (ψ₂.comp (QuotientAddGroup.mk' _))]
    congr 1
    ext M
    have h1 := FreeAbelianGroup.lift_apply_of
      (FreeAbelianGroup.lift.symm (ψ₁.comp (QuotientAddGroup.mk' (K0SESRelSubgroup R)))) M
    have h2 := FreeAbelianGroup.lift_apply_of
      (FreeAbelianGroup.lift.symm (ψ₂.comp (QuotientAddGroup.mk' (K0SESRelSubgroup R)))) M
    rw [Equiv.apply_symm_apply] at h1 h2
    simp only [AddMonoidHom.comp_apply, QuotientAddGroup.mk'_apply] at h1 h2
    rw [← h1, ← h2]
    exact h M

  apply AddMonoidHom.ext
  intro x
  obtain ⟨y, rfl⟩ := QuotientAddGroup.mk'_surjective (K0SESRelSubgroup R) x
  exact DFunLike.congr_fun hsuff y

end DegreeAdditivity

end
