/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.AlgebraicGeometryI.code.Lec5BezoutPascal

namespace Formalization

open MvPolynomial

variable {k : Type*} [Field k] {n : Type*} [DecidableEq n]

/-- The maximal ideal of `k[x_i]_i` corresponding to a point `p`, generated by the
linear forms `X_i − p_i`. -/
noncomputable def maximalIdealAt (p : n → k) : Ideal (MvPolynomial n k) :=
  Ideal.span (Set.range fun i => X i - C (p i))

/-- Hypersurface multiplicity at a point (Def 12, Lec 5): the largest `m` such that the
defining polynomial `g` lies in the `m`-th power of the maximal ideal at `p` — i.e.,
the lowest nonzero homogeneous degree of `g` expanded about `p`. -/
noncomputable def hypersurfaceMultiplicityIdeal (g : MvPolynomial n k)
    (p : n → k) : ℕ∞ :=
  ⨆ (m : ℕ) (_ : g ∈ (maximalIdealAt p) ^ m), (m : ℕ∞)

end Formalization
