/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.AlgebraicGeometryI.code.KrullDimensionAffineSpace

noncomputable section
open Ideal

/-- Helper: a minimal prime over a principal ideal in a Noetherian ring has height at
most one (one half of Krull's principal ideal theorem). -/
theorem height_principal_le_one {R : Type*} [CommRing R] [IsNoetherianRing R]
    (f : R) (P : Ideal R) [P.IsPrime] (hP : P ∈ (Ideal.span ({f} : Set R)).minimalPrimes) :
    P.height ≤ 1 := by
  have : Submodule.IsPrincipal (Ideal.span ({f} : Set R)) := ⟨⟨f, by simp⟩⟩
  exact height_le_one_of_isPrincipal_of_mem_minimalPrimes _ P hP

/-- Generalized Krull height theorem: a minimal prime over a finitely generated ideal
has height at most the number of generators. -/
theorem height_le_card_of_minimalPrimes_span {R : Type*} [CommRing R] [IsNoetherianRing R]
    {P : Ideal R} {s : Finset R} (hP : P ∈ (Ideal.span (s : Set R)).minimalPrimes) :
    P.height ≤ s.card :=
  height_le_card_of_mem_minimalPrimes_span_finset hP

/-- Sharp converse: every prime in a Noetherian ring is a minimal prime over an ideal
generated by exactly `height P` elements. -/
theorem exists_generators_card_eq_height {R : Type*} [CommRing R] [IsNoetherianRing R]
    (P : Ideal R) [P.IsPrime] :
    ∃ s : Finset R, P ∈ (Ideal.span (s : Set R)).minimalPrimes ∧ ↑s.card = P.height :=
  Ideal.exists_finset_card_eq_height_of_isNoetherianRing P

/-- Quotienting by a nonzero-divisor `f` drops Krull dimension by at least one. -/
theorem dim_quotient_nonZeroDivisor_succ_le {R : Type*} [CommRing R]
    {f : R} (hf : f ∈ nonZeroDivisors R) :
    ringKrullDim (R ⧸ Ideal.span {f}) + 1 ≤ ringKrullDim R :=
  ringKrullDim_quotient_succ_le_of_nonZeroDivisor hf

/-- Upper bound on `height P` in terms of the Krull dimension of `R/(f)` for `f ∈ P`. -/
theorem height_le_dim_quotient_principal_succ {R : Type*} [CommRing R] [IsNoetherianRing R]
    {f : R} {P : Ideal R} [P.IsPrime] (hf : f ∈ P) :
    ↑P.height ≤ ringKrullDim (R ⧸ Ideal.span {f}) + 1 :=
  height_le_ringKrullDim_quotient_add_one hf

/-- Intersection dimension (Thm 8.1, Lec 8): the height of a prime `P` containing a
set `s` is bounded by `dim(R/(s)) + |s|`. Codimension of an irreducible component of
`X ∩ Y` is at most `codim X + codim Y`. -/
theorem height_le_dim_quotient_add_encard {R : Type*} [CommRing R] [IsNoetherianRing R]
    {P : Ideal R} [P.IsPrime] (s : Set R) (hs : s ⊆ ↑P) :
    ↑P.height ≤ ringKrullDim (R ⧸ Ideal.span s) + ↑s.encard :=
  Ideal.height_le_ringKrullDim_quotient_add_encard s hs

/-- Monotonicity: if `I ⊆ J` then `dim(R/J) ≤ dim(R/I)`. -/
theorem ringKrullDim_quotient_le_of_le {R : Type*} [CommRing R]
    {I J : Ideal R} (h : I ≤ J) :
    ringKrullDim (R ⧸ J) ≤ ringKrullDim (R ⧸ I) := by
  apply ringKrullDim_le_of_surjective (Ideal.Quotient.factor h)
  intro x
  obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective x
  exact ⟨Ideal.Quotient.mk I r, rfl⟩

end
