/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Basic

namespace K0Gen

/-- Axiomatic data for `K^0(Coh X)` of a smooth curve: a type of coherent sheaves with
rank/degree invariants additive in short exact sequences, including the distinguished
classes `O_X` (rank one, degree zero) and `O_x` (rank zero, degree one). -/
structure SmoothCurveK0Data where
  CohSheaf : Type
  rank : CohSheaf → ℕ
  deg : CohSheaf → ℤ
  SES : CohSheaf → CohSheaf → CohSheaf → Prop
  O_X : CohSheaf
  O_x : CohSheaf
  O_X_rank : rank O_X = 1
  O_X_deg : deg O_X = 0
  O_x_rank : rank O_x = 0
  O_x_deg : deg O_x = 1
  rank_additive : ∀ A B C, SES A B C → rank B = rank A + rank C
  deg_additive : ∀ A B C, SES A B C → deg B = deg A + deg C

/-- The subgroup of relations in the free abelian group generated by coherent sheaves
imposed by short exact sequences `0 → A → B → C → 0`, namely `[A] + [C] − [B]`. -/
def sesRelations (X : SmoothCurveK0Data) : AddSubgroup (FreeAbelianGroup X.CohSheaf) :=
  AddSubgroup.closure
    { r | ∃ A B C, X.SES A B C ∧
        r = FreeAbelianGroup.of A + FreeAbelianGroup.of C - FreeAbelianGroup.of B }

/-- The Grothendieck group `K^0(Coh X)`: free abelian group on coherent sheaves modulo
short-exact-sequence relations. -/
abbrev K0Coh (X : SmoothCurveK0Data) : Type :=
  FreeAbelianGroup X.CohSheaf ⧸ sesRelations X

/-- The class `[F] ∈ K^0(Coh X)` of a coherent sheaf `F`. -/
def K0Coh.classOf (X : SmoothCurveK0Data) (F : X.CohSheaf) : K0Coh X :=
  QuotientAddGroup.mk' (sesRelations X) (FreeAbelianGroup.of F)

/-- The map `(r, d) ↦ r·[O_X] + d·[O_x]` from `ℤ × ℤ` into `K^0(Coh X)`. -/
def rankDegToK0 (X : SmoothCurveK0Data) : ℤ × ℤ →+ K0Coh X where
  toFun := fun ⟨r, d⟩ => r • K0Coh.classOf X X.O_X + d • K0Coh.classOf X X.O_x
  map_zero' := by simp
  map_add' := by intro ⟨r₁, d₁⟩ ⟨r₂, d₂⟩; simp only [add_smul]; ac_rfl

/-- Lemma 35 (Lec 24): on a smooth curve, `O_X` and `O_x` generate `K^0(Coh X)`; i.e.
the rank-degree map `ℤ × ℤ → K^0(Coh X)` is surjective. -/
theorem goal_179_lemma35_proved (X : SmoothCurveK0Data) :
    Function.Surjective (rankDegToK0 X) := by sorry

end K0Gen
