/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Algebra.Category.ModuleCat.Sheaf.Quasicoherent
import Mathlib.AlgebraicGeometry.Modules.Sheaf
import Mathlib.AlgebraicGeometry.Modules.Tilde
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.RingTheory.Noetherian.Basic

open AlgebraicGeometry CategoryTheory

namespace SheafOfModules

variable {C : Type*} [Category C] {J : GrothendieckTopology C} {R : Sheaf J RingCat}
  [∀ X, (J.over X).HasSheafCompose (CategoryTheory.forget₂ RingCat AddCommGrpCat)]
  [∀ X, HasWeakSheafify (J.over X) AddCommGrpCat]
  [∀ X, (J.over X).WEqualsLocallyBijective AddCommGrpCat]

/-- A sheaf of modules `M` is coherent if it is quasi-coherent and of finite type
(locally generated by finitely many sections). -/
class IsCoherent (M : SheafOfModules.{u} R) : Prop where
  isQuasicoherent : M.IsQuasicoherent
  isFiniteType : M.IsFiniteType

attribute [instance] IsCoherent.isQuasicoherent IsCoherent.isFiniteType

instance (M : SheafOfModules.{u} R) [M.IsFinitePresentation] : M.IsCoherent where
  isQuasicoherent := inferInstance
  isFiniteType := inferInstance

end SheafOfModules

/-- Algebraic counterpart: an `R`-module `M` is "coherent" in our sense iff it is
finitely generated as an `R`-module. -/
def IsCoherentModule (R : Type*) (M : Type*) [CommRing R] [AddCommGroup M] [Module R M] :
    Prop :=
  Module.Finite R M

/-- Unfolds the definition: `IsCoherentModule R M` is by definition `Module.Finite R M`. -/
theorem isCoherentModule_iff_finite {R : Type*} [CommRing R]
    (M : Type*) [AddCommGroup M] [Module R M] :
    IsCoherentModule R M ↔ Module.Finite R M :=
  Iff.rfl

/-- Over a Noetherian ring, every finitely generated module is finitely presented. -/
theorem fg_noetherian_finitePresentation {R : Type*} [CommRing R] [IsNoetherianRing R]
    (M : Type*) [AddCommGroup M] [Module R M] [Module.Finite R M] :
    Module.FinitePresentation R M :=
  Module.finitePresentation_of_finite R M

/-- Over a Noetherian ring, coherent (= finitely generated) and finitely presented
coincide. -/
theorem isCoherentModule_iff_finitePresentation
    {R : Type*} [CommRing R] [IsNoetherianRing R]
    (M : Type*) [AddCommGroup M] [Module R M] :
    IsCoherentModule R M ↔ Module.FinitePresentation R M :=
  (Module.finitePresentation_iff_finite R M).symm
