/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.AlgebraicGeometryI.code.PicardProjective
import Atlas.AlgebraicGeometryI.code.DivisorsPicard
import Atlas.AlgebraicGeometryI.code.PrincipalDivisorDegree
import Atlas.AlgebraicGeometryI.code.BezoutTheorem
import Atlas.AlgebraicGeometryI.code.LinearEquivDivisors
import Atlas.AlgebraicGeometryI.code.PowerSeriesUFD
import Atlas.AlgebraicGeometryI.code.PicardGroup
import Atlas.AlgebraicGeometryI.code.SmoothCurveDivisors

set_option maxHeartbeats 1600000

noncomputable section

namespace Lec15PicardDivisorClass

open Module Polynomial LinearEquivDivisors


/-- The graded Picard group of `Pⁿ_k` is canonically isomorphic to `ℤ`, generated by
the twisting sheaf `O(1)`. -/
def picard_projective_iso_int (k : Type*) [Field k] (n : ℕ) :
    PicardProjective.GradedPicardGroup (Fin (n + 1)) k ≃+ ℤ :=
  PicardProjective.gradedPicardGroup_equiv_int k n

/-- Every element of `Pic(Pⁿ_k)` is a power `O(d)` of the twisting sheaf for some
integer `d`. -/
theorem picard_projective_generated_by_O1 (k : Type*) [Field k] (n : ℕ)
    (L : PicardProjective.GradedPicardGroup (Fin (n + 1)) k) :
    ∃ d : ℤ, L = PicardProjective.twistingSheafPow n k d :=
  PicardProjective.picardGroup_generated_by_O1 k n L

/-- Under the isomorphism `Pic(Pⁿ_k) ≃ ℤ`, the twisting sheaf `O(1)` corresponds to `1`. -/
theorem degree_O1_eq_one (k : Type*) [Field k] (n : ℕ) :
    (PicardProjective.gradedPicardGroup_equiv_int k n)
      (PicardProjective.twistingSheaf n k) = 1 :=
  PicardProjective.degree_twistingSheaf k n


/-- Proposition 23a (Lec 15): the power-series ring `k[[x₁,…,xₙ]]` over a field is a
UFD. -/
theorem prop23a_powerSeries_ufd (k : Type*) [Field k] (n : ℕ) :
    UniqueFactorizationMonoid (MvPowerSeries (Fin n) k) :=
  PowerSeriesUFD.mvPowerSeries_isUFD k n

/-- Proposition 23b (Lec 15): if the `𝔪`-adic completion of a Noetherian local domain
`A` is a UFD, then `A` itself is a UFD. -/
theorem prop23b_noetherian_local_completion_ufd
    (A : Type*) [CommRing A] [IsDomain A] [IsLocalRing A] [IsNoetherianRing A]
    (hcompl : UniqueFactorizationMonoid
      (AdicCompletion (IsLocalRing.maximalIdeal A) A)) :
    UniqueFactorizationMonoid A :=
  PowerSeriesUFD.ufd_of_completion_ufd A hcompl


/-- Linear equivalence of Weil divisors modulo a chosen subgroup `P` of principal
divisors; abbreviation forwarding to `WeilLinearlyEquivalent`. -/
abbrev weilLinearlyEquivalent' {Y : Type*}
    (P : PrincipalDivisors Y)
    (D₁ D₂ : DivisorsPicard.WeilDivisorGroup Y) : Prop :=
  WeilLinearlyEquivalent P D₁ D₂

/-- Dimension `ℓ(D)` of a linear system: the `k`-vector space dimension of `V`. -/
def lD_dim (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V] : ℕ :=
  Module.finrank k V

/-- The dimension `ℓ(D)` is a non-negative natural number. -/
theorem lD_dim_nonneg (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V] :
    0 ≤ lD_dim k V := Nat.zero_le _

/-- `ℓ(D) = 0` iff the underlying `k`-vector space has dimension `0`, i.e. is trivial. -/
theorem lD_dim_eq_zero_iff (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V] :
    lD_dim k V = 0 ↔ Module.finrank k V = 0 := by
  rfl


/-- Degree of a Weil divisor; abbreviation for `WeilDivisor.degree`. -/
abbrev divisorDegree {Y : Type*} (D : DivisorsPicard.WeilDivisorGroup Y) : ℤ :=
  WeilDivisor.degree D

/-- The zero divisor has degree zero. -/
theorem divisorDegree_zero {Y : Type*} :
    divisorDegree (0 : DivisorsPicard.WeilDivisorGroup Y) = 0 :=
  WeilDivisor.degree_zero

/-- Degree is additive on Weil divisors. -/
theorem divisorDegree_add {Y : Type*} [DecidableEq Y]
    (D₁ D₂ : DivisorsPicard.WeilDivisorGroup Y) :
    divisorDegree (D₁ + D₂) = divisorDegree D₁ + divisorDegree D₂ :=
  WeilDivisor.degree_add D₁ D₂

/-- If every principal divisor in `P` has degree zero, then the degree is an invariant
of the linear equivalence class of a divisor. -/
theorem divisorDegree_eq_of_linearlyEquiv {Y : Type*} [DecidableEq Y]
    {P : PrincipalDivisors Y}
    (hP : ∀ D ∈ P, WeilDivisor.degree D = 0)
    {D₁ D₂ : DivisorsPicard.WeilDivisorGroup Y}
    (h : WeilLinearlyEquivalent P D₁ D₂) :
    divisorDegree D₁ = divisorDegree D₂ :=
  WeilDivisor.degree_eq_of_linearlyEquiv hP h


/-- Smooth-curve case: the additive homomorphism from invertible fractional ideals to
the free abelian group on height-one primes (i.e. closed points), realizing a fractional
ideal as a finite formal sum of points. -/
def goal119_weilDivisor_sum_of_points
    (R : Type*) [CommRing R] [IsDomain R] [IsDedekindDomain R]
    (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K] :
    Additive (FractionalIdeal (nonZeroDivisors R) K)ˣ →+
      (IsDedekindDomain.HeightOneSpectrum R →₀ ℤ) :=
  SmoothCurveDivisors.weilDivisor_sum_of_points R K

/-- Upgraded version of `goal119_weilDivisor_sum_of_points`: this map is in fact an
isomorphism of abelian groups. -/
def goal119_weilDivisor_sum_of_points_equiv
    (R : Type*) [CommRing R] [IsDomain R] [IsDedekindDomain R]
    (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K] :
    Additive (FractionalIdeal (nonZeroDivisors R) K)ˣ ≃+
      (IsDedekindDomain.HeightOneSpectrum R →₀ ℤ) :=
  SmoothCurveDivisors.weilDivisor_sum_of_points_equiv R K

/-- For a Dedekind domain `R`, the divisor class group `Cl(R)` is isomorphic to the
Picard group `Pic(R)` of invertible sheaves. -/
def goal119_weilDivisorClassGroup_iso_pic
    (R : Type*) [CommRing R] [IsDomain R] [IsDedekindDomain R] :
    ClassGroup R ≃* CommRing.Pic R :=
  SmoothCurveDivisors.weilDivisorClassGroup_iso_pic R


/-- Bézout's theorem (algebraic form): for `g` monic irreducible in `k[x][y]` defining
a smooth curve and `f ∈ k[x]` non-vanishing on its image, the intersection multiplicity
is `deg(g) · deg(f)`. -/
theorem bezout_thm (k : Type*) [Field k]
    (g : Polynomial (Polynomial k))
    (hg_monic : g.Monic)
    (hg_irred : Irreducible g)
    (f : Polynomial k)
    (hf : algebraMap (Polynomial k) (AdjoinRoot g) f ≠ 0) :
    Module.finrank k (AdjoinRoot g ⧸
      Ideal.span {algebraMap (Polynomial k) (AdjoinRoot g) f}) =
      g.natDegree * f.natDegree :=
  bezout_algebraic_irreducible k g hg_monic hg_irred f hf

/-- Simplest case of Bézout: two distinct lines `x = 0` and `y = 0` in `𝔸²_k` meet in
a single reduced point. -/
theorem line_line_bezout (k : Type*) [Field k] :
    Module.finrank k (Polynomial (Polynomial k) ⧸
      Ideal.span {Polynomial.C (Polynomial.X : Polynomial k),
                  (Polynomial.X : Polynomial (Polynomial k))}) = 1 :=
  line_line_intersection_dim k


/-- Proposition 24 (Lec 15): on a complete curve, every principal divisor has degree
zero. -/
theorem prop24_principal_divisor_degree_zero (k : Type*) [Field k]
    {S : Type*} [CommRing S] [IsDomain S]
    {ι : Type*} [Fintype ι]
    [Algebra (Polynomial k) S] [Algebra k S] [IsScalarTower k (Polynomial k) S]
    [IsCompleteCurveAlg k S]
    (b : Basis ι (Polynomial k) S)
    {p q : Polynomial k} (hp : p ≠ 0) (hq : q ≠ 0)
    (hpd : IsPrincipalDivisorData k S p q) :
    PrincipalDivisorDegZero.principalDivisorDeg k S
      (Ideal.span {algebraMap (Polynomial k) S p})
      (Ideal.span {algebraMap (Polynomial k) S q}) = 0 :=
  PrincipalDivisorDegZero.principal_divisor_deg_zero k b hp hq hpd


/-- Degree formula (Prop 24): `deg ((p) - (q)) = card(ι) · (deg p - deg q)` where
`card(ι)` is the rank of the algebra `S` over `k[x]`. -/
theorem prop24_degree_formula (k : Type*) [Field k]
    {S : Type*} [CommRing S] [IsDomain S]
    {ι : Type*} [Fintype ι]
    [Algebra (Polynomial k) S] [Algebra k S] [IsScalarTower k (Polynomial k) S]
    (b : Basis ι (Polynomial k) S)
    {p q : Polynomial k} (hp : p ≠ 0) (hq : q ≠ 0) :
    PrincipalDivisorDegZero.principalDivisorDeg k S
      (Ideal.span {algebraMap (Polynomial k) S p})
      (Ideal.span {algebraMap (Polynomial k) S q}) =
    (Fintype.card ι : ℤ) * ((p.natDegree : ℤ) - (q.natDegree : ℤ)) :=
  PrincipalDivisorDegZero.principalDivisorDeg_eq_rank_mul_degDiff k b hp hq

/-- Specialization of the degree formula to the affine line: `deg ((p) - (q)) =
deg(p) - deg(q)` for `p, q ∈ k[x]`. -/
theorem prop24_affine_formula (k : Type*) [Field k]
    (p q : Polynomial k) :
    PrincipalDivisorDegZero.principalDivisorDeg k (Polynomial k)
      (Ideal.span {p}) (Ideal.span {q}) =
      (p.natDegree : ℤ) - (q.natDegree : ℤ) :=
  PrincipalDivisorDegZero.principalDivisorDeg_affine_eq k p q


/-- Proposition 25 (Lec 15): principal divisor associated to a translation
`(x - c₁) - (x - c₂)` has degree zero on a curve covered by `k[x]`. -/
theorem prop25_principal_divisor_degree_zero_curve (k : Type*) [Field k]
    {S : Type*} [CommRing S] [IsDomain S]
    {ι : Type*} [Fintype ι]
    [Algebra (Polynomial k) S] [Algebra k S] [IsScalarTower k (Polynomial k) S]
    (b : Basis ι (Polynomial k) S) (c₁ c₂ : k) :
    PrincipalDivisorDegZero.principalDivisorDeg k S
      (Ideal.span {algebraMap (Polynomial k) S (Polynomial.X - Polynomial.C c₁)})
      (Ideal.span {algebraMap (Polynomial k) S (Polynomial.X - Polynomial.C c₂)}) = 0 :=
  PrincipalDivisorDegZero.principal_divisor_deg_zero_linear k b c₁ c₂

/-- The fiber `S / (x - c)` over a closed point `x = c` has `k`-dimension equal to the
rank of `S` as a `k[x]`-module. -/
theorem prop25_fiber_dimension_eq_rank (k : Type*) [Field k]
    {S : Type*} [CommRing S] [IsDomain S]
    {ι : Type*} [Fintype ι]
    [Algebra (Polynomial k) S] [Algebra k S] [IsScalarTower k (Polynomial k) S]
    (b : Basis ι (Polynomial k) S)
    (c : k) :
    Module.finrank k
      (S ⧸ (Ideal.span {algebraMap (Polynomial k) S (Polynomial.X - Polynomial.C c)})) =
    Fintype.card ι :=
  PrincipalDivisorDegZero.fiber_dimension_linear_eq_rank k b c

/-- Constancy of the fiber dimension: dim_k(S / (x - c)) is independent of `c`. -/
theorem prop25_fiber_dimension_constant (k : Type*) [Field k]
    {S : Type*} [CommRing S] [IsDomain S]
    {ι : Type*} [Fintype ι]
    [Algebra (Polynomial k) S] [Algebra k S] [IsScalarTower k (Polynomial k) S]
    (b : Basis ι (Polynomial k) S)
    (c₁ c₂ : k) :
    Module.finrank k
      (S ⧸ (Ideal.span {algebraMap (Polynomial k) S (Polynomial.X - Polynomial.C c₁)})) =
    Module.finrank k
      (S ⧸ (Ideal.span {algebraMap (Polynomial k) S (Polynomial.X - Polynomial.C c₂)})) :=
  PrincipalDivisorDegZero.fiber_dimension_linear_constant k b c₁ c₂

/-- General fiber dimension formula: dim_k(S / (p)) = rank(S over k[x]) · deg(p). -/
theorem prop25_fiber_dimension_formula (k : Type*) [Field k]
    {S : Type*} [CommRing S] [IsDomain S]
    {ι : Type*} [Fintype ι]
    [Algebra (Polynomial k) S] [Algebra k S] [IsScalarTower k (Polynomial k) S]
    (b : Basis ι (Polynomial k) S)
    {p : Polynomial k} (hp : p ≠ 0) :
    Module.finrank k (S ⧸ Ideal.span {algebraMap (Polynomial k) S p}) =
      Fintype.card ι * p.natDegree :=
  PrincipalDivisorDegZero.fiber_dimension_eq_rank_mul_natDegree k b hp


/-- Projective dimension `dim |D| = ℓ(D) - 1` of the complete linear system
associated to a divisor `D`, as an integer (so that `dim ∅ = -1`). -/
def completeLinearSystemProjDim (k : Type*) [Field k]
    (V : Type*) [AddCommGroup V] [Module k V] : ℤ :=
  (Module.finrank k V : ℤ) - 1

/-- Unfolding: `dim |D| = ℓ(D) - 1` in the integer expression. -/
theorem completeLinearSystemProjDim_eq (k : Type*) [Field k]
    (V : Type*) [AddCommGroup V] [Module k V] :
    completeLinearSystemProjDim k V = (lD_dim k V : ℤ) - 1 := by
  rfl

/-- If `ℓ(D) ≥ 1` then the complete linear system `|D|` has non-negative projective
dimension (in particular is non-empty as a projective space). -/
theorem completeLinearSystem_nonempty_of_lD_pos (k : Type*) [Field k]
    (V : Type*) [AddCommGroup V] [Module k V]
    (h : 1 ≤ lD_dim k V) : completeLinearSystemProjDim k V ≥ 0 := by
  unfold completeLinearSystemProjDim lD_dim at *
  omega

end Lec15PicardDivisorClass

end
