/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.Ideal.Cotangent
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.GradedAlgebra.Basic
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.ReesAlgebra
import Mathlib.AlgebraicGeometry.Scheme

open Polynomial

namespace Lec20TangentCone

universe u

variable {R : Type u} [CommRing R]

/-- The `R`-algebra homomorphism `R[X] → R[X]` sending `X ↦ c · X`, used to realise the
scalar `R*`-action on the Rees algebra and hence on the tangent cone. -/
noncomputable def scaleAlgHom (c : R) : R[X] →ₐ[R] R[X] :=
  aeval (C c * X)

/-- Scaling by `1` on `R[X]` is the identity homomorphism. -/
lemma scaleAlgHom_one : scaleAlgHom (1 : R) = AlgHom.id R R[X] := by
  ext; unfold scaleAlgHom; simp [map_one, one_mul]

/-- Composition of scaling homomorphisms corresponds to multiplication: scaling by `c₁`
after scaling by `c₂` equals scaling by `c₁ * c₂`. -/
lemma scaleAlgHom_comp (c₁ c₂ : R) :
    (scaleAlgHom c₁).comp (scaleAlgHom c₂) = scaleAlgHom (c₁ * c₂) := by
  ext
  unfold scaleAlgHom
  simp only [AlgHom.comp_apply, aeval_X]
  simp only [aeval_def, eval₂_mul, eval₂_C, eval₂_X, Polynomial.algebraMap_eq]
  rw [← mul_assoc, ← C_mul, mul_comm c₂ c₁]

/-- The scaling endomorphism `scaleAlgHom c` preserves the Rees subalgebra of `R[X]`
associated to an ideal `I`. -/
lemma scaleAlgHom_mem_reesAlgebra (I : Ideal R) (c : R)
    (f : R[X]) (hf : f ∈ reesAlgebra I) :
    (scaleAlgHom c : R[X] →ₐ[R] R[X]) f ∈ reesAlgebra I := by
  have h : (reesAlgebra I).map (scaleAlgHom c) ≤ reesAlgebra I := by
    rw [← adjoin_monomial_eq_reesAlgebra, ← Algebra.adjoin_image R (scaleAlgHom c)]
    apply Algebra.adjoin_le
    intro x hx
    rw [Set.mem_image] at hx
    obtain ⟨y, hy, rfl⟩ := hx
    simp only [SetLike.mem_coe, Submodule.mem_map] at hy
    obtain ⟨r, hr, rfl⟩ := hy
    rw [adjoin_monomial_eq_reesAlgebra, SetLike.mem_coe]
    unfold scaleAlgHom
    simp only [aeval_def, eval₂_monomial, Polynomial.algebraMap_eq, pow_one]
    rw [← mul_assoc, ← map_mul, C_mul_X_eq_monomial, reesAlgebra.monomial_mem, pow_one]
    exact I.mul_mem_right c hr
  exact h ⟨f, hf, rfl⟩

/-- The ring endomorphism of the Rees algebra `reesAlgebra I` induced by scaling `X ↦ c · X`. -/
noncomputable def scaleOnRees (I : Ideal R) (c : R) : reesAlgebra I →+* reesAlgebra I where
  toFun f := ⟨scaleAlgHom c f.val, scaleAlgHom_mem_reesAlgebra I c f.val f.prop⟩
  map_one' := Subtype.ext (map_one (scaleAlgHom c))
  map_mul' x y := Subtype.ext (map_mul (scaleAlgHom c) x.val y.val)
  map_zero' := Subtype.ext (map_zero (scaleAlgHom c))
  map_add' x y := Subtype.ext (map_add (scaleAlgHom c) x.val y.val)

/-- The scaling endomorphism of the Rees algebra fixes the image of `R` under the structure map. -/
lemma scaleOnRees_algebraMap (I : Ideal R) (c : R) (r : R) :
    scaleOnRees I c (algebraMap R (reesAlgebra I) r) = algebraMap R (reesAlgebra I) r :=
  Subtype.ext ((scaleAlgHom c).commutes r)

/-- The ideal of the Rees algebra obtained by extending an ideal `𝔪 ⊆ R` along the
structure map; its quotient defines the associated graded ring. -/
noncomputable def reesIdealFromBase (𝔪 : Ideal R) : Ideal (reesAlgebra 𝔪) :=
  Ideal.map (algebraMap R (reesAlgebra 𝔪)) 𝔪

/-- The extended ideal `reesIdealFromBase I` is preserved (in the comap sense) by every
scaling endomorphism of the Rees algebra. -/
lemma reesIdealFromBase_le_comap_scaleOnRees (I : Ideal R) (c : R) :
    reesIdealFromBase I ≤ (reesIdealFromBase I).comap (scaleOnRees I c) := by
  unfold reesIdealFromBase
  rw [Ideal.map_le_iff_le_comap]
  intro r hr
  show scaleOnRees I c (algebraMap R (reesAlgebra I) r) ∈
    Ideal.map (algebraMap R (reesAlgebra I)) I
  rw [scaleOnRees_algebraMap]
  exact Ideal.mem_map_of_mem _ hr

/-- The associated graded ring `gr_𝔪(R) = ⨁ 𝔪^n/𝔪^{n+1}`, realised as the quotient
of the Rees algebra by the ideal generated by `𝔪`. -/
def assocGradedRing (𝔪 : Ideal R) : Type _ :=
  (reesAlgebra 𝔪) ⧸ reesIdealFromBase 𝔪

/-- The commutative ring structure on the associated graded ring, inherited from
the quotient construction. -/
noncomputable instance assocGradedRing.commRing (𝔪 : Ideal R) :
    CommRing (assocGradedRing 𝔪) :=
  Ideal.Quotient.commRing (reesIdealFromBase 𝔪)

/-- The induced ring endomorphism of the associated graded ring `gr_I(R)` coming from
the `R*`-scaling action on the Rees algebra. -/
noncomputable def scaleOnGraded (I : Ideal R) (c : R) :
    assocGradedRing I →+* assocGradedRing I :=
  Ideal.Quotient.lift (reesIdealFromBase I)
    ((Ideal.Quotient.mk (reesIdealFromBase I)).comp (scaleOnRees I c))
    (fun x hx => by
      show Ideal.Quotient.mk _ (scaleOnRees I c x) = 0
      rw [Ideal.Quotient.eq_zero_iff_mem]
      exact reesIdealFromBase_le_comap_scaleOnRees I c hx)

/-- The tangent cone is a cone: scaling by `1` acts as the identity on the associated graded ring. -/
theorem tangentCone_isCone_identity (I : Ideal R) :
    scaleOnGraded I (1 : R) = RingHom.id (assocGradedRing I) := by
  apply Ideal.Quotient.ringHom_ext
  ext x
  simp only [scaleOnGraded, RingHom.comp_apply, Ideal.Quotient.lift_mk]
  show Ideal.Quotient.mk _ (scaleOnRees I 1 x) = Ideal.Quotient.mk _ x
  congr 1
  apply Subtype.ext
  show scaleAlgHom 1 x.val = x.val
  rw [show scaleAlgHom (1 : R) = AlgHom.id R R[X] from scaleAlgHom_one]
  simp

/-- The tangent cone is a cone: the scaling action is multiplicative,
`(c₁ * c₂)·_ = c₁ ·(c₂ ·_)` on `gr_I(R)`. -/
theorem tangentCone_isCone_compose (I : Ideal R) (c₁ c₂ : R) :
    scaleOnGraded I (c₁ * c₂) = (scaleOnGraded I c₁).comp (scaleOnGraded I c₂) := by
  apply Ideal.Quotient.ringHom_ext
  ext x
  simp only [scaleOnGraded, RingHom.comp_apply, Ideal.Quotient.lift_mk]
  show Ideal.Quotient.mk _ (scaleOnRees I (c₁ * c₂) x) =
    Ideal.Quotient.mk _ (scaleOnRees I c₁ (scaleOnRees I c₂ x))
  congr 1
  apply Subtype.ext
  show scaleAlgHom (c₁ * c₂) x.val = scaleAlgHom c₁ (scaleAlgHom c₂ x.val)
  rw [← AlgHom.comp_apply, ← scaleAlgHom_comp]

/-- The canonical ring homomorphism `R → gr_𝔪(R)`, factoring through the structure map
into the Rees algebra and the quotient projection. -/
noncomputable def ringHomToAssocGraded (𝔪 : Ideal R) : R →+* assocGradedRing 𝔪 :=
  (Ideal.Quotient.mk (reesIdealFromBase 𝔪)).comp (algebraMap R (reesAlgebra 𝔪))

/-- The tangent cone sits over the closed point: the ideal `𝔪` lies in the kernel of
`R → gr_𝔪(R)`, so the map factors through the residue field `R⧸𝔪`. -/
theorem tangentCone_over_closedPoint (𝔪 : Ideal R) :
    𝔪 ≤ RingHom.ker (ringHomToAssocGraded 𝔪) := by
  intro r hr
  rw [RingHom.mem_ker]
  show (Ideal.Quotient.mk (reesIdealFromBase 𝔪)) ((algebraMap R (reesAlgebra 𝔪)) r) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.mem_map_of_mem _ hr

/-- The tangent cone `C_x X := Spec(gr_𝔪 O_{X,x})` of `X = Spec R` at the point cut out by `𝔪`. -/
noncomputable def tangentCone (𝔪 : Ideal R) : AlgebraicGeometry.Scheme :=
  AlgebraicGeometry.Spec (.of (assocGradedRing 𝔪))

/-- Definition 38: the tangent cone of `Spec R` at a point with maximal ideal `𝔪`,
defined as `Spec(gr_𝔪(R))`. -/
noncomputable abbrev definition_38_tangentCone (𝔪 : Ideal R) : AlgebraicGeometry.Scheme :=
  tangentCone 𝔪

/-- The structure morphism `C_x X → X = Spec R` from the tangent cone to the ambient scheme. -/
noncomputable def tangentConeMap (𝔪 : Ideal R) :
    tangentCone 𝔪 ⟶ AlgebraicGeometry.Spec (.of R) :=
  AlgebraicGeometry.Spec.map (CommRingCat.ofHom (ringHomToAssocGraded 𝔪))

/-- The associated graded ring is an algebra over the residue field `R ⧸ 𝔪`. -/
noncomputable instance assocGradedRing.algebraQuot (𝔪 : Ideal R) :
    Algebra (R ⧸ 𝔪) (assocGradedRing 𝔪) := by
  unfold assocGradedRing
  apply Ideal.Quotient.algebraQuotientOfLEComap
  intro r hr
  show r ∈ (reesIdealFromBase 𝔪).comap (algebraMap R (reesAlgebra 𝔪))
  rw [Ideal.mem_comap]
  exact Ideal.mem_map_of_mem _ hr

/-- The associated graded ring is an algebra over the Rees algebra via the quotient map. -/
noncomputable instance assocGradedRing.algebraRees (𝔪 : Ideal R) :
    Algebra (↥(reesAlgebra 𝔪)) (assocGradedRing 𝔪) := by
  unfold assocGradedRing; exact Ideal.Quotient.algebra _

/-- Algebra isomorphism realising the associated graded ring as the exceptional fiber
of the blow-up: `gr_𝔪(R) ≃ reesAlgebra 𝔪 ⊗_R (R⧸𝔪)`. -/
noncomputable def assocGradedRing_equivExceptionalFiber (𝔪 : Ideal R) :
    assocGradedRing 𝔪 ≃ₐ[↥(reesAlgebra 𝔪)] TensorProduct R (↥(reesAlgebra 𝔪)) (R ⧸ 𝔪) := by
  unfold assocGradedRing
  exact Algebra.TensorProduct.quotIdealMapEquivTensorQuot (↥(reesAlgebra 𝔪)) 𝔪

/-- The ring isomorphism underlying the algebra equivalence
`gr_𝔪(R) ≃ reesAlgebra 𝔪 ⊗_R (R⧸𝔪)`. -/
noncomputable def assocGradedRing_ringEquivExceptionalFiber (𝔪 : Ideal R) :
    assocGradedRing 𝔪 ≃+* TensorProduct R (↥(reesAlgebra 𝔪)) (R ⧸ 𝔪) :=
  (assocGradedRing_equivExceptionalFiber 𝔪).toRingEquiv

/-- The exceptional fiber of the blow-up `Bl_𝔪(Spec R) → Spec R` above the closed point,
realised as `Spec(reesAlgebra 𝔪 ⊗_R (R⧸𝔪))`. -/
noncomputable def exceptionalFiberScheme (𝔪 : Ideal R) : AlgebraicGeometry.Scheme :=
  AlgebraicGeometry.Spec (.of (TensorProduct R (↥(reesAlgebra 𝔪)) (R ⧸ 𝔪)))

/-- Scheme-theoretic isomorphism identifying the tangent cone with the exceptional fiber
of the blow-up. -/
noncomputable def tangentCone_isoExceptionalFiber (𝔪 : Ideal R) :
    tangentCone 𝔪 ≅ exceptionalFiberScheme 𝔪 := by
  unfold tangentCone exceptionalFiberScheme
  exact AlgebraicGeometry.Scheme.Spec.mapIso
    (assocGradedRing_ringEquivExceptionalFiber 𝔪).symm.toCommRingCatIso.op

/-- The `n`-th graded piece `𝔪^n / 𝔪^{n+1}` of the associated graded ring `gr_𝔪(R)`. -/
def assocGradedPiece (𝔪 : Ideal R) (n : ℕ) : Type _ :=
  ↥(𝔪 ^ n) ⧸ (𝔪 • ⊤ : Submodule R ↥(𝔪 ^ n))

/-- The additive group structure on the graded piece `𝔪^n / 𝔪^{n+1}`. -/
instance assocGradedPiece.addCommGroup (𝔪 : Ideal R) (n : ℕ) :
    AddCommGroup (assocGradedPiece 𝔪 n) :=
  inferInstanceAs (AddCommGroup (↥(𝔪 ^ n) ⧸ _))

/-- The `R`-module structure on the graded piece `𝔪^n / 𝔪^{n+1}`. -/
instance assocGradedPiece.module (𝔪 : Ideal R) (n : ℕ) :
    Module R (assocGradedPiece 𝔪 n) :=
  inferInstanceAs (Module R (↥(𝔪 ^ n) ⧸ _))

/-- The quotient ring homomorphism from the Rees algebra onto the associated graded ring. -/
noncomputable def reesToAssocGraded (𝔪 : Ideal R) :
    (reesAlgebra 𝔪) →+* assocGradedRing 𝔪 :=
  Ideal.Quotient.mk (reesIdealFromBase 𝔪)

/-- The projection `reesAlgebra 𝔪 → gr_𝔪(R)` is surjective. -/
theorem reesToAssocGraded_surjective (𝔪 : Ideal R) :
    Function.Surjective (reesToAssocGraded 𝔪) :=
  Ideal.Quotient.mk_surjective

/-- Proposition 38 (smooth case): At a smooth (regular) point, the associated graded ring
is isomorphic to the symmetric algebra on the cotangent space, so the tangent cone is the
linear tangent space `Sym(T*_x X)`. -/
theorem proposition_38_smooth_graded_iso_symmetric
    (R : Type u) [CommRing R] [IsLocalRing R] [IsRegularLocalRing R] :
    Nonempty (assocGradedRing (IsLocalRing.maximalIdeal R) ≃+*
      SymmetricAlgebra (IsLocalRing.ResidueField R) (IsLocalRing.CotangentSpace R)) := by sorry

/-- Proposition 38: The tangent cone of `Spec R` at `𝔪` is the exceptional fiber of the
blow-up, and at a regular (smooth) local ring it coincides with `Sym(T*_x X)`. -/
theorem proposition_38 (𝔪 : Ideal R) :

    Nonempty (tangentCone 𝔪 ≅ exceptionalFiberScheme 𝔪) ∧

    ∀ (S : Type u) [CommRing S] [IsLocalRing S] [IsRegularLocalRing S],
      Nonempty (assocGradedRing (IsLocalRing.maximalIdeal S) ≃+*
        SymmetricAlgebra (IsLocalRing.ResidueField S) (IsLocalRing.CotangentSpace S)) :=
  ⟨⟨tangentCone_isoExceptionalFiber 𝔪⟩,
   fun S _ _ _ => proposition_38_smooth_graded_iso_symmetric S⟩

section TangentSpace

variable (R : Type u) [CommRing R] [IsLocalRing R]

/-- The coordinate ring of the linear tangent space at the closed point of a local ring,
namely the symmetric algebra on the cotangent space. -/
abbrev tangentSpaceRing :=
  SymmetricAlgebra (IsLocalRing.ResidueField R) (IsLocalRing.CotangentSpace R)

/-- The (Zariski) tangent space scheme `Spec(Sym(T*_x X))` at the closed point. -/
noncomputable def tangentSpaceScheme : AlgebraicGeometry.Scheme :=
  AlgebraicGeometry.Spec (.of (tangentSpaceRing R))

/-- There is a canonical surjective ring homomorphism from the symmetric algebra on the
cotangent space onto the associated graded ring; equivalently, the tangent cone embeds
into the linear tangent space. -/
theorem symToAssocGradedSurjection
    (R : Type u) [CommRing R] [IsLocalRing R] :
    ∃ f : tangentSpaceRing R →+* assocGradedRing (IsLocalRing.maximalIdeal R),
      Function.Surjective f := by sorry

end TangentSpace

end Lec20TangentCone
