/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib

set_option maxHeartbeats 400000

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits

noncomputable section

universe u

variable {X : Scheme.{u}} {k : Type u} [Field k] (f : X ⟶ Spec (.of k))

/-- `SectionsGenerate X U V` asserts that on `U ⊓ V` the subring
generated by restrictions of sections from `U` and from `V` is the
whole ring (Lec 7, Prop 9 generation condition). -/
def SectionsGenerate (X : Scheme.{u}) (U V : X.Opens) : Prop :=
  let resU := (X.presheaf.map (homOfLE (inf_le_left : U ⊓ V ≤ U)).op).hom
  let resV := (X.presheaf.map (homOfLE (inf_le_right : U ⊓ V ≤ V)).op).hom
  Subring.closure (Set.range resU ∪ Set.range resV) = ⊤

/-- Over an affine base `S`, the diagonal `Δ_g` is affine iff
intersections of affine opens in `X` remain affine. -/
lemma isAffineHom_diagonal_iff_of_affine_target
    {S : Scheme.{u}} [IsAffine S] {g : X ⟶ S} :
    IsAffineHom (pullback.diagonal g) ↔
    ∀ (V₁ V₂ : X.Opens), IsAffineOpen V₁ → IsAffineOpen V₂ → IsAffineOpen (V₁ ⊓ V₂) := by
  rw [isAffineHom_diagonal_iff]
  constructor
  · intro h V₁ V₂ hV₁ hV₂
    exact h ⊤ (isAffineOpen_top _) V₁ (by simp) V₂ (by simp) hV₁ hV₂
  · intro h U _ V₁ _ V₂ _ hV₁ hV₂
    exact h V₁ V₂ hV₁ hV₂

/-- Equivalence reformulating diagonal surjectivity on affine opens of
the fiber square as a section-generation condition on intersections
(Lec 7, Prop 9). -/
theorem diagonal_surjective_iff_sectionsGenerate
    {X : Scheme.{u}} {k : Type u} [Field k] (f : X ⟶ Spec (.of k)) :
    (∀ (W : (pullback f f).Opens), IsAffineOpen W →
      Function.Surjective (ConcreteCategory.hom ((pullback.diagonal f).app W))) ↔
    (∀ (U V : X.Opens), IsAffineOpen U → IsAffineOpen V → SectionsGenerate X U V) := by sorry

/-- Lec 7, Prop 9 (forward direction): if `f : X → Spec k` is separated
then intersections of affine opens of `X` are affine. -/
theorem prop9_separated_imp_affine_intersection
    [IsSeparated f]
    {U V : X.Opens} (hU : IsAffineOpen U) (hV : IsAffineOpen V) :
    IsAffineOpen (U ⊓ V) := by
  have hAff : IsAffineHom (pullback.diagonal f) :=
    (isClosedImmersion_iff_isAffineHom.mp ((isSeparated_iff f).mp ‹_›)).1
  exact isAffineHom_diagonal_iff.mp hAff ⊤ (isAffineOpen_top _) U (by simp) V (by simp) hU hV

/-- For `f : X → Spec k`, the diagonal is affine iff intersections of
affine opens of `X` are affine (Lec 7, Prop 9). -/
theorem prop9_affine_diagonal_iff_affine_intersection :
    IsAffineHom (pullback.diagonal f) ↔
    ∀ (U V : X.Opens), IsAffineOpen U → IsAffineOpen V → IsAffineOpen (U ⊓ V) :=
  isAffineHom_diagonal_iff_of_affine_target

/-- Lec 7, Prop 9: `f : X → Spec k` is separated iff (i) intersections
of affine opens of `X` are affine and (ii) on every such intersection
the restrictions from each side generate the ring of sections. -/
theorem prop9_separated_iff_affine_intersection_and_tensor_surjective :
    IsSeparated f ↔
    (∀ (U V : X.Opens), IsAffineOpen U → IsAffineOpen V → IsAffineOpen (U ⊓ V)) ∧
    (∀ (U V : X.Opens), IsAffineOpen U → IsAffineOpen V → SectionsGenerate X U V) := by
  rw [isSeparated_iff, isClosedImmersion_iff_isAffineHom]
  constructor
  · rintro ⟨hAff, hSurj⟩
    exact ⟨isAffineHom_diagonal_iff_of_affine_target.mp hAff,
           (diagonal_surjective_iff_sectionsGenerate f).mp hSurj⟩
  · rintro ⟨hAff, hSurj⟩
    exact ⟨isAffineHom_diagonal_iff_of_affine_target.mpr hAff,
           (diagonal_surjective_iff_sectionsGenerate f).mpr hSurj⟩

end
