/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.AlgebraicGeometryI.code.DimensionTheory
import Mathlib.RingTheory.KrullDimension.Polynomial
import Mathlib.RingTheory.KrullDimension.Field
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.RingTheory.DiscreteValuationRing.Basic

noncomputable section
open Ideal

/-- Serre's dimension inequality: for a Noetherian local ring `R` and primes `𝔭`, `𝔮`,
`dim(R/𝔭) + dim(R/𝔮) ≤ dim R + dim(R/(𝔭 ⊔ 𝔮))`. -/
theorem serre_dimension_inequality
    (R : Type*) [CommRing R] [IsNoetherianRing R] [IsLocalRing R]
    {𝔭 𝔮 : Ideal R} [𝔭.IsPrime] [𝔮.IsPrime] :
    ringKrullDim (R ⧸ 𝔭) + ringKrullDim (R ⧸ 𝔮) ≤
      ringKrullDim R + ringKrullDim (R ⧸ (𝔭 ⊔ 𝔮)) := by
  sorry

/-- Typeclass abstracting Serre's dimension inequality for a local ring, allowing
downstream lemmas to be stated under a single hypothesis. -/
class HasSerreDimensionInequality (R : Type*) [CommRing R] [IsLocalRing R] : Prop where
  dim_ineq : ∀ {𝔭 𝔮 : Ideal R} [𝔭.IsPrime] [𝔮.IsPrime],
    ringKrullDim (R ⧸ 𝔭) + ringKrullDim (R ⧸ 𝔮) ≤
      ringKrullDim R + ringKrullDim (R ⧸ (𝔭 ⊔ 𝔮))

/-- Every Noetherian local ring satisfies Serre's dimension inequality. -/
instance instHasSerreDimensionInequalityNoetherian
    (R : Type*) [CommRing R] [IsNoetherianRing R] [IsLocalRing R] :
    HasSerreDimensionInequality R where
  dim_ineq := serre_dimension_inequality R

/-- The Krull dimension of the trivial quotient `R / ⊤` is `⊥`. -/
lemma ringKrullDim_quotient_top (R : Type*) [CommRing R] :
    ringKrullDim (R ⧸ (⊤ : Ideal R)) = ⊥ := by
  haveI : Subsingleton (R ⧸ (⊤ : Ideal R)) := Ideal.Quotient.subsingleton_iff.mpr rfl
  exact ringKrullDim_eq_bot_of_subsingleton

/-- If Serre's dimension inequality holds for two primes, then their sum is not the unit
ideal — otherwise the right-hand side becomes `⊥` while the left-hand side is `≥ 0`. -/
theorem sup_ne_top_of_dim_inequality {R : Type*} [CommRing R]
    {𝔭 𝔮 : Ideal R} [𝔭.IsPrime] [𝔮.IsPrime]
    (hdim : ringKrullDim (R ⧸ 𝔭) + ringKrullDim (R ⧸ 𝔮) ≤
      ringKrullDim R + ringKrullDim (R ⧸ (𝔭 ⊔ 𝔮))) :
    𝔭 ⊔ 𝔮 ≠ ⊤ := by
  intro htop
  rw [htop, ringKrullDim_quotient_top, WithBot.add_bot] at hdim
  have h1 : (0 : WithBot ℕ∞) ≤ ringKrullDim (R ⧸ 𝔭) := by
    haveI : Nontrivial (R ⧸ 𝔭) := Ideal.Quotient.nontrivial_iff.mpr (Ideal.IsPrime.ne_top ‹_›)
    exact ringKrullDim_nonneg_of_nontrivial
  have h2 : (0 : WithBot ℕ∞) ≤ ringKrullDim (R ⧸ 𝔮) := by
    haveI : Nontrivial (R ⧸ 𝔮) := Ideal.Quotient.nontrivial_iff.mpr (Ideal.IsPrime.ne_top ‹_›)
    exact ringKrullDim_nonneg_of_nontrivial
  exact absurd (le_trans (le_add_of_nonneg_of_le h1 h2) hdim)
    (not_le.mpr (WithBot.bot_lt_coe 0))

/-- Corollary of Serre's inequality: in a local ring satisfying the inequality, the sum
of two primes is never the whole ring. -/
theorem sup_ne_top_of_serre {R : Type*} [CommRing R] [IsLocalRing R]
    [HasSerreDimensionInequality R]
    {𝔭 𝔮 : Ideal R} [𝔭.IsPrime] [𝔮.IsPrime] :
    𝔭 ⊔ 𝔮 ≠ ⊤ :=
  sup_ne_top_of_dim_inequality HasSerreDimensionInequality.dim_ineq

/-- Variant with a height bound: under Serre's inequality, the sum of two primes whose
heights bound the dimension of `R` is still proper. -/
theorem sum_of_primes_proper_of_height_bound {R : Type*} [CommRing R] [IsDomain R]
    [IsNoetherianRing R] [IsLocalRing R] [HasSerreDimensionInequality R]
    {𝔭 𝔮 : Ideal R} [𝔭.IsPrime] [𝔮.IsPrime]
    (_h : 𝔭.height + 𝔮.height ≤ ringKrullDim R) : 𝔭 ⊔ 𝔮 ≠ ⊤ :=
  sup_ne_top_of_serre

/-- If `𝔭 ⊔ 𝔮 = ⊤`, then `𝔮` maps to the unit ideal in `R / 𝔭`. -/
lemma map_quotient_eq_top_of_sup_eq_top {R : Type*} [CommRing R] {𝔭 𝔮 : Ideal R}
    (h : 𝔭 ⊔ 𝔮 = ⊤) : Ideal.map (Ideal.Quotient.mk 𝔭) 𝔮 = ⊤ := by
  have : Ideal.map (Ideal.Quotient.mk 𝔭) (𝔭 ⊔ 𝔮) = ⊤ := by
    rw [h]; exact Ideal.map_top _
  rw [Ideal.map_sup, Ideal.map_mk_eq_bot_of_le le_rfl] at this
  simpa using this

/-- If `I ⊔ J = ⊤`, then the Krull dimension of `R / (I ⊔ J)` is `⊥`. -/
lemma ringKrullDim_quotient_eq_bot_of_sup_eq_top {R : Type*} [CommRing R]
    {I J : Ideal R} (h : I ⊔ J = ⊤) :
    ringKrullDim (R ⧸ (I ⊔ J)) = ⊥ := by
  rw [h]; exact ringKrullDim_quotient_top R

/-- Restatement of Serre's inequality via the typeclass `HasSerreDimensionInequality`. -/
theorem ringKrullDim_quotient_sup_add_le {R : Type*} [CommRing R] [IsLocalRing R]
    [HasSerreDimensionInequality R]
    {𝔭 𝔮 : Ideal R} [𝔭.IsPrime] [𝔮.IsPrime] :
    ringKrullDim (R ⧸ 𝔭) + ringKrullDim (R ⧸ 𝔮) ≤
      ringKrullDim R + ringKrullDim (R ⧸ (𝔭 ⊔ 𝔮)) :=
  HasSerreDimensionInequality.dim_ineq

open MvPolynomial

/-- The irrelevant ideal of a polynomial ring: the ideal generated by all variables `X_i`. -/
def MvPolynomial.variablesIdeal (k : Type*) [CommSemiring k] (σ : Type*) :
    Ideal (MvPolynomial σ k) :=
  Ideal.span (Set.range (MvPolynomial.X : σ → MvPolynomial σ k))

/-- Each variable `X_i` lies in the irrelevant ideal. -/
lemma MvPolynomial.X_mem_variablesIdeal {k : Type*} [CommSemiring k] {σ : Type*} (i : σ) :
    (MvPolynomial.X i : MvPolynomial σ k) ∈ MvPolynomial.variablesIdeal k σ :=
  Ideal.subset_span (Set.mem_range.mpr ⟨i, rfl⟩)

/-- The irrelevant ideal is contained in the kernel of evaluation at the origin. -/
lemma MvPolynomial.variablesIdeal_le_ker_eval_zero {k : Type*} [CommSemiring k] {σ : Type*} :
    MvPolynomial.variablesIdeal k σ ≤ RingHom.ker (MvPolynomial.eval (0 : σ → k)) := by
  apply Ideal.span_le.mpr
  intro p hp
  obtain ⟨i, rfl⟩ := hp
  simp [RingHom.mem_ker]

/-- The irrelevant ideal is proper (does not contain `1`). -/
lemma MvPolynomial.variablesIdeal_ne_top (k : Type*) [CommSemiring k] [Nontrivial k]
    (σ : Type*) :
    MvPolynomial.variablesIdeal k σ ≠ ⊤ := by
  rw [Ne, Ideal.eq_top_iff_one]
  intro h1
  have := MvPolynomial.variablesIdeal_le_ker_eval_zero h1
  simp [RingHom.mem_ker] at this

/-- The singleton ideal `(X_i)` is contained in the irrelevant ideal. -/
lemma MvPolynomial.span_singleton_X_le_variablesIdeal {k : Type*} [CommSemiring k]
    {σ : Type*} (i : σ) :
    Ideal.span {(MvPolynomial.X i : MvPolynomial σ k)} ≤
    MvPolynomial.variablesIdeal k σ :=
  Ideal.span_le.mpr (Set.singleton_subset_iff.mpr (MvPolynomial.X_mem_variablesIdeal i))

/-- The sum of two ideals contained in the irrelevant ideal remains proper. -/
theorem MvPolynomial.sup_ne_top_of_le_variablesIdeal {k : Type*} [Field k] {σ : Type*}
    {𝔭 𝔮 : Ideal (MvPolynomial σ k)}
    (hp : 𝔭 ≤ MvPolynomial.variablesIdeal k σ)
    (hq : 𝔮 ≤ MvPolynomial.variablesIdeal k σ) :
    𝔭 ⊔ 𝔮 ≠ ⊤ :=
  ne_top_of_le_ne_top (MvPolynomial.variablesIdeal_ne_top k σ) (sup_le hp hq)

/-- An indexed supremum of ideals contained in the irrelevant ideal remains proper. -/
theorem MvPolynomial.iSup_ne_top_of_le_variablesIdeal {k : Type*} [Field k] {σ : Type*}
    {ι : Type*} {𝔭 : ι → Ideal (MvPolynomial σ k)}
    (h : ∀ i, 𝔭 i ≤ MvPolynomial.variablesIdeal k σ) :
    iSup 𝔭 ≠ ⊤ :=
  ne_top_of_le_ne_top (MvPolynomial.variablesIdeal_ne_top k σ) (iSup_le h)

/-- Example: two distinct lines in `P^2` (cut out by `X_0` and `X_1`) intersect. -/
theorem lines_meet_in_P2 (k : Type*) [Field k] :
    Ideal.span {(MvPolynomial.X (0 : Fin 3) : MvPolynomial (Fin 3) k)} ⊔
    Ideal.span {(MvPolynomial.X (1 : Fin 3) : MvPolynomial (Fin 3) k)} ≠ ⊤ :=
  MvPolynomial.sup_ne_top_of_le_variablesIdeal
    (MvPolynomial.span_singleton_X_le_variablesIdeal 0)
    (MvPolynomial.span_singleton_X_le_variablesIdeal 1)

/-- Example: a line and a conic in `P^2` meet, since both ideals lie in the irrelevant
ideal. -/
theorem line_and_conic_meet_in_P2 (k : Type*) [Field k] :
    Ideal.span {(MvPolynomial.X (0 : Fin 3) : MvPolynomial (Fin 3) k)} ⊔
    Ideal.span {(MvPolynomial.X (1 : Fin 3) * MvPolynomial.X (1 : Fin 3) -
      MvPolynomial.X (0 : Fin 3) * MvPolynomial.X (2 : Fin 3) :
      MvPolynomial (Fin 3) k)} ≠ ⊤ := by
  apply MvPolynomial.sup_ne_top_of_le_variablesIdeal
  · exact MvPolynomial.span_singleton_X_le_variablesIdeal 0
  · apply Ideal.span_le.mpr
    intro p hp
    rw [Set.mem_singleton_iff] at hp
    rw [hp]
    exact Ideal.sub_mem _ (Ideal.mul_mem_right _ _ (MvPolynomial.X_mem_variablesIdeal 1))
      (Ideal.mul_mem_right _ _ (MvPolynomial.X_mem_variablesIdeal 0))

/-- Example: two planes in `P^4` meet, since both ideals lie in the irrelevant ideal. -/
theorem planes_meet_in_P4 (k : Type*) [Field k] :
    (Ideal.span {(MvPolynomial.X (0 : Fin 5) : MvPolynomial (Fin 5) k),
      MvPolynomial.X (1 : Fin 5)}) ⊔
    (Ideal.span {(MvPolynomial.X (2 : Fin 5) : MvPolynomial (Fin 5) k),
      MvPolynomial.X (3 : Fin 5)}) ≠ ⊤ := by
  apply MvPolynomial.sup_ne_top_of_le_variablesIdeal <;>
  apply Ideal.span_le.mpr <;>
  intro p hp <;>
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hp <;>
  rcases hp with rfl | rfl <;>
  exact MvPolynomial.X_mem_variablesIdeal _

/-- General principle: the sum of two ideals contained in a proper ideal is proper. -/
theorem Ideal.sup_ne_top_of_le_proper {R : Type*} [CommRing R]
    {𝔭 𝔮 𝔪 : Ideal R} (hp : 𝔭 ≤ 𝔪) (hq : 𝔮 ≤ 𝔪) (hm : 𝔪 ≠ ⊤) :
    𝔭 ⊔ 𝔮 ≠ ⊤ :=
  ne_top_of_le_ne_top hm (sup_le hp hq)

/-- General principle: an indexed supremum of ideals contained in a proper ideal is proper. -/
theorem Ideal.iSup_ne_top_of_le_proper {R : Type*} [CommRing R]
    {ι : Type*} {𝔭 : ι → Ideal R} {𝔪 : Ideal R}
    (h : ∀ i, 𝔭 i ≤ 𝔪) (hm : 𝔪 ≠ ⊤) :
    iSup 𝔭 ≠ ⊤ :=
  ne_top_of_le_ne_top hm (iSup_le h)

end
