/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.CategoryTheory.Abelian.Basic
import Mathlib.Algebra.Homology.ShortComplex.Exact
import Mathlib.CategoryTheory.Abelian.Exact
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Defs

set_option maxHeartbeats 400000

noncomputable section

open CategoryTheory

namespace Proposition40

universe u v

/-- Abstract input data for Proposition 40: an abelian category `CohSheaf` of "coherent
sheaves" on a smooth complete curve, a predicate selecting locally free objects, a
degree function `degree : CohSheaf → ℤ`, an axiom that every short exact sequence has
the same degree defect as one between locally free objects, and additivity of the
degree on locally free short exact sequences. -/
structure SmoothCompleteCurveCohData where
  /-- The ambient category of coherent sheaves. -/
  CohSheaf : Type u
  [catInst : Category.{v} CohSheaf]
  [abelInst : Abelian CohSheaf]
  /-- The predicate selecting locally free coherent sheaves. -/
  IsLocallyFree : CohSheaf → Prop
  /-- The degree function on coherent sheaves. -/
  degree : CohSheaf → ℤ
  /-- Every short exact sequence admits a "locally free replacement" with the same degree
  defect `deg(X₂) − deg(X₁) − deg(X₃)`. -/
  reduce_to_locally_free :
    ∀ (S : ShortComplex CohSheaf) [Mono S.f] [Epi S.g],
    S.Exact →
    ∃ (S' : ShortComplex CohSheaf),
      Mono S'.f ∧ Epi S'.g ∧ S'.Exact ∧
      IsLocallyFree S'.X₁ ∧ IsLocallyFree S'.X₂ ∧ IsLocallyFree S'.X₃ ∧
      degree S.X₂ - degree S.X₁ - degree S.X₃ =
        degree S'.X₂ - degree S'.X₁ - degree S'.X₃
  /-- Degree is additive on short exact sequences whose terms are all locally free. -/
  locally_free_additive :
    ∀ (S : ShortComplex CohSheaf) [Mono S.f] [Epi S.g],
    S.Exact →
    IsLocallyFree S.X₁ → IsLocallyFree S.X₂ → IsLocallyFree S.X₃ →
    degree S.X₂ = degree S.X₁ + degree S.X₃

attribute [instance] SmoothCompleteCurveCohData.catInst
attribute [instance] SmoothCompleteCurveCohData.abelInst

variable (D : SmoothCompleteCurveCohData.{u,v})

/-- Combining the two axioms in `SmoothCompleteCurveCohData`, the degree is additive on
*every* short exact sequence, not just locally free ones. -/
theorem degree_additive (S : ShortComplex D.CohSheaf) [Mono S.f] [Epi S.g]
    (hex : S.Exact) :
    D.degree S.X₂ = D.degree S.X₁ + D.degree S.X₃ := by

  obtain ⟨S', hf', hg', hex', hlf1, hlf2, hlf3, hdefect⟩ :=
    D.reduce_to_locally_free S hex

  have hlf := @SmoothCompleteCurveCohData.locally_free_additive D S' hf' hg' hex'
    hlf1 hlf2 hlf3

  omega

/-- The set of "short exact sequence relations" inside the free abelian group on
coherent sheaves: for every short exact sequence `0 → X₁ → X₂ → X₃ → 0` we get an
element `[X₂] − [X₁] − [X₃]`. -/
def CohSESRelSet : Set (FreeAbelianGroup D.CohSheaf) :=
  { x | ∃ (S : ShortComplex D.CohSheaf),
    Mono S.f ∧ Epi S.g ∧ S.Exact ∧
    x = FreeAbelianGroup.of S.X₂ - FreeAbelianGroup.of S.X₁ - FreeAbelianGroup.of S.X₃ }

/-- The subgroup of the free abelian group on coherent sheaves generated by the short
exact sequence relations. -/
def CohSESRelSubgroup : AddSubgroup (FreeAbelianGroup D.CohSheaf) :=
  AddSubgroup.closure (CohSESRelSet D)

/-- The Grothendieck group `K⁰(Coh(X))` of coherent sheaves: the free abelian group on
coherent sheaves modulo the short exact sequence relations. -/
abbrev K0Coh : Type _ :=
  FreeAbelianGroup D.CohSheaf ⧸ CohSESRelSubgroup D

/-- The class `[ℱ] ∈ K⁰(Coh(X))` of a coherent sheaf `ℱ`. -/
def K0Coh.classOf (ℱ : D.CohSheaf) : K0Coh D :=
  QuotientAddGroup.mk (FreeAbelianGroup.of ℱ)

/-- In `K⁰(Coh(X))`, every short exact sequence gives the relation
`[X₂] = [X₁] + [X₃]`. -/
theorem K0Coh.ses_relation (S : ShortComplex D.CohSheaf)
    [Mono S.f] [Epi S.g] (hex : S.Exact) :
    K0Coh.classOf D S.X₂ = K0Coh.classOf D S.X₁ + K0Coh.classOf D S.X₃ := by
  unfold K0Coh.classOf
  rw [← QuotientAddGroup.mk_add]
  apply QuotientAddGroup.eq.mpr
  have hmem : FreeAbelianGroup.of S.X₂ - FreeAbelianGroup.of S.X₁ -
      FreeAbelianGroup.of S.X₃ ∈ CohSESRelSubgroup D :=
    AddSubgroup.subset_closure ⟨S, inferInstance, inferInstance, hex, rfl⟩
  have : -FreeAbelianGroup.of S.X₂ + (FreeAbelianGroup.of S.X₁ + FreeAbelianGroup.of S.X₃) =
      -(FreeAbelianGroup.of S.X₂ - FreeAbelianGroup.of S.X₁ - FreeAbelianGroup.of S.X₃) := by
    simp [sub_eq_add_neg]; abel
  rw [this]
  exact (CohSESRelSubgroup D).neg_mem hmem

/-- The lift of `degree : CohSheaf → ℤ` to a homomorphism on the free abelian group
sends every short exact sequence relation to zero, so its kernel contains the SES
relations subgroup. -/
lemma degree_lift_ker_contains_relations :
    CohSESRelSubgroup D ≤ (FreeAbelianGroup.lift D.degree).ker := by
  rw [CohSESRelSubgroup, AddSubgroup.closure_le]
  intro x hx
  obtain ⟨S, hf, hg, hex, rfl⟩ := hx
  rw [SetLike.mem_coe, AddMonoidHom.mem_ker, map_sub, map_sub,
      FreeAbelianGroup.lift_apply_of, FreeAbelianGroup.lift_apply_of,
      FreeAbelianGroup.lift_apply_of]
  have := @degree_additive D S hf hg hex
  omega

/-- The induced degree homomorphism `δ : K⁰(Coh(X)) → ℤ`. -/
def degreeMapK0 : K0Coh D →+ ℤ :=
  QuotientAddGroup.lift (CohSESRelSubgroup D)
    (FreeAbelianGroup.lift D.degree)
    (degree_lift_ker_contains_relations D)

/-- Proposition 40 (computation on classes): the induced degree map sends `[ℱ]` to
`deg ℱ`. -/
theorem proposition_40_delta_on_class (ℱ : D.CohSheaf) :
    degreeMapK0 D (K0Coh.classOf D ℱ) = D.degree ℱ := by
  unfold degreeMapK0 K0Coh.classOf
  simp only [QuotientAddGroup.lift_mk, FreeAbelianGroup.lift_apply_of]

/-- Proposition 40 (existence of `δ`): there exists a group homomorphism
`δ : K⁰(Coh(X)) → ℤ` extending the degree of every coherent sheaf. -/
theorem proposition_40_delta_well_defined :
    ∃ δ : K0Coh D →+ ℤ,
      ∀ ℱ : D.CohSheaf,
        δ (K0Coh.classOf D ℱ) = D.degree ℱ := by
  exact ⟨degreeMapK0 D, proposition_40_delta_on_class D⟩

/-- The degree map `δ : K⁰(Coh(X)) → ℤ` itself satisfies the SES relation on classes. -/
theorem degreeMapK0_ses (S : ShortComplex D.CohSheaf)
    [Mono S.f] [Epi S.g] (hex : S.Exact) :
    degreeMapK0 D (K0Coh.classOf D S.X₂) =
      degreeMapK0 D (K0Coh.classOf D S.X₁) +
        degreeMapK0 D (K0Coh.classOf D S.X₃) := by
  rw [proposition_40_delta_on_class, proposition_40_delta_on_class,
      proposition_40_delta_on_class]
  exact degree_additive D S hex

end Proposition40

end
