/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Ideal.Maps

noncomputable section

/-- The maximal ideal of polynomials in `k[X_1, ..., X_n]` vanishing at the point `x`. -/
def maxIdealOfPoint_P31 {k : Type*} [Field k] {n : ℕ}
    (x : Fin n → k) : Ideal (MvPolynomial (Fin n) k) :=
  RingHom.ker (MvPolynomial.eval x)

/-- The maximal ideal at a point is genuinely maximal. -/
instance maxIdealOfPoint_P31_isMaximal {k : Type*} [Field k] {n : ℕ}
    (x : Fin n → k) : (maxIdealOfPoint_P31 x).IsMaximal :=
  RingHom.ker_isMaximal_of_surjective _
    (fun c => ⟨MvPolynomial.C c, MvPolynomial.eval_C c⟩)

/-- The image of the maximal ideal at `x` in the quotient `k[X]/I`, for `I` contained
in that maximal ideal. -/
def maxIdealInQuotient_P31 {k : Type*} [Field k] {n : ℕ}
    (I : Ideal (MvPolynomial (Fin n) k))
    (x : Fin n → k) (_ : I ≤ maxIdealOfPoint_P31 x) :
    Ideal (MvPolynomial (Fin n) k ⧸ I) :=
  Ideal.map (Ideal.Quotient.mk I) (maxIdealOfPoint_P31 x)

/-- The image maximal ideal in the quotient is maximal. -/
instance maxIdealInQuotient_P31_isMaximal {k : Type*} [Field k] {n : ℕ}
    (I : Ideal (MvPolynomial (Fin n) k))
    (x : Fin n → k) (hI : I ≤ maxIdealOfPoint_P31 x) :
    (maxIdealInQuotient_P31 I x hI).IsMaximal := by
  apply Ideal.IsMaximal.map_of_surjective_of_ker_le
  · exact Ideal.Quotient.mk_surjective
  · rwa [Ideal.mk_ker]

/-- The image maximal ideal in the quotient is prime. -/
instance maxIdealInQuotient_P31_isPrime {k : Type*} [Field k] {n : ℕ}
    (I : Ideal (MvPolynomial (Fin n) k))
    (x : Fin n → k) (hI : I ≤ maxIdealOfPoint_P31 x) :
    (maxIdealInQuotient_P31 I x hI).IsPrime :=
  (maxIdealInQuotient_P31_isMaximal I x hI).isPrime

/-- The local ring of the variety `V(I)` at the point `x`. -/
abbrev localRingAtPoint_P31 {k : Type*} [Field k] {n : ℕ}
    (I : Ideal (MvPolynomial (Fin n) k))
    (x : Fin n → k) (hI : I ≤ maxIdealOfPoint_P31 x) :=
  Localization.AtPrime (maxIdealInQuotient_P31 I x hI)

/-- The Jacobian matrix of `f_1, ..., f_m ∈ k[X_1, ..., X_n]` at the point `x ∈ k^n`. -/
def jacobianMatrix_P31 {k : Type*} [Field k] {n m : ℕ}
    (f : Fin m → MvPolynomial (Fin n) k) (x : Fin n → k) :
    Matrix (Fin m) (Fin n) k :=
  fun i j => MvPolynomial.eval x (MvPolynomial.pderiv j (f i))

/-- For a variety cut out by `f_1, ..., f_m` at a point `x` where all `f_i` vanish, the
cotangent space dimension equals `n − rank(Jacobian)`. -/
theorem cotangentSpace_finrank_eq_n_sub_jacobianRank_P31
    {k : Type*} [Field k] {n m : ℕ}
    (f : Fin m → MvPolynomial (Fin n) k)
    (x : Fin n → k)
    (hx : ∀ i, MvPolynomial.eval x (f i) = 0)
    (hI : Ideal.span (Set.range f) ≤ maxIdealOfPoint_P31 x) :
    Module.finrank
      (IsLocalRing.ResidueField (localRingAtPoint_P31 (Ideal.span (Set.range f)) x hI))
      (IsLocalRing.CotangentSpace (localRingAtPoint_P31 (Ideal.span (Set.range f)) x hI)) =
    n - (jacobianMatrix_P31 f x).rank := by sorry

/-- Forward direction of Proposition 31 (Jacobian criterion): if `m` local generators
with `m × n` Jacobian of maximal rank `m` cut out a `V` of dimension `n − m` at `x`,
then the local ring at `x` is regular. -/
theorem proposition31_forward {k : Type*} [Field k] {n m : ℕ}
    (f : Fin m → MvPolynomial (Fin n) k)
    (x : Fin n → k)
    (hx : ∀ i, MvPolynomial.eval x (f i) = 0)
    (hI : Ideal.span (Set.range f) ≤ maxIdealOfPoint_P31 x)
    (hdim : ringKrullDim
      (localRingAtPoint_P31 (Ideal.span (Set.range f)) x hI) = (n - m : ℕ))
    (_hmn : m ≤ n)
    (hrank : (jacobianMatrix_P31 f x).rank = m) :
    IsRegularLocalRing
      (localRingAtPoint_P31 (Ideal.span (Set.range f)) x hI) := by

  have hcot : Module.finrank
      (IsLocalRing.ResidueField (localRingAtPoint_P31 (Ideal.span (Set.range f)) x hI))
      (IsLocalRing.CotangentSpace (localRingAtPoint_P31 (Ideal.span (Set.range f)) x hI)) =
    n - (jacobianMatrix_P31 f x).rank :=
    cotangentSpace_finrank_eq_n_sub_jacobianRank_P31 f x hx hI

  rw [hrank] at hcot

  rw [IsRegularLocalRing.iff_finrank_cotangentSpace]
  rw [hcot, hdim]


/-- Converse direction of Proposition 31: if the local ring is regular and of dimension
`n − m`, then `I` is locally generated by `m` polynomials with linearly independent
differentials. -/
theorem proposition31_converse_aux
    {k : Type*} [Field k] {n m : ℕ}
    (I : Ideal (MvPolynomial (Fin n) k))
    (x : Fin n → k)
    (hI : I ≤ maxIdealOfPoint_P31 x)
    (hdim : ringKrullDim (localRingAtPoint_P31 I x hI) = (n - m : ℕ))
    (hmn : m ≤ n)
    (hreg : IsRegularLocalRing (localRingAtPoint_P31 I x hI)) :
    ∃ f : Fin m → MvPolynomial (Fin n) k,
      (∀ i, f i ∈ I) ∧
      (∀ i, MvPolynomial.eval x (f i) = 0) ∧
      (jacobianMatrix_P31 f x).rank = m ∧
      (Ideal.span (Set.range f) = I) := by sorry

/-- Proposition 31 (Jacobian criterion): smoothness at `x` is equivalent to existence of
`m` local generators of `I` with linearly independent differentials at `x`. -/
theorem proposition31_smooth_iff_local_generators {k : Type*} [Field k] {n m : ℕ}
    (I : Ideal (MvPolynomial (Fin n) k))
    (x : Fin n → k)
    (hI : I ≤ maxIdealOfPoint_P31 x)
    (hdim : ringKrullDim (localRingAtPoint_P31 I x hI) = (n - m : ℕ))
    (hmn : m ≤ n) :
    IsRegularLocalRing (localRingAtPoint_P31 I x hI) ↔
    ∃ f : Fin m → MvPolynomial (Fin n) k,
      (∀ i, f i ∈ I) ∧
      (∀ i, MvPolynomial.eval x (f i) = 0) ∧
      (jacobianMatrix_P31 f x).rank = m ∧
      (Ideal.span (Set.range f) = I) := by
  constructor
  ·
    intro hreg
    exact proposition31_converse_aux I x hI hdim hmn hreg
  ·
    intro ⟨f, _hfI, hfx, hrank, hgen⟩

    have hfI_le : Ideal.span (Set.range f) ≤ maxIdealOfPoint_P31 x := hgen ▸ hI
    have hreg := proposition31_forward f x hfx hfI_le
      (by subst hgen; exact hdim) hmn hrank
    subst hgen
    exact hreg

end
