/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Coprime.Lemmas
import Mathlib.RingTheory.Finiteness.Defs

/-- If `(f, g) = (1)` in `A` and every `f^n • m` lies in span `S` while every
`g^k • m` lies in span `T`, then `S ∪ T` spans all of `M`. A gluing helper for
local-to-global finite generation arguments behind quasi-coherence. -/
theorem span_union_eq_top_of_powers {A : Type*} [CommRing A]
    {M : Type*} [AddCommGroup M] [Module A M]
    {f g : A} (hfg : Ideal.span {f, g} = ⊤)
    {S T : Set M} {n k : ℕ}
    (hS : ∀ m : M, f ^ n • m ∈ Submodule.span A S)
    (hT : ∀ m : M, g ^ k • m ∈ Submodule.span A T) :
    Submodule.span A (S ∪ T) = ⊤ := by

  have hcop : IsCoprime f g := by
    have h1 : (1 : A) ∈ Ideal.span ({f, g} : Set A) := by rw [hfg]; exact Submodule.mem_top
    rw [Ideal.mem_span_pair] at h1
    obtain ⟨a, b, hab⟩ := h1
    exact ⟨a, b, hab⟩

  obtain ⟨a, b, hab⟩ := hcop.pow (m := n) (n := k)
  rw [eq_top_iff]
  intro m _

  have key : m = a • (f ^ n • m) + b • (g ^ k • m) := by
    have : (a * f ^ n + b * g ^ k) • m = m := by rw [hab, one_smul]
    rw [add_smul, mul_smul, mul_smul] at this
    exact this.symm
  rw [key, Submodule.span_union]
  apply Submodule.add_mem
  · exact (Submodule.span A S ⊔ Submodule.span A T).smul_mem a (Submodule.mem_sup_left (hS m))
  · exact (Submodule.span A S ⊔ Submodule.span A T).smul_mem b (Submodule.mem_sup_right (hT m))

/-- Lem 23 / coherence helper: if `(f, g) = (1)` and `M` is generated by a
finite set after inverting `f` (resp. `g`), then `M` is itself finitely
generated as an `A`-module. -/
theorem module_fg_of_localization_fg {A : Type*} [CommRing A]
    {M : Type*} [AddCommGroup M] [Module A M]
    {f g : A} (hfg : Ideal.span {f, g} = ⊤)
    {S T : Set M} (hSfin : S.Finite) (hTfin : T.Finite)
    {n k : ℕ}
    (hS : ∀ m : M, f ^ n • m ∈ Submodule.span A S)
    (hT : ∀ m : M, g ^ k • m ∈ Submodule.span A T) :
    Module.Finite A M := by
  rw [Module.finite_def, Submodule.fg_def]
  exact ⟨S ∪ T, hSfin.union hTfin, span_union_eq_top_of_powers hfg hS hT⟩
