/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.CategoryTheory.Yoneda
import Mathlib.RingTheory.Discriminant
import Mathlib.RingTheory.Spectrum.Prime.Topology

open CategoryTheory Opposite

noncomputable section

namespace Lecture6

/-- The Yoneda embedding `C → [Cᵒᵖ, Type]` is fully faithful, the categorical
input behind functor-of-points reasoning in ramification arguments. -/
def yonedaFullyFaithful (C : Type*) [Category C] :
    (yoneda (C := C)).FullyFaithful :=
  Yoneda.fullyFaithful

example (C : Type*) [Category C] : (yoneda (C := C)).Full := inferInstance

example (C : Type*) [Category C] : (yoneda (C := C)).Faithful := inferInstance

/-- The Yoneda lemma: natural transformations `Hom(−, X) → F` correspond
bijectively to elements of `F(X)`. -/
def yonedaLemmaEquiv {C : Type*} [Category C] (X : C)
    (F : Cᵒᵖ ⥤ Type _) : (yoneda.obj X ⟶ F) ≃ F.obj (op X) :=
  yonedaEquiv

/-- The principal ramification ideal `(disc(A → B))` of `A`, generated by the
discriminant of a chosen basis of the free finite extension `B / A`. -/
def ramificationIdeal (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    [Module.Finite A B] [Module.Free A B] : Ideal A :=
  Ideal.span {Algebra.discr A (Module.Free.chooseBasis A B)}

/-- The ramification locus is closed in `Spec A`, being the zero locus of the
discriminant ideal (Lec 6 variant of Prop 7). -/
theorem ramificationLocus_isClosed (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    [Module.Finite A B] [Module.Free A B] :
    IsClosed (PrimeSpectrum.zeroLocus (ramificationIdeal A B : Set A)) :=
  PrimeSpectrum.isClosed_zeroLocus _

/-- If the discriminant is nonzero, the ramification locus is a proper closed
subset of `Spec A`. -/
theorem ramificationLocus_ne_univ (A B : Type*) [CommRing A] [IsDomain A]
    [CommRing B] [Algebra A B] [Module.Finite A B] [Module.Free A B]
    (hsep : Algebra.discr A (Module.Free.chooseBasis A B) ≠ 0) :
    PrimeSpectrum.zeroLocus (ramificationIdeal A B : Set A) ≠ Set.univ := by
  intro h
  rw [PrimeSpectrum.zeroLocus_eq_univ_iff] at h
  have hmem : Algebra.discr A (Module.Free.chooseBasis A B) ∈ nilradical A := by
    apply h
    exact Ideal.subset_span (Set.mem_singleton _)
  rw [nilradical_eq_zero] at hmem
  exact hsep hmem

/-- For a finite separable extension of fields `K → L`, the discriminant of any
chosen basis is nonzero. -/
theorem discr_ne_zero_of_separable (K L : Type*) [Field K] [Field L]
    [Algebra K L] [Module.Finite K L] [Algebra.IsSeparable K L] :
    Algebra.discr K (Module.Free.chooseBasis K L) ≠ 0 :=
  Algebra.discr_not_zero_of_basis K _

/-- The degree of a dominant morphism of irreducible curves: the dimension of
the function-field extension `K(B) / K(A)`. -/
def dominantMorphismDegree (A B : Type*) [CommRing A] [IsDomain A]
    [CommRing B] [IsDomain B] [Algebra A B] [FaithfulSMul A B] : ℕ :=
  haveI := FractionRing.liftAlgebra A (FractionRing B)
  Module.finrank (FractionRing A) (FractionRing B)

end Lecture6

end
