/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.AlgebraicGeometryI.code.SerreDualityLinear
import Atlas.AlgebraicGeometryI.code.SerreDualityGeneral
import Atlas.AlgebraicGeometryI.code.SerreDualityCurves
import Atlas.AlgebraicGeometryI.code.ResidueSum
import Atlas.AlgebraicGeometryI.code.SheafCohCurvesFiniteness
import Atlas.AlgebraicGeometryI.code.CanonicalSheafCurves

noncomputable section

namespace SerreDualityTate

open CanonicalSheafCurves RiemannRochCurves SerreDualityP1
open SheafCohCurvesFiniteness CohomologyP1 SheafCohomology
open SerreDualityCurves


section CechSetup

variable (k : Type*) [Field k]

/-- A Tate-style duality setup: a `k`-vector space `V` together with two
subspaces `V₁`, `V₂` which model a two-cover Čech setup. -/
structure TateDualitySetup where
  V : Type*
  [instACG : AddCommGroup V]
  [instModule : Module k V]
  V₁ : Submodule k V
  V₂ : Submodule k V

attribute [instance] TateDualitySetup.instACG TateDualitySetup.instModule

variable {k}

namespace TateDualitySetup

variable (S : TateDualitySetup k)

/-- The Čech `H⁰` of the setup: the intersection `V₁ ∩ V₂`. -/
def cechH0 : Submodule k S.V := S.V₁ ⊓ S.V₂

/-- The Čech `H¹` of the setup: the quotient `V / (V₁ + V₂)`. -/
def cechH1 : Type _ := S.V ⧸ (S.V₁ ⊔ S.V₂)

/-- `cechH1` is an additive commutative group, inherited from the quotient. -/
instance cechH1.instACG : AddCommGroup S.cechH1 :=
  inferInstanceAs (AddCommGroup (S.V ⧸ (S.V₁ ⊔ S.V₂)))

/-- `cechH1` is a `k`-module, inherited from the quotient. -/
instance cechH1.instModule : Module k S.cechH1 :=
  inferInstanceAs (Module k (S.V ⧸ (S.V₁ ⊔ S.V₂)))

/-- Unfolds `cechH0` as `V₁ ∩ V₂`. -/
theorem cechH0_eq_inf : S.cechH0 = S.V₁ ⊓ S.V₂ := rfl

/-- The dual Tate setup: `V*` with subspaces given by the annihilators of `V₁` and `V₂`. -/
def dual : TateDualitySetup k where
  V := Module.Dual k S.V
  V₁ := S.V₁.dualAnnihilator
  V₂ := S.V₂.dualAnnihilator

end TateDualitySetup

end CechSetup


section AnnihilatorIdentities

variable {k : Type*} [Field k]

/-- The dual `cechH0` equals the annihilator of the sum `V₁ + V₂`:
`V₁⁰ ∩ V₂⁰ = (V₁ + V₂)⁰`. -/
theorem dual_H0_eq_annihilator_sup (S : TateDualitySetup k) :
    S.dual.cechH0 = (S.V₁ ⊔ S.V₂).dualAnnihilator := by
  show S.V₁.dualAnnihilator ⊓ S.V₂.dualAnnihilator = (S.V₁ ⊔ S.V₂).dualAnnihilator
  exact (Submodule.dualAnnihilator_sup_eq S.V₁ S.V₂).symm

/-- The sum of annihilators is contained in the annihilator of the intersection:
`W₁⁰ + W₂⁰ ⊆ (W₁ ∩ W₂)⁰`. -/
theorem annihilator_inf_contains_sup {V : Type*}
    [AddCommGroup V] [Module k V]
    (W₁ W₂ : Submodule k V) :
    W₁.dualAnnihilator ⊔ W₂.dualAnnihilator ≤ (W₁ ⊓ W₂).dualAnnihilator :=
  Submodule.sup_dualAnnihilator_le_inf W₁ W₂

/-- Over a field, the annihilator of the intersection equals the sum of annihilators:
`(W₁ ∩ W₂)⁰ = W₁⁰ + W₂⁰`. -/
theorem annihilator_inf_eq_sup_field {V : Type*}
    [AddCommGroup V] [Module k V]
    (W₁ W₂ : Submodule k V) :
    (W₁ ⊓ W₂).dualAnnihilator = W₁.dualAnnihilator ⊔ W₂.dualAnnihilator :=
  Subspace.dualAnnihilator_inf_eq W₁ W₂

end AnnihilatorIdentities


section TateVectorSpaces

variable (k : Type*) [Field k]

/-- Tate vector space (Def 46, Lec 25): a `k`-vector space `V` with a topology
admitting a neighborhood basis of `0` by mutually commensurable subspaces. -/
structure TateVectorSpace where
  V : Type*
  [instACG : AddCommGroup V]
  [instModule : Module k V]
  topology : TopologicalSpace V
  nhd_basis : Set (Submodule k V)
  is_nhd_basis : ∀ U ∈ nhd_basis, (U : Set V) ∈ @nhds V topology 0
  commensurable : ∀ U₁ ∈ nhd_basis, ∀ U₂ ∈ nhd_basis,
    Module.Finite k (U₁ ⧸ Submodule.comap U₁.subtype (U₁ ⊓ U₂)) ∧
    Module.Finite k (U₂ ⧸ Submodule.comap U₂.subtype (U₁ ⊓ U₂))

attribute [instance] TateVectorSpace.instACG TateVectorSpace.instModule

/-- Two subspaces `W₁`, `W₂` are commensurable if each quotient `Wᵢ / (W₁ ∩ W₂)`
is finite-dimensional. -/
def Commensurable {V : Type*} [AddCommGroup V] [Module k V]
    (W₁ W₂ : Submodule k V) : Prop :=
  Module.Finite k (W₁ ⧸ Submodule.comap W₁.subtype (W₁ ⊓ W₂)) ∧
  Module.Finite k (W₂ ⧸ Submodule.comap W₂.subtype (W₁ ⊓ W₂))

/-- The subspace of Laurent polynomials supported in indices `≥ i`. -/
def shiftedSupported (i : ℤ) : Submodule k (ℤ →₀ k) :=
  Finsupp.supported k k {n : ℤ | i ≤ n}

/-- The Laurent topology on `ℤ →₀ k` generated by translates of the
`shiftedSupported` subspaces — a basic case of a Tate vector space topology. -/
def laurentTopology : TopologicalSpace (ℤ →₀ k) :=
  TopologicalSpace.generateFrom
    { U | ∃ (f : ℤ →₀ k) (i : ℤ), U = {g | g - f ∈ shiftedSupported k i} }

/-- The Tate vector space structure on `ℤ →₀ k` with the Laurent topology
and neighborhood basis given by `shiftedSupported`. -/
def tateVS_kLaurent : TateVectorSpace k where
  V := ℤ →₀ k
  topology := laurentTopology k
  nhd_basis := Set.range (shiftedSupported k)
  is_nhd_basis := by
    intro U hU
    obtain ⟨i, rfl⟩ := hU
    sorry
  commensurable := by
    intro U₁ hU₁ U₂ hU₂
    obtain ⟨i, rfl⟩ := hU₁
    obtain ⟨j, rfl⟩ := hU₂
    sorry

end TateVectorSpaces


section ResiduePairingProperties

variable {k : Type*} [Field k]

/-- Residue pairing vanishing implies annihilator inclusion: if `φ(w)(v) = 0`
for all `v ∈ V₁`, `w ∈ V₁'`, then `V₁' ⊆ φ⁻¹(V₁⁰)`. -/
theorem residue_annihilator_property {V : Type*} [AddCommGroup V] [Module k V]
    (V₁ V₁' : Submodule k V) (φ : V →ₗ[k] Module.Dual k V)
    (h_zero : ∀ v ∈ V₁, ∀ w ∈ V₁', φ w v = 0) :
    V₁' ≤ Submodule.comap φ V₁.dualAnnihilator := by
  intro w hw
  simp only [Submodule.mem_comap, Submodule.mem_dualAnnihilator]
  intro v hv
  exact h_zero v hv w hw

/-- If `f` annihilates every nonneg-supported `g` under the residue pairing,
then `f` itself is nonneg-supported. -/
theorem lattice_annihilator_nonneg (f : ℤ →₀ k) :
    (∀ g : ℤ →₀ k, (∀ (i : ℤ), i < 0 → g i = 0) →
      (∑ j ∈ f.support, f j * g (-1 - j)) = 0) →
    ∀ (i : ℤ), i < 0 → f i = 0 := by
  intro hpair i hi


  specialize hpair (Finsupp.single (-1 - i) 1) (fun j hj => by
    simp only [Finsupp.single_apply]
    split_ifs with h
    · subst h; omega
    · rfl)


  simp only [Finsupp.single_apply] at hpair
  have key : ∀ j ∈ f.support, f j * (if -1 - i = -1 - j then (1 : k) else 0) =
    if j = i then f j else 0 := by
    intro j _
    split_ifs with h1 h2
    · simp
    · omega
    · omega
    · simp
  rw [Finset.sum_congr rfl key] at hpair
  by_cases hm : i ∈ f.support
  · rw [Finset.sum_ite_eq' f.support i] at hpair
    simp [hm] at hpair
    exact hpair
  · exact Finsupp.notMem_support_iff.mp hm

end ResiduePairingProperties


section CoreDuality

variable {k : Type*} [Field k]

/-- `cechH0` is by definition the intersection `V₁ ∩ V₂`. -/
theorem tate_H0_eq_intersection (S : TateDualitySetup k) :
    S.cechH0 = S.V₁ ⊓ S.V₂ := rfl

/-- The dual `cechH0` equals the annihilator of `V₁ + V₂`. -/
theorem tate_H0_dual_eq (S : TateDualitySetup k) :
    S.dual.cechH0 = (S.V₁ ⊔ S.V₂).dualAnnihilator :=
  dual_H0_eq_annihilator_sup S

/-- Core Tate-style duality: in finite dimension, `dim H⁰(S.dual) = dim H¹(S)`,
i.e. `dim (V₁ + V₂)⁰ = dim (V / (V₁ + V₂))`. -/
theorem tate_duality_core (S : TateDualitySetup k)
    [FiniteDimensional k S.V] :
    Module.finrank k ↥S.dual.cechH0 = Module.finrank k S.cechH1 := by

  unfold TateDualitySetup.cechH0 TateDualitySetup.dual TateDualitySetup.cechH1
  simp only


  rw [(Submodule.dualAnnihilator_sup_eq S.V₁ S.V₂).symm]


  have h_ann := Subspace.finrank_add_finrank_dualAnnihilator_eq (S.V₁ ⊔ S.V₂)
  have h_quot := Submodule.finrank_quotient_add_finrank (S.V₁ ⊔ S.V₂)


  apply Nat.add_right_cancel (m := Module.finrank k ↥(S.V₁ ⊔ S.V₂))
  rw [add_comm (Module.finrank k ↥(S.V₁ ⊔ S.V₂).dualAnnihilator)]
  convert h_ann.trans h_quot.symm using 2

end CoreDuality


section ResidueCharacterization

variable (k : Type*) [Field k]

/-- The residue of an exact differential `d(a · z^n)` vanishes. -/
theorem residue_characterization_exact (n : ℤ) (a : k) :
    SerreDualityCurves.residueMap k (Finsupp.single (n - 1) ((↑n : k) * a)) = 0 :=
  SerreDualityCurves.residue_of_exact_zero k n a

/-- The residue of `dt / t` (concentrated at index `-1`) equals `1`. -/
theorem residue_of_dt_over_t :
    SerreDualityCurves.residueMap k (Finsupp.single (-1 : ℤ) (1 : k)) = 1 :=
  SerreDualityCurves.residueMap_single_neg_one k 1

/-- The residue pairing of `a · z^i` with `g` equals `a · g(-1 - i)`. -/
theorem residue_pairing_shift (i : ℤ) (a : k) (g : ℤ →₀ k) :
    SerreDualityCurves.residuePairing k (Finsupp.single i a) g =
    a * g (SerreDualityP1.residueShift i) :=
  SerreDualityCurves.residuePairing_via_shift k i a g

end ResidueCharacterization


section SerreDualityFromTate

variable (k : Type*) [Field k]

/-- Combining the Tate-style core duality with Riemann–Roch on a smooth complete
curve yields both Serre-duality identities `h⁰(E∨⊗K) = h¹(E)` and `h⁰(E) = h¹(E∨⊗K)`. -/
theorem serre_duality_from_tate_both
    {k : Type*} [Field k]
    (S : TateDualitySetup k) [FiniteDimensional k S.V]
    (C : SmoothCompleteCurve) (d : ℤ)
    (h0_E h1_E h0_EK h1_EK : ℤ)
    (hRR_E : h0_E - h1_E = C.χ (1, d))
    (hRR_EK : h0_EK - h1_EK = C.χ (1, C.degK - d))

    (h_h0_EK : h0_EK = ↑(Module.finrank k ↥S.dual.cechH0))

    (h_h1_E : h1_E = ↑(Module.finrank k S.cechH1)) :
    h0_EK = h1_E ∧ h0_E = h1_EK := by

  have h_tate := tate_duality_core S

  have h_tate_int : (Module.finrank k ↥S.dual.cechH0 : ℤ) =
      (Module.finrank k S.cechH1 : ℤ) := by exact_mod_cast h_tate

  have h_first : h0_EK = h1_E := by
    rw [h_h0_EK, h_h1_E, h_tate_int]

  have hchi := SerreDualityCurves.serre_duality_chi_rank1 C d
  exact ⟨h_first, by linarith⟩

/-- Rank-1 Euler-characteristic identity from Serre duality: `χ(E) + χ(E∨⊗K) = 0`. -/
theorem euler_char_dual_pair (C : SmoothCompleteCurve) (d : ℤ) :
    C.χ (1, d) + C.χ (1, C.degK - d) = 0 :=
  SerreDualityCurves.serre_duality_chi_rank1 C d

/-- Rank-`r` Euler-characteristic identity from Serre duality. -/
theorem euler_char_dual_pair_rank_r (C : SmoothCompleteCurve) (r d : ℤ) :
    C.χ (r, d) + C.χ (r, r * C.degK - d) = 0 :=
  SerreDualityCurves.serre_duality_chi_rank_r C r d

end SerreDualityFromTate


section P1Connection

variable (k : Type) [Field k]

/-- The Čech setup on `ℙ¹` for `O(n)`: `V = (ℤ →₀ k)` with the two cover-pieces
realized as `NonNeg` and `AtMost n` subspaces. -/
def cechSetup_P1 (n : ℤ) : TateDualitySetup k where
  V := ℤ →₀ k
  V₁ := CohomologyP1.NonNeg k
  V₂ := CohomologyP1.AtMost k n

/-- The Čech `H⁰` of the `ℙ¹` setup is `NonNeg ∩ AtMost n`. -/
theorem cechSetup_P1_H0 (n : ℤ) :
    (cechSetup_P1 k n).cechH0 = CohomologyP1.NonNeg k ⊓ CohomologyP1.AtMost k n :=
  rfl

/-- Serre duality on `ℙ¹` derived from the Tate setup (existence form): for `n < -1`,
`H¹(O(n)) ≃ H⁰(O(-2 - n))`. -/
theorem serre_duality_P1_from_tate (n : ℤ) (hn : n < -1) :
    Nonempty (((ℤ →₀ k) ⧸ (CohomologyP1.NonNeg k ⊔ CohomologyP1.AtMost k n)) ≃ₗ[k]
      ↥(CechH0 k (-2 - n))) :=
  ⟨SerreDualityP1.serre_duality_P1 k n hn⟩

/-- Dimension form of Serre duality on `ℙ¹`. -/
theorem serre_duality_P1_dim (n : ℤ) :
    RiemannRoch.dimH1 k n = RiemannRoch.dimH0 k (-2 - n) :=
  RiemannRoch.serre_duality_P1 k n

end P1Connection


section SumOfResidues

variable (k : Type*) [Field k]

/-- Sum of residues theorem on `ℙ¹`: the sum of finite-place residues
of a partial fraction plus the residue at infinity vanishes. -/
theorem sum_of_residues_zero {n : ℕ} (c : Fin n → k) (a : Fin n → k)
    (hdist : Function.Injective a) :
    (∑ i, ResidueSum.residuePartialFrac c a i) +
    ResidueSum.residueAtInfPartialFrac c a = 0 :=
  ResidueSum.residue_sum_partial_frac c a hdist

/-- Vanishing of the residue pairing on `V₁ × V₁'` implies `V₁' ⊆ V₁⁰`. -/
theorem residue_implies_annihilator_inclusion
    (S : TateDualitySetup k) (V₁' : Submodule k (Module.Dual k S.V))
    (h_residue : ∀ f ∈ S.V₁, ∀ φ ∈ V₁', φ f = 0) :
    V₁' ≤ S.V₁.dualAnnihilator := by
  intro φ hφ
  rw [Submodule.mem_dualAnnihilator]
  exact fun v hv => h_residue v hv φ hφ

/-- If `V₁' = V₁⁰` and `V₂' = V₂⁰`, then `V₁' ∩ V₂' = (V₁ + V₂)⁰`. -/
theorem annihilator_equality_gives_duality
    (S : TateDualitySetup k) (V₁' : Submodule k (Module.Dual k S.V))
    (h_eq : V₁' = S.V₁.dualAnnihilator)
    (V₂' : Submodule k (Module.Dual k S.V))
    (h_eq₂ : V₂' = S.V₂.dualAnnihilator) :
    V₁' ⊓ V₂' = (S.V₁ ⊔ S.V₂).dualAnnihilator := by
  rw [h_eq, h_eq₂]
  exact (Submodule.dualAnnihilator_sup_eq S.V₁ S.V₂).symm

end SumOfResidues


section FullSerreDuality

/-- Full Serre duality + Riemann–Roch package on a smooth complete curve. -/
theorem serre_duality_full (C : SmoothCompleteCurve) (d : ℤ) :
    C.χ (1, d) + C.χ (1, C.degK - d) = 0 ∧
    C.χ (1, d) = d + 1 - C.g :=
  SerreDualityCurves.serre_duality_theorem C d

/-- Serre duality applied to `O ↔ K`: `χ(O) + χ(K) = 0`. -/
theorem genus_equality (C : SmoothCompleteCurve) :
    C.χ (1, 0) + C.χ (1, C.degK) = 0 :=
  SerreDualityCurves.serre_duality_chi_O_K C

/-- Riemann–Roch in Serre form: `h⁰(D) − h⁰(K - D) = d + 1 − g`. -/
theorem riemann_roch_serre (C : SmoothCompleteCurve) (d : ℤ)
    (h0_D h0_KD : ℤ) (hRR : h0_D - h0_KD = C.χ (1, d)) :
    h0_D - h0_KD = d + 1 - C.g :=
  SerreDualityCurves.riemann_roch_serre_form_general C d h0_D h0_KD hRR

/-- The degree of the canonical divisor: `deg K_C = 2g − 2`. -/
theorem deg_canonical (C : SmoothCompleteCurve) :
    C.degK = 2 * C.g - 2 :=
  SerreDualityCurves.deg_K_from_serre_duality C

end FullSerreDuality


section Verification

variable (k : Type) [Field k]

/-- Serre duality on `ℙ¹` at the dimension level (verification). -/
theorem P1_serre_duality_dim (n : ℤ) :
    RiemannRoch.dimH1 k n = RiemannRoch.dimH0 k (-2 - n) :=
  RiemannRoch.serre_duality_P1 k n

/-- Riemann–Roch on `ℙ¹`: `h⁰(O(n)) − h¹(O(n)) = n + 1`. -/
theorem P1_riemann_roch (n : ℤ) :
    (RiemannRoch.dimH0 k n : ℤ) - (RiemannRoch.dimH1 k n : ℤ) = n + 1 :=
  RiemannRoch.riemann_roch_P1 k n

/-- Equivalent dimensional form of Serre duality on `ℙ¹`, for `n < -1`. -/
theorem P1_serre_duality_equiv (n : ℤ) (hn : n < -1) :
    Module.finrank k ((ℤ →₀ k) ⧸ (CohomologyP1.NonNeg k ⊔ CohomologyP1.AtMost k n)) =
    Module.finrank k ↥(CechH0 k (-2 - n)) :=
  SerreDualityP1.serre_duality_finrank k n hn

end Verification

end SerreDualityTate

end
