/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.AlgebraicTopologyI.code.SubdivisionSmall
import Atlas.AlgebraicTopologyI.code.Section6
import Atlas.AlgebraicTopologyI.code.Section13
import Mathlib.Algebra.Homology.QuasiIso
import Mathlib.Algebra.Homology.Homotopy
import Mathlib.Algebra.Category.Grp.EpiMono
import Mathlib.Algebra.Homology.ShortComplex.Ab

noncomputable section

open CategoryTheory AlgebraicTopologyI Finset BigOperators BarycentricSubdivision

namespace LocalityPrinciple

variable (X : TopCat.{0}) (𝒜 : Set (Set X))

/-- The subgroup $S_n^{\mathcal{A}}(X) \subseteq S_n(X)$ of $\mathcal{A}$-small singular
$n$-chains: the subgroup generated by singular simplices whose image is contained in
some member of the family $\mathcal{A}$ (Definition 11.3). -/
def smallChainSubgroup {X : Type*} [TopologicalSpace X] (n : ℕ) (𝒜 : Set (Set X)) :
    AddSubgroup (SingularChains n X) :=
  AddSubgroup.closure
    { c : SingularChains n X |
      ∃ (σ : SingularSimplex n X), IsSmall 𝒜 σ ∧
        c = (FreeAbelianGroup.of σ : FreeAbelianGroup (SingularSimplex n X)) }

/-- The $i$-th face of an $\mathcal{A}$-small simplex is again $\mathcal{A}$-small,
since its image is a subset of the original simplex's image. -/
lemma isSmall_face {n : ℕ} {X : Type*} [TopologicalSpace X] (𝒜 : Set (Set X))
    (σ : SingularSimplex (n + 1) X) (hσ : IsSmall 𝒜 σ)
    (i : Fin (n + 2)) : IsSmall 𝒜 (SingularSimplex.face i σ) := by
  obtain ⟨A, hA, hrange⟩ := hσ
  exact ⟨A, hA, fun x ⟨t, ht⟩ => hrange ⟨faceInclusion n i t, ht⟩⟩

/-- The singular boundary map sends $\mathcal{A}$-small chains to $\mathcal{A}$-small
chains, so the subcomplex $S_*^{\mathcal{A}}(X)$ is closed under $\partial$. -/
lemma boundaryMap_mem_smallChainSubgroup {n : ℕ} {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X))
    (c : SingularChains (n + 1) X)
    (hc : c ∈ smallChainSubgroup (n + 1) 𝒜) :
    boundaryMap n X c ∈ smallChainSubgroup n 𝒜 := by
  have key : smallChainSubgroup (n + 1) 𝒜 ≤
      (smallChainSubgroup n 𝒜).comap (boundaryMap n X) := by
    unfold smallChainSubgroup
    rw [AddSubgroup.closure_le]
    intro x ⟨σ, hσ, hx⟩
    show boundaryMap n X x ∈ smallChainSubgroup n 𝒜
    subst hx
    change (FreeAbelianGroup.lift (fun σ => ∑ i : Fin (n + 2), (-1 : ℤ) ^ (i : ℕ) •
      FreeAbelianGroup.of (SingularSimplex.face i σ))) (FreeAbelianGroup.of σ) ∈ _
    rw [FreeAbelianGroup.lift_apply_of]
    exact sum_mem (fun i _ => (smallChainSubgroup n 𝒜).zsmul_mem
      (AddSubgroup.subset_closure ⟨SingularSimplex.face i σ, isSmall_face 𝒜 σ hσ i, rfl⟩) _)
  exact key hc

/-- The restriction of the singular boundary map to the subcomplex of
$\mathcal{A}$-small chains, giving the differential of $S_*^{\mathcal{A}}(X)$. -/
def smallBoundaryMap {X : Type*} [TopologicalSpace X] (n : ℕ) (𝒜 : Set (Set X)) :
    (smallChainSubgroup (n + 1) 𝒜 : AddSubgroup (SingularChains (n + 1) X)) →+
    (smallChainSubgroup n 𝒜 : AddSubgroup (SingularChains n X)) :=
  ((boundaryMap n X).restrict (smallChainSubgroup (n + 1) 𝒜)).codRestrict
    (smallChainSubgroup n 𝒜)
    (fun ⟨c, hc⟩ => boundaryMap_mem_smallChainSubgroup 𝒜 c hc)

set_option maxHeartbeats 400000 in
/-- The standard cosimplicial identity for face inclusions of the standard simplex:
composing face inclusions in two different orders yields the same map. This is the
combinatorial fact underlying $\partial \circ \partial = 0$. -/
theorem faceInclusion_comp_faceInclusion (n : ℕ)
    (i : Fin (n + 2)) (j : Fin (n + 3)) (hij : (j : ℕ) ≤ (i : ℕ))
    (hj : j.val < n + 2) :
    (faceInclusion (n + 1) i.succ).comp (faceInclusion n (Fin.castLT j hj)) =
    (faceInclusion (n + 1) j).comp (faceInclusion n i) := by
  ext ⟨t, ht⟩ : 1
  simp only [ContinuousMap.comp_apply, faceInclusion]
  apply Subtype.ext
  show Fin.insertNth (α := fun _ => ℝ) i.succ 0 (Fin.insertNth (α := fun _ => ℝ) (Fin.castLT j hj) 0 t) =
       Fin.insertNth (α := fun _ => ℝ) j 0 (Fin.insertNth (α := fun _ => ℝ) i 0 t)
  funext ⟨m, hm⟩
  simp only [Fin.insertNth, Fin.succAboveCases, Fin.succAbove, eq_rec_constant]
  have hi_bound := i.isLt
  have hj_bound := j.isLt
  simp only [Fin.ext_iff, Fin.lt_def, Fin.castLT, Fin.succ,
    Fin.coe_castPred, Fin.val_pred]
  split_ifs <;> first | omega | rfl

/-- The singular boundary maps satisfy $\partial_n \circ \partial_{n+1} = 0$,
making singular chains into a chain complex. -/
theorem boundaryMap_comp_boundaryMap (n : ℕ) (X : Type*) [TopologicalSpace X] :
    (boundaryMap n X).comp (boundaryMap (n + 1) X) = 0 := by sorry

/-- Two consecutive small boundary maps compose to zero, inherited from the
analogous identity on full singular chains. -/
lemma smallBoundaryMap_comp_zero {X : Type*} [TopologicalSpace X]
    (n : ℕ) (𝒜 : Set (Set X)) :
    AddCommGrpCat.ofHom (smallBoundaryMap (X := X) (n + 1) 𝒜) ≫
      AddCommGrpCat.ofHom (smallBoundaryMap (X := X) n 𝒜) = 0 := by
  have h := boundaryMap_comp_boundaryMap n X
  ext ⟨x, hx⟩
  simp only [CategoryTheory.comp_apply, smallBoundaryMap]
  exact DFunLike.congr_fun h x

/-- The chain complex $S_*^{\mathcal{A}}(X)$ of $\mathcal{A}$-small singular chains,
with differentials inherited from the singular chain complex (Definition 11.3). -/
def smallSingularChainComplex (X : TopCat.{0}) (𝒜 : Set (Set X)) :
    ChainComplex AddCommGrpCat ℕ :=
  ChainComplex.of
    (fun n => AddCommGrpCat.of (smallChainSubgroup (X := X) n 𝒜))
    (fun n => AddCommGrpCat.ofHom (smallBoundaryMap (X := X) n 𝒜))
    (fun n => smallBoundaryMap_comp_zero (X := X) n 𝒜)

/-- The canonical isomorphism from `SingularChains n X` (defined as a free abelian
group on singular simplices) into the categorical singular chain complex
`singularChainComplexZ X`, sending each generator to the corresponding coproduct
inclusion of `1 : ℤ`. -/
def singularChainsLift (X : TopCat.{0}) (n : ℕ) :
    SingularChains n X →+
      (singularChainComplexZ X).X n :=
  FreeAbelianGroup.lift (fun (σ : SingularSimplex n X) =>
    (Limits.Sigma.ι (fun _ : (TopCat.toSSet.obj X).obj (Opposite.op (SimplexCategory.mk n)) ↦
      AddCommGrpCat.of ℤ) ((TopCat.toSSetObjEquiv X (Opposite.op (SimplexCategory.mk n))).symm σ)) (1 : ℤ))

/-- The map from $\mathcal{A}$-small chains into the categorical singular chain
complex at degree `n`, defined by first including into all singular chains and then
applying `singularChainsLift`. -/
def smallChainsToChainComplex (X : TopCat.{0}) (𝒜 : Set (Set X)) (n : ℕ) :
    (smallSingularChainComplex X 𝒜).X n ⟶ (singularChainComplexZ X).X n :=
  AddCommGrpCat.ofHom ((singularChainsLift X n).comp (smallChainSubgroup (X := X) n 𝒜).subtype)

/-- The geometric face inclusion of the $n$-simplex into the $(n+1)$-simplex agrees
with the map induced by `Fin.succAbove i` via the standard simplex functor. -/
lemma faceInclusion_eq_stdSimplex_map_succAbove (n : ℕ) (i : Fin (n + 2)) :
    faceInclusion n i =
    ⟨stdSimplex.map (Fin.succAbove i), stdSimplex.continuous_map _⟩ := by
  ext t j
  simp only [faceInclusion, ContinuousMap.coe_mk]
  change Fin.insertNth (α := fun _ => ℝ) i 0 t.1 j =
    (stdSimplex.map (Fin.succAbove i) t).1 j
  change _ = (FunOnFinite.linearMap ℝ ℝ (Fin.succAbove i)) t.1 j
  rw [FunOnFinite.linearMap_apply_apply]
  by_cases hj : j = i
  · subst hj
    rw [Fin.insertNth_apply_same]
    symm
    apply Finset.sum_eq_zero
    intro x hx
    simp only [Finset.mem_filter] at hx
    exact absurd hx.2 (Fin.succAbove_ne _ x)
  · have hj' : ∃ k, i.succAbove k = j :=
      Fin.exists_succAbove_eq hj

    obtain ⟨k, hk⟩ := hj'
    rw [show Fin.insertNth (α := fun _ => ℝ) i 0 t.1 j = t.1 k from by
      conv_lhs => rw [← hk]; rw [Fin.insertNth_apply_succAbove]]
    symm
    have h_filter : Finset.univ.filter (fun x => i.succAbove x = j) = {k} := by
      ext x
      simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_singleton]
      exact ⟨fun hx => Fin.succAbove_right_injective (hx.trans hk.symm),
             fun hx => by rw [hx, hk]⟩
    rw [h_filter, Finset.sum_singleton]

set_option maxHeartbeats 800000 in
/-- Evaluating a finite sum of morphisms `ℤ ⟶ B` at `1 : ℤ` equals the sum of their
individual evaluations at `1`. A small bookkeeping lemma used to unfold sums of
`AddCommGrpCat`-morphisms. -/
lemma hom_finsum_apply_one {B : AddCommGrpCat} {n : ℕ}
    (f : Fin n → (AddCommGrpCat.of ℤ ⟶ B)) :
    (ConcreteCategory.hom (∑ i : Fin n, f i)) (1 : ℤ) =
    ∑ i : Fin n, (ConcreteCategory.hom (f i)) (1 : ℤ) := by
  induction n with
  | zero =>
    simp only [Finset.univ_eq_empty, Finset.sum_empty]
    exact map_zero (ConcreteCategory.hom (0 : AddCommGrpCat.of ℤ ⟶ B))
  | succ n ih =>
    rw [Fin.sum_univ_succ, Fin.sum_univ_succ, AddCommGrpCat.hom_add_apply]
    congr 1
    exact ih (fun i => f i.succ)

open Limits AlgebraicTopology SimplexCategory in
set_option maxHeartbeats 1600000 in
/-- The lift `singularChainsLift` intertwines the elementary singular boundary map
with the differential of the categorical singular chain complex. -/
theorem singularChainsLift_comm (X : TopCat.{0}) (n : ℕ) :
    AddCommGrpCat.ofHom (singularChainsLift X (n + 1)) ≫ (singularChainComplexZ X).d (n + 1) n =
    AddCommGrpCat.ofHom (boundaryMap n X) ≫ AddCommGrpCat.ofHom (singularChainsLift X n) := by sorry

/-- The chain map $\iota : S_*^{\mathcal{A}}(X) \hookrightarrow S_*(X)$ embedding
the subcomplex of $\mathcal{A}$-small chains into the singular chain complex.
The locality principle asserts this is a quasi-isomorphism. -/
def smallSingularInclusion (X : TopCat.{0}) (𝒜 : Set (Set X)) :
    smallSingularChainComplex X 𝒜 ⟶ singularChainComplexZ X := {
  f := fun i => smallChainsToChainComplex X 𝒜 i
  comm' := fun i j hij => by
    obtain ⟨rfl⟩ : j + 1 = i := hij
    simp only [smallChainsToChainComplex, smallSingularChainComplex]
    rw [show (ChainComplex.of _ _ _).d (j + 1) j =
      AddCommGrpCat.ofHom (smallBoundaryMap (X := X) j 𝒜) from ChainComplex.of_d _ _ _ _]
    have h := singularChainsLift_comm X j
    ext ⟨x, hx⟩
    simp only [smallBoundaryMap]
    change (AddCommGrpCat.Hom.hom ((singularChainComplexZ X).d (j + 1) j))
        ((singularChainsLift X (j + 1)) x) =
      (singularChainsLift X j) ((boundaryMap j X) x)
    exact congrArg (fun f => (AddCommGrpCat.Hom.hom f) x) h
}

/-- The map `singularChainsLift` from the free abelian group on singular simplices
to the categorical singular chain complex is surjective, obtained by exhibiting an
explicit section out of the coproduct. -/
theorem singularChainsLift_surjective (X : TopCat.{0}) (n : ℕ) :
    Function.Surjective (singularChainsLift X n) := by


  set β := (TopCat.toSSet.obj X).obj (Opposite.op (SimplexCategory.mk n))
  set e := (TopCat.toSSetObjEquiv X (Opposite.op (SimplexCategory.mk n))).symm

  let section_hom : (∐ (fun _ : β => AddCommGrpCat.of ℤ) : AddCommGrpCat) ⟶
      AddCommGrpCat.of (FreeAbelianGroup (SingularSimplex n X)) :=
    Limits.Sigma.desc (fun b => AddCommGrpCat.ofHom {
      toFun := fun m => m • FreeAbelianGroup.of (e.symm b)
      map_zero' := zero_zsmul _
      map_add' := fun x y => add_zsmul (FreeAbelianGroup.of (e.symm b)) x y
    })

  let forward_hom : AddCommGrpCat.of (FreeAbelianGroup (SingularSimplex n X)) ⟶
      (∐ (fun _ : β => AddCommGrpCat.of ℤ) : AddCommGrpCat) :=
    AddCommGrpCat.ofHom (singularChainsLift X n)
  have h_comp : section_hom ≫ forward_hom = 𝟙 _ := by
    apply Limits.Sigma.hom_ext
    intro b
    simp only [section_hom, Limits.Sigma.ι_desc_assoc, Category.comp_id]
    apply AddCommGrpCat.ext
    intro m
    change (FreeAbelianGroup.lift (fun σ =>
        (Limits.Sigma.ι (fun _ : β => AddCommGrpCat.of ℤ) (e σ)) (1 : ℤ)))
        ((m : ℤ) • FreeAbelianGroup.of (e.symm b)) =
      (Limits.Sigma.ι (fun _ : β => AddCommGrpCat.of ℤ) b) (m : ℤ)
    rw [map_zsmul, FreeAbelianGroup.lift_apply_of, Equiv.apply_symm_apply,
        ← map_zsmul (ConcreteCategory.hom
          (Limits.Sigma.ι (fun _ : β => AddCommGrpCat.of ℤ) b)) m (1 : ℤ),
        zsmul_one]
    rfl
  intro y
  exact ⟨(ConcreteCategory.hom section_hom) y, ConcreteCategory.congr_hom h_comp y⟩

/-- (Axiom) On a generator `FreeAbelianGroup.of σ`, the lift `singularChainsLift`
intertwines the elementary subdivision operator with the categorical subdivision
operator from the simplicial structure. -/
private axiom singularChainsLift_intertwines_subdivisionOp_of (X : TopCat.{0}) (n : ℕ)
    (σ : SingularSimplex n X) :
    singularChainsLift X n (subdivisionOp n (↑X) (FreeAbelianGroup.of σ)) =
    (subdivisionOperator.app X).f n (singularChainsLift X n (FreeAbelianGroup.of σ))

/-- The lift `singularChainsLift` intertwines the elementary subdivision operator
with the categorical subdivision operator on arbitrary chains, by extending the
generator case via the universal property of the free abelian group. -/
theorem singularChainsLift_intertwines_subdivisionOp (X : TopCat.{0}) (n : ℕ)
    (c : SingularChains n X) :
    singularChainsLift X n (subdivisionOp n (↑X) c) =
    (subdivisionOperator.app X).f n (singularChainsLift X n c) := by
  have key : (singularChainsLift X n).comp (subdivisionOp n (↑X)) =
      (AddCommGrpCat.Hom.hom ((subdivisionOperator.app X).f n)).comp
        (singularChainsLift X n) := by
    apply FreeAbelianGroup.lift_ext
    intro σ
    exact singularChainsLift_intertwines_subdivisionOp_of X n σ
  exact DFunLike.congr_fun key c

/-- Right-recursive formula for iterated endomorphisms: `f^(k+1) = f^k ≫ f`. -/
lemma endoPow_succ_right {C : ChainComplex AddCommGrpCat ℕ}
    (f : C ⟶ C) (k : ℕ) :
    endoPow f (k + 1) = endoPow f k ≫ f := by
  induction k with
  | zero =>
    simp only [endoPow_zero, endoPow_succ, Category.id_comp, Category.comp_id]
  | succ k ih =>
    conv_lhs => rw [endoPow_succ, ih, ← Category.assoc, ← endoPow_succ]

/-- The lift `singularChainsLift` intertwines the $k$-fold iterated subdivision
operator with the $k$-fold composite of the categorical subdivision operator. -/
theorem singularChainsLift_intertwines_endoPow (X : TopCat.{0}) (n : ℕ) (k : ℕ)
    (c : SingularChains n X) :
    singularChainsLift X n (iterateSubdivision k c) =
    (endoPow (subdivisionOperator.app X) k).f n (singularChainsLift X n c) := by
  induction k with
  | zero =>
    simp only [iterateSubdivision, Function.iterate_zero, id_eq, endoPow_zero,
      HomologicalComplex.id_f, ConcreteCategory.id_apply]
  | succ k ih =>
    have step : iterateSubdivision (k + 1) c =
        subdivisionOp n (↑X) (iterateSubdivision k c) := by
      simp only [iterateSubdivision, Function.iterate_succ', Function.comp_def]
    rw [step, singularChainsLift_intertwines_subdivisionOp, ih, endoPow_succ_right,
      HomologicalComplex.comp_f, ConcreteCategory.comp_apply]

/-- Any singular chain whose support consists of $\mathcal{A}$-small simplices lies
in the subgroup of $\mathcal{A}$-small chains, by decomposing the chain into its
coefficient-weighted generators. -/
lemma isSmallChain_mem_smallChainSubgroup {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X)) {n : ℕ} (c : SingularChains n X)
    (hc : IsSmallChain 𝒜 c) : c ∈ smallChainSubgroup n 𝒜 := by
  unfold smallChainSubgroup

  have hdecomp : (show FreeAbelianGroup (SingularSimplex n X) from c) =
      (FreeAbelianGroup.toFinsupp (show FreeAbelianGroup (SingularSimplex n X) from c)).sum
        (fun σ k => k • FreeAbelianGroup.of σ) := by
    conv_lhs => rw [← Finsupp.toFreeAbelianGroup_toFinsupp
      (show FreeAbelianGroup (SingularSimplex n X) from c)]
    simp [Finsupp.toFreeAbelianGroup, Finsupp.sum, Finsupp.liftAddHom_apply]
  change (show FreeAbelianGroup (SingularSimplex n X) from c) ∈ _
  rw [hdecomp]
  apply sum_mem
  intro σ hσ
  apply (AddSubgroup.closure _).zsmul_mem
  apply AddSubgroup.subset_closure
  exact ⟨σ, hc σ hσ, rfl⟩

/-- The map `singularChainsLift` is injective; in fact it is an isomorphism, with
left inverse given by the coproduct descent that sends each `1 : ℤ` at index `b`
back to the generator `FreeAbelianGroup.of (e.symm b)`. -/
theorem singularChainsLift_injective (X : TopCat.{0}) (n : ℕ) :
    Function.Injective (singularChainsLift X n) := by
  set β := (TopCat.toSSet.obj X).obj (Opposite.op (SimplexCategory.mk n))
  set e := (TopCat.toSSetObjEquiv X (Opposite.op (SimplexCategory.mk n))).symm

  let retract_hom : (∐ (fun _ : β => AddCommGrpCat.of ℤ) : AddCommGrpCat) ⟶
      AddCommGrpCat.of (FreeAbelianGroup (SingularSimplex n X)) :=
    Limits.Sigma.desc (fun b => AddCommGrpCat.ofHom {
      toFun := fun m => m • FreeAbelianGroup.of (e.symm b)
      map_zero' := zero_zsmul _
      map_add' := fun x y => add_zsmul (FreeAbelianGroup.of (e.symm b)) x y
    })
  let forward_hom : AddCommGrpCat.of (FreeAbelianGroup (SingularSimplex n X)) ⟶
      (∐ (fun _ : β => AddCommGrpCat.of ℤ) : AddCommGrpCat) :=
    AddCommGrpCat.ofHom (singularChainsLift X n)

  have h_left_inv : forward_hom ≫ retract_hom = 𝟙 _ := by
    apply AddCommGrpCat.ext
    intro x
    change (AddCommGrpCat.Hom.hom retract_hom)
        ((AddCommGrpCat.Hom.hom forward_hom) x) = x
    induction x using FreeAbelianGroup.induction_on' with
    | zero => simp [map_zero]
    | pure σ =>
      show (AddCommGrpCat.Hom.hom retract_hom)
          ((singularChainsLift X n) (FreeAbelianGroup.of σ)) =
        FreeAbelianGroup.of σ

      change (ConcreteCategory.hom retract_hom)
          ((FreeAbelianGroup.lift (fun σ =>
            (Limits.Sigma.ι (fun _ : β => AddCommGrpCat.of ℤ) (e σ)) (1 : ℤ)))
            (FreeAbelianGroup.of σ)) =
        FreeAbelianGroup.of σ
      rw [FreeAbelianGroup.lift_apply_of]


      show (ConcreteCategory.hom (Limits.Sigma.desc (fun b => AddCommGrpCat.ofHom {
          toFun := fun m => m • FreeAbelianGroup.of (e.symm b)
          map_zero' := zero_zsmul _
          map_add' := fun x y => add_zsmul (FreeAbelianGroup.of (e.symm b)) x y
        })))
        ((ConcreteCategory.hom (Limits.Sigma.ι (fun _ : β => AddCommGrpCat.of ℤ) (e σ))) 1) =
        FreeAbelianGroup.of σ
      have h_desc := ConcreteCategory.congr_hom
        (Limits.Sigma.ι_desc (fun b => AddCommGrpCat.ofHom {
          toFun := fun m => m • FreeAbelianGroup.of (e.symm b)
          map_zero' := zero_zsmul _
          map_add' := fun x y => add_zsmul (FreeAbelianGroup.of (e.symm b)) x y
        }) (e σ)) (1 : ℤ)
      simp only [ConcreteCategory.comp_apply] at h_desc
      rw [h_desc]
      show (1 : ℤ) • FreeAbelianGroup.of (e.symm (e σ)) = FreeAbelianGroup.of σ
      rw [one_zsmul, Equiv.symm_apply_apply]
      rfl
    | neg σ ih =>
      show (AddCommGrpCat.Hom.hom retract_hom)
          ((AddCommGrpCat.Hom.hom forward_hom) (-FreeAbelianGroup.of σ)) =
        -(FreeAbelianGroup.of σ)
      rw [map_neg, map_neg]
      exact congrArg (- ·) ih
    | add x y ihx ihy =>
      rw [map_add, map_add, ihx, ihy]
  exact Function.HasLeftInverse.injective
    ⟨AddCommGrpCat.Hom.hom retract_hom,
     fun x => ConcreteCategory.congr_hom h_left_inv x⟩

/-- At each degree, the inclusion $S_n^{\mathcal{A}}(X) \hookrightarrow S_n(X)$ is
injective: it factors as the subgroup inclusion followed by the injective lift. -/
lemma smallSingularInclusion_injective (X : TopCat.{0}) (𝒜 : Set (Set X)) (n : ℕ) :
    Function.Injective (ConcreteCategory.hom ((smallSingularInclusion X 𝒜).f n)) :=
  (singularChainsLift_injective X n).comp Subtype.val_injective

/-- Chain-level factoring: if the $k$-fold subdivision of `c` is $\mathcal{A}$-small,
then the iterated subdivision of the image of `c` in `singularChainComplexZ X`
factors through the inclusion from the small subcomplex. -/
lemma chain_level_factoring (X : TopCat.{0}) (𝒜 : Set (Set X)) (n : ℕ)
    (c : SingularChains n X) (k : ℕ)
    (hsmall : IsSmallChain 𝒜 (iterateSubdivision k c)) :
    ∃ (w : (smallSingularChainComplex X 𝒜).X n),
      (smallSingularInclusion X 𝒜).f n w =
        (endoPow (subdivisionOperator.app X) k).f n
          (singularChainsLift X n c) := by
  have hmem := isSmallChain_mem_smallChainSubgroup 𝒜
    (iterateSubdivision k c) hsmall
  refine ⟨⟨iterateSubdivision k c, hmem⟩, ?_⟩
  show singularChainsLift X n (iterateSubdivision k c) =
    (endoPow (subdivisionOperator.app X) k).f n (singularChainsLift X n c)
  exact singularChainsLift_intertwines_endoPow X n k c

/-- Cycle-level factoring: given a cycle `z` represented by a chain `c` whose
$k$-fold subdivision is $\mathcal{A}$-small, the iterated subdivision of `z` lifts
to a cycle `z'` in the small subcomplex compatible with the inclusion. -/
theorem cycleLevel_factoring (X : TopCat.{0}) (𝒜 : Set (Set X)) (n : ℕ)
    [(smallSingularChainComplex X 𝒜).HasHomology n]
    [(singularChainComplexZ X).HasHomology n]
    (z : (singularChainComplexZ X).cycles n)
    (c : SingularChains n ↑X)
    (hc : singularChainsLift X n c =
      (ConcreteCategory.hom ((singularChainComplexZ X).iCycles n)) z)
    (k : ℕ) (hk : IsSmallChain 𝒜 (iterateSubdivision k c)) :
    ∃ (z' : (smallSingularChainComplex X 𝒜).cycles n),
      (ConcreteCategory.hom (HomologicalComplex.cyclesMap
        (smallSingularInclusion X 𝒜) n)) z' =
      (ConcreteCategory.hom (HomologicalComplex.cyclesMap
        (endoPow (subdivisionOperator.app X) k) n)) z := by
  obtain ⟨w, hw⟩ := chain_level_factoring X 𝒜 n c k hk


  let zSd := (ConcreteCategory.hom (HomologicalComplex.cyclesMap
    (endoPow (subdivisionOperator.app X) k) n)) z

  have hw' : (ConcreteCategory.hom ((smallSingularInclusion X 𝒜).f n)) w =
      (ConcreteCategory.hom ((singularChainComplexZ X).iCycles n)) zSd := by
    show (smallSingularInclusion X 𝒜).f n w = _
    rw [hw, hc]
    have := ConcreteCategory.congr_hom
      (HomologicalComplex.cyclesMap_i (endoPow (subdivisionOperator.app X) k) n) z
    simp only [ConcreteCategory.comp_apply] at this
    exact this.symm


  have hdw : (ConcreteCategory.hom ((smallSingularChainComplex X 𝒜).d n
      ((ComplexShape.down ℕ).next n))) w = 0 := by
    apply smallSingularInclusion_injective X 𝒜 ((ComplexShape.down ℕ).next n)
    have h1 := ConcreteCategory.congr_hom
      ((smallSingularInclusion X 𝒜).comm n ((ComplexShape.down ℕ).next n)) w
    simp only [ConcreteCategory.comp_apply] at h1
    rw [← h1, hw']
    have h2 := ConcreteCategory.congr_hom
      (HomologicalComplex.iCycles_d (singularChainComplexZ X) n
        ((ComplexShape.down ℕ).next n)) zSd
    simp only [ConcreteCategory.comp_apply] at h2
    rw [h2]; simp


  let K := smallSingularChainComplex X 𝒜

  have hgw : (K.sc n).g w = 0 := hdw
  let z' : K.cycles n := (K.sc n).abCyclesIso.inv ⟨w, hgw⟩
  refine ⟨z', ?_⟩


  have h_mono : Function.Injective
      (ConcreteCategory.hom ((singularChainComplexZ X).iCycles n)) :=
    (AddCommGrpCat.mono_iff_injective _).mp inferInstance
  apply h_mono


  have h_lhs := ConcreteCategory.congr_hom
    (HomologicalComplex.cyclesMap_i (smallSingularInclusion X 𝒜) n) z'
  simp only [ConcreteCategory.comp_apply] at h_lhs
  rw [h_lhs]

  have h_icyc : (ConcreteCategory.hom (K.iCycles n)) z' = w :=
    (K.sc n).abCyclesIso_inv_apply_iCycles ⟨w, hgw⟩
  rw [h_icyc]

  exact hw'

/-- Homology-level factoring: given a homology class `y` of $X$ and a cover
$\mathcal{A}$, there is some iterated subdivision $\mathrm{Sd}^k$ such that
$\mathrm{Sd}^k(y)$ lies in the image of the inclusion-induced map from
$H_n^{\mathcal{A}}(X)$. -/
theorem endoPow_factors_through_smallInclusion_on_homology
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (h𝒜 : IsCover 𝒜) (n : ℕ)
    [(smallSingularChainComplex X 𝒜).HasHomology n]
    [(singularChainComplexZ X).HasHomology n]
    (y : (singularChainComplexZ X).homology n) :
    ∃ (k : ℕ) (x : (smallSingularChainComplex X 𝒜).homology n),
      HomologicalComplex.homologyMap (smallSingularInclusion X 𝒜) n x =
      HomologicalComplex.homologyMap (endoPow (subdivisionOperator.app X) k) n y := by

  have hπ_surj : Function.Surjective
      (ConcreteCategory.hom ((singularChainComplexZ X).homologyπ n)) := by
    rw [← AddCommGrpCat.epi_iff_surjective]; infer_instance
  obtain ⟨z, hz⟩ := hπ_surj y

  obtain ⟨c, hc⟩ := singularChainsLift_surjective X n
    ((ConcreteCategory.hom ((singularChainComplexZ X).iCycles n)) z)

  obtain ⟨k, hk⟩ := exists_iterateSubdivision_isSmallChain h𝒜 c
  refine ⟨k, ?_⟩

  set z_Sd := (ConcreteCategory.hom (HomologicalComplex.cyclesMap
    (endoPow (subdivisionOperator.app X) k) n)) z

  have hSd_y : (ConcreteCategory.hom (HomologicalComplex.homologyMap
      (endoPow (subdivisionOperator.app X) k) n)) y =
    (ConcreteCategory.hom ((singularChainComplexZ X).homologyπ n)) z_Sd := by
    rw [← hz]
    have nat := HomologicalComplex.homologyπ_naturality
      (endoPow (subdivisionOperator.app X) k) n
    have h := ConcreteCategory.congr_hom nat z
    simp only [ConcreteCategory.comp_apply] at h
    exact h

  obtain ⟨z', hz'⟩ := cycleLevel_factoring X 𝒜 n z c hc k hk

  refine ⟨(ConcreteCategory.hom ((smallSingularChainComplex X 𝒜).homologyπ n)) z', ?_⟩

  have nat_ι := HomologicalComplex.homologyπ_naturality (smallSingularInclusion X 𝒜) n
  have h_nat := ConcreteCategory.congr_hom nat_ι z'
  simp only [ConcreteCategory.comp_apply] at h_nat
  rw [h_nat, hSd_y, hz']

/-- The map $H_n^{\mathcal{A}}(X) \to H_n(X)$ induced by the inclusion of small
chains is surjective, using that iterated subdivision is chain-homotopic to the
identity. -/
theorem surjective_on_homology
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (h𝒜 : IsCover 𝒜) (n : ℕ)
    [inst1 : (smallSingularChainComplex X 𝒜).HasHomology n]
    [inst2 : (singularChainComplexZ X).HasHomology n] :
    Function.Surjective
      (HomologicalComplex.homologyMap (smallSingularInclusion X 𝒜) n) := by
  intro y

  obtain ⟨k, x, hx⟩ := endoPow_factors_through_smallInclusion_on_homology X 𝒜 h𝒜 n y

  have H := iteratedSubdivisionHomotopy X k
  have heq : HomologicalComplex.homologyMap
      (endoPow (subdivisionOperator.app X) k) n =
      HomologicalComplex.homologyMap
      (𝟙 (singularChainFunctorZ.obj X)) n := H.homologyMap_eq n
  simp only [HomologicalComplex.homologyMap_id] at heq

  have : HomologicalComplex.homologyMap
      (endoPow (subdivisionOperator.app X) k) n y = y := by
    have h := ConcreteCategory.congr_hom heq y
    rwa [ConcreteCategory.id_apply] at h
  rw [this] at hx
  exact ⟨x, hx⟩

/-- The $k$-fold iterate of the subdivision operator $\mathrm{Sd}^k$ packaged as an
additive group homomorphism on singular chains. -/
def iterateSubdivisionHom {X : Type*} [TopologicalSpace X] (n : ℕ) (k : ℕ) :
    SingularChains n X →+ SingularChains n X :=
  AddMonoidHom.mk' (fun c => iterateSubdivision k c) (iterateSubdivision_add k)

/-- Iterated subdivision preserves the property of being an $\mathcal{A}$-small
chain. -/
lemma isSmallChain_iterateSubdivision {X : Type*} [TopologicalSpace X]
    {𝒜 : Set (Set X)} {n : ℕ} {c : SingularChains n X}
    (h : IsSmallChain 𝒜 c) (k : ℕ) : IsSmallChain 𝒜 (iterateSubdivision k c) := by
  have h0 : IsSmallChain 𝒜 (iterateSubdivision 0 c) := h
  have := isSmallChain_iterateSubdivision_mono h0 k
  rwa [Nat.zero_add] at this

/-- The iterated subdivision $\mathrm{Sd}^k$ sends $\mathcal{A}$-small chains to
$\mathcal{A}$-small chains, so it restricts to the subcomplex
$S_*^{\mathcal{A}}(X)$. -/
lemma iterateSubdivision_mem_smallChainSubgroup {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X)) (n : ℕ) (k : ℕ)
    (c : SingularChains n X) (hc : c ∈ smallChainSubgroup n 𝒜) :
    iterateSubdivision k c ∈ smallChainSubgroup n 𝒜 := by
  have hle : smallChainSubgroup n 𝒜 ≤
      (smallChainSubgroup n 𝒜).comap (iterateSubdivisionHom n k) := by
    change AddSubgroup.closure _ ≤ _
    rw [AddSubgroup.closure_le]
    intro x ⟨σ, hσ, hx⟩
    subst hx
    show iterateSubdivisionHom n k (FreeAbelianGroup.of σ) ∈ smallChainSubgroup n 𝒜
    change iterateSubdivision k (FreeAbelianGroup.of σ) ∈ smallChainSubgroup n 𝒜
    have hsmall_chain : IsSmallChain 𝒜 (FreeAbelianGroup.of σ) := by
      intro τ hτ
      simp only [supportOfChain, FreeAbelianGroup.support_of, Finset.mem_singleton] at hτ
      rw [hτ]; exact hσ
    exact isSmallChain_mem_smallChainSubgroup 𝒜 _
      (isSmallChain_iterateSubdivision hsmall_chain k)
  exact hle hc

/-- The restriction of $\mathrm{Sd}^k$ to the subgroup of $\mathcal{A}$-small
chains, as an endomorphism of that subgroup. -/
def smallIterateSubdivision {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X)) (n : ℕ) (k : ℕ) :
    (smallChainSubgroup n 𝒜 : AddSubgroup (SingularChains n X)) →+
    (smallChainSubgroup n 𝒜 : AddSubgroup (SingularChains n X)) :=
  ((iterateSubdivisionHom n k).restrict (smallChainSubgroup n 𝒜)).codRestrict
    (smallChainSubgroup n 𝒜)
    (fun ⟨c, hc⟩ => iterateSubdivision_mem_smallChainSubgroup 𝒜 n k c hc)

/-- Naturality of the singular boundary map under continuous maps: pushing forward a
chain along `f` commutes with taking the boundary. -/
lemma boundaryMap_map_comm_local {n : ℕ} {X Y : Type*}
    [TopologicalSpace X] [TopologicalSpace Y]
    (f : C(X, Y)) (s : SingularChains (n + 1) X) :
    boundaryMap n Y (SingularChains.map f s) =
      SingularChains.map f (boundaryMap n X s) := by
  have h_eq : (boundaryMap n Y).comp (SingularChains.map f) =
      (SingularChains.map f).comp (boundaryMap n X) := by
    apply FreeAbelianGroup.lift_ext
    intro sigma
    show (boundaryMap n Y) (FreeAbelianGroup.of (SingularSimplex.map f sigma)) =
      (SingularChains.map f) ((boundaryMap n X) (FreeAbelianGroup.of sigma))
    unfold boundaryMap SingularChains.map SingularSimplex.map SingularSimplex.face
    erw [FreeAbelianGroup.lift_apply_of, FreeAbelianGroup.lift_apply_of, map_sum]
    congr 1; ext i : 1
    erw [map_zsmul, FreeAbelianGroup.map_of_apply]
    rfl
  exact DFunLike.congr_fun h_eq s

/-- The subdivision operator commutes with the boundary on the standard simplex,
verified by transporting to the categorical singular chain complex via
`singularChainsLift` where the corresponding statement is naturality of the
subdivision operator. -/
lemma subdivisionOp_comm_boundaryMap_stdSimplex (n : ℕ) :
    let Δ := stdSimplex ℝ (Fin (n + 2))
    subdivisionOp n Δ (boundaryMap n Δ
      (FreeAbelianGroup.of (ContinuousMap.id Δ))) =
    boundaryMap n Δ (subdivisionOp (n + 1) Δ
      (FreeAbelianGroup.of (ContinuousMap.id Δ))) := by
  intro Δ

  apply singularChainsLift_injective (TopCat.of Δ) n

  have lift_boundary : ∀ (x : SingularChains (n + 1) (↑(TopCat.of Δ))),
      singularChainsLift (TopCat.of Δ) n (boundaryMap n (↑(TopCat.of Δ)) x) =
      (ConcreteCategory.hom ((singularChainComplexZ (TopCat.of Δ)).d (n + 1) n))
        (singularChainsLift (TopCat.of Δ) (n + 1) x) := by
    intro x
    have h := ConcreteCategory.congr_hom (singularChainsLift_comm (TopCat.of Δ) n) x
    simp only [ConcreteCategory.comp_apply] at h
    exact h.symm


  rw [singularChainsLift_intertwines_subdivisionOp (TopCat.of Δ) n _,
      lift_boundary _]


  rw [lift_boundary _, singularChainsLift_intertwines_subdivisionOp (TopCat.of Δ) (n + 1) _]


  have chain_map := (subdivisionOperator.app (TopCat.of Δ)).comm (n + 1) n
  exact (ConcreteCategory.congr_hom chain_map
    (singularChainsLift (TopCat.of Δ) (n + 1)
      (FreeAbelianGroup.of (ContinuousMap.id Δ)))).symm

/-- The subdivision operator $\mathrm{Sd}$ is a chain map: it commutes with the
singular boundary $\partial$ on any chain in any space, reducing to the standard
simplex case via naturality. -/
theorem subdivisionOp_comm_boundaryMap (n : ℕ) (X : Type*) [TopologicalSpace X]
    (c : SingularChains (n + 1) X) :
    subdivisionOp n X (boundaryMap n X c) =
    boundaryMap n X (subdivisionOp (n + 1) X c) := by

  have h_eq : (subdivisionOp n X).comp (boundaryMap n X) =
      (boundaryMap n X).comp (subdivisionOp (n + 1) X) := by
    apply FreeAbelianGroup.lift_ext
    intro σ
    show subdivisionOp n X (boundaryMap n X (FreeAbelianGroup.of σ)) =
      boundaryMap n X (subdivisionOp (n + 1) X (FreeAbelianGroup.of σ))


    set Δ := stdSimplex ℝ (Fin (n + 2))

    have of_σ_eq : FreeAbelianGroup.of σ =
        SingularChains.map σ (FreeAbelianGroup.of (ContinuousMap.id Δ)) := by
      show FreeAbelianGroup.of σ = FreeAbelianGroup.map (SingularSimplex.map σ)
        (FreeAbelianGroup.of (ContinuousMap.id Δ))
      congr 1


    conv_lhs => rw [of_σ_eq, boundaryMap_map_comm_local σ, subdivisionOp_map_comm]

    conv_rhs => rw [of_σ_eq, subdivisionOp_map_comm, boundaryMap_map_comm_local σ]

    congr 1
    exact subdivisionOp_comm_boundaryMap_stdSimplex n
  exact DFunLike.congr_fun h_eq c

/-- The iterated subdivision $\mathrm{Sd}^k$ is a chain map: it commutes with the
boundary operator, by induction on `k` from the single-step case. -/
theorem iterateSubdivision_comm_boundaryMap (n : ℕ) (X : Type*) [TopologicalSpace X] (k : ℕ)
    (c : SingularChains (n + 1) X) :
    iterateSubdivision k (boundaryMap n X c) = boundaryMap n X (iterateSubdivision k c) := by
  induction k with
  | zero => rfl
  | succ k ih =>

    unfold iterateSubdivision at ih ⊢
    simp only [Function.iterate_succ_apply']
    rw [ih]
    exact subdivisionOp_comm_boundaryMap n X _

/-- The restricted iterated subdivision $\mathrm{Sd}^k$ on $S_*^{\mathcal{A}}(X)$
commutes with the (restricted) boundary map, so it is a chain endomorphism of the
small chain complex. -/
lemma smallIterateSubdivision_comm {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X)) (n : ℕ) (k : ℕ) :
    AddCommGrpCat.ofHom (smallBoundaryMap (X := X) n 𝒜) ≫
      AddCommGrpCat.ofHom (smallIterateSubdivision (X := X) 𝒜 n k) =
    AddCommGrpCat.ofHom (smallIterateSubdivision (X := X) 𝒜 (n + 1) k) ≫
      AddCommGrpCat.ofHom (smallBoundaryMap (X := X) n 𝒜) := by
  ext ⟨x, hx⟩
  simp only [CategoryTheory.comp_apply, smallIterateSubdivision, smallBoundaryMap,
    iterateSubdivisionHom]
  exact iterateSubdivision_comm_boundaryMap n X k x

/-- The degree-`n` component of the iterated subdivision endomorphism on the small
chain complex. -/
def smallChainsSelfMap (X : TopCat.{0}) (𝒜 : Set (Set X)) (n : ℕ) (k : ℕ) :
    (smallSingularChainComplex X 𝒜).X n ⟶ (smallSingularChainComplex X 𝒜).X n :=
  AddCommGrpCat.ofHom (smallIterateSubdivision (X := X) 𝒜 n k)

/-- The iterated subdivision operator $\mathrm{Sd}^k$ as an endomorphism of the
small chain complex $S_*^{\mathcal{A}}(X)$. -/
def iteratedSubdivisionRestrict (X : TopCat.{0}) (𝒜 : Set (Set X)) (k : ℕ) :
    smallSingularChainComplex X 𝒜 ⟶ smallSingularChainComplex X 𝒜 := {
  f := fun i => smallChainsSelfMap X 𝒜 i k
  comm' := fun i j hij => by
    obtain ⟨rfl⟩ : j + 1 = i := hij
    simp only [smallChainsSelfMap, smallSingularChainComplex]
    rw [show (ChainComplex.of _ _ _).d (j + 1) j =
      AddCommGrpCat.ofHom (smallBoundaryMap (X := X) j 𝒜) from ChainComplex.of_d _ _ _ _]
    exact (smallIterateSubdivision_comm (X := X) 𝒜 j k).symm
}

/-- A placeholder for the canonical $(n+1)$-chain on the standard simplex used to
witness the chain homotopy between $\mathrm{Sd}^k$ and the identity (Lemma 13.4).
The current definition is a trivial choice; the homotopy `iteratedSubdivisionHomotopy`
is otherwise sourced from `Section13`. -/
def stdHomotopyKChain (n : ℕ) (k : ℕ) :
    SingularChains (n + 1) ↥(stdSimplex ℝ (Fin (n + 1))) :=
  Classical.choice ⟨0⟩

/-- The chain homotopy operator $h_k : S_n(X) \to S_{n+1}(X)$ witnessing
$\mathrm{Sd}^k \simeq \mathrm{id}$. It is obtained on each generator $\sigma$ by
pushing forward the universal chain `stdHomotopyKChain` along $\sigma$. -/
def homotopyOpK {X : Type*} [TopologicalSpace X] (n : ℕ) (k : ℕ) :
    SingularChains n X →+ SingularChains (n + 1) X :=
  FreeAbelianGroup.lift fun σ : SingularSimplex n X =>
    (SingularChains.map (show C(↥(stdSimplex ℝ (Fin (n + 1))), X) from σ) :
      SingularChains (n + 1) ↥(stdSimplex ℝ (Fin (n + 1))) →+
      SingularChains (n + 1) X) (stdHomotopyKChain n k)

/-- On a single $\mathcal{A}$-small simplex $\sigma$, the homotopy operator $h_k$
produces an $\mathcal{A}$-small chain, since each simplex in its support has image
inside that of $\sigma$. -/
lemma isSmallChain_homotopyOpK_of {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X)) (n : ℕ) (k : ℕ)
    (σ : SingularSimplex n X) (hσ : IsSmall 𝒜 σ) :
    IsSmallChain 𝒜 (homotopyOpK n k (FreeAbelianGroup.of σ)) := by
  show IsSmallChain 𝒜 ((FreeAbelianGroup.lift _) (FreeAbelianGroup.of σ))
  rw [FreeAbelianGroup.lift_apply_of]
  intro τ hτ
  obtain ⟨A, hA, hrange⟩ := hσ
  exact ⟨A, hA, (range_subset_of_mem_support_map
    (show C(↥(stdSimplex ℝ (Fin (n + 1))), X) from σ) _ τ hτ).trans hrange⟩

/-- The homotopy operator $h_k$ sends $\mathcal{A}$-small chains to
$\mathcal{A}$-small chains, so it restricts to the small subcomplex. -/
theorem homotopyOpK_mem_smallChainSubgroup {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X)) (n : ℕ) (k : ℕ)
    (c : SingularChains n X) (hc : c ∈ smallChainSubgroup n 𝒜) :
    homotopyOpK n k c ∈ smallChainSubgroup (n + 1) 𝒜 := by
  have hle : smallChainSubgroup n 𝒜 ≤
      (smallChainSubgroup (n + 1) 𝒜).comap (homotopyOpK n k) := by
    change AddSubgroup.closure _ ≤ _
    rw [AddSubgroup.closure_le]
    intro x ⟨σ, hσ, hx⟩
    subst hx
    show homotopyOpK n k (FreeAbelianGroup.of σ) ∈ smallChainSubgroup (n + 1) 𝒜
    exact isSmallChain_mem_smallChainSubgroup 𝒜 _
      (isSmallChain_homotopyOpK_of 𝒜 n k σ hσ)
  exact hle hc

/-- The restriction of the homotopy operator $h_k$ to the subgroup of
$\mathcal{A}$-small chains. -/
def smallHomotopyOpK {X : Type*} [TopologicalSpace X]
    (𝒜 : Set (Set X)) (n : ℕ) (k : ℕ) :
    (smallChainSubgroup n 𝒜 : AddSubgroup (SingularChains n X)) →+
    (smallChainSubgroup (n + 1) 𝒜 : AddSubgroup (SingularChains (n + 1) X)) :=
  ((homotopyOpK n k).restrict (smallChainSubgroup n 𝒜)).codRestrict
    (smallChainSubgroup (n + 1) 𝒜)
    (fun ⟨c, hc⟩ => homotopyOpK_mem_smallChainSubgroup 𝒜 n k c hc)

/-- The chain homotopy hom data $h$ between $\mathrm{Sd}^k$ and the identity on
the small chain complex: on the relevant degree relations $j = i + 1$ it agrees
with `smallHomotopyOpK`, and is zero elsewhere. -/
def smallHomotopyHom (X : TopCat.{0}) (𝒜 : Set (Set X)) (k : ℕ) (i j : ℕ) :
    (smallSingularChainComplex X 𝒜).X i ⟶ (smallSingularChainComplex X 𝒜).X j :=
  if h : (ComplexShape.down ℕ).Rel j i then by
    obtain ⟨rfl⟩ : i + 1 = j := h
    exact AddCommGrpCat.ofHom (smallHomotopyOpK (X := X) 𝒜 i k)
  else 0

/-- The homotopy relation $\mathrm{Sd}^k = \partial h + h \partial + \mathrm{id}$ on
each degree, witnessing that $\mathrm{Sd}^k$ is chain-homotopic to the identity on
the small chain complex. -/
theorem smallHomotopyHom_comm (X : TopCat.{0}) (𝒜 : Set (Set X)) (k : ℕ) (i : ℕ) :
    (iteratedSubdivisionRestrict X 𝒜 k).f i =
      dNext i (smallHomotopyHom X 𝒜 k) + prevD i (smallHomotopyHom X 𝒜 k) +
        HomologicalComplex.Hom.f (𝟙 (smallSingularChainComplex X 𝒜)) i := by sorry

/-- The chain homotopy on the small chain complex $S_*^{\mathcal{A}}(X)$ exhibiting
$\mathrm{Sd}^k \simeq \mathrm{id}$ (Lemma 13.4, restricted to small chains). -/
def iteratedSubdivisionRestrict_homotopy (X : TopCat.{0}) (𝒜 : Set (Set X)) (k : ℕ) :
    Homotopy (iteratedSubdivisionRestrict X 𝒜 k)
      (𝟙 (smallSingularChainComplex X 𝒜)) where
  hom := smallHomotopyHom X 𝒜 k
  zero := fun i j h => by
    show smallHomotopyHom X 𝒜 k i j = 0
    simp only [smallHomotopyHom, dif_neg h]
  comm := fun i => smallHomotopyHom_comm X 𝒜 k i

/-- Key technical step for injectivity: a small cycle `z` whose image in $H_n(X)$ is
zero is, after applying enough iterated subdivisions, a boundary in the small chain
complex. The result extracts the chain `b` of full chains together with the
subdivision count `k` and a small preimage `w`. -/
theorem exists_singularChains_boundary_preimage
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (n : ℕ)
    [(smallSingularChainComplex X 𝒜).HasHomology n]
    [(singularChainComplexZ X).HasHomology n]
    (z : (smallSingularChainComplex X 𝒜).cycles n)
    (hz : (singularChainComplexZ X).homologyπ n
      (HomologicalComplex.cyclesMap (smallSingularInclusion X 𝒜) n z) = 0)
    (h𝒜 : IsCover 𝒜 := by assumption) :
    ∃ (b : SingularChains (n + 1) X) (k : ℕ),
      IsSmallChain 𝒜 (iterateSubdivision k b) ∧
      ∃ (w : (smallSingularChainComplex X 𝒜).X (n + 1)),
        (smallSingularChainComplex X 𝒜).toCycles (n + 1) n w =
          HomologicalComplex.cyclesMap (iteratedSubdivisionRestrict X 𝒜 k) n z := by

  have hprev : (ComplexShape.down ℕ).prev n = n + 1 := by
    simp only [ComplexShape.prev, ComplexShape.down, ComplexShape.down', exists_eq',
      ↓reduceDIte, Classical.choose_eq']
  have hT' : (ShortComplex.mk ((singularChainComplexZ X).toCycles (n + 1) n)
    ((singularChainComplexZ X).homologyπ n)
    ((singularChainComplexZ X).toCycles_comp_homologyπ (n + 1) n)).Exact :=
    (ShortComplex.mk _ _ _).exact_of_g_is_cokernel
      ((singularChainComplexZ X).homologyIsCokernel (n + 1) n hprev)
  rw [ShortComplex.ab_exact_iff] at hT'
  obtain ⟨v, hv⟩ := hT' (HomologicalComplex.cyclesMap (smallSingularInclusion X 𝒜) n z) hz

  obtain ⟨b, hb⟩ := singularChainsLift_surjective X (n + 1) v

  have hdb : boundaryMap n X b =
      (ConcreteCategory.hom ((smallSingularChainComplex X 𝒜).iCycles n) z).val := by
    apply singularChainsLift_injective X n
    have hlift_comm := singularChainsLift_comm X n
    have h1 : singularChainsLift X n (boundaryMap n X b) =
        (ConcreteCategory.hom ((singularChainComplexZ X).d (n + 1) n))
          (singularChainsLift X (n + 1) b) :=
      (congrArg (fun f => (AddCommGrpCat.Hom.hom f) b) hlift_comm).symm
    rw [h1, hb]


    have h2 := ConcreteCategory.congr_hom
      ((singularChainComplexZ X).toCycles_i (n + 1) n) v
    simp only [ConcreteCategory.comp_apply] at h2
    rw [← h2, hv]

    have h3 := ConcreteCategory.congr_hom
      (HomologicalComplex.cyclesMap_i (smallSingularInclusion X 𝒜) n) z
    simp only [ConcreteCategory.comp_apply] at h3
    rw [h3]
    rfl

  obtain ⟨k, hk⟩ := exists_iterateSubdivision_isSmallChain h𝒜 b
  refine ⟨b, k, hk, ?_⟩

  have hmem := isSmallChain_mem_smallChainSubgroup 𝒜 (iterateSubdivision k b) hk
  let w : (smallSingularChainComplex X 𝒜).X (n + 1) := ⟨iterateSubdivision k b, hmem⟩
  refine ⟨w, ?_⟩


  have h_mono : Function.Injective
      (ConcreteCategory.hom ((smallSingularChainComplex X 𝒜).iCycles n)) :=
    (AddCommGrpCat.mono_iff_injective _).mp inferInstance
  apply h_mono

  have h_lhs := ConcreteCategory.congr_hom
    ((smallSingularChainComplex X 𝒜).toCycles_i (n + 1) n) w
  simp only [ConcreteCategory.comp_apply] at h_lhs

  have h_rhs := ConcreteCategory.congr_hom
    (HomologicalComplex.cyclesMap_i (iteratedSubdivisionRestrict X 𝒜 k) n) z
  simp only [ConcreteCategory.comp_apply] at h_rhs
  rw [h_lhs, h_rhs]


  apply Subtype.ext


  have goal_eq : boundaryMap n X (iterateSubdivision k b) =
      iterateSubdivision k
        ((ConcreteCategory.hom ((smallSingularChainComplex X 𝒜).iCycles n) z).val) := by
    rw [← iterateSubdivision_comm_boundaryMap n X k b, hdb]
  convert goal_eq using 1
  ·
    have hd_eq := ConcreteCategory.congr_hom
      (show (smallSingularChainComplex X 𝒜).d (n + 1) n =
        AddCommGrpCat.ofHom (smallBoundaryMap (X := X) n 𝒜)
        from ChainComplex.of_d _ _ _ _) w
    simp only [ConcreteCategory.comp_apply] at hd_eq
    rw [hd_eq]
    rfl

/-- A small cycle that becomes null-homologous after inclusion into $H_n(X)$ is
killed at the cycles level by some iterated subdivision: there exists `k` such that
$\mathrm{Sd}^k(z) = 0$ in $H_n^{\mathcal{A}}(X)$. -/
theorem chain_level_kernel_killing
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (h𝒜 : IsCover 𝒜) (n : ℕ)
    [(smallSingularChainComplex X 𝒜).HasHomology n]
    [(singularChainComplexZ X).HasHomology n]
    (z : (smallSingularChainComplex X 𝒜).cycles n)
    (hz : (singularChainComplexZ X).homologyπ n
      (HomologicalComplex.cyclesMap (smallSingularInclusion X 𝒜) n z) = 0) :
    ∃ k : ℕ, (smallSingularChainComplex X 𝒜).homologyπ n
      (HomologicalComplex.cyclesMap (iteratedSubdivisionRestrict X 𝒜 k) n z) = 0 := by

  obtain ⟨b, k, _, w, hw⟩ := exists_singularChains_boundary_preimage X 𝒜 n z hz
  refine ⟨k, ?_⟩
  rw [← hw]

  have h := ConcreteCategory.congr_hom
    ((smallSingularChainComplex X 𝒜).toCycles_comp_homologyπ (n + 1) n) w
  simp only [ConcreteCategory.comp_apply] at h
  simpa using h

/-- Homology-level kernel killing: any small homology class `x` mapping to zero in
$H_n(X)$ is annihilated by some iterated subdivision $\mathrm{Sd}^k$ on the small
chain complex. -/
theorem exists_iteratedSubdivisionRestrict_kills_kernel
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (h𝒜 : IsCover 𝒜) (n : ℕ)
    [(smallSingularChainComplex X 𝒜).HasHomology n]
    [(singularChainComplexZ X).HasHomology n]
    (x : (smallSingularChainComplex X 𝒜).homology n)
    (hx : HomologicalComplex.homologyMap (smallSingularInclusion X 𝒜) n x = 0) :
    ∃ k : ℕ, HomologicalComplex.homologyMap
      (iteratedSubdivisionRestrict X 𝒜 k) n x = 0 := by

  have hπ_surj : Function.Surjective ((smallSingularChainComplex X 𝒜).homologyπ n) :=
    (AddCommGrpCat.epi_iff_surjective _).mp inferInstance
  obtain ⟨z, hz⟩ := hπ_surj x


  have h_cycle_bdy : (singularChainComplexZ X).homologyπ n
      (HomologicalComplex.cyclesMap (smallSingularInclusion X 𝒜) n z) = 0 := by
    have nat := HomologicalComplex.homologyπ_naturality (smallSingularInclusion X 𝒜) n
    have heq := ConcreteCategory.congr_hom nat z
    simp only [CategoryTheory.comp_apply] at heq
    rw [hz, hx] at heq
    exact heq.symm

  obtain ⟨k, hk⟩ := chain_level_kernel_killing X 𝒜 h𝒜 n z h_cycle_bdy
  refine ⟨k, ?_⟩

  have nat2 := HomologicalComplex.homologyπ_naturality (iteratedSubdivisionRestrict X 𝒜 k) n
  have heq2 := ConcreteCategory.congr_hom nat2 z
  simp only [CategoryTheory.comp_apply] at heq2
  rw [hz] at heq2
  rw [heq2, hk]

/-- The map $H_n^{\mathcal{A}}(X) \to H_n(X)$ induced by the inclusion of small
chains is injective. Combined with `surjective_on_homology`, this gives the
isomorphism asserted by the locality principle. -/
theorem injective_on_homology
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (h𝒜 : IsCover 𝒜) (n : ℕ)
    [inst1 : (smallSingularChainComplex X 𝒜).HasHomology n]
    [inst2 : (singularChainComplexZ X).HasHomology n] :
    Function.Injective
      (HomologicalComplex.homologyMap (smallSingularInclusion X 𝒜) n) := by
  intro a b hab
  have hsub : HomologicalComplex.homologyMap (smallSingularInclusion X 𝒜) n (a - b) = 0 := by
    rw [map_sub, hab, sub_self]
  suffices h : a - b = 0 from sub_eq_zero.mp h
  obtain ⟨k, hk⟩ := exists_iteratedSubdivisionRestrict_kills_kernel X 𝒜 h𝒜 n (a - b) hsub
  have H := iteratedSubdivisionRestrict_homotopy X 𝒜 k
  have heq : HomologicalComplex.homologyMap (iteratedSubdivisionRestrict X 𝒜 k) n =
      HomologicalComplex.homologyMap (𝟙 (smallSingularChainComplex X 𝒜)) n :=
    H.homologyMap_eq n
  simp only [HomologicalComplex.homologyMap_id] at heq
  have hid : HomologicalComplex.homologyMap
      (iteratedSubdivisionRestrict X 𝒜 k) n (a - b) = (a - b) := by
    have h := ConcreteCategory.congr_hom heq (a - b)
    rwa [ConcreteCategory.id_apply] at h
  rw [hid] at hk
  exact hk

/-- The inclusion of small chains induces an isomorphism on homology in degree `n`,
i.e. it is a quasi-isomorphism at `n`. Packages the surjectivity and injectivity
results together. -/
theorem quasiIsoAt_inclusion
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (h𝒜 : IsCover 𝒜) (n : ℕ)
    [(smallSingularChainComplex X 𝒜).HasHomology n]
    [(singularChainComplexZ X).HasHomology n] :
    QuasiIsoAt (smallSingularInclusion X 𝒜) n := by
  rw [quasiIsoAt_iff_isIso_homologyMap]
  rw [ConcreteCategory.isIso_iff_bijective]
  exact ⟨injective_on_homology X 𝒜 h𝒜 n,
         surjective_on_homology X 𝒜 h𝒜 n⟩

/-- **The Locality Principle (Theorem 11.4 / 13.5).** For any cover $\mathcal{A}$
of a space $X$, the inclusion of $\mathcal{A}$-small chains
$S_*^{\mathcal{A}}(X) \subseteq S_*(X)$ is a quasi-isomorphism; equivalently, the
induced map $H_*^{\mathcal{A}}(X) \to H_*(X)$ is an isomorphism in every degree. -/
theorem locality_principle
    (X : TopCat.{0}) (𝒜 : Set (Set X)) (h𝒜 : IsCover 𝒜)
    [∀ i, (smallSingularChainComplex X 𝒜).HasHomology i]
    [∀ i, (singularChainComplexZ X).HasHomology i] :
    QuasiIso (smallSingularInclusion X 𝒜) := by
  rw [quasiIso_iff]
  intro n
  exact quasiIsoAt_inclusion X 𝒜 h𝒜 n

end LocalityPrinciple

end
