/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Analysis.Convex.StdSimplex
import Mathlib.Topology.ContinuousMap.Basic
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.AlgebraicTopology.SingularHomology.Basic
import Mathlib.Algebra.Category.Grp.Basic
import Mathlib.Algebra.Category.Grp.Colimits
import Mathlib.Algebra.Category.Grp.Preadditive
import Mathlib.Algebra.Homology.HomologicalComplex
import Mathlib.Algebra.Category.Grp.Abelian

namespace AlgebraicTopologyI

open Finset AlgebraicTopology CategoryTheory

/-- **Definition 1.1**. The standard $n$-simplex $\Delta^n \subseteq \mathbb{R}^{n+1}$,
realised as the convex hull of the standard basis vectors: the set of points
$(t_0, \ldots, t_n)$ with $t_i \ge 0$ and $\sum t_i = 1$. -/
def standardSimplex (n : ℕ) : Set (Fin (n + 1) → ℝ) :=
  stdSimplex ℝ (Fin (n + 1))

/-- **Definition 1.2**. A singular $n$-simplex in a topological space $X$: a continuous
map $\sigma : \Delta^n \to X$. -/
def SingularSimplex (n : ℕ) (X : Type*) [TopologicalSpace X] :=
  C(↥(stdSimplex ℝ (Fin (n + 1))), X)

/-- **Definition 1.3**. The group of singular $n$-chains on $X$: the free abelian group
$S_n(X) = \mathbb{Z}\langle \mathrm{SingularSimplex}_n(X) \rangle$ generated by all
singular $n$-simplices in $X$. -/
def SingularChains (n : ℕ) (X : Type*) [TopologicalSpace X] :=
  FreeAbelianGroup (SingularSimplex n X)

/-- The abelian group structure on $S_n(X)$, inherited from the free abelian group
construction. -/
instance (n : ℕ) (X : Type*) [TopologicalSpace X] : AddCommGroup (SingularChains n X) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup (SingularSimplex n X)))

/-- The integer-graded variant of singular chains: equals $S_n(X)$ for $n \ge 0$ and is
trivial for $n < 0$. Convenient for stating chain-complex axioms uniformly. -/
def SingularChainsZ (n : ℤ) (X : Type*) [TopologicalSpace X] : Type _ :=
  if n ≥ 0 then SingularChains n.toNat X else PUnit

/-- In negative degrees, `SingularChainsZ` reduces to `PUnit`. -/
theorem singularChainsZ_neg {n : ℤ} (hn : n < 0) (X : Type*) [TopologicalSpace X] :
    SingularChainsZ n X = PUnit := by
  simp [SingularChainsZ, show ¬(n ≥ 0) from not_le.mpr hn]

/-- A chain $c \in A$ is a cycle with respect to a boundary map $d : A \to B$ if
$d(c) = 0$. -/
def IsCycle {A B : Type*} [AddCommGroup A] [AddCommGroup B]
    (d : A →+ B) (c : A) : Prop :=
  d c = 0

/-- The subgroup of cycles for a boundary map $d : A \to B$: the kernel of $d$. -/
def Cycles {A B : Type*} [AddCommGroup A] [AddCommGroup B]
    (d : A →+ B) : AddSubgroup A :=
  d.ker

/-- The singular $n$-cycles of $X$ with respect to a given boundary map $d$:
$Z_{n+1}(X) = \ker (d : S_{n+1}(X) \to S_n(X))$. -/
def SingularCycles (n : ℕ) (X : Type*) [TopologicalSpace X]
    (d : SingularChains (n + 1) X →+ SingularChains n X) :
    AddSubgroup (SingularChains (n + 1) X) :=
  Cycles d

/-- An integer-graded chain complex of abelian groups. -/
abbrev ChainComplexOfAbelianGroups := ChainComplex AddCommGrpCat ℤ

/-- **Definition 1.4**. The singular chain complex $S_*(X; \mathbb{Z})$ of a topological
space $X$ with integer coefficients, as a chain complex of abelian groups indexed by
$\mathbb{N}$ with the differential $\partial$ assembled from face maps. -/
noncomputable def singularChainComplexZ (X : TopCat.{0}) : ChainComplex AddCommGrpCat ℕ :=
  ((singularChainComplexFunctor AddCommGrpCat).obj (AddCommGrpCat.of ℤ)).obj X

/-- **Theorem 1.5** ($\partial^2 = 0$). Consecutive differentials in the singular chain
complex compose to zero: $\partial \circ \partial = 0$. -/
theorem singular_d_comp_d (X : TopCat.{0}) (i j k : ℕ) :
    (singularChainComplexZ X).d i j ≫ (singularChainComplexZ X).d j k = 0 :=
  (singularChainComplexZ X).d_comp_d i j k

/-- **Definition 1.7**. The $n$-th singular homology group with integer coefficients,
$H_n(X; \mathbb{Z}) = Z_n(X) / B_n(X)$, packaged as an abelian group. -/
noncomputable def SingularHomologyGroup (n : ℕ) (X : Type) [TopologicalSpace X] :
    AddCommGrpCat :=
  ((singularHomologyFunctor AddCommGrpCat n).obj (AddCommGrpCat.of ℤ)).obj (TopCat.of X)

/-- Identification of `SingularHomologyGroup n X` with the categorical homology
$H_n(S_*(X; \mathbb{Z}))$ of the singular chain complex. -/
theorem singularHomologyGroup_eq_homology (n : ℕ) (X : Type) [TopologicalSpace X] :
    SingularHomologyGroup n X = (singularChainComplexZ (TopCat.of X)).homology n :=
  rfl

end AlgebraicTopologyI
