/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.LinearAlgebra.BilinearMap
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.LinearAlgebra.TensorProduct.RightExactness
import Mathlib.LinearAlgebra.DirectSum.TensorProduct
import Mathlib.RingTheory.Flat.Basic
import Atlas.AlgebraicTopologyI.code.Section11

namespace BilinearMap

/-- (Definition 20.1) The type of $R$-bilinear maps $\beta : M \times N \to P$, encoded as a
linear map $M \to (N \to_{R} P)$; concretely $\beta$ satisfies
$\beta(x+x', y) = \beta(x,y) + \beta(x',y)$, $\beta(x, y+y') = \beta(x,y) + \beta(x,y')$,
$\beta(rx,y) = r\beta(x,y)$, $\beta(x,ry) = r\beta(x,y)$. -/
abbrev BilinearMapType (R : Type*) [CommSemiring R]
    (M N P : Type*) [AddCommMonoid M] [Module R M]
    [AddCommMonoid N] [Module R N] [AddCommMonoid P] [Module R P] :=
  M →ₗ[R] N →ₗ[R] P

end BilinearMap

namespace TensorProduct

open TensorProduct

variable {R : Type*} [CommSemiring R]
variable {M N P : Type*}
variable [AddCommMonoid M] [AddCommMonoid N] [AddCommMonoid P]
variable [Module R M] [Module R N] [Module R P]

/-- (Definition 20.3) The universal property of the tensor product as the universal $R$-bilinear
target: $R$-bilinear maps $M \times N \to P$ are in linear bijection with $R$-linear maps
$M \otimes_R N \to P$. -/
def universalProperty :
    (M →ₗ[R] N →ₗ[R] P) ≃ₗ[R] (M ⊗[R] N →ₗ[R] P) :=
  TensorProduct.lift.equiv (RingHom.id R) M N P

/-- The canonical map $\beta_0 : M \times N \to M \otimes_R N$, $(m, n) \mapsto m \otimes n$,
is $R$-bilinear; this is the universal bilinear map from Definition 20.3. -/
theorem mk_isBilinearMap :
    IsBilinearMap R (fun (m : M) (n : N) => m ⊗ₜ[R] n) where
  add_left m₁ m₂ n := by simp [add_tmul]
  smul_left r m n := by simp [smul_tmul']
  add_right m n₁ n₂ := by simp [tmul_add]
  smul_right r m n := by simp [tmul_smul]

/-- Computation rule for the universal map: the linear extension of a bilinear form $\beta$ to
$M \otimes_R N$ agrees with $\beta$ on simple tensors, $\widetilde{\beta}(m \otimes n) = \beta(m,n)$. -/
theorem lift_tmul (β : M →ₗ[R] N →ₗ[R] P) (m : M) (n : N) :
    TensorProduct.lift β (m ⊗ₜ[R] n) = β m n :=
  TensorProduct.lift.tmul m n

/-- Uniqueness in the universal property of the tensor product: any linear map
$g : M \otimes_R N \to P$ that agrees with $\beta$ on simple tensors coincides with the linear
extension `TensorProduct.lift β`. -/
theorem lift_unique (β : M →ₗ[R] N →ₗ[R] P)
    (g : M ⊗[R] N →ₗ[R] P)
    (hg : ∀ (m : M) (n : N), g (m ⊗ₜ[R] n) = β m n) :
    g = TensorProduct.lift β :=
  TensorProduct.lift.unique hg

/-- (Construction 20.4) Definitional unfolding of `M ⊗[R] N` as the quotient of the free abelian
group on $M \times N$ by the additive congruence generated by the bilinearity relations. -/
theorem construction :
    M ⊗[R] N = (addConGen (TensorProduct.Eqv R M N)).Quotient :=
  rfl


/-- Induction principle on $M \otimes_R N$: to prove a predicate $C$ for every tensor it suffices
to verify it for $0$, for simple tensors $m \otimes n$, and to show $C$ is closed under sums. -/
theorem induction (C : M ⊗[R] N → Prop)
    (zero : C 0)
    (tmul : ∀ m n, C (m ⊗ₜ[R] n))
    (add : ∀ x y, C x → C y → C (x + y))
    (t : M ⊗[R] N) : C t :=
  TensorProduct.induction_on t zero tmul add

end TensorProduct

namespace HomologyWithCoefficients

open EilenbergSteenrod TensorProduct


/-- The underlying type of the $n$-th singular homology group $H_n(X, A)$ of a topological pair,
serving as the value of the singular homology theory functor. -/
noncomputable def singularH : ℤ → TopPair.{0} → Type := by sorry


/-- Each singular homology group $H_n(X, A)$ is an abelian group. -/
noncomputable instance singularH_instAddCommGroup :
    ∀ (n : ℤ) (P : TopPair.{0}), AddCommGroup (singularH n P) := by sorry

attribute [instance] singularH_instAddCommGroup


/-- Functoriality: a map of pairs $f : (X, A) \to (Y, B)$ induces a group homomorphism
$f_* : H_n(X, A) \to H_n(Y, B)$. -/
noncomputable def singularH_map :
    ∀ (n : ℤ) {P Q : TopPair.{0}}, MapOfPairs P Q → (singularH n P →+ singularH n Q) := by sorry


/-- Functoriality (identities): the identity map of pairs induces the identity on homology. -/
theorem singularH_map_id :
    ∀ (n : ℤ) (P : TopPair.{0}),
      singularH_map n (MapOfPairs.id P) = AddMonoidHom.id (singularH n P) := by sorry


/-- Functoriality (compositions): $(g \circ f)_* = g_* \circ f_*$ on singular homology. -/
theorem singularH_map_comp :
    ∀ (n : ℤ) {P Q R : TopPair.{0}} (f : MapOfPairs P Q) (g : MapOfPairs Q R),
      singularH_map n (g.comp f) = (singularH_map n g).comp (singularH_map n f) := by sorry


/-- The connecting homomorphism $\partial : H_{n+1}(X, A) \to H_n(A)$ of the long exact sequence
of a pair. -/
noncomputable def singularH_boundary :
    ∀ (n : ℤ) (P : TopPair.{0}), singularH (n + 1) P →+ singularH n P.subPair := by sorry


/-- Naturality of the connecting homomorphism with respect to maps of pairs. -/
theorem singularH_boundary_natural :
    ∀ (n : ℤ) {P Q : TopPair.{0}} (f : MapOfPairs P Q),
      (singularH_map n f.restrictToSub).comp (singularH_boundary n P) =
        (singularH_boundary n Q).comp (singularH_map (n + 1) f) := by sorry


/-- Homotopy invariance (Eilenberg-Steenrod axiom 1): homotopic maps of pairs induce the same map
on singular homology. -/
theorem singularH_homotopy_invariance :
    ∀ (n : ℤ) {P Q : TopPair.{0}} (f₀ f₁ : MapOfPairs P Q),
      AreHomotopic f₀ f₁ → singularH_map n f₀ = singularH_map n f₁ := by sorry


/-- Excision (Eilenberg-Steenrod axiom 2): for an excisive triple $(X, A, U)$ the inclusion
$(X - U, A - U) \hookrightarrow (X, A)$ induces an isomorphism in homology. -/
theorem singularH_excision :
    ∀ (n : ℤ) (P : TopPair.{0}) (U : Set P.space),
      IsExcisiveTriple P U → Function.Bijective (singularH_map n (excisionInclusion P U)) := by sorry


/-- Long exact sequence (exactness at $H_n(A)$): the image of the connecting map
$\partial : H_{n+1}(X, A) \to H_n(A)$ equals the kernel of $H_n(A) \to H_n(X)$. -/
theorem singularH_exact_at_sub :
    ∀ (n : ℤ) (P : TopPair.{0}),
      Function.Exact (singularH_boundary n P) (singularH_map n (inclusionSubToSpace P)) := by sorry


/-- Long exact sequence (exactness at $H_n(X)$): the image of $H_n(A) \to H_n(X)$ equals the
kernel of $H_n(X) \to H_n(X, A)$. -/
theorem singularH_exact_at_space :
    ∀ (n : ℤ) (P : TopPair.{0}),
      Function.Exact (singularH_map n (inclusionSubToSpace P))
        (singularH_map n (inclusionSpaceToPair P)) := by sorry


/-- Long exact sequence (exactness at $H_{n+1}(X, A)$): the image of $H_{n+1}(X) \to H_{n+1}(X, A)$
equals the kernel of the connecting map $\partial$. -/
theorem singularH_exact_at_pair :
    ∀ (n : ℤ) (P : TopPair.{0}),
      Function.Exact (singularH_map (n + 1) (inclusionSpaceToPair P)) (singularH_boundary n P) := by sorry


/-- Dimension axiom (Eilenberg-Steenrod): $H_n(\mathrm{pt}) = 0$ for $n \neq 0$. -/
theorem singularH_dimension :
    ∀ (n : ℤ), n ≠ 0 → Subsingleton (singularH n TopPair.point) := by sorry


/-- Milnor (additivity) axiom: the inclusions $X_i \hookrightarrow \coprod_i X_i$ induce an
isomorphism $\bigoplus_i H_n(X_i) \xrightarrow{\cong} H_n(\coprod_i X_i)$. -/
theorem singularH_coproduct :
    ∀ (n : ℤ) {ι : Type} [DecidableEq ι] (X : ι → Type) [∀ i, TopologicalSpace (X i)],
      Function.Bijective
        (DirectSum.toAddMonoid (β := fun i => singularH n (TopPair.ofSpace (X i)))
          (fun i => singularH_map n (coproductInclusion ι X i))) := by sorry

/-- Singular homology with integer coefficients, packaged as a `HomologyTheory` (i.e. satisfying
all Eilenberg-Steenrod axioms plus the Milnor axiom). -/
noncomputable def singularHomologyTheoryZ : HomologyTheory.{0} where
  H := singularH
  instAddCommGroup := singularH_instAddCommGroup
  map := singularH_map
  map_id := singularH_map_id
  map_comp := singularH_map_comp
  boundary := singularH_boundary
  boundary_natural := singularH_boundary_natural
  homotopy_invariance := singularH_homotopy_invariance
  excision := singularH_excision
  exact_at_sub := singularH_exact_at_sub
  exact_at_space := singularH_exact_at_space
  exact_at_pair := singularH_exact_at_pair
  dimension := singularH_dimension
  coproduct := singularH_coproduct


/-- $H_0(\mathrm{pt}; \mathbf{Z}) \cong \mathbf{Z}$: the zeroth integral singular homology of a
point is isomorphic to $\mathbf{Z}$. -/
theorem singularH_point_zero_iso :
    Nonempty (singularH 0 TopPair.point ≃+ ℤ) := by sorry

/-- Restating `singularH_point_zero_iso` for the packaged homology theory: the value at a point
in degree zero is $\mathbf{Z}$. -/
theorem singularHomologyTheoryZ_point_zero_iso :
    Nonempty (singularHomologyTheoryZ.H 0 TopPair.point ≃+ ℤ) :=
  singularH_point_zero_iso


/-- Right exactness of $-\otimes_{\mathbf{Z}} M$ on exact sequences: if $A \to B \to C$ is exact
then so is $A \otimes M \to B \otimes M \to C \otimes M$, used to transfer the long exact
sequences of `singularHomologyTheoryZ` to the coefficient theory. -/
theorem exact_lTensor {A B C : Type} [AddCommGroup A] [AddCommGroup B]
    [AddCommGroup C] (M : Type) [AddCommGroup M] {f : A →+ B} {g : B →+ C}
    (hexact : Function.Exact f g) :
    Function.Exact
      (TensorProduct.map f.toIntLinearMap (LinearMap.id : M →ₗ[ℤ] M)).toAddMonoidHom
      (TensorProduct.map g.toIntLinearMap (LinearMap.id : M →ₗ[ℤ] M)).toAddMonoidHom := by sorry


/-- Compatibility of the Milnor axiom with tensoring by $M$: tensoring a bijection
$\bigoplus_i h_n(X_i) \cong h_n(\coprod_i X_i)$ with $M$ yields a bijection
$\bigoplus_i (h_n(X_i) \otimes M) \cong h_n(\coprod_i X_i) \otimes M$, the additivity statement
for the coefficient-twisted theory. -/
theorem coproduct_lTensor (h : HomologyTheory.{0})
    (M : Type) [AddCommGroup M] (n : ℤ) {ι : Type} [DecidableEq ι]
    (X : ι → Type) [∀ i, TopologicalSpace (X i)]
    (hbij : Function.Bijective
      (DirectSum.toAddMonoid (β := fun i => h.H n (TopPair.ofSpace (X i)))
        (fun i => h.map n (coproductInclusion ι X i)))) :
    Function.Bijective
      (DirectSum.toAddMonoid (β := fun i => TensorProduct ℤ (h.H n (TopPair.ofSpace (X i))) M)
        (fun i => (TensorProduct.map
          (h.map n (coproductInclusion ι X i)).toIntLinearMap
          (LinearMap.id : M →ₗ[ℤ] M)).toAddMonoidHom)) := by
  have htensor_bij : Function.Bijective
    (TensorProduct.map (DirectSum.toAddMonoid (β := fun i => h.H n (TopPair.ofSpace (X i)))
      (fun i => h.map n (coproductInclusion ι X i))).toIntLinearMap
      (LinearMap.id : M →ₗ[ℤ] M)) :=
    TensorProduct.map_bijective hbij Function.bijective_id
  let A := fun i => h.H n (TopPair.ofSpace (X i))
  let B := h.H n (TopPair.ofSpace (Sigma X))
  let φ := fun i => h.map n (coproductInclusion ι X i)
  let f := DirectSum.toAddMonoid (β := fun i => TensorProduct ℤ (A i) M)
    (fun i => (TensorProduct.map (φ i).toIntLinearMap LinearMap.id).toAddMonoidHom)
  let g := (TensorProduct.map (DirectSum.toAddMonoid φ).toIntLinearMap
    (LinearMap.id : M →ₗ[ℤ] M)).comp
    (TensorProduct.directSumLeft ℤ (S := ℤ) A M).symm.toLinearMap
  suffices heq : (f : DirectSum ι (fun i => TensorProduct ℤ (A i) M) →+ TensorProduct ℤ B M) =
    g.toAddMonoidHom by
    rw [show (⇑f) = (⇑g.toAddMonoidHom) from congr_arg DFunLike.coe heq]
    exact htensor_bij.comp (TensorProduct.directSumLeft ℤ (S := ℤ) A M).symm.bijective
  ext i t
  induction t using TensorProduct.induction_on with
  | zero => simp [f, g, map_zero]
  | tmul a m =>
    simp only [f, g, AddMonoidHom.comp_apply, DirectSum.toAddMonoid_of,
      LinearMap.toAddMonoidHom_coe, LinearMap.comp_apply,
      TensorProduct.map_tmul, LinearMap.id_coe, id_eq]
    erw [TensorProduct.directSumLeft_symm_lof_tmul ℤ ℤ (M₁ := A) (M₂' := M) i a m,
      TensorProduct.map_tmul]
    simp only [LinearMap.id_coe, id_eq]
    congr 1
    show (φ i) a = (DirectSum.toAddMonoid φ) (DirectSum.of A i a)
    rw [DirectSum.toAddMonoid_of]
  | add x y hx hy => simp [map_add, hx, hy]

/-- (Proposition 20.11) Homology with coefficients in an abelian group $M$ defines a homology
theory $H_*(X, A; M) := H_*(X, A) \otimes_{\mathbf{Z}} M$ satisfying the Eilenberg-Steenrod axioms;
in particular $H_0(\mathrm{pt}; M) = M$. -/
noncomputable def homologyTheoryWithCoefficients
    (M : Type) [AddCommGroup M] :
    HomologyTheory.{0} where
  H n P := TensorProduct ℤ (singularHomologyTheoryZ.H n P) M
  instAddCommGroup _n _P := inferInstance
  map n {_P _Q} f :=
    (TensorProduct.map (singularHomologyTheoryZ.map n f).toIntLinearMap
      LinearMap.id).toAddMonoidHom
  map_id n P := by
    have h := singularHomologyTheoryZ.map_id n P
    ext x; show (TensorProduct.map _ LinearMap.id) x = x
    rw [show (singularHomologyTheoryZ.map n (MapOfPairs.id P)).toIntLinearMap =
      LinearMap.id from by rw [h]; rfl]
    simp [TensorProduct.map_id]
  map_comp n {_P _Q _R} f g := by
    have h := singularHomologyTheoryZ.map_comp n f g
    ext x; induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul a m => show (singularHomologyTheoryZ.map n (g.comp f)) a ⊗ₜ[ℤ] m = _; rw [h]; rfl
    | add x y hx hy => simp [map_add, hx, hy]
  boundary n P :=
    (TensorProduct.map (singularHomologyTheoryZ.boundary n P).toIntLinearMap
      LinearMap.id).toAddMonoidHom
  boundary_natural n {_P _Q} f := by
    have h := singularHomologyTheoryZ.boundary_natural n f
    ext x; induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul a m =>
      show (singularHomologyTheoryZ.map n f.restrictToSub)
        ((singularHomologyTheoryZ.boundary n _) a) ⊗ₜ[ℤ] m =
        (singularHomologyTheoryZ.boundary n _)
        ((singularHomologyTheoryZ.map (n + 1) f) a) ⊗ₜ[ℤ] m
      congr 1; exact congr_fun (congr_arg DFunLike.coe h) a
    | add x y hx hy => simp [map_add, hx, hy]
  homotopy_invariance n {_P _Q} f₀ f₁ hf := by
    have h := singularHomologyTheoryZ.homotopy_invariance n f₀ f₁ hf
    ext x; induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul a m => show (singularHomologyTheoryZ.map n f₀) a ⊗ₜ[ℤ] m =
        (singularHomologyTheoryZ.map n f₁) a ⊗ₜ[ℤ] m; rw [h]
    | add x y hx hy => simp [map_add, hx, hy]
  excision n P U hU := by
    have hbij := singularHomologyTheoryZ.excision n P U hU
    exact TensorProduct.map_bijective hbij Function.bijective_id
  exact_at_sub n P :=
    exact_lTensor M (singularHomologyTheoryZ.exact_at_sub n P)
  exact_at_space n P :=
    exact_lTensor M (singularHomologyTheoryZ.exact_at_space n P)
  exact_at_pair n P :=
    exact_lTensor M (singularHomologyTheoryZ.exact_at_pair n P)
  dimension n hn := by
    haveI : Subsingleton (singularHomologyTheoryZ.H n TopPair.point) :=
      singularHomologyTheoryZ.dimension n hn
    constructor; intro a b
    have triv : ∀ x : TensorProduct ℤ (singularHomologyTheoryZ.H n TopPair.point) M, x = 0 := by
      intro x
      induction x using TensorProduct.induction_on with
      | zero => rfl
      | tmul a m => simp [Subsingleton.elim a 0]
      | add x y hx hy => simp [hx, hy]
    exact (triv a).trans (triv b).symm
  coproduct := fun n {_ι} [_] X [_] => by
    exact coproduct_lTensor singularHomologyTheoryZ M n X
      (singularHomologyTheoryZ.coproduct n X)

end HomologyWithCoefficients
