/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.TensorCategories.code.HopfAlgebra
import Atlas.TensorCategories.code.CoradicalFiltration
import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.RingTheory.Adjoin.Basic
import Mathlib.Algebra.Lie.UniversalEnveloping

set_option maxHeartbeats 800000

open Coalgebra HopfAlgebra
open scoped TensorProduct

universe u v w


/-- A Hopf algebra `H` is the universal enveloping algebra of a Lie algebra `L` if it admits
a Lie homomorphism `ι : L → H` whose image consists of primitive elements. -/
class EnvelopingHopfAlgebra (k : Type u) [CommRing k] (L : Type v) [LieRing L]
    [LieAlgebra k L] (H : Type w) [Ring H] [HopfAlgebra k H] where
  ι : L →ₗ⁅k⁆ H
  comul_ι (x : L) :
    Coalgebra.comul (ι x) = (ι x) ⊗ₜ[k] (1 : H) + (1 : H) ⊗ₜ[k] (ι x)

namespace EnvelopingHopfAlgebra

variable {k : Type u} [CommRing k] {L : Type v} [LieRing L] [LieAlgebra k L]
  {H : Type w} [Ring H] [HopfAlgebra k H] [h : EnvelopingHopfAlgebra k L H]

end EnvelopingHopfAlgebra


/-- The Sweedler Hopf algebra: a four-dimensional pointed non-commutative non-cocommutative
Hopf algebra over a field of characteristic ≠ 2, generated by a grouplike `g` and a `(g, 1)`
skew-primitive `x`. -/
class SweedlerHopfAlgebra (k : Type u) [Field k] (A : Type v) [Ring A]
    [HopfAlgebra k A] where
  g : A
  x : A
  g_sq : g * g = 1
  x_sq : x * x = 0
  gx_comm : g * x = -(x * g)
  char_ne_two : (2 : k) ≠ 0
  comul_g : comul (R := k) g = g ⊗ₜ[k] g
  comul_x : comul (R := k) x = x ⊗ₜ[k] g + 1 ⊗ₜ[k] x
  counit_g : counit (R := k) g = (1 : k)
  counit_x : counit (R := k) x = (0 : k)
  antipode_g : antipode k g = g
  antipode_x : antipode k x = -(x * g)
  finrank_eq : Module.finrank k A = 4

namespace SweedlerHopfAlgebra

variable {k : Type u} [Field k] {A : Type v} [Ring A] [HopfAlgebra k A]
  [h : SweedlerHopfAlgebra k A]

/-- The proposition that the Sweedler Hopf algebra is pointed as a coalgebra. -/
def isPointed_statement : Prop :=
  IsPointedCoalgebra (R := k) (C := A)

end SweedlerHopfAlgebra


/-- The Taft algebra `T_n(q)`: an `n^2`-dimensional pointed Hopf algebra generated by a
grouplike `g` of order `n` and a `(g, 1)` skew-primitive `x` with `x^n = 0`, where `q` is a
primitive `n`th root of unity. Specializes to the Sweedler algebra at `n = 2`. -/
class TaftAlgebra (k : Type u) [Field k] (A : Type v) [Ring A]
    [HopfAlgebra k A] where
  n : ℕ
  hn : n ≥ 2
  q : k
  hq : IsPrimitiveRoot q n
  g : A
  x : A
  g_pow_n : g ^ n = 1
  x_pow_n : x ^ n = 0
  gx_comm : g * x = algebraMap k A q * (x * g)
  comul_g : comul (R := k) g = g ⊗ₜ[k] g
  comul_x : comul (R := k) x = x ⊗ₜ[k] g + 1 ⊗ₜ[k] x
  counit_g : counit (R := k) g = (1 : k)
  counit_x : counit (R := k) x = (0 : k)
  antipode_g : antipode k g = g ^ (n - 1)
  antipode_x : antipode k x = -(g ^ (n - 1) * x)
  finrank_eq : Module.finrank k A = n ^ 2

namespace TaftAlgebra

variable {k : Type u} [Field k] {A : Type v} [Ring A] [HopfAlgebra k A]
  [h : TaftAlgebra k A]

/-- The proposition that the Taft algebra is pointed as a coalgebra. -/
def isPointed_statement : Prop :=
  IsPointedCoalgebra (R := k) (C := A)

end TaftAlgebra


section AndruskiewitschSchneiderConjecture

/-- Conjecture 1.32.1 (Andruskiewitsch-Schneider): any finite-dimensional pointed Hopf
algebra over a field of characteristic zero is generated by grouplike and skew-primitive
elements, equivalently by the first level of the coradical filtration. -/
theorem andruskiewitschSchneider_conjecture
    (k : Type u) [Field k] [CharZero k]
    (H : Type v) [Ring H] [HopfAlgebra k H]
    [FiniteDimensional k H]
    (hPointed : IsPointedCoalgebra (R := k) (C := H)) :
    Algebra.adjoin k (coradicalFiltration (R := k) (C := H) 1 : Set H) = ⊤ := by sorry

end AndruskiewitschSchneiderConjecture
