/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.TensorCategories.code.CoradicalFiltration

set_option maxHeartbeats 800000

open scoped TensorProduct
open Coalgebra CategoryTheory MonoidalCategory

/-- The category of finite-dimensional right `H`-comodules, for `H` a Hopf algebra over `k`. -/
noncomputable def HComodCat.{u, v} (k : Type u) (H : Type v) [CommSemiring k] [Ring H]
    [HopfAlgebra k H] : Type max u v := by sorry

/-- Category structure on `HComodCat k H`. -/
noncomputable instance HComodCat.categoryInstance {k : Type*} {H : Type*} [CommSemiring k] [Ring H]
    [HopfAlgebra k H] : Category (HComodCat k H) := by sorry

attribute [instance] HComodCat.categoryInstance

/-- Monoidal category structure on `HComodCat k H` given by the cotensor product of
comodules. -/
noncomputable instance HComodCat.monoidalCategoryInstance {k : Type*} {H : Type*}
    [CommSemiring k] [Ring H] [HopfAlgebra k H] :
    MonoidalCategory (HComodCat k H) := by sorry

attribute [instance] HComodCat.monoidalCategoryInstance

/-- Abelian category structure on `HComodCat k H`. -/
noncomputable instance HComodCat.abelianInstance {k : Type*} {H : Type*}
    [CommSemiring k] [Ring H] [HopfAlgebra k H] :
    Abelian (HComodCat k H) := by sorry

attribute [instance] HComodCat.abelianInstance

/-- `HComodCat k H` is canonically the category of finite-dimensional right `H`-comodules
in the sense of `IsComoduleCategoryOf`. -/
theorem HComodCat.isComoduleCategoryOfInstance {k : Type*} {H : Type*}
    [CommSemiring k] [Ring H] [HopfAlgebra k H] :
    IsComoduleCategoryOf k H (HComodCat k H) := by sorry

attribute [instance] HComodCat.isComoduleCategoryOfInstance

/-- Proposition 1.32.3: A pointed Hopf algebra `H` is generated by grouplike and
skew-primitive elements if and only if the tensor category `H`-comod is tensor-generated by
objects of length at most two. -/
theorem proposition_1_32_3
    {k : Type*} [Field k]
    {H : Type*} [Ring H] [HopfAlgebra k H]
    (hPointed : IsPointedCoalgebra (R := k) (C := H)) :
    IsGeneratedByGrouplikesAndSkewPrimitives k H ↔
      IsTensorGenerated (fun X => HasLoewyLengthAtMostTwo (HComodCat k H) X)
        (C := HComodCat k H) := by
  sorry

/-- Alias `Proposition_1_32_3_alt` for `proposition_1_32_3`. -/
abbrev Proposition_1_32_3_alt := @proposition_1_32_3
