/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.RingTheory.HopfAlgebra.Basic
import Mathlib.RingTheory.Coalgebra.TensorProduct
import Mathlib.Algebra.BigOperators.GroupWithZero.Finset
import Mathlib.Tactic

set_option maxHeartbeats 800000

open Coalgebra HopfAlgebra
open scoped TensorProduct

universe u v


section QAnalogs

variable {k : Type*} [Field k]

/-- The q-analog `[n]_q = (q^n - q^{-n}) / (q - q^{-1})` of a natural number `n`. -/
noncomputable def qAnalog (q : k) (n : ℕ) : k :=
  (q ^ n - q⁻¹ ^ n) / (q - q⁻¹)

/-- The q-analog factorial `[n]_q! = ∏_{l=1}^{n} [l]_q`. -/
noncomputable def qAnalogFactorial (q : k) (n : ℕ) : k :=
  ∏ l ∈ Finset.range n, qAnalog q (l + 1)

/-- The coefficient `(-1)^l / ([l]_q! · [N-l]_q!)` appearing in the q-Serre relations. -/
noncomputable def qSerreCoeff (q : k) (N l : ℕ) : k :=
  (-1) ^ l / (qAnalogFactorial q l * qAnalogFactorial q (N - l))

/-- The q-analog of `1` equals `1`, provided `q - q⁻¹ ≠ 0`. -/
lemma qAnalog_one (q : k) (hq : q - q⁻¹ ≠ 0) : qAnalog q 1 = 1 := by
  simp only [qAnalog, pow_one]
  exact div_self hq

end QAnalogs


/-- A Cartan datum of rank `r`: a symmetrizable Cartan matrix together with a
choice of symmetrizing positive integers `d_i`. -/
structure CartanDatum (r : ℕ) where
  cartanMatrix : Fin r → Fin r → ℤ
  symm : Fin r → ℕ
  diag : ∀ i, cartanMatrix i i = 2
  off_diag_nonpos : ∀ i j, i ≠ j → cartanMatrix i j ≤ 0
  symm_pos : ∀ i, 0 < symm i
  symmetrizable : ∀ i j, (symm i : ℤ) * cartanMatrix i j = (symm j : ℤ) * cartanMatrix j i

namespace CartanDatum

/-- The rank-1 Cartan datum for `sl_2`: Cartan matrix `[2]` with symmetrizer `1`. -/
def sl2 : CartanDatum 1 where
  cartanMatrix := fun _ _ => 2
  symm := fun _ => 1
  diag := fun _ => rfl
  off_diag_nonpos := fun i j hij => absurd (Fin.ext (by omega)) hij
  symm_pos := fun _ => by omega
  symmetrizable := fun _ _ => by ring

end CartanDatum


/-- Definition 1.26.2 (Etingof–Gelaki–Nikshych–Ostrik): The quantum group `U_q(g)`
attached to a Cartan datum `C`. It is the Hopf algebra over `k` generated by
elements `E_i, F_i` and invertible elements `K_i` (with inverses `Kinv_i`),
subject to the standard commutation, Cartan, and q-Serre relations, with
comultiplication `Δ(K_i) = K_i ⊗ K_i`, `Δ(E_i) = E_i ⊗ K_i + 1 ⊗ E_i`,
`Δ(F_i) = F_i ⊗ 1 + K_i^{-1} ⊗ F_i`. -/
class QuantumGroup {r : ℕ} (C : CartanDatum r) (k : Type u) [Field k]
    (A : Type v) [Ring A] [HopfAlgebra k A] where
  q : k
  hq_ne_zero : q ≠ 0
  hq_sq_ne_one : q ^ 2 ≠ 1
  E : Fin r → A
  F : Fin r → A
  K : Fin r → A
  Kinv : Fin r → A
  K_mul_Kinv : ∀ i, K i * Kinv i = 1
  Kinv_mul_K : ∀ i, Kinv i * K i = 1
  K_comm : ∀ i j, K i * K j = K j * K i
  K_E_Kinv : ∀ i j, K i * E j * Kinv i = (q ^ (C.cartanMatrix i j)) • E j
  K_F_Kinv : ∀ i j, K i * F j * Kinv i = (q ^ (-C.cartanMatrix i j)) • F j
  EF_comm : ∀ i j, E i * F j - F j * E i =
    if i = j then
      (q ^ (C.symm i : ℤ) - q ^ (-(C.symm i : ℤ)))⁻¹ •
        ((K i) ^ C.symm i - (Kinv i) ^ C.symm i)
    else 0
  qSerre_E : ∀ i j, i ≠ j →
    ∑ l ∈ Finset.range ((1 - C.cartanMatrix i j).toNat + 1),
      qSerreCoeff (q ^ (C.symm i : ℤ)) ((1 - C.cartanMatrix i j).toNat) l •
        ((E i) ^ ((1 - C.cartanMatrix i j).toNat - l) * E j * (E i) ^ l) = 0
  qSerre_F : ∀ i j, i ≠ j →
    ∑ l ∈ Finset.range ((1 - C.cartanMatrix i j).toNat + 1),
      qSerreCoeff (q ^ (C.symm i : ℤ)) ((1 - C.cartanMatrix i j).toNat) l •
        ((F i) ^ ((1 - C.cartanMatrix i j).toNat - l) * F j * (F i) ^ l) = 0
  comul_K : ∀ i, comul (R := k) (K i) = K i ⊗ₜ[k] K i
  comul_E : ∀ i, comul (R := k) (E i) = E i ⊗ₜ[k] K i + 1 ⊗ₜ[k] E i
  comul_F : ∀ i, comul (R := k) (F i) = F i ⊗ₜ[k] 1 + Kinv i ⊗ₜ[k] F i


namespace QuantumGroup

variable {k : Type*} [Field k]
variable {r : ℕ} {C : CartanDatum r} {A : Type v} [Ring A] [HopfAlgebra k A]
  [h : QuantumGroup C k A]

end QuantumGroup


/-- Theorem 1.26.3 (Etingof–Gelaki–Nikshych–Ostrik): There exists a unique
Hopf algebra structure on `U_q(g)` whose coproduct satisfies the prescribed
values on the generators `K_i, E_i, F_i`. Any `k`-linear algebra map
`f : A → A ⊗ A` agreeing with the comultiplication on generators must agree
everywhere. -/
theorem QuantumGroup.hopf_unique_from_generators
    {k : Type*} [Field k]
    {r : ℕ} {C : CartanDatum r}
    {A : Type v} [Ring A] [HopfAlgebra k A]
    [h : QuantumGroup C k A] (f : A →ₗ[k] A ⊗[k] A)
    (hf_alg : ∀ a b : A, f (a * b) = f a * f b)
    (hf_K : ∀ i, f (h.K i) = h.K i ⊗ₜ[k] h.K i)
    (hf_E : ∀ i, f (h.E i) = h.E i ⊗ₜ[k] h.K i + 1 ⊗ₜ[k] h.E i)
    (hf_F : ∀ i, f (h.F i) = h.F i ⊗ₜ[k] 1 + h.Kinv i ⊗ₜ[k] h.F i) :
    ∀ a : A, f a = comul (R := k) a := by sorry
