/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.Buildings.code.Reflection.HyperplaneChambers
import Mathlib.LinearAlgebra.Basis.Defs
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.Data.List.OfFn
import Mathlib.Data.Set.Finite.Basic

open scoped InnerProductSpace
open Set

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

namespace FiniteReflectionGroups

/-- Linear reflection across the hyperplane orthogonal to $α$:
$s_α(v) = v - (2⟨α,v⟩/⟨α,α⟩)·α$. -/
def linearReflection (α v : E) : E :=
  v - (2 * ⟪α, v⟫_ℝ / ⟪α, α⟫_ℝ) • α

/-- Linear reflection $s_α$ packaged as an $ℝ$-linear map. -/
def linearReflectionLM (α : E) : E →ₗ[ℝ] E where
  toFun v := v - (2 * ⟪α, v⟫_ℝ / ⟪α, α⟫_ℝ) • α
  map_add' x y := by
    simp only [inner_add_right, mul_add, add_div, add_smul]; abel
  map_smul' r x := by
    simp only [inner_smul_right, RingHom.id_apply]
    ring_nf; simp [smul_sub, smul_smul]; congr 1; ring

/-- The linear-map version of $s_α$ agrees with the function version. -/
@[simp]
lemma linearReflectionLM_apply (α v : E) :
    linearReflectionLM α v = linearReflection α v := rfl

/-- The coroot of $α$: $\check α = (2 / ⟨α,α⟩)·α$. -/
def coroot (α : E) : E :=
  (2 / ⟪α, α⟫_ℝ) • α

/-- A (finite) root system in an inner product space: a nonempty finite set $Φ$ of nonzero
vectors that spans $E$ and is closed under reflection $s_α(β) ∈ Φ$ for all $α,β ∈ Φ$. -/
structure RootSystem (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E] where
  roots : Finset E
  roots_ne_zero : ∀ α ∈ roots, α ≠ 0
  roots_nonempty : roots.Nonempty
  reflection_closed : ∀ α ∈ roots, ∀ β ∈ roots, linearReflection α β ∈ roots
  roots_span : Submodule.span ℝ (roots : Set E) = ⊤

variable {Φ : RootSystem E}

/-- A root system is *reduced* if the only roots proportional to $α$ are $±α$. -/
def RootSystem.IsReduced (Φ : RootSystem E) : Prop :=
  ∀ α ∈ Φ.roots, ∀ β ∈ Φ.roots, (∃ c : ℝ, β = c • α) → β = α ∨ β = -α

/-- A root system is *crystallographic* if every pairing $⟨α, \check β⟩$ is an integer. -/
def RootSystem.IsCrystallographic (Φ : RootSystem E) : Prop :=
  ∀ α ∈ Φ.roots, ∀ β ∈ Φ.roots, ∃ n : ℤ, ⟪α, coroot β⟫_ℝ = ↑n

/-- The set of coroots $\{\check α : α ∈ Φ\}$. -/
def RootSystem.corootSet (Φ : RootSystem E) : Set E :=
  { v | ∃ α ∈ Φ.roots, v = coroot α }

/-- Positive roots relative to a separating linear functional $f$: those $α ∈ Φ$ with
$f(α) > 0$. -/
def RootSystem.positiveRootSet (Φ : RootSystem E) (f : E → ℝ) : Set E :=
  { α ∈ (Φ.roots : Set E) | f α > 0 }

/-- Negative roots relative to $f$: those $α ∈ Φ$ with $f(α) < 0$. -/
def RootSystem.negativeRootSet (Φ : RootSystem E) (f : E → ℝ) : Set E :=
  { α ∈ (Φ.roots : Set E) | f α < 0 }

/-- A positive root $α$ is *simple* relative to $f$ if it is not a sum of two positive
roots. -/
def RootSystem.IsSimpleRoot (Φ : RootSystem E) (f : E → ℝ) (α : E) : Prop :=
  α ∈ Φ.positiveRootSet f ∧
    ¬∃ (β γ : E), β ∈ Φ.positiveRootSet f ∧ γ ∈ Φ.positiveRootSet f ∧ α = β + γ

/-- The set of simple roots relative to a separating functional $f$. -/
def RootSystem.simpleRootSet (Φ : RootSystem E) (f : E → ℝ) : Set E :=
  { α : E | Φ.IsSimpleRoot f α }

/-- Inductive definition of membership in the Weyl group, generated by reflections
$s_α$ for $α ∈ Φ$ under composition. -/
inductive RootSystem.WeylGroupMem (Φ : RootSystem E) : (E → E) → Prop where
  | id : Φ.WeylGroupMem _root_.id
  | gen (α : E) (hα : α ∈ Φ.roots) : Φ.WeylGroupMem (linearReflection α)
  | comp (f g : E → E) : Φ.WeylGroupMem f → Φ.WeylGroupMem g →
      Φ.WeylGroupMem (f ∘ g)

/-- The underlying set of the Weyl group inside $E → E$. -/
def RootSystem.weylGroupSet (Φ : RootSystem E) : Set (E → E) :=
  { g | Φ.WeylGroupMem g }

end FiniteReflectionGroups
