/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.TensorCategories.code.CartierKostant.Axioms

open Coalgebra HopfAlgebra
open scoped TensorProduct

universe u v


section CartierKostantTheorem

/-- Milnor–Moore (injectivity part): for a cocommutative connected Hopf algebra over an
algebraically closed field of characteristic zero, the canonical map `U(Prim(H)) → H` is
injective. Deduced from the PBW-compatible coradical filtration. -/
theorem HopfAlgebra.milnorMoore_injective
    (k : Type u) (H : Type v)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H]
    (hconn : HopfAlgebra.grouplikeElements (R := k) (H := H) = {1}) :
    Function.Injective (HopfAlgebra.canonicalMapUEA (R := k) (H := H)) := by

  obtain ⟨F, hMono, hExhaust, _hCompat, hBase, hGraded⟩ :=
    HopfAlgebra.coradicalFiltration_compatible_injective k H hconn

  have hKerFilt : ∀ n x, x ∈ F n →
      (HopfAlgebra.canonicalMapUEA (R := k) (H := H)) x = 0 → x = 0 := by
    intro n
    induction n with
    | zero => exact hBase
    | succ n ih =>
      intro x hxF hψx

      exact ih x (hGraded n x hxF hψx) hψx

  intro a b hab
  rw [← sub_eq_zero]
  have hψ_diff : (HopfAlgebra.canonicalMapUEA (R := k) (H := H)) (a - b) = 0 := by
    rw [map_sub, sub_eq_zero]; exact hab

  have hMem : a - b ∈ (⨆ n, F n) := by rw [hExhaust]; exact Submodule.mem_top
  obtain ⟨n, hn⟩ := (Submodule.mem_iSup_of_directed F (hMono.directed_le)).mp hMem
  exact hKerFilt n _ hn hψ_diff

/-- Cartier–Kostant generation: a cocommutative Hopf algebra over an algebraically closed
field of characteristic zero is generated as an algebra by its grouplike and primitive
elements. -/
theorem HopfAlgebra.cartierKostant
    (k : Type u) (H : Type v)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H] :
    Algebra.adjoin k
      (HopfAlgebra.grouplikeElements (R := k) (H := H) ∪
       (HopfAlgebra.primitiveElements (R := k) (H := H) : Set H)) = ⊤ := by

  have hDecomp := HopfAlgebra.pointedCoalgebraDecomposition k H

  have hRange : (Set.range (HopfAlgebra.canonicalMapUEA (R := k) (H := H))) ⊆
      ↑(Algebra.adjoin k (HopfAlgebra.primitiveElements (R := k) (H := H) : Set H)) := by
    intro x hx
    rw [Set.mem_range] at hx
    obtain ⟨y, rfl⟩ := hx
    exact HopfAlgebra.canonicalMapUEA_range_le_adjoin ⟨y, rfl⟩

  rw [eq_top_iff, ← hDecomp]
  apply Algebra.adjoin_le
  intro x hx
  rcases hx with hG | hψ
  · exact Algebra.adjoin_mono Set.subset_union_left (Algebra.subset_adjoin hG)
  · exact Algebra.adjoin_mono Set.subset_union_right (hRange hψ)

/-- Theorem 1.33.1 (Cartier–Kostant–Milnor–Moore): a cocommutative Hopf algebra `H` over
an algebraically closed field of characteristic zero is isomorphic to the smash product
`k[G(H)] ⋉ U(Prim(H))`. -/
theorem thm_1_33_1
    (k : Type u) (H : Type u)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H] :
    let G := HopfAlgebra.GrouplikeGroup k H
    let 𝔤 := HopfAlgebra.primitiveLieSubalgebra (R := k) (H := H)
    let act := HopfAlgebra.grouplikeConjugationAction k H
    Nonempty (@AlgEquiv k
      (@SmashProductAlgebra k G 𝔤 _ _ _ _ act)
      H
      _
      (@SmashProductAlgebra.instRing k G 𝔤 _ _ _ _ act).toSemiring
      (inferInstance : Semiring H)
      (@SmashProductAlgebra.instAlgebra k G 𝔤 _ _ _ _ act)
      (inferInstance : Algebra k H)) :=
  HopfAlgebra.cartierKostant_iso k H

/-- Theorem 1.33.1 (textbook-name alias of `thm_1_33_1`): Cartier–Kostant–Milnor–Moore
isomorphism for cocommutative Hopf algebras over an algebraically closed field of
characteristic zero. -/
theorem Theorem_1_33_1
    (k : Type u) (H : Type u)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H] :
    let G := HopfAlgebra.GrouplikeGroup k H
    let 𝔤 := HopfAlgebra.primitiveLieSubalgebra (R := k) (H := H)
    let act := HopfAlgebra.grouplikeConjugationAction k H
    Nonempty (@AlgEquiv k
      (@SmashProductAlgebra k G 𝔤 _ _ _ _ act)
      H
      _
      (@SmashProductAlgebra.instRing k G 𝔤 _ _ _ _ act).toSemiring
      (inferInstance : Semiring H)
      (@SmashProductAlgebra.instAlgebra k G 𝔤 _ _ _ _ act)
      (inferInstance : Algebra k H)) :=
  thm_1_33_1 k H

/-- Root-namespace alias for `HopfAlgebra.cartierKostant`: every cocommutative Hopf
algebra (in characteristic zero, over an algebraically closed field) is generated by its
grouplike and primitive elements. -/
theorem cartierKostant
    (k : Type u) (H : Type v)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H] :
    Algebra.adjoin k
      (HopfAlgebra.grouplikeElements (R := k) (H := H) ∪
       (HopfAlgebra.primitiveElements (R := k) (H := H) : Set H)) = ⊤ :=
  HopfAlgebra.cartierKostant k H

/-- For a connected cocommutative Hopf algebra in characteristic zero over an
algebraically closed field, primitive elements generate `H` as an algebra. -/
theorem HopfAlgebra.milnorMoore_primitives_generate
    (k : Type u) (H : Type v)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H]
    (hconn : HopfAlgebra.grouplikeElements (R := k) (H := H) = {1}) :
    Algebra.adjoin k
      ((HopfAlgebra.primitiveElements (R := k) (H := H) : Set H)) = ⊤ := by
  have hCK := HopfAlgebra.cartierKostant k H
  rw [hconn] at hCK
  rw [eq_top_iff, ← hCK]
  apply Algebra.adjoin_le
  intro x hx
  cases hx with
  | inl h => rw [Set.mem_singleton_iff.mp h]; exact Subalgebra.one_mem _
  | inr h => exact Algebra.subset_adjoin h

/-- Milnor–Moore theorem: for a connected cocommutative Hopf algebra in characteristic
zero over an algebraically closed field, the canonical map `U(Prim(H)) → H` is a
bijection (and hence an algebra isomorphism). -/
theorem HopfAlgebra.milnorMoore
    (k : Type u) (H : Type v)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H]
    (hconn : HopfAlgebra.grouplikeElements (R := k) (H := H) = {1}) :
    Function.Bijective (HopfAlgebra.canonicalMapUEA (R := k) (H := H)) :=
  ⟨HopfAlgebra.milnorMoore_injective k H hconn,
   HopfAlgebra.surjective_of_primitives_generate
     (HopfAlgebra.milnorMoore_primitives_generate k H hconn)⟩

/-- Pointed decomposition (re-export): a cocommutative Hopf algebra over an algebraically
closed field of characteristic zero is generated by its grouplike elements together with
the image of `U(Prim(H))`. -/
theorem HopfAlgebra.pointedDecomposition
    (k : Type u) (H : Type v)
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H] :
    Algebra.adjoin k
      (HopfAlgebra.grouplikeElements (R := k) (H := H) ∪
       Set.range (HopfAlgebra.canonicalMapUEA (R := k) (H := H))) = ⊤ :=
  HopfAlgebra.pointedCoalgebraDecomposition k H

/-- A commutative Hopf algebra in characteristic zero is geometrically reduced (deduced
from the fact that all finitely generated subalgebras are geometrically reduced). -/
theorem HopfAlgebra.commHopfAlgebra_isGeometricallyReduced
    (k : Type u) (H : Type v)
    [Field k] [CharZero k]
    [CommRing H] [HopfAlgebra k H] :
    Algebra.IsGeometricallyReduced k H :=
  Algebra.IsGeometricallyReduced.of_forall_fg fun B hB =>
    HopfAlgebra.commHopfAlgebra_fg_subalgebra_isGeometricallyReduced k H B hB

/-- A commutative Hopf algebra over a field of characteristic zero is reduced (no nonzero
nilpotents). -/
theorem HopfAlgebra.commHopfAlgebra_isReduced
    (k : Type u) (H : Type v)
    [Field k] [CharZero k]
    [CommRing H] [HopfAlgebra k H] :
    IsReduced H := by
  haveI := HopfAlgebra.commHopfAlgebra_isGeometricallyReduced k H
  exact Algebra.isReduced_of_isGeometricallyReduced k

/-- Corollary 1.33.4: a commutative Hopf algebra over a field of characteristic zero is
reduced. -/
theorem Corollary_1_33_4
    (k : Type u) (H : Type v)
    [Field k] [CharZero k]
    [CommRing H] [HopfAlgebra k H] :
    IsReduced H :=
  HopfAlgebra.commHopfAlgebra_isReduced k H

end CartierKostantTheorem


section Consequences

variable {k : Type u} {H : Type v}

/-- A connected cocommutative Hopf algebra (in characteristic zero over an algebraically
closed field) is generated as an algebra by its primitive elements. -/
theorem HopfAlgebra.milnorMoore_generation
    [Field k] [IsAlgClosed k] [CharZero k]
    [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H]
    (hconn : HopfAlgebra.grouplikeElements (R := k) (H := H) = {1}) :
    Algebra.adjoin k ((HopfAlgebra.primitiveElements (R := k) (H := H) : Set H)) = ⊤ :=
  HopfAlgebra.surjective_canonicalMapUEA_adjoin_top
    (HopfAlgebra.milnorMoore k H hconn).2

/-- Every primitive element is `(1,1)`-skew-primitive: `Δ x = x ⊗ 1 + 1 ⊗ x`. -/
theorem HopfAlgebra.IsPrimitive.isSkewPrimitive_one_one
    [CommRing k] [Ring H] [HopfAlgebra k H]
    {x : H} (hx : HopfAlgebra.IsPrimitive (R := k) x) :
    IsSkewPrimitive (R := k) (1 : H) (1 : H) x := by
  show comul (R := k) x = x ⊗ₜ 1 + 1 ⊗ₜ x
  exact hx

/-- Every primitive element lies in the first piece of the coradical filtration, provided
the unit `1` lies in the coradical. -/
theorem HopfAlgebra.IsPrimitive.mem_coradicalFiltration_one
    [CommRing k] [Ring H] [HopfAlgebra k H]
    {x : H} (hx : HopfAlgebra.IsPrimitive (R := k) x)
    (h1 : (1 : H) ∈ coradical (R := k) (C := H)) :
    x ∈ coradicalFiltration (R := k) (C := H) 1 :=
  skewPrimitive_mem_coradicalFiltration_one 1 1 x h1 h1 hx.isSkewPrimitive_one_one

/-- Pointwise cocommutativity restated for Hopf algebras: `τ(Δ x) = Δ x` for every
`x : H` in a cocommutative Hopf algebra. -/
theorem HopfAlgebra.comul_symmetric
    [CommRing k] [Ring H] [HopfAlgebra k H]
    [Coalgebra.IsCocommutative k H] (x : H) :
    (TensorProduct.comm k H H) (comul (R := k) x) = comul (R := k) x :=
  cocommutative_comul_apply k H x

/-- Reinterpret `IsGrouplikeHopf` as the coalgebraic `IsGrouplike` predicate. -/
theorem HopfAlgebra.IsGrouplikeHopf.toIsGrouplike
    [CommRing k] [Ring H] [HopfAlgebra k H]
    {g : H} (hg : HopfAlgebra.IsGrouplikeHopf (R := k) g) :
    IsGrouplike (R := k) g :=
  hg

/-- The antipode of a grouplike element is a unit in `H`. -/
theorem HopfAlgebra.IsGrouplikeHopf.antipode_isUnit
    [CommRing k] [Ring H] [HopfAlgebra k H]
    {g : H} (hg : HopfAlgebra.IsGrouplikeHopf (R := k) g) :
    IsUnit (antipode k g) :=
  ⟨⟨antipode k g, g, hg.antipode_mul, hg.mul_antipode⟩, rfl⟩

/-- A commutative Hopf algebra in characteristic zero has no nonzero nilpotent elements
(consequence of being reduced). -/
theorem HopfAlgebra.commHopfAlgebra_no_nilpotents
    [Field k] [CharZero k]
    [CommRing H] [HopfAlgebra k H]
    (x : H) (hx : IsNilpotent x) : x = 0 := by
  haveI := HopfAlgebra.commHopfAlgebra_isReduced k H
  exact hx.eq_zero

end Consequences
