/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.MeasureTheory.Function.SimpleFunc

open MeasurableSpace Set MeasureTheory MeasureTheory.SimpleFunc
open scoped ENNReal NNReal

namespace MeasurabilityOfFunctions

/-- Lemma 3.1 of Melrose: a function `f : X → Y` is measurable into the σ-algebra generated by
a family `G` of subsets of `Y` if and only if the preimages of all generating sets are
measurable in `X`. -/
theorem measurable_generateFrom_iff {X Y : Type*} [MeasurableSpace X]
    {G : Set (Set Y)} {f : X → Y} :
    @Measurable X Y _ (generateFrom G) f ↔
      ∀ A ∈ G, MeasurableSet (f ⁻¹' A) := by
  constructor
  · intro hf A hA
    exact hf (measurableSet_generateFrom hA)
  · exact measurable_generateFrom

/-- Proposition 3.2 of Melrose: between Borel spaces, every continuous map is measurable. -/
theorem continuous_imp_measurable
    {X Y : Type*} [MetricSpace X] [MetricSpace Y]
    [MeasurableSpace X] [BorelSpace X]
    [MeasurableSpace Y] [BorelSpace Y]
    {f : X → Y} (hf : Continuous f) : Measurable f :=
  hf.measurable

end MeasurabilityOfFunctions

/-- Density of the rational encoding `ennrealRatEmbed` in compact intervals `[0, C] ⊂ ℝ≥0∞`:
for any `C < ∞` and `ε > 0`, finitely many rational embeddings (indexed by indices `< N`) form
an `ε`-net from below for every `v ≤ C`. This is the discretisation used in the construction
of simple-function approximations to measurable functions. -/
theorem ennrealRatEmbed_dense_Icc (C : ℝ≥0∞) (hC : C ≠ ⊤)
    (ε : ℝ≥0∞) (hε : 0 < ε) :
    ∃ N : ℕ, ∀ v : ℝ≥0∞, v ≤ C →
      ∃ k : ℕ, k < N ∧ ennrealRatEmbed k ≤ v ∧ v - ennrealRatEmbed k < ε := by

  obtain ⟨q, hq0, hq_pos_ennreal, hqε⟩ := ENNReal.lt_iff_exists_rat_btwn.mp hε
  have hq_pos : (0 : ℝ) < (q : ℝ) := by
    by_contra h
    simp only [not_lt] at h
    have h1 : Real.toNNReal (q : ℝ) = 0 := Real.toNNReal_eq_zero.mpr h
    simp [h1] at hq_pos_ennreal

  set δ : ℝ := (q : ℝ) with hδ_def
  set M : ℕ := ⌊C.toReal / δ⌋₊

  let encodeFn : ℕ → ℕ := fun j => Encodable.encode ((j : ℚ) * q)
  use 1 + (Finset.range (M + 1)).sup encodeFn
  intro v hv
  have hv_ne : v ≠ ⊤ := ne_top_of_le_ne_top hC hv
  have hv_le_r : v.toReal ≤ C.toReal := (ENNReal.toReal_le_toReal hv_ne hC).mpr hv

  set i : ℕ := ⌊v.toReal / δ⌋₊
  have hi_le : i ≤ M := Nat.floor_le_floor (div_le_div_of_nonneg_right hv_le_r hq_pos.le)
  have hi_mem : i ∈ Finset.range (M + 1) := Finset.mem_range.mpr (by omega)

  have key : ennrealRatEmbed (Encodable.encode ((↑i : ℚ) * q)) =
      ENNReal.ofReal ((i : ℝ) * δ) := by
    have h1 := ennrealRatEmbed_encode ((↑i : ℚ) * q)
    rw [h1]
    unfold ENNReal.ofReal
    congr 1
    congr 1
    rw [hδ_def]
    push_cast
    ring

  have hiδ_le : (i : ℝ) * δ ≤ v.toReal := by
    have h1 : (↑i : ℝ) ≤ v.toReal / δ :=
      Nat.floor_le (div_nonneg ENNReal.toReal_nonneg hq_pos.le)
    have h2 : v.toReal / δ * δ = v.toReal := div_mul_cancel₀ v.toReal hq_pos.ne'
    calc (↑i : ℝ) * δ ≤ v.toReal / δ * δ :=
            mul_le_mul_of_nonneg_right h1 hq_pos.le
      _ = v.toReal := h2

  have hv_lt : v.toReal < ((↑i : ℝ) + 1) * δ := by
    have h1 := Nat.lt_floor_add_one (v.toReal / δ)
    have h2 : v.toReal / δ * δ = v.toReal := div_mul_cancel₀ v.toReal hq_pos.ne'
    calc v.toReal = v.toReal / δ * δ := h2.symm
      _ < ((↑i : ℝ) + 1) * δ := mul_lt_mul_of_pos_right h1 hq_pos
  have hiδ_nn : (0 : ℝ) ≤ (↑i : ℝ) * δ := mul_nonneg (Nat.cast_nonneg _) hq_pos.le
  refine ⟨Encodable.encode ((i : ℚ) * q), ?_, ?_, ?_⟩

  · have hsup := Finset.le_sup (f := encodeFn) hi_mem
    change encodeFn i < _
    omega

  · rw [key, ← ENNReal.ofReal_toReal hv_ne]
    exact ENNReal.ofReal_le_ofReal hiδ_le

  · rw [key]
    have hvsub : v.toReal - (↑i : ℝ) * δ < δ := by nlinarith
    calc v - ENNReal.ofReal ((↑i : ℝ) * δ)
        = ENNReal.ofReal v.toReal - ENNReal.ofReal ((↑i : ℝ) * δ) := by
            rw [ENNReal.ofReal_toReal hv_ne]
      _ = ENNReal.ofReal (v.toReal - (↑i : ℝ) * δ) := (ENNReal.ofReal_sub v.toReal hiδ_nn).symm
      _ < ENNReal.ofReal δ := by
            rw [ENNReal.ofReal_lt_ofReal_iff hq_pos]; exact hvsub
      _ = ↑(Real.toNNReal δ) := rfl
      _ < ε := hqε
