/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.IdentDistrib

open MeasureTheory MeasurableSpace ProbabilityTheory Filter Set
open scoped ENNReal MeasureTheory

variable {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]

/-- A set `A ⊆ (ℕ → S)` is an **exchangeable** (or permutable) event if it is
measurable and invariant under every finite permutation of the index set `ℕ`,
i.e. `{x : x ∘ σ ∈ A} = A` for every permutation `σ` that moves only finitely
many indices. -/
def IsExchangeableEvent (A : Set (ℕ → S)) : Prop :=
  MeasurableSet A ∧
  ∀ σ : Equiv.Perm ℕ, Set.Finite {i | σ i ≠ i} →
    (fun x => x ∘ σ) ⁻¹' A = A

/-- An event `E ⊆ Ω` is **exchangeable with respect to the sequence** `X : ℕ → Ω → S`
if there is some exchangeable event `A ⊆ (ℕ → S)` such that `E` is the pullback of
`A` under `ω ↦ (n ↦ X n ω)`. Equivalently, `E` belongs to the σ-field of exchangeable
events generated by `X`. -/
def IsExchangeableEventWrt (X : ℕ → Ω → S) (E : Set Ω) : Prop :=
  ∃ A : Set (ℕ → S), IsExchangeableEvent A ∧
    E = (fun ω n => X n ω) ⁻¹' A

/-- An exchangeable event with respect to a measurable sequence `X` is itself
measurable in `Ω`. -/
theorem IsExchangeableEventWrt.measurableSet
    {X : ℕ → Ω → S} {E : Set Ω}
    (hX : ∀ n, Measurable (X n))
    (hE : IsExchangeableEventWrt X E) :
    MeasurableSet E := by
  obtain ⟨A, ⟨hA_meas, _⟩, rfl⟩ := hE
  exact (measurable_pi_lambda _ (fun n => hX n)) hA_meas

/-- **Hewitt–Savage 0–1 law**. If `X_1, X_2, …` is an i.i.d. sequence (independent
and identically distributed) and `E` is an exchangeable event (i.e. `E ∈ ℰ`, the
σ-field of permutable events) with respect to `X`, then `μ E ∈ {0, 1}`. -/
theorem hewittSavage_zeroOne
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {X : ℕ → Ω → S}
    (hX : ∀ n, Measurable (X n))
    (h_ident : ∀ i, IdentDistrib (X i) (X 0) μ μ)
    (h_indep : iIndepFun (m := fun _ => inferInstance) X μ)
    {E : Set Ω}
    (hE : IsExchangeableEventWrt X E) :
    μ E = 0 ∨ μ E = 1 := by sorry
