/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.TheoryOfProbability.code.MarkovChainConstruction

open MeasureTheory ProbabilityTheory

variable {Ω S : Type*} {m : MeasurableSpace Ω} [MeasurableSpace S]

/-- The defining Markov property of an `IsMarkovChain`, re-exported as a top-level lemma:
for any measurable set `B ⊆ S` and any `n`,

  `E[1_B ∘ X (n+1) | ℱ n] = κ (X n ·) B  μ`-a.e.,

i.e. `P(X_{n+1} ∈ B | ℱ_n) = κ(X_n, B)`. -/
theorem IsMarkovChain.markov_property {X : ℕ → Ω → S} {ℱ : Filtration ℕ m} {κ : Kernel S S}
    [IsMarkovKernel κ] {μ : Measure Ω} (hMC : IsMarkovChain X ℱ κ μ)
    (n : ℕ) {B : Set S} (hB : MeasurableSet B) :
    μ[(B.indicator (fun _ => (1 : ℝ))) ∘ (X (n + 1)) | ℱ n] =ᵐ[μ]
      fun ω => (κ (X n ω) B).toReal :=
  hMC.markov_prop n B hB

/-- The discrete-time shift on path space: `shiftPath n ω` is the path
`k ↦ ω (n + k)`, i.e. the trajectory `ω` viewed from time `n` onward. -/
def shiftPath {S : Type*} (n : ℕ) : (ℕ → S) → (ℕ → S) :=
  fun ω k => ω (n + k)

/-- The time-`n` shift map on path space is measurable. -/
theorem measurable_shiftPath {S : Type*} [MeasurableSpace S] (n : ℕ) :
    Measurable (shiftPath n : (ℕ → S) → (ℕ → S)) := by
  apply measurable_pi_lambda
  intro k
  exact measurable_pi_apply (n + k)

/-- The canonical filtration on the path space `ℕ → S`: at time `n` it is the σ-algebra
generated by the coordinate maps `ω ↦ ω i` for `i ≤ n`. -/
noncomputable def pathFiltration (S : Type*) [MeasurableSpace S] :
    Filtration ℕ
      (m := MeasurableSpace.pi (m := fun _ : ℕ => (inferInstance : MeasurableSpace S))) where
  seq n := ⨆ (i : ℕ) (_ : i ≤ n),
    MeasurableSpace.comap (fun (ω : ℕ → S) => ω i) ‹MeasurableSpace S›
  mono' i j hij := iSup_mono fun k => iSup_mono' fun hk => ⟨hk.trans hij, le_rfl⟩
  le' n := iSup_le fun k => iSup_le fun _ => (measurable_pi_apply k).comap_le

/-- The law on path space `ℕ → S` of the Markov chain with initial distribution `μ` and
transition kernel `κ`. Built via the trajectory measure of the lifted kernel
`markovLiftKernel κ`. -/
noncomputable def MarkovChainPathMeasure
    (S : Type*) [MeasurableSpace S]
    (μ : Measure S) (κ : Kernel S S) [IsMarkovKernel κ] :
    @Measure (ℕ → S) MeasurableSpace.pi :=
  ProbabilityTheory.Kernel.trajMeasure (X := fun _ : ℕ => S) μ (markovLiftKernel κ)

/-- When the initial distribution `μ` is a probability measure, the resulting path measure
is itself a probability measure on `ℕ → S`. -/
noncomputable instance MarkovChainPathMeasure.isProbabilityMeasure
    (S : Type*) [MeasurableSpace S]
    (μ : Measure S) [IsProbabilityMeasure μ]
    (κ : Kernel S S) [IsMarkovKernel κ] :
    @IsProbabilityMeasure (ℕ → S) MeasurableSpace.pi (MarkovChainPathMeasure S μ κ) := by
  unfold MarkovChainPathMeasure
  infer_instance

/-- When the initial distribution `μ` is finite, the resulting path measure is itself a
finite measure on `ℕ → S`. -/
noncomputable instance MarkovChainPathMeasure.isFiniteMeasure
    (S : Type*) [MeasurableSpace S]
    (μ : Measure S) [IsFiniteMeasure μ]
    (κ : Kernel S S) [IsMarkovKernel κ] :
    @IsFiniteMeasure (ℕ → S) MeasurableSpace.pi (MarkovChainPathMeasure S μ κ) := by
  unfold MarkovChainPathMeasure ProbabilityTheory.Kernel.trajMeasure
  infer_instance

/-- The expectation `E_x Y` of a path functional `Y` under the Markov chain started from
the point `x ∈ S`. It is the integral of `Y` against the path measure with initial
distribution `δ_x`. -/
noncomputable def markovExpectation
    (S : Type*) [MeasurableSpace S]
    (κ : Kernel S S) [IsMarkovKernel κ] (Y : (ℕ → S) → ℝ) (x : S) : ℝ :=
  ∫ ω, Y ω ∂(MarkovChainPathMeasure S (Measure.dirac x) κ)

/-- The map `x ↦ E_x Y = markovExpectation S κ Y x` is measurable in the starting state
`x`, provided `Y` is bounded measurable on path space and `S` is a standard Borel space. -/
theorem measurable_markovExpectation
    (S : Type*) [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    (κ : Kernel S S) [IsMarkovKernel κ]
    (Y : (ℕ → S) → ℝ) (hY_meas : @Measurable _ _ MeasurableSpace.pi _ Y)
    (hY_bdd : ∃ C : ℝ, ∀ ω, |Y ω| ≤ C) :
    Measurable (markovExpectation S κ Y) := by


  let K := ProbabilityTheory.Kernel.traj (X := fun _ : ℕ => S) (markovLiftKernel κ) 0
  let e := MeasurableEquiv.piUnique (fun _ : ↥(Finset.Iic 0) => S)
  have hfun : ∀ x : S, markovExpectation S κ Y x = ∫ ω, Y ω ∂(K (e.symm x)) := by
    intro x
    unfold markovExpectation MarkovChainPathMeasure ProbabilityTheory.Kernel.trajMeasure
    congr 1
    rw [Measure.map_dirac' (MeasurableEquiv.measurable _),
        Measure.dirac_bind (Kernel.measurable _)]
  simp_rw [show markovExpectation S κ Y = fun x => ∫ ω, Y ω ∂(K (e.symm x)) from
    funext hfun]
  exact (hY_meas.stronglyMeasurable.integral_kernel).measurable.comp e.symm.measurable

/-- Identifies an integral on the trajectory kernel with `markovExpectation`: the integral
of `Y` against the shifted trajectory starting from a finite history `x₀` equals
`E_{x₀ n} Y`, the expected value of `Y` for the chain started from the last coordinate
of `x₀`. -/
theorem integral_shiftPath_traj_eq_markovExpectation
    (S : Type*) [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    (μ : Measure S) [IsFiniteMeasure μ]
    (κ : Kernel S S) [IsMarkovKernel κ]
    (Y : (ℕ → S) → ℝ) (hY_meas : @Measurable _ _ MeasurableSpace.pi _ Y)
    (hY_bdd : ∃ C : ℝ, ∀ ω, |Y ω| ≤ C)
    (n : ℕ) (x₀ : (i : ↥(Finset.Iic n)) → S) :
    ∫ ω, Y (shiftPath n ω) ∂(Kernel.traj (markovLiftKernel κ) n x₀) =
      ∫ ω, Y ω ∂(MarkovChainPathMeasure S (Measure.dirac (x₀ ⟨n, Finset.mem_Iic.mpr le_rfl⟩)) κ) := by sorry

/-- Each level of the `pathFiltration` is contained in the product σ-algebra on `ℕ → S`. -/
lemma pathFiltration_le_pi (S : Type*) [MeasurableSpace S] (n : ℕ) :
    pathFiltration S n ≤ MeasurableSpace.pi := by
  exact (pathFiltration S).le' n

/-- Set-integral form of the Markov property for the Markov chain path measure. For any
bounded measurable path functional `Y` and any set `A` measurable with respect to
`pathFiltration S n`,

  `∫_A Y(shiftPath n ω) dP_μ = ∫_A markovExpectation S κ Y (ω n) dP_μ`.

This is the analogue of `setIntegral_shift_eq_pathExpectation` for discrete-time Markov
chains. -/
theorem markov_setIntegral_shift
    (S : Type*) [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    (μ : Measure S) [IsFiniteMeasure μ]
    (κ : Kernel S S) [IsMarkovKernel κ]
    (Y : (ℕ → S) → ℝ) (hY_meas : @Measurable _ _ MeasurableSpace.pi _ Y)
    (hY_bdd : ∃ C : ℝ, ∀ ω, |Y ω| ≤ C)
    (n : ℕ) (A : Set (ℕ → S))
    (hA : @MeasurableSet _ (pathFiltration S n) A) :
    let P_μ := MarkovChainPathMeasure S μ κ
    ∫ ω in A, (Y ∘ shiftPath n) ω ∂P_μ = ∫ ω in A, markovExpectation S κ Y (ω n) ∂P_μ := by
  intro P_μ
  obtain ⟨C, hC⟩ := hY_bdd
  set κ' := markovLiftKernel κ
  set K := Kernel.traj (X := fun _ : ℕ => S) κ' 0
  set e := MeasurableEquiv.piUnique (fun _ : ↑(Finset.Iic 0) => S)
  set ν := Measure.map (⇑e.symm) μ

  have hP_eq : P_μ = K ∘ₘ ν := by
    simp only [P_μ, MarkovChainPathMeasure, Kernel.trajMeasure, K, ν, κ']
    rfl
  have hA_pi : @MeasurableSet _ MeasurableSpace.pi A := pathFiltration_le_pi S n A hA


  have hf_meas : @Measurable _ _ MeasurableSpace.pi _ (Y ∘ shiftPath n) :=
    hY_meas.comp (measurable_shiftPath n)
  have hf_int : IntegrableOn (Y ∘ shiftPath n) A P_μ := by
    apply IntegrableOn.of_bound (measure_lt_top P_μ A)
      hf_meas.aestronglyMeasurable.restrict C
    exact ae_of_all _ (fun ω => by rw [Real.norm_eq_abs]; exact hC (shiftPath n ω))

  have hg_meas_pi : Measurable (markovExpectation S κ Y) :=
    measurable_markovExpectation S κ Y hY_meas ⟨C, hC⟩
  have hg_bdd : ∀ ω : ℕ → S, |markovExpectation S κ Y (ω n)| ≤ C := by
    intro ω
    simp only [markovExpectation]
    calc |∫ ω', Y ω' ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ|
        ≤ ∫ ω', |Y ω'| ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ :=
          by have := norm_integral_le_integral_norm (f := Y) (μ := MarkovChainPathMeasure S (Measure.dirac (ω n)) κ)
             rw [Real.norm_eq_abs] at this
             simp_rw [Real.norm_eq_abs] at this
             exact this
      _ ≤ ∫ _ : ℕ → S, C ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ :=
          integral_mono_of_nonneg (ae_of_all _ (fun _ => abs_nonneg _))
            (integrable_const C) (ae_of_all _ (fun ω' => hC ω'))
      _ = C := by rw [integral_const, smul_eq_mul, mul_comm]; simp
  have hg_int : IntegrableOn (fun ω => markovExpectation S κ Y (ω n)) A P_μ := by
    apply IntegrableOn.of_bound (measure_lt_top P_μ A)
      (hg_meas_pi.comp (measurable_pi_apply n)).aestronglyMeasurable.restrict C
    exact ae_of_all _ (fun ω => by rw [Real.norm_eq_abs]; exact hg_bdd ω)
  rw [hP_eq, Measure.comp_eq_comp_const_apply]
  have hP_eq' : P_μ = (K ∘ₖ Kernel.const Unit ν) () := by rw [hP_eq, Measure.comp_eq_comp_const_apply]
  rw [Kernel.setIntegral_comp hA_pi (hP_eq' ▸ hf_int),
      Kernel.setIntegral_comp hA_pi (hP_eq' ▸ hg_int)]
  congr 1


  ext x₀
  set_option maxHeartbeats 800000 in


  have hA_piLE : @MeasurableSet _ ((Filtration.piLE (X := fun _ : ℕ => S)).seq n) A := by
    apply (show pathFiltration S n ≤
      (Filtration.piLE (X := fun _ : ℕ => S)).seq n from ?_) _ hA
    apply iSup_le; intro i; apply iSup_le; intro hi
    simp only [Filtration.piLE]
    rw [show (fun (ω : ℕ → S) => ω i) = (fun x : {j : ℕ | j ≤ n} → S => x ⟨i, hi⟩) ∘
      Preorder.restrictLe n from rfl]
    rw [← MeasurableSpace.comap_comp]
    exact MeasurableSpace.comap_mono (measurable_pi_apply _).comap_le

  have hf_int_K : Integrable (Y ∘ shiftPath n) (K x₀) := by
    apply Integrable.of_bound hf_meas.aestronglyMeasurable C
    exact ae_of_all _ (fun ω => by rw [Real.norm_eq_abs]; exact hC (shiftPath n ω))

  have hcondExp := Kernel.condExp_traj (κ := κ') (X := fun _ : ℕ => S)
    (a := 0) (b := n) (Nat.zero_le n) (x₀ := x₀) (f := Y ∘ shiftPath n) hf_int_K


  have hinner : ∀ ω : ℕ → S,
      ∫ y, (Y ∘ shiftPath n) y ∂(Kernel.traj κ' n (Preorder.frestrictLe n ω)) =
      markovExpectation S κ Y (ω n) := by
    intro ω
    have := integral_shiftPath_traj_eq_markovExpectation S μ κ Y hY_meas ⟨C, hC⟩ n
      (Preorder.frestrictLe n ω)
    simp only [Function.comp_apply] at this ⊢
    rw [this]
    simp only [markovExpectation, Preorder.frestrictLe_apply]

  have hcondExp_eq : (K x₀)[Y ∘ shiftPath n | Filtration.piLE n] =ᵐ[K x₀]
      fun ω => markovExpectation S κ Y (ω n) := by
    exact hcondExp.trans (Filter.Eventually.of_forall hinner)


  have hpiLE_le : (Filtration.piLE (X := fun _ : ℕ => S)).seq n ≤ MeasurableSpace.pi :=
    (Filtration.piLE (X := fun _ : ℕ => S)).le' n
  rw [← setIntegral_condExp hpiLE_le hf_int_K hA_piLE]
  exact setIntegral_congr_ae hA_pi (hcondExp_eq.mono fun ω hω _ => hω)

/-- **Markov property** for a discrete-time Markov chain (conditional-expectation form).
For any bounded measurable path functional `Y` on `ℕ → S`,

  `E_μ[Y ∘ shiftPath n | pathFiltration n] = (ω ↦ E_{ω n} Y)`  `P_μ`-a.e.,

i.e. conditioning on the trajectory up to time `n` only depends on the value `ω n`, and the
conditional expectation of `Y(shiftPath n ·)` equals the expectation `E_{ω n} Y` of `Y`
under the chain restarted from `ω n`. -/
theorem markov_property_full
    (S : Type*) [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    (μ : Measure S) [IsFiniteMeasure μ]
    (κ : Kernel S S) [IsMarkovKernel κ]
    (Y : (ℕ → S) → ℝ)
    (hY_meas : @Measurable _ _ MeasurableSpace.pi _ Y)
    (hY_bdd : ∃ C : ℝ, ∀ ω, |Y ω| ≤ C)
    (n : ℕ) :
    let P_μ := MarkovChainPathMeasure S μ κ
    @condExp (ℕ → S) ℝ (pathFiltration S n)
      MeasurableSpace.pi _ _ _
      P_μ
      (Y ∘ shiftPath n)
    =ᵐ[P_μ]
      fun ω => markovExpectation S κ Y (ω n) := by
  intro P_μ


  set g := fun ω : ℕ → S => markovExpectation S κ Y (ω n) with hg_def
  set f := Y ∘ shiftPath n with hf_def
  have hle : pathFiltration S n ≤ MeasurableSpace.pi := (pathFiltration S).le' n

  obtain ⟨C, hC⟩ := hY_bdd
  have hf_bdd : ∀ ω, |f ω| ≤ C := fun ω => hC (shiftPath n ω)


  have hg_bdd : ∀ ω : ℕ → S, |g ω| ≤ C := by
    intro ω
    simp only [hg_def, markovExpectation]
    have : ‖∫ ω', Y ω' ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ‖ ≤
        ∫ ω', ‖Y ω'‖ ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ :=
      norm_integral_le_integral_norm _
    rw [Real.norm_eq_abs] at this
    simp_rw [Real.norm_eq_abs] at this
    calc |∫ ω', Y ω' ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ|
        ≤ ∫ ω', |Y ω'| ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ := this
      _ ≤ ∫ _ : ℕ → S, C ∂MarkovChainPathMeasure S (Measure.dirac (ω n)) κ := by
            apply integral_mono_of_nonneg
            · exact ae_of_all _ (fun ω' => abs_nonneg _)
            · exact integrable_const C
            · exact ae_of_all _ (fun ω' => hC ω')
      _ = C := by
            rw [integral_const, smul_eq_mul, mul_comm]
            simp


  have hf_sm : @Measurable _ _ MeasurableSpace.pi _ f := hY_meas.comp (measurable_shiftPath n)
  have hf_int : Integrable f P_μ := by
    apply Integrable.of_bound hf_sm.aestronglyMeasurable C
    exact ae_of_all _ (fun ω => by rw [Real.norm_eq_abs]; exact hf_bdd ω)

  have hg_meas_pi : Measurable (markovExpectation S κ Y) :=
    measurable_markovExpectation S κ Y hY_meas ⟨C, hC⟩

  have hn_meas : @Measurable _ _ (pathFiltration S n) _ (fun ω : ℕ → S => ω n) := by
    rw [measurable_iff_comap_le]
    exact le_iSup₂ (f := fun (i : ℕ) (_ : i ≤ n) =>
      MeasurableSpace.comap (fun (ω : ℕ → S) => ω i) ‹MeasurableSpace S›) n le_rfl
  have hg_meas : @Measurable _ _ (pathFiltration S n) _ g := hg_meas_pi.comp hn_meas
  have hg_aesm : AEStronglyMeasurable (m := pathFiltration S n) g P_μ :=
    hg_meas.aestronglyMeasurable


  have hg_int_finite : ∀ s, @MeasurableSet _ (pathFiltration S n) s → P_μ s < ⊤ →
      IntegrableOn g s P_μ := by
    intro s _ hs_lt
    apply IntegrableOn.of_bound hs_lt
      (hg_meas_pi.comp (measurable_pi_apply n)).aestronglyMeasurable.restrict C
    exact ae_of_all _ (fun ω => by rw [Real.norm_eq_abs]; exact hg_bdd ω)

  have hg_eq : ∀ s : Set (ℕ → S), @MeasurableSet _ (pathFiltration S n) s → P_μ s < ⊤ →
      ∫ x in s, g x ∂P_μ = ∫ x in s, f x ∂P_μ := by
    intro s hs _
    exact (markov_setIntegral_shift S μ κ Y hY_meas ⟨C, hC⟩ n s hs).symm
  exact (ae_eq_condExp_of_forall_setIntegral_eq hle hf_int hg_int_finite hg_eq hg_aesm).symm
