/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Probability.Kernel.MeasurableLIntegral
import Mathlib.MeasureTheory.Measure.GiryMonad
import Mathlib.MeasureTheory.Integral.Lebesgue.Map
import Mathlib.Data.Fin.VecNotation

open MeasureTheory ProbabilityTheory ENNReal Set

/-- The finite-dimensional distribution of a Markov chain with initial distribution `mu`
and transition kernel `kappa`. Concretely, `markovFDD mu kappa n A` computes the iterated
integral

  `∫_{A 0} ∫_{A 1} ⋯ ∫_{A n} 1 dκ(xₙ₋₁) ⋯ dκ(x₀) dμ`,

i.e. the probability that the chain visits the sets `A 0, A 1, …, A n` at consecutive
times. -/
noncomputable def markovFDD {S : Type*} [MeasurableSpace S]
    (mu : Measure S) (kappa : Kernel S S) : (n : Nat) -> (Fin (n + 1) -> Set S) -> ENNReal
  | 0, A => mu (A 0)
  | n + 1, A => ∫⁻ x in A 0, markovFDD (kappa x) kappa n (fun i => A i.succ) ∂mu

set_option maxHeartbeats 800000 in
/-- For each `n` and tuple of measurable sets `A`, the function
`x ↦ markovFDD (kappa x) kappa n A` is measurable in the starting state `x`. This is the
key regularity statement needed to integrate the FDDs against a starting distribution. -/
lemma markovFDD_measurable {S : Type*} [MeasurableSpace S]
    (kappa : Kernel S S) [IsMarkovKernel kappa]
    (n : Nat) (A : Fin (n + 1) -> Set S) (hA : forall i, MeasurableSet (A i)) :
    Measurable (fun x => markovFDD (kappa x) kappa n A) := by
  induction n with
  | zero => simp only [markovFDD]; exact Kernel.measurable_coe kappa (hA 0)
  | succ m ih =>
    simp only [markovFDD]
    show Measurable (fun x => ∫⁻ y in A 0, markovFDD (kappa y) kappa m (fun i => A i.succ) ∂(kappa x))
    have hg : Measurable (fun x => markovFDD (kappa x) kappa m (fun i => A i.succ)) :=
      ih (fun i => A i.succ) (fun i => hA i.succ)
    have : (fun x => ∫⁻ y in A 0, markovFDD (kappa y) kappa m (fun i => A i.succ) ∂(kappa x)) =
           (fun x => ∫⁻ y, (A 0).indicator
             (fun y => markovFDD (kappa y) kappa m (fun i => A i.succ)) y ∂(kappa x)) := by
      ext x; rw [← lintegral_indicator (hA 0)]
    rw [this]
    exact (Measurable.lintegral_kernel_prod_right ((hg.indicator (hA 0)).comp measurable_snd))

/-- The `σ`-algebra generated by `(X 0, …, X k)` is contained in the one generated by
`(X 0, …, X (k+1))`. In other words, the σ-algebras `σ(X 0, …, X k)` are monotone in `k`. -/
lemma comap_sigma_mono
    {Omega S : Type*} [MeasurableSpace Omega] [MeasurableSpace S]
    (X : Nat -> Omega -> S) (k : Nat) :
    MeasurableSpace.comap (fun omega => fun i : Fin (k + 1) => X i omega) MeasurableSpace.pi ≤
    MeasurableSpace.comap (fun omega => fun i : Fin (k + 2) => X i omega) MeasurableSpace.pi := by
  let phi : (Fin (k + 2) -> S) -> (Fin (k + 1) -> S) := fun f i => f (Fin.castSucc i)
  have hphi : @Measurable _ _ MeasurableSpace.pi MeasurableSpace.pi phi :=
    measurable_pi_lambda _ (fun i => measurable_pi_apply _)
  have h_factor : (fun omega => fun i : Fin (k + 1) => X (↑i) omega) =
      phi ∘ (fun omega => fun i : Fin (k + 2) => X (↑i) omega) := by
    ext omega i; simp [phi, Fin.castSucc]
  rw [h_factor, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono hphi.comap_le

/-- If `C` is measurable with respect to `σ(X 0, …, X k)` and `B` is a measurable subset of
the state space, then `C ∩ X (k+1)⁻¹ B` is measurable with respect to `σ(X 0, …, X (k+1))`. -/
lemma comap_inter_preimage
    {Omega S : Type*} [MeasurableSpace Omega] [MeasurableSpace S]
    (X : Nat -> Omega -> S) (k : Nat)
    (C : Set Omega) (B : Set S) (hB : MeasurableSet B)
    (hC : @MeasurableSet Omega (MeasurableSpace.comap
      (fun omega => fun i : Fin (k + 1) => X i omega) MeasurableSpace.pi) C) :
    @MeasurableSet Omega (MeasurableSpace.comap
      (fun omega => fun i : Fin (k + 2) => X i omega) MeasurableSpace.pi)
      (C ∩ X (k + 1) ⁻¹' B) := by
  exact MeasurableSet.inter (comap_sigma_mono X k C hC)
    (by rw [MeasurableSpace.measurableSet_comap]
        exact ⟨(fun f : Fin (k + 2) -> S => f ⟨k + 1, by omega⟩) ⁻¹' B,
          (measurable_pi_apply _) hB, by ext omega; simp⟩)

/-- Promotes the Markov property from indicator functions to general measurable functions:
under the Markov hypothesis on indicators of measurable sets, for every measurable
`f : S → ℝ≥0∞` and every set `C` measurable with respect to `σ(X 0, …, X k)`,
`∫_C f (X (k+1) ω) dP = ∫_C (∫ f dκ (X k ω)) dP`. -/
lemma lintegral_measurable_extension
    {Omega S : Type*} [MeasurableSpace Omega] [MeasurableSpace S]
    (P : Measure Omega) [IsProbabilityMeasure P]
    (X : Nat -> Omega -> S) (hmeas : forall i, Measurable (X i))
    (kappa : Kernel S S) [IsMarkovKernel kappa]
    (hmarkov : forall (k : Nat) (B : Set S), MeasurableSet B ->
      forall (C : Set Omega),
        @MeasurableSet Omega (MeasurableSpace.comap
          (fun omega => fun i : Fin (k + 1) => X i omega) MeasurableSpace.pi) C ->
        ∫⁻ omega in C, (X (k + 1) ⁻¹' B).indicator (fun _ => (1 : ENNReal)) omega ∂P =
        ∫⁻ omega in C, kappa (X k omega) B ∂P)
    (k : Nat) (C : Set Omega)
    (hC_comap : @MeasurableSet Omega (MeasurableSpace.comap
      (fun omega => fun i : Fin (k + 1) => X i omega) MeasurableSpace.pi) C)
    (f : S -> ENNReal) (hf : Measurable f) :
    ∫⁻ omega in C, f (X (k + 1) omega) ∂P = ∫⁻ omega in C, (∫⁻ y, f y ∂kappa (X k omega)) ∂P := by
  have h_eq : (P.restrict C).map (X (k + 1)) =
      ((P.restrict C).map (X k)).bind (fun x => kappa x) := by
    ext B hB
    rw [Measure.map_apply (hmeas (k + 1)) hB,
        Measure.bind_apply hB (Kernel.measurable kappa).aemeasurable,
        lintegral_map (Kernel.measurable_coe kappa hB) (hmeas k),
        Measure.restrict_apply (hmeas (k + 1) hB)]
    have h := hmarkov k B hB C hC_comap
    rw [lintegral_indicator ((hmeas (k + 1)) hB), setLIntegral_one,
        Measure.restrict_apply ((hmeas (k + 1)) hB)] at h
    exact h
  calc ∫⁻ omega in C, f (X (k + 1) omega) ∂P
      = ∫⁻ y, f y ∂((P.restrict C).map (X (k + 1))) := by
          rw [lintegral_map hf (hmeas (k + 1))]
    _ = ∫⁻ y, f y ∂(((P.restrict C).map (X k)).bind (fun x => kappa x)) := by
          rw [h_eq]
    _ = ∫⁻ x, (∫⁻ y, f y ∂kappa x) ∂((P.restrict C).map (X k)) := by
          rw [Measure.lintegral_bind (Kernel.measurable kappa).aemeasurable hf.aemeasurable]
    _ = ∫⁻ omega in C, (∫⁻ y, f y ∂kappa (X k omega)) ∂P := by
          rw [lintegral_map _ (hmeas k)]
          exact Measurable.lintegral_kernel_prod_right (hf.comp measurable_snd)

/-- Restriction–indicator identity used in the inductive step: integrating `f ∘ X` over
`C ∩ X⁻¹ A` is the same as integrating the indicator `A.indicator f ∘ X` over `C`. -/
lemma set_lintegral_inter_preimage
    {Omega S : Type*} [MeasurableSpace Omega] [MeasurableSpace S]
    (P : Measure Omega) (X : Omega -> S) (hX : Measurable X)
    (A : Set S) (hA : MeasurableSet A) (C : Set Omega)
    (f : S -> ENNReal) :
    ∫⁻ omega in C ∩ X ⁻¹' A, f (X omega) ∂P = ∫⁻ omega in C, A.indicator f (X omega) ∂P := by
  have : forall omega, A.indicator f (X omega) = (X ⁻¹' A).indicator (fun omega => f (X omega)) omega := fun _ => rfl
  simp_rw [this]
  rw [lintegral_indicator (hX hA), Measure.restrict_restrict (hX hA), inter_comm]

set_option maxHeartbeats 1600000 in
/-- Auxiliary form of the finite-dimensional distribution formula, allowing an arbitrary
"prefix" event `C` measurable with respect to `σ(X 0, …, X j)`. It states
`P(C ∩ ⋂_{i ≤ n} {X (j+1+i) ∈ A i}) = ∫_C markovFDD (κ (X j ω)) κ n A dP`,
i.e. conditioning on the past up to time `j`, the joint distribution of the next `n+1` steps
is given by `markovFDD` started from `X j ω`. -/
theorem markov_chain_fdd_aux
    {Omega S : Type*} [MeasurableSpace Omega] [MeasurableSpace S]
    (P : Measure Omega) [IsProbabilityMeasure P]
    (X : Nat -> Omega -> S) (hmeas : forall i, Measurable (X i))
    (kappa : Kernel S S) [IsMarkovKernel kappa]
    (hmarkov : forall (k : Nat) (B : Set S), MeasurableSet B ->
      forall (C : Set Omega),
        @MeasurableSet Omega (MeasurableSpace.comap
          (fun omega => fun i : Fin (k + 1) => X i omega) MeasurableSpace.pi) C ->
        ∫⁻ omega in C, (X (k + 1) ⁻¹' B).indicator (fun _ => (1 : ENNReal)) omega ∂P =
        ∫⁻ omega in C, kappa (X k omega) B ∂P)
    (n : Nat) (j : Nat)
    (A : Fin (n + 1) -> Set S) (hA : forall i, MeasurableSet (A i))
    (C : Set Omega) (hC_meas : MeasurableSet C)
    (hC_comap : @MeasurableSet Omega (MeasurableSpace.comap
      (fun omega => fun i : Fin (j + 1) => X i omega) MeasurableSpace.pi) C) :
    P (C ∩ ⋂ i : Fin (n + 1), X (j + 1 + ↑i) ⁻¹' A i) =
    ∫⁻ omega in C, markovFDD (kappa (X j omega)) kappa n A ∂P := by
  induction n generalizing j C with
  | zero =>
    simp only [markovFDD]
    have h_fin1 : ⋂ i : Fin 1, X (j + 1 + ↑i) ⁻¹' A i = X (j + 1) ⁻¹' A 0 := by
      ext omega; simp [Fin.forall_fin_one]
    rw [h_fin1]
    have h := hmarkov j (A 0) (hA 0) C hC_comap
    rw [lintegral_indicator (hmeas (j + 1) (hA 0)), setLIntegral_one,
        Measure.restrict_apply (hmeas (j + 1) (hA 0))] at h
    rw [inter_comm]; exact h
  | succ m ih =>
    have h_split : (⋂ i : Fin (m + 2), X (j + 1 + ↑i) ⁻¹' A i) =
        (X (j + 1) ⁻¹' A 0) ∩ (⋂ i : Fin (m + 1), X (j + 2 + ↑i) ⁻¹' A i.succ) := by
      ext omega
      simp only [mem_iInter, mem_inter_iff, mem_preimage]
      constructor
      · intro h
        exact ⟨by have := h 0; simp at this; exact this,
          fun i => by
            have := h i.succ; simp only [Fin.val_succ] at this
            convert this using 2; omega⟩
      · intro ⟨h0, hs⟩ i
        refine Fin.cases (by simpa using h0) (fun i => ?_) i
        simp only [Fin.val_succ]
        have := hs i; convert this using 2; omega
    rw [h_split, ← inter_assoc]
    set C' := C ∩ X (j + 1) ⁻¹' A 0
    have hC'_meas : MeasurableSet C' := hC_meas.inter (hmeas (j + 1) (hA 0))
    have hC'_comap : @MeasurableSet Omega (MeasurableSpace.comap
        (fun omega => fun i : Fin (j + 2) => X i omega) MeasurableSpace.pi) C' :=
      comap_inter_preimage X j C (A 0) (hA 0) hC_comap
    rw [ih (j + 1) (fun i => A i.succ) (fun i => hA i.succ) C' hC'_meas hC'_comap]
    simp only [markovFDD]
    set f := fun x => markovFDD (kappa x) kappa m (fun i => A i.succ) with hf_def
    have hf_meas : Measurable f := markovFDD_measurable kappa m _ (fun i => hA i.succ)
    rw [set_lintegral_inter_preimage P (X (j + 1)) (hmeas (j + 1)) (A 0) (hA 0) C f]
    rw [lintegral_measurable_extension P X hmeas kappa hmarkov j C hC_comap
      ((A 0).indicator f) (hf_meas.indicator (hA 0))]
    congr 1; ext omega
    rw [← lintegral_indicator (hA 0)]

set_option maxHeartbeats 1600000 in
/-- Finite-dimensional distributions of a Markov chain. If `X` is a sequence of random
variables with transition kernel `κ` (in the sense expressed by `hmarkov`), then for any
measurable sets `A 0, …, A n`,

  `P(⋂ i : Fin (n+1), {X i ∈ A i}) = markovFDD (P ∘ X 0⁻¹) κ n A`.

This is the standard formula expressing the law of `(X 0, …, X n)` as an iterated integral
against the initial distribution and the transition kernel. -/
theorem markov_chain_fdd
    {Omega S : Type*} [MeasurableSpace Omega] [MeasurableSpace S]
    (P : Measure Omega) [IsProbabilityMeasure P]
    (X : Nat -> Omega -> S) (hmeas : forall i, Measurable (X i))
    (kappa : Kernel S S) [IsMarkovKernel kappa]
    (n : Nat) (A : Fin (n + 1) -> Set S) (hA : forall i, MeasurableSet (A i))
    (hmarkov : forall (k : Nat) (B : Set S), MeasurableSet B ->
      forall (C : Set Omega),
        @MeasurableSet Omega (MeasurableSpace.comap
          (fun omega => fun i : Fin (k + 1) => X i omega) MeasurableSpace.pi) C ->
        ∫⁻ omega in C, (X (k + 1) ⁻¹' B).indicator (fun _ => (1 : ENNReal)) omega ∂P =
        ∫⁻ omega in C, kappa (X k omega) B ∂P) :
    P (⋂ i : Fin (n + 1), X i ⁻¹' A i) = markovFDD (P.map (X 0)) kappa n A := by
  induction n with
  | zero =>
    simp only [markovFDD]
    have h_fin1 : ⋂ i : Fin 1, X (↑i) ⁻¹' A i = X 0 ⁻¹' A 0 := by
      ext omega; simp [Fin.forall_fin_one]
    rw [h_fin1, ← Measure.map_apply (hmeas 0) (hA 0)]
  | succ m ih =>
    simp only [markovFDD]
    have h_split : (⋂ i : Fin (m + 2), X (↑i) ⁻¹' A i) =
        (X 0 ⁻¹' A 0) ∩ (⋂ i : Fin (m + 1), X (0 + 1 + ↑i) ⁻¹' A i.succ) := by
      ext omega
      simp only [mem_iInter, mem_inter_iff, mem_preimage]
      constructor
      · intro h
        exact ⟨by have := h 0; simp at this; exact this,
          fun i => by
            have := h i.succ; simp only [Fin.val_succ] at this
            convert this using 2; omega⟩
      · intro ⟨h0, hs⟩ i
        refine Fin.cases (by simpa using h0) (fun i => ?_) i
        simp only [Fin.val_succ]
        have := hs i; convert this using 2; omega
    rw [h_split]
    have hC_meas : MeasurableSet (X 0 ⁻¹' A 0) := hmeas 0 (hA 0)
    have hC_comap : @MeasurableSet Omega (MeasurableSpace.comap
        (fun omega => fun i : Fin 1 => X i omega) MeasurableSpace.pi) (X 0 ⁻¹' A 0) := by
      rw [MeasurableSpace.measurableSet_comap]
      exact ⟨(fun f : Fin 1 -> S => f 0) ⁻¹' A 0,
        (measurable_pi_apply _) (hA 0), by ext omega; simp⟩
    rw [markov_chain_fdd_aux P X hmeas kappa hmarkov m 0
      (fun i => A i.succ) (fun i => hA i.succ)
      (X 0 ⁻¹' A 0) hC_meas hC_comap]
    rw [← setLIntegral_map (hA 0)
      (markovFDD_measurable kappa m _ (fun i => hA i.succ)) (hmeas 0)]

/-- **Markov chain finite-dimensional distributions** (textbook statement).
If `X` is any Markov chain with initial distribution `μ = P ∘ (X 0)⁻¹` and transition
kernel `κ`, then the finite-dimensional probabilities are given by

  `P(X i ∈ A i, 0 ≤ i ≤ n) = ∫_{A 0} μ(dx₀) ∫_{A 1} κ(x₀, dx₁) ⋯ ∫_{A n} κ(x_{n-1}, dx_n)`.

This is the user-facing wrapper around `markov_chain_fdd`. -/
theorem markov_chain_finite_dimensional_distributions
    {Omega S : Type*} [MeasurableSpace Omega] [MeasurableSpace S]
    (P : Measure Omega) [IsProbabilityMeasure P]
    (X : Nat -> Omega -> S) (hmeas : forall i, Measurable (X i))
    (kappa : Kernel S S) [IsMarkovKernel kappa]
    (n : Nat) (A : Fin (n + 1) -> Set S) (hA : forall i, MeasurableSet (A i))
    (hmarkov : forall (k : Nat) (B : Set S), MeasurableSet B ->
      forall (C : Set Omega),
        @MeasurableSet Omega (MeasurableSpace.comap
          (fun omega => fun i : Fin (k + 1) => X i omega) MeasurableSpace.pi) C ->
        ∫⁻ omega in C, (X (k + 1) ⁻¹' B).indicator (fun _ => (1 : ENNReal)) omega ∂P =
        ∫⁻ omega in C, kappa (X k omega) B ∂P) :
    P (⋂ i : Fin (n + 1), X i ⁻¹' A i) = markovFDD (P.map (X 0)) kappa n A :=
  markov_chain_fdd P X hmeas kappa n A hA hmarkov
