/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.MeasureTheory.MeasurableSpace.Basic

open MeasurableSpace

/--
Measurability from generators (Lecture 3, "Defining random variables"):
a map `f : α → β` is measurable for the σ-algebra generated by a family
`S` of subsets of `β` if and only if `f ⁻¹' s` is measurable for every
`s ∈ S`. Equivalently, to check measurability it suffices to check it on a
generating family of the target σ-algebra.
-/
theorem measurability_from_generators {α β : Type*} [MeasurableSpace α] {S : Set (Set β)}
    {f : α → β} :
    @Measurable α β _ (generateFrom S) f ↔
    ∀ s ∈ S, MeasurableSet (f ⁻¹' s) := by
  constructor
  · intro hf s hs
    exact hf (measurableSet_generateFrom hs)
  · exact measurable_generateFrom
