/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.Probability.StrongLaw
import Mathlib.Probability.Independence.Basic
import Mathlib.Analysis.PSeries
import Mathlib.Topology.Algebra.InfiniteSum.Real

open MeasureTheory ProbabilityTheory Filter Set
open scoped ENNReal NNReal MeasureTheory

set_option linter.unusedSectionVars false

noncomputable section

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]

/-- The partial sum `S_n = ∑_{i < n} 1_{A_i}` of indicators of the first `n` events,
viewed as a real-valued random variable on `Ω`. -/
def partialSumIndicators (A : ℕ → Set Ω) (n : ℕ) : Ω → ℝ :=
  fun ω => ∑ i ∈ Finset.range n, (A i).indicator (1 : Ω → ℝ) ω

/-- Rewrite `partialSumIndicators A n` as the pointwise sum (function-valued sum) of the
individual indicator functions. -/
lemma partialSumIndicators_eq (A : ℕ → Set Ω) (n : ℕ) :
    partialSumIndicators A n = ∑ i ∈ Finset.range n, (A i).indicator (1 : Ω → ℝ) := by
  ext ω; simp only [partialSumIndicators, Finset.sum_apply]

/-- The σ-algebra generated by the indicator `1_s : Ω → ℝ` of a set `s` is contained in the
σ-algebra generated by the singleton family `{s}`. -/
lemma comap_indicator_one_le_generateFrom (s : Set Ω) :
    MeasurableSpace.comap (s.indicator (1 : Ω → ℝ)) Real.measurableSpace ≤
    MeasurableSpace.generateFrom {s} := by
  intro t ht
  rw [MeasurableSpace.measurableSet_comap] at ht
  obtain ⟨u, _, rfl⟩ := ht
  classical
  change MeasurableSet[MeasurableSpace.generateFrom {s}]
    ((s.indicator (fun _ => (1 : ℝ))) ⁻¹' u)
  rw [indicator_const_preimage_eq_union s u (1 : ℝ)]
  have hs : MeasurableSet[MeasurableSpace.generateFrom {s}] s :=
    MeasurableSpace.measurableSet_generateFrom (mem_singleton _)
  apply MeasurableSet.union
  · split_ifs
    · exact hs
    · exact @MeasurableSet.empty _ (MeasurableSpace.generateFrom {s})
  · split_ifs
    · exact hs.compl
    · exact @MeasurableSet.empty _ (MeasurableSpace.generateFrom {s})

/-- Independence of two sets implies independence of their real-valued indicator functions. -/
lemma indepFun_indicator_of_indepSet {s t : Set Ω} (h : IndepSet s t μ) :
    IndepFun (s.indicator (1 : Ω → ℝ)) (t.indicator (1 : Ω → ℝ)) μ := by
  rw [IndepFun, IndepSet] at *
  exact Kernel.indep_of_indep_of_le_left
    (Kernel.indep_of_indep_of_le_right h (comap_indicator_one_le_generateFrom t))
    (comap_indicator_one_le_generateFrom s)

/-- The indicator function `1_s` of a measurable set is in `L²` for any probability measure. -/
lemma memLp_indicator_one {s : Set Ω} (hs : MeasurableSet s) :
    MemLp (s.indicator (1 : Ω → ℝ)) 2 μ :=
  memLp_indicator_const 2 hs 1 (Or.inr (measure_ne_top μ s))

/-- The square of an indicator function equals the indicator function itself: `(1_s)² = 1_s`. -/
lemma indicator_one_sq (s : Set Ω) :
    s.indicator (1 : Ω → ℝ) ^ 2 = s.indicator 1 := by
  ext ω; simp only [Pi.pow_apply, indicator, Pi.one_apply]; split_ifs <;> ring

/-- The variance of the indicator of a measurable set is bounded by its probability:
`Var(1_s) = P(s)(1 - P(s)) ≤ P(s)`. -/
lemma variance_indicator_le {s : Set Ω} (hs : MeasurableSet s) :
    variance (s.indicator (1 : Ω → ℝ)) μ ≤ (μ s).toReal := by
  rw [variance_eq_sub (memLp_indicator_one hs)]
  rw [indicator_one_sq, integral_indicator_one hs, measureReal_def]
  linarith [sq_nonneg ((μ s).toReal)]

/-- The expected value `E[S_n] = ∑_{i < n} P(A_i)` of the partial sum of indicators. -/
theorem integral_partialSumIndicators
    (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i)) (n : ℕ) :
    ∫ ω, partialSumIndicators A n ω ∂μ =
    ∑ i ∈ Finset.range n, (μ (A i)).toReal := by
  simp only [partialSumIndicators]
  rw [integral_finset_sum _ (fun i _ => (memLp_indicator_one (hA i)).integrable one_le_two)]
  congr 1 with i
  rw [integral_indicator_one (hA i), measureReal_def]

/-- For pairwise independent events `A_i`, the variance of the partial sum of indicators
is bounded by its expectation: `Var(S_n) ≤ E[S_n]`. This follows from `Var(1_{A_i}) ≤ P(A_i)`
and the fact that pairwise independence makes covariances vanish. -/
theorem variance_partialSumIndicators_le
    (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    (hindep : Pairwise fun i j => IndepSet (A i) (A j) μ)
    (n : ℕ) :
    variance (partialSumIndicators A n) μ ≤
    integral μ (partialSumIndicators A n) := by

  rw [partialSumIndicators_eq]

  have hmem : ∀ i ∈ Finset.range n, MemLp ((A i).indicator (1 : Ω → ℝ)) 2 μ :=
    fun i _ => memLp_indicator_one (hA i)

  have hindepFun : (↑(Finset.range n) : Set ℕ).Pairwise
      fun i j => IndepFun ((A i).indicator (1 : Ω → ℝ)) ((A j).indicator (1 : Ω → ℝ)) μ :=
    fun _ _ _ _ hij => indepFun_indicator_of_indepSet (hindep hij)

  rw [IndepFun.variance_sum hmem hindepFun]

  show _ ≤ ∫ ω, (∑ i ∈ Finset.range n, (A i).indicator (1 : Ω → ℝ)) ω ∂μ
  simp_rw [Finset.sum_apply]
  rw [integral_finset_sum _ (fun i hi => (hmem i hi).integrable one_le_two)]

  apply Finset.sum_le_sum
  intro i _
  rw [integral_indicator_one (hA i), measureReal_def]
  exact variance_indicator_le (hA i)

/-- If `∑ P(A_n) = ∞`, then the expectations `E[S_n] = ∑_{i<n} P(A_i)` of the partial sums
tend to `∞`. -/
theorem ES_tendsto_atTop
    (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    (hsum : ∑' n, μ (A n) = ⊤) :
    Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop := by
  simp_rw [integral_partialSumIndicators A hA]
  have hnn : ∀ n, 0 ≤ (μ (A n)).toReal := fun _ => ENNReal.toReal_nonneg
  rw [← not_summable_iff_tendsto_nat_atTop_of_nonneg hnn]
  intro h
  have h1 : ∑' n, ENNReal.ofReal ((μ (A n)).toReal) < ⊤ := h.tsum_ofReal_lt_top
  simp_rw [ENNReal.ofReal_toReal (measure_ne_top μ (A _))] at h1
  exact absurd hsum (ne_of_lt h1)

/-- The map `n ↦ E[S_n]` is monotone since each summand `P(A_i)` is nonnegative. -/
theorem ES_mono (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i)) :
    Monotone (fun n => ∫ ω, partialSumIndicators A n ω ∂μ) := by
  intro m n hmn
  simp_rw [integral_partialSumIndicators A hA]
  exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.range_mono hmn)
    (fun _ _ _ => ENNReal.toReal_nonneg)

/-- Successive expectations differ by at most one: `E[S_{n+1}] - E[S_n] = P(A_n) ≤ 1`. -/
theorem ES_step_le_one (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i)) (n : ℕ) :
    ∫ ω, partialSumIndicators A (n + 1) ω ∂μ - ∫ ω, partialSumIndicators A n ω ∂μ ≤ 1 := by
  simp_rw [integral_partialSumIndicators A hA, Finset.sum_range_succ]
  ring_nf
  exact ENNReal.toReal_le_of_le_ofReal zero_le_one (ENNReal.ofReal_one ▸ prob_le_one)

/-- The subsequence `φ(k)` used in the proof of the pairwise-independent strong law: it
chooses the first index `n` such that `E[S_n] ≥ (k+1)²`. Because the spacing grows
quadratically, the Chebyshev tail bounds for `S_{φ(k)}/E[S_{φ(k)}]` are summable. -/
noncomputable def sllnSubseq {A : ℕ → Set Ω}
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop) : ℕ → ℕ :=
  fun k => Nat.find
    ((hES_top.eventually (Filter.eventually_ge_atTop (((k : ℝ) + 1) ^ 2))).exists)

/-- Defining property of `sllnSubseq`: at index `φ(k)` we have `E[S_{φ(k)}] ≥ (k+1)²`. -/
lemma sllnSubseq_spec {A : ℕ → Set Ω}
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop)
    (k : ℕ) :
    ((k : ℝ) + 1) ^ 2 ≤ ∫ ω, partialSumIndicators A (sllnSubseq hES_top k) ω ∂μ := by
  classical
  exact Nat.find_spec
    ((hES_top.eventually (Filter.eventually_ge_atTop (((k : ℝ) + 1) ^ 2))).exists)

/-- Every index `φ(k)` in the subsequence is strictly positive, because `E[S_0] = 0` cannot
reach `(k+1)² > 0`. -/
lemma sllnSubseq_pos {A : ℕ → Set Ω}
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop)
    (k : ℕ) : 0 < sllnSubseq hES_top k := by
  rw [Nat.pos_iff_ne_zero]
  intro h
  have h1 := sllnSubseq_spec hES_top k
  change sllnSubseq hES_top k = 0 at h
  rw [h] at h1
  have h2 : ∫ ω, partialSumIndicators A 0 ω ∂μ = 0 := by simp [partialSumIndicators]
  linarith [show 0 < ((k : ℝ) + 1) ^ 2 from by positivity]

/-- The subsequence `φ : ℕ → ℕ` is strictly monotone. -/
lemma sllnSubseq_strictMono {A : ℕ → Set Ω}
    (hA : ∀ i, MeasurableSet (A i))
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop) :
    StrictMono (sllnSubseq hES_top) := by
  classical
  intro k k' hkk'
  have hpos : 0 < sllnSubseq hES_top k := sllnSubseq_pos hES_top k
  obtain ⟨m, hm⟩ : ∃ m, sllnSubseq hES_top k = m + 1 :=
    ⟨sllnSubseq hES_top k - 1, (Nat.succ_pred_eq_of_pos hpos).symm⟩
  have hmin_m : ∫ ω, partialSumIndicators A m ω ∂μ < ((k : ℝ) + 1) ^ 2 :=
    not_le.mp (Nat.find_min _ (by omega : m < sllnSubseq hES_top k))
  have hub : ∫ ω, partialSumIndicators A (sllnSubseq hES_top k) ω ∂μ <
      ((k : ℝ) + 1) ^ 2 + 1 := by
    rw [hm]; linarith [ES_step_le_one (μ := μ) A hA m]
  have hthresh : ((k : ℝ) + 1) ^ 2 + 1 ≤ ((k' : ℝ) + 1) ^ 2 := by
    have : (k : ℝ) + 2 ≤ (k' : ℝ) + 1 := by exact_mod_cast Nat.add_le_add_right hkk' 1
    nlinarith
  have hlt : ∫ ω, partialSumIndicators A (sllnSubseq hES_top k) ω ∂μ <
      ((k' : ℝ) + 1) ^ 2 := by linarith
  by_contra hle
  push Not at hle
  have h_mono := ES_mono (μ := μ) A hA hle
  have h_spec := sllnSubseq_spec hES_top k'
  linarith

/-- The expectation `E[S_{φ(k)}]` along the subsequence is strictly positive (at least
`(k+1)² > 0`). -/
lemma ES_sllnSubseq_pos {A : ℕ → Set Ω}
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop)
    (k : ℕ) :
    0 < ∫ ω, partialSumIndicators A (sllnSubseq hES_top k) ω ∂μ := by
  have h := sllnSubseq_spec hES_top k
  have : 0 < ((k : ℝ) + 1) ^ 2 := by positivity
  linarith

/-- The partial-sum random variable `S_n` is in `L²`. -/
lemma memLp_partialSumIndicators (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i)) (n : ℕ) :
    MemLp (partialSumIndicators A n) 2 μ := by
  rw [partialSumIndicators_eq]
  exact memLp_finset_sum' _ (fun i _ => memLp_indicator_one (hA i))

/-- Almost sure convergence from quantitative tail bounds: if for every `m`, almost surely
`|f_k(ω) - a| < 1/(m+1)` eventually as `k → ∞`, then almost surely `f_k(ω) → a`. -/
lemma ae_tendsto_of_ae_eventually_abs_sub_lt
    {f : ℕ → Ω → ℝ} {a : ℝ}
    (h : ∀ m : ℕ, ∀ᵐ ω ∂μ, ∀ᶠ k in Filter.atTop, |f k ω - a| < 1 / ((m : ℝ) + 1)) :
    ∀ᵐ ω ∂μ, Filter.Tendsto (fun k => f k ω) Filter.atTop (nhds a) := by
  have h' : ∀ᵐ ω ∂μ, ∀ m : ℕ, ∀ᶠ k in Filter.atTop, |f k ω - a| < 1 / ((m : ℝ) + 1) := by
    rwa [ae_all_iff]
  filter_upwards [h'] with ω hω
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨m, hm⟩ := exists_nat_gt (1 / ε)
  have hm_pos : (0:ℝ) < (m : ℝ) + 1 := by positivity
  have hm1 : 1 / ((m : ℝ) + 1) < ε := by
    rw [div_lt_iff₀ hm_pos]
    have := (div_lt_iff₀ hε).mp hm
    linarith
  obtain ⟨N, hN⟩ := (hω m).exists_forall_of_atTop
  exact ⟨N, fun n hn => lt_trans (by rw [Real.dist_eq]; exact hN n hn) hm1⟩

/-- Chebyshev tail bound along the subsequence: the probability that
`|S_{φ(k)}/E[S_{φ(k)}] - 1| ≥ ε` is bounded by `1/(ε² (k+1)²)`. This is the summable estimate
used to conclude a.s. convergence along the subsequence. -/
lemma chebyshev_subseq_bound
    (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    (hindep : Pairwise fun i j => IndepSet (A i) (A j) μ)
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop)
    (ε : ℝ) (hε : 0 < ε) (k : ℕ) :
    μ {ω | ε ≤ |partialSumIndicators A (sllnSubseq hES_top k) ω /
            (∫ ω', partialSumIndicators A (sllnSubseq hES_top k) ω' ∂μ) - 1|} ≤
    ENNReal.ofReal (1 / (ε ^ 2 * ((k : ℝ) + 1) ^ 2)) := by
  set n := sllnSubseq hES_top k with hn_def
  set ESn := ∫ ω', partialSumIndicators A n ω' ∂μ with hESn_def
  have hESn_pos : 0 < ESn := ES_sllnSubseq_pos hES_top k
  have hESn_sq : ((k : ℝ) + 1) ^ 2 ≤ ESn := sllnSubseq_spec hES_top k
  have hsub : {ω | ε ≤ |partialSumIndicators A n ω / ESn - 1|} ⊆
      {ω | ε * ESn ≤ |partialSumIndicators A n ω - ESn|} := by
    intro ω hω
    simp only [mem_setOf_eq] at hω ⊢
    have key : partialSumIndicators A n ω / ESn - 1 =
        (partialSumIndicators A n ω - ESn) / ESn := by
      field_simp
    rw [key, abs_div, abs_of_pos hESn_pos] at hω
    have h1 : ε ≤ |partialSumIndicators A n ω - ESn| / ESn := hω
    exact le_of_le_of_eq (mul_le_mul_of_nonneg_right h1 hESn_pos.le)
      (div_mul_cancel₀ _ (ne_of_gt hESn_pos))
  have hc_pos : 0 < ε * ESn := mul_pos hε hESn_pos
  have hmemLp : MemLp (partialSumIndicators A n) 2 μ := memLp_partialSumIndicators A hA n
  have hcheb := meas_ge_le_variance_div_sq hmemLp hc_pos
  have hvar := variance_partialSumIndicators_le A hA hindep n
  calc μ {ω | ε ≤ |partialSumIndicators A n ω / ESn - 1|}
      ≤ μ {ω | ε * ESn ≤ |partialSumIndicators A n ω -
          ∫ x, partialSumIndicators A n x ∂μ|} := by
        apply measure_mono hsub
    _ ≤ ENNReal.ofReal (variance (partialSumIndicators A n) μ / (ε * ESn) ^ 2) := hcheb
    _ ≤ ENNReal.ofReal (ESn / (ε * ESn) ^ 2) := by
        apply ENNReal.ofReal_le_ofReal
        exact div_le_div_of_nonneg_right hvar (by positivity)
    _ = ENNReal.ofReal (1 / (ε ^ 2 * ESn)) := by
        congr 1
        have hESn_ne : ESn ≠ 0 := ne_of_gt hESn_pos
        have hε_ne : ε ≠ 0 := ne_of_gt hε
        field_simp
    _ ≤ ENNReal.ofReal (1 / (ε ^ 2 * ((k : ℝ) + 1) ^ 2)) := by
        apply ENNReal.ofReal_le_ofReal
        apply div_le_div_of_nonneg_left (by positivity) (by positivity)
        exact mul_le_mul_of_nonneg_left hESn_sq (by positivity)

/-- Summing the Chebyshev bounds along the subsequence gives a finite total measure, since
`∑ 1/(k+1)² < ∞`. This is the Borel-Cantelli input for the subsequence. -/
lemma summable_chebyshev_subseq
    (A : ℕ → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    (hindep : Pairwise fun i j => IndepSet (A i) (A j) μ)
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop)
    (ε : ℝ) (hε : 0 < ε) :
    ∑' k, μ {ω | ε ≤ |partialSumIndicators A (sllnSubseq hES_top k) ω /
            (∫ ω', partialSumIndicators A (sllnSubseq hES_top k) ω' ∂μ) - 1|} ≠ ⊤ := by
  apply ne_top_of_le_ne_top
  · have : ∑' (k : ℕ), ENNReal.ofReal (1 / (ε ^ 2 * ((k : ℝ) + 1) ^ 2)) < ⊤ := by
      have hsumm : Summable (fun k : ℕ => 1 / (ε ^ 2 * ((k : ℝ) + 1) ^ 2)) := by
        have hshift : Summable (fun n : ℕ => (1 : ℝ) / ((n : ℝ) + 1) ^ 2) := by
          have h2 := (Real.summable_nat_pow_inv (p := 2)).mpr (by norm_num : 1 < 2)
          have heq : (fun n : ℕ => (1 : ℝ) / ((n : ℝ) + 1) ^ 2) =
              (fun n : ℕ => ((n : ℝ) ^ 2)⁻¹) ∘ (· + 1) := by
            ext n; simp only [Function.comp, one_div]; push_cast; ring
          rw [heq]
          exact h2.comp_injective (fun a b hab => by omega)
        exact (Summable.mul_left (1 / ε ^ 2) hshift).congr (fun k => by
          have hε2 : ε ^ 2 ≠ 0 := by positivity
          have hk : ((k : ℝ) + 1) ^ 2 ≠ 0 := by positivity
          field_simp)
      exact hsumm.tsum_ofReal_lt_top
    exact this.ne
  · exact ENNReal.tsum_le_tsum (fun k =>
      chebyshev_subseq_bound A hA hindep hES_top ε hε k)

/-- Pointwise monotonicity of the partial sum process: for each `ω`, the map
`n ↦ S_n(ω)` is nondecreasing. -/
lemma partialSumIndicators_mono (A : ℕ → Set Ω) (ω : Ω) :
    Monotone (fun n => partialSumIndicators A n ω) := by
  intro m n hmn
  simp only [partialSumIndicators]
  apply Finset.sum_le_sum_of_subset_of_nonneg (Finset.range_mono hmn)
  intro i _ _
  exact Set.indicator_nonneg (fun _ _ => one_pos.le) ω

/-- The partial sum `S_n(ω) ≥ 0` since it is a sum of nonnegative indicators. -/
lemma partialSumIndicators_nonneg (A : ℕ → Set Ω) (n : ℕ) (ω : Ω) :
    0 ≤ partialSumIndicators A n ω := by
  simp only [partialSumIndicators]
  apply Finset.sum_nonneg
  intro i _
  exact Set.indicator_nonneg (fun _ _ => one_pos.le) ω

/-- For a strictly monotone sequence `φ : ℕ → ℕ` and any `n ≥ φ 0`, there exists `k` such that
`φ k ≤ n < φ (k+1)`. This "bracketing" is used to sandwich a general `n` between
two consecutive subsequence indices. -/
lemma exists_bracket_of_strictMono (φ : ℕ → ℕ) (hφ : StrictMono φ) (n : ℕ) (hn : φ 0 ≤ n) :
    ∃ k, φ k ≤ n ∧ n < φ (k + 1) := by
  have hid : ∀ k, k ≤ φ k := StrictMono.id_le hφ
  have hex : ∃ k, n < φ (k + 1) :=
    ⟨n, lt_of_lt_of_le (Nat.lt_succ_of_le le_rfl) (hid (n + 1))⟩
  set k := Nat.find hex with hk_def
  have hk_spec : n < φ (k + 1) := Nat.find_spec hex
  refine ⟨k, ?_, hk_spec⟩
  rcases Nat.eq_zero_or_pos k with hk0 | hk_pos
  · rw [hk0]; exact hn
  · have hk_pred : k - 1 < k := Nat.sub_lt hk_pos Nat.one_pos
    have hmm := Nat.find_min hex hk_pred
    push Not at hmm
    have hkk : k - 1 + 1 = k := Nat.succ_pred_eq_of_pos hk_pos
    rwa [hkk] at hmm

/-- Upper bound on `E[S_{φ(k)}]` by `(k+1)² + 1`, since the previous index `φ(k) - 1` fails
the threshold `(k+1)²` and the expectation grows by at most one per step. -/
lemma ES_sllnSubseq_upper_bound {A : ℕ → Set Ω}
    (hA : ∀ i, MeasurableSet (A i))
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop)
    (k : ℕ) :
    ∫ ω, partialSumIndicators A (sllnSubseq hES_top k) ω ∂μ < ((k : ℝ) + 1) ^ 2 + 1 := by
  classical
  have hpos : 0 < sllnSubseq hES_top k := sllnSubseq_pos hES_top k
  obtain ⟨m, hm⟩ : ∃ m, sllnSubseq hES_top k = m + 1 :=
    ⟨sllnSubseq hES_top k - 1, (Nat.succ_pred_eq_of_pos hpos).symm⟩
  have hmin_m : ∫ ω, partialSumIndicators A m ω ∂μ < ((k : ℝ) + 1) ^ 2 :=
    not_le.mp (Nat.find_min _ (by omega : m < sllnSubseq hES_top k))
  rw [hm]; linarith [ES_step_le_one (μ := μ) A hA m]

/-- The ratio `E[S_{φ(k+1)}] / E[S_{φ(k)}]` tends to `1` as `k → ∞`. This "slow growth"
property allows interpolation between the subsequence and the full sequence in the SLLN proof. -/
lemma ES_subseq_ratio_tendsto_one {A : ℕ → Set Ω}
    (hA : ∀ i, MeasurableSet (A i))
    (hES_top : Filter.Tendsto (fun n => ∫ ω, partialSumIndicators A n ω ∂μ)
      Filter.atTop Filter.atTop) :
    Filter.Tendsto
      (fun k => (∫ ω, partialSumIndicators A (sllnSubseq hES_top (k + 1)) ω ∂μ) /
                (∫ ω, partialSumIndicators A (sllnSubseq hES_top k) ω ∂μ))
      Filter.atTop (nhds 1) := by
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨K, hK⟩ := exists_nat_gt (4 / ε)
  refine ⟨K, fun k hk => ?_⟩
  rw [Real.dist_eq]
  set a := ∫ ω, partialSumIndicators A (sllnSubseq hES_top (k + 1)) ω ∂μ
  set b := ∫ ω, partialSumIndicators A (sllnSubseq hES_top k) ω ∂μ
  have hb_pos : 0 < b := ES_sllnSubseq_pos hES_top k
  have ha_pos : 0 < a := ES_sllnSubseq_pos hES_top (k + 1)
  have hb_sq : ((k : ℝ) + 1) ^ 2 ≤ b := sllnSubseq_spec hES_top k
  have ha_ub : a < ((k : ℝ) + 1 + 1) ^ 2 + 1 := by
    have := ES_sllnSubseq_upper_bound hA hES_top (k + 1)
    push_cast at this; linarith
  have hab : b ≤ a := ES_mono (μ := μ) A hA (le_of_lt (sllnSubseq_strictMono hA hES_top (Nat.lt_succ_of_le le_rfl)))
  have h_ge_one : 1 ≤ a / b := le_div_iff₀ hb_pos |>.mpr (by linarith)
  rw [abs_of_nonneg (by linarith)]
  have h_step : a / b - 1 = (a - b) / b := by
    rw [div_sub_one (ne_of_gt hb_pos)]
  rw [h_step]
  have h_diff : a - b < 2 * (k : ℝ) + 4 := by
    have hb_lb := sllnSubseq_spec hES_top k
    have : a < ((k : ℝ) + 2) ^ 2 + 1 := by push_cast at ha_ub ⊢; linarith
    nlinarith
  have hk1_pos : (0 : ℝ) < (k : ℝ) + 1 := by positivity
  calc (a - b) / b ≤ (a - b) / ((k : ℝ) + 1) ^ 2 :=
        div_le_div_of_nonneg_left (by linarith) (by positivity) hb_sq
    _ < (2 * (k : ℝ) + 4) / ((k : ℝ) + 1) ^ 2 :=
        div_lt_div_of_pos_right h_diff (by positivity)
    _ ≤ 4 / ((k : ℝ) + 1) := by
        rw [div_le_div_iff₀ (by positivity : (0 : ℝ) < ((k : ℝ) + 1) ^ 2) hk1_pos]
        nlinarith [sq_nonneg ((k : ℝ) + 1)]
    _ < ε := by
        rw [div_lt_iff₀ hk1_pos]
        have hK1 : (K : ℝ) ≤ (k : ℝ) := by exact_mod_cast hk
        have hK2 : 4 < (K : ℝ) * ε := by rwa [div_lt_iff₀ hε] at hK
        nlinarith

/-- **Pairwise-independent strong law for indicator sums** (Lecture 9): suppose
`A₁, A₂, …` are pairwise independent events with `∑ P(A_n) = ∞`, and write
`S_n = ∑_{i=1}^n 1_{A_i}`. Then the ratio `S_n / E[S_n]` tends almost surely to `1`. -/
theorem pairwise_indep_slln
    {A : ℕ → Set Ω}
    (hA_meas : ∀ n, MeasurableSet (A n))
    (hA_indep : Pairwise fun i j => IndepSet (A i) (A j) μ)
    (hA_sum : ∑' n, μ (A n) = ⊤) :
    ∀ᵐ ω ∂μ, Filter.Tendsto
      (fun n => (∑ i ∈ Finset.range n, (A i).indicator (1 : Ω → ℝ) ω) /
                (∑ i ∈ Finset.range n, (μ (A i)).toReal))
      Filter.atTop (nhds 1) := by
  suffices h : ∀ᵐ ω ∂μ, Filter.Tendsto
      (fun n => partialSumIndicators A n ω /
                ∫ ω', partialSumIndicators A n ω' ∂μ)
      Filter.atTop (nhds 1) by
    filter_upwards [h] with ω hω
    simp_rw [integral_partialSumIndicators A hA_meas] at hω
    exact hω
  have hES_top := ES_tendsto_atTop A hA_meas hA_sum
  have hES_mono := ES_mono (μ := μ) A hA_meas
  set φ := sllnSubseq hES_top
  have hφ_strict : StrictMono φ := sllnSubseq_strictMono hA_meas hES_top
  have hES_φ_pos : ∀ k, 0 < ∫ ω', partialSumIndicators A (φ k) ω' ∂μ :=
    fun k => ES_sllnSubseq_pos hES_top k
  have hρ := ES_subseq_ratio_tendsto_one hA_meas hES_top
  have hφ_ae : ∀ᵐ ω ∂μ, Filter.Tendsto
      (fun k => partialSumIndicators A (φ k) ω /
                ∫ ω', partialSumIndicators A (φ k) ω' ∂μ)
      Filter.atTop (nhds 1) := by
    apply ae_tendsto_of_ae_eventually_abs_sub_lt
    intro m
    have hε : (0 : ℝ) < 1 / ((m : ℝ) + 1) := by positivity
    have hfin := summable_chebyshev_subseq A hA_meas hA_indep hES_top _ hε
    filter_upwards [ae_eventually_notMem hfin] with ω hω
    exact hω.mono (fun k hk => not_le.mp hk)

  filter_upwards [hφ_ae] with ω hω_subseq
  rw [Metric.tendsto_atTop]
  intro ε hε
  set δ := min (ε / 4) (1 / 2) with hδ_def
  have hδ_pos : 0 < δ := lt_min (by linarith) (by norm_num)
  have hδ_le_half : δ ≤ 1 / 2 := min_le_right _ _
  have hδ_le_ε4 : δ ≤ ε / 4 := min_le_left _ _
  obtain ⟨K₁, hK₁⟩ := (Metric.tendsto_atTop.mp hω_subseq) δ hδ_pos
  obtain ⟨K₂, hK₂⟩ := (Metric.tendsto_atTop.mp hρ) δ hδ_pos
  set K := max K₁ K₂
  refine ⟨φ K, fun n hn => ?_⟩
  have hn0 : φ 0 ≤ n := le_trans (hφ_strict.monotone (Nat.zero_le K)) hn
  obtain ⟨k, hk_lb, hk_ub⟩ := exists_bracket_of_strictMono φ hφ_strict n hn0
  have hk_ge : K ≤ k := by
    by_contra hlt; push Not at hlt
    exact absurd (lt_of_lt_of_le hk_ub (hφ_strict.monotone hlt)) (not_lt.mpr hn)
  have h_rk : |partialSumIndicators A (φ k) ω /
      (∫ ω', partialSumIndicators A (φ k) ω' ∂μ) - 1| < δ := by
    rw [← Real.dist_eq]; exact hK₁ k (le_trans (le_max_left _ _) hk_ge)
  have h_rk1 : |partialSumIndicators A (φ (k + 1)) ω /
      (∫ ω', partialSumIndicators A (φ (k + 1)) ω' ∂μ) - 1| < δ := by
    rw [← Real.dist_eq]; exact hK₁ (k + 1) (by omega)
  have h_ρk : |(∫ ω', partialSumIndicators A (φ (k + 1)) ω' ∂μ) /
      (∫ ω', partialSumIndicators A (φ k) ω' ∂μ) - 1| < δ := by
    rw [← Real.dist_eq]; exact hK₂ k (le_trans (le_max_right _ _) hk_ge)
  have hEφk := hES_φ_pos k
  have hEφk1 := hES_φ_pos (k + 1)
  have hEn : 0 < ∫ ω', partialSumIndicators A n ω' ∂μ :=
    lt_of_lt_of_le hEφk (hES_mono hk_lb)
  have hSn_lb := partialSumIndicators_mono A ω hk_lb
  have hSn_ub := partialSumIndicators_mono A ω (le_of_lt hk_ub)
  have hEn_lb : ∫ ω', partialSumIndicators A (φ k) ω' ∂μ ≤
      ∫ ω', partialSumIndicators A n ω' ∂μ := hES_mono hk_lb
  have hEn_ub : ∫ ω', partialSumIndicators A n ω' ∂μ ≤
      ∫ ω', partialSumIndicators A (φ (k + 1)) ω' ∂μ := hES_mono (le_of_lt hk_ub)
  have hSφk_nn := partialSumIndicators_nonneg A (φ k) ω
  have hSn_nn := partialSumIndicators_nonneg A n ω
  set r₀ := partialSumIndicators A (φ k) ω / (∫ ω', partialSumIndicators A (φ k) ω' ∂μ)
  set r₁ := partialSumIndicators A (φ (k + 1)) ω / (∫ ω', partialSumIndicators A (φ (k + 1)) ω' ∂μ)
  set ρ := (∫ ω', partialSumIndicators A (φ (k + 1)) ω' ∂μ) / (∫ ω', partialSumIndicators A (φ k) ω' ∂μ)
  have hρ_pos : 0 < ρ := div_pos hEφk1 hEφk

  have hub_eq : partialSumIndicators A (φ (k + 1)) ω /
      (∫ ω', partialSumIndicators A (φ k) ω' ∂μ) = r₁ * ρ := by
    simp only [r₁, ρ]; field_simp
  have hlb_eq : partialSumIndicators A (φ k) ω /
      (∫ ω', partialSumIndicators A (φ (k + 1)) ω' ∂μ) = r₀ / ρ := by
    simp only [r₀, ρ]; field_simp

  have h_lower : r₀ / ρ ≤
      partialSumIndicators A n ω / (∫ ω', partialSumIndicators A n ω' ∂μ) := by
    rw [← hlb_eq]
    calc partialSumIndicators A (φ k) ω / (∫ ω', partialSumIndicators A (φ (k + 1)) ω' ∂μ)
        ≤ partialSumIndicators A (φ k) ω / (∫ ω', partialSumIndicators A n ω' ∂μ) :=
          div_le_div_of_nonneg_left hSφk_nn hEn hEn_ub
      _ ≤ partialSumIndicators A n ω / (∫ ω', partialSumIndicators A n ω' ∂μ) :=
          div_le_div_of_nonneg_right hSn_lb hEn.le
  have h_upper : partialSumIndicators A n ω /
      (∫ ω', partialSumIndicators A n ω' ∂μ) ≤ r₁ * ρ := by
    rw [← hub_eq]
    calc partialSumIndicators A n ω / (∫ ω', partialSumIndicators A n ω' ∂μ)
        ≤ partialSumIndicators A n ω / (∫ ω', partialSumIndicators A (φ k) ω' ∂μ) :=
          div_le_div_of_nonneg_left hSn_nn hEφk hEn_lb
      _ ≤ partialSumIndicators A (φ (k + 1)) ω / (∫ ω', partialSumIndicators A (φ k) ω' ∂μ) :=
          div_le_div_of_nonneg_right hSn_ub hEφk.le
  rw [Real.dist_eq]

  have hub_bound : |r₁ * ρ - 1| < ε := by
    have heq : r₁ * ρ - 1 = (r₁ - 1) * (ρ - 1) + (r₁ - 1) + (ρ - 1) := by ring
    rw [heq]
    have hδ_sq_bound : δ ^ 2 + 2 * δ < ε := by nlinarith [sq_nonneg (δ - 1/2)]
    calc |(r₁ - 1) * (ρ - 1) + (r₁ - 1) + (ρ - 1)|
        ≤ |(r₁ - 1) * (ρ - 1) + (r₁ - 1)| + |ρ - 1| := abs_add_le _ _
      _ ≤ (|(r₁ - 1) * (ρ - 1)| + |r₁ - 1|) + |ρ - 1| := by
          gcongr; exact abs_add_le _ _
      _ = |r₁ - 1| * |ρ - 1| + |r₁ - 1| + |ρ - 1| := by rw [abs_mul]
      _ < δ * δ + δ + δ := by
          have h1 : |r₁ - 1| * |ρ - 1| < δ * δ :=
            mul_lt_mul'' h_rk1 h_ρk (abs_nonneg _) (abs_nonneg _)
          linarith
      _ = δ ^ 2 + 2 * δ := by ring
      _ < ε := hδ_sq_bound

  have hlb_bound : |r₀ / ρ - 1| < ε := by
    have hρ_lb : 1 / 2 < ρ := by
      have := (abs_sub_lt_iff.mp h_ρk).2; linarith
    have h_eq : r₀ / ρ - 1 = (r₀ - ρ) / ρ := by
      rw [div_sub_one (ne_of_gt hρ_pos)]
    rw [h_eq, abs_div, abs_of_pos hρ_pos]
    have h_num : |r₀ - ρ| < 2 * δ := by
      have h1 : |r₀ - ρ| = |(r₀ - 1) - (ρ - 1)| := by ring_nf
      rw [h1]; exact (abs_sub _ _).trans_lt (by linarith)
    calc |r₀ - ρ| / ρ < 2 * δ / ρ :=
          div_lt_div_of_pos_right h_num hρ_pos
      _ ≤ 2 * δ / (1 / 2) :=
          div_le_div_of_nonneg_left (by linarith) (by linarith) (le_of_lt hρ_lb)
      _ = 4 * δ := by ring
      _ ≤ ε := by linarith

  set q := partialSumIndicators A n ω / (∫ ω', partialSumIndicators A n ω' ∂μ) with hq_def
  have hq_lb : 1 - ε < q := by
    have := (abs_sub_lt_iff.mp hlb_bound).2
    linarith
  have hq_ub : q < 1 + ε := by
    have := (abs_sub_lt_iff.mp hub_bound).1
    linarith
  rw [abs_sub_lt_iff]; exact ⟨by linarith, by linarith⟩

end
