/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.MeasureTheory.PiSystem

open MeasurableSpace Set

variable {α : Type*}

/-- **π-λ theorem** (Lecture 2, Dynkin's π-λ theorem): if `P` is a π-system and `L` is a
λ-system (Dynkin system) containing `P`, then `σ(P) ⊆ L`. Concretely, if `s` is measurable
with respect to the σ-algebra generated by a π-system `S`, and the Dynkin system `d`
contains every set in `S`, then `d` also contains `s`. -/
theorem pi_lambda_theorem {S : Set (Set α)} (hpi : IsPiSystem S)
    (d : DynkinSystem α) (hS : ∀ s ∈ S, d.Has s)
    {s : Set α} (hs : @MeasurableSet α (generateFrom S) s) : d.Has s := by
  have h_gen_le : DynkinSystem.generate S ≤ d := d.generate_le hS
  rw [DynkinSystem.generateFrom_eq hpi] at hs
  exact h_gen_le s hs
