/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
import Mathlib.MeasureTheory.MeasurableSpace.Pi
import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
import Mathlib.MeasureTheory.PiSystem
import Mathlib.Topology.Order.Basic
import Mathlib.Order.Filter.Basic
import Mathlib.Data.ENNReal.Basic
import Mathlib.Analysis.SpecificLimits.Basic

noncomputable section

open MeasureTheory MeasurableSpace Set

/-- The vertex of the rectangle `[a, b] ⊆ ℝᵈ` obtained by selecting the lower coordinate
`a i` for indices `i ∈ S` and the upper coordinate `b i` otherwise. Used to compute
inclusion–exclusion sums over all `2^d` vertices. -/
def rectangleVertex {d : ℕ} (a b : Fin d → ℝ) (S : Finset (Fin d)) : Fin d → ℝ :=
  fun i => if i ∈ S then a i else b i

/-- The alternating sum of `F` over the `2^d` vertices of the rectangle `(a, b]`. For a
distribution function `F` on `ℝᵈ`, this equals the mass `μ((a, b])` of the associated
measure (signed inclusion–exclusion). -/
def rectangleValue {d : ℕ} (F : (Fin d → ℝ) → ℝ) (a b : Fin d → ℝ) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, (-1 : ℝ) ^ S.card * F (rectangleVertex a b S)

/-- `F : ℝᵈ → ℝ` is coordinate-wise non-decreasing: for every coordinate `i`, fixing the
remaining coordinates and increasing the `i`-th argument does not decrease the value of `F`. -/
def IsCoordNonDecreasing {d : ℕ} (F : (Fin d → ℝ) → ℝ) : Prop :=
  ∀ (i : Fin d) (x : Fin d → ℝ) (y z : ℝ), y ≤ z →
    F (Function.update x i y) ≤ F (Function.update x i z)

/-- `F : ℝᵈ → ℝ` is coordinate-wise right continuous: in every coordinate `i`, with the
remaining coordinates fixed, `F` is right-continuous in the `i`-th argument. -/
def IsCoordRightContinuous {d : ℕ} (F : (Fin d → ℝ) → ℝ) : Prop :=
  ∀ (i : Fin d) (x : Fin d → ℝ),
    Filter.Tendsto (fun t => F (Function.update x i t))
      (nhdsWithin (x i) (Ici (x i))) (nhds (F x))

/-- `F` assigns a non-negative inclusion–exclusion value to every rectangle `(a, b]`
with `a ≤ b` coordinate-wise. This is the multivariate analogue of monotonicity of a CDF
and is needed for `F` to come from a measure. -/
def IsRectangleNonneg {d : ℕ} (F : (Fin d → ℝ) → ℝ) : Prop :=
  ∀ (a b : Fin d → ℝ), (∀ i, a i ≤ b i) → 0 ≤ rectangleValue F a b

namespace MeasureTheory

/-- The family of left-infinite intervals `{Iic n : n ∈ ℕ}` is a countable spanning
collection of `ℝ`: their union covers all of `ℝ`. -/
lemma Real.isCountablySpanning_range_Iic :
    IsCountablySpanning (range (Iic : ℝ → Set ℝ)) :=
  ⟨fun n => Iic (n : ℝ), fun n => mem_range.mpr ⟨n, rfl⟩, by
    ext x; simp only [Set.mem_iUnion, Set.mem_Iic, Set.mem_univ, iff_true]
    exact ⟨⌈x⌉₊, Nat.le_ceil x⟩⟩

/-- The Borel `σ`-algebra on `ℝ` is generated by the left-infinite intervals `Iic x` for
`x ∈ ℝ`. -/
lemma Real.generateFrom_range_Iic :
    generateFrom (range (Iic : ℝ → Set ℝ)) = (inferInstance : MeasurableSpace ℝ) :=
  (borel_eq_generateFrom_Iic ℝ).symm.trans BorelSpace.measurable_eq.symm

/-- The collection of `d`-dimensional boxes of the form `∏ᵢ Iic (aᵢ)` is a π-system in
`ℝᵈ`: finite intersections of such boxes are again of this form. -/
lemma isPiSystem_piIic (d : ℕ) :
    IsPiSystem (univ.pi '' univ.pi (fun _ : Fin d => range (Iic : ℝ → Set ℝ))) :=
  IsPiSystem.pi fun _ => isPiSystem_Iic

/-- The Borel `σ`-algebra on `ℝᵈ` is generated by `d`-dimensional boxes of the form
`∏ᵢ Iic (aᵢ)`. -/
lemma generateFrom_piIic (d : ℕ) :
    generateFrom (univ.pi '' univ.pi (fun _ : Fin d => range (Iic : ℝ → Set ℝ))) =
      (inferInstance : MeasurableSpace (Fin d → ℝ)) :=
  generateFrom_eq_pi
    (fun _ => Real.generateFrom_range_Iic)
    (fun _ => Real.isCountablySpanning_range_Iic)

/-- Two probability measures on `ℝᵈ` are equal whenever they agree on all left-closed
quadrants `Iic a = {x | x ≤ a}` for `a ∈ ℝᵈ`. This is the multivariate analogue of CDF
determining a probability measure. -/
theorem ProbabilityMeasure.ext_of_Iic (d : ℕ)
    (μ ν : Measure (Fin d → ℝ))
    [IsProbabilityMeasure μ] [IsProbabilityMeasure ν]
    (h : ∀ a : Fin d → ℝ, μ (Iic a) = ν (Iic a)) :
    μ = ν := by
  apply ext_of_generate_finite
    (univ.pi '' univ.pi (fun _ : Fin d => range (Iic : ℝ → Set ℝ)))
  ·
    exact (generateFrom_piIic d).symm
  ·
    exact isPiSystem_piIic d
  ·
    intro s hs
    obtain ⟨f, hf, rfl⟩ := hs
    choose a ha using fun i => hf i (Set.mem_univ i)
    have : univ.pi f = Iic a := by
      ext x; simp only [Set.mem_pi, Set.mem_univ, true_implies, Set.mem_Iic, Pi.le_def]
      exact forall_congr' fun i => by rw [← ha i]; simp [Set.mem_Iic]
    rw [this]; exact h a
  ·
    simp [measure_univ]

end MeasureTheory

/-- **Existence (Carathéodory extension)**. Given `F : ℝᵈ → ℝ` that is coordinate-wise
non-decreasing, coordinate-wise right-continuous, and assigns non-negative rectangle values,
there exists a Borel measure `μ` on `ℝᵈ` whose mass on each rectangle `(a, b]` equals
`rectangleValue F a b`. -/
theorem caratheodory_extension_rectangleFunction {d : ℕ}
    (F : (Fin d → ℝ) → ℝ)
    (hF_mono : IsCoordNonDecreasing F)
    (hF_rcont : IsCoordRightContinuous F)
    (hF_rect : IsRectangleNonneg F) :
    ∃ μ : MeasureTheory.Measure (Fin d → ℝ),
      ∀ (a b : Fin d → ℝ), (∀ i, a i ≤ b i) →
        μ (Set.univ.pi fun i => Set.Ioc (a i) (b i)) =
          ENNReal.ofReal (rectangleValue F a b) := by sorry

/-- The collection of nonempty bounded half-open intervals `(l, u]` in `ℝ`. Used as a
generating π-system for the Borel σ-algebra. -/
def C_Ioc_pi : Set (Set ℝ) := { S | ∃ l u, l < u ∧ Ioc l u = S }

/-- The family of nonempty bounded half-open intervals `(l, u]` is a π-system. -/
lemma isPiSystem_C_Ioc_pi : IsPiSystem C_Ioc_pi := by
  have := isPiSystem_Ioc_mem (univ : Set ℝ) univ
  simp only [mem_univ, true_and] at this; exact this

/-- The Borel `σ`-algebra on `ℝ` is generated by the family of nonempty bounded half-open
intervals `(l, u]`. -/
lemma generateFrom_C_Ioc_pi :
    generateFrom C_Ioc_pi = (inferInstance : MeasurableSpace ℝ) := by
  rw [show (inferInstance : MeasurableSpace ℝ) = borel ℝ from BorelSpace.measurable_eq]
  exact (borel_eq_generateFrom_Ioc ℝ).symm

/-- The family of nonempty bounded half-open intervals `(l, u]` is countably spanning:
e.g. the intervals `(-n-1, n+1]` for `n ∈ ℕ` cover `ℝ`. -/
lemma isCountablySpanning_C_Ioc_pi : IsCountablySpanning C_Ioc_pi := by
  refine ⟨fun n => Ioc (-(n : ℝ) - 1) (n + 1), ?_, ?_⟩
  · intro n; exact ⟨-(n : ℝ) - 1, n + 1, by linarith, rfl⟩
  · ext x; simp only [mem_iUnion, mem_Ioc, mem_univ, iff_true]
    obtain ⟨n, hn⟩ := exists_nat_gt (|x|)
    exact ⟨n, by linarith [neg_abs_le x], by linarith [le_abs_self x]⟩

/-- **Characterization of probability measures on `ℝᵈ`**. Given `F : ℝᵈ → ℝ` that is
coordinate-wise non-decreasing, coordinate-wise right-continuous, and rectangle-nonnegative,
there exists a *unique* Borel measure `μ` on `ℝᵈ` whose value on each finite rectangle
`(a, b]` is determined by the inclusion–exclusion `rectangleValue F a b`. -/
theorem exists_unique_borelMeasure_of_rectangleFunction {d : ℕ}
    (F : (Fin d → ℝ) → ℝ)
    (hF_mono : IsCoordNonDecreasing F)
    (hF_rcont : IsCoordRightContinuous F)
    (hF_rect : IsRectangleNonneg F) :
    ∃! μ : MeasureTheory.Measure (Fin d → ℝ),
      (∀ (a b : Fin d → ℝ), (∀ i, a i ≤ b i) →
        μ (Set.univ.pi fun i => Set.Ioc (a i) (b i)) =
          ENNReal.ofReal (rectangleValue F a b)) := by


  suffices huniq : ∀ (μ₁ μ₂ : MeasureTheory.Measure (Fin d → ℝ)),
      (∀ (a b : Fin d → ℝ), (∀ i, a i ≤ b i) →
        μ₁ (univ.pi fun i => Ioc (a i) (b i)) = ENNReal.ofReal (rectangleValue F a b)) →
      (∀ (a b : Fin d → ℝ), (∀ i, a i ≤ b i) →
        μ₂ (univ.pi fun i => Ioc (a i) (b i)) = ENNReal.ofReal (rectangleValue F a b)) →
      μ₁ = μ₂ by

    obtain ⟨μ, hμ⟩ : ∃ μ : MeasureTheory.Measure (Fin d → ℝ),
      ∀ (a b : Fin d → ℝ), (∀ i, a i ≤ b i) →
        μ (univ.pi fun i => Ioc (a i) (b i)) = ENNReal.ofReal (rectangleValue F a b) :=
      caratheodory_extension_rectangleFunction F hF_mono hF_rcont hF_rect
    exact ⟨μ, hμ, fun ν hν => huniq ν μ hν hμ⟩


  intro μ₁ μ₂ hμ₁ hμ₂
  apply MeasureTheory.Measure.ext_of_generateFrom_of_iUnion
    (univ.pi '' univ.pi (fun _ : Fin d => C_Ioc_pi))
    (fun n : ℕ => univ.pi (fun _ : Fin d => Ioc (-(n : ℝ) - 1) ((n : ℝ) + 1)))
  ·
    exact (generateFrom_eq_pi
      (fun _ => generateFrom_C_Ioc_pi) (fun _ => isCountablySpanning_C_Ioc_pi)).symm
  ·
    exact IsPiSystem.pi fun _ => isPiSystem_C_Ioc_pi
  ·
    ext x; simp only [mem_iUnion, mem_univ, iff_true]


    by_cases hd : d = 0
    · subst hd; exact ⟨0, fun i _ => Fin.elim0 i⟩
    · haveI : Nonempty (Fin d) := ⟨⟨0, Nat.pos_of_ne_zero hd⟩⟩

      have : ∃ n : ℕ, ∀ i : Fin d, |x i| < (n : ℝ) := by
        obtain ⟨n, hn⟩ := exists_nat_gt
          (Finset.univ.sup' Finset.univ_nonempty (fun i => |x i|))
        exact ⟨n, fun i => lt_of_le_of_lt (Finset.le_sup' (fun i => |x i|) (Finset.mem_univ i)) hn⟩
      obtain ⟨n, hn⟩ := this
      refine ⟨n, fun i _ => ?_⟩
      exact ⟨by linarith [neg_abs_le (x i), hn i], by linarith [le_abs_self (x i), hn i]⟩
  ·
    intro n
    exact ⟨fun _ => Ioc (-(n : ℝ) - 1) (n + 1),
      fun i _ => ⟨-(n : ℝ) - 1, n + 1, by linarith, rfl⟩, rfl⟩
  ·
    intro n
    rw [show univ.pi (fun _ : Fin d => Ioc (-(n : ℝ) - 1) ((n : ℝ) + 1)) =
      univ.pi (fun i : Fin d => Ioc ((fun _ => -(n : ℝ) - 1) i) ((fun _ => (n : ℝ) + 1) i))
      from rfl,
      hμ₁ _ _ (fun _ => by linarith)]
    exact ENNReal.ofReal_ne_top
  ·
    intro s hs
    obtain ⟨f, hf, rfl⟩ := hs
    choose a b hab hfab using fun i => hf i (mem_univ i)
    have heq : univ.pi f = univ.pi (fun i => Ioc (a i) (b i)) := by
      congr 1; funext i; exact (hfab i).symm
    rw [heq, hμ₁ a b (fun i => le_of_lt (hab i)), hμ₂ a b (fun i => le_of_lt (hab i))]
