/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.MeasureTheory.MeasurableSpace.Basic

open MeasurableSpace

variable {Ω : Type*}

/-- Given a sequence of σ-algebras `𝓐 i` on `Ω`, `tailMeasurableSpaceFrom 𝓐 n` is the σ-algebra
generated by `𝓐 i` for all `i ≥ n`, i.e. `σ(𝓐 n, 𝓐 (n+1), …)`. -/
@[reducible]
def tailMeasurableSpaceFrom (𝓐 : ℕ → MeasurableSpace Ω) (n : ℕ) : MeasurableSpace Ω :=
  ⨆ (i : ℕ) (_ : n ≤ i), 𝓐 i

/-- The **tail σ-algebra** of a sequence of σ-algebras `𝓐 i`, defined as
`𝓣 = ⋂ₙ σ(𝓐 n, 𝓐 (n+1), …)`. It contains the information observable by looking only at
events arbitrarily far into the future. -/
@[reducible]
def tailMeasurableSpace (𝓐 : ℕ → MeasurableSpace Ω) : MeasurableSpace Ω :=
  ⨅ n, tailMeasurableSpaceFrom 𝓐 n

/-- The tail σ-algebra of a sequence of random variables `X : ℕ → Ω → β`, defined as
`𝓣 = ⋂ₙ σ(X n, X (n+1), …)`. This is the standard tail σ-algebra appearing in Kolmogorov's
0-1 law. -/
abbrev tailMeasurableSpaceOfFun {β : Type*} [MeasurableSpace β] (X : ℕ → Ω → β) :
    MeasurableSpace Ω :=
  tailMeasurableSpace (fun n => MeasurableSpace.comap (X n) ‹_›)
