/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.GroupTheory.Coxeter.Basic
import Mathlib.GroupTheory.Coxeter.Length
import Mathlib.Tactic.Group

variable {B : Type*}

namespace CoxeterBruhat

/-- The set of reflections of a Coxeter system: all conjugates of simple
generators, $T = \{w s_i w^{-1} \mid w \in W,\ i \in B\}$. -/
def reflections {W : Type*} [Group W] (M : CoxeterMatrix B)
    (cs : CoxeterSystem M W) : Set W :=
  { t | ∃ (w : W) (i : B), t = w * cs.simple i * w⁻¹ }

/-- A single Bruhat step $v \to w$: there exists a reflection $t$ such that
$v t = w$ and $\ell(v) < \ell(w)$. -/
def BruhatStep {W : Type*} [Group W] {M : CoxeterMatrix B}
    (cs : CoxeterSystem M W) (v w : W) : Prop :=
  ∃ t ∈ reflections M cs, v * t = w ∧ cs.length v < cs.length w

/-- The Bruhat order $v \le w$, defined as the reflexive-transitive closure of
$\mathtt{BruhatStep}$. -/
def BruhatLE {W : Type*} [Group W] {M : CoxeterMatrix B}
    (cs : CoxeterSystem M W) : W → W → Prop :=
  Relation.ReflTransGen (BruhatStep cs)

/-- The standard parabolic subgroup $W_J$ generated by the simple reflections
indexed by $J \subseteq B$. -/
def parabolicSubgroup {W : Type*} [Group W] {M : CoxeterMatrix B}
    (cs : CoxeterSystem M W) (J : Finset B) : Subgroup W :=
  Subgroup.closure ((cs.simple '' ↑J) : Set W)

section Basics
variable {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- Simple reflections are involutions: $s_i \cdot s_i = 1$. -/
theorem simple_sq (i : B) : cs.simple i * cs.simple i = 1 := by
  have h := cs.simple_mul_simple_cancel_left (w := 1) i; rwa [mul_one] at h

/-- Simple reflections are self-inverse: $s_i^{-1} = s_i$. -/
theorem simple_inv (i : B) : (cs.simple i)⁻¹ = cs.simple i :=
  inv_eq_of_mul_eq_one_right (simple_sq cs i)

/-- Every reflection $t$ is an involution: $t \cdot t = 1$. -/
theorem reflection_sq {t : W} (ht : t ∈ reflections M cs) : t * t = 1 := by
  obtain ⟨w, i, rfl⟩ := ht
  have h1 : (w * cs.simple i * w⁻¹) * (w * cs.simple i * w⁻¹)
      = w * (cs.simple i * cs.simple i) * w⁻¹ := by group
  rw [h1, simple_sq cs i]; group

/-- Every reflection is self-inverse: $t^{-1} = t$. -/
theorem reflection_inv {t : W} (ht : t ∈ reflections M cs) : t⁻¹ = t :=
  inv_eq_of_mul_eq_one_right (reflection_sq cs ht)

/-- Each simple reflection $s_i$ is itself a reflection in the set $T$. -/
theorem simple_mem_reflections (i : B) : cs.simple i ∈ reflections M cs :=
  ⟨1, i, by simp⟩

/-- Reflections are closed under conjugation by simple reflections: if $t \in T$
then $s_i\, t\, s_i \in T$. -/
theorem simple_conj_reflection {t : W} (ht : t ∈ reflections M cs) (i : B) :
    cs.simple i * t * cs.simple i ∈ reflections M cs := by
  obtain ⟨w, j, rfl⟩ := ht
  refine ⟨cs.simple i * w, j, ?_⟩
  rw [mul_inv_rev, simple_inv cs i]; group

/-- Algebraic identity used in the lifting lemma: if $v t = w$ then
$(v s_i)(s_i t s_i) = w s_i$. -/
theorem mul_simple_conj_eq {v w : W} {t : W} (hvw : v * t = w) (i : B) :
    (v * cs.simple i) * (cs.simple i * t * cs.simple i) = w * cs.simple i := by
  have : v * cs.simple i * (cs.simple i * t * cs.simple i)
      = v * (cs.simple i * cs.simple i) * t * cs.simple i := by group
  rw [this, simple_sq cs i, mul_one, ← hvw]

/-- Multiplication by a reflection is reversible: if $a t = b$ for a reflection
$t$, then $b t = a$. -/
theorem mul_reflection_reverse {a b : W} {t : W} (ht : t ∈ reflections M cs)
    (h : a * t = b) : b * t = a := by
  rw [← h, mul_assoc, reflection_sq cs ht, mul_one]

end Basics

section Parity
variable {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- Every reflection has odd length. -/
theorem reflection_length_odd {t : W} (ht : t ∈ reflections M cs) :
    cs.length t % 2 = 1 := by
  obtain ⟨u, j, rfl⟩ := ht
  have h : cs.lengthParity (u * cs.simple j * u⁻¹) = Multiplicative.ofAdd 1 := by
    simp [map_mul, cs.lengthParity_simple, map_inv]
  rw [cs.lengthParity_eq_ofAdd_length] at h
  have h1 : (cs.length (u * cs.simple j * u⁻¹) : ZMod 2) = ((1 : ℕ) : ZMod 2) := by
    have := Multiplicative.ofAdd.injective h; simpa using this
  rwa [ZMod.natCast_eq_natCast_iff'] at h1

/-- Multiplying by a reflection flips the parity of the length: if $v t = w$
and $t \in T$, then $\ell(v)$ and $\ell(w)$ have opposite parities. -/
theorem length_parity_ne_of_mul_reflection {v w t : W}
    (ht : t ∈ reflections M cs) (hvw : v * t = w) :
    cs.length v % 2 ≠ cs.length w % 2 := by
  have h1 := cs.length_mul_mod_two v t; rw [hvw] at h1
  have h2 := reflection_length_odd cs ht; omega

end Parity

section BruhatBasics
variable {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- A Bruhat step strictly increases length: if $v \to w$ then
$\ell(v) < \ell(w)$. -/
theorem bruhatStep_length_lt {v w : W} (h : BruhatStep cs v w) :
    cs.length v < cs.length w := by
  obtain ⟨_, _, _, hlen⟩ := h; exact hlen

/-- The Bruhat order is compatible with length: $v \le w$ implies
$\ell(v) \le \ell(w)$. -/
theorem bruhatLE_length_le {v w : W} (h : BruhatLE cs v w) :
    cs.length v ≤ cs.length w := by
  induction h with
  | refl => exact Nat.le_refl _
  | @tail _ c _ hbc ih => exact le_of_lt (lt_of_le_of_lt ih (bruhatStep_length_lt cs hbc))

/-- Reflexivity of the Bruhat order. -/
theorem bruhatLE_refl (w : W) : BruhatLE cs w w := Relation.ReflTransGen.refl

/-- Transitivity of the Bruhat order. -/
theorem bruhatLE_trans {u v w : W} (h1 : BruhatLE cs u v) (h2 : BruhatLE cs v w) :
    BruhatLE cs u w := h1.trans h2

/-- A single Bruhat step witnesses the Bruhat-order inequality. -/
theorem bruhatLE_of_step {v w : W} (h : BruhatStep cs v w) : BruhatLE cs v w :=
  Relation.ReflTransGen.single h

/-- A right descent gives a Bruhat step: if $\ell(v s_i) < \ell(v)$ then
$v s_i \to v$ is a Bruhat step. -/
theorem bruhatStep_mul_simple_descent {v : W} (i : B)
    (h : cs.length (v * cs.simple i) < cs.length v) :
    BruhatStep cs (v * cs.simple i) v :=
  ⟨cs.simple i, simple_mem_reflections cs i,
   by rw [mul_assoc, simple_sq cs i, mul_one], h⟩

/-- Antisymmetry via length: if $v \le w$ and $\ell(v) = \ell(w)$, then
$v = w$. -/
theorem bruhatLE_eq_of_length_eq {v w : W} (h : BruhatLE cs v w)
    (hlen : cs.length v = cs.length w) : v = w := by
  induction h with
  | refl => rfl
  | @tail _ c _ hbc ih =>
    have hlen_bc := bruhatStep_length_lt cs hbc
    have hlen_vb := bruhatLE_length_le cs (by assumption)
    omega

end BruhatBasics

section StrongExchange
variable {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- The Strong Exchange Condition specialised to Bruhat covers: when $v < w$ is
a Bruhat cover via a reflection $t$ (i.e. $vt = w$ and $\ell(v)+1 = \ell(w)$)
and $i$ is a right descent of $w$ but not of $v$, then $v s_i = w$. -/
def StrongExchangeForBruhat
    {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W) : Prop :=
  ∀ (v w : W) (t : W), t ∈ reflections M cs → v * t = w →
    cs.length v + 1 = cs.length w → ∀ (i : B),
    ¬cs.IsRightDescent v i → cs.IsRightDescent w i →
    v * cs.simple i = w

end StrongExchange

section LiftingLemma
variable {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- Bruhat lifting lemma: given a Bruhat cover $v \to w$ via a reflection $t$,
if $i$ is not a right descent of $v$ and $v s_i \ne w$, then $i$ is not a right
descent of $w$ either, and $v s_i \to w s_i$ is a Bruhat step. -/
theorem bruhat_lifting_lemma
    (hSEC : StrongExchangeForBruhat cs)
    {v w : W} (t : W) (ht : t ∈ reflections M cs) (hvt : v * t = w)
    (hcover : cs.length v + 1 = cs.length w)
    (i : B) (hv_up : ¬cs.IsRightDescent v i) (hne : v * cs.simple i ≠ w) :
    ¬cs.IsRightDescent w i ∧ BruhatStep cs (v * cs.simple i) (w * cs.simple i) := by

  have hw_up : ¬cs.IsRightDescent w i := by
    intro hw_desc
    exact hne (hSEC v w t ht hvt hcover i hv_up hw_desc)
  constructor
  · exact hw_up
  ·
    rw [CoxeterSystem.not_isRightDescent_iff] at hv_up hw_up
    exact ⟨cs.simple i * t * cs.simple i,
           simple_conj_reflection cs ht i,
           mul_simple_conj_eq cs hvt i,
           by rw [hv_up, hw_up]; omega⟩

end LiftingLemma

section Proposition
variable {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- Right multiplication by a simple reflection on a Bruhat step: from
$v \to w$ one obtains either $v s_i \le w$ or $v s_i \le w s_i$ in the Bruhat
order. -/
theorem bruhatStep_right_mul
    (hSEC : StrongExchangeForBruhat cs)
    {v w : W} (hvw : BruhatStep cs v w) (i : B) :
    BruhatLE cs (v * cs.simple i) w ∨
    BruhatLE cs (v * cs.simple i) (w * cs.simple i) := by
  obtain ⟨t, ht, hvt, hlen⟩ := hvw

  by_cases hv : cs.IsRightDescent v i
  ·
    left
    exact (bruhatLE_of_step cs (bruhatStep_mul_simple_descent cs i hv)).trans
          (bruhatLE_of_step cs ⟨t, ht, hvt, hlen⟩)
  ·
    rw [CoxeterSystem.not_isRightDescent_iff] at hv

    by_cases hw : cs.IsRightDescent w i
    ·
      rw [cs.isRightDescent_iff] at hw

      have ht' : cs.simple i * t * cs.simple i ∈ reflections M cs :=
        simple_conj_reflection cs ht i
      have hvs_ws : (v * cs.simple i) * (cs.simple i * t * cs.simple i) =
          w * cs.simple i := mul_simple_conj_eq cs hvt i
      by_cases heq : v * cs.simple i = w
      ·
        left; rw [heq]; exact bruhatLE_refl cs w
      ·
        by_cases hgap : cs.length v + 1 = cs.length w
        ·
          exfalso
          exact heq (hSEC v w t ht hvt hgap i
            (by rwa [CoxeterSystem.not_isRightDescent_iff])
            (by rwa [cs.isRightDescent_iff]))
        ·
          have hparity := length_parity_ne_of_mul_reflection cs ht hvt

          have hgap' : cs.length w ≥ cs.length v + 3 := by omega

          have h_lt : cs.length (v * cs.simple i) < cs.length (w * cs.simple i) := by
            rw [hv]; omega
          right
          exact bruhatLE_of_step cs ⟨cs.simple i * t * cs.simple i, ht', hvs_ws, h_lt⟩
    ·
      rw [CoxeterSystem.not_isRightDescent_iff] at hw

      right
      have h_lt : cs.length (v * cs.simple i) < cs.length (w * cs.simple i) := by
        rw [hv, hw]; exact Nat.add_lt_add_right hlen 1
      exact bruhatLE_of_step cs
        ⟨cs.simple i * t * cs.simple i, simple_conj_reflection cs ht i,
         mul_simple_conj_eq cs hvt i, h_lt⟩

/-- Right multiplication compatibility with the Bruhat order: if $v \le w$ then
either $v s_i \le w$ or $v s_i \le w s_i$. -/
theorem bruhat_right_mul
    (hSEC : StrongExchangeForBruhat cs)
    {v w : W} (hvw : BruhatLE cs v w) (i : B) :
    BruhatLE cs (v * cs.simple i) w ∨
    BruhatLE cs (v * cs.simple i) (w * cs.simple i) := by
  induction hvw with
  | refl => right; exact bruhatLE_refl cs _
  | @tail b c _ hbc ih =>
    rcases ih with ih_left | ih_right
    ·
      left; exact ih_left.trans (bruhatLE_of_step cs hbc)
    ·
      rcases bruhatStep_right_mul cs hSEC hbc i with hbc_left | hbc_right
      · left; exact ih_right.trans hbc_left
      · right; exact ih_right.trans hbc_right

end Proposition

end CoxeterBruhat
