/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.Buildings.code.CoxeterGroup.CoxeterHomomorphism
import Mathlib.GroupTheory.Coxeter.Length

set_option linter.unusedSectionVars false

open CoxeterGroup

namespace CoxeterGroup

variable {B : Type*} [DecidableEq B] [Fintype B]

/-- For $t \neq s_0$, the geometric reflection $\sigma_t$ preserves the $s_0$-coordinate. -/
theorem sigma_preserves_coord (M : CoxeterMatrix B) (t s₀ : B) (hts : t ≠ s₀)
    (v : B → ℝ) : sigma M t v s₀ = v s₀ := by
  unfold sigma e
  simp [hts]

/-- The $s$-coordinate of the standard basis vector $\alpha_s$ equals $1$. -/
theorem e_self (s : B) : e (B := B) s s = (1 : ℝ) := by
  unfold e
  exact Pi.single_eq_same s 1

/-- Injectivity of $s \mapsto \sigma_s$: equality of two simple reflections in the
geometric representation forces equality of the simple generators. -/
theorem sigma_injective (M : CoxeterMatrix B) (s t : B)
    (h : sigma M s = sigma M t) : s = t := by
  by_contra hst
  have h1 : sigma M s (e s) s = -(e s s) := congr_fun (sigma_e_self M s) s
  have h2 : sigma M t (e s) s = e s s := sigma_preserves_coord M t s (Ne.symm hst) (e s)
  have h3 : sigma M s (e s) s = sigma M t (e s) s := congr_fun (congr_fun h (e s)) s
  rw [h1, h2] at h3
  rw [e_self] at h3
  linarith

end CoxeterGroup

namespace CoxeterSystem

open CoxeterGroup CoxeterMatrix

variable {B : Type*} [DecidableEq B] [Fintype B]
variable {W : Type*} [Group W]
variable {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- The map $s \mapsto s_W$ from $S$ into $W$ is injective. -/
theorem simple_injective : Function.Injective cs.simple := by
  intro s t hst
  have hrep_s := coxeterRepresentation_simple M cs s
  have hrep_t := coxeterRepresentation_simple M cs t
  have heq : coxeterRepresentation M cs (cs.simple s) =
      coxeterRepresentation M cs (cs.simple t) := by rw [hst]
  rw [hrep_s, hrep_t] at heq
  have hsigma : sigma M s = sigma M t := by
    ext v u
    have := congr_arg (fun (f : (B → ℝ) ≃ₗ[ℝ] (B → ℝ)) => f v u) heq
    simp only [sigmaLinearEquiv_apply] at this
    exact this
  exact sigma_injective M s t hsigma

/-- Compatibility of the Coxeter representation with multiplication:
$\rho(w_1 w_2) v = \rho(w_1)(\rho(w_2) v)$. -/
theorem coxRep_mul_apply (w₁ w₂ : W) (v : B → ℝ) :
    (coxeterRepresentation M cs (w₁ * w₂)) v =
    (coxeterRepresentation M cs w₁) ((coxeterRepresentation M cs w₂) v) := by
  have := map_mul (coxeterRepresentation M cs) w₁ w₂
  show (coxeterRepresentation M cs (w₁ * w₂)) v =
    (coxeterRepresentation M cs w₁) ((coxeterRepresentation M cs w₂) v)
  rw [this]
  rfl

/-- Positivity test for parabolic subgroups: if $s_0 \in S$ but $s_{0,W}$ lies in the
parabolic $W_{S'}$ generated by $\{s_W : s \in S'\}$, then $s_0 \in S'$. -/
theorem mem_of_simple_mem_closure (S' : Set B) (s₀ : B)
    (hs : cs.simple s₀ ∈ Subgroup.closure (cs.simple '' S')) :
    s₀ ∈ S' := by
  by_contra hns
  set ρ := coxeterRepresentation M cs

  have closure_preserves : ∀ w, w ∈ Subgroup.closure (cs.simple '' S') →
      ∀ v : B → ℝ, (ρ w) v s₀ = v s₀ := by
    intro w hw
    induction hw using Subgroup.closure_induction with
    | mem x hx =>
      obtain ⟨t, ht, rfl⟩ := hx
      intro v
      have hts : t ≠ s₀ := fun h => hns (h ▸ ht)
      change (ρ (cs.simple t)) v s₀ = v s₀
      rw [coxeterRepresentation_simple, sigmaLinearEquiv_apply]
      exact sigma_preserves_coord M t s₀ hts v
    | one =>
      intro v
      rw [map_one]
      rfl
    | mul a b _ _ iha ihb =>
      intro v
      rw [show (ρ (a * b)) v = (ρ a) ((ρ b) v) from coxRep_mul_apply cs a b v]
      rw [iha, ihb]
    | inv x _ ihx =>
      intro v

      have hcomp : (ρ x) ((ρ x⁻¹) v) = v := by
        have := coxRep_mul_apply cs x x⁻¹ v
        rw [mul_inv_cancel] at this
        rw [← this, map_one]
        rfl
      calc (ρ x⁻¹) v s₀ = (ρ x) ((ρ x⁻¹) v) s₀ := (ihx ((ρ x⁻¹) v)).symm
        _ = v s₀ := by rw [hcomp]

  have repr_preserves := closure_preserves (cs.simple s₀) hs (e s₀)
  have contra : (ρ (cs.simple s₀)) (e s₀) s₀ = -(e s₀ s₀) := by
    change (ρ (cs.simple s₀)) (e s₀) s₀ = _
    rw [coxeterRepresentation_simple, sigmaLinearEquiv_apply]
    exact congr_fun (sigma_e_self M s₀) s₀
  rw [contra] at repr_preserves
  rw [e_self] at repr_preserves
  linarith

/-- Parabolic subgroup injectivity: $S_1 \mapsto W_{S_1}$ is injective, i.e.
$W_{S_1} = W_{S_2} \Rightarrow S_1 = S_2$. -/
theorem parabolicSubgroup_injective (S₁ S₂ : Set B)
    (h : Subgroup.closure (cs.simple '' S₁) = Subgroup.closure (cs.simple '' S₂)) :
    S₁ = S₂ := by
  ext s
  constructor
  · intro hs
    exact cs.mem_of_simple_mem_closure S₂ s
      (h ▸ Subgroup.subset_closure ⟨s, hs, rfl⟩)
  · intro hs
    exact cs.mem_of_simple_mem_closure S₁ s
      (h ▸ Subgroup.subset_closure ⟨s, hs, rfl⟩)

end CoxeterSystem
