/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Mathlib.GroupTheory.Coxeter.Length
import Mathlib.Data.Set.Card

open Function Set

namespace CoxeterMatrix

variable {B : Type*}

/-- Restriction of a Coxeter matrix $M$ to a subset $T \subseteq B$, giving the Coxeter
matrix of the parabolic subsystem indexed by $T$. -/
def restrictToSet (M : CoxeterMatrix B) (T : Set B) : CoxeterMatrix T where
  M := Matrix.of fun (i j : T) => M i.val j.val
  isSymm := by
    ext ⟨i, _⟩ ⟨j, _⟩
    simp only [Matrix.of_apply, Matrix.transpose_apply]
    exact (M.symmetric i j).symm
  diagonal := by
    intro ⟨i, _⟩
    simp only [Matrix.of_apply]
    exact M.diagonal i
  off_diagonal := by
    intro ⟨i, _⟩ ⟨j, _⟩ h
    simp only [Matrix.of_apply]
    exact M.off_diagonal i j (fun heq => h (Subtype.ext heq))

end CoxeterMatrix

/-- Group-theoretic helper: any integer power of an involution $x$ (with $x^2 = 1$) is
either $1$ or $x$. -/
theorem zpow_eq_one_or_self_of_sq_eq_one {G : Type*} [Group G] {x : G}
    (h : x * x = 1) (n : ℤ) : x ^ n = 1 ∨ x ^ n = x := by
  have h_sq : x ^ (2 : ℤ) = 1 := by rw [zpow_ofNat, pow_two]; exact h
  rcases Int.even_or_odd n with ⟨k, rfl⟩ | ⟨k, rfl⟩
  · left
    rw [show k + k = 2 * k from by ring, zpow_mul, h_sq, one_zpow]
  · right
    rw [show 2 * k + 1 = 2 * k + 1 from rfl]
    rw [zpow_add, zpow_mul, h_sq, one_zpow, one_mul, zpow_one]

namespace CoxeterSystem

open CoxeterMatrix

variable {B : Type*} {W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

local prefix:100 "s" => cs.simple
local prefix:100 "ℓ" => cs.length

/-- Each simple reflection $s_i \in W$ is nontrivial, i.e. $s_i \neq 1$. -/
theorem simple_ne_one (i : B) : s i ≠ 1 := by
  intro h
  have h1 := cs.length_simple i
  rw [h, cs.length_one] at h1
  exact absurd h1 (by omega)

/-- Right-multiplying by a simple generator changes the element: $w \neq w \cdot s_i$. -/
theorem mul_simple_ne_self (w : W) (i : B) : w ≠ w * s i := by
  intro h
  have := cs.length_mul_simple_ne w i
  rw [← h] at this
  exact this rfl

/-- Parabolic subgroup $W_T \subseteq W$: the subgroup generated by the simple
reflections $\{s_i : i \in T\}$. -/
def parabolicSubgroup (T : Set B) : Subgroup W :=
  Subgroup.closure (cs.simple '' T)

/-- Monotonicity of parabolic subgroups: $T \subseteq T' \Rightarrow W_T \leq W_{T'}$. -/
theorem parabolicSubgroup_mono {T T' : Set B} (h : T ⊆ T') :
    cs.parabolicSubgroup T ≤ cs.parabolicSubgroup T' :=
  Subgroup.closure_mono (Set.image_mono h)

end CoxeterSystem
