/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Atlas.Buildings.code.ChamberComplex.Basic
import Mathlib.GroupTheory.Coxeter.Basic

variable {B : Type*} [DecidableEq B] [Fintype B]

namespace CoxeterComplex

omit [DecidableEq B] [Fintype B] in
/-- Two elements $w, w'$ of the Coxeter group $W$ are *chamber-adjacent* when $w \neq w'$ and
$w' = w \cdot s_i$ for some simple generator $s_i$. -/
def ChamberAdjacent (M : CoxeterMatrix B) (w w' : M.Group) : Prop :=
  w ≠ w' ∧ ∃ i : B, w' = w * M.toCoxeterSystem.simple i

omit [DecidableEq B] [Fintype B] in
/-- A list of group elements is a gallery in the Coxeter complex iff consecutive entries are
chamber-adjacent. -/
def IsGallery (M : CoxeterMatrix B) : List M.Group → Prop
  | [] => True
  | [_] => True
  | w :: w' :: rest => ChamberAdjacent M w w' ∧ IsGallery M (w' :: rest)

/-- A simplex in the Coxeter complex of $M$: a chamber representative $w \in W$ together with a
subset of simple generators determining the standard parabolic. -/
structure Simplex (M : CoxeterMatrix B) where
  rep : M.Group
  subset : Finset B

/-- Face relation between simplices: $\tau$ is a face of $\sigma$ when its index-set is contained
in $\sigma$'s and $\sigma^{-1}\tau$ lies in the parabolic subgroup generated by $\sigma$'s simples. -/
def Simplex.IsFaceOf (M : CoxeterMatrix B) (σ τ : Simplex M) : Prop :=
  τ.subset ⊆ σ.subset ∧
  ∃ g : M.Group, g = σ.rep⁻¹ * τ.rep ∧
    g ∈ Subgroup.closure ((M.toCoxeterSystem.simple '' (↑σ.subset : Set B)) : Set M.Group)

omit [DecidableEq B] [Fintype B] in
/-- Chamber adjacency is irreflexive: $w$ is never adjacent to itself. -/
theorem chamberAdjacent_irrefl (M : CoxeterMatrix B) (w : M.Group) :
    ¬ChamberAdjacent M w w :=
  fun ⟨h, _⟩ => h rfl

omit [DecidableEq B] [Fintype B] in
/-- The empty list is trivially a gallery. -/
theorem isGallery_nil (M : CoxeterMatrix B) : IsGallery M ([] : List M.Group) :=
  trivial

omit [DecidableEq B] [Fintype B] in
/-- A singleton list is trivially a gallery. -/
theorem isGallery_singleton (M : CoxeterMatrix B) (w : M.Group) :
    IsGallery M [w] :=
  trivial

omit [DecidableEq B] [Fintype B] in
/-- Destructor: a gallery of length $\geq 2$ decomposes as an adjacent first edge and a tail gallery. -/
theorem isGallery_cons (M : CoxeterMatrix B) (w w' : M.Group) (rest : List M.Group)
    (h : IsGallery M (w :: w' :: rest)) :
    ChamberAdjacent M w w' ∧ IsGallery M (w' :: rest) :=
  h

omit [DecidableEq B] [Fintype B] in
/-- Reflexivity of the face relation: every simplex is a face of itself. -/
theorem Simplex.isFaceOf_refl (M : CoxeterMatrix B) (σ : Simplex M) :
    σ.IsFaceOf M σ :=
  ⟨Finset.Subset.refl _, ⟨1, by simp, Subgroup.one_mem _⟩⟩

end CoxeterComplex
